### ISSUE TITLE
On Windows, exceptions thrown from RCPP modules bypass try(..., silent = TRUE)

### ISSUE THREAD

**Issue by venelin** [RcppCore/Rcpp#1001]
Hello, I am trying to find an answer to the following question:

What is the recommended way of handling exceptions thrown from C++ methods exported using RCPP_MODULEs?

I notice that these exceptions are handled differently on Windows vs Linux/Mac OSX systems. On Linux Mac OSX, it is possible to wrap the call to the C++ method in a try(..., silent = TRUE) and to examine whether the class of the result is a 'try-error'. On Windows, this mechanism seems to fail and the R-process crashes. The package PCMBaseCpp uses Rcpp modules and is compiled using a C++11 compiler with compiler options:
```

PKG_CXXFLAGS=$(SHLIB_OPENMP_CXXFLAGS) -DARMA_DONT_USE_OPENMP
PKG_LIBS=$(SHLIB_OPENMP_CXXFLAGS) $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS)

CXX_STD = CXX11
```

Below is an example code reproducing the problem (copied from [this issue](https://github.com/venelin/PCMBaseCpp/issues/1#issue-507813590)).

```
install.packages(c("TreeSim", "PCMBase", "PCMBaseCpp"))

library(TreeSim)
library(PCMBase)
library(PCMBaseCpp)

modelBM <- PCMBase::PCM(model = "BM", k = 1)
phyltree<-TreeSim::sim.bd.taxa(n=5,numbsim=1,lambda=1,mu=0)[[1]]
phyltree$root.edge<-NULL
mTraits<-matrix(0,ncol=1,nrow=5)
loglik_PCMBase<-PCMBase::PCMLik(t(mTraits), phyltree, modelBM)
loglik_PCMBase

# This line of code returns an object of class 'try-error' on
# Linux and Mac OSX, but crashes the R process on Windows:
loglik_PCMBaseCpp_PCMLik<-PCMBase::PCMLik(t(mTraits), phyltree, modelBM, metaI = PCMBaseCpp::PCMInfoCpp)

```

Here's an excerpt of the stack-trace (links pointing to lines of code on github).
[try()](https://github.com/venelin/PCMBase/blob/4c1a4f3b1ce8340b885ce7ce300a552f05621932/R/GaussianPCM.R#L374) --> 
...
[PCMBaseCpp::PCMLmr.PCMInfoCpp](https://github.com/venelin/PCMBaseCpp/blob/61659b9ada4c1adf0641b438eb7ad6401e6696de/R/Generic.R#L248) --> 
...
[SPLITT::TraversalSpecification::TraverseTree()](https://github.com/venelin/PCMBaseCpp/blob/61659b9ada4c1adf0641b438eb7ad6401e6696de/src/SPLITT.h#L582) --> 
...
[std::rethrow_exception()](https://github.com/venelin/PCMBaseCpp/blob/61659b9ada4c1adf0641b438eb7ad6401e6696de/src/SPLITT.h#L1863).

The C++ method TraverseTree is exported via an RCPP_MODULE defined [here](https://github.com/venelin/PCMBaseCpp/blob/61659b9ada4c1adf0641b438eb7ad6401e6696de/src/Rcpp.cpp#L477).

The `try(..., silent=TRUE)` statement is in the R-package PCMBase [here](https://github.com/venelin/PCMBase/blob/4c1a4f3b1ce8340b885ce7ce300a552f05621932/R/GaussianPCM.R#L374).

**Comment by eddelbuettel** [comment]
Didn't read all of this but I think the gist of it is that exception handling across shared libraries is difficult to impossible, as a long jumps, across OS.  So what you observed is ... all you can get.

**Comment by venelin** [comment]
Thanks.

**Comment by jjallaire** [comment]
It is indeed a known limitation that Rcpp module methods cannot `stop()` on Windows (as the crash you observed occurs). This is ultimately because of the fact that R links to libgcc statically (see https://stackoverflow.com/questions/2424836/exceptions-are-not-caught-in-gcc-program).

@eddelbuettel You may recall that we had to re-write Rcpp attributes entirely at the beginning. That was because of this issue (see https://stackoverflow.com/questions/2424836/exceptions-are-not-caught-in-gcc-program).

One possible piece of good news is that we did do the gymnastics in Rcpp attributes to work around this, so you could either: (1) Expose your underlying C++ code as a set of top-level R functions using attributes; and/or (2) Wrap those functions in an S4 ref class or R6 ref class to provide the user with object/reference semantics.

**Comment by venelin** [comment]
Thanks @jjallaire and @eddelbuettel for the quick replies! 

> (1) Expose your underlying C++ code as a set of top-level R functions using attributes; and/or
> (2) Wrap those functions in an S4 ref class or R6 ref class to provide the user with object/reference semantics.

I am not familiar with the above techniques, yet, I am not convinced that any of these would be easy to implement, because the package relies heavily on Rcpp modules, see e.g. [this code](https://github.com/venelin/PCMBaseCpp/blob/master/src/Rcpp.cpp). Therefore, I think the only feasible approach would be to handle the exceptions on the C++ level and return a valid object to R each time.

**Comment by eddelbuettel** [comment]
@jjallaire Much appreciate the follow-up and link.  Let's earmark this for a Rcpp FAQ addition as I have to add an entry for the upcoming 'no modules' and 'no rtti' options.  I'll draft a paragraph and have you check.  Deal?

**Comment by eddelbuettel** [comment]
> I think the only feasible approach would be to handle the exceptions on the C++ level and return a valid object to R each time.

Correct.  "Been there. done that".

**Comment by jjallaire** [comment]
Sounds good!

**Comment by eddelbuettel** [comment]
See #1009 for a start.
