### ISSUE TITLE
Issue with random numbers and R calls from C++

### ISSUE THREAD

**Issue by Enchufa2** [RcppCore/Rcpp#1013]
It may have something to do with #465, which was unresolved back in 2016:

```r
Rcpp::cppFunction("bool comp(Function fun) { return runif(1)[0] > as<double>(fun()); }")
set.seed(1)
sum(replicate(1e3, comp(function() runif(1, 0, 1))))
# 0
sum(replicate(1e3, comp(function() runif(1, 0.0001, 0.9999))))
# 481
```

This is very odd. I'm not sure what's happening here. I've spent hours debugging a package of mine due to a very strange behaviour that has to do with this, but I finally managed to get this simple example that only involves Rcpp. I don't have much energy left today to investigate further. Any help would be appreciated.

**Comment by Enchufa2** [comment]
It may also have something to do with #823 and associated issues.

And before I get the usual _calling R from C++ is not a good idea_, the package in question is [this one](https://r-simmer.org/), and calling R from C++ is the whole point, because it's a simulator and the user needs to be able to insert custom functions into the model.

**Comment by Enchufa2** [comment]
Equivalent reprex, but arguably more informative:

```r
Rcpp::cppFunction("bool comp(Function fun) { return runif(1)[0] == as<double>(fun()); }")
set.seed(1)
sum(replicate(1e3, comp(function() runif(1, 0, 1))))
# 1000
sum(replicate(1e3, comp(function() runif(1, 0.0001, 0.9999))))
# 0
```

**Comment by eddelbuettel** [comment]
I am not sure what else to add besides all that was said in #823:

- for normal use cases, Rcpp _does the right thing_ of setting/resetting RNGs so for standard calls from R to C++ to R you get the same streams in _either_ R or C++; this is important
- when you do something else, for whichever reason, you have to be careful -- that was the Shiny use case in #823, it may be yours here.
- the PR #825 made changes
- we also always had the ability to say `Rcpp::export(rng=false)` if you want things to be left alone
- similarly, you could use Rcpp and not use our interface generator if they don't suit you

Hope this helps. I understand your simulator framework may have very special needs.  But there are also 1830 other packages using Rcpp and they do just fine.

**Comment by Enchufa2** [comment]
I understand, and I understand that this is not a *normal* case, statistically speaking; but it is definitely a valid case.

The thing is,

- I'm not sure whether I fully understand why this happens. Rcpp continues the RNG stream and then restores it, and that's why I get the same number?
- Is there any simple workaround using the functions to get/set the RNG state?
- I suppose, then, that if I call the R function `stats::runif` from Rcpp, instead of `Rcpp::runif`, I will get two different numbers, because Rcpp will restore/set, restore/set the RNG state for both R calls.
- I'm not sure whether I fully understand the implications of setting `Rcpp::export(rng=false)`. Does this mean that the random stuff called from C++ will continue the RNG stream when coming from R and the other way around?

**Comment by Enchufa2** [comment]
BTW, the same example with `Rcpp::export(rng=false)` returns exactly the same, so I'm even more confused than before. :(

**Comment by Enchufa2** [comment]
And:

```r
Rcpp::cppFunction(
  "bool comp(Function fun) {
    double x = as<double>(fun());
    return runif(1)[0] == x;
  }")
set.seed(1)
sum(replicate(1e3, comp(function() runif(1, 0, 1))))
# 0
sum(replicate(1e3, comp(function() runif(1, 0.0001, 0.9999))))
# 0
```

seems to work just ok (well, just as I expected at the very least).

**Comment by eddelbuettel** [comment]
Maybe your use case requires not using our `as<>()` and `wrap()`.  They are offered as a courtesy, if they don't work for you (in the _very special cases of repeatedly crossing the R/C++ border_) then maybe you either need to help us debug _why_, or not use them.

**Comment by eddelbuettel** [comment]
It would also help if you could restrict yourself to maybe one post at time.  These can be edited.  I am not sure how I am going this thread up with the parallel questions from you. 

The base use of RNGs is described in our intro paper shipped as a vignette.  We ensure we have the same streams _in normal use cases_.  You construct a non-normal use case.  Things break.  Sorry.  But that did not disprove the normal use case.

**Comment by Enchufa2** [comment]
Ok, sorry, one question at a time. Here's an important one: how calling `as<>()` inline makes any difference? E.g.,

```r
Rcpp::cppFunction(
  "bool comp(Function fun) {
    double x = as<double>(fun());
    return runif(1)[0] == x;
  }")
set.seed(1)
sum(replicate(1e3, comp(function() runif(1, 0, 1))))
# 0
sum(replicate(1e3, comp(function() runif(1, 0.0001, 0.9999))))
# 0
```

but

```r
Rcpp::cppFunction(
  "bool comp(Function fun) {
    return runif(1)[0] == as<double>(fun());
  }")
set.seed(1)
sum(replicate(1e3, comp(function() runif(1, 0, 1))))
# 1000
sum(replicate(1e3, comp(function() runif(1, 0.0001, 0.9999))))
# 0
```

**Comment by eddelbuettel** [comment]
Well it is TMP so other code is involved.  My first instinct would be to try a counter example.  Do all you are doing with the C API of R.  Then add Rcpp one feature and see where it breaks.  

Also, I am not sure how often I have to repeat this:  Your function `comp()`, being passed back and forth 1e3 times via replicate, is not really what our setup was built for.  I understand you are very frustrated, but if you step back a just a bit maybe you can see that you are constructing a special case.  Which as it turns out is not covered.   Which we knew already.

**Comment by Enchufa2** [comment]
Sorry, TMP?

`replicate` has nothing to do with this. In a simple call, without `replicate` the issue is the same.

**Comment by eddelbuettel** [comment]
Sorry, TMP is [template meta-programming](https://en.wikipedia.org/wiki/Template_metaprogramming).

**Comment by romainfrancois** [comment]
@Enchufa2 the difference is the order in which the various `runif()` are called, i.e. if you save the result of `fun()` in an object before calling `as<>` you'll see that `as<>` does not affect the result: 

``` r
library(Rcpp)

Rcpp::cppFunction(
  "bool comp1(Function fun) {
    Rcpp::Shield<SEXP> res(fun());
    double x = as<double>(res);
    return runif(1)[0] == x;
  }")
set.seed(1)
sum(replicate(1e3, comp1(function() runif(1, 0, 1))))
#> [1] 0
sum(replicate(1e3, comp1(function() runif(1, 0.0001, 0.9999))))
#> [1] 0

Rcpp::cppFunction(
  "bool comp2(Function fun) {
    Rcpp::Shield<SEXP> res(fun());
    return runif(1)[0] == as<double>(res);
  }")
set.seed(1)
sum(replicate(1e3, comp2(function() runif(1, 0, 1))))
#> [1] 0
sum(replicate(1e3, comp2(function() runif(1, 0.0001, 0.9999))))
#> [1] 0
```

<sup>Created on 2019-11-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by eddelbuettel** [comment]
Nice work.  I wanted to convert his example to just doing (scalar) `SEXP` which is close in spirit, but I didn't think about the various "concurrent" transformations happening when the `return` object is computed in (what was in his case a compound expression).  Also interesting that `comp2` works that way via the protection.

**Comment by Enchufa2** [comment]
Thanks, @romainfrancois. It's clear from your example that this has nothing to do with `as<>()`, so I renamed the issue.

Still, the difference due to the call order seems weird to me. I have to think about it and play around a little bit more.

In the meantime, question: does the R function call involve any RNG state change?

**Comment by eddelbuettel** [comment]
I would think the discussion in #823 plus the changes by @kevinushey from June 2018 in #862 are your best starting points.

**Comment by Enchufa2** [comment]
I went through #823 and several more threads referenced there and it's not clear to me at all in which point we exactly are here.

What I think I understood correctly is that, whenever you call an R function from C++, if this R function call e.g. `runif`, then the RNG state is updated. So, this

```r
Rcpp::cppFunction(
  "bool comp1(Function fun) {
    double x = runif(1)[0];
    double y = as<double>(fun());
    return x == y;
  }")
comp1(function() runif(1))

Rcpp::cppFunction(
  "bool comp2(Function fun) {
    GetRNGstate();
    double x = runif(1)[0];
    PutRNGstate();
    double y = as<double>(fun());
    return x == y;
  }")
comp2(function() runif(1))
```

means that `Rcpp::runif` is **not** handling correctly the RNG state, right? Wasn't the whole point of the sugar functions to do this automatically? (Maybe not and I'm just overloaded with so many discussions around this navigating these threads).

**Comment by eddelbuettel** [comment]
Did you look at #862 and `SuspendRNGSynchronizationScope` ?  I have the feeling we are going in circles here.

**Comment by Enchufa2** [comment]
As far as I understand, it is not. What I'm saying is that the call to `Rcpp::runif` behaves *as if the synchronization was suspended*, right? (i.e., *not* calling to `GetRNGstate` and `PutRNGstate`, unless I understood the opposite). And I don't want that, because in that case I obtain the same random number (`comp1` above). Instead, I was expecting the behaviour in `comp2`.

**Comment by kevinushey** [comment]
I'm a bit hazy on the details, but IIRC the underlying issue is that
separate copies of the RNG state (the seed) are maintained both at the C
level and R level, and whenever you switch between these contexts, you need
to call GetRNGstate() / PutRNGstate() as appropriate to synchronize these
states.

Rcpp tries to do this for you with RNGScope (assuming you will do all your
random number generation in the C world), but if you break that contract
and start performing R-level random number generation, you typically need
to manually manage the RNG state.

In theory, we could modify Rcpp::Function to do this synchronization for
the user as well, but I'm almost certain that this might break something.

**Comment by kevinushey** [comment]
Sorry, the above respond was formed before I saw the thread had been updated with further comments (thanks slow e-mail)

**Comment by eddelbuettel** [comment]
@Enchufa2 What about a different approach? Maybe it would just be easier if you maintained your own RNG for simmer? Then what we do (and which, if I may, serves most users) will not get in your way.  There are a number of good RNGs you could use, including some that are capable of parallel streams.

**Comment by Enchufa2** [comment]
> @Enchufa2 What about a different approach? Maybe it would just be easier if you maintained your own RNG for simmer? Then what we do (and which, if I may, serves most users) will not get in your way. There are a number of good RNGs you could use, including some that are capable of parallel streams.

Excellent suggestion. That's something I definitely need to consider, but it takes time. For the time being, I want to get this right and solve the issue without breaking changes.

Am I safe if I just call `GetRNGstate` and `PutRNGstate` around any call to `Rcpp::runif` and the like, as in the `comp2` example above? Or do I need to get/put the RNG state also around calls to R functions?

**Comment by eddelbuettel** [comment]
> Am I safe if I just call GetRNGstate and PutRNGstate around any call to Rcpp::runif and the like

I don't think so, and the issue is, as @kevinushey alluded to, a wee bit more complicated.  But I think we all feel that the issue _you_ see here is particular to _your_ usage pattern for your simulation driver, and the suggestion solutions follows the old _doctor, doctor, it hurts when I do this..._ pattern of just not doing _this_.  Happy to help with a distinct RNG; the [RcppZiggurat]() code can help as it is a) small and simple and _fast_ and b) _all_ its statefulness is embedded in the created  instance.  There are lots of other nice RNGs too.

**Comment by Enchufa2** [comment]
Thanks for the pointers and the discussion.

Anyway, I still don't see how my use case is essentially different from the usual one, or how it could make things more complicated in respect of preserving the RNG state: the usual case is a bunch of R computations that sporadically call some C++ code to speed something up; my case is a bunch of C++ computations that sporadically call some R code to get inputs from the user.

FYI, I've defined a couple RNGScope objects here and there wherever I need some random numbers in the C++ side, and everything seems to work as expected so far.

**Comment by kevinushey** [comment]
Rcpp uses RNGScopes to manage the seed state when going from the R -> C++ worlds, and does this automatically e.g. for functions with attributes-generated wrappers.

We don't do any similar state management for functions which go back the other way, from C++ -> R. Hence, if you're invoking R functions that use the R random number generator from the C++ side, the onus is on you to manage that state.

I believe in theory we _could_ fix this (with a similar but inverted RNGScope object for RFunction invocations) but this may break some things.

If you wanted to trial a fix, you could try inserting calls like:

```
PutRNGstate();
// do stuff in R
GetRNGstate();
```

to see if that helps.

**Comment by Enchufa2** [comment]
Thanks, @kevinushey. Yes, I believe that your approach is the most general one. But since my C++ code interacts very very rarely with the RNG state, this is the approach I took finally (using RNGScope):

```
// simulation starts
GetRNGstate(); # in RcppExports.cpp
  // do stuff in C++
  // do stuff in R (may modify the RNG state)
  // do stuff in C++
  GetRNGstate();
  // C++ modifies the RNG state
  PutRNGstate();
  // etc. (repeat)
PutRNGstate(); # in RcppExports.cpp
```

This is completely equivalent (wraps R calls between Put-Get, instead of Get-Put), but with fewer calls to Put/Get, because there are many more calls to R functions that to random stuff in the C++ side. I could even set `rng=false` to remove the RNGScopes in RcppExports.cpp, but a few more calls won't hurt.
