### ISSUE TITLE
cppFunction plugins

### ISSUE THREAD

**Issue by tjmckinley** [RcppCore/Rcpp#1018]
Just flagging this as a possible further issue related to #1016 from @coatless? I haven't got a reprex for this, so I'm unsure whether it's a bug or not, but thought it should be flagged just in case.

> @tjmckinley while you're at it... Mind fixing the code for `plugins` as well? c.f.
> 
> https://github.com/RcppCore/Rcpp/blob/975361f40ee5140e3c843be365a20070edc63bfb/R/Attributes.R#L258-L259

Yes @coatless. Happy to do this if you and @eddelbuettel think this is an issue.

_Originally posted by @tjmckinley in https://github.com/RcppCore/Rcpp/pull/1016#issuecomment-552123417_

**Comment by eddelbuettel** [comment]
There is no issue here as best as I can tell so I am closing it.  If a need for action can be demonstrated, feel free to reopen preferably with such a demonstration or [minimally complete verifiable example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example).
