### ISSUE TITLE
Rcpp Update fails - any idea why?

### ISSUE THREAD

**Issue by MakaiMcClintock** [RcppCore/Rcpp#1020]
> R version 3.6.1 (2019-07-05) -- "Action of the Toes"
> Copyright (C) 2019 The R Foundation for Statistical Computing
> Platform: x86_64-apple-darwin15.6.0 (64-bit)
> 
> R is free software and comes with ABSOLUTELY NO WARRANTY.
> You are welcome to redistribute it under certain conditions.
> Type 'license()' or 'licence()' for distribution details.
> 
>   Natural language support but running in an English locale
> 
> R is a collaborative project with many contributors.
> Type 'contributors()' for more information and
> 'citation()' on how to cite R or R packages in publications.
> 
> Type 'demo()' for some demos, 'help()' for on-line help, or
> 'help.start()' for an HTML browser interface to help.
> Type 'q()' to quit R.
> 
> > reducedByOne = lm(CRIME ~ POP + CHILD + POPCH + LUNCH + INCOME, data=house)
> Error in is.data.frame(data) : object 'house' not found
> > house <- read.csv("~/Downloads/house.txt", sep="")
> >   View(house)
> > reducedByOne = lm(CRIME ~ POP + CHILD + POPCH + LUNCH + INCOME, data=house)
> > linearMod <- lm(CRIME ~ POP + POPCH + CHILD + LUNCH + INCOME + CRIMECH, data=house)
> > vif(reducedByOne)
> Error in vif(reducedByOne) : could not find function "vif"
> > install.packages("car")
> also installing the dependency ‘quantreg’
> 
> 
>   There is a binary version available but the source
>   version is later:
>          binary source needs_compilation
> quantreg   5.51   5.52              TRUE
> 
> Do you want to install from sources the package which needs compilation? (Yes/no/cancel) 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/car_3.0-4.tgz'
> Content type 'application/x-gzip' length 1567290 bytes (1.5 MB)
> ==================================================
> downloaded 1.5 MB
> 
> 
> The downloaded binary packages are in
> 	/var/folders/k0/_z_bb8sd6_31374_4sfs_ps00000gn/T//Rtmp0pncla/downloaded_packages
> installing the source package ‘quantreg’
> 
> trying URL 'https://cran.rstudio.com/src/contrib/quantreg_5.52.tar.gz'
> Content type 'application/x-gzip' length 995251 bytes (971 KB)
> ==================================================
> downloaded 971 KB
> 
> * installing *source* package ‘quantreg’ ...
> ** package ‘quantreg’ successfully unpacked and MD5 sums checked
> ** using staged installation
> ** libs
> gfortran  -fPIC  -Wall -g -O2  -c boot.f -o boot.o
> make: gfortran: No such file or directory
> make: *** [boot.o] Error 1
> ERROR: compilation failed for package ‘quantreg’
> * removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/quantreg’
> Warning in install.packages :
>   installation of package ‘quantreg’ had non-zero exit status
> 
> The downloaded source packages are in
> 	‘/private/var/folders/k0/_z_bb8sd6_31374_4sfs_ps00000gn/T/Rtmp0pncla/downloaded_packages’
> > library(car)
> Loading required package: carData
> Error: package or namespace load failed for ‘car’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
>  there is no package called ‘haven’
> > vif(reducedByOne)
> Error in vif(reducedByOne) : could not find function "vif"
> > car::vif(reducedByOne)
> Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
>   there is no package called ‘haven’
> > install.packages ("car", dep=T)
> also installing the dependencies ‘ps’, ‘plyr’, ‘labeling’, ‘munsell’, ‘RColorBrewer’, ‘processx’, ‘gtable’, ‘reshape2’, ‘scales’, ‘viridisLite’, ‘withr’, ‘callr’, ‘colorspace’, ‘estimability’, ‘yaml’, ‘Rcpp’, ‘evaluate’, ‘highr’, ‘markdown’, ‘stringr’, ‘xfun’, ‘httpuv’, ‘mime’, ‘xtable’, ‘sourcetools’, ‘later’, ‘promises’, ‘fastmap’, ‘lazyeval’, ‘ggplot2’, ‘miniUI’, ‘base64enc’, ‘webshot’, ‘DBI’, ‘effects’, ‘bdsmatrix’, ‘zoo’, ‘htmlwidgets’, ‘htmltools’, ‘knitr’, ‘jsonlite’, ‘shiny’, ‘crosstalk’, ‘manipulateWidget’, ‘numDeriv’, ‘mitools’, ‘quantreg’, ‘alr4’, ‘coxme’, ‘leaps’, ‘lmtest’, ‘rgl’, ‘sandwich’, ‘survey’
> 
> 
>   There are binary versions available but the source
>   versions are later:
>          binary source needs_compilation
> Rcpp      1.0.2  1.0.3              TRUE
> quantreg   5.51   5.52              TRUE
> 
> Do you want to install from sources the packages which need compilation? (Yes/no/cancel) YesYes     
> Error in install.packages : Unrecognized response “YesYes”
> > Yes
> Error: object 'Yes' not found
> > 
> > install.packages ("car", dep=T)
> also installing the dependencies ‘ps’, ‘plyr’, ‘labeling’, ‘munsell’, ‘RColorBrewer’, ‘processx’, ‘gtable’, ‘reshape2’, ‘scales’, ‘viridisLite’, ‘withr’, ‘callr’, ‘colorspace’, ‘estimability’, ‘yaml’, ‘Rcpp’, ‘evaluate’, ‘highr’, ‘markdown’, ‘stringr’, ‘xfun’, ‘httpuv’, ‘mime’, ‘xtable’, ‘sourcetools’, ‘later’, ‘promises’, ‘fastmap’, ‘lazyeval’, ‘ggplot2’, ‘miniUI’, ‘base64enc’, ‘webshot’, ‘DBI’, ‘effects’, ‘bdsmatrix’, ‘zoo’, ‘htmlwidgets’, ‘htmltools’, ‘knitr’, ‘jsonlite’, ‘shiny’, ‘crosstalk’, ‘manipulateWidget’, ‘numDeriv’, ‘mitools’, ‘quantreg’, ‘alr4’, ‘coxme’, ‘leaps’, ‘lmtest’, ‘rgl’, ‘sandwich’, ‘survey’
> 
> 
>   There are binary versions available but the source
>   versions are later:
>          binary source needs_compilation
> Rcpp      1.0.2  1.0.3              TRUE
> quantreg   5.51   5.52              TRUE
> 
> Do you want to install from sources the packages which need compilation? (Yes/no/cancel) Yes
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/ps_1.3.0.tgz'
> Content type 'application/x-gzip' length 209460 bytes (204 KB)
> ==================================================
> downloaded 204 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/plyr_1.8.4.tgz'
> Content type 'application/x-gzip' length 965992 bytes (943 KB)
> ==================================================
> downloaded 943 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/labeling_0.3.tgz'
> Content type 'application/x-gzip' length 61520 bytes (60 KB)
> ==================================================
> downloaded 60 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/munsell_0.5.0.tgz'
> Content type 'application/x-gzip' length 243642 bytes (237 KB)
> ==================================================
> downloaded 237 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/RColorBrewer_1.1-2.tgz'
> Content type 'application/x-gzip' length 53161 bytes (51 KB)
> ==================================================
> downloaded 51 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/processx_3.4.1.tgz'
> Content type 'application/x-gzip' length 236878 bytes (231 KB)
> ==================================================
> downloaded 231 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/gtable_0.3.0.tgz'
> Content type 'application/x-gzip' length 432473 bytes (422 KB)
> ==================================================
> downloaded 422 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/reshape2_1.4.3.tgz'
> Content type 'application/x-gzip' length 307635 bytes (300 KB)
> ==================================================
> downloaded 300 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/scales_1.0.0.tgz'
> Content type 'application/x-gzip' length 749007 bytes (731 KB)
> ==================================================
> downloaded 731 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/viridisLite_0.3.0.tgz'
> Content type 'application/x-gzip' length 57231 bytes (55 KB)
> ==================================================
> downloaded 55 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/withr_2.1.2.tgz'
> Content type 'application/x-gzip' length 152438 bytes (148 KB)
> ==================================================
> downloaded 148 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/callr_3.3.2.tgz'
> Content type 'application/x-gzip' length 338290 bytes (330 KB)
> ==================================================
> downloaded 330 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/colorspace_1.4-1.tgz'
> Content type 'application/x-gzip' length 2522321 bytes (2.4 MB)
> ==================================================
> downloaded 2.4 MB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/estimability_1.3.tgz'
> Content type 'application/x-gzip' length 36369 bytes (35 KB)
> ==================================================
> downloaded 35 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/yaml_2.2.0.tgz'
> Content type 'application/x-gzip' length 201073 bytes (196 KB)
> ==================================================
> downloaded 196 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/evaluate_0.14.tgz'
> Content type 'application/x-gzip' length 74657 bytes (72 KB)
> ==================================================
> downloaded 72 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/highr_0.8.tgz'
> Content type 'application/x-gzip' length 41180 bytes (40 KB)
> ==================================================
> downloaded 40 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/markdown_1.1.tgz'
> Content type 'application/x-gzip' length 199930 bytes (195 KB)
> ==================================================
> downloaded 195 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/stringr_1.4.0.tgz'
> Content type 'application/x-gzip' length 213304 bytes (208 KB)
> ==================================================
> downloaded 208 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/xfun_0.10.tgz'
> Content type 'application/x-gzip' length 175679 bytes (171 KB)
> ==================================================
> downloaded 171 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/httpuv_1.5.2.tgz'
> Content type 'application/x-gzip' length 2967678 bytes (2.8 MB)
> ==================================================
> downloaded 2.8 MB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/mime_0.7.tgz'
> Content type 'application/x-gzip' length 35263 bytes (34 KB)
> ==================================================
> downloaded 34 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/xtable_1.8-4.tgz'
> Content type 'application/x-gzip' length 702711 bytes (686 KB)
> ==================================================
> downloaded 686 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/sourcetools_0.1.7.tgz'
> Content type 'application/x-gzip' length 138829 bytes (135 KB)
> ==================================================
> downloaded 135 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/later_1.0.0.tgz'
> Content type 'application/x-gzip' length 567936 bytes (554 KB)
> ==================================================
> downloaded 554 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/promises_1.1.0.tgz'
> Content type 'application/x-gzip' length 1401944 bytes (1.3 MB)
> ==================================================
> downloaded 1.3 MB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/fastmap_1.0.1.tgz'
> Content type 'application/x-gzip' length 168581 bytes (164 KB)
> ==================================================
> downloaded 164 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/lazyeval_0.2.2.tgz'
> Content type 'application/x-gzip' length 158838 bytes (155 KB)
> ==================================================
> downloaded 155 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/ggplot2_3.2.1.tgz'
> Content type 'application/x-gzip' length 3973186 bytes (3.8 MB)
> ==================================================
> downloaded 3.8 MB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/miniUI_0.1.1.1.tgz'
> Content type 'application/x-gzip' length 34591 bytes (33 KB)
> ==================================================
> downloaded 33 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/base64enc_0.1-3.tgz'
> Content type 'application/x-gzip' length 32230 bytes (31 KB)
> ==================================================
> downloaded 31 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/webshot_0.5.1.tgz'
> Content type 'application/x-gzip' length 129184 bytes (126 KB)
> ==================================================
> downloaded 126 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/DBI_1.0.0.tgz'
> Content type 'application/x-gzip' length 879880 bytes (859 KB)
> ==================================================
> downloaded 859 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/effects_4.1-3.tgz'
> Content type 'application/x-gzip' length 2837774 bytes (2.7 MB)
> ==================================================
> downloaded 2.7 MB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/bdsmatrix_1.3-3.tgz'
> Content type 'application/x-gzip' length 273050 bytes (266 KB)
> ==================================================
> downloaded 266 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/zoo_1.8-6.tgz'
> Content type 'application/x-gzip' length 1089387 bytes (1.0 MB)
> ==================================================
> downloaded 1.0 MB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/htmlwidgets_1.5.1.tgz'
> Content type 'application/x-gzip' length 798782 bytes (780 KB)
> ==================================================
> downloaded 780 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/htmltools_0.4.0.tgz'
> Content type 'application/x-gzip' length 342242 bytes (334 KB)
> ==================================================
> downloaded 334 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/knitr_1.25.tgz'
> Content type 'application/x-gzip' length 1367480 bytes (1.3 MB)
> ==================================================
> downloaded 1.3 MB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/jsonlite_1.6.tgz'
> Content type 'application/x-gzip' length 1117755 bytes (1.1 MB)
> ==================================================
> downloaded 1.1 MB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/shiny_1.4.0.tgz'
> Content type 'application/x-gzip' length 4879671 bytes (4.7 MB)
> ==================================================
> downloaded 4.7 MB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/crosstalk_1.0.0.tgz'
> Content type 'application/x-gzip' length 662863 bytes (647 KB)
> ==================================================
> downloaded 647 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/manipulateWidget_0.10.0.tgz'
> Content type 'application/x-gzip' length 1826581 bytes (1.7 MB)
> ==================================================
> downloaded 1.7 MB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/numDeriv_2016.8-1.1.tgz'
> Content type 'application/x-gzip' length 113679 bytes (111 KB)
> ==================================================
> downloaded 111 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/mitools_2.4.tgz'
> Content type 'application/x-gzip' length 270213 bytes (263 KB)
> ==================================================
> downloaded 263 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/alr4_1.0.6.tgz'
> Content type 'application/x-gzip' length 687707 bytes (671 KB)
> ==================================================
> downloaded 671 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/coxme_2.2-14.tgz'
> Content type 'application/x-gzip' length 1256914 bytes (1.2 MB)
> ==================================================
> downloaded 1.2 MB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/leaps_3.0.tgz'
> Content type 'application/x-gzip' length 101530 bytes (99 KB)
> ==================================================
> downloaded 99 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/lmtest_0.9-37.tgz'
> Content type 'application/x-gzip' length 350323 bytes (342 KB)
> ==================================================
> downloaded 342 KB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/rgl_0.100.30.tgz'
> Content type 'application/x-gzip' length 4829347 bytes (4.6 MB)
> ==================================================
> downloaded 4.6 MB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/sandwich_2.5-1.tgz'
> Content type 'application/x-gzip' length 1385328 bytes (1.3 MB)
> ==================================================
> downloaded 1.3 MB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/survey_3.36.tgz'
> Content type 'application/x-gzip' length 2509029 bytes (2.4 MB)
> ==================================================
> downloaded 2.4 MB
> 
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/car_3.0-4.tgz'
> Content type 'application/x-gzip' length 1567290 bytes (1.5 MB)
> ==================================================
> downloaded 1.5 MB
> 
> 
> The downloaded binary packages are in
> 	/var/folders/k0/_z_bb8sd6_31374_4sfs_ps00000gn/T//Rtmp0pncla/downloaded_packages
> installing the source packages ‘Rcpp’, ‘quantreg’
> 
> trying URL 'https://cran.rstudio.com/src/contrib/Rcpp_1.0.3.tar.gz'
> Content type 'application/x-gzip' length 2749025 bytes (2.6 MB)
> ==================================================
> downloaded 2.6 MB
> 
> trying URL 'https://cran.rstudio.com/src/contrib/quantreg_5.52.tar.gz'
> Content type 'application/x-gzip' length 995251 bytes (971 KB)
> ==================================================
> downloaded 971 KB
> 
> * installing *source* package ‘Rcpp’ ...
> ** package ‘Rcpp’ successfully unpacked and MD5 sums checked
> ** using staged installation
> ** libs
> clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include/  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c api.cpp -o api.o
> clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk' [-Wmissing-sysroot]
> In file included from api.cpp:24:
> In file included from ../inst/include/Rcpp.h:27:
> In file included from ../inst/include/RcppCommon.h:29:
> In file included from ../inst/include/Rcpp/r/headers.h:67:
> In file included from ../inst/include/Rcpp/platform/compiler.h:100:
> In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:305:
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:301:15: fatal error: 'math.h' file not found
> #include_next <math.h>
>               ^~~~~~~~
> 1 error generated.
> make: *** [api.o] Error 1
> ERROR: compilation failed for package ‘Rcpp’
> * removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp’
> Warning in install.packages :
>   installation of package ‘Rcpp’ had non-zero exit status
> * installing *source* package ‘quantreg’ ...
> ** package ‘quantreg’ successfully unpacked and MD5 sums checked
> ** using staged installation
> ** libs
> gfortran  -fPIC  -Wall -g -O2  -c boot.f -o boot.o
> make: gfortran: No such file or directory
> make: *** [boot.o] Error 1
> ERROR: compilation failed for package ‘quantreg’
> * removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/quantreg’
> Warning in install.packages :
>   installation of package ‘quantreg’ had non-zero exit status
> 
> The downloaded source packages are in
> 	‘/private/var/folders/k0/_z_bb8sd6_31374_4sfs_ps00000gn/T/Rtmp0pncla/downloaded_packages’
> > car::vif(reducedByOne)
> Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
>   there is no package called ‘haven’
> > install.packages("haven")
> also installing the dependency ‘Rcpp’
> 
> 
>   There are binary versions available but the source
>   versions are later:
>       binary source needs_compilation
> Rcpp   1.0.2  1.0.3              TRUE
> haven  2.1.1  2.2.0              TRUE
> 
> Do you want to install from sources the packages which need compilation? (Yes/no/cancel) Yes
> installing the source packages ‘Rcpp’, ‘haven’
> 
> trying URL 'https://cran.rstudio.com/src/contrib/Rcpp_1.0.3.tar.gz'
> Content type 'application/x-gzip' length 2749025 bytes (2.6 MB)
> ==================================================
> downloaded 2.6 MB
> 
> trying URL 'https://cran.rstudio.com/src/contrib/haven_2.2.0.tar.gz'
> Content type 'application/x-gzip' length 272575 bytes (266 KB)
> ==================================================
> downloaded 266 KB
> 
> * installing *source* package ‘Rcpp’ ...
> ** package ‘Rcpp’ successfully unpacked and MD5 sums checked
> ** using staged installation
> ** libs
> clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include/  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c api.cpp -o api.o
> clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk' [-Wmissing-sysroot]
> In file included from api.cpp:24:
> In file included from ../inst/include/Rcpp.h:27:
> In file included from ../inst/include/RcppCommon.h:29:
> In file included from ../inst/include/Rcpp/r/headers.h:67:
> In file included from ../inst/include/Rcpp/platform/compiler.h:100:
> In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:305:
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:301:15: fatal error: 'math.h' file not found
> #include_next <math.h>
>               ^~~~~~~~
> 1 error generated.
> make: *** [api.o] Error 1
> ERROR: compilation failed for package ‘Rcpp’
> * removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp’
> Warning in install.packages :
>   installation of package ‘Rcpp’ had non-zero exit status
> ERROR: dependency ‘Rcpp’ is not available for package ‘haven’
> * removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/haven’
> Warning in install.packages :
>   installation of package ‘haven’ had non-zero exit status
> 
> The downloaded source packages are in
> 	‘/private/var/folders/k0/_z_bb8sd6_31374_4sfs_ps00000gn/T/Rtmp0pncla/downloaded_packages’
> > install.packages(c("Rcpp", "Rcpp11"))
> 
>   There is a binary version available but the source
>   version is later:
>      binary source needs_compilation
> Rcpp  1.0.2  1.0.3              TRUE
> 
> Do you want to install from sources the package which needs compilation? (Yes/no/cancel) Yes
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/Rcpp11_3.1.2.0.tgz'
> Content type 'application/x-gzip' length 104775 bytes (102 KB)
> ==================================================
> downloaded 102 KB
> 
> 
> The downloaded binary packages are in
> 	/var/folders/k0/_z_bb8sd6_31374_4sfs_ps00000gn/T//Rtmp0pncla/downloaded_packages
> installing the source package ‘Rcpp’
> 
> trying URL 'https://cran.rstudio.com/src/contrib/Rcpp_1.0.3.tar.gz'
> Content type 'application/x-gzip' length 2749025 bytes (2.6 MB)
> ==================================================
> downloaded 2.6 MB
> 
> * installing *source* package ‘Rcpp’ ...
> ** package ‘Rcpp’ successfully unpacked and MD5 sums checked
> ** using staged installation
> ** libs
> clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include/  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c api.cpp -o api.o
> clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk' [-Wmissing-sysroot]
> In file included from api.cpp:24:
> In file included from ../inst/include/Rcpp.h:27:
> In file included from ../inst/include/RcppCommon.h:29:
> In file included from ../inst/include/Rcpp/r/headers.h:67:
> In file included from ../inst/include/Rcpp/platform/compiler.h:100:
> In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:305:
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:301:15: fatal error: 'math.h' file not found
> #include_next <math.h>
>               ^~~~~~~~
> 1 error generated.
> make: *** [api.o] Error 1
> ERROR: compilation failed for package ‘Rcpp’
> * removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp’
> Warning in install.packages :
>   installation of package ‘Rcpp’ had non-zero exit status
> 
> The downloaded source packages are in
> 	‘/private/var/folders/k0/_z_bb8sd6_31374_4sfs_ps00000gn/T/Rtmp0pncla/downloaded_packages’
>

**Comment by eddelbuettel** [comment]
Just FYI:  Each edit box here has a link for formatting. Proper formatting makes it easier for us to read it.
