### ISSUE TITLE
consider updating RCPP_VERSION etc. automatically at build time

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/Rcpp#1021]
To help avoid things like https://github.com/RcppCore/Rcpp/issues/1019. It'd be nice to automate this (e.g. with a `configure` script) so that these fields are always populated as appropriate based the version in the DESCRIPTION file.

I don't think we need a full-blown autoconf script; rather, we could just use a simple `configure` / `configure.win` script to build e.g. `config.h` from `config.h.in`.

If I can toot my own horn, I would propose using [configure](https://github.com/kevinushey/configure) to make this happen. Note that this would not require any explicit dependency on the configure package; the necessary infrastructure would be bundled into Rcpp itself.

Otherwise, it'd be simple to (say) have `configure` / `configure.win` scripts which merely sourced a helper R script that manages the configure process.

Let me know if this sounds worth doing.

**Comment by eddelbuettel** [comment]
Allow me to gently vote against.  I also maintain maybe a dozen `configure.ac` across packages, but the _one-time_ release process is different.  I have set such things up in the past (_e.g._ RInside and littler stored a decade ago which SVN revision built the package) but I generally just use one-off scripts. 

In this case, a one-off script to modify `config.h` would have helped.  Then again when you look at the git log of that file I didn't miss all that often.  So call it a :man_shrugging:
