### ISSUE TITLE
Apparent fragility in Rcpp use when not calling importFrom(Rcpp, somesymbol)

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#1030]
I am currently running some reverse depends checks for a new RcppArmadillo minor release, and noticed a view package bonking in tests on `  function 'dataptr' not provided by package 'Rcpp'`.

This relates to our file [`inst/include/Rcpp/routines.h`](https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/routines.h) which has it, but also carries a comment 

```c++
// The 'attribute_hidden' used here is a simple precessor defined from
// ${R_HOME}/include/R_ext/Visibility.h -- it is empty when not supported
// by the compiler and otherwise '__attribute__ ((visibility ("hidden")))'
```

and that may recently have changed in R.  

Do we care?  Should we care?  

Should we remove the now-no-longer empty `attribute_hidden` define in front of `dataptr()` and a number of other helpers?

**Comment by kevinushey** [comment]
Are we sure this related to the use of `attribute_hidden`?

IIUC that error means that R wasn't able to find the R-level object acting as a pointer to the C-level entrypoint, which makes me think something "weird" happened to Rcpp during tests.

More directly, it means a call to `R_GetCCallable()` failed:

https://github.com/wch/r-source/blob/c12c7f3276c23bd6d3df5bffe1773cb39681fd2d/src/main/Rdynload.c#L1488-L1499

And we definitely register these routines here:

https://github.com/RcppCore/Rcpp/blob/e77e79c275bc3f520929917afb5b79b1a6f79ea0/src/rcpp_init.cpp#L88-L125

So I'm not exactly sure what's going on.

**Comment by eddelbuettel** [comment]
Definitely not sure what is going on either, but just thought that it was something we did not change but which R may have changed?  

That part of `rcpp_init.cpp` and `routines.cpp` is ... pretty old and unchanged too.  So big hmpf from me.

**Comment by eddelbuettel** [comment]
Took another look, and it could definitely also be that the 'compiling' branch no longer activates. I would not know why.

Simple tests work for me:

```r
R> cppFunction("bool getIt(NumericVector x) { void *ptr = dataptr(x); return ptr!=nullptr; }")
R> getIt(rnorm(5))
[1] FALSE
R> 
```

**Comment by eddelbuettel** [comment]
I _think_ it is the use of Rcpp in the affected package.  _E.g._ in the first one I looked, I noticed it did *not* have an `importFrom("Rcpp", "evalCpp")` (or alike) statement in `NAMESPACE`.  Adding that, and hence forcing symbol registration, is all it took to make the error go away in one package:

```diff
diff -ru BatchMap.orig/DESCRIPTION BatchMap/DESCRIPTION
--- BatchMap.orig/DESCRIPTION   2017-11-12 00:55:01.000000000 +0100
+++ BatchMap/DESCRIPTION        2019-12-05 14:39:13.450765159 +0100
@@ -15,7 +15,7 @@
     "augusto.garcia@usp.br"))
 LinkingTo: Rcpp (>= 0.10.5), RcppArmadillo (>= 0.7.700)
 Depends: parallel (>= 3.2.3), ggplot2 (>= 1.0.1), R (>= 3.2.0)
-Imports: reshape2 (>= 1.4.1), methods
+Imports: reshape2 (>= 1.4.1), methods, Rcpp
 Suggests: knitr (>= 1.10), rmarkdown
 VignetteBuilder: knitr
 Encoding: UTF-8
diff -ru BatchMap.orig/NAMESPACE BatchMap/NAMESPACE
--- BatchMap.orig/NAMESPACE     2017-10-30 17:44:39.000000000 +0100
+++ BatchMap/NAMESPACE  2019-12-05 14:32:23.872820158 +0100
@@ -10,6 +10,7 @@
            "median", "na.omit", "qchisq", "sd")
 importFrom("utils", "flush.console", "head", "setTxtProgressBar",
            "tail", "txtProgressBar")
+importFrom("Rcpp", "evalCpp")
 ## Export all names
 exportPattern(".")

```

**Comment by kevinushey** [comment]
That makes sense to me. We've documented using `importFrom(Rcpp, evalCpp)` basically forever because of issues of this from.

**Comment by eddelbuettel** [comment]
Indeed.  And when I looked at the package, it still had some older school direct use of SEXP, using .Call() with the symbol quoted and package name listed etc pp.  In that case I think one simply needs it.

**Comment by eddelbuettel** [comment]
I just added to the Rcpp FAQ for this.  PR coming in a moment, have a look at that to see if the writing I added is sufficient.
