### ISSUE TITLE
Should we support R CMD SHLIB -d on Windows only?

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#1035]
Via email, a user alerted me to the fact that he cannot create a gdb-compliant file on Windows when using `sourceCpp()`.

And that appears to be the case.  The bottom of `R CMD SHLIB --help` shows

```
Windows only:
  -d, --debug           build a debug DLL
```

And seemingly (when using `sourceCpp()`) one cannot get by via `~/.R/Makevars`.   Looking at `R/Attributes.R` it appears that we'd "just" need a new argument to `sourceCpp()` and insert an `ifelse()` line around line 124 just as we do to support `--preclean` and `--dry-run`.   

Shall we do that? I guess there is no real reason not to...

**Comment by eddelbuettel** [comment]
Nice find on the effect!  I'll cook up a quick and simple PR.  May warn if flag to 'debugdll' is set when not an Windows, otherwise expand signature and add to Rd.  That should be it.  I'll also ship it to winbuilder and contact the person who raised ... who may or may not work on it over the weekend.

**Comment by eddelbuettel** [comment]
(This is now implemented in a branch, and a pointed the user to a binary built by win-builder.)

**Comment by eddelbuettel** [comment]
Apparently what I did was not good enough:

```
 > library("Rcpp")
Error: package or namespace load failed for ‘Rcpp’ in rbind(info, 
getNamespaceInfo(env, "S3methods")):
  number of columns of matrices must match (see arg 2)
```

I don't have a Windows machine, and there is a limit to what I can do in one-offs to users who cannot or will not use the official channels.  I.e. these tickets.

**Comment by eddelbuettel** [comment]
Passed at win-builder, now passes at rhub:  
  https://builder.r-hub.io/status/Rcpp_1.0.3.5.tar.gz-b7d940fac70348898792fe3c03df63fd

Maybe the user has an older installation.  Oh well.

**Comment by GoralBill** [comment]
I am the user who raised the issue. I just set up a GitHub account so that I could read these posts. I am currently using R 3.5.1 with RTools35 so I believe that it should be recent enough.

**Comment by eddelbuettel** [comment]
Hi Bill, thanks for coming here.

In the meantime, I have re-confirmed builds at both win-builder and rhub.  Those do of course use the current R, 3.6.1 or as of last week, 3.6.2.  So to test it would be great if you could take the source here.   If you are git-savvy than this old news but if not do
1. go to the branch, ie https://github.com/RcppCore/Rcpp/tree/feature/win_debug_dll
1. clock on 'Clone or Download' (the green button towards the top right)
1. select 'download zip'
When I just did that I got a zipfile named `Rcpp-feature-win_debug_dll.zip` reflecting the branch.  Do `R CMD INSTALL .` once you expand it, and test that version.

Appreciate the help!

**Comment by GoralBill** [comment]
I've never been on GitHub before so I'm most definitely not "Git Savvy". Didn't even know you guys used it as the "official" communication channel until I followed the link you left in one of our emails this morning. That said, I'm generally a fairly quick study so I'll give it a try.

**Comment by GoralBill** [comment]
After installing from the source above, all seems to be working as I expect. I am able to load Rcpp and step into my test function using gdb. Thank you.

**Comment by eddelbuettel** [comment]
Thanks for the feedback.  I will merge this; next release won't come for a while but now know where to get the pieces to help yourself in the meantime. 

Also:  weird error message from using the R 3.6.* build on R 3.5.*.  I guess we skipped the earlier warning message that is there for this reason.
