### ISSUE TITLE
Staged Install Issue with loadModule

### ISSUE THREAD

**Issue by pistacliffcho** [RcppCore/Rcpp#1039]
When I try to install my package, I get an issue with staged install (both with R v3.6.0 and 3.6.2):

ERROR: hard-coded installation path: please report to the package maintainer and use ‘--no-staged-install’

This error can be "fixed" by commenting out the following code:
```
loadModule("LCN", TRUE)
loadModule("BKN", TRUE)
```
but of course that means my package will not work. 

The package in question is [here](https://github.com/pistacliffcho/LatentChannelNetworks.R), the file with loadModules is [here](https://github.com/pistacliffcho/LatentChannelNetworks.R/blob/master/R/latChanNet/R/loading.R).

**Comment by eddelbuettel** [comment]
That seems ... strange.  I have a few packages implemented as Rcpp Modules and have never seen that issue.  Could it be that you are doing something else you should maybe not be doing?

**Comment by pistacliffcho** [comment]
I'm certainly perplexed as well. I'm going to start from a skeleton package and see if I can recreate the issue.

**Comment by pistacliffcho** [comment]
Hmm, when I clone the problem repo to another machine, the issue goes away. That's quite confusing, but it seems safe to assume the issue is not with Rcpp. 

Closing the issue.

**Comment by pistacliffcho** [comment]
Just to follow up on this in case anyone else finds it: whatever the cause was, the fix was throwing out .Rhistory inside the package.

**Comment by eddelbuettel** [comment]
Glad you sorted it out!
