### ISSUE TITLE
Rcpp v1.0.4 causes package installations to fail on macOS

### ISSUE THREAD

**Issue by pat-s** [RcppCore/Rcpp#1052]
With Rcpp v1.0.4 some packages fail to install from source on macOS (v1.0.3 works fine).
I don't know if this is expected (i.e. an issue that the packages should solve), related to my CFLAGS or from Rcpp.

Anyhow this breaks all CI testing on R-devel macOS currently since many packages are affected.

Log slice from a local install attempt of package `fs`:

```r
In file included from id.cc:4:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/grp.h:79:25: error: unknown type name 'uuid_t'; did you mean 'uid_t'?
struct group *getgruuid(uuid_t);
                        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_uid_t.h:31:31: note: 'uid_t' declared here
typedef __darwin_uid_t        uid_t;

[...]

9 errors generated.
make: *** [id.o] Error 1
ERROR: compilation failed for package ‘fs’
```

Just in case, here are the CFLAGS. Using the ones recommended in https://github.com/rmacoslib/r-macos-rtools including an openMP enabled clang7 on macOS 10.15.3.

```
CFLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
CCFLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
CXXFLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
CPPFLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include
```

**Comment by eddelbuettel** [comment]
Please see #1046, which was fixed in #1047.  Corrected versions on the Rcpp drat.
