### ISSUE TITLE
bad_alloc crash on throw with -D_GLIBCXX_USE_CXX11_ABI=0 flag

### ISSUE THREAD

**Issue by renkun-ken** [RcppCore/Rcpp#1058]
When Rcpp code is built with `-D_GLIBCXX_USE_CXX11_ABI=0` flag, any `throw` or `stop` will cause memory-not-mapped crash with `std::bad_alloc`.

A minimal reproducible example:

```r
Sys.setenv(PKG_CPPFLAGS = "-D_GLIBCXX_USE_CXX11_ABI=0")

f <- Rcpp::cppFunction('
void test() {
  stop("error");
}')

f()
```

```
 *** caught segfault ***
address 0x7b64060, cause 'memory not mapped'

Traceback:
 1: .Call(<pointer: 0x7fd9b3810da0>)
 2: f()
```

Some third-party libs are built with C++11 ABI disabled. This problem makes it hard to use these libs with Rcpp.

**Comment by eddelbuettel** [comment]
Thanks for reporting this. We can surely report it in the Rcpp FAQ. 

I am not sure we can do much about it -- "mismatched ABIs" has been a source of incompatibilties for as long as I have used C++.  It is somewhat unavoidable.

**Comment by renkun-ken** [comment]
Currently, `-D_GLIBCXX_USE_CXX11_ABI=0` works perfectly with `CharacterVector` in dealing with `string`. I'm not sure if we could make error handling also work with it since it is the only thing I find not compatible.

**Comment by renkun-ken** [comment]
I could only use the following as a walk around at the moment:

```cpp
int test() {
  Rcerr << "error" << std::endl;
  throw 0;
}
```

**Comment by eddelbuettel** [comment]
If you feel energetic, go right ahead.  I am little tired of changes to exeception handling given that the (maybe overly ambitious) PR #1043 required three more follow-up PRs ... 

But we are always open to high-quality contributions.  Currently, it seems it is your itch to scratch, so maybe you want to give it a go.

**Comment by kevinushey** [comment]
Works fine for me if Rcpp itself is also compiled with `D_GLIBCXX_USE_CXX11_ABI=0`. You might need to ensure this define is always enabled whenever compiling R packages on your machine.

> Some third-party libs are built with C++11 ABI disabled. This problem makes it hard to use these libs with Rcpp.

Why can't you just recompile these libraries?

**Comment by eddelbuettel** [comment]
> Why can't you just recompile these libraries?

Sometimes vendors only hand-down pre-built libraries and no sources.  But your point is 100% correct: _we can adjust_ on our open source side maybe @renkun-ken just needs a separate `.libPaths()` for linking with a constrained build that has the required define/option.

**Comment by renkun-ken** [comment]
The ABI issue is quite contagious since I might need some other libs that requires enabling C++11 ABI.

We might need to document this somewhere.

I took a slight look at the code but I don't have a clue how to make it compatible with C++11 ABI disabled without recompiling or using a separate lib path. I guess I'll stick to my walk-around at the moment.

**Comment by eddelbuettel** [comment]
I think we can file this under user / other apps rather than Rcpp specific so I will close it.
