### ISSUE TITLE
I am trying to use google perftools in my .cpp script but keep getting the following compilation error.

### ISSUE THREAD

**Issue by hasibul212003** [RcppCore/Rcpp#1063]
I have a .cpp file named nested_list.cpp. I installed google perftools from source file. In the .cpp file #gperftools/profiler.h and use ProfilerStart("output.log") and ProfilerStop() in the script where I want to perform profiling. Trying to source the .cpp file gives the following error.

Rcpp::sourceCpp('nested_list.cpp')
Error in dyn.load("/tmp/Rtmpns7Els/sourceCpp-x86_64-pc-linux-gnu-1.0.4/sourcecpp_6a227b762fd1/sourceCpp_11.so") : 
  unable to load shared object '/tmp/Rtmpns7Els/sourceCpp-x86_64-pc-linux-gnu-1.0.4/sourcecpp_6a227b762fd1/sourceCpp_11.so':
  /tmp/Rtmpns7Els/sourceCpp-x86_64-pc-linux-gnu-1.0.4/sourcecpp_6a227b762fd1/sourceCpp_11.so: undefined symbol: ProfilerStart

**Comment by eddelbuettel** [comment]
You need to _link_ with the corresponding library.

I don't have a pointer for recent tutorials but it covered all this in full example in various 'intro do high performance computing with R' tutorials I did about a decade+ ago.  The pdf slides are still at my site under talks.

Closing this as there is not Rcpp issue here.

**Comment by eddelbuettel** [comment]
PS:  It may be as simple as `Sys.setenv("PKG_LIBS"="-lprofiler")`.  I usually start via an "existence proof" in a small C++ binary and then carry the linker (and compiler, if needed) flags to the R package.
