### ISSUE TITLE
problem creating a simple namespace

### ISSUE THREAD

**Issue by brunaw** [RcppCore/Rcpp#1064]
Hey all. I'm having a problem to load a simple namespace from `c++` into `R`. My code is as follows:

`csample.cpp`:
```
#include <RcppArmadillo.h>
// [[Rcpp::depends(RcppArmadillo)]]
using namespace Rcpp;
#include "utils.h"
#include <RcppArmadilloExtensions/sample.h>
// [[Rcpp::export]]
namespace bartBMA { 
IntegerVector utils::csample_num( 
    IntegerVector x,
    int size,
    bool replace, 
    NumericVector prob = NumericVector::create()) {
  RNGScope scope;
  IntegerVector ret = RcppArmadillo::sample(x, size, replace, prob);
  return ret;
}
}
```
(I also tried using `#include <Rcpp.h>` instead of `#include <RcppArmadillo.h>` but with no luck)

while `utils.h` is:

```
#include "Rcpp.h"
using namespace Rcpp ;
// [[Rcpp::export]]
namespace bartBMA {
class utils
{
public:
  Rcpp::IntegerVector csample_num(
      Rcpp::IntegerVector x,
      int size,
      bool replace, 
      Rcpp::NumericVector prob
  ); 
};
}
```

When I try to load it into R with  `sourceCpp("csample.cpp")` I get:
```
> sourceCpp("csample.cpp")
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
Warning messages:
1: No function found for Rcpp::export attribute at csample.cpp:6 
2: No function found for Rcpp::export attribute at utils.h:3 
3: In sourceCpp("csample.cpp") :
  No Rcpp::export attributes or RCPP_MODULE declarations found in source
```

and I don't really know how to interpret this. I've played around with the inclusion ordering of the `.h` and `// [[Rcpp::export]]` parts but nothing really helped. I also don't know where does the first part of the warning come from as I recently had `gcc` problems but managed to fix them (or so I thought) and now I can compile `c++` or R packages that use `c++` normally. Any ideas?

**Comment by coatless** [comment]
@brunaw functions have to be placed in the global environment. Not a namespace.

```cpp
#include <RcppArmadillo.h>
// [[Rcpp::depends(RcppArmadillo)]]
using namespace Rcpp;
#include "utils.h"
#include <RcppArmadilloExtensions/sample.h>

namespace bartBMA { 
IntegerVector utils::csample_num( 
    IntegerVector x,
    int size,
    bool replace, 
    NumericVector prob = NumericVector::create()) {
  RNGScope scope;
  IntegerVector ret = RcppArmadillo::sample(x, size, replace, prob);
  return ret;
}
}

// Write a wrapper to the namespace'd function that will be elevated into R
// [[Rcpp::export]]
IntegerVector csample_num( 
    IntegerVector x,
    int size,
    bool replace, 
    NumericVector prob = NumericVector::create()) {

    return bartBMA::utils::csample_num(x, size, replace, prob);
}
```

**Comment by eddelbuettel** [comment]
Also, will due respect, this is the wrong place for this.  

There are over 2000 questions for Rcpp on StackOverflow. Many capable folks watch that tag and offer answers within minutes.  That, or of course the rcpp-devel list, is the appropriate place.  The issue tracker here _is not_.  Please do no abuse it.

Also, I often find it helps me to first walk and stumble before I try to sprint.  You may find the paper by @coatless and myself which is included with Rcpp helpful -- it even shows how to use the sampler as I recall.
