### ISSUE TITLE
warning when compiling with clang-10 on macOS

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/Rcpp#1066]
Saw this while compiling Rcpp with the latest version of LLVM on macOS:

```
/usr/local/opt/llvm/bin/clang++ -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -fsanitize=address,undefined -fno-omit-frame-pointer -fno-sanitize=alignment,function,float-divide-by-zero -std=gnu++11 -I"/Users/kevinushey/r/r-devel-sanitizers/lib/R/include" -DNDEBUG -I../inst/include/  -I/usr/local/include   -fPIC  -g -O1 -Wall -pedantic -DSWITCH_TO_REFCNT  -c module.cpp -o module.o
api.cpp:136:12: warning: address of stack memory associated with local variable 'f' returned [-Wreturn-stack-address]
    return f.c_str();
           ^
1 warning generated.
```

The offending routine is here:

https://github.com/RcppCore/Rcpp/blob/c9cf6aaf7b48216d141a3e549c74e50ebf55a13f/src/api.cpp#L129-L137

We are indeed returning a pointer to the data for a `std::string` on the stack, which is unsafe. Note that while this is a registered routine, it's only used internally (when Rcpp debugging is enabled via `RCPP_DEBUG`). Either way, two potential fixes here would be:

1. Just return a `std::string` rather than a `const char*`, or
2. Use a static `std::string`, and return a pointer to the data for that `std::string`.

**Comment by eddelbuettel** [comment]
Ugg.  Option 1. is probably safer.
