### ISSUE TITLE
better handle %s in single-argument calls to stop()

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/Rcpp#1072]
For example, with the following document:

```
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
void ouch() {
    stop("This is a bad example. %100%s.");
}

/***R
ouch()
*/
```

I see:

```
> Rcpp::sourceCpp('~/scratch/ouch.cpp')
> ouch()
Error in ouch() : 
  tinyformat: Too many conversion specifiers in format string
```

Worth considering whether the single-argument version of `Rcpp:stop()` should sidestep the use of `tinyformat`.

https://github.com/RcppCore/Rcpp/blob/a80908fe835ada996708da345cdb68bff569aecc/inst/include/Rcpp/exceptions/cpp11/exceptions.h#L50-L53

**Comment by eddelbuettel** [comment]
I use that idiom quite a bit myself, and have not been bitten.  How do you suggest the catch the 'bad' second '%' in there?

**Comment by eddelbuettel** [comment]
As discussed over online chat, shall we maybe close this one?

**Comment by kevinushey** [comment]
Sounds good to me!
