### ISSUE TITLE
Random number generator

### ISSUE THREAD

**Issue by donaldRwilliams** [RcppCore/Rcpp#1073]
I was curious whether it would be possible to allow for the random number generators, say, `Rcpp::rnorm` to accept vectors for the mean and standard deviation. In a current problem I am working on, I am having to loop through each row of a larger matrix when using Rcpp (c++), whereas, in R, I can generate the random numbers by giving the vector to `stats::rnorm`. This seems to be making the base R implementation much faster.

**Comment by eddelbuettel** [comment]
Sure. (And I saw the StackOverflow thread where you added this a comment).

But _first and foremost_ we like API similarity and stability.  So the easiest fix really is if you built yourself a, say, `drwrng` package and then your function `drwrnorm(M, S)` could consume vectors M _and_ S and nobody would confuse it with a) the existing 10 year old API and b) the R API it shadows.  Hope that makes sense to you too.

And of course in the case a Normal distribution you can always do it _after_ the fact:

```r
R> cppFunction("NumericVector foo(int n) { return Rcpp::rnorm(n); }")
R> foo(2)
[1] 0.876980 0.775977
R> foo(2) + c(10,20)           # means of 10 and 20, respectively
[1] 10.3807 19.9167
R> 
```

**Comment by donaldRwilliams** [comment]
Thank you for the quick response ! 

I will give that a try. I noted in some other code that allows for this (e.g., the source code for `extraDistr` ) that, in fact, there is a for loop writing in c++. I also have a for loop, so now thinking that maybe my code is perhaps poorly written.

**Comment by eddelbuettel** [comment]
(Back from a groceries run now).  Also, strickly speaking, we are now talking about the "RNG" (as in underlying source of pseudo-randomness) but "simply" some helper wrapper functions.  That may be best added in a package of your own unless / until we find sufficient interest to add it to Rcpp sugar.  So on balance I think we should close this.

**Comment by eddelbuettel** [comment]
I am closing this as there isn't really anything actionable for Rcpp here.  The question can be answered most easily in add-on function or package.
