### ISSUE TITLE
Add the '13 steps for package with C++ library' paper?

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#1077]
How to build R package with an external C++ library is still tricky, with or without Rcpp. In workshops I often mention three cases of i) headers-only, ii) small sources (to be included), iii) large sources (external library) and mention that especially the latter one is still hard esp cross-platform. 

Now, I did sit down in November on wrote down some notes that turned into a arXiv pre-print (at [arxiv.org/abs/1911.06416](https://arxiv.org/abs/1911.06416)) that I actually never really announced,. Somehow made it into a twitter thread recently, and people seem to find it useful. It occurred to me that we could stick it into the package as a new vignette as well.

Thoughts?  Yay?  Nay?

**Comment by jwood000** [comment]
@eddelbuettel,

I think this would be a great idea. I have never seen the linked article before this morning and just with a quick read, this is fantastic stuff.

As an avid `Rcpp` user, the vignettes are a staple of my mine and I point many people seeking help with `Rcpp` questions to the vignettes often. If added, this would be yet another authoritative and concise resource to help others.

in short, Yay!

**Comment by coatless** [comment]
@jwood000 you may want to check out https://github.com/r-pkg-examples ;)

**Comment by eddelbuettel** [comment]
So after three days we have 
 - one yay
 - zero nays
 - one commercial for something else (hi, @coatless)

which I read as mildly in favour.   Proceeding...
