### ISSUE TITLE
Check length before eccessing?

### ISSUE THREAD

**Issue by ltierney** [RcppCore/Rcpp#1080]
https://github.com/RcppCore/Rcpp/blob/446c3cafdf514e6d9db1d84c580b77c5b1d8f3e2/inst/include/Rcpp/String.h#L68-L80

**Comment by ltierney** [comment]
It looks like the `STRING_ELT(charsxp, 0)` is happening before th elength check, in particular before making sure length is at least one.

**Comment by eddelbuettel** [comment]
Looking at it now.   The line just above you chose not quote makes defines an incoming `SEXP charsxp`.  

Is the concern that `charsxp` could be of length zero in line 69?  That would indeed be a possible corner case. 

And not to leave it unsaid: appreciate you are checking these details.

**Comment by ltierney** [comment]
That's just the variable name. The code looks like it is allowing the value of `charsxp` to be a `STRSXP` and is grabbing element 0, which might not exist. Just happened to notice in another context that I'll try to post about tomorrow.

**Comment by Enchufa2** [comment]
We have:

``` r
Rcpp::cppFunction('
CharacterVector test(SEXP x) {
  return String(x).get_sexp();
}
')

test(character(0))
#> Error in test(character(0)): 'getCharCE' must be called on a CHARSXP
test(character(1))
#> [1] ""
test(character(2))
#> [1] ""
test(integer(1))
#> Error in test(integer(1)): 'getCharCE' must be called on a CHARSXP
```

Grabbing the first element without checking the length is not the only problem in that constructor. Any other SEXP types are not handled in any way, so `data` is NULL and we get this not-very-helpful error message.

To address this, we should first define what should happen for each SEXP type. Given that down below there are constructors for int, double, bool, RComplex and Rbyte, I would say that the last call in my example above should work.

**Comment by eddelbuettel** [comment]
I pulled your test apart into

```r
Rcpp::cppFunction("CharacterVector test2(SEXP x) { String s(x); CharacterVector cv(s.get_sexp()); return cv; }")  
```

which shows no difference.  Which leads to a simplification

```r
 Rcpp::cppFunction("String test3(SEXP x) { String s(x); return s; }")  
```

which both exhibit the same behaviour.
