### ISSUE TITLE
Rcpp wants to compile `foo.c` all the time

### ISSUE THREAD

**Issue by torkar** [RcppCore/Rcpp#1086]
I saw something similar about this on the mailing list but I'm unfortunately on `Ubuntu 18.04` on an OpenStack environment. 

For some reason, when I run my `Rmd` script now (did not happen before) it tries to compile a `foo.c` file when running `brms`/`Stan` and it fails. But then, compiling the model with `g++` works. So in short, I get the below error msg printed in the output from `Rmd` every time I try to run `brms`:
```
## Running /usr/lib/R/bin/R CMD SHLIB foo.c
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG   -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include/"  -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/"  -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/unsupported"  -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/BH/include" -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include/src/"  -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include/"  -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/rstan/include" -DEIGEN_NO_DEBUG  -D_REENTRANT  -DBOOST_DISABLE_ASSERTS -DBOOST_PENDING_INTEGER_LOG2_HPP -include stan/math/prim/mat/fun/Eigen.hpp      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-aGvNeb/r-base-4.0.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c foo.c -o foo.o
## In file included from /home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/Core:88:0,
##                  from /home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/Dense:1,
##                  from /home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:4,
##                  from <command-line>:0:
## /home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/src/Core/util/Macros.h:613:1: error: unknown type name ‘namespace’
##  namespace Eigen {
##  ^~~~~~~~~
## /home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/src/Core/util/Macros.h:613:17: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
##  namespace Eigen {
##                  ^
## In file included from /home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/Dense:1:0,
##                  from /home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:4,
##                  from <command-line>:0:
## /home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/Core:96:10: fatal error: complex: No such file or directory
##  #include <complex>
##           ^~~~~~~~~
## compilation terminated.
## /usr/lib/R/etc/Makeconf:167: recipe for target 'foo.o' failed
## make: *** [foo.o] Error 1
```
`pkgbuild::has_build_tools(debug = TRUE)` shows `TRUE` and I'm on `R`v4.0.0. I'm sorry if this is not an `Rcpp` issue, but then I'll go to the `Stan` community and ask.

**Comment by torkar** [comment]
I should add that I run `RStudio Server` on OpenStack :)

**Comment by eddelbuettel** [comment]
Come on, you need to better. That is a) incomplete b) hence irreproducible and c) not verifiable.  Plus you are using a layer of tools that have *nothing* to do with Rcpp -- apart from being piled on top.   If you have issues with `brms` or `rstan` or `pkbuild` or ... raise that at *their repos* or support tracker.  When you can show something wrong with Rcpp itself i.e. via `Rcpp::sourceCpp()` or `R CMD build ...` iinvolving Rcpp you can come here.

This is _possibly_ a question for StackOverflow or the mailing list _if improved and made complete_ but most clearly not one for here.

**Comment by torkar** [comment]
Fair enough, Dick. As I wrote, "I'm sorry if this is not an Rcpp issue"

**Comment by kangxiongbin** [comment]
> I saw something similar about this on the mailing list but I'm unfortunately on `Ubuntu 18.04` on an OpenStack environment.
> 
> For some reason, when I run my `Rmd` script now (did not happen before) it tries to compile a `foo.c` file when running `brms`/`Stan` and it fails. But then, compiling the model with `g++` works. So in short, I get the below error msg printed in the output from `Rmd` every time I try to run `brms`:
> 
> ```
> ## Running /usr/lib/R/bin/R CMD SHLIB foo.c
> ## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG   -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include/"  -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/"  -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/unsupported"  -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/BH/include" -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include/src/"  -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include/"  -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/rstan/include" -DEIGEN_NO_DEBUG  -D_REENTRANT  -DBOOST_DISABLE_ASSERTS -DBOOST_PENDING_INTEGER_LOG2_HPP -include stan/math/prim/mat/fun/Eigen.hpp      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-aGvNeb/r-base-4.0.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c foo.c -o foo.o
> ## In file included from /home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/Core:88:0,
> ##                  from /home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/Dense:1,
> ##                  from /home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:4,
> ##                  from <command-line>:0:
> ## /home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/src/Core/util/Macros.h:613:1: error: unknown type name ‘namespace’
> ##  namespace Eigen {
> ##  ^~~~~~~~~
> ## /home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/src/Core/util/Macros.h:613:17: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
> ##  namespace Eigen {
> ##                  ^
> ## In file included from /home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/Dense:1:0,
> ##                  from /home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:4,
> ##                  from <command-line>:0:
> ## /home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/Core:96:10: fatal error: complex: No such file or directory
> ##  #include <complex>
> ##           ^~~~~~~~~
> ## compilation terminated.
> ## /usr/lib/R/etc/Makeconf:167: recipe for target 'foo.o' failed
> ## make: *** [foo.o] Error 1
> ```
> 
> `pkgbuild::has_build_tools(debug = TRUE)` shows `TRUE` and I'm on `R`v4.0.0. I'm sorry if this is not an `Rcpp` issue, but then I'll go to the `Stan` community and ask.

**Comment by kangxiongbin** [comment]
> I saw something similar about this on the mailing list but I'm unfortunately on `Ubuntu 18.04` on an OpenStack environment.
> 
> For some reason, when I run my `Rmd` script now (did not happen before) it tries to compile a `foo.c` file when running `brms`/`Stan` and it fails. But then, compiling the model with `g++` works. So in short, I get the below error msg printed in the output from `Rmd` every time I try to run `brms`:
> 
> ```
> ## Running /usr/lib/R/bin/R CMD SHLIB foo.c
> ## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG   -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include/"  -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/"  -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/unsupported"  -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/BH/include" -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include/src/"  -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include/"  -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/rstan/include" -DEIGEN_NO_DEBUG  -D_REENTRANT  -DBOOST_DISABLE_ASSERTS -DBOOST_PENDING_INTEGER_LOG2_HPP -include stan/math/prim/mat/fun/Eigen.hpp      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-aGvNeb/r-base-4.0.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c foo.c -o foo.o
> ## In file included from /home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/Core:88:0,
> ##                  from /home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/Dense:1,
> ##                  from /home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:4,
> ##                  from <command-line>:0:
> ## /home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/src/Core/util/Macros.h:613:1: error: unknown type name ‘namespace’
> ##  namespace Eigen {
> ##  ^~~~~~~~~
> ## /home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/src/Core/util/Macros.h:613:17: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
> ##  namespace Eigen {
> ##                  ^
> ## In file included from /home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/Dense:1:0,
> ##                  from /home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:4,
> ##                  from <command-line>:0:
> ## /home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/Core:96:10: fatal error: complex: No such file or directory
> ##  #include <complex>
> ##           ^~~~~~~~~
> ## compilation terminated.
> ## /usr/lib/R/etc/Makeconf:167: recipe for target 'foo.o' failed
> ## make: *** [foo.o] Error 1
> ```
> 
> `pkgbuild::has_build_tools(debug = TRUE)` shows `TRUE` and I'm on `R`v4.0.0. I'm sorry if this is not an `Rcpp` issue, but then I'll go to the `Stan` community and ask.

Dear Richard Torkar,
Did you find how to deal with it? When I run brms in R (R version 3.6.0), encountering the same issue. My serve information: Linux version 3.10.0-1127.19.1.el7.x86_64 (gcc version 4.8.5 20150623)

**Comment by eddelbuettel** [comment]
Please take that to the `brms` mailing list or other help channels.  This has still nothing to do with Rcpp, and I am going to lock this issue now.
