### ISSUE TITLE
Possible package.skeleton issue affecting Rcpp, RcppArmadillo, RStudio (!!), ...

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#1087]
So I just did the [live webinar](https://www.youtube.com/watch?v=1Zap6j1uUyw) on Rcpp and got to show live how package generation now fails (from RStudio) for both Rcpp and RcppArmadillo :cry: 

It looks the `NAMESPACE` file now gets an 'echo' from a temp function we create but which is no longer there when the package is finished.  And misses an actual `exportPatter()`.  

So a simple first fix for RcppArmadillo could be (done and tested)

```diff
modified   R/RcppArmadillo.package.skeleton.R
@@ -78,6 +78,8 @@ RcppArmadillo.package.skeleton <- function(name="anRpackage", list=character(),
     ## add a useDynLib to NAMESPACE,
     NAMESPACE <- file.path( root, "NAMESPACE")
     lines <- readLines( NAMESPACE )
+    lines <- lines[!grepl("^export.*fake", lines)]
+    lines <- c(lines, "exportPattern(\"^[[:alpha:]]+\")")
     if (! grepl("useDynLib", lines)) {
         lines <- c(sprintf("useDynLib(%s, .registration=TRUE)", name),
                    "importFrom(Rcpp, evalCpp)",        ## ensures Rcpp instantiation
```

do not print the `fake` one but add the pattern.  Is my fear justified that the RStudio generator may need this too?  Paging @kevinushey ....

**Comment by eddelbuettel** [comment]
I just pushed a simpler / better fix in a new branch.  In essence we seem to need to keep a fake symbol around, and already cleaned up after it at the end.   Now, it seems, R changed and somehow that symbol ends up in the NAMESPACE.  So ... we clean that too.

That, plus ensuring an `exportPattern(...)` is set may be all we need here.

@kevinushey Can you remind how it works from RStudio when we create a package? Does it call the Rcpp function?

**Comment by kevinushey** [comment]
Hmm, it looks like the behavior in `package.skeleton()` has actually changed in R 4.0.0. Before, it would insert an export pattern; now, it just exports the 'fake' objects that were created. For example, I see:

```
$ R --vanilla --slave -e "x <- 1; package.skeleton()" && cat anRpackage/NAMESPACE
Creating directories ...
Creating DESCRIPTION ...
Creating NAMESPACE ...
Creating Read-and-delete-me ...
Saving functions and data ...
Making help files ...
Done.
Further steps are described in './anRpackage/Read-and-delete-me'.
export("x")
```

Compare with R 3.6:

```
kevinushey@Kevins-MBP:~/scratch/opkasda
$ R --vanilla --slave -e "x <- 1; package.skeleton()" && cat anRpackage/NAMESPACE
Creating directories ...
Creating DESCRIPTION ...
Creating NAMESPACE ...
Creating Read-and-delete-me ...
Saving functions and data ...
Making help files ...
Done.
Further steps are described in './anRpackage/Read-and-delete-me'.
exportPattern("^[[:alpha:]]+")
```

So this might warrant a closer look at what `package.skeleton()` is doing.

**Comment by kevinushey** [comment]
Looks like this was changed here: https://github.com/wch/r-source/commit/36b27d951fb355f268191a25909ab292a273932d#diff-a1b94fcea8b8818d4371aabf04dc2b3c

**Comment by eddelbuettel** [comment]
Yes, and for _narrow_ case of an empty package I now have it fixed by 
 - removing the _faux_ global symbol
 - adding the now missing `exportPattern()`

Question is what, if anything, to do with the more complicated usage patterns the skeleton helpers support "in theory" and which (as far as I can tell) nobody uses...

**Comment by eddelbuettel** [comment]
Good catch on the commit to R. We should probably stick our heads together, take another look on the weekend or Monday, or report to them.  Looks like a bug, doesn't it?

**Comment by eddelbuettel** [comment]
With @dmurdoch kindly [waving the cluebat at me](https://stat.ethz.ch/pipermail/r-devel/2020-June/079624.html) we can assume the beahvior will stay so I think the simple PR here can be merged  too.
