### ISSUE TITLE
Latest Rcpp not working with shiny

### ISSUE THREAD

**Issue by reisner** [RcppCore/Rcpp#1105]
I have this dockerfile:

```
# syntax = docker/dockerfile:1.0-experimental # https://docs.docker.com/develop/develop-images/build_enhancements/
FROM rocker/r-ver:4.0.0-ubuntu18.04

RUN R -e "install.packages(c('shiny'))"

RUN mkdir /shinyapp

WORKDIR /shinyapp/
ADD ./ ./

EXPOSE 3838

CMD ["R", "-e", "shiny::runApp('/shinyapp', host = '0.0.0.0', port = 3838)"]
```

I get the following error running the container:

```
> shiny::runApp('/shinyapp', host = '0.0.0.0', port = 3838)
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/usr/local/lib/R/site-library/Rcpp/libs/Rcpp.so':
  /usr/local/lib/R/site-library/Rcpp/libs/Rcpp.so: undefined symbol: EXTPTR_PTR
Calls: :: ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
```

If I use an older version of Rcpp, the issue doesnt occur:

```
RUN R -e "install.packages('devtools')"
RUN R -e "devtools::install_version('Rcpp', version = '1.0.4', repos = 'http://cran.us.r-project.org')"
```

Any idea why the newest Rcpp isnt playing nice with this image? 

Thanks!

**Comment by chris-prener** [comment]
I'll add to this that I don't think it is just an issue with shiny. I upgraded to the latest `Rcpp` version on macOS and then got the following error when I went to open the package:

```r
> library(Rcpp)
Error: package or namespace load failed for ‘Rcpp’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so, 6): Symbol not found: _EXTPTR_PTR
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so
  Expected in: /Library/Frameworks/R.framework/Resources/lib/libR.dylib
 in /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so
```

I can also confirm that @reisner's approach to re-installing `v1.0.4` resolves the issue for me.

**Comment by eddelbuettel** [comment]
The ` _EXTPTR_PTR` issue is very annoying but
- not us, but R :-/
- fixed if yoiu use R 4.0.2
- came up here and on SO before

**Comment by chris-prener** [comment]
Great - thanks @eddelbuettel - I may have been too specific with my google searches to find the SO issues. Unfortunately can't update to R 4.0.2 on one of my machines, but glad to know what the solution is!

**Comment by reisner** [comment]
@eddelbuettel Thanks for the info. Curious about why the previous version of `Rcpp` seems to work though?

**Comment by thirdwing** [comment]
@reisner You can get more information from https://github.com/RcppCore/Rcpp/issues/1097 and https://github.com/RcppCore/Rcpp/pull/1098

**Comment by eddelbuettel** [comment]
Sorry, I was just giving a two-hour Rcpp tutorial for useR! when this popped up. As I explained in the break, it is NOT an Rcpp issue but a needed update of your R interpreter which flipped a bit on an ABI part accidentally exposing this change.

So I am closing this.
