### ISSUE TITLE
Installation of package 'Rcpp' had non zero exit status and failed to install

### ISSUE THREAD

**Issue by Shawnmhy** [RcppCore/Rcpp#1107]
Recently I upgraded my Mac OS to 10.15.6, after that one of my R package: largeVis failed to be loaded saying that 'math.h' file cannot be found. I tried to re-install the dependencies such as 'Rcpp' and the same error occurred:

```
> `installing the source package ‘Rcpp’

trying URL 'https://cran.rstudio.com/src/contrib/Rcpp_1.0.5.tar.gz'
Content type 'application/x-gzip' length 2950521 bytes (2.8 MB)
==================================================
downloaded 2.8 MB

* installing *source* package ‘Rcpp’ ...
** package ‘Rcpp’ successfully unpacked and MD5 sums checked
** libs
/usr/local/clang4/bin/clang++ -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include/  -I/usr/local/include   -fPIC  -Wall -g -O2  -c api.cpp -o api.o
In file included from api.cpp:24:
In file included from ../inst/include/Rcpp.h:27:
In file included from ../inst/include/RcppCommon.h:29:
In file included from ../inst/include/Rcpp/r/headers.h:67:
In file included from ../inst/include/Rcpp/platform/compiler.h:100:
In file included from /usr/local/clang4/bin/../include/c++/v1/cmath:305:
/usr/local/clang4/bin/../include/c++/v1/math.h:301:15: fatal error: 'math.h' file not found
#include_next <math.h>
              ^~~~~~~~
1 error generated.
make: *** [api.o] Error 1
ERROR: compilation failed for package ‘Rcpp’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp’
Warning in install.packages :
  installation of package ‘Rcpp’ had non-zero exit status`
```

I have seen somebody met the similar problem on Mac OS 10.14, but how to solve this on 10.15 OS? Thank you!

**Comment by eddelbuettel** [comment]
I don't run macOS myself so someone else will need to help you -- but if you search among closed issues you _will see that we had several prior reports_ of the `#include_next` issue.  It is in some way related to how macOS is actually not ready for R work as shipped and requiring _you_ to do some legwork.  And, as a near religious ritual, of course changes every few moon phases^Hevery macOS release.

Maybe @coatless will pipe in. If he doesn't he could just read what he already wrote e.g. [here](https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/).  Good luck!

**Comment by coatless** [comment]
@Shawnmhy when upgrading macOS, you will need to reinstall Xcode Command Line Tools. 

Open Terminal and type:

```bash
sudo xcode-select --install
```

Alternatively, you can watch the process here: http://www.youtube.com/watch?v=Z01lzHNrSdU

[![View installation video for Xcode CLI on YouTube](http://img.youtube.com/vi/Z01lzHNrSdU/0.jpg)](http://www.youtube.com/watch?v=Z01lzHNrSdU "Xcode CLI Installation")

**Comment by eddelbuettel** [comment]
Thanks, as always, @coatless.

Closing this as it is not a Rcpp bug but a macOS err, hmm, well, "feature".
