### ISSUE TITLE
Rcpp::interfaces(r, cpp) raises "PACKAGE_RcppExport_registerCCallable" not available for .Call()

### ISSUE THREAD

**Issue by ms609** [RcppCore/Rcpp#1110]
Following a [StackOverflow discussion](https://stackoverflow.com/questions/63751526), I've created a [minimal package](https://github.com/ms609/RcppExports) containing a single c++ file:

```c++
#include <Rcpp.h>
using namespace Rcpp;
// [[Rcpp::interfaces(r, cpp)]]


// [[Rcpp::export]]
void hello_world() {
  Rcout << "Hello, world!\n";
}
```

I've also added a housekeeping .R file:
```r
#' @useDynLib ExportTest, .registration = TRUE
.onUnload <- function (libpath) {
  library.dynam.unload("ExportTest", libpath)
}
```

When I run `Rcpp::compileAttributes()`, relevant files are generated in `inst\include` alongside the usual `*\RcppExports.*` files.

But when I `devtools::document()` the package, I see

```
Error in .Call("_ExportTest_RcppExport_registerCCallable", PACKAGE = "ExportTest") : 
  "_ExportTest_RcppExport_registerCCallable" not available for .Call() for package "ExportTest"
```

Now, interestingly, I notice that  `useDynLib(ExportTest)` was not added to `NAMESPACE`, as expected -- presumably `document()` fails before it reaches this stage.  If I manually add this line to `NAMESPACE` (see [branch](https://github.com/ms609/RcppExports/tree/NAMESPACE)), then the package loads successfully.

This doesn't seem to be quite the same issue as I'm encountering in the 'TreeTools' package, whose NAMESPACE file already contains a `useDynLib` line, but as it gives rise to the same error I'm hoping that it may be related?

`sessionInfo()`:
```
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_2.3.1 usethis_1.6.1 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5        compiler_4.0.2    prettyunits_1.1.1 remotes_2.2.0     tools_4.0.2       testthat_2.3.2   
 [7] digest_0.6.25     pkgbuild_1.1.0    pkgload_1.1.0     memoise_1.1.0     rlang_0.4.7       cli_2.0.2        
[13] rstudioapi_0.11   xfun_0.16         withr_2.2.0       stringr_1.4.0     roxygen2_7.1.1    knitr_1.29       
[19] xml2_1.3.2        desc_1.2.0        fs_1.4.2          rprojroot_1.3-2   glue_1.4.1        R6_2.4.1         
[25] processx_3.4.3    fansi_0.4.1       sessioninfo_1.1.1 callr_3.4.3       purrr_0.3.4       magrittr_1.5     
[31] backports_1.1.8   ps_1.3.3          ellipsis_0.3.1    ExportTest_1.0    assertthat_0.2.1  stringi_1.4.6    
[37] crayon_1.3.4 
```
C++ compiler: `C:/rtools40/mingw64/bin/"g++ -std=gnu++11`

**Comment by eddelbuettel** [comment]
Thanks for bring this over from SO and creating a package.  The next step may be to use with standard documented functions, as (at least to me) `devtools::document` is _not_ part of the documented Rcpp toolbox, as common and popular as it may,  And runnng `compileAttributes()` (which I tend to do on the command-line via a `littler` wrapper, but that is just a personal preference).  And that works just fine.

Reading the question as it is rewritten here, do you _maybe_ just have the wrong expectation?  There are _two_ desired uses for your line `// [[Rcpp::interfaces(r, cpp)]]`:

1.  `hello_world()` needs to still be callable from the package itself via the `[[Rcpp::exports]]` tag

2. `hello_world()` needs to be _callable from another package via a direct C++ to C++ call which is what exporting functions to other packages is about and that the `cpp` interface does by creating the two header files in `inst/include`.  You actual test is now yet another package (!!) setting up `LinkingTo: ExportTest` and adding `#include <ExportTest.h>` and then calling the (correctly inlines and all) function `ExportTest::hello_world()`.

None of these involve `.Call`.  In fact, come to think about it, no Rcpp use case involves sending the user to `.Call`.  Maybe our documentation needs some brightening up?  Or is this "merely" an issue in the `devtools` function you call?

**Comment by eddelbuettel** [comment]
@ms609 Any comments or thoughts?

**Comment by ms609** [comment]
Thanks for taking this forwards, and sorry for the slow reply, I haven't had the chance to follow up thoroughly.

I am hoping to call the C++ function from within C++ in a second package.  At present the second package (containing LinkingTo and #include) isn't able to find `TreeTools.h` -- I've not had time to try with `ExportTest.h` yet.

I also haven't tried installing with `R CMD install`, which I suppose is the supported alternative to `devtools` -- I believe that RStudio uses `devtools::install()` by default too.  

Yes, it's possible that it's a `devtools` issue; it'll take a bit of thinking to work out how to effectively get to the point at which the issue is arising.   Probably the R CMD install is the next thing for me to try.

**Comment by ms609** [comment]
NB the call to `.Call` that seems to be the issue in 'TreeTools' is added by `compileAttributes()` to `R\RcppExports.R`:

```r
# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_TreeTools_RcppExport_registerCCallable', PACKAGE = 'TreeTools')
})
```

**Comment by eddelbuettel** [comment]
Well, I cloned your repo and did what I usualy do here, and I had no issue. `compileAttributtes()` followed by build and check.  No complaints.  

I call only urge to minimize the example to a standard [MCVE](https://stackoverflow.com/help/minimal-reproducible-example).  And for Rcpp that would not entail `devtools` (and I can't really see it getting in the way but one never knows).

**Comment by eddelbuettel** [comment]
I think the culprit is the `devtools` / `roxygen` nexus.  This cannot work:

```
edd@rob:~/git/rcppexport_issue1110(master)$ cat NAMESPACE 
# Generated by roxygen2: do not edit by hand

edd@rob:~/git/rcppexport_issue1110(master)$ 
```

**Comment by eddelbuettel** [comment]
Replace the irrepairably borked `NAMESPACE` which does *not* come from our skeleton generators with a standard one such as

```sh
edd@rob:~/git/rcppexport_issue1110(master)$ cat NAMESPACE 
useDynLib(ExportTest, .registration=TRUE)
importFrom(Rcpp, evalCpp)
exportPattern("^[[:alpha:]]+")
edd@rob:~/git/rcppexport_issue1110(master)$ 
```

and you're golden:

```sh
edd@rob:~/git/rcppexport_issue1110(master)$ rcc.r   # simple wrapper around rcmdcheck
── R CMD build ─────────────────────────────────────────────────────────────────────
✔  checking for file ‘.../DESCRIPTION’
─  preparing ‘ExportTest’:
✔  checking DESCRIPTION meta-information
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘ExportTest_1.0.tar.gz’
   
── R CMD check ────────────────────────────────────────────────────────────────────────────────
─  using log directory ‘/tmp/file18cbae1c958133/ExportTest.Rcheck’
─  using R version 4.0.2 (2020-06-22)
─  using platform: x86_64-pc-linux-gnu (64-bit)
─  using session charset: UTF-8
✔  checking for file ‘ExportTest/DESCRIPTION’
─  checking extension type ... Package
─  this is package ‘ExportTest’ version ‘1.0’
─  package encoding: UTF-8
✔  checking package namespace information
✔  checking package dependencies (796ms)
✔  checking if this is a source package
✔  checking if there is a namespace
✔  checking for executable files
✔  checking for hidden files and directories
✔  checking for portable file names
✔  checking for sufficient/correct file permissions
✔  checking whether package ‘ExportTest’ can be installed (1.3s)
✔  checking installed package size
✔  checking package directory
✔  checking DESCRIPTION meta-information
✔  checking top-level files
✔  checking for left-over files
✔  checking index information
✔  checking package subdirectories
✔  checking R files for non-ASCII characters
✔  checking R files for syntax errors
✔  checking whether the package can be loaded
✔  checking whether the package can be loaded with stated dependencies
✔  checking whether the package can be unloaded cleanly
✔  checking whether the namespace can be loaded with stated dependencies
✔  checking whether the namespace can be unloaded cleanly
✔  checking loading without being on the library search path
✔  checking dependencies in R code
✔  checking S3 generic/method consistency (398ms)
✔  checking replacement functions
✔  checking foreign function calls
✔  checking R code for possible problems (885ms)
W  checking for missing documentation entries
   Undocumented code objects:
     ‘hello_world’
   All user-level objects in a package should have documentation entries.
   See chapter ‘Writing R documentation files’ in the ‘Writing R
   Extensions’ manual.
✔  checking line endings in C/C++/Fortran sources/headers
✔  checking compilation flags used
✔  checking compiled code
─  checking examples ... NONE
✔  checking PDF version of manual (834ms)
   
   See
     ‘/tmp/file18cbae1c958133/ExportTest.Rcheck/00check.log’
   for details.
   
   
edd@rob:~/git/rcppexport_issue1110(master)$ 
```

**Comment by ms609** [comment]
I've updated the `NAMESPACE`, and added a `c` function to the 'ExportTest' package (which is I think the critical complicating factor).

Now I can build with `R CMD build ExportTest`, but `R CMD INSTALL ExportTest` fails.
Hopefully you will now be able to reproduce this behaviour.

Suspected culprit: `ExportTest-init.c` contains 
```c 
void R_init_ExportTest(DllInfo *dll) {
  R_registerRoutines(dll, cMethods, callMethods, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
```
whereas `compileAttributes()` would otherwise add
```
RcppExport void R_init_ExportTest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
```

I had thought that the `RcppExport` prefix (which cannot be added within a `.c` file) might be the issue, but it looks like the problem might lie with `R_forceSymbols`. It'll be interesting to know whether you are able to reproduce the issue from the revised repo.

**Comment by eddelbuettel** [comment]
> and added a c function to the 'ExportTest' package

Why?

**Comment by ms609** [comment]
Because, as mentioned in the original comment, changing the `NAMESPACE` fixed the problem in the example file, and I'm trying to produce a reproducible example that replicates the problems I am encountering in the TreeTools package.

**Comment by ms609** [comment]
So it sounds like you are saying I have to choose between C functions (which are necessary as they are from a pre-existing library) and Rcpp?  That's a shame, though I can understand why that might be the case.

**Comment by eddelbuettel** [comment]
Ok, let's revisit TreeTools another time / see how we can (re-)organize this.

Let me just bring closure to your (most helpful!) `ExportTest` package.  If I leave it free of C code, keep the repaired `NAMESPACE` and install it, then all that Rcpp promises to do _actually works as advertised_:

```r
R> cppFunction("void checkCall() { ExportTest::hello_world(); }", \
                            includes = "#include <ExportTest.h>", 
                            depends="ExportTest")
R> checkCall()
Hello, world!
R> 
```

**Comment by eddelbuettel** [comment]
So I just demontrated that the (promised) exports mechanism works.  So in the narrow sense we can close the SO question and this issue.

In the wider sense we have to work our how you can also have C functions.  Simplest alternative: Can you make them C++?

**Comment by eddelbuettel** [comment]
Or maybe we move the (legacy) C code to another part and create C++ shims to call them.  The shims can then be exported to R by Rcpp.

But please understand that Rcpp never offered to also magically support C interface.  Simply not our scope.

**Comment by ms609** [comment]
I've got to scoot now, but I'll think about these suggestions and ponder a way forwards.  Thanks again for your help getting to the bottom of this.

**Comment by eddelbuettel** [comment]
Gotta run too.  MCVEs really are key to crystalize issues.

**Comment by eddelbuettel** [comment]
@ms609 How are we doing here? Can this be closed as the promised-to-be-working behavior has been seen to be working?

**Comment by eddelbuettel** [comment]
Closing for lack of follow-up.  If it needs reopening let us know.
