### ISSUE TITLE
InternalFunction memory leak

### ISSUE THREAD

**Issue by FBartos** [RcppCore/Rcpp#1114]
Hi, I encountered a memory leak while trying to use R::optim from within Rcpp. I tried the R-help mailing list and stack-overflow, and it has been suggested to me to fill an issue since it seems like that the Rcpp::InternalFunction is leaking memory.
the stack-overflow ticket: https://stackoverflow.com/questions/64451927/how-calling-statsoptim-from-rcpp-causes-memory-leak

code for reproducing the leak:
Rcpp:
```
#include <Rcpp.h>
using namespace Rcpp;
double objective_function(double x){
  double obj = .666 - x;
  return pow(obj, 2);
}
// [[Rcpp::export(leak)]]
double leak(double a, double b){
 

  // Extract R's optim function
  Rcpp::Environment stats("package:stats");
  Rcpp::Function optim = stats["optim"];
 
  // Call the optim function from R in C++
  Rcpp::List opt_results = optim(Rcpp::_["par"]    = .5,
                                 Rcpp::_["fn"]     = Rcpp::InternalFunction(&objective_function),
                                 Rcpp::_["method"] = "Brent",
                                 Rcpp::_["lower"]  = a,
                                 Rcpp::_["upper"]  = b);
 
  // Extract out the estimated parameter values
  double mu = opt_results[0];
 
  // Return estimated values
  return mu;
}
```
R
```
repeat{
  leak(0, 1)
}
```
I tried exporting the objective_function to R and optimizing it there, but it did not cause the leak.

**Comment by eddelbuettel** [comment]
@kevinushey Thanks for the follow-up at StackOverflow and the two pointers (copying here)

- instantiating with `false` for `delete_finalizer` https://github.com/RcppCore/Rcpp/blob/97222bb753c4cd76a4cef7d33c2bfc2e305d1158/inst/include/Rcpp/generated/InternalFunction__ctors.h#L35-L38
- defintion with default `true` https://github.com/RcppCore/Rcpp/blob/97222bb753c4cd76a4cef7d33c2bfc2e305d1158/inst/include/Rcpp/XPtr.h#L88-L106

As you surmise there it isn't exactly clear why we pick `false`.   (It so happens that I had a case this summer where I needed an even more ensure finalizer than I was getting with a `true` so I did something else closer to the C API and had been meaning to bring that back to Rcpp.  Right now I know little about `InternalFunction`.)

**Comment by eddelbuettel** [comment]
We can do the following:

First, modify the (very helpful !!) reproducible example to add the end
```c++
/*** R
print(Sys.getpid())
repeat{
  leak(0, 1)
}
*/
```

Second run this with the current Rcpp version via `Rcpp::sourceCpp()` , noting the printed pid and running `htop -p $PID` and using the pid printed.  This shows a leak as the RES memory column keeps growing.

Third, flip the `false` to `true` in all instances of the constructor in `Rcpp/inst/include/Rcpp/generated/InternalFunction__ctors.h`. The resulting package still checks fine, and installs.

Fourth, re-running it as before shows RES stable.  No leak.

I'll probably make a PR off the simple change.
