### ISSUE TITLE
RNG state related warnings when using future

### ISSUE THREAD

**Issue by andrewwbutler** [RcppCore/Rcpp#1116]
When no `.Random.seed` exists initially, it appears that Rcpp is setting this value upon returning back to R. This can potentially cause warnings when used in conjunction with the `future` package (see https://github.com/HenrikBengtsson/future/issues/440 for a discussion). Below is a reproducible example: 

```R
library(future)
plan(sequential)
Rcpp::cppFunction("bool hello() { return TRUE; }")
f <- future(hello())
v <- value(f)
```

This can be worked around by first initializing with a dummy random number but just wanted to bring this up in case this is an edge case worth addressing. Thanks!

<details>
<summary> sessionInfo()  if it's useful </summary>

```R
R version 4.0.1 (2020-06-06)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] future_1.19.1

loaded via a namespace (and not attached):
[1] compiler_4.0.1   tools_4.0.1      parallel_4.0.1   listenv_0.8.0   
[5] Rcpp_1.0.5       codetools_0.2-16 digest_0.6.27    globals_0.13.1
```
</details>

**Comment by eddelbuettel** [comment]
Per "Dr Dr it hurts when I do this" can I suggest you just don't use `cppFunction()` if you don't like the side effect?

For proper package you call tell `compileAttributes` with an option to not touch RNG states.

**Comment by eddelbuettel** [comment]
As just noted over in https://github.com/HenrikBengtsson/future/issues/440, you _can_ say `rng=false` as an option in the `export()` tag.

**Comment by andrewwbutler** [comment]
I see. Yes, `rng=false` via the `export()` tag is the appropriate way to handle this. Sorry for the bother.

**Comment by eddelbuettel** [comment]
It's all moderately complicated as you then need to know what to do with RNG seeding etc pp.  But I guess the proper 'knowing what to do' is what `future` is all concerned with in the context of multiple threads and process.  A joint howto or Rcpp Gallery piece might be a good idea.  If you have the bandwidth or energy to write up a few paragraphs...
