### ISSUE TITLE
documentation for compileAttributes with RCPP_MODULE

### ISSUE THREAD

**Issue by tdhock** [RcppCore/Rcpp#1119]
Hi @eddelbuettel I noticed that compileAttributes will generate code in RcppExports.cpp when there are RCPP_MODULE declarations in the other *.cpp files. Can this behavior be documented, please? Here is my suggested documentation that would have been helpful for me to understand how compileAttributes works with RCPP_MODULE declarations, https://github.com/RcppCore/Rcpp/pull/1118/commits/68ef75693f7fc1da2b69785e6301174dcf27ff86

**Comment by tdhock** [comment]
Suggested addition to man/compileAttributes.Rd: "This function also scans the C++ source code for \code{RCPP_MODULE} declarations, and generates the corresponding required entries in \code{src/RcppExports.cpp}."

**Comment by eddelbuettel** [comment]
Please stop filing issues.

**Comment by tdhock** [comment]
ok

**Comment by eddelbuettel** [comment]
They are _all_ on the same _core isssue_ of Rcpp Modules and Rcpp Attributes having complicated interactions.  I do not think that spreading a discussion about that over _four distinct issues_ is helping.

**Comment by tdhock** [comment]
hi again, I was just trying to help by explaining the issues I ran into (which seemed related but separate to me), and possible fixes that would have helped me at least. 
really sorry for the trouble again and feel free to close the issues if they are not useful for you.

**Comment by eddelbuettel** [comment]
You get my attention with a single issue.  I usually respond.   I do not think you get four times my attention with four issues.  

Anyway, water down the drain now.    Please feel free to suggest steps forward in any of these issues.

**Comment by eddelbuettel** [comment]
Here is another related issue where someone else ambushed his own attempts at Rcpp Modules but destroying the `NAMESPACE` file courtesy of `roxygen2::roxygenize()`: 
https://stackoverflow.com/questions/64879434/rcpp-modules-to-expose-class-error-loadmodule-not-found
