### ISSUE TITLE
Installation error R 4.0.2 mac os Catalina 10.15.7

### ISSUE THREAD

**Issue by cmwerner** [RcppCore/Rcpp#1123]
R Version 4.0.2
OS: Catalina 10.15.7

I installed RCPP using

```
install.packages("Rcpp", repos = "https://rcppcore.github.io/drat")
```

The installation seemed to work and nothing is printed after 
```
library(Rcpp)
```

But when I tried to use Rcpp with a simple command

```
evalCpp("1+1")
```

I get the following errors 

```
ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sourceCpp_2.so] Error 1
clang++ -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I"/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include" -I"/private/var/folders/s4/66_91_h91s75tf5cwjhq9vzh0000gn/T/RtmpbGLYq6/sourceCpp-x86_64-apple-darwin17.0-1.0.5" -I/usr/local/include   -fPIC  -Wall -g -O2  -c file2ed92e9ceaa7.cpp -o file2ed92e9ceaa7.o
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o sourceCpp_2.so file2ed92e9ceaa7.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
Error in sourceCpp(code = code, env = env, rebuild = rebuild, cacheDir = cacheDir,  : 
  Error 1 occurred building shared library.
```

I've tried uninstalling and reinstalling rcpp, restarting R and my computer, checking to make sure XCode and command line tools are installed. I also tried the solution here: https://stackoverflow.com/questions/64565863/rcpp-not-working-on-r-3-6-3-macos-catalina-10-15-7 but it didn't help. Any advice or ideas would be appreciated.

**Comment by eddelbuettel** [comment]
You will need to find a kind soul that is also a macOS user to walk you through.  @coatless provides writeups here:  https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/

Rcpp passes fine at CRAN including their setup, see this link https://cloud.r-project.org/web/checks/check_results_Rcpp.html and this description of their machines: https://cloud.r-project.org/web/checks/check_flavors.html

As there is no evidence of the _package_ being at fault (as opposed to the maybe more-difficult-than-elsewhere setup) I will close this.  Please do reopen it if you find something amiss in the package.
