### ISSUE TITLE
Memory can't be released when function returns a list?

### ISSUE THREAD

**Issue by donald-keighley** [RcppCore/Rcpp#1124]
I wrote an Rcpp function that returns a large list of arbitrarily sized vectors.  After I use the list in R, I need to remove it to free memory.  Unfortunately, after I remove it using rm() and gc() the memory does not appear to be freed in the Windows Task Manager.  Oddly, if I create a nearly identical function that returns a NumericVector instead of a List the memory is released.

Also, if I run the function that won't release the memory repeatedly, the problem does not compound.  Only the memory from the first run is not released.  This is the case even if I output a very small list followed by a very large one (which is my current workaround).

This is a simplified version of the function.  Before I run it, the Task Manager shows R using about 400MB of memory.  After R is using about 1.3GB even after rm() and gc().

```{r}
library(Rcpp)

cppFunction('List makeList(int n) {
  std::vector<std::vector<int>> indices(n, std::vector<int>());
  for (int i = 0; i < n; i++) {
    for (int j = 1; rand() % 10; j++){
      indices[i].push_back(j);
    }
  }
  List indicesOut = wrap(indices);
  return indicesOut;
}')

indexList = makeList(10000000)
rm(indexList)
gc()

```

This next function behaves as I would expect.  If I restart the session the task manager shows 400MB before I run the function, 1.3GB after, and 400MB after rm() and gc().

```{r}
library(Rcpp)

cppFunction('NumericVector makeVector(int n) {
  std::vector<int> indices;
  for (int i = 0; i < n; i++) {
    for (int j = 1; rand() % 10; j++){
      indices.push_back(j);
    }
  }
  NumericVector indicesOut = wrap(indices);
  return indicesOut;
}')

indexVector = makeVector(10000000)
rm(indexVector)
gc()
```

Hopefully this is reproducible enough.  Unfortunately, I wasn't able to find a programmatic way to get R to show how much memory Windows thinks it's using.

**Comment by eddelbuettel** [comment]
This is a tricky and touchy topic, made more complicated by the fact that R does not immedialy release memory even when you call `rm()` and `gc()` -- managed memory means it does as needed.

What you do in the second example reads more cleanly and looks cleaner---because we _know_ that STL objects will call the desctructor and end of scope, `indices` will be gone.  (BTW you could also write that function as returning `std::vector<int>` and save the temporary `indicesOut` object.)

But the first solution may actually be better, even if the _R object created in the function is passed on_ and may therefore appear to inflate memory use.  But as I said, it's murky.  I don't think we have leak here.  The only way to _really_ tell is via memory profiling, see _Writing R Extensions_ for more.

**Comment by donald-keighley** [comment]
Fair enough.  The first solution performs much better for my purposes so I'll continue to use that.  Never done memory profiling, but I may go down that rabbit hole if I start having real issues.  Thanks!

**Comment by eddelbuettel** [comment]
Memory profilig is not as hard or tricky as it sounds.  And there is always the quick / poor man's version of letting code run in a loop and watching `top` or `htop` (or its Windows equivalent)....

**Comment by donald-keighley** [comment]
I experimented some more and I think you're right, there is no leak.  For instance if I create a list of variable length vectors in R using lapply, remove it, and perform garbage collection the memory in the task manager does not drop.  So, it's just something about how R handles lists of vectors regardless of whether they're come from Rcpp or not.

```{r}
test = lapply(1:1000000, function(x) c(1:sample(1:1000,1)))
rm(test)
gc()
```

You can also do this several times in a row and the memory in the task manager doesn't change.  So, I think the memory is actually released within R and can be reused, it's just not given back to the system, which isn't really an issue... and if it is an issue it's an issue with R not Rcpp.

**Comment by eddelbuettel** [comment]
I think that is exactly right, having spend some years (decades, actually, ...) around the r-devel list.  The garbage collection in R is not "eager" so one should not think of a `new`/`delete` or `malloc`/`free` mental model:  R will release memory _when R things it is good to do so_.  There are some profiling tools and helpers, but even the more "heuristic" argument we made here via `top` or the task manager is good enough to reveal a leak when there is one.  (We had bugs...)  But yes, the default mode is not leaking.

**Comment by kevinushey** [comment]
This could also depend on how the OS / runtime library decided to manage memory for the application. IIUC if the OS sees an application reserve a large amount of memory up-front, it may decide to just keep that memory reserved for the application under the assumption that it may want to re-use that memory soon after. (You might see that memory reclaimed if you start using a separate application that requires more memory?)
