### ISSUE TITLE
Allow silent R output

### ISSUE THREAD

**Issue by DavZim** [RcppCore/Rcpp#1126]
As outlined in a [SO question](https://stackoverflow.com/questions/65241069/rcpp-with-embedded-r-code-show-no-output-of-r-code), when sourcing a `cpp`-file with embedded R code, there is no option to silence the R output.

This can be seen by running:
```R
Rcpp::sourceCode(code='
#include <Rcpp.h>
// [[Rcpp::export]]
Rcpp::NumericVector timesTwo(Rcpp::NumericVector x) {
  return x * 2;
}
/*** R
times_two <- function(x) timesTwo(x)
*/
')
#> times_two <- function(x) timesTwo(x)
```
I opened this issue so we can discuss if this is needed.

I use embedded R code to define an R wrapper around a cpp function in one file, reducing the number of files needed (e.g., define a cpp function, which returns a data.frame, then call some `dplyr` or `data.table` code on the data.frame). I would like to prevent printing the R code when I call `sourceCpp()`, for example in some kinds of rmarkdown format.

As pointed out by [MrFlick](https://stackoverflow.com/questions/65241069/rcpp-with-embedded-r-code-show-no-output-of-r-code?noredirect=1#comment115339879_65241069), it would require changing the [`Attributes.R` L217](https://github.com/RcppCore/Rcpp/blob/e0353c7e1eb57f54e01a2ef0319d74b78e476f18/R/Attributes.R#L217) call to `source()`, which could include an option `showROutput` or `silenceR` or similar.

**Comment by eddelbuettel** [comment]
As I said on SO, I am somewhat ambivalent about it:

- if you don't want R code to run or show, just don't include it
- you can wrap `suppressMessages()` (my fave) or `captureOutput()` around it
- (R)Markdown and `knitr` blocks give you very fine control about what to show _up to the chunk line number to control it_
- you could create a trivial `mySourceCpp()` which maybe strips the R code, and another variant that takes the R code in a different file or...

So colour me not-convinced.  We're also in a quasi-freeze as I am switching to a six-month release cycle with a January release coming.  Given the incidents around release 1.0.4 and the very disappointing and childish community behavior experienced there I have little inclination to accept changes close to release as we did then.  So we could talk about it for July 2021.  But is it _really_ worth it?



That said, the change is trivial and close to meaningless and may never reach than a handful of user all of whom could

**Comment by kevinushey** [comment]
I think the simple fix here is:

1. Add an option `echo` (or `quiet`?) to `sourceCpp()`;
2. Propagate that down to the `source()` call.

I don't have strong feelings either way but agree with the general inclination to avoid changes immediately prior to release. At least this should be a safe change though.

**Comment by eddelbuettel** [comment]
Yes this is, to paraphrase, Douglas Adams "mostly harmless".  But we need it in `sourceCpp()` and `cppFunction()`.

**Comment by eddelbuettel** [comment]
This was more or less a two-liner and has been added.  Stll not convinced it is all that useful but hey we aim to please :)
