### ISSUE TITLE
Implement check.names as DataFrame::create() option

### ISSUE THREAD

**Issue by PMSeitzer** [RcppCore/Rcpp#1131]
In R,
`df <- data.frame("[M+H]+"= c(0,1,2), "[M-H]-"=(c(3,4,5)))`
produces
```
  X.M.H.. X.M.H...1
1       0         3
2       1         4
3       2         5
```

While
`df <- data.frame("[M+H]+"= c(0,1,2), "[M-H]-"=(c(3,4,5)), check.names=FALSE)`
produces
```
  [M+H]+ [M-H]-
1      0      3
2      1      4
3      2      5
```

In Rcpp, it is possible to encode the `stringsAsFactors` option via 
```
Rcpp::create(
        Named("[M+H]+")=NumericVector(0,1,2),
        _["stringsAsFactors"] = false
        )
```

It would be nice to offer the same for `check.names`.  Currently, 
```
Rcpp::create(
        Named("[M+H]+")=NumericVector(0,1,2),
        _["stringsAsFactors"] = false,
        _["check.names"] = false
        )
```
adds a `LogicalVector` with all values `false`.

Reading the code, it appears the `stringsAsFactors` option is handled here:
https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/DataFrame.h#L165

I would suggest that `check.names` could also be handled in a similar way.

**Comment by eddelbuettel** [comment]
Hm. Interesting. May I ask what your real motivation is here?   `check.names` actually has a good underlying motivation, namely making the column ids be permitted R identifiers. 

I see not a lot of reason to deviate from that goal of keeping valid headers apart for maybe ... pritty printing which might be more cleanly addressed at the R level by subclassing and adding a custom `print()` method.  

That said, _in principle_ this could be done.  Would you be able to work on a PR?

**Comment by eddelbuettel** [comment]
BTW you can also skirt this by setting the name in a second step:

### Code

```c++
#include <Rcpp.h>

// [[Rcpp::export]]
Rcpp::DataFrame foo(Rcpp::NumericVector v, Rcpp::CharacterVector n) {
  Rcpp::DataFrame df = Rcpp::DataFrame::create(Rcpp::Named("x") = v);
  df.attr("names") = n;
  return df;
}

/*** R
foo(1:4, "[M+H]+")
*/
```

### Output

```r
> Rcpp::sourceCpp("/tmp/df.cpp")

> foo(1:4, "[M+H]+")
  [M+H]+
1      1
2      2
3      3
4      4
> 
```

Good enough?

**Comment by PMSeitzer** [comment]
As you suggested, my motivation was for printing/display.

Thank you for the prompt response and `df.attr("names")=n` suggestion, this solution will work well for me.
