### ISSUE TITLE
Puzzle on denominator for double type

### ISSUE THREAD

**Issue by ctex77** [RcppCore/Rcpp#1134]
It appears that Rcpp prefers denominator as a variable instead of as a value. The result is correct for a denominator being a variable, but treats it as integer by ignoring the digital numbers after decimal point for a denominator being a value. A minimum example is test01.cpp as follows:

```c++
#include <Rcpp.h>
using namespace Rcpp;
//[[Rcpp::export]]
NumericVector tz1(){
    double xx1=3;
    double yy1=5/3, yy2=5/xx1;
    Rcout << "yy1:" << yy1 << ", yy2: " << yy2 << "\n";
    Rprintf("yy1: %f, yy2: %f.\n", yy1, yy2);
    NumericVector zz={yy1,yy2};
    return(zz);
}
```
I run "sourceCpp(test01.cpp)" after loading the Rcpp library, and then submit the command of "tz1()" in the Rstudio console. It shows only yy2 is as expected. y1 is surprisedly 1. Could anybody help to clear the possible issue? Thanks.
My running environment is R4.0.2, RStudio 1.1.442, Rtools4.0.0, Windows10 64bit.

**Comment by ctex77** [comment]
Sorry for little knowledge of C. Either (double)5/3 or 5/(double)3 produces the same result as expected as 5/xx1.

**Comment by eddelbuettel** [comment]
Yes. That is a basic feature of how C and C++ operate.  You can also write `double yy = 5.0 / 3.0;` (and converting just one is enough).  

However this has nothing to do with Rcpp, and we recommend using StackOverflow or the mailing list for such questions.  Please try them in the future as you will get a friendly amswer there too, and likely sooner.
