### ISSUE TITLE
compiler warning from DataFrame.h when including Rcpp

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/Rcpp#1137]
I saw this while compiling `reticulate` with latest Rcpp on macOS:

```
In file included from python.cpp:4:
In file included from /Users/kevinushey/Library/R/4.0/library/Rcpp/include/Rcpp.h:57:
/Users/kevinushey/Library/R/4.0/library/Rcpp/include/Rcpp/DataFrame.h:136:18: warning: unused variable 'data' [-Wunused-variable]
            SEXP data = Parent::get__();
                 ^
```

And indeed, `data` is read but never used here:

https://github.com/RcppCore/Rcpp/blob/0ba1b550d64bbe98d622d3032acd91fc6c1436c2/inst/include/Rcpp/DataFrame.h#L133-L155

Looks like it was introduced with https://github.com/RcppCore/Rcpp/commit/d800e2ae7afa1f9b1eac99d1bfb3c1dadd267132. I think we can just remove the offending line.

**Comment by eddelbuettel** [comment]
Interesting.  Yes, that is new (in 1.0.6) code by @waltersom that hasn't seen too much exposure yet as 1.0.6 is new-ish.  

It does look like we can trim it off.    Thoughs, @waltersom?   No need for a PR we can clean it up alongside whatever comes up next.

**Comment by waltersom** [comment]
I agree, should be fine to remove, I guess it was part of an earlier
attempt by me that should have been taken out earlier.
