### ISSUE TITLE
Rcpp::Function finalizer with OpenMP firstprivate clause

### ISSUE THREAD

**Issue by helske** [RcppCore/Rcpp#1142]
While testing my bssm package with various debugging tools provided by Winston Chang’s [r-debug images for Docker](https://github.com/wch/r-debug), I stumbled upon an issue with `Rcpp::Function` and OpenMP. I have a class that contains a member of type `Rcpp::Function`, but even though this function is not called within parallel OpenMP block, I get segfault when running the code in R compiled with `-DTHREADCHECK`.

I managed to create a simpler case of this behaviour:

```
#include "omp.h"
#include <Rcpp.h>

// [[Rcpp::plugins(openmp)]]
// [[Rcpp::export]]
void foo(Rcpp::Function fun) {

  Rcpp::Function fun2(fun);

#pragma omp parallel for num_threads(2) firstprivate(fun2)
  for (unsigned int i = 0; i < 10; i++) {
    double y = i;
  }
}
```
running say `foo(dnorm)` gives `Fatal error: Wrong thread calling 'RunFinalizers'`. Note that if I use `firstprivate(fun)` there is no error (or if I remove the whole `firstprivate` clause). 

However, I see no issues in practice when `-DTHREADCHECK` is not used, so this might not be a very relevant or urgent issue (if it is an issue at all). Just thought to let you know in case it is not known already...

**Comment by eddelbuettel** [comment]
Remember that Rcpp Attributes builds other glue functions around the code you submit, so first instictive guess is that your segment thusly appears in a context where it caused trouble.

I am with you that a properly shield `#pragma` should be (and generally is) safe.  So my approach here would be to keep `foo()` as an exported function but have it call, say, `foo_impl()` which you don't wrap, and which localises the OpenMP use.

**Comment by eddelbuettel** [comment]
The general rule (which we are for example for clear about in RcppParallel which is in fact explicitly parallel) is that nothing that R may have control over (and might execute a random garbage collection) should in a multithreaded context.   I know it sounds extra restrictive but I am really not sure that have a `Function` (_i.e._ `SEXP`) as a member can work reliably.   Not really an Rcpp issue but more one of how R does things.

**Comment by helske** [comment]
Yes, I've been trying to adhere to the rule of never mixing anything R related with parallelization but was mostly concerned about actually using SEXP etc inside the parallel region and didn't realize that even sharing but not explicitly calling, assigning etc. might be problematic.  While everything has been working fine in practice (so far), I now removed `Function` from the class and use it as an independent variable where needed instead. This way I can, fortunately, avoid using it anywhere near OpenMP. Made the code bit uglier, but that's ok.

You're of course right that this isn't really an Rcpp issue, so I'll close the issue.
