### ISSUE TITLE
as<CharacterVector>(Named non-CharacterVector)

### ISSUE THREAD

**Issue by Bijaelo** [RcppCore/Rcpp#1143]
I'm back!

While toying around in the category of not-very-useful problems, I noticed a somewhat obscure "bug"-ish (maybe it is not a bug?) when converting a named Integer/Numeric `SEXP` directly to `CharacterVector`. 

```R
Rcpp::sourceCpp(code = 
                  "
#include <Rcpp.h>

// [[Rcpp::export]]
SEXP toInteger(SEXP dn){
  return Rcpp::as<Rcpp::IntegerVector>(dn);
}
// [[Rcpp::export]]
SEXP toCharacter(SEXP dn){
  return Rcpp::as<Rcpp::CharacterVector>(dn);
}
")
vals <- c(a = 1, b = 2, c = 4)
toInteger(vals)
# a b c 
# 1 2 4 
toCharacter(vals)
# [1] "1" "2" "4"
``` 
As obviously visible names are dropped in the process, without warning. I **did** try to do some digging, but it seems somewhat obscure for my eye. (Maybe somewhere in inst/include/Rcpp/as.h between line 31 and 89? Maybe it is `r_type_generic_tag` conversion to array that causes this?) I did not go through the debugger to check up on this, this time.

This is part of the "somewhat obscure and why would you ever experience this" potential bugs, but to that point remember we are met with an error. when going from String to Integer:
```R
cvals <- c(a = '1', b = '2', c = '4')
toInteger(cvals)
# Error in toInteger(cvals) : 
#   Not compatible with requested type: [type=character; target=integer].
```
So this seems like an obscure and not very important unintended bug.

**Comment by kevinushey** [comment]
For the first example at least, the dropping-of-names matches the behavior of R; e.g.

```
> as.character(c("a" = 1, "b" = 2))
[1] "1" "2"
```

The string -> integer behavior is a bit less defensible since R lets you do so:

```
> as.integer(c("1", "2", "3"))
[1] 1 2 3
```

But ultimately I agree this is a relatively low priority issue.

**Comment by Bijaelo** [comment]
Agreed, note however that `as.*` in general removes all attributes. 
```r
as.integer(c(a = 1, b = 2)) 
[1] 1 2
```
Which is not the case for `as<IntegerVector>(...)` (or `NumericVector`).
```R
toInteger(c(a = 1, b = 2)) # toInteger from the post itself
a b
1 2
```
This "somewhat" talks against the consistency argument, seeing as this seemingly is the solo example which removes the attributes. :-)
