### ISSUE TITLE
local variable returned

### ISSUE THREAD

**Issue by sgsokol** [RcppCore/Rcpp#1144]
https://github.com/RcppCore/Rcpp/blob/5530578b5501d8b17e321fe7cf890f614b5b7511/src/api.cpp#L156

Is not it a multithread risk to return a reference on local variable content?

**Comment by eddelbuettel** [comment]
Did you see the comment in line 143 to 146 ?

**Comment by sgsokol** [comment]
No, I didn't. Thanks for pointing it out and sorry for the noise.
