### ISSUE TITLE
Rcpp::message() ?

### ISSUE THREAD

**Issue by krlmlr** [RcppCore/Rcpp#1145]
I wonder if `Rcpp::message()` should exist. `Rcpp::warning()` forwards to `Rf_warning()`; since there is no `Rf_message()`, the new function would take care of calling `base::message()` from R.

**Comment by eddelbuettel** [comment]
I am not sure I understand what you are writing about.   

Are you suggesting we need to add `Rcpp::message()` and implement it via a call to the R function `message()` ?

If so, why?  What current problem does this solve?

**Comment by eddelbuettel** [comment]
If `RSQLite` needs a `message()` you implement a local one, just how you have a local `XPtr` header as I re-noticed the other (and is that something we should clean up together) ?

**Comment by krlmlr** [comment]
Of course I could roll this myself, I'd rather not. I really think emitting a message from C/C++ code should be easier than the status quo.

The `XPtr.h` workaround was for an IDE I no longe ruse.

**Comment by eddelbuettel** [comment]
Ok, now at least I know we are talking about :)   Net additions are easiest; no side effects to existing code.  I may have looked into that at some point myself: the (possible) absense of a genuine C API is a spot of bother but we do go via the R API in one or two other places.

So having now established that "yes, we could" the burden is now on you to convince Team Rcpp why we should, and burden ourselves with the test and maintenance work going forward.  We're listening.

**Comment by krlmlr** [comment]
I really think emitting a message from C/C++ code should be easier than the status quo. There are various ways to solve this:

1. introduce a C API in R base
1. solve this in Rcpp and cpp11 via an R call (as proposed here)
1. implement directly in user libraries

Unless this is solved here first, I'll eventually go with the third option and propose PRs.

**Comment by eddelbuettel** [comment]
I still don''t understand. 
- the "1." we have no control over as we're not R Core
- the "3." is orthogonal to what we do here and everybody can do as they please in their.

So has it taken us five messages to establish that you are proposing a C++ function with static instantiation of an R function you want to call?

And you still have not addressed the question in my previous post:  _Why would we need this_ ?

**Comment by krlmlr** [comment]
I hear you're hesitant to take on new code, perhaps because that's more of a liability than an asset. If I contribute, I add tests and can respond to questions regarding the new code.

Personally, I think we need this 

- for symmetry: I typed `Rcpp::message()` without thinking and was genuinely surprised by the CI failure
- because the alternative is a mess: three or more lines of code that *could* be a simple call to `<whatever_namespace>::message()`

Please decide if this is enough motivation, and if it's a good fit for this package. There's no hurry.

(Thanks for the fast responses!)

**Comment by eddelbuettel** [comment]
Less fast response now as we have to sleep sometimes too :)  

I completely agree on the need for symmetry, I think I wanted it once or twice too.

So how do we do it then?  I presume you may have looked into the R code?  We could do the _verboten_ thing and hitting a hidden API, or we could do the simple thing via `Rcpp::Function` (and document that it'll be slower).  Thoughts?

**Comment by eddelbuettel** [comment]
I had a very very quick look and there is `R_ShowMessages()` but on first attempt is not yet suppressable:

```r
> Rcpp::cppFunction("void foo(std::string s) { R_ShowMessage(s.c_str()); }")
> foo("The quick brown fox")
The quick brown fox
> suppressMessages(foo("The quick brown fox"))
The quick brown fox
> 
```

**Comment by eddelbuettel** [comment]
And the reason maybe the logic in `src/library/base/R/message.R`.  

So ... dunno: do we need two, an (unconditional) `Rcpp::message()` and a (suppressable) `Rcpp::message2()` (or another name...) that goes via `Rcpp::Function()` to reap these goodies?

**Comment by krlmlr** [comment]
We can do un-suppressible messages today via `cerr` or the equivalent. Should we stick with the approach via `Function` only?

**Comment by eddelbuettel** [comment]
And ignore `R_ShowMessage()` ?  Hm.  That one is so cheap to add that I feel like we should (for that very reason of being cheap).

So your motivation, which, even ten or so messages in, you don't seem have made clear is that you want a printing / messaging mechanism that can be silenced via `suppressMessages()` ?  Is that it?  In that case a function wrapper it is.

**Comment by eddelbuettel** [comment]
Using `Rcpp::Rcerr` or `Rcout` does *not* show the text is a highlighted colour.  Using `R_ShowMessages` does.  Picture below (and I have to be a little careful to generalize as I am running [colorout](https://github.com/jalvesaq/colorout) here for kicks):

![image](https://user-images.githubusercontent.com/673121/111906467-abbeeb00-8a1e-11eb-9826-c452ece7fc6f.png)

**Comment by krlmlr** [comment]
Yeah, I'd think that `Rcpp::message()` should mimic `base::message()`. I looked at `R_ShowMessage()`, but messages that can't be suppressed feel terrible no matter how cheap.

Maybe `Rcpp::message()` and `Rcpp::show_message()` ?

**Comment by kevinushey** [comment]
I think we should just call base::message

**Comment by eddelbuettel** [comment]
I am also puzzled by what `R_ShowMessage()` is there for then :-/  Oh well.   

Ok, let's wrap `base::message` as `Rcpp::message()` then.

**Comment by kevinushey** [comment]
Looking at the R sources, it looks like `R_ShowMessage()` exists primarily for applications embedding R; in theory, an application embedding R could provide their own `ptr_R_ShowMessage()` implementation to decide what to do when R shows a message via `R_ShowMessage()`.

https://github.com/wch/r-source/blob/210076051305661d27393f790cb4a43e63a97715/src/unix/system.c#L74

However, these "message"s are different from what is exposed to users via `base::message()`; that is, condition objects of class `"message"` which write to stderr by default.

**Comment by eddelbuettel** [comment]
A truly minimal implementation is here:  https://github.com/RcppCore/Rcpp/commit/8992d83c8a8559821619c1ca2863a46110f40b53

I am currently rubbing my chin pondering how I would test for `suppressMessage()` working in a wrapper around (which it does, I am just not quite sure yet how to operationalize the test...  Can one capture messages?

**Comment by Enchufa2** [comment]
You also have `tinytest::expect_message`.

**Comment by eddelbuettel** [comment]
Hah.  Mark and I were DMing and that did not come up.  Paging the good Dr @markvanderloo ...

**Comment by eddelbuettel** [comment]
I guess it affirms that there was a message.  Nice.  Will add.  From the session in which I was noodling:

```r
> expect_message( foo("ABC") )
----- PASSED      : <-->
 call| expect_message(foo("ABC")) 
> 
```

**Comment by Enchufa2** [comment]
And more:

```r
> expect_message(message("asdf"), "ASDF")
----- FAILED[xcpt]: <-->
 call| expect_message(message("asdf"), "ASDF")
 diff| Found 1 message(s) of class 'message', but not matching 'ASDF'. 
 diff| Showing up to three messages:
 diff| Message 1 of class <simpleMessage, message, condition>:
 diff| 'asdf'
```

**Comment by eddelbuettel** [comment]
When did the classed messages appear?  Would we have to condition this?  I think I am fine with the one-liner I just added, but good thinking...

**Comment by Enchufa2** [comment]
I think that's 4.0+ features, but I was just pointing out that `expect_message` is able to match patterns too, which should also work for R < 4.0.

**Comment by eddelbuettel** [comment]
True, true, but I did it "in longhand" by calling `capture,output` myself.  All good, methinks.

**Comment by krlmlr** [comment]
Thanks for taking this on!

**Comment by stla** [comment]
Hi everyone,

 Please how to include a C++ variable in the message? I mean I have this code currently:

`Rcpp::Rcout << "Number of points removed: " << nremoved << ".\n";`

where `nremoved` is an integer. Should I convert it to a string and then use `Rcpp::collapse`?
