### ISSUE TITLE
Compile error code meaning

### ISSUE THREAD

**Issue by Dekermanjian** [RcppCore/Rcpp#1147]
Hello I am very new to using Rcpp, I am getting a compile error that I am not able to decipher. The error points me to the Rcpp.h file and says: 

"Line 3: no member named 'Object' in 'Rcpp::Argument'"

Line 3 in the Rcpp file is : 
// Rcpp.h: R/C++ interface class library

Any help would be greatly appreciated.

**Comment by eddelbuettel** [comment]
Please supply a reproducible example.  And for questions like the the mailing list is **much better**.  Could I ask you to 
i)  subscribe to the mailing list and posting there
ii) close this

**Comment by Dekermanjian** [comment]
Sure, no problem. Can you please provide me with the mailing list?

**Comment by Dekermanjian** [comment]
Never mind I found it
