### ISSUE TITLE
Switch to GitHub's container registry?

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#1150]
GitHub Actions are belly-up because hub.docker.com isn't serving.  

Should we bite the bullet and move the containers to GitHub's registry?

**Comment by eddelbuettel** [comment]
Follow-ups:

1. Not as easy as I thought.  My initial trial push was rejected even though I have a GH PAT :-/
2. We have green checkmarks again at GH Actions so maybe non-issue.

Docker Hub is way flakier than it used to be.  Ah well.   Back when we walked to schook, uphill both ways, in the hail...

**Comment by Enchufa2** [comment]
It seems easy to [maintain images](https://docs.github.com/en/packages/guides/using-github-packages-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio). However, the biggest concern is [this](https://docs.github.com/en/packages/guides/migrating-to-github-container-registry-for-docker-images#billing-changes):

> After the beta, the same billing and storage rates that other GitHub Packages registries use will apply to the container registry. For more information, see ["About billing for GitHub Packages."](https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-packages)

And those storage rates are quite low (for several docker images).

**Comment by eddelbuettel** [comment]
Yes, I aw that too.  But 'free for public package' and 'free transfers' if I understand it correctly if properly setup.  But wait and see it is I suppose.

**Comment by eddelbuettel** [comment]
Actions access to Docker still flaky as hell.  Really disappointing.
