### ISSUE TITLE
compileAttribute fails on comment in exported function definition

### ISSUE THREAD

**Issue by Bijaelo** [RcppCore/Rcpp#1151]
While answering a question on SO, I came over a small bug while. One that fails dramatically with the least understandable error in best C++ fashion. 

```c++
#include <Rcpp.h>
using namespace Rcpp;
// [[Rcpp::export]]
NumericVector fun(NumericVector x, NumericVector y){
  return x;
}
```
compiles fine,  but if one were to have a (truly viable) reason for adding a single line comment into the function definition such
```c++
#include <Rcpp.h>
using namespace Rcpp;
// [[Rcpp::export]]
NumericVector fun(NumericVector x, 
                               // y defunc from V 2.0
                               NumericVector y){
  return x;
}
``` 
this code fails beautifully with a few errors about "expcted ')' at end of input" and "expected initializer at end of input".  I haven't checked the `RcppExports.cpp` file but I am assuming the entire definition is copied without newlines causing the issue. Changing the comment to multiline removes the issue (eg: `/* ... */` causes no error).

While being a user problem it seems sensible to throw a warning on the R side or something. I might have missed this behaviour documented somewhere of course.

**Comment by eddelbuettel** [comment]
See previous issues; the parser is hand-written and *very unlikely* to be replaced / extended:
- #975
- #749
- #161

and possibly more.

**Comment by Bijaelo** [comment]
Fair enough. I thought I had gone through all the search words, but didn't hit these. :-) 
Apologies.

**Comment by kevinushey** [comment]
No worries; for whatever reason I find it very challenging to use GitHub's issue search to find relevant issues as well...
