### ISSUE TITLE
String CE_NATIVE encoding issue in CRAN

### ISSUE THREAD

**Issue by david-cortes** [RcppCore/Rcpp#1155]
I have a funny issue which I suspect could be caused by `Rcpp::String` encoding and which shows up in one of the CRAN builds (`r-devel-linux-x86_64-debian-clang`) ([this](https://cran.r-project.org/web/packages/readsparse/index.html) is the package in question).

In short, I'm trying to get a non-ascii string with system-native encoding from an R character variable (trying to imitate `RC_fopen`), with code like this:
```cpp
FILE *CRAN_acceptable_fopen(Rcpp::CharacterVector fname, const char *mode)
{
    Rcpp::String s(fname[0]);
    s.set_encoding(CE_NATIVE);
    return fopen(s.get_cstring(), mode);
}
```

When I use `fopen` with with the obtained string for writing a file with non-ascii characters, it will produce a file in the system (I'm not yet sure whether it actually has the right non-ascii name or not); but when using `fopen` with the same R `CharacterVector` again in read mode, it will fail to open the file it just created.

I guess the problem might be one of the following:
* The original `CharacterVector` element (or one of its attributes) is being modified in-place after changing the encoding of the new `String`.
* The string gets encoded incorrectly and `fopen` somehow modifies the path in a way that doesn't find the file it created after entering the same character vector.
* The `fopen` from `libc` uses different code paths for read and write mode which are incompatible with each other in terms of non-ascii file name support.

I suspect the issue is most likely caused by unintended modification of the original variable.

The problem only occurs in that particular CRAN build, as it works correctly in all the other linux, solaris, and mac versions. At least in my own system (debian + gcc) it works correctly and produces a file with the right name, so I cannot provide an exact setup to reproduce.

**Comment by eddelbuettel** [comment]
We could look into the first case and ensure the character vector remains unchanged by making a deep copy.  Using `std::vector<std::string>` may also be enough (or even just `std::string`).  

Not being able to reproduce is of course a minor issue :-/   Did you try the closest rhub instance? Per https://builder.r-hub.io/advanced it has 'Debian Linux, R-devel, clang, ISO-8859-15 locale'.  And ... maybe the locale choice matters?  I am fairly naive when it comes to anything but 7 or at best 8 bit char variables...

**Comment by david-cortes** [comment]
The error is reproducible on Rhub (`Debian Linux, R-devel, clang, ISO-8859-15 locale`), will try to investigate.

**Comment by david-cortes** [comment]
Apologies, this was not a problem with Rcpp at all, I just noticed I had some error messages in my R code which looked like the ones I had in my C++ code. The actual issue was that `file.exists` would not pick up the file name generated after applying the encoding.

The underlying issue was actually that the R version with non-UTF8-encoding didn't read character variables in `\u` notation properly, so something like `"\u00d1o\u00f1o"` (`Ñoño`) would become `�o�o` in R and `�\221oño` after the decoding.

**Comment by eddelbuettel** [comment]
No worries, glad you have it squared away.  "Non-standard" characters are, in fact, non-standard :grin: and a slight pain.
