### ISSUE TITLE
An Rcpp::dgCMatrix class

### ISSUE THREAD

**Issue by zdebruine** [RcppCore/Rcpp#1156]
I wrote an Rcpp sparse matrix class for dgCMatrix. It's built on _Rcpp::IntegerVector_ and _Rcpp::NumericVector_ and provides Armadillo-esque sparse iterators and subviews.

My motivation was to avoid the overhead of deep-copying done by `Rcpp::as` functions for _arma::SpMat_ and _Eigen::SparseMatrix_ in RcppArmadillo and RcppEigen.

[Code](https://github.com/zdebruine/RcppSparse/blob/main/RcppSparse.h)
[Documentation](https://github.com/zdebruine/RcppSparse#readme)
[Microbenchmark vs. Matrix R package](https://github.com/zdebruine/RcppSparse/wiki/Microbenchmarks:--Matrix-R-package)
[Benchmark vs. RcppArmadillo and RcppEigen](https://github.com/zdebruine/RcppSparse/wiki/Microbenchmarks:-RcppArmadillo-and-RcppEigen)

Having a sparse matrix class built in the default Rcpp namespace would be really nice. I'm all ears to any critiques and suggestions, and can submit a pull request if this is something you are interested in.

dgCMatrix is obviously just a start, but it meets all my needs and my focus right now needs to be more on application and less on implementation.

P.S. thanks Dirk for handling my questions on SO!

**Comment by eddelbuettel** [comment]
Likely won't happen as we won't add dependencies to Rcpp.  There is a bit of work in RcppArmadillo for sparse matrices following an intiail Google Summer of Code project.  It also has existing tests via packages Matrix, slam and even reticulate against Python.

RcppArmadillo is a better home for this as Armadillo actually _has_ sparse matrix functionality.  

Of course I see that one could argue that more functionality _could_ bubble up into Rcpp proper, but there is a general overall consensus that narrower base packages are preferable.  I see no reason to depart from this.

That said, would you be interested in documenting what you have in an additional Rcpp Gallery piece (or two even) ?

**Comment by eddelbuettel** [comment]
And maybe it could of course also be an add-on package at CRAN if you prefer that.   As for the benchmarks, measuring constructors is one thing; I think you also need to show _something_ doing real work for which the existing by-copy-of-elements are used as they happen to fit SuiteSparse _et al_ doing that actual work.

**Comment by zdebruine** [comment]
Thanks Dirk!  The RcppArmadillo sparse matrix wrappers are very comprehensive indeed, even if they are copying the data, and Armadillo is equally versatile.

I absolutely agree with keeping the base Rcpp package focus narrow.

In terms of benchmarking, much more could be done, for sure. SuiteSparse is a great resource. In my current work on NMF of large single-cell datasets by alternating least squares, I've used RcppEigen and RcppArmadillo, and now this class, and performance of this class falls between Eigen and Armadillo, plus I don't have the overhead of copying the very large (sometimes up to 10Gb) matrices. So it's definitely the way to go in my case.

I could write something up for the Rcpp gallery. Maybe next week though.

Yes, an add-on package is probably the best home for this project. I'll look into that.

**Comment by eddelbuettel** [comment]
No that is good -- if you can in fact get by with 'home grown' analytics just moving over the data than the zero copy approach is good.  Let's document that, let's document that you won't get SuiteSparse and friends the same way (unless I actually skipped a missing step, maybe you can get there from the Matrix package classes?).  

There is a huge need for performant sparse matrix stuff.  I deal with that in ${dayjob} too (see https://tiledb.com) and there is some work going on.   But ... there are also Matrix, spam, slam, RcppArmadillo, ... and more already there so I don't want to rush this.  An add-on package may be the best start.  If and when we get by without added dependency and headaches we can maybe talk about fusing it but it should mature for a bit.
