### ISSUE TITLE
large max time for a Rcpp call (microbenchmark)

### ISSUE THREAD

**Issue by LaurentPlagne** [RcppCore/Rcpp#1157]
Hi,
I have posted a question about the large max time observed with a Rcpp call here

[](https://community.rstudio.com/t/large-max-time-for-microbenchmark-of-rcpp-call/102054?u=laurentplagne
![test_perf](https://user-images.githubusercontent.com/24976886/115108338-3c321200-9f70-11eb-9a2b-3208c8f80647.png)
)

I am a R beginner and I apologize in advance if the answer is obvious.
Than you for your help.

**Comment by eddelbuettel** [comment]
That's standard R behaviour of, every now and then, requiring a call to garbage collection (_i.e._ function `gc()` from R).  It would be the same if you coded the same test function 'by hand' in C or C++ and interfaced it by hand---there is nothing nefarious here that Rcpp does and that we could simply remove.  Most easy fixes have, in fact, been applied by now to a project that is well over ten years old.

**Comment by LaurentPlagne** [comment]
Thank you very much for your explanation !
