### ISSUE TITLE
Compilation failed for package ‘Rcpp’

### ISSUE THREAD

**Issue by karthik2527** [RcppCore/Rcpp#1164]
Seeing compilation errors while trying to install Rcpp, below are the details of the environment. It will be great if someone could guide me to resolve it please. 

Package being tried  to install ` Rcpp_0.12.15.tar.gz`
Command used to install `R CMD INSTALL Rcpp_0.12.15.tar.gz`
OS `Red Hat Enterprise Linux release 8.3 (Ootpa)`
R version `R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"`
gcc version `gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)`
Attaching the error if in case required, there were multiple errors so not sure which one would best fit on the body here. 
[output.txt](https://github.com/RcppCore/Rcpp/files/6602732/output.txt)

**Comment by eddelbuettel** [comment]
Did you _read_ the [template](https://github.com/RcppCore/Rcpp/blob/master/.github/ISSUE_TEMPLATE.md) we present before you added your hundreds of lines of output?

**Comment by kevinushey** [comment]
```
/usr/include/bits/local_lim.h:87:1: error: â€˜defineâ€™ does not name a type; did you mean â€˜rewindâ€™?

 define TTY_NAME_MAX  256
 ^~~~~~
 rewind
```

This error make me think your system headers are messed up somehow. There should be a # before the define.

Seems not to be an Rcpp issue.

**Comment by eddelbuettel** [comment]
Disclaimer:  25+ user and contributor to Debian. I know _very little_ about RHEL and CentOS.

But I just installed the default `centos:8` Docker image and bumbled my way around two google searches, The [RStudio page on installation](https://docs.rstudio.com/resources/install-r/) was helpful.  And in short ... "it just worked".  Briefly edited from my bash history:

```
dnf install epel-release
dnf install dnf-plugins-core     # because something else wanted config-manager
curl -O https://cdn.rstudio.com/r/centos-8/pkgs/R-4.0.5-1-1.x86_64.rpm
yum install R-4.0.5-1-1.x86_64.rpm
/opt/R/4.0.5/bin/R -q -e 'install.packages("Rcpp", repos="https://cloud.r-project.org")'
```

at which point I had R and Rcpp on CentOS 8 so I am going to close this now.  If you can actually find something reproducible that is a bug in our package --always possible, happened often enough -- then please reopen and let us know but as Kevin just noted this looks more like it is in your court.

**Comment by karthik2527** [comment]
thanks all we will check our env.
