### ISSUE TITLE
Is it safe to have a main function in a C++ file to be loaded by sourceCpp?

### ISSUE THREAD

**Issue by waynelapierre** [RcppCore/Rcpp#1165]
The code below works fine with sourceCpp. I just want to understand whether there are side effects with using the main function.

```
include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
double meanC(NumericVector x) {
  int n = x.size();
  double total = 0;

  for(int i = 0; i < n; ++i) {
    total += x[i];
  }
  return total / n;
}

int main(){
return 0;
} 
```

**Comment by eddelbuettel** [comment]
Well "works fine with `souceCpp()`" is relative as it cannot work _as an extension function from R_ as R controls its own `main()`.  Compiling another entry point that will never get called from R (no `[[Rcpp::export]])`) does not make too much sense either.

If you want to add R code to C++ examples, maybe look into our other project [RInside](https://github.com/eddelbuettel/rinside).

I suggest we close this.

**Comment by waynelapierre** [comment]
OK, thanks.
