### ISSUE TITLE
R session crashes upon array declaration

### ISSUE THREAD

**Issue by lavkeshg** [RcppCore/Rcpp#1166]
`include <Rcpp.h>`
`using namespace Rcpp;`
`// [[Rcpp::export]]`
`Rcpp::NumericVector Rcpp_vector_test(int vector_size) {`

`  int my_array[vector_size][vector_size][vector_size] = {0};`
 
`  my_array[0][0][0] = 1;`
  
`  Rcpp::NumericVector my_vector(vector_size);`
`  return(my_vector);`
  
`}`

Up on running the function with input in the order of 10^6 the session crashes, even though it is well below the overflow limit. The result can be seen below.

![image](https://user-images.githubusercontent.com/64500451/125142379-94972c80-e0e5-11eb-9083-3b10bc22332e.png)

Any ideas as to what might be causing this?

**Comment by eddelbuettel** [comment]
Thanks for taking the time to file a bug report.  But what you experience here, and apologies for being blunt, is chiefly due to incorrect use of the underlying language.  

Please take the time review some C++ tutorials -- which can be intimidating -- and/or look at the _many_ Rcpp examples we provide at the Rcpp Gallery, the RcppExamples package, the vignettes, the over 2700 answers on StackOverflow, our dedicated mailing list and more.   Randoly slapping code together will get you segfaults. Such is life with C and C++.  

```c++
#include <Rcpp.h>     

// [[Rcpp::export]]        

Rcpp::NumericVector simple() {       
  int n = 2;
  Rcpp::NumericVector v(n);     // allocates 
  v[0] = 42; 
  v[1] = 123.456;
 return v;
} 

/*** R 
simple()   
*/
```


You can save the above and `Rcpp::sourceCpp("nameOfTheFile.cpp")`.

**Comment by lavkeshg** [comment]
@eddelbuettel the underlying code in the original post is trying to declare a new array at two separate intervals within the code. The second array (RcppNumericVector) gets its size, after some intermediate processing steps, after the first array (integer array) is initialized. The problem to be specific here, is with returning a NumericVector after a certain size is reached. Are you sure that the originally posted function worked fine for you? 

If the original code is incorrect and is bound to run into problems of the sort that I am describing, then how would you re-write it in that case?

**Comment by Enchufa2** [comment]
I see:

```
warning: ISO C++ forbids variable length array ‘my_array’ [-Wvla]
```

You are corrupting the stack with that huge variable-length array. Without it, the code runs just fine.

**Comment by eddelbuettel** [comment]
Please understand that we are a volunteer project, serving 2300+ packages on CRAN alone.  We can not offer semi-arbitrary  debugging service, or C / C++ language tutorials. 

Also, your one function doing two dinstinct things, and it blows up. Did you try to separate the two things to which of these (or both?) were at fault.

Please allow us to use this venue to discuss potential or actual bugs in Rcpp.  We feel this is not one, so we closed this.  If we were wrong please let us know but with a more concrete example than "RStudio blew when I tried code".  We do not have the bandwidth to help you with that.  Sorry.
