### ISSUE TITLE
size of long vector 

### ISSUE THREAD

**Issue by waynelapierre** [RcppCore/Rcpp#1175]
If I have an R vector with a length longer than 2147483647 and supply it to a C++ function sourced via Rcpp, do I need to use data type long instead of int for the vector size in my C++ function? I use R on Linux.

**Comment by eddelbuettel** [comment]
You are not very specific with exactly what it is you are trying to do, and what is that is failing.

```r
> N <- 2147483647 + 1
> N
[1] 2147483648
> V <- rep(1L, N)
> Rcpp::cppFunction("double foo(std::vector<int> v) { return v.size(); }")
> foo(V)
[1] 2147483648
> Rcpp::cppFunction("double foo(Rcpp::IntegerVector v) { return v.length(); }")
> foo(V)
[1] 2147483648
> 
```

These seem to cope.  I think R now works internally mostly with `R_xlen_t` and we switched most if not all internal counters too years ago.  There may still be issues -- it is a tricky limit.   If you find something that truly doesn't work, you can probably work around by chunking which ... is after all a common method for really 'large' data.

**Comment by waynelapierre** [comment]
How about this one on your computer?
Rcpp::cppFunction("long foo(std::vector<int> v) { return v.size(); }

**Comment by eddelbuettel** [comment]
`long` is discouraged.  Use `int64_t` to guarantee 64 bits, and there `double` is easier because R can map to it.  We would have to look it up in Rcpp's source but I would suspect a `long` is mapped to a `double` anyway.

And if I may for a second time:  what problem are you actually trying to solve? That an `int` (aka `int32_t` cannot run longer than 2^31-1?  Well ... that is why R uses `R_xlen_t` and we often resort to `double`.

**Comment by waynelapierre** [comment]
I only use the data type long within C++ and don't need to worry about mapping it back to R. I want to ensure it is OK to do that with Rcpp. 

```
double rv(const std::vector<double>& x)
{
  long n = x.size();
  double param = 2.0;
  double res = 0.0;
  
  for (long i = 0; i < n; i++)
  {
    res += pow(x[i], param);  
  } 
  
  return res;
}
```

**Comment by eddelbuettel** [comment]
Sure. `long` is only used inside the `{ ... }` scope of your functions.

**Comment by eddelbuettel** [comment]
My pleasure.
