### ISSUE TITLE
RCPP_USE_GLOBAL_ROSTREAM causing issues

### ISSUE THREAD

**Issue by andrew-plowright** [RcppCore/Rcpp#1176]
I wasn't able to find any documentation about this, but the most recent version of `Rcpp` has been adding the following lines to my `RcppExports.cpp` file.

```cpp
#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif
```

This does not cause any code to fail, but instead changes its behaviour. The functions defined in this file now return matrices with all 0s, instead of the usual input:

https://github.com/andrew-plowright/ForestTools/blob/master/src/glcm.cpp

For example here is the output that is normally expected:

```r
> img <- matrix(c(0,0,1,1,0,0,1,1,0,2,2,2,2,2,3,3), ncol =4, byrow=T)
> glcm0(img, n_grey = 3, d = 1)
     [,1] [,2] [,3] [,4]
[1,]    2    2    1    0
[2,]    0    2    0    0
[3,]    0    0    3    1
[4,]    0    0    0    1
```

And now the output is this:

```r
> glcm0(img, n_grey = 3, d = 1)
     [,1] [,2] [,3] [,4]
[1,]    0    0    0    0
[2,]    0    0    0    0
[3,]    0    0    0    0
[4,]    0    0    0    0
```

**Comment by eddelbuettel** [comment]
Hi Andrew.  We can surely take a look.  This change is described in the NEWS file as a 1.0.7 change we made some time earlier in the years.  And it was as always, fully tested against all known CRAN reverse dependencies.

**Comment by eddelbuettel** [comment]
I cannot reproduce your finding:

```r
> library(Rcpp)
> sourceCpp("glcm.cpp")   # downloaded via wget from 'raw' view of your file
> img <- matrix(c(0,0,1,1,0,0,1,1,0,2,2,2,2,2,3,3), ncol =4, byrow=T)
> glcm0(img, n_grey = 3, d = 1)
     [,1] [,2] [,3] [,4]
[1,]    2    2    1    0
[2,]    0    2    0    0
[3,]    0    0    3    1
[4,]    0    0    0    1
> R.version.string
[1] "R version 4.1.1 (2021-08-10)"
> packageVersion("Rcpp")
[1] ‘1.0.7.2’
> 
```

Ignore the fact that mine shows 1.0.7.2 and not 1.0.7, it just corresponds to local master plus whatever we're currently testing. These days these change sets are small so I expect no delta there.

**Comment by eddelbuettel** [comment]
It could be a side-effect in your package.  Sadly there is not shortcut: I would make a copy of `ForestTools` to debug with and prune other faciltities away until in use Rcpp.  Then add your `glcm0()` function.  See how it behaves. If it is good add things back in step by step to bring to `ForestTools` level.

(Also:  in a directory such as https://github.com/andrew-plowright/ForestTools/tree/master/src you do not want to commit object files or shared libraries.  This can affect the build -- maybe you were mixing and and new Rcpp compilation -- surprises could come from such a side.)

**Comment by Enchufa2** [comment]
> I wasn't able to find any documentation about this, but the most recent version of `Rcpp` has been adding the following lines to my `RcppExports.cpp` file.
> 
> ```c++
> #ifdef RCPP_USE_GLOBAL_ROSTREAM
> Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
> Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
> #endif
> ```
> 
> This does not cause any code to fail, but instead changes its behaviour. The functions defined in this file now return matrices with all 0s, instead of the usual input:

It seems implausible that the code above could cause anything like that, especially if you don't define `RCPP_USE_GLOBAL_ROSTREAM`, which means that the fragment is gone after the preprocessor.

Instead, mixing packages compiled against different versions of Rcpp is the usual suspect in these strange cases, as Dirk already suggested.

**Comment by andrew-plowright** [comment]
Thanks for your replies. Using `sourceCpp("glcm.cpp")` did indeed work on my end, so I guess the issue is not with the latest version of Rcpp itself. This new version is triggering a recompile, however, and somewhere in that recompiling there's an issue.

> ```r
> > library(Rcpp)
> > sourceCpp("glcm.cpp")   # downloaded via wget from 'raw' view of your file
> > img <- matrix(c(0,0,1,1,0,0,1,1,0,2,2,2,2,2,3,3), ncol =4, byrow=T)
> > glcm0(img, n_grey = 3, d = 1)
>      [,1] [,2] [,3] [,4]
> [1,]    2    2    1    0
> [2,]    0    2    0    0
> [3,]    0    0    3    1
> [4,]    0    0    0    1
> > R.version.string
> [1] "R version 4.1.1 (2021-08-10)"
> > packageVersion("Rcpp")
> [1] ‘1.0.7.2’

**Comment by andrew-plowright** [comment]
Update: I deleted everything in the `/src/` folder except for my `glcm.cpp` file. I then ran `devtools::document()`, then rebuilt the package, and then no more issues.

I suppose that the files generated with `devtools::document()` were out of date or corrupt or something.

Anyways, thanks for your help everyone. Cheers.

**Comment by eddelbuettel** [comment]
I sometimes blame `devtools` as it indroduces opaqueness (relative to plain `R CMD build` and friends) but here it was, I think, really just you leaving the old files.  `devtools` and its commands just call R which in turn just calls `make` using the temporary `Makefile` it creates.  And leaving old files around means those got used.

These things tend to have a heavy flavour of 'doh' once one realizes it but it is all hidden. I tend to now _always_ add a top-level files `cleanup` which purges `src/*.{o,so,dll}` and alike.  I'd recommend that.   The headaches and hours lost you can get otherwise are ... really only able to files as (very painful) "learning experiences".

**Comment by tpq** [comment]
Thanks for this thread. I'm just leaving a message for future Googlers... I had the same symptom as Andrew where the new RCPP text had strange a effect on my package, apparently causing a memory leak. My problem did seem to be with devtools too. I cleaned `rm src/*{o,so,dll}` and installed via `R CMD build` and everything now works as it should.

**Comment by eddelbuettel** [comment]
> apparently causing a memory leak

I strongly doubt that. If you are able to replicate by all means file an issue.  If you can't maybe refrain of speaking ill of other packages without actual justification.  Your issue seems to be entirely with `devtools` which is an entirely different toolchain we do not condone, endorse, or recommend.

**Comment by tpq** [comment]
I think you misunderstand my intention. I'm very grateful for `Rcpp`, and agree the issue is entirely with `devtools`. This thread helped me fix my problem, and I reckon it may help others in the future too.

**Comment by eddelbuettel** [comment]
You are making a (borderline libelous) that statement that "Rcpp caused your memory leak".  And I object -- I have to have a decent handle on fairly widespread use of Rcpp given its 2400+ reverse dependencies.

So: by all means, speak your mind and report bugs _but back them up with credible evidence_.  So far you brought zero.

**Comment by eddelbuettel** [comment]
And `rm src/*{o,so,dll}` is not even a `devtools` issue.  Maybe you had build artefacts from a prior R version. Or another package version. Or another Rcpp version.  Nobody can tell.

So maybe it's best to just state:  "I was working from a local 'in-flight' repository, and restarting from a clean state cleaned things up.".  Much cleaner and easier.

**Comment by MartinRoth** [comment]
>I was working from a local 'in-flight' repository, and restarting from a clean state cleaned things up.

This thread, helped me remember that `rm src/*{o,so,dll}` should be part of my cleaning routine :)
