### ISSUE TITLE
Why Rcpp attributes need to be written as comments?

### ISSUE THREAD

**Issue by waynelapierre** [RcppCore/Rcpp#1179]
Another R package cpp11 has `[[cpp11::register]]`, which is similar to `// [[Rcpp::export]]`. I was wondering if Rcpp would consider allowing attributes to be in non-comment codes.

**Comment by eddelbuettel** [comment]
@waynelapierre May I ask you to stop filling issue tickets as means of conversation?  There is a mailing list you could use.  

And if may, Rcpp is open source.  How attributes are dealt with is (relatively) easy to see by studying the 3600-line file `src/attributes.cpp`.   If you think it is important that the tags be written differently you could alter that file to your content.  We are happy with it as it is.
