### ISSUE TITLE
Minor documentation issue with .pdf textbox overflow

### ISSUE THREAD

**Issue by billdenney** [RcppCore/Rcpp#1195]
While trying to understand why Rcpp was documenting a NULL object (nlmixr2/rxode2#85), I found a minor formatting issue with the .pdf documentation on page 5 of the left column in https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-attributes.pdf.  Specifically, if you search for "NULL", you will see a textbox where the first column overlaps the second.

I'm going to make a simple PR for it, but I can't easily test the PR because of some issue with my TeX installation relative to what Rcpp requires.

**Comment by eddelbuettel** [comment]
The PR #1196, as commented there, looks good.

I am out of context here for the issue that got you here: https://github.com/nlmixr2/rxode2/issues/85.  Anything I can do to help in case it is Rcpp-related?
