### ISSUE TITLE
Rcpp::DateVector has weird side effect on R input argument

### ISSUE THREAD

**Issue by klin333** [RcppCore/Rcpp#1197]
For a c++ function that takes in a Rcpp::DateVector as an argument, if it is called in R with a numeric vector as the argument, this numeric vector gets converted to a Date vector in R, after the function runs. This seems like an unexpected side effect because the function _argument_ got changed by the function.

Project created with Rcpp::Rcpp.package.skeleton().
The only cpp file is below:
```cpp
#include <Rcpp.h>

// [[Rcpp::export]]
Rcpp::DateVector debugDateVector(Rcpp::DateVector x) {
    return x ;
}

// [[Rcpp::export]]
Rcpp::Date debugDate(Rcpp::Date x) {
    return x ;
}
```

The only R script is:
```r
a <- 1L
tmp <- debugDate(a)
str(a) # int 1


b <- 1
tmp <- debugDate(b)
str(b) # num 1

c <- 1L
tmp <- debugDateVector(c)
str(c) # int 1


d <- 1
tmp <- debugDateVector(d)
str(d) # Date[1:1], format: "1970-01-02" ??? this is weird ???
```

I expect d to remain a numeric vector ater calling debugDateVector. Sure it's not great that the R user is calling a function that expects dates, with a numeric vector as the input. Sure maybe better type checking is the way to go. However, it still feels not right that a function argument in R can be unexpectedly altered by a function.

SessionInfo
```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] debug123_1.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8        rstudioapi_0.13   magrittr_1.5      usethis_2.0.1     devtools_2.4.2    pkgload_1.2.1     R6_2.4.1         
 [8] rlang_0.4.10      fastmap_1.0.1     tools_3.6.3       pkgbuild_1.2.0    packrat_0.5.0     sessioninfo_1.1.1 cli_2.5.0        
[15] withr_2.4.2       ellipsis_0.3.1    remotes_2.3.0     rprojroot_1.3-2   lifecycle_1.0.0   crayon_1.3.4      processx_3.5.1   
[22] purrr_0.3.4       callr_3.7.0       fs_1.5.0          ps_1.6.0          testthat_3.0.2    memoise_2.0.0     glue_1.4.1       
[29] cachem_1.0.4      compiler_3.6.3    desc_1.3.0        backports_1.1.7   prettyunits_1.1.1
```

**Comment by Enchufa2** [comment]
Thanks, it seems that we are skipping a copy where we really shouldn't. Which is somehow related to 943 (but not tagging until @eddelbuettel @kevinushey confirm)

**Comment by eddelbuettel** [comment]
@echufa Not sure I see a relation to #943 

To me this more like 'yep we always get `SEXP` and sometimes we mutate -- it's been like this for 10-15 year and it may be hard to change.  Recall the old example of doing something with an `IntegerVector` that behave differently between and `int` vector (taken as is, hence mutated if written to) and a `double` vector (copied on entry, hence not mutable).

**Comment by eddelbuettel** [comment]
From inst/include/Rcpp/date_datetime/newDateVector.h:

```c++
namespace Rcpp {

    class newDateVector : public NumericVector {
    public:
        template <int RTYPE, bool NA, typename VEC>
        newDateVector(const VectorBase<RTYPE,NA,VEC>& vec) : NumericVector(vec) {
            setClass();
        }

        newDateVector(SEXP vec) : NumericVector(vec) { setClass(); }
        newDateVector(int n) : NumericVector(n) { setClass(); }

//... more omitted
```

**Comment by Enchufa2** [comment]
There are several things that seem odd to me in this implementation:

1. A `DateVector` is not a vector of `Date`.
2. `Date` doesn't change the input, independently of the input type, but `DateVector` does.
3. `DateVector` uses numeric as storage, while a date, conceptually, is a count, so it should be integer.
4. Therefore, if any, I would expect the integer case to be modified and the numeric case to get copied.
5. Rcpp enables the user to mutate the input. As you say, this has been the case for a number of years. But if I recall correctly, all the previous discussions around this required the user to do _something_. So the user can choose: copy stuff to be a good citizen or try to be smarter. Here, however, the side effect is forced on the user. The functions above do nothing, and yet we have a side effect because it's in the constructor.

**Comment by eddelbuettel** [comment]
It's all part of the very first / oldest interface I wrote using Rcpp in a client package.  It gets even worse when you look into the `date_datetime/` dir and look at the files prefixed with `old`  -- the horror :)

**Comment by eddelbuettel** [comment]
As for 3. above: No because it's not an `integer` internally:

```r
 > now <- Sys.time()                                                                                                                                                                                               
 > as.Date(now)                                                                                                                                                                                                    
 [1] "2022-02-14"                                                                                                                                                                                                  
 > unclass(as.Date(now))                                                                                                                                                                                           
 [1] 19037                                                                                                                                                                                                         
 > storage.mode(unclass(as.Date(now)))                                                                                                                                                                             
 [1] "double"                                                                                                                                                                                                      
 >  
```

**Comment by Enchufa2** [comment]
Whaaat? Weird! Then delete 3 and 4.

1, 2, 5 still hold though. :D

**Comment by eddelbuettel** [comment]
1 and 2 are bad, but such is life.  Published API contract.

And 5 is "left as an exercise to the reader" aiming for the complete rewrite that will be required to make this happen.

**Comment by Enchufa2** [comment]
> So (I didn't look into it but) maybe if a `MAYBE_SHARED`check is added in the proper place (the storage class?) we may be fixing this and #943 in one go?

Answering to myself: no, it's not enough. Still, `DateVector`'s constructor is executed before the object is copied, so the `setClass` call should be delayed too.

**Comment by kevinushey** [comment]
> Answering to myself: no, it's not enough. Still, DateVector's constructor is executed before the object is copied, so the setClass call should be delayed too.

I agree with that. This could also be a good "canary in the coal mine" to see whether explicitly duplicating the SEXP passed in before calling `setClass()` causes any kind of breakage in packages.

**Comment by eddelbuettel** [comment]
I think I might be open to adding another parameter to explicitly deep copy / clone (with default value of `FALSE` to match current behavior) but otherwise at least a package of mine depends on current behavior so not too keep to change this.

**Comment by klin333** [comment]
I would think it's not great practice to rely on Rcpp's side effect of altering the class of function _arguments_, especially in this case of the side effect only occurring for Rcpp::DateVector argument types and only when given a double. 

To me, it seems like a bug, and that packages which depend on bugs should be fixed, instead of keeping the bug as a feature. If this is indeed a feature of Rcpp, it should be documented as part of the API with a giant user beware. 

Otherwise, this seems dangerous. It's extremely rare for a R function to alter the argument from the caller's perspective. R is always always copy on modify, and vast majority if not all users of Rcpp would expect functions written with Rcpp to be copy on modify. 

See Hadley's book https://bookdown.dongzhuoer.com/hadley/adv-r/modify-in-place.html, i quote
```
As we’ve seen above, modifying an R object usually creates a copy. There are two exceptions:

Objects with a single binding get a special performance optimisation.

Environments, a special type of object, are always modified in place.
```

Neither of which applies here.

**Comment by eddelbuettel** [comment]
I mentioned question 5.1 of the Rcpp FAQ already; you may find informative.   

Not mutating has a cost for deep copies; if you want to bear the cost is easy and takes just another application of the [fundamental theorem of software engineering](https://en.wikipedia.org/wiki/Fundamental_theorem_of_software_engineering) by adding a layer:

```r
> Rcpp::cppFunction("DateVector dd(NumericVector x) { NumericVector y = clone(x); return DateVector(y); }")
> d <- 1:3
> dd(d)
[1] "1970-01-02" "1970-01-03" "1970-01-04"
> d
[1] 1 2 3
> 
```

**Comment by klin333** [comment]
arh yep you are right, sorry I should have read that... ok, seems like a legit unknown issue / feature then. i'm happy with no further actions.

**Comment by eddelbuettel** [comment]
It's complicated -- what you described and encountered is a little off-putting and surprising but has also been documented for a decade or longer (the longer workshops almost always had an example).   

In theory one could do better.  In practice it is what have been doing for give or take 15 years so it is hard to change now. We can't always win all the little battles.

**Comment by klin333** [comment]
Arh ok yes I should have read that faq. I'm satisfied this is a known issue. 

I'm also happy with the suggestion of an additional parameter to explicitly deep copy / clone. At least this way, users of Rcpp that don't care about the time cost of a deep copy, can avoid this weird side effect for users of their Rcpp exported R functions.
