### ISSUE TITLE
NULL is documented instead of a function

### ISSUE THREAD

**Issue by billdenney** [RcppCore/Rcpp#1198]
This is an attempt to make a reproducible example for nlmixr2/rxode2#85 .  As someone who doesn't program in C++, I'm not sure that I've generated the issue correctly, but I can at least make something happen the way that I'm having the issue over there.

The steps that I followed are to create a package with:

```r
library(Rcpp)
Rcpp.package.skeleton(name="issueextern")
```

Then, I:

* put this file into the src directory as "rcpp_hello_word.cpp" [rcpp_hello_world.txt](https://github.com/RcppCore/Rcpp/files/8072386/rcpp_hello_world.txt),
* I ran `Rcpp::compileAttributes()`
* I then ran `roxygen2::roxygenize(load_code=roxygen2::load_source)`, and the issue is that I see the warning `Warning: [C:\tmp\issueextern\R\RcppExports.R:1] @title Missing name`

I think that the issue is that NULL is documented instead of the expected function name.  I don't know why NULL is documented instead of `indLin` or `rxIndLin_` which is what I would have expected.

**Comment by billdenney** [comment]
I think that the preferred output would be that either NULL is not documented.  (Maybe documentation of NULL should be an error?  I'm not sure.)  Or, when NULL is documented and it is not explicitly intended a warning is generated (how it would be "explicitly intended", I don't know).

**Comment by eddelbuettel** [comment]
Ok, I am going to close this for two reasons.

First, `Rcpp` is 100% orthogonal to `roxygenize`.  We do not opinionate on how you write documentation or how you use it.  There is no dependency, implicit or explicit.

Second, it think this is a case of PNKAC. Your roxygen block of 

```c++
//' Inductive linearization solver
//'
//' @param cSub = Current subject number
//' @param op - rxode2 solving options
//' @param tp - Prior time point/time zeor
//' @param yp - Prior state;  vector size = neq; Final state is updated here
//' @param tf - Final Time
//' @param InfusionRate = Rates of each comparment;  vector size = neq
//' @param on Indicator for if the compartment is "on"
//' @param cache
//'    0 = no Cache
//'    When doIndLin == 0, cache > 0 = nInf-1
//' @param ME the rxode2 matrix exponential function
//' @param IndF The rxode2 Inductive Linearization function F
//' 
//' @return Returns a status for solving
//' 
//'   1 = Successful solve
//' 
//'   -1 = Maximum number of iterations reached when doing
//'        inductive linearization
```

lacks @title or @name or ...  

So nothing to do for Rcpp here.
