### ISSUE TITLE
NumericMatrix subscript operator

### ISSUE THREAD

**Issue by waynelapierre** [RcppCore/Rcpp#1200]
Since the multidimensional subscript operator has been voted into C++23, will you consider adding this feature for NumericMatrix?
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2128r6.pdf

**Comment by eddelbuettel** [comment]
That doesn't even work as a joke.  Have you realized which compilation standard we still support?  Have you considered what current compilers support?   

But we have a long view and I look forward to your well-written and extensively tested PR.  Shall we say in March 2037?
