### ISSUE TITLE
trouble for sourceCpp to include local header file and corresponding cpp file

### ISSUE THREAD

**Issue by ctex77** [RcppCore/Rcpp#1204]
I prefer to use sourceCpp to compile a cpp file including several other cpp files instead of wrapping all related files in a package. But I find there may be some troubles for including local cpp files for `sourceCpp`. I created files of `test02.cpp`, `shared/utilities.hpp`, `shared/utilities2.hpp`, `shared/utilities.cpp` as written in the document of "Rcpp Attributes.pdf". Specifically, `test02.cpp` has all content of 

```c++
#include "shared/utilities2.hpp"

// [[Rcpp::export]]
double transformValue(double x) {
    return timesTwo(x)   *10;
}
```

`shared/utilities.hpp` has all the content of

```c++
#ifndef __UTILITIES__
#define __UTILITIES__
double timesTwo(double x);
#endif 
```

`shared/utilities.cpp` is

```c++
#include "utilities.hpp"
double timesTwo(double x) {
    return x * 2;
}
```

`shared/utilities2.hpp` has all the content of

```c++
#ifndef __UTILITIES__
#define __UTILITIES__
double timesTwo(double x) {
    return x * 2;
};
#endif 
```

The `sourceCpp('test02.cpp')`, with `#include "shared/utilities.hpp"` in `test02.cpp`, fails with errors of 

```
undefined reference to `timesTwo(double)'
```

and the `sourceCpp('test02.cpp')`, with `#include "shared/utilities2.hpp"` in `test02.cpp`, succeeds.

Is there anyway for

```c++
#include "shared/utilities.hpp"
```

but not `"shared/utilities2.hpp"` with `sourceCpp` when I do not want to create a packaged to accommodate all related files.

The environment is
Windows 10 Pro V21H1, R version 4.1.2 (2021-11-01), Rtools40, Rcpp v1.0.8, RStudio
2022.02.0 Build 443, "Prairie Trillium" Release (9f796939, 2022-02-16) for Windows

**Comment by Enchufa2** [comment]
I tested the example in the vignette and it works well. Note that I fixed your comment so that code chunks are properly highlighted, and I corrected `\_\_UTILITIES\_\_` with `__UTILITIES__`, because I thought that was some copy artifact, but maybe the problem is that you really have those backslashes in your files?

**Comment by ctex77** [comment]
> I tested the example in the vignette and it works well. Note that I fixed your comment so that code chunks are properly highlighted, and I corrected `\_\_UTILITIES\_\_` with `__UTILITIES__`, because I thought that was some copy artifact, but maybe the problem is that you really have those backslashes in your files?

The backslashes are not in my files, but are here for exposition with github. What I use with the UTILITIES is the same as what you write and what the vignette writes. The follows is the result after the sourceCpp

> sourceCpp('test02.cpp',rebuild=T,verbose=T)

Generated extern "C" functions 
--------------------------------------------------------


#include <Rcpp.h>
#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// transformValue
double transformValue(double x);
RcppExport SEXP sourceCpp_1_transformValue(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(transformValue(x));
    return rcpp_result_gen;
END_RCPP
}

Generated R functions 
-------------------------------------------------------

`.sourceCpp_1_DLLInfo` <- dyn.load('C:/Users/jxf/AppData/Local/Temp/Rtmp6X6Ewp/sourceCpp-x86_64-w64-mingw32-1.0.8/sourcecpp_4c9053b02a2d/sourceCpp_4.dll')

transformValue <- Rcpp:::sourceCppFunction(function(x) {}, FALSE, `.sourceCpp_1_DLLInfo`, 'sourceCpp_1_transformValue')

rm(`.sourceCpp_1_DLLInfo`)

Building shared library
--------------------------------------------------------

DIR: C:/Users/jxf/AppData/Local/Temp/Rtmp6X6Ewp/sourceCpp-x86_64-w64-mingw32-1.0.8/sourcecpp_4c9053b02a2d

C:/PROGRA~1/R/R-41~1.2/bin/x64/R CMD SHLIB --preclean -o "sourceCpp_4.dll" "test02.cpp" 
"C:/rtools40/mingw64/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-41~1.2/include" -DNDEBUG   -I"C:/Users/jxf/Documents/R/win-library/4.1/Rcpp/include" -I"D:/test"        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c test02.cpp -o test02.o
C:/rtools40/mingw64/bin/g++ -std=gnu++11 -shared -s -static-libgcc -o sourceCpp_4.dll tmp.def test02.o -LC:/PROGRA~1/R/R-41~1.2/bin/x64 -lR
C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: test02.o:test02.cpp:(.text+0x105): undefined reference to `timesTwo(double)'
C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: test02.o:test02.cpp:(.text+0x1b9): undefined reference to `timesTwo(double)'
collect2.exe: error: ld returned 1 exit status
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Users/jxf/AppData/Local/Temp/Rtmp6X6Ewp/sourceCpp-x86_64-w64-mingw32-1.0.8/sourcecpp_4c9053b02a2d/sourceCpp_4.dll':
  LoadLibrary failure:  The specified module could not be found.
>

**Comment by eddelbuettel** [comment]
(Please take the time to properly typeset your post. There is plenty of help available by GitHub and others, starting with just the editing menu right above your edit box.)

**Comment by Enchufa2** [comment]
> C:/PROGRA~1/R/R-41~1.2/bin/x64/R CMD SHLIB --preclean -o "sourceCpp_4.dll" "test02.cpp"

The `utilities.cpp` file is missing there. However, I'm unable to reproduce this. I added a test with this exact example in a new branch, and:

- It works fine on Linux: https://github.com/RcppCore/Rcpp/actions/runs/1976537688
- It works fine on CRAN's win-builder service: https://win-builder.r-project.org/B1nT8P9oFKf3/examples_and_tests/tests/tinytest.Rout

So unfortunately we don't have much to work with here. Maybe some misconfiguration on your side? Maybe some path with spaces is causing trouble?

**Comment by eddelbuettel** [comment]
It's all irrelevant. `sourceCpp()` is designed to work on single file, and we have said since day one that to work with more files you really _really_ **really** need to switch to a package.

I have zero intentions of supporting any other madness (think: half a dozen packages replacing / extending base R's `library()` with whatever self-declared "modules" mechanism because somebody felt like it).   If OP need to find a way to work with multiples files, cannot set environment variables like `PKG_LIBS` to link and won't work with (fully working, tested. documented, ...) packages ... then we cordially extend an invitation to write a new helper and enjoy it.

But to me that does not belong to Rcpp, and I vote to just close this.  Life being short and all.

**Comment by Enchufa2** [comment]
I agree. The thing is that `sourceCpp`'s manual page says that, but the vignette says that it works with more files too, and it does indeed. At least on Linux and win-builder.

**Comment by eddelbuettel** [comment]
It's because we call `R CMD ...` that way but I don't think it is a design we really support.   I could be wrong.

The _intent_ of `sourceCpp()` is to work on a single file.

**Comment by ctex77** [comment]
Thank Enchufa2 and eddelbuettel for your interpretation. Altough I can not do it as Enchufa2, I now close the issue and try to find a way for my own preference.
