### ISSUE TITLE
Link time optimisation (LTO), One Definition Rule, and possible trouble for Modules

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#1207]
So a few days ago I got one of those CRAN emails with a 'fix this or else' ultimatum for [RcppBDT](https://github.com/eddelbuettel/rcppbdt).  For context, [RcppBDT](https://github.com/eddelbuettel/rcppbdt) is one of the oldest Rcpp-using packages around, and was the first package to wrap third-party date and time libraries, namely Boost Date_Time (hence the name).  I never sat down and defined all the (laborious) R-level ops in S3, S4, ... as other packages did later.  But it was both a really good testing ground for [anytime](https://github.com/eddelbuettel/anytime) (which also uses Boost Date_Time at the core of its parsers) and other packages --- and it stresses and uses Rcpp Modules in a good way.

That last part may now come to an end.  I poked around a little this weekend in a helper / exploration repo [rcpp-modules-odr](https://github.com/eddelbuettel/rcpp-modules-odr) which currently contains two packages: `odrcheck` and `odrr6`.  The first of these `odrcheck` "demonstrates" that we cannot have more than one Module containing a member variable (here from Boost Date_Time), or else the compiler (if properly instrumented) complains about violations to the OneDefitionRule.  I have not found a way around, the repo is a good starting ground.  There "should be away" but here the headers cross-pollineate, Modules creates code with its internal prefixing and maybe that it is the way it is and remains.

Which may mean we might need to put Modules to rest _in ambitious packages using more than one modules (and data)_. Simple packages with just one Module wrapping one class (of which I have a few too) appear to be fine.  

The obvious candidate for more complex use is R6.  I banged out the second test package `odrr6` just to demonstrate 'yet we can'.  I will probably extend this as needed and replace the code in [RcppBDT](https://github.com/eddelbuettel/rcppbdt).

Lastly, how to test / replicate. The R build needs to have `--enable-lto` which I added to my (local) build of R-devel (and I may for convenience add it to either the `drd` or `r-devel` container from our Rocker Project which are both rebuilt weekly).  On R installation build this way, `-flto` is added and at link time the whole enchillada gets analyzed / optimised.  And for [RcppBDT](https://github.com/eddelbuettel/rcppbdt) we get

```
/usr/local/lib/R-devel/lib/R/library/BH/include/boost/date_time/posix_time/posix_time_config.hpp:44:30: warning: type ‘struct time_duration’ violates the C++ One Definition Rule [-Wodr]
   44 |   class BOOST_SYMBOL_VISIBLE time_duration :
      |                              ^
/usr/local/lib/R-devel/lib/R/library/BH/include/boost/date_time/posix_time/posix_time_config.hpp:44:30: note: a type with different bases is defined in another translation unit
   44 |   class BOOST_SYMBOL_VISIBLE time_duration :
      |                              ^
/usr/local/lib/R-devel/lib/R/library/BH/include/boost/date_time/posix_time/ptime.hpp:32:30: warning: type ‘struct ptime’ violates the C++ One Definition Rule [-Wodr]
   32 |   class BOOST_SYMBOL_VISIBLE ptime : public date_time::base_time<ptime, posix_time_system>
      |                              ^
/usr/local/lib/R-devel/lib/R/library/BH/include/boost/date_time/posix_time/ptime.hpp:32:30: note: a type with different bases is defined in another translation unit
   32 |   class BOOST_SYMBOL_VISIBLE ptime : public date_time::base_time<ptime, posix_time_system>
      |                              ^
```

So it is just a warning.  So if CRAN were sane(r), they might leave us alone but I am not going to be the one arguing this with them.  Life being too short and all.  And, when everything is said and then, there as been an end of the road for Modules for quite some time so may as well go with the fllow.  Compiler warnings are there for a reason even if Modules's code generation has passed quite some tests of time it may be time for a wrap.  Obviously we won't remove it from the Rcpp package but this may be one of those time where we can highlight `#include <Rcpp/Lightest>` which is what I used in `odrr6` so far too.

**Comment by Enchufa2** [comment]
Doesn't just an `#include <RcppBDT.h>` in `src/toPOSIXct.cpp` solve the issue?

**Comment by eddelbuettel** [comment]
Chapeau.  It does.  (Well we need to adjust already-present Boost headers a little ...)

Now why didn't I think of that?  I was fully aware that RcppBDT.h was a 'portmanteau' header file for all the _Modules-using_ source files and declarations.  I didn't think it could possible be missing from this (non-Modules) later addition.

Really well spotted.  I owe you a cold one.
