### ISSUE TITLE
Converting strings to dates is slow due to tryCatch

### ISSUE THREAD

**Issue by louisswarren** [RcppCore/Rcpp#1208]
The Date constructor for strings uses R functions, which causes Rcpp to insert a very costly tryCatch around any Rcpp code which uses it. Using fast_eval prevents this issue. Handling of invalid input is unchanged.

I've implemented this solution here: #1209

As a benchmark, the following script's runtime drops from 40 seconds to 16 seconds on my machine:

```R
library(Rcpp)

cppFunction('
  double dates_offset(std::string& base, Rcpp::StringVector& date_strs) {
    double offset = 0;
    Date date = Date(base, "%Y-%m-%d");
    for (auto it = date_strs.begin(); it != date_strs.end(); ++it) {
      Date d = Date(Rcpp::as<std::string>(*it), "%Y-%m-%d");
      offset += d.getDate() - date.getDate();
    }
    return offset;
  }
')

base <- "2000-01-01"
dates <- seq(as.Date('1000-01-01'), as.Date('2999-12-31'), by="day")
dates_offset(base, dates)
```

And the proof is in the profvis:
![image](https://user-images.githubusercontent.com/8112477/160751341-343daf09-e1f1-4e4e-b985-d2e4cd214cd6.png)

Compiling with g++ (GCC) 11.2.0. My sessionInfo:
```
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS:   /usr/lib/libblas.so.3.10.0
LAPACK: /usr/lib/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=en_NZ.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_NZ.UTF-8        LC_COLLATE=en_NZ.UTF-8
 [5] LC_MONETARY=en_NZ.UTF-8    LC_MESSAGES=en_NZ.UTF-8
 [7] LC_PAPER=en_NZ.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_NZ.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.1.2
```

**Comment by louisswarren** [comment]
> Appreciate the effort, but you can achieve the same with `unwindProtect` (which activates the `RCPP_USE_UNWIND_PROTECT` define):

Yes, in my code I do get around this. However, it seems like a bit of a performance foot-gun; before I was aware that Date "cheats" by using R functions, I assumed it would be performant. As far as I can tell, Date is an outlier here, aside from the obvious `new.env`.
 
> Besides, if an Rcpp consumer needs for some reason to disable `unwindProtect`, they should be able to _completely_ disable it, including `Date`, so I'd even say that this patch is a bad idea.

Would it not be better for it to be disabled for date than for it to be disabled completely? The latter seems unsafe; I suggest enabling it for `Date` specifically because I don't think there is a string input that actually causes it to unwind - invalid inputs return an invalid date with no exceptions. But am I missing some case? If so then this patch is indeed a bad idea; it's predicated on `Date` actually being safe.

**Comment by Enchufa2** [comment]
The `Date` class is a quite old piece of code in Rcpp. E.g., what you are doing above takes just a few milliseconds and a single line of code in plain R (`sum(dates - as.Date(base))`), or even less in Rcpp by avoiding so many conversions:

``` r
Rcpp::cppFunction('
  double dates_offset(std::string& base, DateVector& date_strs) {
    Date date = Date(base, "%Y-%m-%d");
    return sum(date_strs - date);
  }
')

base <- "2000-01-01"
dates <- seq(as.Date('1000-01-01'), as.Date('2999-12-31'), by="day")
system.time(dates_offset(base, dates))
#>    user  system elapsed 
#>   0.002   0.000   0.002
```

If anything, `Date` would benefit from a complete rewrite. But there are much better alternatives out there, so I'm not sure it would pay off.

> Disabling protection with limited scope inside Rcpp seems safer than asking consumers to do it for their code.

Fast evaluation does _not_ disable protection. `unwindProtect` is _another_ faster and more modern path for evaluating R calls provided by R itself, and it's perfectly safe. What I'm saying is that maybe there are still use cases out there in which the `tryCatch` is required for some reason. I don't think so, but still, it's a number of years with these `tryCatch` in place. So after the change to `unwindProtect` by default, it is a good practice to support switching to the old behaviour for backwards compatibility for some time, just in case. And this includes `Date`.

**Comment by louisswarren** [comment]
> what you are doing above takes just a few milliseconds ... or even less in Rcpp by avoiding so many conversions

To be clear, the code above is a minimal reproducible example I wrote specifically to demonstrate the performance difference by calling `Date` a lot. But yes, the fastest code is the code that never runs.

> Fast evaluation does _not_ disable protection. `unwindProtect` is _another_ faster and more modern path for evaluating R calls provided by R itself, and it's perfectly safe.

Ah, thank you for explaining. I couldn't find documentation on this, but I see now it's explained in the changelog (is this the core location for explanatory documentation?).

> What I'm saying is that maybe there are still use cases out there in which the `tryCatch` is required for some reason... so after the change to `unwindProtect` by default, it is a good practice to support switching to the old behaviour for backwards compatibility for some time, just in case. And this includes `Date`.

If so, and/or if `unwindProtect` will be the default in the next release anyway, then I agree that `Date` should be left as is (or rewritten entirely).

I found this issue only after profiling a non-trivial Rcpp codebase, and it took some time to find that `Date` was the culprit. It may be useful to document that `Date` is not currently fast.

**Comment by eddelbuettel** [comment]
Also look at (newer, different) code in package `anytime` -- which does this vectorises, and the cost of creating a `Date` vector is a single attribute set (line 451 in `src/anytime.cpp`).  Depending on what _format_ you use Simon' `fasttime` may also help.

As @Enchufa2 mentioned, `Date(time)(Vector)` are a little odd.  They are the first parts I wrote, rewritten once to be less awful but still have warts ... but we a) can't undo the fundamental design (oddity having a scalar type and vectors) and b) if you pay attention to your interface the call is less expensive.   And I agree that

> If anything, Date would benefit from a complete rewrite.

yet

> But there are much better alternatives out there

and we have bigger fish to fry in `Rcpp` if we decide to rweite stuff.

**Comment by Enchufa2** [comment]
> To be clear, the code above is a minimal reproducible example I wrote specifically to demonstrate the performance difference by calling `Date` a lot. But yes, the fastest code is the code that never runs.

I figured as much, but just in case. ;-)

> > Fast evaluation does _not_ disable protection. `unwindProtect` is _another_ faster and more modern path for evaluating R calls provided by R itself, and it's perfectly safe.
> 
> Ah, thank you for explaining. I couldn't find documentation on this, but I see now it's explained in the changelog (is this the core location for explanatory documentation?).

No, it's not. It's not in the docs because this wasn't a user-facing feature. Now that this mechanism has passed the test of time, we are planning to enable it by default and pretty much everybody will benefit from this transparently.

> I found this issue only after profiling a non-trivial Rcpp codebase, and it took some time to find that `Date` was the culprit. It may be useful to document that `Date` is not currently fast due to calling R functions (this issue showing up in google results may have to suffice). I doubt most Rcpp users look into the internals, given that most documentation I've found include a basic explanation of C++.

Maybe a FAQ entry giving some hints on the proper usage of `Date[time]` and `Date[time]Vector`, and pointing to better alternatives for advanced usage cases, would be useful. But then people still try to `push_back()` into Rcpp `Vector` classes...

**Comment by eddelbuettel** [comment]
I just added a new paragraph to the Rcpp-FAQ vignette mentioning that Date and Datetime are not exactly meant for large scale conversion, giving additional pointers.  That, along with the discussion here, hopefully addresses the concerns raised so I am going to close this.  If you think there are other matters to discuss pertaining to this and that we haven't touched upon please feel free to reopen this.  Thanks again for opening an issue and trying to make Rcpp better, it is always appreciated!
