### ISSUE TITLE
Tag 1.0.8.3 in git does not match version 1.8.0.3 published in CRAN

### ISSUE THREAD

**Issue by ellert** [RcppCore/Rcpp#1213]
The 1.8.0.3 version published in CRAN corresponds to commit 136ec60c48da7c4361b8de4c6a72035ed63d6133.
The 1.8.0.3 tag in git is not on this commit.

**Comment by eddelbuettel** [comment]
<Deep sigh>  Oh well.  Consider `git` as a storage medium. 

What counts for releases is CRAN, so 1.0.8.3 is whatever you get from them.  But `git` does know what a tag is and CRAN Release Policy doesn't mentioned.  What _is_ tagged 1.0.8.3 is two microaspects better.  I can live with that.   If all this poses a production problem for you maybe you live with 1.0.8 from January.  

So I suggest we just close this.  Generally the two match, here we needed to accomodate a small oversight in CRAN 1.0.8.2.
