### ISSUE TITLE
Allow client packages of Rcpp to extend BEGIN_RCPP macro

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/Rcpp#1215]
In some cases, it would be useful for R packages to be able to "extend" the `BEGIN_RCPP` macro with their own macro definitions. (For example, because they'd like to run their own custom code within the auto-generated attributes wrapper functions)

Unfortunately, it's not possible in C++ to redefine a macro in terms of its prior definition, so packages cannot "extend" the macro as-is -- the only option currently is to replace it whole-sale.

This is the strategy currently adopted by reticulate, but is obviously going to be brittle if Rcpp changed those macro definitions later:

https://github.com/rstudio/reticulate/blob/main/src/reticulate_types.h#L106-L115

One proposal would be to move the current macro definition to `BEGIN_RCPP_BASE` (or some similar name), then define `BEGIN_RCPP` in terms of that definition (if it's not already defined). This way, package authors could provide their own definition of `BEGIN_RCPP`, as an extension of the existing `BEGIN_RCPP_BASE`.

**Comment by eddelbuettel** [comment]
Coming back to this (as I prepare/finalize 1.0.9): as I recall `reticulate` now does just this for better Python initialization. Is there something we want to generalize out for Rcpp?

**Comment by kevinushey** [comment]
We're still providing our own definition of `BEGIN_RCPP`, so it does risk breakage if Rcpp's own `BEGIN_RCPP` macro (or other companion macros like `END_RCPP`) were to change in a backwards-incompatible way.

**Comment by eddelbuettel** [comment]
Well then steady-state and current status quo is fine for everybody I presume?

**Comment by kevinushey** [comment]
Right, I think so.
