### ISSUE TITLE
[FR] Move semantics for Rcpp::String

### ISSUE THREAD

**Issue by p00ya** [RcppCore/Rcpp#1218]
`Rcpp::String`, unlike Rcpp classes that just wrap SEXPs, copies potentially large data on assignment and construction.  This can often be hidden because of the many implicit type conversions Rcpp exposes.

Some (somewhat contrived) examples:

```c++
void Test1() {
  std::string s = SomeVeryLargeString();
  // Initializes from a std::string, making a std::string copy.
  Rcpp::String rs = s;
}

void Test2(Rcpp::String& out) {
  Rcpp::String rs = SomeVeryLargeRcppString();
  if (ShouldSet()) {
    // Calls Rf_mkCharLenCE, making another copy.
    out = rs;
  }
}

void Test3(std::vector<Rcpp::String>& v) {
  Rcpp::String rs = SomeVeryLargeRcppString();
  // Depending on when SomeVeryLargeRcppString last caused String::setData
  // to get called, could either be a (shallow) SEXP copy or a Rf_mkCharLenCE copy.
  v.push_back(rs);
}

void Foo(const Rcpp::String& rs) {
  // Need to make copy of rs to mutate.
}

void Test4() {
  Foo(rs);
}
```

Better C++11 would be:

```c++
void Test1() {
  std::string s = SomeVeryLargeString();
  // Move the std::string to rs.buffer.
  Rcpp::String rs = std::move(s);
}

void Test2(Rcpp::String& out) {
  Rcpp::String rs = SomeVeryLargeRcppString();
  if (ShouldSet()) {
    // Move rs.buffer or rs.data without making a copy.
    out = std::move(rs);
  }
}

void Test3(std::vector<Rcpp::String>& v) {
  Rcpp::String rs = SomeVeryLargeRcppString();
  // Move rs.buffer or rs.data without making a copy.
  v.push_back(std::move(rs));
}

// Pass by value!
void Foo(Rcpp::String rs) {
  // rs is mutable!
}

void Test4() {
  // No deep-copy.
  Foo(std::move(rs));
}
```

For the C++11 example to actually avoid copies, it will need appropriate move/copy/assignment overloads to be added to `Rcpp::String` for both `Rcpp::String&&` and `std::string&&`.

Admittedly I don't have any real-world benchmarking to quantify the improvement.  Even without benchmarking, I think this is a small and safe change (with appropriate C++11 guards).  Happy to send a PR if it sounds acceptable.

**Comment by eddelbuettel** [comment]
Thanks for this. The topic is relevant, if somewhat murky, as 'strings' are dealt with separately by R itself.

We now have C++11 as a baseline so if you propose something 'better' we would likely be all ears!

**Comment by p00ya** [comment]
Yeah I'll leave the strings already in SEXPs alone.  Rcpp itself is making copies of std::string and char arrays, which I can fix.  Thanks for the quick response, I'lll send a PR.

**Comment by p00ya** [comment]
> Out of curiousity, did you ever benchmark 'before' and 'after' ? Small strings? Large strings? Lots of them or LOTS OF THEM?

No, but I'm happy to post something reproducible and the results here.

For an idea of scale I was noticing the copying and `Rf_mkCharLenCE` being  significant with ~1M x small (~16 byte) strings.

**Comment by eddelbuettel** [comment]
Great!  Maybe even write a short piece for the Rcpp Gallery?

**Comment by p00ya** [comment]
I'll see about the Gallery but just results for now sorry.

Here's a toy function for benchmarking purposes.  It doesn't even have any explicit `std::move`, just passing around some strings in ways that seem pretty idiomatic to me.

```cpp
#include <string>
#include <vector>

#include <Rcpp.h>
using namespace Rcpp;

namespace {

std::string Render(int i) {
  std::string s;
  s.reserve(2 + i / 10 + (i < 0 ? 1 : 0));
  s += std::to_string(i);
  if ((i / 10) % 10 == 1) {
      s += "th";
  } else {
      switch (i % 10) {
        case 1:
          s += "st";
          break;
        case 2:
          s += "nd";
          break;
        case 3:
          s += "rd";
          break;
        default:
          s += "th";
          break;
      }
  }
  return s;
}

}  // namespace

// [[Rcpp::export]]
CharacterVector AddSuffixes(const IntegerVector& x) {
  const size_t n = x.size();
  std::vector<String> v;
  v.reserve(n);
  for (int i = 0; i < n; ++i) {
    v.push_back(Render(x[i]));
  }
  return CharacterVector(v.begin(), v.end());
}

/*** R
packageVersion("Rcpp")
million <- seq(1L, 1000000L)
microbenchmark::microbenchmark(
  AddSuffixes(million)
)
*/
```

Results from HEAD:

```
Unit: milliseconds
                 expr      min       lq     mean   median       uq      max
 AddSuffixes(million) 734.3104 852.4978 942.4905 916.9386 978.9277 3255.274
 neval
   100
```

Results from CRAN (1.0.8.3):

```
Unit: milliseconds
                 expr      min       lq     mean   median       uq      max
 AddSuffixes(million) 969.9753 1073.511 1203.097 1135.823 1262.379 3431.406
 neval
   100
```
