### ISSUE TITLE
Issues wtih installing Rcpp -- Rcpp Sugar

### ISSUE THREAD

**Issue by DimitriBrattle** [RcppCore/Rcpp#1220]
I am having issues with install Rcpp. Whenever I do so -- and I have tried doing so on several different machines now, and using both standard installation, as well as installing from source, as well as downloading the tar and installing using that -- I run into an error of the form:

cannot create file 'C:/.../AppData/Local/R/win-library/4.2/00LOCK-Rcpp/00new/Rcpp/include/Rcpp/sugar/operators/logical_operators__Vector__Vector.h', reason 'No such file or directory'

Other missing files/directories I have come across during the installation include (among others):

AppData/Local/R/win-library/4.2/00LOCK-Rcpp/00new/Rcpp/tinytest/testRcppInterfaceExporter/inst/include/testRcppInterfaceExporter.h', reason 'No such file or directory'

AppData/Local/R/win-library/4.2/00LOCK-Rcpp/00new/Rcpp/tinytest/testRcppInterfaceExporter/inst/include/testRcppInterfaceExporter_RcppExports.h', reason 'No such file or directory'

**Comment by Enchufa2** [comment]
How many subdirectories are in that path? Is it a local path or a network path? It seems that you're hitting some limit there. Anyway, this is not an Rcpp issue, so we can't be of much help here, sorry. The R Help mailing list would be a good candidate for such a question. Other fellow useRs may have run into such trouble on Windows before.

**Comment by eddelbuettel** [comment]
As @Enchufa2 said, you are having what appears to be a generic R question for which many help options exist.  As there is nothing Rcpp specific I will close.  Please do not hesitate to reopen with pertinent materal if you find something about Rcpp that needs adressing.
