### ISSUE TITLE
Rcpp::unique() order changes when restarting R

### ISSUE THREAD

**Issue by jhorzek** [RcppCore/Rcpp#1222]
Thank you for the awesome package! I've been using the Rcpp::unique function in one of my R packages, but the order of the returned elements changes every time I restart the R session. Here is a simple example:

    library(Rcpp)
    cppFunction('Rcpp::StringVector uniqueVectorElements(Rcpp::StringVector vec) {
      return (Rcpp::unique(vec));
    }')
    
    set.seed(123)
    (v <- LETTERS[sample(1:5, 10, replace = T)])
    # "C" "C" "B" "B" "C" "E" "D" "A" "B" "C" (this part stays the same)
    uniqueVectorElements(v)
    # "A" "E" "B" "C" "D" (this part changes when restarting the R session)

Is there a way to set the seed such that uniqueVectorElements(v) always returns the same vector even when restarting R?
I am using Ubuntu 22.04 and R version 4.2.0 with Rcpp_1.0.8.3

**Comment by eddelbuettel** [comment]
I can reproduce this on the command-line (simulating fresh sessions):

```
edd@rob:~$ Rscript -e 'Rcpp::cppFunction("Rcpp::StringVector uniqueVectorElements(Rcpp::StringVector vec) {  return (Rcpp::unique(vec)); }"); set.seed(123); (v <- LETTERS[sample(1:5, 10, replace = TRUE)]); uniqueVectorElements(v)'
 [1] "C" "C" "B" "B" "C" "E" "D" "A" "B" "C"
[1] "D" "A" "C" "B" "E"
edd@rob:~$ Rscript -e 'Rcpp::cppFunction("Rcpp::StringVector uniqueVectorElements(Rcpp::StringVector vec) {  return (Rcpp::unique(vec)); }"); set.seed(123); (v <- LETTERS[sample(1:5, 10, replace = TRUE)]); uniqueVectorElements(v)'
 [1] "C" "C" "B" "B" "C" "E" "D" "A" "B" "C"
[1] "E" "A" "B" "C" "D"
edd@rob:~$ Rscript -e 'Rcpp::cppFunction("Rcpp::StringVector uniqueVectorElements(Rcpp::StringVector vec) {  return (Rcpp::unique(vec)); }"); set.seed(123); (v <- LETTERS[sample(1:5, 10, replace = TRUE)]); uniqueVectorElements(v)'
 [1] "C" "C" "B" "B" "C" "E" "D" "A" "B" "C"
[1] "B" "C" "E" "D" "A"
edd@rob:~$ 
```

But I am not sure `unique()` guaranrtees 'session-stable' behaviour.  Note that the answer is _correct_ in all three cases.

**Comment by jhorzek** [comment]
Good to know! Then I'll sort the vector before returning. Thanks for clarifying!

**Comment by eddelbuettel** [comment]
I took a look, and unique uses a hash internally and there these things can happen.  I think one is simply best-advised to sort this.
