### ISSUE TITLE
Why are the computation times of these two functions so different?

### ISSUE THREAD

**Issue by JiaqiHu2021** [RcppCore/Rcpp#1224]
When I am writing a for loop, I find a very confusing question, the running times of the following two functions is thousands of times. The only difference between two functions are whether or not return a value. Can you help me figure this out?

```{c++}
// [[Rcpp::export]]
void test1(NumericMatrix x){
  int n = x.rows();
  int p = x.cols();
  double s = 0;
  for(int k = 0; k < 100; k++){
    s = 0;
    for(int i = 0; i < n; i++){
      for(int j = 0; j < p; j++){
        s += x(i, j);
      }
    }
  }
}

// [[Rcpp::export]]
double test2(NumericMatrix x){
  int n = x.rows();
  int p = x.cols();
  double s = 0;
  for(int k = 0; k < 100; k++){
    s = 0;
    for(int i = 0; i < n; i++){
      for(int j = 0; j < p; j++){
        s += x(i, j);
      }
    }
  }
  return(s);
}
```

The running time:

```{R}
n = 1000
x = matrix(rnorm(n*n), n, n)
microbenchmark::microbenchmark(test1(x), test2(x), times = 10)
```

```{r}
Unit: microseconds
     expr       min        lq       mean    median        uq       max neval cld
 test1(x)     1.209     1.375     8.5547     3.938    15.709    21.542    10  a 
 test2(x) 93331.709 93770.918 95583.0425 95458.793 97061.084 98564.043    10   b
```

**Comment by eddelbuettel** [comment]
(Ideally pure usage questions would go to the mailing list.  Could you consider posting there?  It requires sign-up in order to post because of evil spam, but it is worth it.)

**Comment by eddelbuettel** [comment]
Your code does not compile for me. I would start there.  Ubuntu 22.04, Rcpp 1.0.9.  

Your benchmark may also runs a different `test2`.

**Comment by JiaqiHu2021** [comment]
Thank you so much for your help, I understand it!

It's me who thinks poorly, I shouldn't ask questions here, thanks again

**Comment by eddelbuettel** [comment]
Oh, the question was not _bad_ -- I have spent lots of time chasing similar mirages.  We all do.  It's just that is not he best place to ask -- the list or SO are better (and will have more viewer, hence better results).

And I just realized there _is_ one interesting question hiding here: what, if anything, is the cost of the return comparing stack and heap?  So here is a fourth variant:

```cpp
// [[Rcpp::export]]
void test4(NumericMatrix x, double &v){
  int n = x.rows();
  int p = x.cols();
  double s = 0;
  for(int k = 0; k < 100; k++){
    s = 0;
    for(int i = 0; i < n; i++){
      for(int j = 0; j < p; j++){
        s += x(i, j);
      }
    }
  }
  v = s;
}
```

and a slightly modified setup (with an added variable):

```r
> Rcpp::sourceCpp("issue1224.cpp")
issue1224.cpp: In function ‘void test3(Rcpp::NumericMatrix)’:
issue1224.cpp:37:7: warning: unused variable ‘y’ [-Wunused-variable]
   37 |   int y = 0;
      |       ^

> n <- 1000

> x <- matrix(rnorm(n*n), n, n)

> v <- NA

> microbenchmark::microbenchmark(test1(x), test2(x), test3(x), test4(x, v), times = 10)
Unit: microseconds
        expr       min        lq        mean     median         uq        max neval cld
    test1(x)     1.222     2.134     64.2658      7.745      8.898    593.659    10  a 
    test2(x) 96438.642 99012.148 111032.3270 104576.735 109090.735 159788.013    10   b
    test3(x)     1.238     1.357     85.0530      8.281      9.051    795.164    10  a 
 test4(x, v) 97256.325 98169.609 101633.3988 100773.103 103870.364 109313.490    10   b
> 
```

"None". Is the reassuring answer.  (As that difference is noise on my machine.)

**Comment by JiaqiHu2021** [comment]
Indeed this is also a very interesting question, no need to worry about which methods is faster.
