### ISSUE TITLE
RcppModules fail compilation when class constructor has more than 7 arguments

### ISSUE THREAD

**Issue by JSzitas** [RcppCore/Rcpp#1238]
Hello! Thank you for this package and for all the work you put into it - much appreciated! I searched quite widely for this problem, and failed to find any mention of it anywhere. Under the chance that this only happens on my system, I am sharing here - and hopefully this also serves as documentation for someone trying to solve the same issue, as it is rather strange. 

A minimally reproducible example - the following does not compile:
```cpp
#include <Rcpp.h>
using namespace Rcpp;
class ModuleBreaker {
public:
  ModuleBreaker( int arg_1, int arg_2, int arg_3,
                 int arg_4, int arg_5, int arg_6,
                 int arg_7, int arg_8) {//note arg_8
}
};
RCPP_EXPOSED_CLASS_NODECL(ModuleBreaker)
RCPP_MODULE(ModuleBreaker) {
  Rcpp::class_<ModuleBreaker>("ModuleBreaker")
  .constructor< int,int,int,int,int,int,int, int>("basic contructor");
}
```
The compilation failure is a repeat of 'Wrong number of template arguments (8, should be 7)' decrementing until 1 (i.e. the next message goes 'Wrong number of template arguments (8, should be 6)'). My guess is that this is some template magic I am not yet experienced enough to understand. Nonetheless, this failing to compile is quite strange, as it is seemingly nothing but an exposed class with a constructor. 

However, using one less argument, it compiles: 

```cpp
#include <Rcpp.h>
using namespace Rcpp;

class ModuleBreaker {
public:
  ModuleBreaker( int arg_1, int arg_2, int arg_3,
                 int arg_4, int arg_5, int arg_6,
                 int arg_7) {}
};

RCPP_EXPOSED_CLASS_NODECL(ModuleBreaker)
RCPP_MODULE(ModuleBreaker) {
  Rcpp::class_<ModuleBreaker>("ModuleBreaker")
  .constructor< int,int,int,int,int,int,int>("basic contructor");
}
```

This is under **g++**, using `-std=gnu++14 -DNDEBUG  -fpic  -g -O2`. 

Further, my `sessionInfo()` produces: 

```R
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 20.2

Matrix products: default
BLAS/LAPACK: /opt/OpenBLAS/lib/libopenblas_zenp-r0.3.15.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=sk_SK.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=sk_SK.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=sk_SK.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rcpp_1.0.7

loaded via a namespace (and not attached):
[1] compiler_4.1.0   tools_4.1.0      codetools_0.2-18```
```

Sorry if this has some straight-forward explanation and is a failure on my part to RTFM - I just could not find an explanation. Thanks for your time!

**Comment by eddelbuettel** [comment]
I think we covered this (or related issues with other pre-C++11 code using autogenerated stubs in lieu of variaditc templates) before.  You _immediate_ fix is to make argument N+1, N+2, ... all members of a list object in position N.

**Comment by JSzitas** [comment]
Thanks for the speedy response! And I agree, this has a fairly straight-forward solution. I just wanted to confirm that I am not going crazy. And to have a record if someone else runs into this, so they do not spend too much time on it.

Thanks again for the tooling, much appreciated!

**Comment by kevinushey** [comment]
For reference, the methods defined are here:

https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/module/Module_generated_class_constructor.h

and indeed, they predate C++11 support so "code bloat" up to some `N` was the solution, with `N = 7` apparently being chosen here.
