### ISSUE TITLE
Apparent C++20 compilation failure

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#1244]
Per email forwarded by BDR and originally to @stla the 'new at CRAN' package [jack](https://github.com/stla/jackR) bonks:

>This fails to install with LLVM clang 15.0.7 (current) with libc++ as its
>(native) C++ library.
>
>    ```
>    ../Rcpp/include/Rcpp/sugar/functions/sapply.h:36:19: error: no template named
>    'result_of' in namespace 'std'; did you mean 'traits::result_of'?
>            typedef typename ::std::result_of<Function(typename
>    SugarExpression::stored_type)>::type type;
>                             ^~~~~~~~~~~~~~~~
>                             traits::result_of
>    .../Rcpp/include/Rcpp/traits/result_of.h:30:8: note: 'traits::result_of'
>    declared here
>    struct result_of{
>           ^
>     ```
>  jack 5.0.0 specifies C++20, but std::result_of was removed in that standard
>  having been deprecated in C++17 according to
>  https://en.cppreference.com/w/cpp/types/result_of
>  and replaced by invoke_result since C++17.

**Comment by eddelbuettel** [comment]
FWIW I have not yet been able to tickle anything on Linux with `clang++-15` when working with `Rcpp` itself and its tests.

**Comment by kevinushey** [comment]
It looks like std::result_of was removed in C++20, so perhaps that's related?

I think invoke_result is the modern alternative. https://en.cppreference.com/w/cpp/types/result_of

**Comment by Enchufa2** [comment]
A simple fix would be to add yet another branch to use `invoke_result` for C++17 or newer in `Rcpp/sugar/functions/sapply.h`.

It seems that this was added to support lambda functions in `sapply`. But the other users of `::Rcpp::traits::result_of` (`lapply`, `mapply` and `outer`) still do not support lambdas. So it would be nice to move conditional compilation stuff to `Rcpp/traits/result_of.h` to generalize this support.

**Comment by eddelbuettel** [comment]
(Yes, BDR made that comment too.  I added it to the web comment, if you replied to email you didn't see it.)

Fully agreed on the need to do this for all *apply functions.

**Comment by eddelbuettel** [comment]
The package experiencing the issue moved [itself from C++20 to C++17](https://github.com/stla/jackR/commit/41ee51d0a3ce6770b7ca69f5d561d3889ccf95a3).

**Comment by eddelbuettel** [comment]
And that of course should not have failed on you.  We'll look into it.

Errors apparently only come up with clang++(-15) _and_ its own libc++.

**Comment by eddelbuettel** [comment]
I took care of the compilation issue, turning lambdas on in the *apply functions is more work ...  Anyone?

**Comment by Enchufa2** [comment]
Ok to the quick patch for now. I currently do not have the time to dig deeper.

**Comment by eddelbuettel** [comment]
Yes we need to unblock this so once PRed and merged I will put a 1.0.10.2 onto the drat repo.

**Comment by eddelbuettel** [comment]
Closing this as #1248 is merged.
