### ISSUE TITLE
Nudge to add 'methods' to Imports when using setLoadAction?

### ISSUE THREAD

**Issue by MichaelChirico** [RcppCore/Rcpp#1254]
When `hasCppInterface()`, Rcpp adds a build-time dependency on 'methods':

https://github.com/RcppCore/Rcpp/blob/7fc0a8f01a18490870ddc1d40c1dd39c941528e8/src/attributes.cpp#L2541

It seems reasonable to me that such packages should list 'methods' in their Imports (or perhaps Suggests). Though it's not clear to me from WRE whether build-time-only dependencies are required in the DESCRIPTION, let alone for default packages that are guaranteed to be available, it seems proper to signal that the package uses 'methods' in this way somehow.

FWIW, I came across this by running `tools:::.check_packages_used(dir = pkg_dir)` for many packages, which flags this usage of `::` not corresponding to a DESCRIPTION entry.

Came across this in three packages, so I'm wondering if it's something Rcpp should be handling:

https://github.com/kosukeimai/MatchIt/pull/150
https://github.com/davidgohel/gdtools/pull/63
https://github.com/aadler/lamW/pull/1

Here are roughly 200 packages with this entry on GitHub (I haven't checked how many of them have the DESCRIPTION entry):

https://github.com/search?q=%22methods%3A%3AsetLoadAction%22+%22%23+Register+entry+points+for+exported+C%2B%2B+functions%22&type=code

**Comment by eddelbuettel** [comment]
But how would we nudge other packages to alter _their_ DESCRIPTION files?

This issue has been around Rcpp "since forever".  IIRC Rcpp Modules requires it, John's Reference Classes do too IIRC.

**Comment by eddelbuettel** [comment]
`compileAttributes()` touches `R/RcppExports.R` and `src/RcppExports.cpp` and leaves everything else alone.  That has served us well so far.

**Comment by MichaelChirico** [comment]
I'm not familiar enough with the whole UX to know where it'd be appropriate... are there any other user-facing messages coming from `compileAttributes()`?

don't you touch NAMESPACE as well for dynamic object registration? Touching DESCRIPTION for this case wouldn't be _too_ farfetched, but admittedly tougher to do from the C++ side where the base functions for working with that file are more cumbersome to use.

This is basically moot so long as CRAN is not complaining about the omission -- raising in case it passes benefit/cost for you. But also don't hesitate to close as WONTFIX.

**Comment by eddelbuettel** [comment]
We do not touch NAMESPACE from Rcpp.

- - - 

Now: progress is made by actually doing and trying.  So I dp look forward to a PR, ideally supplemented by running reverse dependency checks against 2600+.  Asking me, an unpaid volunteer as far as work on Rcpp in concerned, to do both is ...  a wee bit unrealistic. I am sure you can sympathize.

**Comment by MichaelChirico** [comment]
I of course sympathize :)

That said, it's not a priority for me, so I wouldn't expect a PR anytime soon. I'll close as it's unlikely to become a priority for anyone unless CRAN starts enforcing this.

**Comment by eddelbuettel** [comment]
`methods` is a weird one.  "Back in the day" we scored a simple victory in `littler` by loading it when `Rscript` didn't.  R got smarter and faster and "eventually" `Rscript` switched and autoloaded it too.  That makes me think we should both bark at the R Core tree instead ...
