### ISSUE TITLE
sourceCpp compile error stderr cannot be caught/suppressed

### ISSUE THREAD

**Issue by andrjohns** [RcppCore/Rcpp#1257]
When writing a `try()` function to check for compile errors from `sourceCpp` the compilation error is always printed to the console, regardless of whichever combinations of `try()`, `suppressMessages()`, `suppressWarnings()` or `sink` are used.

Reprex:

``` r
dcode <- "//[[Rcpp::export]]\n int fun(int x) { const int y; return x; }"
status <- suppressWarnings(suppressMessages(
  output <- capture.output(
    try(Rcpp::sourceCpp(code = dcode, verbose=FALSE, echo=FALSE),
                 silent = TRUE))
))
```

<sup>Created on 2023-03-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<summary>
Standard output and standard error
</summary>

``` sh
fileeed07e197428.cpp:2:29: error: default initialization of an object of const type 'const int'
 int fun(int x) { const int y; return x; }
                            ^
                              = 0
1 error generated.
make: *** [fileeed07e197428.o] Error 1
```

**Comment by eddelbuettel** [comment]
Hm, I think that's the way it is and likely will be -- `Rcpp::sourceCpp()` and friends call functions calling commands like `R CMD COMPILE` and `R CMD SHLIB` so the output suppression you desire happens at the _operating system command level_ and R's own output suppressers (working on R's own output streams) have nothing for them.  

Not really an Rcpp issue.

**Comment by andrjohns** [comment]
`sourceCpp` calls `system()`, and this can be handled with `system()`:
```r
cat("int fun(int x) { const int y; return x; }", file="foo.cpp")
system("R CMD SHLIB foo.cpp", ignore.stderr = TRUE, ignore.stdout = TRUE)
```

Could `verbose`/`showOutput`/`echo` be passed to these?

**Comment by eddelbuettel** [comment]
If you believe strongly that this is warranted, maybe you could sketch a change proposal in this issue, and ideally test it? One of us may take a look.

**Comment by andrjohns** [comment]
Another perspective, it also means that the `verbose` flag is only respected if the compilation succeeds. Since the following:

```r
gooddcode <- "//[[Rcpp::export]]\n int fun(int x) { return x; }"
Rcpp::sourceCpp(code = gooddcode, verbose=FALSE, rebuild = TRUE)
```

Does not print the compilation call, but it does get printed if the compilation fails

**Comment by Enchufa2** [comment]
I think it's a reasonable request. I'll take a look, I have some experience with this kind of stuff with bspm.

**Comment by eddelbuettel** [comment]
@andrjohns Can you do us a favour and build of the branch @Enchufa2 submitted as part of his PR #1259 ?  It now uses `system2()` and should be able to accomodate you.

**Comment by eddelbuettel** [comment]
@andrjohns I am going to merge this now, assuming it will indeed address the issue you pointed out to us.  Should it still be an issue for you please feel free to reopen this and append any additional detail you can think of.

**Comment by eddelbuettel** [comment]
Can you look into a PR accomplishing what you desire exactly as you desire?  We would be happy to review.
