### ISSUE TITLE
Document Rcpp functions with default arguments that appear in their header files

### ISSUE THREAD

**Issue by zhuxr11** [RcppCore/Rcpp#1265]
I am using roxygen 2 (`//'`) to document Rcpp functions. As a common practice, functions shared across multiple files are defined in header file with default arguments ([reference here](https://stackoverflow.com/questions/14902129/default-parameters-in-h-and-cpp-files)). However, roxygen2 comments live in `.cpp` files (not the header files), where default parameters are not defined (and cannot be defined there even with the same default values, since this is not allowed in C++). In the end, the help page does not show any default parameters. I am wondering how this could be improved.

Example:

In `test.h`:

```
# ifndef TEST_CPP
# def TEST_CPP

#include <Rcpp.h>
using namespace Rcpp;

int timesTwo(int x = 0);

#endif
```

In `test.cpp`:

```
//' Multiply a number by two
//' 
//' @param x A single integer.
//' @export
// [[Rcpp::export]]
int timesTwo(int x) {
   return x * 2;
}
```

How could I get the help page show `timesTwo(x = 0)` in the usage section with roxygen2 comments?

**Comment by Enchufa2** [comment]
We can't help with that. This is a question for `roxygen2`, which is the package that handles such doc comments.

**Comment by eddelbuettel** [comment]
Agreed, and suggest we close this here.  Rcpp plays the hand it was dealt.  I sometimes write

```
//' @param x A single integer with default value of zero.
```

but that is of course manual.
