### ISSUE TITLE
Figure 3 incorrect caption in Rcpp-introduction vignette

### ISSUE THREAD

**Issue by remlapmot** [RcppCore/Rcpp#1276]
In the Rcpp-introduction vignette the caption of Figure 3 looks to be an unedited copy-paste of the Figure 1 caption.

<img width="402" alt="Screenshot 2023-09-29 at 18 13 06" src="https://github.com/RcppCore/Rcpp/assets/3777473/07b58cc2-b02b-436a-8991-b672e2b28e06">

Whereas the figure is about the results of running `Rcpp::Rcpp.package.skeleton("samplePkg")`.

I think the line to edit is:

https://github.com/RcppCore/Rcpp/blob/62bb38178399b061d34b8f838d45a4730cb03fbb/vignettes/rmd/Rcpp-introduction.Rmd#L876

**Comment by eddelbuettel** [comment]
Nice catch, thank you! 

That vignette undoubtedly had a number of eyes on it.  I will make the fix in the few days.

**Comment by remlapmot** [comment]
Thanks indeed.
