### ISSUE TITLE
Bug in assigning SEXP to List

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/Rcpp#128]
Related to [this SO post](http://stackoverflow.com/questions/22288025/rcpp-dynamically-update-a-list):

```cpp
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
List test_list(SEXP x){
    List L;
    L = x;
    return L;
}

/*** R
test_list( list(1, 2, 3) )
*/
```

just gives

```
> test_list( list(1, 2, 3) )
list()
```

This is because of the odd comma-initialization `operator=`, in `Vector.h`:

```cpp
internal::ListInitialization<iterator,init_type> operator=( init_type x){
    iterator start = begin() ; *start = x; 
    return internal::ListInitialization<iterator,init_type>( start + 1 ) ; ;
}
```

This hijacks the normal `operator=` and breaks things here.

**Comment by coatless** [comment]
The issue was addressed in git commit fd1f828 and has survived in [/inst/include/Rcpp/vector/Vector.h](https://github.com/RcppCore/Rcpp/blob/96f36a1706ebba3289b247690052f7b215b0dfb3/inst/include/Rcpp/vector/Vector.h#L257-L262)

Confirmation:
```r
> test_list( list(1, 2, 3) )
[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3
```

Please close. (Tagging #506)
