### ISSUE TITLE
pass by const refererence

### ISSUE THREAD

**Issue by waynelapierre** [RcppCore/Rcpp#1286]
I thought pass by const reference is not necessary when using NumericVector, but the function convolve_cpp on page 3 of this vignette uses it. Is there any specific reason to use it in the case?
https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-introduction.pdf

**Comment by eddelbuettel** [comment]
"It's complicated."    You can do 

```r
> cppFunction("void twice(NumericVector x) { x = x + x; }")
> x <- c(2,4,8); twice(x); x
[1]  4  8 16
> 
```

which clearly changes `x`.  The compiler slaps your fingers when you try to do this as `cppFunction("void twice(const NumericVector x) { x = x + x; }")` as it notices the assignment to the `const` declared `x`.   But this only goes so far and if we want to trick it we can for example do

```r
> cppFunction("void twice(const NumericVector x) { NumericVector y{x}; y = y + y; }")
> x <- c(2,4,8); twice(x); x
[1]  4  8 16
> 
```

where `y` as a _shallow_ copy is actually a pointer reference and changes `x`.    

So I think of the `const` as mostly for declaring intent and that is clearly the spirit of the intro example on page three.
