### ISSUE TITLE
A fresh -Wformat-security issue under r-devel

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#1287]
**Update 2023-11-28:**  If you came here because of a similar message in your package please read on and see particularly [this comment below](https://github.com/RcppCore/Rcpp/issues/1287#issuecomment-1829886024) for the fairly simple fix.

---

While working on an update for `RQuantLib` with a few r-devel discovered minor changes, CRAN and I both came across a new nag this time from `-Wformat-security.`.  Our glue code in `src/attributes.cpp` does

```c++
                     << "    if (rcpp_isError_gen) {" << std::endl
                     << "        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);" << std::endl
                     << "        UNPROTECT(1);" << std::endl
                     << "        Rf_error(CHAR(rcpp_msgSEXP_gen));" << std::endl
                     << "    }" << std::endl
```

and the `Rf_error(someCharvariablehere)` now makes the compiler bark under `-Wformat-security`:

    RcppExports.cpp:180:18: warning: format string is not a string literal (potentially insecure) [-Wformat-security]

The fix is pretty easy:  add a `"%s"`.  I will take care of that shortly.

**Comment by eddelbuettel** [comment]
Yes, I actually got _five_ such emails myself today for packages of mine using `Rcpp`.

The fix is simple thanks to PR #1288 we made two days ago.  Install Rcpp 1.0.11.5 from the Rcpp drat repo via, _e.g._,

     Rscript -e 'install.packages("Rcpp", repos=c("https://RcppCore.github.io/drat", getOption("repos")))'

and then re-run `compileAttributes()`.  That will fix the `RcppExports.cpp` file for you.

**Comment by TobiasFellinger** [comment]
Thanks for the quick fix and the comment on how to fix issues with packages linking to Rcpp.

**Comment by eddelbuettel** [comment]
My pleasure!  As you see in this ticket, I actually hit is myself updating a package a few days ago.  `r-devel` and a new `g++` are good at this. 

And  I am sure we will hear more about it here, at StackOverflow, or on lists such as `rcpp-devel` or `r-package-devel` so when you see it by all means feel free to share the word :grinning:

**Comment by DISOhda** [comment]
> You then need to upload your updated package to CRAN. It has no change in its run-time dependency on `Rcpp` so you do not need to change anything in `DESCRIPTION`. Just re-run `compileAttributes()`.

I tried to resubmit my fixed package without changing `DESCRIPTION`. But it was rejected because it is unchanged, i.e. I got warned that the date is quite old and that the version string is the same as the existing version's. So, I had to increase the it and change the date to get it approved.

But still, thank you very much for your quick response. It is very much appreciated.

**Comment by eddelbuettel** [comment]
> So, I had to increase it and change the date to get it approved.

That is expected.  

You actually changed code, so that requires a version that is strictly monotonically higher than the one it replaces.

**Comment by DISOhda** [comment]
> PS I see where I confused you writing "so you do not need to change anything in DESCRIPTION". Will edit.

Purely my mistake. I schould have known not to take that so literally. Anyway...

While I am at it: Which Rcpp version should be specified as the minimum requirement in `DESCRIPTION`?

**Comment by eddelbuettel** [comment]
> While I am at it: Which Rcpp version should be specified as the minimum requirement in DESCRIPTION?

That is what my comment is about: No change needed as that determines a _run-time_ for which you have no changed depedency.  Remember that these warnings come from a fixed, static, generated file `RcppExports.cpp` that does not change no matter what the user of your package has.  Makes sense?   Once Rcpp 1.0.12 is at CRAN come January you depend on that.  Depending on the development version you used will create trouble as that version is not yet at CRAN.

Makes sense?

**Comment by eddelbuettel** [comment]
Rcpp 1.0.12 arrived at CRAN on Jan 9 as planned so this can be closed.

![image](https://github.com/RcppCore/Rcpp/assets/673121/1c774325-f52b-4aeb-afbc-99e124b45747)
