### ISSUE TITLE
'CRAN package Rcpp' notice

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#1290]
CRAN / @kurthornik  emails:

> Dear maintainer,
> 
> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_Rcpp.html>.
> 
> Please correct before 2024-01-10 to safely retain your package on CRAN.
> 
> Note that this will be the *final* reminder.
> 
> Best,
> -k

which is of course redundant as we had been in contact ever since the `-Wformat -Wformat-security` wave broke.  

'They know' we have a fixed 1.0.11.3 here, in the drat and at R-universe.   Which, given no other currently known needs for change,  I plan to relabel as 1.0.12 and ship once our regular bi-annual window opens in January.  So January 8 or 9 it is [per their winter break notice](https://mastodon.social/@eddelbuettel/111534581290998516).  (If memory serves, 'incoming' re-opened on the final day of the notice in the past.)

**Comment by kurthornik** [comment]
>>>>> Dirk Eddelbuettel writes:

Thanks: yes I know, I had forgotten to tag my issue db accordingly.

Best
-k

**Comment by eddelbuettel** [comment]
@kurthornik  No worries, it looked very much like the automated script and it was in fact timely -- I had promised 'early Jan' and it is now officially on the map.

**Comment by hadley** [comment]
FYI I'm seeing this in problem causing a check failure in odbc: https://www.stats.ox.ac.uk/pub/bdr/clang18/odbc.log so I'd appreciate it if you have time to get a fix to CRAN in the not too distant future.

**Comment by eddelbuettel** [comment]
Sure.  First off the release happened yesterday and second as you can see in the extended comments in #1287 (which i am  sure you consulted) a number of packages made use of the provided pre-releases that have been available since November.

**Comment by eddelbuettel** [comment]
Rcpp 1.0.12 arrived at CRAN on Jan 9 as planned so this can be closed.

![image](https://github.com/RcppCore/Rcpp/assets/673121/b854cd7c-0673-4f85-bc40-86cc75ae46ac)
