### ISSUE TITLE
test_packageversion fails with Rcpp 1.0.12

### ISSUE THREAD

**Issue by pekkarr** [RcppCore/Rcpp#1294]
With the `Rcpp_1.0.12.tar.gz` source archive downloaded from CRAN, the `test_packageversion.R` unit test fails because of a version mismatch.

```
----- FAILED[data]: test_packageversion.R<37--37>
 call| expect_equal(res$cur_ver, res$def_ver, info = "current computed version equal defined version")
 diff| Expected '65547', got '65548'
 info| current computed version equal defined version
Error: 1 out of 1534 tests failed
```

In the CRAN source archive, `inst/include/Rcpp/config.h` contains the wrong version number in `RCPP_VERSION`:

```c
#define RCPP_VERSION            Rcpp_Version(1,0,11)
#define RCPP_VERSION_STRING     "1.0.12"
```

This git repository has the correct definition, having `Rcpp_Version(1,0,12)` instead, so the problem only appears when installing from CRAN instead of GitHub.

**Comment by eddelbuettel** [comment]
Yes I know and it's already fixed in the repo:

https://github.com/RcppCore/Rcpp/blob/08093bc5185a093158f0d88f7597c8f42681b53e/inst/include/Rcpp/config.h#L28-L34

When you run `R CMD check` to run the tests, or run them any other way via `tests/tinytest.R` then a reduced test suite is run and this won't affect anything.  Otherwise refresh from GitHub, please.

**Comment by pekkarr** [comment]
Thanks for the quick response, I [patched](../../../BioArchLinux/Packages/blob/d082c5455746c82861c18f3bc7f6e942b3940da7/BioArchLinux/r-rcpp/fix-version.patch) the BioArchLinux package to have the correct version.

> When you run `R CMD check` to run the tests, or run them any other way via `tests/tinytest.R` then a reduced test suite is run and this won't affect anything.

The [BioArchLinux build script](../../../BioArchLinux/Packages/blob/d082c5455746c82861c18f3bc7f6e942b3940da7/BioArchLinux/r-rcpp/PKGBUILD#L46) runs the tests with `RunAllRcppTests=yes` which is why this unit test is run in our builds.

**Comment by eddelbuettel** [comment]
Yes a local patch is the right step as the package is fine at CRAN and in other places running tests normal.  Kudos for being diligent enough to run extended checks!  This was just an editing oversight of mine.
