### ISSUE TITLE
Cannot make std::vector<int8_t> from NumericVector

### ISSUE THREAD

**Issue by oleksii-nikolaienko** [RcppCore/Rcpp#1297]
Hi,
first of all - I searched for something relevant and couldn't find it. But forgive me if I missed it.

The following example works for all `int32_t`, `uint_32t`, `int16_t`, `uint_16t`, and `uint8_t` - but not for `int_8t`. Is this a bug or by design?

```
dt <- data.table::data.table("x"=list(4:6))
Rcpp::cppFunction('int test(Rcpp::DataFrame &a) {
  std::vector<int8_t> vec = Rcpp::as<std::vector<int8_t>>(((Rcpp::List)(a["x"]))[0]);
  return vec.size();
}')
test(dt)
```

Both GCC and clang report `error: cannot initialize a member subobject of type 'signed char' with an lvalue of type 'SEXP' (aka 'SEXPREC *')`

Thanks.

**Comment by eddelbuettel** [comment]
It's been a while but I have a faint recollection that this may be due `char` and `int8_t` clashing 'as they are both the same' and we weren't explicit about about preferring `int8_t` (which of course does not exist in R).  And I guess we need to do what we do for `char` to that character variables work.  

You can always write yourself a custom converter helper for this where the autoMAGIC dispatch fromt the compiler does not work.   What you get from R will always be a `int32_t` so for example in one package where Rcpp is used this happens (and `vec` is the incoming variable from R

```c++
  } else if (dtype == "INT8") {
    IntegerVector v(vec);
    auto n = v.length();
    std::vector<int8_t> x(n);
    for (auto i=0; i<n; i++) {
      x[i] = static_cast<int8_t>(v[i]);
    }
```

I don't think there is much else you can do.  If it bugs you greatly that the compiler complains, see if you can improve it without side effects to `char` and others.  We would be interested ... but as `int8_t` is somewhat rare in R application this was never a priority.

(Going via interfaces that do know `int8_t` such as `arrow` might be an alternative too.)

**Comment by oleksii-nikolaienko** [comment]
Thanks for the explanation. I don't think I can improve `as`, that's beyond my expertise. So, I guess, I'll resort to `static_cast` as in your example.

FYI, I need this to [write array tags](https://github.com/samtools/htslib/blob/develop/htslib/sam.h#L2251) to BAM files given the data from R, and these arrays can be of different type

**Comment by eddelbuettel** [comment]
Yep, I know.  My day job is at [TileDB](https://www.tiledb.com) and the lines I quoted were from our R package which may of course encounter different `int` sizes and signedness.  Ditto with the single cell projects etc.

I think a one-off helper is fair workaround.  Especially as template metaprogramming is hairy.

Ok to close this?

**Comment by oleksii-nikolaienko** [comment]
Yes, thanks again
