### ISSUE TITLE
New warnings from -Wconversion -Wno-sign-conversion

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#1299]
Prof Ripley emailed the following in a messaging concerning the earlier R_NO_MAP issue (that is apparently defered for a bit at CRAN, we did our bit here, he pointed me also to another issue in another package of mine now taken care of):

> A couple of other warnings I noted whilst compiler logs for CRAN 
> packages scrolled by:
> 
> ```
> /Users/ripley/R/Library/Rcpp/include/Rcpp/sugar/functions/sample.h:369:17: 
> warning: implicit conversion loses integer precision: 'R_xlen_t' (aka 
> 'long') to 'int' [-Wshorten-64-to-32]
> 
> /Users/ripley/R/Library/Rcpp/include/Rcpp/internal/export.h:114:9: 
> warning: implicit conversion loses integer precision: 'R_xlen_t' (aka 
> 'long') to 'uword' (aka 'unsigned int') [-Wshorten-64-to-32]
> 
> (That's from clang with -Wconversion -Wno-sign-conversion.)
> ```

**Comment by eddelbuettel** [comment]
I am actually not sure I can reproduce these with `clang++-17`, at least not from building Rcpp.  `uword` hints at RcppArmadillo but it could also be any one of 1100+ packages using it.   Uggh.

**Comment by Enchufa2** [comment]
I assume you asked Prof. Ripley for more details. :) In the meantime, I found [this](https://www.stats.ox.ac.uk/pub/bdr/M1mac/GPvecchia.log) for the second one via Google search, nothing for the first one.

**Comment by eddelbuettel** [comment]
I looked into this some more. One can tickle a fair amount by for example testing our embedded package  `testRcppClass` via the test file `test_module_client_package.R`.  And while I can subsitute a number of `int` for `size_t` invariably I end at an impassed that I convert enough to silence all warnings, the module no longer loads.  Uggh.  One can backtrack and only convert 'some' and the module remains loadable, but so does a faily warning.  The main culprit (for this issue) appears to be [this function](https://github.com/RcppCore/Rcpp/blob/30f1a0a336a12b068ea6f994f076941c069035d0/inst/include/Rcpp/module/class.h#L320-L342).  I changed some more trivial things (adding `void` to signatures in `init.c` for the test package, a number of other `int` -> `size_t` in `class.h`) but this one stings.

So we `-Wconversion -Wno-sign-conversion` under clang are enforced we may have some trouble.

**Comment by Enchufa2** [comment]
> I looked into this some more. One can tickle a fair amount by for example testing our embedded package `testRcppClass` via the test file `test_module_client_package.R`. And while I can subsitute a number of `int` for `size_t` invariably I end at an impassed that I convert enough to silence all warnings, the module no longer loads.

Do you have a branch with this to apply another pair of eyes?

**Comment by eddelbuettel** [comment]
Hah!  Following #1303 this is now different and (for the one test I looked at) much quieter.  Will keep looking.

**Comment by eddelbuettel** [comment]
New branch [bugfix/size_t_casts](https://github.com/RcppCore/Rcpp/tree/bugfix/size_t_casts) pushed. 

It behaves here.  I think the key difference to what gave me minor trouble yesterday is the one-line change in Module.h.

**Comment by Enchufa2** [comment]
(Note to self) Packages to check for more casts: `support`, `lavacreg`, `hdtg`, `mapdeck`, `morf`

Found using this search:

```
site:www.stats.ox.ac.uk /Users/ripley/R/Library/Rcpp/include/Rcpp warning: implicit conversion loses integer precision: 'R_xlen_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
```

**Comment by JanMarvin** [comment]
Hi, not sure if further input is still needed, but I saw the following warning when compiling with clang 17.0.6 and `-Wconversion -Wno-sign-conversion`
```
/home/jmg/R/x86_64-pc-linux-gnu-library/4.4/Rcpp/include/Rcpp/internal/Proxy_Iterator.h:110:23: warning: implicit conversion loses integer precision: 'R_xlen_t' (aka 'long') to 'difference_type' (aka 'int') [-Wshorten-64-to-32]
  110 |                         return proxy.index - other.proxy.index ;
      |                         ~~~~~~ ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
```
This I was able to silence switching `int` to `R_xlen_t` here:
https://github.com/RcppCore/Rcpp/blob/b6941183db941c0d501b0af0502170b2b45b075b/inst/include/Rcpp/internal/Proxy_Iterator.h#L34

**Comment by eddelbuettel** [comment]
Hi @JanMarvin that is helpful as we likely do need additional rounds of fixes as different package will expose different parts of the "API surface".  Which package did you compile?

**Comment by JanMarvin** [comment]
Hi @eddelbuettel , I was compiling [`openxlsx2`](https://github.com/JanMarvin/openxlsx2). The warning is triggered by a custom `wrap()` function in a `_types.h` file with `#include <RcppCommon.h>`

**Comment by eddelbuettel** [comment]
Confirming. An alternative (more local?) fix would be 

```diff
@@ -107,7 +105,7 @@ public:
 		}
 
 		inline difference_type operator-(const Proxy_Iterator& other) const {
-			return proxy.index - other.proxy.index ;
+			return static_cast<difference_type>(proxy.index - other.proxy.index) ;
 		}
 
 		inline int index() const { return proxy.index ; }
```

which is more local but your suggestion is likely better.

**Comment by eddelbuettel** [comment]
@Enchufa2 You search string is good! I see

- [x] support: no longer on CRAN
- [x] VBel:  lots of warnings from RcppEigen (another time ...), the one reported on Vector does not reproduce
- [ ] lavacreg: 
- [ ] hdtg: 
- [ ] mapdeck: 
- [ ] morf: 

I will try to get to these one by one. Help welcome :grinning: . I will also push a new branch with the change suggested by @Janmarvin and we can combine changes in there.

**Comment by eddelbuettel** [comment]
That worked out ok in the rev.dep check so I will make another PR.

**Comment by eddelbuettel** [comment]
Closing as #1309 covered this.
