### ISSUE TITLE
Attributes vignette and Imports/Depends distinction

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#130]
@jayemerson says in email (regarding Imports vs Depends)

      It may now be that CRAN recommends use of Import rather than Depends unless
      there is a clear case to be made for Depends. Ripley made me do some changes
     before accepting a recent package version update on exactly this point.  So "more 
     recent alternative" may soon become stronger at the end of 3.2.                  

so would should probably update the wording in Section 3.2 of the Attributes vignette.

**Comment by coatless** [comment]
This issue can be closed out

https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-attributes.pdf#page=11

Issue Resolved on: 
https://github.com/RcppCore/Rcpp/commit/e00131349cce71722f291f722048caea95b2fd5d#diff-02f0b547c2779d25cff89672135f20e3

**Comment by eddelbuettel** [comment]
You're on a roll.  We should probably just meet halfway between Chicago and Urbana, get a few beers and pizza and jointly review the rest :)

**Comment by dcdillon** [comment]
I'll go all the way to champaign if we can go to Murphys

**Comment by eddelbuettel** [comment]
I think we may have a late summer / fall weekend coming out of this :)

**Comment by coatless** [comment]
Murphys is great! [The Blind Pig](http://blindpigco.com/) is also acceptable. 

Though, we probably should go to [Triptych](http://triptychbrewing.com/) if it is late summer / the start of Fall.
