### ISSUE TITLE
compileAttributes and use of .External2() for calling native symbol routine

### ISSUE THREAD

**Issue by astamm** [RcppCore/Rcpp#1300]
I have defined a light version of `stats::uniroot()` function in a package of mine as follows:

```r
find_zero <- function(f, lower = 0, upper = 1, tol = 1e-8, maxiter = 1000L, ...) {
  C_zeroin2 <- utils::getFromNamespace("C_zeroin2", "stats")
  f.lower <- f(lower, ...)
  f.upper <- f(upper, ...)
  val <- .External2(C_zeroin2, \(arg) f(arg, ...),
                    lower, upper, f.lower, f.upper, tol, as.integer(maxiter))
  return(val[1])
}
```

upon a suggestion from Ben Bolker [here](https://stackoverflow.com/questions/69860570/is-there-any-faster-alternative-to-statsuniroot-function-in-r).

Now if I set up my package to work with *Rcpp*, it seems that `Rcpp::compileAttributes()` is bothered by that function since `C_zeroin2` is of class `NativeSymbolInfo`.

As such, it fails and returns:

> ==> Rcpp::compileAttributes()
>
> Error in match.call(definition, call, expand.dots, envir) : 
>   unused arguments (function(arg) f(arg, ...), lower, upper, f.lower, f.upper, tol, as.integer(maxiter))
> Calls: source ... native_routine_registration_db_from_ff_call_db -> lapply -> FUN -> match.call
> Execution halted
>
>
> Exited with status 1.

Shouldn't it look only inside the `src/` folder ?

**Comment by eddelbuettel** [comment]
Hm.  A guess from the hip here -- are you sure it's 
- not the `.External2` ?
- not also happening via the base R function [1] writing `src/init.c` as we IIRC call it to?

[1] ie `tools::package_native_routine_registration_skeleton()` ?

**Comment by astamm** [comment]
Thanks for the reply. And apologies for filing the issue here. It actually happens when `tools::package_native_routine_registration_skeleton()` is invoked. Not sure why yet. But seems unrelated to *Rcpp*.

**Comment by eddelbuettel** [comment]
No worries.  You interfaced our function, I just happened to suspect that the base function was at the heart of it.

I to have written simple wrapper around `uniroot()` and I got by without `.External2()`.  I am sure you find a way that is compliant with the R API.

**Comment by astamm** [comment]
Actually it seems that the problem is in `tools:::native_routine_registration_db_from_ff_call_db()` at the beginning when they define the vector`ff_call_names` to look for in the code.

It is currently:

```r
native_routine_registration_db_from_ff_call_db <- function (calls, dir = NULL, character_only = TRUE) 
{
  if (!length(calls)) 
    return(NULL)
  ff_call_names <- c(".C", ".Call", ".Fortran", ".External")
```

if I add `.External2` to the vector, it works fine.

**Comment by eddelbuettel** [comment]
Wrong repo.  We do not have control over the `tools` package.  :wink:

**Comment by Enchufa2** [comment]
@astamm FWIW, the manual page for `.External2` declares it as an _internal version of `.External`_, which suggests that you probably should be using `.External` instead. Of course this collides with the fact that they export it. So... who knows.
