### ISSUE TITLE
`HASHTAB` is no longer allowed

### ISSUE THREAD

**Issue by mattfidler** [RcppCore/Rcpp#1313]
Raising for awareness (I know you are already working through many of these issues).  Currently `HASHTAB` is located here:

https://github.com/RcppCore/Rcpp/blob/518961121d632fe42ad93421027e98459626d724/inst/include/Rcpp/Environment.h#L88

I suppose this can use evaluation to get around this in the mean time.

**Comment by kevinushey** [comment]
Are these so-called `UserDefinedDatabase` objects still in use anywhere? The only reference I see in the R sources are:

https://github.com/wch/r-source/blob/c4706b85233fbcdeefe96c05e52ad01481ef28ee/src/library/base/man/attach.Rd#L78-L80

and the RObjectTables package isn't on CRAN and hasn't been updated in over 10 years. Through that lens, I'm inclined to just remove support from Rcpp (which would allow us to drop our usage of HASHTAB here).
