### ISSUE TITLE
`rchk` falsely claims imbalanced protect as it does not understand `Rf_onintr` exits

### ISSUE THREAD

**Issue by dipterix** [RcppCore/Rcpp#1318]
* Rcpp version: 1.0.12
* R version: 4.4.1

I tried to search elsewhere but couldn't find similar issues. The `rchk` keeps reporting un/imbalanced protect.

I believe this could be just a false positive... since `Rf_onintr` and `Rf_error` will raise exceptions, and it will eventually jump out the function call. However, it seems the static code analysis couldn't recognize this. Would it be helpful if you could add `return R_NilValue;` after `Rf_onintr` and `Rf_error`?

```
Function _ravetools_Vector3__add_scalar
  [UP] unprotected variable rcpp_result_gen while calling allocating function Rf_onintr /__w/ravetools/ravetools/src/RcppExports.cpp:1878
  [PB] has negative depth /__w/ravetools/ravetools/src/RcppExports.cpp:1890
  [UP] attempt to unprotect more items (1) than protected (0), results will be incomplete /__w/ravetools/ravetools/src/RcppExports.cpp:1890
  [PB] has possible protection stack imbalance /__w/ravetools/ravetools/src/RcppExports.cpp:1891
```

RcppExports.cpp code:

```cpp
// Vector3__add_scalar
void Vector3__add_scalar(const SEXP& self, std::vector<double>& s);
static SEXP _ravetools_Vector3__add_scalar_try(SEXP selfSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< const SEXP& >::type self(selfSEXP);
    Rcpp::traits::input_parameter< std::vector<double>& >::type s(sSEXP);
    Vector3__add_scalar(self, s);
    return R_NilValue;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _ravetools_Vector3__add_scalar(SEXP selfSEXP, SEXP sSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_ravetools_Vector3__add_scalar_try(selfSEXP, sSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr(); // <---- append return R_NilValue; ?
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen)); // <---- append return R_NilValue; ?
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
```

Thanks for taking a look at this... If I made an error, please let me know : )

**Comment by eddelbuettel** [comment]
Please provide a [minimally complete verifiable example](https://stackoverflow.com/help/minimal-reproducible-example).  A partial quote of an `RcppExports.cpp` that we do not have does not do.  `RcppEigen` is over a decade old and widely used, as is the `Rcpp` machinery supporting this.  There could *always* be a bug but your have to give us more to work with.

(Also `Rcpp` has 2800+ packages using it at CRAN isomh `rchk`, `RcppArmadillo` has 1100+ and so on. )

**Comment by dipterix** [comment]
Sure. Is there anything else I should provide?

* `rchk`: https://github.com/dipterix/ravetools/actions/runs/9939817489/job/27455173218
* `RcppExports.cpp`: https://github.com/dipterix/ravetools/blob/master/src/RcppExports.cpp

**Comment by eddelbuettel** [comment]
A pointer to your packages actions run is *not* a MCVE.  Come on now.  We have our own work to do, you cannot expect us to do debug your package for you,

Maybe it is a bug in `rchk`?  Again, I am willing to engage if you can provide a _minimally complete verifiable example_.  Pointing at a package with a dozen dependencies is not exactly minimal.

**Comment by dipterix** [comment]
I mean `rchk` does not know `Rf_onintr` will jump out of the function, hence it counts more `UNPROTECT()` than `PROTECT()`:

I tracked down to your source code:

https://github.com/RcppCore/Rcpp/blob/9c5f71c0e6432966667708306352e3a112ad31dc/src/attributes.cpp#L2950-L2953

Is it OK to add one line after `Rf_onintr`, just like what you did for [`testSendInterrupt`](https://github.com/RcppCore/Rcpp/blob/9c5f71c0e6432966667708306352e3a112ad31dc/inst/tinytest/cpp/stack.cpp#L50-L53)?

Here's proposed change

```cpp
<< "    if (rcpp_isInterrupt_gen) {" << std::endl
<< "        UNPROTECT(1);" << std::endl
<< "        Rf_onintr();" << std::endl
<< "        return R_NilValue;" << std::endl   // insert a new line here
<< "    }" << std::endl
```


Similarly: https://github.com/RcppCore/Rcpp/blob/9c5f71c0e6432966667708306352e3a112ad31dc/src/attributes.cpp#L2961C17-L2965C45

Proposed change:

```cpp
<< "    if (rcpp_isError_gen) {" << std::endl
<< "        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);" << std::endl
<< "        UNPROTECT(1);" << std::endl
<< "        Rf_error(\"%s\", CHAR(rcpp_msgSEXP_gen));" << std::endl
<< "        return R_NilValue;" << std::endl   // insert a new line here
<< "    }" << std::endl
```

**Comment by eddelbuettel** [comment]
From the looks of this may be an issue  `rchkr` which does not understand that `Rf_onintr()` may exit?

**Comment by eddelbuettel** [comment]
I think I am going to close this overly dramatic (and falsely titled) issue, and may open a new wishlist one to place a placebo `return R_NilValue();` after the `Rf_onintr` call.   If you would like to to see this issue progress, it would help a lot if you could create such a modification to `src/attributes.cpp` (also to provide a proper diff or pull request) and _test it_ with a few packages, or ideally all reverse dependencies to ensure the change is free of side effects.

**Comment by dipterix** [comment]
Thanks, I will ask rchk folks

**Comment by eddelbuettel** [comment]
And I think it may help you used one of the package creation helpers and created a package with _one_ function wrapped by RcppExports showing the Rf_onintr.  No dependencies besides Rcpp.  Just a simple `add_two_values()` values function.
Everything else is a distraction.

**Comment by dipterix** [comment]
Will do. Thanks for the advice. I do want to minimize your efforts by checking into the source code for possibly cause of the issue. Not an excuse but I think sometimes people like me (just barely know how to use Rcpp) are just too at a loss to know even where to start. Feel the same when my users reach out to me for help with a piece of screenshot...

**Comment by eddelbuettel** [comment]
Sure. 

And just for context, it is harder for someone like to me to 'dive into' your issue when

- the package is large
- unnecessary dependencies obfuscate (the issue here has nothing to with any non-Rcpp package your package uses)
-  you do not show how you created RcppExports.cpp (it could have been different)

and so on.  Remember that you want to make it _easy_ for us to help you.

**Comment by dipterix** [comment]
> * you do not show how you created RcppExports.cpp (it could have been different)

Ah I didn't know that... I thought just flagging `// [[Rcpp::export]]` or `// [[Rcpp:interfaces(...)]]` suffice according to the tutorial...

**Comment by dipterix** [comment]
Please allow me to bug you again @eddelbuettel . I've posted this issue https://github.com/kalibera/rchk/issues/34?notification_referrer_id=NT_kwDOAHyQ-LMxMTUzNjMzODMyNDo4MTYzNTc2#issuecomment-2256884785

The author of `rchk` says:

> But in principle, R on long jumps automatically unprotects (restores the pointer protection stack depth). One should not be unprotecting before calling Rf_error() - it is R that will do this work. The PROTECT/UNPROTECT calls should be placed as if functions called were returning normally and it is the responsibility of the user code to ensure protection balance on (only) local returns. 

Now I feel like I don't understand when to `UNPROTECT` anymore... So basically he said there shouldn't exist `UNPROTECT` before `Rf_error`?

**Comment by eddelbuettel** [comment]
Have you considered adding an "empty" (ie never reached) UNPROTECT just past it?

I otherwise have nothing much to add. I do not have the time, sadly, to dive into debugging your (large-ish) package for you, we no reproducible small example, and nobody else has come forward with anything similar.  So the ball may be in your court here.
