### ISSUE TITLE
Can't download Rcpp/lme4 package | R default language not changing

### ISSUE THREAD

**Issue by naj-r** [RcppCore/Rcpp#1319]
I want to run a linear mixed effects regression model using lmer(). This requires the package lme4. The package lme4 depends on Matrix and Rcpp. I reinstalled Matrix. I was able to then use the package. However, when I came to download lme4 I kept getting errors. I tried it in two ways and here are the following errors:
Firstly:
```
Sys.setlocale("LC_ALL", "en_GB.UTF-8")
Sys.getlocale()
```
(apologies that it is in German. I changed the system language to English but it keeps showing up as german - not sure why)

**_Downloading lme4_**
Method 1:
```
install.packages("lme4")

>Warning in install.packages :
  kann nicht auf den Index für das Repository https://cran.rstudio.com/src/contrib zugreifen:
  kann URL 'https://cran.rstudio.com/src/contrib/PACKAGES' nicht öffnen
Warning in install.packages :
  kann nicht auf den Index für das Repository https://cran.rstudio.com/src/contrib zugreifen:
  kann URL 'https://cran.rstudio.com/src/contrib/PACKAGES' nicht öffnen
Warning in install.packages :
  Paket ‘lme4’ ist nicht verfügbar for this version of R

Eine Version dieses Paketes für ihre R Version ist evtl woanders verfügbar,
siehe unter
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
Warning in install.packages :
  kann nicht auf den Index für das Repository https://cran.rstudio.com/bin/windows/contrib/4.4 zugreifen:
  kann URL 'https://cran.rstudio.com/bin/windows/contrib/4.4/PACKAGES' nicht öffnen
```

Method 2:
```
install.packages("C:/path_to_file/lme4_1.1-35.5.tar.gz", repos = NULL, type = "source")

> ERROR: dependency 'Rcpp' is not available for package 'lme4'
* removing 'C:/path_to_file/AppData/Local/Programs/R/R-4.4.1/library/lme4'
Warning in install.packages :
  Installation des Pakets ‘C:/path_to_file/lme4_1.1-35.5.tar.gz’ hatte Exit-Status ungleich 0
```

I see that the package Rcpp is required due to the dependency. So I downloaded it again in the two ways I tried above:

```
install.packages("Rcpp")

>  Warning in install.packages :
  kann nicht auf den Index für das Repository https://cran.rstudio.com/src/contrib zugreifen:
  kann URL 'https://cran.rstudio.com/src/contrib/PACKAGES' nicht öffnen
Warning in install.packages :
  kann nicht auf den Index für das Repository https://cran.rstudio.com/src/contrib zugreifen:
  kann URL 'https://cran.rstudio.com/src/contrib/PACKAGES' nicht öffnen
Warning in install.packages :
  Paket ‘Rcpp’ ist nicht verfügbar for this version of R

Eine Version dieses Paketes für ihre R Version ist evtl woanders verfügbar,
siehe unter
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
Warning in install.packages :
  kann nicht auf den Index für das Repository https://cran.rstudio.com/bin/windows/contrib/4.4 zugreifen:
  kann URL 'https://cran.rstudio.com/bin/windows/contrib/4.4/PACKAGES' nicht öffnen
```
and
```
install.packages("C:/path_to_file/Downloads/Rcpp_1.0.13.tar.gz", repos = NULL, type = "source")

>* installing *source* package 'Rcpp' ...
** Paket 'Rcpp' erfolgreich entpackt und MD5 Summen überprüft
** using staged installation
** libs
g++ -std=gnu++17  -I"C:/path_to_file/AppData/Local/Programs/R/R-44~1.1/include" -DNDEBUG -I../inst/include/    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c api.cpp -o api.o
/bin/sh: line 1: g++: command not found
make: *** [C:/path_to_file/AppData/Local/Programs/R/R-44~1.1/etc/x64/Makeconf:296: api.o] Error 127
ERROR: compilation failed for package 'Rcpp'
* removing 'C:/path_to_file/AppData/Local/Programs/R/R-4.4.1/library/Rcpp'
Warning in install.packages :
  Installation des Pakets ‘C:/path_to_file/Downloads/Rcpp_1.0.13.tar.gz’ hatte Exit-Status ungleich 0
```

I have spent hours trying to fix this to run a simple linear mixed effects regression but keep getting these package issues. I have the R version 4.4.1 and even tried this on 4.4.0 but get even worse errors.
I would appreciate it if someone could help me.

**Comment by eddelbuettel** [comment]
This has nothing to do with Rcpp in particular, you appear to be struggling with more basic steps in R package installation. Maybe you need some handholding from you IT team to help you access the CRAN mirror your machine currently refuses to access. As that is a [CDN](https://en.wikipedia.org/wiki/Content_delivery_network) (as opposed to a single server) it should always be available so we can't you here.

To install from source, you need additional tools namely the so-called set of `Rtools` containing a compiler for Windows.  (While the just made release 1.0.13 may be rebuilt for Windows, you can try the previous one or access a binary from another source, for example [the r-universe build](https://rcppcore.r-universe.dev/Rcpp).

**Comment by eddelbuettel** [comment]
Also, even when CRAN may be building 1.0.13 for Windows (per [the Rcpp page at CRAN it is](https://cran.r-project.org/web/packages/Rcpp/index.html)) you should still always get the previous version.

**Comment by naj-r** [comment]
Thanks!
