### ISSUE TITLE
Error while installing package after update to Rcpp 1.0.13

### ISSUE THREAD

**Issue by sjmgarnier** [RcppCore/Rcpp#1322]
Since updating to Rcpp 1.0.13, installing a package that I'm developing (https://github.com/swarm-lab/Rvision) returns the following error on Mac OS and Windows 10 (not tested on other platforms yet): 

```
** testing if installed package can be loaded
Error: package or namespace load failed for ‘Rvision’ in .doLoadActions(where, attach):
 error in load action .__A__.12 for package Rvision: Rcpp::loadModule(module = "methods_Display", what = TRUE, env = ns, : Unable to load module "methods_Display": invalid type/length (symbol/0) in vector allocation
Error: loading failed
Execution halted
ERROR: loading failed
```

The error disappears if I revert to 1.0.12. 

Procedure to reproduce the error with 1.0.13:

```r
install.packages("ROpenCVLite")
ROpenCVLite::installOpenCV()
remotes::install_github("swarm-lab/Rvision")
```

**Comment by sjmgarnier** [comment]
Ok, thanks. I will see what I can do on my end. The offending module wraps OpenCV functions, so I don't know if I can build a minimal example without depending on it.

**Comment by eddelbuettel** [comment]
Your file visionModule.cpp is almost 500 lines long :open_mouth: so you may be the biggest Modules power user out there (also a guess).  

The error, as I see it, comes from Modules instantiation.  I don't think it is linking which is what I was hoping we could 'mock it'.  By comparison, my (much smaller) packages (such as eg RcppAnnoy) have no issues (see below) but they are also way less fancy. 

```sh
edd@rob:~/git/rcppannoy(master)$ ./cleanup 
edd@rob:~/git/rcppannoy(master)$ install.r
* installing *source* package found in current working directory ...
* installing *source* package ‘RcppAnnoy’ ...
** using staged installation
** libs
using C compiler: ‘gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0’
using C++ compiler: ‘g++ (Ubuntu 13.2.0-23ubuntu4) 13.2.0’
using C++17
ccache g++  -std=gnu++17 -I"/usr/share/R/include" -DNDEBUG -I../inst/include/  -I'/usr/local/lib/R/site-library/Rcpp/include'     -fpic  -g -O0 -Wall -pipe -pedantic -fdiagnostics-color=always -Wformat    -c RcppExports.cpp -o RcppExports.o
ccache g++  -std=gnu++17 -I"/usr/share/R/include" -DNDEBUG -I../inst/include/  -I'/usr/local/lib/R/site-library/Rcpp/include'     -fpic  -g -O0 -Wall -pipe -pedantic -fdiagnostics-color=always -Wformat    -c annoy.cpp -o annoy.o
ccache g++  -std=gnu++17 -I"/usr/share/R/include" -DNDEBUG -I../inst/include/  -I'/usr/local/lib/R/site-library/Rcpp/include'     -fpic  -g -O0 -Wall -pipe -pedantic -fdiagnostics-color=always -Wformat    -c arch.cpp -o arch.o
ccache gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include/  -I'/usr/local/lib/R/site-library/Rcpp/include'     -fpic  -g -O0 -Wall -pipe -std=gnu17 -pedantic -fdiagnostics-color=always -Wformat   -c init.c -o init.o
ccache g++  -std=gnu++17 -I"/usr/share/R/include" -DNDEBUG -I../inst/include/  -I'/usr/local/lib/R/site-library/Rcpp/include'     -fpic  -g -O0 -Wall -pipe -pedantic -fdiagnostics-color=always -Wformat    -c version.cpp -o version.o
ccache g++ -std=gnu++17 -Wl,-S -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -Wl,-z,relro -o RcppAnnoy.so RcppExports.o annoy.o arch.o init.o version.o -L/usr/lib/R/lib -lR
installing to /usr/local/lib/R/site-library/00LOCK-rcppannoy/00new/RcppAnnoy/libs
** R
** demo
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (RcppAnnoy)
edd@rob:~/git/rcppannoy(master)$ 
```

**Comment by sjmgarnier** [comment]
This was pretty much my first Rcpp-based package. I think some decisions I made back then are now biting me back. But I'm also too busy/lazy to restart from scratch. In any case, I'm working through each function in this module to see which one is causing the problem. Hopefully, there is an easy fix or workaround.

**Comment by eddelbuettel** [comment]
I hear you on both counts.  Modules is awesome, but also ultimately limited/limiting.  The automation is surely nice but one can get also pretty far (and generally further) via external pointer managed objects.  There once was RcppR6 trying something similar with R6 objects but it was never finalised to CRAN and ultimately withered.

**Comment by eddelbuettel** [comment]
That may even be the compiler / R flags for it.  We had a phase where CRAN outlawed functions without proper prototypes...

Do you know from the top of your head where we should highlight that in the docs?

**Comment by sjmgarnier** [comment]
I guess that would be in section 2.1.2 here: https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-modules.pdf.

**Comment by sjmgarnier** [comment]
I guess I technically didn't need to specify anything. This works for instance: 

```r
function("_nameOfFunction", &_nameOfFunction);
```

**Comment by eddelbuettel** [comment]
> I guess that would be in section 2.1.2 here

I could / likely should add a line at the end of the section there.

**Comment by eddelbuettel** [comment]
Done, see https://github.com/RcppCore/Rcpp/commit/0b592442ca0baa45373c4478e09f0d93743edc3a as referenced here.

**Comment by sjmgarnier** [comment]
Thanks!
