### ISSUE TITLE
Possible issue in `loadRcppClass()` and `loadModule()`

### ISSUE THREAD

**Issue by zhuxr11** [RcppCore/Rcpp#1323]
When trying to load a class exported with `RCPP_EXPOSED_CLASS` in a package with `loadRcppClass()`, I encountered the following errors:
* In `loadModule()` function, I spotted a possible error [here](https://github.com/RcppCore/Rcpp/blob/0b592442ca0baa45373c4478e09f0d93743edc3a/R/loadModule.R#L59): possibly this should be: `module <- get("moduleName", loadM)`, where `loadM` is an environment and `moduleName` is the name to look for.
* Also, when `module` is a `Module` object, `metaName` does not exist when running to [this line](https://github.com/RcppCore/Rcpp/blob/0b592442ca0baa45373c4478e09f0d93743edc3a/R/loadModule.R#L82). Possibly we should add `metaName <- moduleMetaName(loadM$moduleName)` after [this line](https://github.com/RcppCore/Rcpp/blob/0b592442ca0baa45373c4478e09f0d93743edc3a/R/loadModule.R#L58).
* Furthermore, when `what = NULL`, as called from `loadRcppClass()`, the returned module only has three bindings: `packageName`, `moduleName` and `pointer`. When running to [this line](https://github.com/RcppCore/Rcpp/blob/0b592442ca0baa45373c4478e09f0d93743edc3a/R/RcppClass.R#L55), `storage` cannot be found in environment `mod`, since it has no such binding. I have not yet figured out how to fix this.

Any method can I export `MyClass` defined in Rcpp to package's namespace as "MyClass" (possibly with `RCPP_EXPOSED_CLASS`), which can be directly used in R as MyClass$method()?

**Comment by eddelbuettel** [comment]
That may be a difficult question.  `RcppClass` is/was a bit of a side project mostly done by John.  There was one change in 2018 described as

https://github.com/RcppCore/Rcpp/blob/0b592442ca0baa45373c4478e09f0d93743edc3a/ChangeLog#L1877-L1884

This has not see much love or attention since.  One approach may be 'RcppModule only' to avoid interaction, otherwise "unsure": you may have to work that out.

**Comment by zhuxr11** [comment]
> That may be a difficult question. `RcppClass` is/was a bit of a side project mostly done by John. There was one change in 2018 described as
> 
> https://github.com/RcppCore/Rcpp/blob/0b592442ca0baa45373c4478e09f0d93743edc3a/ChangeLog#L1877-L1884
> 
> This has not see much love or attention since. One approach may be 'RcppModule only' to avoid interaction, otherwise "unsure": you may have to work that out.

Well, finally figured out a way: the **RCPP_EXPOSED_CLASS_NODECL** did the trick (instead of **RCPP_EXPOSED_CLASS**)

In `inst/include/MyClass.h`:

```
#ifndef MYHEADER
#define MYHEADER

#include <Rcpp.h>

namespace MyNs
{

using namespace Rcpp;

class MyClass
{
public:
    MyClass() {}
};

}

using namespace MyNs;

RCPP_EXPOSED_CLASS_NODECL(MyClass);

#endif // MYHEADER
```

Then, in `src/MyClass.cpp`:

```
#include "../inst/include/MyClass.h"
using namespace MyNs;

RcppModule(MyMod){
    Rcpp::class_<MyClass>("MyClass")
    .constructor<>()
    ;
}
```

Finally, `MyClass` was exported to use in R with `new_obj <- new(MyClass)`, and `MyClass` could also be available to other packages as `MyNs::MyClass` as well, given it is included in `inst/include/MyPackage.h`.

**Comment by eddelbuettel** [comment]
That is clearly underdocumented.  If you have a few moments, and would like to do this, we could add a small example around this (maybe calling a function too) in the [Rcpp Gallery](https://gallery.rcpp.org) site.
