### ISSUE TITLE
Did something change with void return of Modules functions?

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#1328]
Fresh CRAN email reports that my RcppCNPy package now differs between the `saveAndLoad.Rout` it creates and the `saveAndLoad.Rout.save` I have in the package, in particular calls to `npySave()` now return a `NULL` but did not before.  This is a standard Rcpp Modules binding of a `void` function (see [here](https://github.com/eddelbuettel/rcppcnpy/blob/602e8568884444f1052f17c6732b7fcef9f0a771/src/cnpyMod.cpp#L113-L187)).

Did we change anything in how this is generated within Rcpp?  I cannot think of anything. Am I missing something?

**Comment by Enchufa2** [comment]
I don't think we changed anything, and it works fine here with v4.4.1. All NOTEs you got are from r-devel machines, so I'd say something changed there. Of course void functions always return NULL at the R side, but something was `invisible()` and now it is not anymore in r-devel, apparently.

**Comment by Enchufa2** [comment]
Mmmh... wait a sec... I had a problem with the package versions and I can reproduce it now with r-release. This is strange. Maybe we did change something, but didn't appear until [this](https://github.com/wch/r-source/commit/3dbf2fc2a0ae75d9bde1c43b3c47716b89a03c57)?

**Comment by Enchufa2** [comment]
Ok. Meanwhile, bisecting...

**Comment by Enchufa2** [comment]
Ok, so 4075b5cb4673d7ad90fbcbea5cda4380f655f165 introduced the change.

**Comment by eddelbuettel** [comment]
That's what I suspected when I glanced at our changelog.  We may have dropped an invisible there somewhere.

**Comment by eddelbuettel** [comment]
@andrjohns Quick ping :)   Not the most burning of fires, but I have have to a minor maintenance release because `void` functions in Modules now return `NULL` whereas they used to be silent.  You wouldn't have a quick guess as to whether this slipped in when you overhauled this so nicely for variadic arguments?

**Comment by Enchufa2** [comment]
The logic that creates such a call is [here](https://github.com/RcppCore/Rcpp/blob/dfa585d2b568db5c8c0ff0e88e7f857758abccd4/R/Module.R#L82-L104), and depends on the detection of whether the `RESULT_TYPE` is void [here](https://github.com/RcppCore/Rcpp/blob/dfa585d2b568db5c8c0ff0e88e7f857758abccd4/inst/include/Rcpp/Module.h#L431). I checked and `is_void` is `FALSE` when RcppCNPy is built. This means that the `RESULT_TYPE` is incorrect with variadic arguments.

**Comment by Enchufa2** [comment]
Also, the generated file has a specific specialization for `void` that uses `void_type` [here](https://github.com/RcppCore/Rcpp/blob/4075b5cb4673d7ad90fbcbea5cda4380f655f165/inst/include/Rcpp/module/Module_generated_CppFunction.h#L47-L65).

**Comment by Enchufa2** [comment]
@andrjohns You may want to start your debugging from the [module-regression](https://github.com/RcppCore/Rcpp/tree/module-regression) branch, where I added a few tests that check that void module functions correctly return invisibly (3 are failing now, which are functions exposed via Modules).

**Comment by Enchufa2** [comment]
@andrjohns Just a kind reminder here. A rough estimate of your time availability for this would be appreciated, even if that's a null value, in order to plan our own efforts over here. Thanks! :)
