### ISSUE TITLE
Suspected malware

### ISSUE THREAD

**Issue by mattp0011** [RcppCore/Rcpp#1330]
Security tools have picked up the latest package for Rcpp version (1.0.13) as containing malware.
Unix/Multiverze is the detected item.
Repo can be found here - https://github.com/RcppCore/Rcpp
Package - Rcpp_1.0.13.tar.gz.

Can confirmation be provided if this is a real threat or if it's a false positive?

![image](https://github.com/user-attachments/assets/d991d84b-afc5-4618-8b17-ac578d5e92d7)

![image](https://github.com/user-attachments/assets/1acbb119-c5d7-4510-b65e-484a081d0a00)

**Comment by Enchufa2** [comment]
My guess is a false positive, because e.g.

- `vignettes/pdf/Rcpp-FAQ.pdf` is flagged: https://www.virustotal.com/gui/file/f836f126eabd262ab2fafb8dcbdcaf17809a85c47e309e5ac4bf1365e06384c8
- `vignettes/Rcpp-FAQ.pdf` is not flagged: https://www.virustotal.com/gui/file/eaee4c6ec01d9644908a2db5a2014db73745c27a4bfe59abad11ef69ff9f37c3

which is the same, but postprocessed via Sweave to add some headers. However, I'm no security expert.

**Comment by eddelbuettel** [comment]
We also heard about this from CRAN who had been contacted by users, but as @Enchufa2 describes, there is little for us to do here.  It is a standard Rmd file processed into a pdf by the standard tools.  

Maybe you can get in contact with the vendor?  You could also try the install of the current development version 1.0.13.1 from [r-universe](https://rcppcore.r-universe.dev/Rcpp) which has Windows binariess for R 4.3 (old-rel), 4.4 (rel) and 4.5 (devel).

**Comment by eddelbuettel** [comment]
The other "remedy" you can always attempt is to remove the pdf files from your installation.  You can still see them at the CRAN side.  We will however probably not want to remove them from the package as documentation has always been closely tied to packages at CRAN.

**Comment by mvankessel-EMC** [comment]
For my use case we send out analytical code to other organisations. One of these organisations flagged Rcpp as containing malware as mentioned in this issue. This prohibited them from running any analyses on their data, and quarantining laptops and workstations.

We lock down the dependencies that are used in the analytical code with `renv`. I ended up forking Rcpp, and removing the 'infected' PDF-files from the forked repo and pointed my renv.lock file at that version. This fork came out clean on their end, so they can now proceed as normal.

I'm intending to keep that fork in-sync, just without PDF-files

**Comment by Enchufa2** [comment]
For those use cases, you don't need the docs at all, so my recomendation is to install all packages (not only Rcpp, but doing this for every package will save quite a few bytes too) using R-CMD-INSTALL's `--no-docs` flag. If you are using `renv`, there's a way to set this, see [here](https://rstudio.github.io/renv/articles/package-install.html#install-flags).

**Comment by Enchufa2** [comment]
Good question. Probably they are still unpacked even if they are not installed in the final destination. :-\
