### ISSUE TITLE
fatal error: 'cmath' file not found

### ISSUE THREAD

**Issue by sarahsamorodnitsky** [RcppCore/Rcpp#1333]
Hi there,

I have a .cpp script I wrote several months ago that I haven't touched in a bit. I source that script using sourceCpp() in my R script. I am now getting the error: `fatal error: 'cmath' file not found` 

I am working from a Mac with OS Sonoma 14.6.1. I just updated R to version 4.4.1 and redownloaded Rcpp and RcppArmadillo. I have copied below a minimally-reproducible example that I found through Hadley Wickham's book:

```
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
NumericMatrix gibbs_cpp(int N, int thin) {
  NumericMatrix mat(N, 2);
  double x = 0, y = 0;

  for(int i = 0; i < N; i++) {
    for(int j = 0; j < thin; j++) {
      x = rgamma(1, 3, 1 / (y * y + 4))[0];
      y = rnorm(1, 1 / (x + 1), 1 / sqrt(2 * (x + 1)))[0];
    }
    mat(i, 0) = x;
    mat(i, 1) = y;
  }

  return(mat);
}
```

If I save the above code in a file called `text.cpp` and source it using `sourceCpp(test.cpp)` I get the following error:

```
> sourceCpp("test.cpp")
using C++ compiler: ‘Apple clang version 16.0.0 (clang-1600.0.26.3)’
using SDK: ‘MacOSX15.0.sdk’
clang++ -arch arm64 -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I"/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/Rcpp/include" -I"/Users/ssamorod/Downloads" -I/opt/R/arm64/include    -fPIC  -falign-functions=64 -Wall -g -O2   -c test.cpp -o test.o
In file included from test.cpp:1:
In file included from /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/Rcpp/include/Rcpp.h:27:
In file included from /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/Rcpp/include/RcppCommon.h:30:
In file included from /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/Rcpp/include/Rcpp/r/headers.h:66:
/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:10: fatal error: 'cmath' file not found
  100 | #include <cmath>
      |          ^~~~~~~
1 error generated.
make: *** [test.o] Error 1
Error in sourceCpp("test.cpp") : 
  Error 1 occurred building shared library.
```

I wasn't able to find this specific error looking through previous Github issues and the listserv, but from similar ones I gathered it has something to do with my local machine, maybe with Xcode? I do not feel qualified to diagnose this myself since I'm very new to using Rcpp and C++. Hoping to get a bit of help or insight. Thank you in advance.

Sarah

**Comment by eddelbuettel** [comment]
This is almost surely at your end, and we have for example this issue pinned for RcppArmadillo (where a Fortran compiler is needed too).   You may also try asking on r-sig-mac for macOS specific questions.

Our package is in good standing at CRAN and that includes tests on different macOS hardware choices and R versions.

**Comment by eddelbuettel** [comment]
Also see https://mac.r-project.org/ and its

> Tools
>
> In order to compile R and R packages you will need Xcode Developer Tools and a Fortran compiler. For details and download, please read the Tools page. The R 4.3.0 and higer binaries are built using Xcode 14.3 and universal GNU Fortran 12.2 from here.

**Comment by coatless** [comment]
@sarahsamorodnitsky try updating xcode cli.

![A screenshot showing the Settings panel on macOS and the update to Xcode CLI option.](https://github.com/user-attachments/assets/1cabea3f-9642-44a6-813e-efa5089d0d26)

**Comment by eddelbuettel** [comment]
Good call.  Maybe the Sonomoa upgrade requires that as follow-up.

**Comment by sarahsamorodnitsky** [comment]
Thank you both for the prompt responses. 

I don't see a software update for Xcode available. @coatless, I've taken a look at some of your resources ([this](https://mac.thecoatlessprofessor.com/macrtools/) and [this](https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/)). `macrtools::is_xcode_cli_installed()` and `macrtools::is_gfortran_installed()` both returned TRUE. `macrtools::is_xcode_app_installed()` returned FALSE, not sure if that is important. Still getting the same error. When I ran `gcc --version` I got th efollowing output:

```
Apple clang version 16.0.0 (clang-1600.0.26.3)
Target: arm64-apple-darwin23.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Not sure if that is relevant or helpful. Do you have any other suggestions? I really appreciate the help.

**Comment by coatless** [comment]
Okidokies, so Xcode should be  installed.

What happens when you type in terminal;

```sh
git --version
```


Is there anything in your ~/.Renviron or ~/.Rprofile? 

Open terminal and type:

```sh
cat ~/.Renviron 

cat ~/.Rprofile
```

Check if there is any clang modifications present.

**Comment by sarahsamorodnitsky** [comment]
No files were found when I ran the above code:

```
(base) ssamorod ~ % cat ~/.Renviron 
cat: /Users/ssamorod/.Renviron: No such file or directory
(base) ssamorod ~ % cat ~/.Rprofile
cat: /Users/ssamorod/.Rprofile: No such file or directory
```

Is that a problem?

**Comment by coatless** [comment]
Whoops, I needed one more: 

```sh
cat ~/.R/Makevars
```

^ What's in that file?

**Comment by sarahsamorodnitsky** [comment]
Also could not find that file:

```
(base) ssamorod ~ % cat ~/.R/Makevars
cat: /Users/ssamorod/.R/Makevars: No such file or directory
```

**Comment by coatless** [comment]
Mmm, that's interesting. Are you running anything to switch between R versions? Do you have `conda` on the path? This looks like there is a mixup between the internal mac headers and what R thinks is present.

**Comment by sarahsamorodnitsky** [comment]
I am not running anything to switch between R versions, other than redownloading some packages. 

Here is what I get when I check the PATH:

```
(base) ssamorod ~ % echo $PATH
/opt/anaconda3/bin:/opt/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Applications/quarto/bin
```

It does look like anaconda3 is present. (Thanks again BTW for helping me figure this out)

**Comment by eddelbuettel** [comment]
Ah..Most of us have better luck outside of Conda, and mixing can be tricky.  If you are knowledgeable around Conda it can surely work .... but naively mixing may be a best idea.

Rcpp essentially "just" needs R to know about and find its compiler.  The simplest litmus test is still

```r
Rcpp::evalCpp("2 + 2")
````

**Comment by sarahsamorodnitsky** [comment]
Ah, okay, I get the same error when I run `Rcpp::evalCpp("2 + 2")`. Should I remove conda from the path? How do I ensure R can find the Rcpp compiler?

**Comment by eddelbuettel** [comment]
I would try that -- see if just R + Xcode will work,

**Comment by sarahsamorodnitsky** [comment]
So I've tried deleting anaconda and have confirmed it is no longer in the path:

```
/Library/Frameworks/Python.framework/Versions/3.12/bin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Applications/quarto/bin
```

Still running into the same error. Tried restarting the computer and redownloading Rcpp.

**Comment by kevinushey** [comment]
I recall @jeroen bumped into something very similar that was resolved by reinstalling CLT:

```
The installer for the Command Line Tools for Xcode 16 does not delete a directory that was installed by some older versions of the CLTs, which unfortunately causes clang++ to look in the wrong place for C++ headers. The majority of ports that contain C++ code will fail to build as a result.

The fix is to delete the stray directory if it exists: sudo rm -rf /Library/Developer/CommandLineTools/usr/include/c++
```

If that doesn't help, can you share the output of:

```
xcrun --show-sdk-path
xcode-select -p
```

It could be worth trying to reinstall command line tools, e.g.

```
sudo rm -rf /Library/Developer/CommandLineTools
sudo xcode-select --install
```

You can also trace the include paths used by clang by adding the `-H` flag; one way to do this is:

```
dir.create("~/.R", showWarnings = FALSE)
cat("CPPFLAGS += -H", file = "~/.R/Makevars", sep = "\n", append = TRUE)
```

Then, try executing `Rcpp::sourceCpp("<file>", verbose = TRUE, rebuild = TRUE)`. You should get a mountain of output like:

```
clang++ -arch arm64 -std=gnu++17 -I"/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/include" -DNDEBUG   -I"/Users/kevin/Library/R/arm64/4.4/library/Rcpp/include" -I"/Users/kevin/scratch" -I/opt/R/arm64/include -DSTRICT_R_HEADERS=1 -H -H    -fPIC  -fpermissive  -c Untitled.cpp -o Untitled.o
. /Users/kevin/Library/R/arm64/4.4/library/Rcpp/include/Rcpp.h
.. /Users/kevin/Library/R/arm64/4.4/library/Rcpp/include/RcppCommon.h
... /Users/kevin/Library/R/arm64/4.4/library/Rcpp/include/Rcpp/r/headers.h
.... /Users/kevin/Library/R/arm64/4.4/library/Rcpp/include/Rcpp/platform/compiler.h
..... /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath
< ... >
```

Note that `cmath` is found in this directory for my case.

**Comment by eddelbuettel** [comment]
@sarahsamorodnitsky Any luck?

**Comment by sarahsamorodnitsky** [comment]
@kevinushey Your first suggestion seems to have solved the problem! Thank you all so much for your help!!

**Comment by eddelbuettel** [comment]
@sarahsamorodnitsky Sounds like we can close this then as the reinstallation provided you with a working setup?

**Comment by sjmgarnier** [comment]
I encountered a similar issue with RcppEigen (`fatal error: 'iterator' file not found`) which was resolved by reinstalling the command line tools as indicated in https://github.com/RcppCore/Rcpp/issues/1333#issuecomment-2375761873 above.

**Comment by eddelbuettel** [comment]
I don't actually think these are issues with either `Rcpp` or `RcppEigen` as all these packages "merely" rely R being able to call a compiler reliably.

Which in the year 2024 appears to still be a challenge on some OSs, alas.  I wish we had means to make this more reliable, I am not aware that we do.

**Comment by sjmgarnier** [comment]
@eddelbuettel They aren't Rcpp issues but I imagine that people will land here each time they have an issue installing/using Rcpp packages. I think the best you can do is document the problem and the solution/workaround. No one can change Apple's mind :-)

**Comment by eddelbuettel** [comment]
@sjmgarnier That is what I tried to say a minute ago:

> I wish we had means to make this more reliable on those OSs, I am not aware that we do.

If you have a PR to test things, please do not hold back and help us make Rcpp (and friends) better!  Where I live, things like `Rcpp::evalCpp("2 + 2")`.  Where you are, they may not on a naive setup.  But how do we _reliably_ get from naive to working?

**Comment by sjmgarnier** [comment]
@eddelbuettel If I can think of something, I will certainly let you know. Right now, I just manually test my packages every time I update the command line tools on my Mac because I know someone at some point will report problems on my repos.

**Comment by sjmgarnier** [comment]
@eddelbuettel It looks like Apple has fixed the issue somehow. The latest update of the CLT for Sequoia doesn't have the problem anymore.

**Comment by eddelbuettel** [comment]
@sjmgarnier That is good to know so thank you for reporting back here!
