### ISSUE TITLE
Attributes pkgHeader handling misses .hpp extension. 

### ISSUE THREAD

**Issue by Thell** [RcppCore/Rcpp#134]
https://github.com/RcppCore/Rcpp/blob/master/R/Attributes.R#L375

No test is being done for `pkgHeaderPath` when the `pkgHeader` has the `.hpp` extension and so it fails to get included into `RcppExports.cpp`.

Shouldn't the skeleton, and supporting scripts be defaulting to `.hpp` to support best practice?

BTW - The `cppFunction` documentation makes reference to `.hpp`

> If no plugin is defined for the package then a header file based the package's name (e.g. PkgName.hpp) will be included.

**Comment by eddelbuettel** [comment]
I may be a little thick but I read the discussion as JJ and I being on board with "just .h it is" and trying to explain to you why.   As such, a pull request may start from a slightly handicapped position...  When I said "seven and four packages" you need to see that in light of the _thousands_ of existing CRAN packages.  So methinks your preference is an outlier.

But I'd be happy to be convinced otherwise.

**Comment by Thell** [comment]
I'd be interested in what those numbers are now.

**Comment by eddelbuettel** [comment]
I usually tell emacs to treat .h as c++, so I think of this as a local issue.

I see six packages with `src/*.hpp`, three by the same author(s) (ie qt{base,paint,util}
I see seven packages with `inst/include/*hpp`.

**Comment by kevinushey** [comment]
I lean towards 'complying' with R-exts. See:
http://cran.r-project.org/doc/manuals/r-release/R-exts.html#FOOT13



On Sat, Jan 24, 2015 at 1:48 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by Thell** [comment]
Well... someday someone will see how silly 'FOOT13' is as pointed out [here](https://stat.ethz.ch/pipermail/r-devel/2014-March/068549.html) (or perhaps actually respond to a modern day issue with using .hpp).

**Comment by eddelbuettel** [comment]
Kevin seals the deal.  We are of the "whatever WRE or CRAN say" school -- it may be silly, but we're playing in their yard.  It is R's build system.    So unless Thell gets R Core to change their mind (and that can happen...) we will play by their rules.  For better or worse (having just needlessly some `inst/examples/*/Makefile(s)` to `GNUmakefile` for which I am still mad.  Butwhatyagonnado...

So I am closing this.

**Comment by Thell** [comment]
Roger on that...

Even with respect to looking at the history of Attributes.R and the inclusion of [these commits](https://github.com/RcppCore/Rcpp/commits/b529b9bbd1d8642e5d8f8124adc098510a24188c?author=luckyrandom) to resolve #193
