### ISSUE TITLE
Rcpp 1.0.13 build error with R 4.4.2 (VECTOR_PTR_RO)

### ISSUE THREAD

**Issue by kyleam** [RcppCore/Rcpp#1341]
I can successfully build and install Rcpp 1.0.13 with an R built from the current trunk (revision 87283).  However, with an R version built from an R-4-4-branch checkout (revision 87276), I get the following error:

```
* installing *source* package ‘Rcpp’ ...
** package ‘Rcpp’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
using C++ compiler: ‘g++ (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0’
g++ -std=gnu++17 -I"/tmp/r-install/lib/R/include" -DNDEBUG -I../inst/include/  -I/usr/local/include    -fpic  -g -O2   -c api.cpp -o api.o
g++ -std=gnu++17 -I"/tmp/r-install/lib/R/include" -DNDEBUG -I../inst/include/  -I/usr/local/include    -fpic  -g -O2   -c attributes.cpp -o attributes.o
g++ -std=gnu++17 -I"/tmp/r-install/lib/R/include" -DNDEBUG -I../inst/include/  -I/usr/local/include    -fpic  -g -O2   -c barrier.cpp -o barrier.o
In file included from barrier.cpp:31:
barrier.cpp: In function ‘SEXPREC** get_vector_ptr(SEXP)’:
../inst/include/Rcpp/r/compat.h:34:26: error: ‘VECTOR_PTR_RO’ was not declared in this scope; did you mean ‘VECTOR_PTR’?
   34 | # define RCPP_VECTOR_PTR VECTOR_PTR_RO
      |                          ^~~~~~~~~~~~~
barrier.cpp:74:30: note: in expansion of macro ‘RCPP_VECTOR_PTR’
   74 |     return const_cast<SEXP*>(RCPP_VECTOR_PTR(x));       // #nocov end
      |                              ^~~~~~~~~~~~~~~
make: *** [/tmp/r-install/lib/R/etc/Makeconf:204: barrier.o] Error 1
ERROR: compilation failed for package ‘Rcpp’
* removing ‘/tmp/rcpp-install/lib/Rcpp’
```

9c5f71c0 (use read-only variants of {STRING/VECTOR}_PTR (#1317), 2024-07-11) added the following conditions:

```
#if R_VERSION >= R_Version(4, 4, 2)
# define RCPP_STRING_PTR STRING_PTR_RO
#else
# define RCPP_STRING_PTR STRING_PTR
#endif

#if R_VERSION >= R_Version(4, 4, 2)
# define RCPP_VECTOR_PTR VECTOR_PTR_RO
#else
# define RCPP_VECTOR_PTR VECTOR_PTR
#endif
```

While it looks like `STRING_PTR_RO` has been around since R 3.5.0, `VECTOR_PTR_RO` isn't available until `trunk@86694` ([wch/r-source@85ee9ad34c](https://github.com/wch/r-source/commit/85ee9ad34cff164ce3e7038f51ce0eee5db90469)).  `VECTOR_PTR_RO` is present in trunk but not the upcoming R 4.4.2 (i.e. the condition above is incorrect).

```
# confirmation by inspecting svn checkouts
$ grep VECTOR_PTR_RO R-4-4-branch/include/Rinternals.h trunk/include/Rinternals.h
trunk/include/Rinternals.h:const SEXP *(VECTOR_PTR_RO)(SEXP x);

# confirmation by inspecting wch/r-source
$ git for-each-ref --contains=85ee9ad34cff164ce3e7038f51ce0eee5db90469 refs/remotes
c06d2576f10fc82a4e06120df79f32eeaf044f99 commit	refs/remotes/origin/HEAD
37f8078802e29f98db40a6b287275a5043e16b06 commit	refs/remotes/origin/R-more-NS
c06d2576f10fc82a4e06120df79f32eeaf044f99 commit	refs/remotes/origin/trunk
```

[ +cc @kevinushey ]

**Comment by eddelbuettel** [comment]
Hm.  Maybe we bit ourselves using 4.4.2 as a cutoff when we meant 4.5.0.

**Comment by kevinushey** [comment]
Yup. I (apparently incorrectly) assumed that R 4.4.2 would've gained those macros.

**Comment by eddelbuettel** [comment]
I think to close this issue #1341 we need more than #1342 -- we may also need a spot release (say: 1.0.13-1) at CRAN if I understand the report correctly as '1.0.13 cannot be compiled under R 4.4.2'.

**Comment by eddelbuettel** [comment]
Yes that is basically the same report as above. 

If you try the branch @kevinushey just committed via `remotes::install_github()` you will likely succeed.

**Comment by eddelbuettel** [comment]
I accepted and merged the PR so `remotes::install_github("RcppCore/Rcpp")` will work for you off the main branch.

Updates at r-universe will happen with the hour, that will give you binaries and tarballs too.  We will look into CRAN as well.

**Comment by eddelbuettel** [comment]
I now have rocker/r-base:4.4.2 up and confirmed that current Rcpp at CRAN / github CRAN up to 1.0.13.4 runs into this issue, and 1.0.13.5 passes.  Now that I can replicate I can work (tomorrow) on a minimal update 1.0.13-1 that passes.

Thanks for everybody's patience while we sort this out.

**Comment by kyleam** [comment]
@eddelbuettel Thank you!

**Comment by eddelbuettel** [comment]
I created a new branch release/1.0.13 with two cherry-picked commits: the required 4.4.2 adjustment correcting use of read-only pointers in the C API to R 4.5.0 or later (the issue at heart here) and the switch to Authors@R without which CRAN would not take the package.   

This content should make it to CRAN as 1.0.13-1.

**Comment by eddelbuettel** [comment]
And I just got the 'thanks, on its way to CRAN now' email, this time from Vienna rather than Dortmund.

**Comment by eddelbuettel** [comment]
Closing this now given the hot-fix is on CRAN as 1.0.13-1.  Big thank you to @kyleam for the timely and very focussed bug report, to @RCIIIcm for the confirmation, and of course to @kevinushey for putting PR #1342 up to address it.

**Comment by barracuda156** [comment]
Somehow I get a similar error with `RJSONIO` and R 4.4.3: https://github.com/duncantl/RJSONIO/issues/30

**Comment by eddelbuettel** [comment]
@barracuda156 :

- As `RJSONIO` does not use `Rcpp` I am not sure why you post here
- I addressed the issue in a [post to the r-devel list](https://stat.ethz.ch/pipermail/r-devel/2025-March/083918.html)
- @kurthornik says he will release an update `RJSONIO` shortly

**Comment by barracuda156** [comment]
@eddelbuettel Thank you very much!
