### ISSUE TITLE
ListOf<T> class

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/Rcpp#135]
`ListOf<T>` is like a `List`, but subsetting it should return elements of type `T` and hence avoid having to do casts. It was initially motivated by @romainfrancois.

Suppose we have:

```cpp
typedef ListOf<NumericVector> NVList;
NVList x;
````

- Can we enable lvalue differentiation, rvalue differentiation, and member functions? E.g. we would like to be able to do both of these:

a. `x[0] = x[0] + x[1];`
b. `x[0].attr("foo") = "bar";`

We currently use the `ListOfProxy` to handle lvalue and rvalue differentiation, but the `ListOfProxy` object generated does not have access to these methods. Is there a clean way that we can get any methods available for a `NumericVector` on the proxy object returned by `x[0]`?

- When constructing a `ListOf<T>`, should we check / coerce elements to `T`, or trust the user to do it? E.g. if I construct a `ListOf<T>` from a `List` should those elements be converted to `T` on insertion? Or should these be subclasses e.g. `StrictListOf`...

**Comment by coatless** [comment]
The [`ListOf<T>`](https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/vector/ListOf.h) was created under commits 5c236276b34968809d6c998bd1510e6122339119, 2e52627a2d18946a2b8092e81de2734da92c5b91, and ce5d157dbb053eabaca9cd2c7c19ce95562d29f3. 

Please close.  (Tagging #506)
