### ISSUE TITLE
.parseLinkingTo fails with versioned LinkingTo

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/Rcpp#145]
This occurs because `.parseLinkingTo` will pass the package name including the version (e.g. `Rcpp(>=0.11.0)`), then look for that name in the set of available packages.

I imagine the easiest solution is just stripping the version numbers; alternatively we can check the version number supplied against the package the user has installed.

**Comment by coatless** [comment]
The commit 51d4f1c3c66026e15392a8c923b4707fd5421be4 has survived the test of time in [R/Attributes.R](https://github.com/RcppCore/Rcpp/blob/96f36a1706ebba3289b247690052f7b215b0dfb3/R/Attributes.R#L960-L968)

Please close. (Tagging #506)
