### ISSUE TITLE
class__dummyInstance not called properly

### ISSUE THREAD

**Issue by romainfrancois** [RcppCore/Rcpp#147]
Spotted [here](http://stackoverflow.com/questions/23831109/rcpp-could-not-be-loaded). 

The problem is that [here](https://github.com/RcppCore/Rcpp/blob/b5ff9b5530e4a82682caab5ddc87ac23a7b8857e/R/Module.R#L129) it is called with quotes when it should not. 

```
new_dummyObject <- function(...)
    .External( "class__dummyInstance", ...)
```

**Comment by dalekube** [comment]
Does the Module.R file not exist anymore? I installed the package today and am receiving this error. However, I can't locate the Module.R file where the "class__dummyInstance" object is called.

> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

**Comment by eddelbuettel** [comment]
It hasn't gone anywhere as you can see [eg here](https://github.com/RcppCore/Rcpp/blob/master/R/Module.R).

**Comment by dalekube** [comment]
The class__dummyInstance object is not in quotes within my Module.R file, yet I still receive the error message.

![rcpp error](https://user-images.githubusercontent.com/12777137/29080787-5a9ef7b0-7c26-11e7-9738-826757db3593.PNG)

**Comment by eddelbuettel** [comment]
If in doubt, reinstall.

**Comment by leok31** [comment]
I'm having the same issues.
R is installed on Windows 7 machine.
@dalekube have you been able to fix this issu? Also, I can't seem to find module.R in the Rcpp directry.

**Comment by eddelbuettel** [comment]
Well, we made _three complete releases_ since that post in August which involves numerous builds and tests (by CRAN and others) on different platforms, including several Windows systems. I still don't have anything reproducible to go by and suspect this too is a local issue.

**Comment by leok31** [comment]
Thanks for replying. I realise this is a local issue, I've been using this package (via ggplot2 and others) for a while on many computers and this is the first time I'm seeing this issue. This is also the first time I'm running this on a machine for which I don't have admin rights.
Maybe you could suggest something I can try on the machine itself?

**Comment by eddelbuettel** [comment]
Reinstalling Rcpp and the packages depending on it.   The binaries on CRAN get rebuild consistently so they should work, else you could recompile locally.
