### ISSUE TITLE
ListOf<>::names() and ::attr()

### ISSUE THREAD

**Issue by romainfrancois** [RcppCore/Rcpp#183]
Would be useful to be able to grab names and other attributes from a `ListOf` object, as in: 

```
ListOf<DataFrame> x = ... ;
CharacterVector names = x.names() ;
```

**Comment by coatless** [comment]
This feature request was addressed in commit 617bb76edf76061197e9dbf24d5f8342fe80ea04

Please close. (Tagging #506)
