### ISSUE TITLE
Rcpp::SquareMatrix class

### ISSUE THREAD

**Issue by romainfrancois** [RcppCore/Rcpp#229]
I have added them in `Rcpp11` and `Rcpp14`. See Rcpp11/Rcpp11#224 for details and implementation. This is just a convenience class, the bonus is that the `SEXP` ctor throws if the given matrix is not square.

**Comment by coatless** [comment]
The resolution of this issue seems straightforward.

Would the inclusion of `SquareMatrix()` be of interest? 
@eddelbuettel

**Comment by eddelbuettel** [comment]
How much effort would you want to toss at it for what gain?   We will not recoup the memory (as we inherit its layout from R as a contiguous n*n chunk) so it is just "sugar", really?   

Thoughts about this @dcdillon ?

**Comment by dcdillon** [comment]
Unless we plan to build streamlined algorithms for square matrices, there isn't any benefit that I can see from having a SquareMatrix class.  And given that sugar almost exclusively operates member wise on vectors, unless we plan on adding a bunch of Matrix functions, it'll just be a pain for everyone to maintain another class

**Comment by eddelbuettel** [comment]
Agreed.  So closing this now.
