### ISSUE TITLE
assert spillover from tinyformat?

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#237]
Kurt Hornik pointed out that the `tinyformat.h` may spill assert:

>  > Where are we with textreg then? "Their" problem in assert() misuse, or do
>  > you suspect a spillover from headers (though you'd think we see that
>  > more often).
>  
>  I can only guess: grepping the old and new Rcpp sources for assert shows
>  that you now have
>  
>    /inst/include/RcppCommon.h:#include <Rcpp/utils/tinyformat.h>
>  
>  which in turn includes cassert ... (which I guess brings in the usual
>  1-arg assert).  Right?

@kevinushey @romainfrancois : As you're more familiar with tinyformat.h, can you check and possible `undef` as needed? So far package textreg appears to be the only casualty, and I misdiagnosed this.

**Comment by kevinushey** [comment]
Hi Dirk,

Sorry for letting that slip in -- indeed, `tinyformat` gives us a simple way to provide our own error handlers on unrecognized format strings, but defaults to `assert` -- we need to override this ourselves. I just submitted a PR to fix that.

**Comment by eddelbuettel** [comment]
Thanks for the quick fix!
