### ISSUE TITLE
print() method for vectors ?

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#239]
Via `Rf_PrintValue`, cf [this SO answer](http://stackoverflow.com/a/28153349/143305) ?

**Comment by thirdwing** [comment]
It seems ``std::ostream & operator<<`` is more C++ than ``print()``

**Comment by eddelbuettel** [comment]
Oh, we need that too :)  And have needed it for years....

**Comment by dcdillon** [comment]
Hey...I think we can close this one!  See #361

**Comment by eddelbuettel** [comment]
Agreed.
