### ISSUE TITLE
XPtr should check that input isn't a null pointer

### ISSUE THREAD

**Issue by hadley** [RcppCore/Rcpp#240]
e.g. at https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/XPtr.h#L65

```cpp
if (R_ExternalPtrAddr(x) == NULL) 
  ::Rcpp::not_compatible( "External pointer is null" );
```

When pointers are serialised then deserialised they are always set to null, so otherwise you need to add this check manually every place you use an external pointer.

**Comment by jjallaire** [comment]
See PR at https://github.com/RcppCore/Rcpp/pull/246
