### ISSUE TITLE
XPtr should include a get method

### ISSUE THREAD

**Issue by hadley** [RcppCore/Rcpp#242]
Since it's a smart pointer, and needs an obvious way to get the underlying object

**Comment by romainfrancois** [comment]
It has a suitable conversion operator: https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/XPtr.h#L121

Consider: 

```cpp
#include <Rcpp.h>
using namespace Rcpp ;

// [[Rcpp::export]]
bool foo(){
  std::vector<double>* x = new std::vector<double>; x->push_back(1) ;
  
  XPtr< std::vector<double> > xp(x) ;
  std::vector<double>* y = xp ;
  
  return y == x ;
  
}

/*** R
    foo()
*/
```

A `.get()` method would not be a luxury though.

**Comment by hadley** [comment]
I needed it when manually "deleting" a XPtr:

```cpp
// [[Rcpp::export]]
void rsqlite_disconnect(XPtr<SqliteConnectionPtr> con) {
  if (R_ExternalPtrAddr(con) == NULL) stop("Connection already closed");
  
  delete con.operator->();
  R_ClearExternalPtr(con);
}
```

although maybe what I actually need is a delete/close method.

cc @jjallaire

**Comment by romainfrancois** [comment]
I see. I guess something that says "delete now" rather than "delete whenever I get GC'd" could be useful as you should not have to use `R_ExternalPtrAddr` or `R_ClearExternalPtr`

**Comment by hadley** [comment]
#240 would fix the need for `R_ExternalPtrAddr`. It's really important because serialisation sets all XPtrs to NULL.

**Comment by hadley** [comment]
In general, maybe should match `unique_ptr` api (http://www.cplusplus.com/reference/memory/unique_ptr/), so call it `release()`?

**Comment by jjallaire** [comment]
See PR at: https://github.com/RcppCore/Rcpp/pull/246
