### ISSUE TITLE
Rcpp::List::create( )  fails for large number of items

### ISSUE THREAD

**Issue by Jacob001** [RcppCore/Rcpp#243]
I have included 2 functions
1) working function: creates two lists each holding half of item
2) non-working function: makes a single list to hold all items 

The error I receive (non-working function) is:

list_error.cpp: In function 'Rcpp::List read_headerC_bad(std::string)':
list_error.cpp:147:43: error: no matching function for call to 'Rcpp::Vector<19>::create(char [4], std::string, short unsigned int&, short unsigned int&, long unsigned int&, short unsigned int&, short unsigned int&, std::string, unsigned char&, unsigned char&, std::string, std::string, short unsigned int&, short unsigned int&, short unsigned int&, long unsigned int&, long unsigned int&, unsigned char&, short unsigned int&, long unsigned int&, long unsigned int&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&)'

//// EXAMPLE 1
#include <Rcpp.h>
#include <iostream>
#include <fstream>
//#include <string>

//using namespace std;
using namespace Rcpp;

#pragma pack(push, 1)
typedef struct {

  char signature[4];
	unsigned short file_source_id;
	unsigned short encoding;
	unsigned long GUID1;
	unsigned short GUID2;
	unsigned short GUID3;
	unsigned char GUID4[8];
	unsigned char version_major;
	unsigned char version_minor;
	char system_id[32];
	char software[32];
	unsigned short create_day;
	unsigned short create_year;
	unsigned short header_size;
	unsigned long offset_to_points;
	unsigned long num_vlr;
	unsigned char format_id;
	unsigned short rec_length;
	unsigned long num_points;
	unsigned long num_returns[5];
	double xscale;
	double yscale;
	double zscale;
	double xoffset;
	double yoffset;
	double zoffset;
	double xmax;
	double ymax;
	double zmax;
	double xmin;
	double ymin;
	double zmin;

} LAS_HEADER;
#pragma pack(pop)

//[[Rcpp::export]]
Rcpp::List read_headerC(std::string file_name) {

	FILE* file = fopen(file_name.c_str(), "rb");
	LAS_HEADER header_in;
	
	fread(&header_in, sizeof header_in, 1, file);

  Rcpp::List r_header_a = Rcpp::List::create(
    
                                         header_in.signature
                                         ,(std::string) (reinterpret_cast <const char*> (header_in.signature)) 
                                          ,header_in.file_source_id
                                          ,header_in.encoding
                                          ,header_in.GUID1
                                          ,header_in.GUID2
                                          ,header_in.GUID3
                                          ,(std::string) (reinterpret_cast <const char*> (header_in.GUID4))
                                          ,header_in.version_major
                                          ,header_in.version_minor
                                          ,(std::string) (reinterpret_cast <const char*> (header_in.system_id)) 
                                          ,(std::string)(reinterpret_cast <const char*> (header_in.software))
                                          ,header_in.create_day
                                          ,header_in.create_year
                                          ,header_in.header_size
                                          ,header_in.offset_to_points
                                          );
                                          
  Rcpp::List r_header_b = Rcpp::List::create(                                     
                                          header_in.num_vlr
                                          ,header_in.format_id
                                          ,header_in.rec_length
                                          ,header_in.num_points
                                          ,*(header_in.num_returns) 
                                          ,header_in.xscale
                                          ,header_in.yscale
                                          ,header_in.zscale
                                          ,header_in.xoffset
                                          ,header_in.yoffset
                                          ,header_in.zoffset
                                          ,header_in.xmax
                                          ,header_in.ymax
                                          ,header_in.zmax
                                          ,header_in.xmin
                                          ,header_in.ymin
                                          ,header_in.zmin
                                          
                                          );

 

	return Rcpp::List::create(r_header_a,r_header_b) ;

}

//[[Rcpp::export]]
Rcpp::List read_headerC_bad(std::string file_name) {

	FILE* file = fopen(file_name.c_str(), "rb");
	LAS_HEADER header_in;
	
	fread(&header_in, sizeof header_in, 1, file);

  Rcpp::List r_header_a = Rcpp::List::create(
    
                                         header_in.signature
                                         ,(std::string) (reinterpret_cast <const char*> (header_in.signature)) 
                                          ,header_in.file_source_id
                                          ,header_in.encoding
                                          ,header_in.GUID1
                                          ,header_in.GUID2
                                          ,header_in.GUID3
                                          ,(std::string) (reinterpret_cast <const char*> (header_in.GUID4))
                                          ,header_in.version_major
                                          ,header_in.version_minor
                                          ,(std::string) (reinterpret_cast <const char*> (header_in.system_id)) 
                                          ,(std::string)(reinterpret_cast <const char*> (header_in.software))
                                          ,header_in.create_day
                                          ,header_in.create_year
                                          ,header_in.header_size
                                          ,header_in.offset_to_points                                 
                                          ,header_in.num_vlr
                                          ,header_in.format_id
                                          ,header_in.rec_length
                                          ,header_in.num_points
                                          ,*(header_in.num_returns) 
                                          ,header_in.xscale
                                          ,header_in.yscale
                                          ,header_in.zscale
                                          ,header_in.xoffset
                                          ,header_in.yoffset
                                          ,header_in.zoffset
                                          ,header_in.xmax
                                          ,header_in.ymax
                                          ,header_in.zmax
                                          ,header_in.xmin
                                          ,header_in.ymin
                                          ,header_in.zmin
                                          
                                          );

 

	return r_header_a ;

}

**Comment by eddelbuettel** [comment]
If you care to check old mailing posts (and possibly old issue tickets) you will see that this is sort of known. 

I would invite to stick with what works, or suggest to patch to accommodate your large-size requests.

**Comment by Jacob001** [comment]
Ok thanks, sounds good. I will dig deeper in the archive.

Jacob L Strunk
Forest Inventory Remote Sensing Specialist
Washington State Department of Natural Resources (WA DNR)
PO Box 47000, 1111 Washington Street SE
Olympia, WA 98504-7000
Jacob.Strunk@dnr.wa.gov
360-902-1653
________________________________

**Comment by kevinushey** [comment]
I posted a `ListBuilder` class on the mailing list a while ago; you might find it useful:

```cpp
#include <Rcpp.h>
using namespace Rcpp;

class ListBuilder {

public:

  ListBuilder() {};
  ~ListBuilder() {};

  inline ListBuilder& add(std::string name, SEXP x) {
    names.push_back(name);
    elements.push_back(PROTECT(x));
    return *this;
  }

  inline operator List() const {
    List result(elements.size());
    for (size_t i = 0; i < elements.size(); ++i) {
      result[i] = elements[i];
    }
    result.attr("names") = wrap(names);
    UNPROTECT(elements.size());
    return result;
  }

  inline operator DataFrame() const {
    List result = static_cast<List>(*this);
    result.attr("class") = "data.frame";
    result.attr("row.names") = IntegerVector::create(NA_INTEGER, XLENGTH(elements[0]));
    return result;
  }

private:

  std::vector<std::string> names;
  std::vector<SEXP> elements;

  ListBuilder(ListBuilder const&) {};

};

// [[Rcpp::export]]
DataFrame test_builder(SEXP x, SEXP y, SEXP z) {
  return ListBuilder()
    .add("foo", x)
    .add("bar", y)
    .add("baz", z);
}

/*** R
test_builder(1:5, letters[1:5], rnorm(5))
*/
```

**Comment by Jacob001** [comment]
Great! Thanks Kevin.
