### ISSUE TITLE
Export Template functions

### ISSUE THREAD

**Issue by bonmac** [RcppCore/Rcpp#249]
When building an R package, I get the error <i>A template declaration cannot appear at block level</i>

I am new to C++ and Rcpp. 
<pre><code>
#include &lt;Rcpp.h&gt;
#include &lt;string&gt;
#include "HashTable.hpp"

// [[Rcpp::export]]
template &lt;typename T&gt;
T getValueImpl( const Rcpp::CharacterVector key ) {
  std::string search = Rcpp::as&lt;std::string&gt; ( key[ 0 ] ) ;
  Rcpp::Environment glbEnv = Rcpp::Environment::global_env () ;
  Rcpp::List hashTable = Rcpp::List( glbEnv [ ".MapperR_hash" ] ) ;
  Cin::HashTable&lt;std::string, T&gt; ht = Rcpp::as&lt;Cin::HashTable&lt;std::string, T&gt; ( hashTable ) ;
  T res =  ht.get_value( search );
  return Rcpp::wrap( res );
}
</code></pre>

The exported function in RcppExports.cpp is

<pre><code>
// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include &lt;Rcpp.h&gt;

using namespace Rcpp;

// getValueImpl
template &lt;typename T&gt; T getValueImpl(const Rcpp::CharacterVector key);
RcppExport SEXP MappeR_getValueImpl(SEXP keySEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter&lt; const Rcpp::CharacterVector >::type key(keySEXP );
        template &lt;typename T&gt; T __result = getValueImpl(key);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}

</code></pre>

Please help out.

**Comment by romainfrancois** [comment]
You just cannot `Rcpp::export` a template function.

**Comment by bonmac** [comment]
Ok thanks
