### ISSUE TITLE
Rcpp sugar exact value by name seems so slowly

### ISSUE THREAD

**Issue by guokai8** [RcppCore/Rcpp#250]
Hi, I just test how to exact value  from a NumericVector by names, the result is so terrible.Below is the code, and the test result;
```
######name_index2.cpp#####
#include <Rcpp.h>
using namespace Rcpp;
//[[Rcpp::export]]
NumericVector sugar_index(StringVector& xin,NumericVector& yin){
  NumericVector res;
  res=yin[xin];
  return res;
}

>sourcecpp("name_index2.cpp")
>x<-rnorm(500)
>names(x)<-paste("a",1:500,sep="_");
>y<-sample(names(x),200)
>library(rbenchmark)
>benchmark(sugar_index(y,x),x[y])
                test         replications elapsed relative user.self sys.self user.child
1 sugar_index(y, x)          100   0.047     23.5     0.047    0.001          0
2              x[y]             100   0.002      1.0     0.003    0.000           0
```
So why the Rcpp sugar seems so slowly!
Is there other method could be used in the Rcpp instead ?

**Comment by guokai8** [comment]
why the first line "#include <Rcpp.h> " could not show completely

**Comment by romainfrancois** [comment]
Embed you c++ code between  "```cpp" and "```"

**Comment by guokai8** [comment]
I have tried , but it failed. The point is the "sugar_index" show almost 24 slowly than the base function. Did I miss something or make mistake?

**Comment by romainfrancois** [comment]
See this for github flavored markdown; https://help.github.com/articles/github-flavored-markdown/

As for the issue you report, it all happens from this line: https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/vector/Subsetter.h#L140

in this methods: 

```
    int find(const RHS_t& names, const char* str) {
        for (int i=0; i < lhs_n; ++i) {
            if (strcmp( CHAR( STRING_ELT( names, i) ), str) == 0) return i;
        }
        stop("no name found");
        return -1;
    }
```

The `find` uses string comparisons where direct pointer comparisons of the `CHARSXP` would be much faster. cc @kevinushey

**Comment by guokai8** [comment]
Thanks,I will try it.Could I use another method instead ?

**Comment by eddelbuettel** [comment]
There are a few things to try.  First, your measured times are very small and prone to error and overhead.  Repeat maybe 1000 or 5000 times (see `help(benchmark)`).  Second, consider writing alternate little C++ function to try different comparisons.  

At the end of the day the cost of the single comparison may or may not matter in the context of larger simulations or studies.  But if you were to submit are carefully written, documented and tested pull request we might well consider it.

**Comment by guokai8** [comment]
Thanks! Below is the 5000 times results
```
> benchmark(sugar_index(y,x),x[y],replications=5000)
               test replications elapsed relative user.self sys.self user.child
1 sugar_index(y, x)         5000   2.532   18.482     2.527    0.004          0
2              x[y]         5000   0.137    1.000     0.137    0.000          0
  sys.child
1         0
2         0
```
Because I have write a package include this step and I find this step is the "bottleneck". So I want to make some changes.
BTW, I have written a small C++ code, but it seem not fast than the "sugar_index" function. Forgive  me for poor C++ skill.

**Comment by guokai8** [comment]
I replace the https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/vector/Subsetter.h#L140 as below
```
void get_indices( traits::identity< traits::int2type<STRSXP> > t ) { 
           indices.reserve(rhs_n);
           SEXP names = Rf_getAttrib(lhs, R_NamesSymbol);                                                                                                 
           if (Rf_isNull(names)) stop("names is null");
           for (int i=0; i < rhs_n; ++i) {
               indices.push_back( find(names, STRING_ELT(rhs, i) ) );
           }   
           indices_n = indices.size();
       }       
               
       int find(const RHS_t& names, SEXP str) {
           for (int i=0; i < lhs_n; ++i) {
               if (STRING_ELT( names, i) == str) return i;
           }   
           stop("no name found");
           return -1; 
       }       
```
then rebuild the Rcpp package by using (install_local function included  in devtools), Below is the test code:
```
> sourceCpp("sugar_index.cpp")
> x<-1:200
> names(x)<-paste("g",1:200,sep="_")
> y<-sample(names(x),50)
> res<-sugar_index(y,x)
> res[1:3]
g_123  g_83  g_28 
  123    83    28 
> library(rbenchmark)
> benchmark(sugar_index(y,x),x[y],replications=5000)
               test replications elapsed relative user.self sys.self user.child
1 sugar_index(y, x)         5000   0.108    1.964     0.107    0.002          0
2              x[y]         5000   0.055    1.000     0.054    0.001          0
  sys.child
1         0
2         0
```
As you see, the speed is almost equal with the bulit in function. Thanks, @romainfrancois.
I guess I do it in right way.
Actually, I wonder why the built in function ('[') is so quick. I want to see the source code and search the google, However, I think I haven't found the source code.

**Comment by romainfrancois** [comment]
I'd retrieve the `SEXP*` from the `names` using `get_string_ptr` then just use a `std::find`. Something like this: 

```
  SEXP* b = get_string_ptr(names) ;
  SEXP* match = std::find( b, b + lhs_n, str ) ;
  if( match == b + lhs_n ){
    stop("not found") ;
    return -1;     
  }
  return match - b ;
```

The advantages are: 
 - `STRING_ELT` pays for the write barrier
 - `std::find` might get better with newer versions of C++

Going further, this is an embarrassingly parallel problem, so this might benefit from parallelism. 
Another option would be to consider caching the retrieved indices into some sort of a hashmap so that you don't pay for linear search each time.

**Comment by guokai8** [comment]
I just test the code you provided,below is the result
```
> benchmark(sugar_index(y,x),x[y],replications=5000)
               test replications elapsed relative user.self sys.self user.child
1 sugar_index(y, x)         5000   0.062    1.148     0.062    0.000          0
2              x[y]         5000   0.054    1.000     0.052    0.001          0
  sys.child
1         0
2         0
```
it seems much quick than mine. Thanks for your good suggestions. @romainfrancois 
Maybe the next version of Rcpp could fix the problem cc @kevinushey

**Comment by romainfrancois** [comment]
Quite sure the remaining difference is about the `STRING_ELT(rhs, i)` in `get_indices`

**Comment by guokai8** [comment]
I try to use parallelFor (included in the RcppParallel) to solve the problem but failed. could you give some clue? Thanks

**Comment by guokai8** [comment]
Below is the code,I have not found why it did not work as I expected.
```
   //[[Rcpp::depends(RcppParallel)]]
   #include <RcppParallel.h>
   #include <Rcpp.h>  
   using namespace RcppParallel;
   using namespace Rcpp;
   struct mySel : Worker
 {                     
    SEXP* namesPtr;  
    SEXP* rhsPtr;       
    StringVector& nn; 
    NumericVector& res;
    mySel(SEXP* names,SEXP* rhsPtr ,StringVector& nn,NumericVector& res):namesPtr(names),rhsPtr(rhsPtr),nn(nn),res(res){}
   void operator()(std::size_t begin,std::size_t end){
     for(std::size_t i=begin;i<end;i++){
       SEXP* match=std::find(namesPtr,namesPtr+nn.size(),*(rhsPtr+i+i));
       if(match==namesPtr+nn.size())
         stop("not found");
       res.push_back(match-namesPtr);
     }                 
   }                   
  };                    
   //[[Rcpp::export]] 
  SEXP compare_and_name_par(StringVector& xin,NumericVector& yin){
    NumericVector res;
    StringVector names = Rf_getAttrib(yin, R_NamesSymbol);
    if (Rf_isNull(names)) stop("names is null");
    SEXP* namesPtr = STRING_PTR(names);
    SEXP* rhsPtr = STRING_PTR(xin);
    mySel mysel(namesPtr,rhsPtr,names,res);
    parallelFor(0,xin.size(),mysel);                                                                                                                   
   // for(int i=0;i<xin.size();i++){
   //   SEXP* match = std::find(namesPtr, namesPtr + names.size(), *(rhsPtr + i));
   //   if (match == namesPtr + names.size())
   //     stop("not found");
   //   res.push_back(match - namesPtr);
   // }                 
    int indice_n=res.size();
    NumericVector output=no_init(indice_n);
   for(int m=0;m<indice_n;m++){
     output[m]=yin[res[m]];
   }                   
    output.attr("names")=xin;
    return output;   
  }
```

**Comment by jjallaire** [comment]
You can't call into R or Rcpp within a Worker (see the various Rcpp Gallery
articles on RcppParallel for more details:
http://gallery.rcpp.org/tags/parallel/)

**Comment by guokai8** [comment]
I have already read the four example and have not make it clearly,Is there other docs?

**Comment by jjallaire** [comment]
No, there aren't. It states very clearly in the examples that you CANNOT
access R and Rcpp classes (e.g. SEXP, CharacterVector) etc. within a
background worker. Your code is doing that. If you need to access R and
Rcpp data you need to use RVector<T> or RMatrix<T> (as described in the
articles). Note that these classes do not work with character vectors so I
don't think what you are doing is possible in any case.

**Comment by guokai8** [comment]
Thanks a lot, I will try.

**Comment by eddelbuettel** [comment]
I am closing this now.  Kevin's PR #252 has been integrated; it brings a solid improvement---and tests fine as per the just-committed reverse dependency checks in repo rcpp-logs.
