### ISSUE TITLE
Additional ways to bind to external dependencies in sourceCpp

### ISSUE THREAD

**Issue by jjallaire** [RcppCore/Rcpp#266]
There is a way for CRAN packages to declare system dependencies and then meet them at configure time (e.g gputools has a SystemDependency on Nvidia's CUDA toolkit which is ultimately bound using a configure script).

However, there is nothing analogous for sourceCpp, making it difficult to bind to system libraries for ad-hoc work unless they are already wrapped in an R package. A couple of things we could do to bridge this gap:
1. Create an `Rcpp::pkgconfig` attribute that queries pkg-config for whatever named dependencies it is passed. For example:

``` cpp
// [[Rcpp::pkgconfig(opencv)]]
```
1. As an escape hatch for when pkg-config isn't available, create an `Rcpp::buildenv` attribute that can be used to define arbitrary build environment variables:

``` cpp
// [[Rcpp::buildenv(PKG_CXXFLAGS = "...")]]
// [[Rcpp::buildenv(PKG_LIBS = "...")]]
```

Granted we have plugins already for the scenarios where you need arbitrary environment variables however plugins that aren't built into Rcpp are somewhat awkward to register as you need to execute some R code in your session to do so (e.g. in .Rprofile). The `buildenv` attribute would be more self-contained (albeit somewhat more hard-coded).

At first I didn't think we needed this sort of mechanism because "everything can be in an R package" but as it turns out even CRAN doesn't hold code to that standard (and some stuff is very difficult to get into a package that's distributed on CRAN).

**Comment by eddelbuettel** [comment]
This is a *very hard* problem.

Even the CRAN solution does not work as the declaration is "loose".  Any such dependency often differs in name between distros or OSs -- thing eg how to encode the (simpler) dependency for, say, MySQL/MariaDB headers and library, for PostgreSQL, ...   There simply is no standard.

I fear we have have the same problem here.  That said, I quite like that you at least attempt to pass _some_ configuration options (which may well be local and not portable) down to the build.  This goes the right way.   (Then again people always had `Sys.setenv()` and I am not sure how many people used that....)

**Comment by jjallaire** [comment]
Yes, I'm thinking that this is inherently a single-platform solutions
(although I do think for some things pkg-config will give you reasonable
portability between OSX and Linux).

Sys.setenv definitely works, but similar to registering plugins you have to
execute it out-of-band (e.g. it's not a documented/reproducible part of the
translation unit). Allowing a syntax for setting environment variables
directly in the C++ file would IMHO be an improvement.

One other thought: we could allow R packages to export plugins and be bound
to like this:

// [[Rcpp::plugins(foo::myplugin)]]

Which would allow packages to make plugin recipes available and to make
them cross platform by probing dynamically for various dependencies (e.g.
look for CUDA using pkg-config on 'NIX, and look in various standard
locations on WindowS).



On Tue, Feb 24, 2015 at 6:21 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by eddelbuettel** [comment]
Yes, I am a huge fan of `pkg-config` and run-time too. But you started with "frozen in time and text" information in DESCRIPTION, and that is harder.

Even `pkg-config` is hard, and possibly incomplete / not all-encompassing.  My main box has CUDA, and while `pkg-config --list-all | wc -l` reveals almost 300 entries, it does not cover CUDA.  Also, anecdotally, `pkg-config` does not always help on OS X where brew may not get it into the `$PATH` etc pp

**Comment by jjallaire** [comment]
We could solve some of this by the aforementioned notion of allowing
packages to export functions that provide configuration information (sort
of like we do now with plugins). These packages could call pkg-config as
well do other platform-specific probing/fixups, e.g.

```cpp
// [[Rcpp::config(gpulibs::opencv)]]
```

We could even create a common package (e.g. cpplibs) that collects a bunch
of these recipes (sort of like the CMake find_* macros), so it could be:

```cpp
// [[Rcpp::config(cpplibs::opencv)]]
```

We could then take pull requests into that package to build up a "database"
of configuration information sort of like CMake has done.

Actually, if CMake is installed I guess we could use it directly as well!
:-)



On Tue, Feb 24, 2015 at 6:41 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by jjallaire** [comment]
We could solve some of this by the aforementioned notion of allowing
packages to export functions that provide configuration information (sort
of like we do now with plugins). These packages could call pkg-config as
well do other platform-specific probing/fixups, e.g.

```cpp
// [[Rcpp::config(gpulibs::opencv)]]
```

We could even create a common package (e.g. cpplibs) that collects a bunch
of these recipes (sort of like the CMake find_* macros), so it could be:

```cpp
// [[Rcpp::config(cpplibs::opencv)]]
```

We could then take pull requests into that package to build up a "database"
of configuration information sort of like CMake has done.

Actually, if CMake is installed I guess we could use it directly as well!
:-)

**Comment by jjallaire** [comment]
Actually, since we're talking about situations where users already need to install extra software, we could base the whole thing on CMake (which already has a comprehensive database of library locations and has uniform names across platforms). Something like this:

```cpp
// [[Rcpp::cmake(OpenCV)]]
```
Which would call this:

```bash
cmake --find-package <etc>
```

Interestingly OpenCV recommends CMake as the best way to consume it on their website: http://docs.opencv.org/doc/tutorials/introduction/linux_gcc_cmake/linux_gcc_cmake.html

At the cost of one extra system dependency (that should be a stable of C++ developers anyway) we don't get into re-investing the configuration wheel. 

To publish the same code in a package would of course still require a custom configure script but that's no different than the world we live in now.

**Comment by jjallaire** [comment]
Here's a refinement of the above:

New package named **cmake** that knows to call `cmake --find-package` and parse the output into values that can be used in Makevars to set PKG_CXXFLAGS and PKG_LIBS (like we used to do for Rcpp). Here's the documentation on using this facility:

https://blogs.kde.org/2011/11/09/cool-new-stuff-cmake-286-2-pkg-config-compatible-mode-added-use-eg-autotools

So then Makevars might look like this:

```make
PKG_CXXFLAGS= $(shell "${R_HOME}/bin${R_ARCH_BIN}/Rscript.exe" -e "cmake::pkgCxxFlags('opencv')")
PKG_LIBS = $(shell "${R_HOME}/bin${R_ARCH_BIN}/Rscript.exe" -e "cmake::pkgLibs('opencv')")
```

For packages this would be an improvement on the existing "you need to somehow get OpenCv" or requirement of using Autoconf to find it.

In sourceCpp we could then do this:

```cpp
// [[Rcpp::cmake(OpenCV)]]
```

We'd then list the **cmake** package as a Suggests of Rcpp to reflect this optional dependency.

**Comment by jjallaire** [comment]
Last piece would be that the **cmake** package would need to list cmake >= 2.8.6 as a SystemDependency.

**Comment by eddelbuettel** [comment]
I was mostly nodding on the commute home about suggesting `cmake`.  It can quite possibly help here, and it does know a lot about other configs.  Small(ish) downside: not that entrenched in R-land.

The idea of a `cmake` package for R is pretty clever. That may work.

**Comment by jjallaire** [comment]
Good discussion. The notion behind all of this is a failsafe for situations
where it's difficult or impossible to have libraries embedded within CRAN
packages (as we've done with GSL, Eigen, Armadillo, TBB, etc.). This is of
course the simplest course for developers and users as there are no extra
steps required for usage and other CRAN packages can easily take the
library as a dependency.

As I've been polking around parallel computing libraries (especially GPU
ones) it looks like some of these might not be embeddable into CRAN
packages quite so easily (thus the motivation for this thread). Let's
revisit once we have a concrete use case (e.g. attempting to create an
ArrayFire package).


On Tue, Feb 24, 2015 at 9:16 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by jjallaire** [comment]
Some useful links when we revisit this:

Docs for cmake --find-package: https://blogs.kde.org/2011/11/09/cool-new-stuff-cmake-286-2-pkg-config-compatible-mode-added-use-eg-autotools

Installing custom CMake modules: http://stackoverflow.com/questions/10765885/how-to-install-your-custom-cmake-find-module

**Comment by stnava** [comment]
are you guys (actively) working toward a cmake R package?  i just tried to submit a package to CRAN (with a cmake SystemRequirement) and was told that cmake is not portable b/c it's not on solaris.  while it's possible to recreate the cmake makefile in makevars, i was hoping to avoid that ... side note: ripley says we cant git clone another repository on the fly, apparently, and this is something that cmake allows pretty naturally.  anyway, am curious if there is progress on this as it will impact (near) future development strategy.

**Comment by jjallaire** [comment]
No that's not something we're working on right now. That wouldn't actually
solve this issue either, as the cmake package would just be an interface to
calling cmake (it would still list CMake as a SystemRequirement).

**Comment by stnava** [comment]
ok, thanks.  i would imagine the cmake r package would redistribute cmake source and compile it for each platform vs making it a system dependency.  it should compile on solaris.

in case you would like to see recent use cases of system cmake (apparently not allowed by cran):

[ITKR here](https://github.com/stnava/ITKR/issues/1)

and 

[ANTsR here](https://github.com/stnava/ANTsRCran)

configure and makevars files are relevant.

**Comment by eddelbuettel** [comment]
There is no need for cmake commercials in this forum.  We are mostly agnostics: Rcpp is an R extension package, and we live in the playground provided by R.  Which does not include cmake. 

And as I said: we are agnostic. It is not a decison we made, were consulted with, or are (in all likelihood) going to be all that influential in changing at a future point.

**Comment by kevinushey** [comment]
Although the comments have since been deleted (please don't do that!) -- you can always push back on the CRAN maintainers, and just say that you don't want to support Solaris -- CRAN will accept packages as long as they build on at least 2 of the supported platforms (as long as you provide a good reason; although there may sitll be pushback). This is documented in the [CRAN Repository Policy](http://cran.r-project.org/web/packages/policies.html):

> Package authors should make all reasonable efforts to provide cross-platform portable code. Packages will not normally be accepted that do not run on at least two of the major R platforms. Cases for Windows-only packages will be considered, but CRAN may not be the most appropriate place to host them.

So just tell the CRAN maintainers that you don't intend to distribute your package on Solaris.

**Comment by eddelbuettel** [comment]
> please don't do that!
:100:
