### ISSUE TITLE
"stop" causes hang with Rtools 3.2 on 64 bit windows

### ISSUE THREAD

**Issue by jackwasey** [RcppCore/Rcpp#276]
```
cppFunction("void doStop() { Rcpp::stop(\"stopping\"); }")
# doStop() #hangs
```
I can't test 32 bit, but I found this debugging a hang using the win-builder CRAN service, and 32 bit executed fine, but 64 bit hung, and this was only in R-devel (which I assume uses the latest toolchain). Everything compiled fine. I therefore installed the latest Rtools 3.2 toolchain and R-devel on 64 bit windows 7, and replicated, as above.

**Comment by eddelbuettel** [comment]
Thanks for the heads-up.  From looking at the R-devel mailing list it seems that Rtools 3.2 isn't exactly settled yet. Duncan appears to have made changes just today or yesterday, and we do not know if Uwe has deployed that version or not.

**Comment by jackwasey** [comment]
Sounds good. I even see hard-coded paths in the MinGW GCC 4.9 with "Duncan" in them, so completely agree. As it causes guaranteed failure when running any Rcpp code with `stop` through winbuilder (which seems to be strongly recommended, and which I imagine many people do), I thought I should bring it to your attention.

**Comment by jackwasey** [comment]
I spoke too soon:
```
Rcpp::cppFunction("void doError() { Rf_error(\"stopping\"); }")
doError()
```
also hangs...

**Comment by eddelbuettel** [comment]
Yes, but don't you think you should talk more to Duncan (and/or r-devel) than to us about this?

**Comment by jackwasey** [comment]
Will do. I was just flagging that it seemed much less likely to be an Rcpp issue at this point.

**Comment by kevinushey** [comment]
Thanks for the report. We definitely want to be prudent in ensuring the newest version of Rtools plays nicely with Rcpp, and there may well be patches needed on our side as well.

Let's wait for the dust to settle around Rtools before throwing Rcpp into the mix -- presumedly, the unit tests passing / failing on win-builder (after Rtools has been confirmed okay) will be a strong indication of whether we're good to go, and certainly CRAN will be quick to let us know.
