### ISSUE TITLE
Rethinking DataFrame for GSoc-2015

### ISSUE THREAD

**Issue by 1dayac** [RcppCore/Rcpp#282]
Hello!
My name is Dima and here I want to discuss with you my proposal for GSoC-2015.

(Previous version refactored to match R-GSoC template)

##### Project title: 
Rethinking DataFrame for Rcpp

##### Project short title (30 characters): 
Rethinking DataFrame

##### URL of project idea page: 
https://github.com/rstats-gsoc/gsoc2015/wiki/Extend-Rcpp

### ==== Bio of Student ====

My name is Meleshko Dmitrii and I'm at master course in bioinformatics Saint-Petersburg Academic University, one of the best Universities in Russia. My professional interests are genome assembly and metagenomics. In bioinformatics problems connected with statistics appears very often and fortunately my two favorite languages now are C++ and R and because of it I've decided to apply for this project.

##### Student name: 
Meleshko Dmitrii

##### Melange Link_id:  
meleshko.dmitrii

##### Student postal address: 
Russia, Saint Petersburg, bl-vd Toreza 37/2

##### Telephone(s): 
+79215838185

##### Email(s): 
dmitrii.meleshko@gmail.com , 1dayac@gmail.com

##### Other communications channels: Skype/Google+, etc. : 
Skype - dmmeleshko

##### Institution: 
St Petersburg Academic University — Nanotechnology Research and Education Centre of the Russian Academy of Sciences (the Academic University)

##### Program: 
Algorithms and data analysis in bioinformatics

##### Stage of completion: 
2nd year of master degree

##### Contact to verify: 
http://www.spbau.ru/main_eng/contacts/list

### ==== Schedule Conflicts: ====

Not any.

##### Mentor names: 
Dirk Eddelbuettel and other RcppCore members

##### Mentor emails: 
edd@debian.org

##### Mentor link_ids: 
https://github.com/eddelbuettel

##### Have you been in touch with the mentors? When and how? 
Yes. Rcpp-github - https://github.com/RcppCore/Rcpp/issues/282

##### Introduction: 
Rcpp contains a class for data.frame objects. Over the years a number of limitations have come up. Some other projects have implemented alternatives: data.table using C, dplyr using C++ on top of Rcpp. This project would scope out and prototype a new DataFrame-alike class for Rcpp.

##### Project goals:
* Design and implement data.frame-alike class for Rcpp which outperforms current solution (time requirements, wider )
* Create add-on package which include all standart components (unit-tests, documentation, vigenettes etc)
* Incorporate implemented class in Rcpp (possiblly)

##### Implementation: 
I'm going to stick the state of art plan declared in "Writing R Extensions" and "R Packages" and use (devtools, RStudio etc.). Before implementation I'm going to explore code of existing solution (data.table, plyr table) and summarize their benefits and limitations. Introducing new data structure into widely used package requires extensive testing stage, possibly I will use RUnit and test that for it.

### ==== TIMELINE ====

Time | Activity
-------|--------
25 or 27 of April (different dates on melange and rstats-gsoc) - 25 of May | Reading and resreshing necessary documentation (Writing R Extensions, Rcpp documentation, work with other packages, communication with R community) 
25 May - 3 July (midterm deadline) | I expect most of coding work to be done to midterm deadline (but I need more discussion to understand what requirements should my work meet)
3 July - 1 August | End of coding and prepare code for distribution as add-on package (and possibly as part of Rcpp)
1-17 August | Writing documentation and testing
17-28 August | Final corrections and wrap-up

July schedule looks sparse, so if something will go wrong - I could catch up all the plans.

### ==== MANAGEMENT OF CODING PROJECT ====

Following "Writing R extensions" in development is best guarantee for code to be tested properly

I will try to commit with small amount of code but often. If I don't comit in 2-3 days something goes wrong. Feel free to contact me.

### ==== TEST ====

https://github.com/RcppCore/Rcpp/issues/129
Simple to fix bug: wrong behaviour of default matrix constructor.

I will be glad to discuss this proposal with you and feel very enthusiastic to work with R community. I understand that my view on project is not very clear but I learn quickly? want project to succeed and hope for your help!

**Comment by eddelbuettel** [comment]
Sorry that we didn't have time to follow up in more detail. The only immediate suggestion I'd have is to use a bit of Markdown formatting here to make it easier to use.  Click eg on [Markdown supported](https://guides.github.com/features/mastering-markdown/) link here.   Otherwise submitting to the Google Melange site is probably a good idea.  It looks like a very strong set of proposals this year.

**Comment by 1dayac** [comment]
Not a problem, I hope we will return to this if I'll be chosen to a program:) I will format it in short time

**Comment by 1dayac** [comment]
Anyway, can I have more precise information about limitations of existing dataframes and what capabilities should have Rcpp-alike data.table and which of them are crucial?
Thank you for your answer!
