### ISSUE TITLE
data precision

### ISSUE THREAD

**Issue by FraDiavolo7** [RcppCore/Rcpp#283]
We use libraries RInside and Rcpp to run an R code through a customized executable.

We are facing a data precision problem: it does not give exactly the same results directly in R and with our executable.
Does anybody know where is the difference coming from, considering that only R does numerical treatment ?
Is there a mean to set data precision ?

We are with R3.1.2 x64 under windows 7.

Details of the problem:
The R code to run is very simple, reads and writes a data file doing a simple transformation:

demo = function(input_filepath,output_filepath,var1,var2){
  #Read data
    Y=read.csv(input_filepath, header=F, sep=",")
  #Transform data
    Y.new =  (Y+var2)*var1
  #Write result in a file
    write.table(Y.new,file = output_filepath,row.names = F,col.names = F,sep=",",dec=".")
}

For the 10 first values of the output file we get :
1) values in R: 0.3,0.286,0.0326,20000.02,0.02001146,20000.02,0.02000000382,0.01999999314,0.02000000228,0.0199999939
2) values in demo.exe: 0.299999999552965,0.285999999552965,0.0325999995529652,20000.0199999996,0.0200114595529652,20000.0199999996,0.0200000033729652,0.0199999926929652,0.0200000018329652,0.0199999934529652

I hope my questions are clear enough.
Thank you for your help

**Comment by thirdwing** [comment]
I think it is much better to provide your data file and code, so we can reproduce the results.

**Comment by eddelbuettel** [comment]
Seconded.  This issue is not providing _a mininmally reproducible example_.   My first guess would be that you may be having `int` versus `double` issues at the C++ side but we can't give you any help here--unless you show code.

**Comment by kevinushey** [comment]
I'm guessing that they're the same -- you need to set the precision when printing within R as `options(digits = 22)` to confirm.

**Comment by eddelbuettel** [comment]
Ah, yes, that too -- it's a basic R FAQ.  Displayed precision != internal precision.  

Also, formatting the quesiton helps. See [this link](https://guides.github.com/features/mastering-markdown/) among many other sources.

**Comment by FraDiavolo7** [comment]
We have found the problem and solution. 
As you mentioned we had the var1 and var2  parameters typed as float and not double.
Setting double give us exactly same results in R and c++.
Thank you for your remarks

**Comment by eddelbuettel** [comment]
Very good, and glad you helped yourself.   For future reference, my preferred approach for request for help is 

+ email to rcpp-devel (where you need to subscribe to post); it will expose your question to the largest number of readers
+ post here
+ post on StackOverflow

**Comment by FraDiavolo7** [comment]
OK thank you I will try to do it next time. Thank you
