### ISSUE TITLE
Rcpp::format or similar?

### ISSUE THREAD

**Issue by hadley** [RcppCore/Rcpp#284]
Now that I understand how tinyformat works, I often find myself doing:

```cpp
tfm::format(Rcpp::Rcout, "%i x %i\n", i, j);
```

instead of 

```cpp
Rcpp::Rcout << i << " x " << j << "\n";
```

Could we have an alias for this pattern in the style of `Rcpp::warning()` and `Rcpp::error()`?

**Comment by romainfrancois** [comment]
How is this not `Rprintf` ?

**Comment by hadley** [comment]
Oh good point!
