### ISSUE TITLE
"Error in loadNamespace" after upgrade to 0.11.6

### ISSUE THREAD

**Issue by katrinleinweber** [RcppCore/Rcpp#295]
```
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  es gibt kein Paket namens (there is no packet called) ‘Rcpp’
```
may be related to #113 

This happens upon execution of `library(ggplot)`, `library(reshape2)` and some others in [RStudio 0.98.1103](http://www.rstudio.com/products/rstudio/download/) with [R 3.2.0](http://cran.rstudio.com/bin/windows/base/) on Win7x64 with the locale `locale: German_Germany.1252`. This definitely started after I let R-Studio upgrade [Rccp to 0.11.6](https://github.com/RcppCore/Rcpp/releases/tag/0.11.6).

**Work-around:** restoring a backup of [0.11.5](https://github.com/RcppCore/Rcpp/releases/tag/0.11.5) to `C:\Program Files\R\R-3.2.0\library\Rcpp`.

Please let me know if you need me to provide more details, or test another work-around.

**Comment by eddelbuettel** [comment]
Please install from source if your mirror has not mirror, or else file a bug report with RStudio (and two of their finest engineers read here too so you have their attention).

But note that [the RStudio CRAN mirror has a Rcpp 0.11.6 package for R-release](http://cran.rstudio.com/bin/windows/contrib/3.2/Rcpp_0.11.6.zip) as well as for R-devel and R-oldrel so methinks you are doing something wrong.

Lastly, the combination of R, RStudio, and ggplot is not all that uncommon and it has not been an error for anybody else...

**Comment by katrinleinweber** [comment]
OK, thanks for the advice and link :-) Works now.

**Comment by eddelbuettel** [comment]
So for posterity ... what was the issue?   I just took 10 mins out to update the R installation on my Windows computer (which I use only to connect to _real computers_ ;-) ) and of course everything installs fine fine here too:

```{.R}
R> install.packages("Rcpp")
Installing package into ‘c:/opt/R-library’
(as ‘lib’ is unspecified)
trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.2/Rcpp_0.11.6.zip'
Content type 'application/zip' length 3173712 bytes (3.0 MB)
downloaded 3.0 MB

package ‘Rcpp’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\deddelbuettel\AppData\Local\Temp\Rtmp4aoqar\downloaded_packages
R> IP <- installed.packages()
R> IP[ IP[,"Package"] %in% c("ggplot2", "Rcpp"), 1:3]
        Package   LibPath            Version 
ggplot2 "ggplot2" "c:/opt/R-library" "1.0.1" 
Rcpp    "Rcpp"    "c:/opt/R-library" "0.11.6"
R> 
```

**Comment by katrinleinweber** [comment]
The Rcpp directory I mentioned above was empty, except for `\libs\x64\Rcpp.dll`. Maybe an extraction error by RStudio during a larger update (maybe 10 or 12 packages). I noticed smaller problems with that already and will test more thoroughly before filing a bug report, if those should occur again ;-)

**Comment by eddelbuettel** [comment]
Yes, that is windows for you.  You probably upgraded while the package was loaded, and it would be too much to expect that in 2015 you could replace a package currently loaded.   <facepalm>

Oh well. Live and learn.  

Beste Gruesse,  Dirk

**Comment by mtsde** [comment]
I can confirm this: encountered the same error while loading Rcpp / ggplot2. Turns out I had upgraded Rcpp a few minutes before while Rcpp was still loaded in another instance of RStudio. Rcpp folder was empty save for the one dll mentioned above. Closing the other instance and installing Rcpp again helped.

**Comment by eddelbuettel** [comment]
Folks, that is a *windows* problem aggravated by the implicit notion that the devtools can updates anything anywhere. Which, for what it is worth, never subscribed too nor promoted.

So in short, if you upgrades fail, do them outside of a running R session, ideally an empty one.
