### ISSUE TITLE
tests for automatically generated math functions

### ISSUE THREAD

**Issue by romainfrancois** [RcppCore/Rcpp#30]
new autogenerated sugar functions: cos, acosh, atan, cos, cosh, log, 
	log10, sqrt, sin, sinh, tan, tanh

**Comment by coatless** [comment]
Unless I am missing the meaning behind this issue, I believe that unit tests are already in place for the sugar math functions. These unit tests were added in 9d2c671ca6f3f7480249f02ae06624452fb02f8d.

I think this was related to the change over from `SUGAR_MATH_1` to `VECTOR_MATH` in commit id 85fb11610701b8a2e88eaf6b437c829c3dfc20eb . 

Please close? Or provide clarity behind the intent. (Tagging #506)
