### ISSUE TITLE
Removing the 2GB Limit in Vectors

### ISSUE THREAD

**Issue by etduwx** [RcppCore/Rcpp#302]
Hello again from the HP Distributed R Team. (Thanks again for your quick response and addressing of issue https://github.com/RcppCore/Rcpp/issues/264; the speed and professionalism were appreciated).

In some of our internal and consumer-facing use cases, some large amounts of data need to be serialized and passed from the master node to the worker node(s). These variables exist first in the master node's environment, but in sending the tasks to the worker(s), we first convert each into a `RawVector`:

```
Rcpp::List raw_vals_list = raw_vals_vec[k];
Rcpp::RawVector raw_value = raw_vals_list[i % raw_vals_list.size()];
```

In this case, `raw_vals_vec` is an `Rcpp::List` (a list of lists) that contains the variables in the master's R environment that need to be sent to each worker node.

We notice that when `raw_value` refers to an object of size greater than 2GB, `raw_value.size()` raises the error, `long vectors not supported yet: ../../src/include/Rinlinedfuns.h:137`.

It appears that `size()` invokes `Rf_length()`, which, upon examination of `Rinternals.h`, ends up at this macro,

```
# define LENGTH(x) (IS_LONG_VEC(x) ? R_BadLongVector(x, __FILE__, __LINE__) : SHORT_VEC_LENGTH(x))
```

where `R_BadLongVector` triggers due to the size of the vector. It seems that `Rf_xlength()` is the version to call for long vectors.

Additionally, several of the constructors in `Vector.h` use `int` for size, so it appears that the class was written with a 2GB limit in mind.

We realize that the reason for this is due to a 2^31-1 limitation in pre-3.0 R; now that the limit has increased, are there plans for adapting Rcpp to accommodate larger vectors? 

Let us know; we'll be happy to discuss.

Thanks.

**Comment by thirdwing** [comment]
Hi, believe it or not. This is exactly what I am working on right now.

In [my fork](https://github.com/thirdwing/Rcpp), the `R_xlen_t` and `Rf_xlength` are used just as you suggest.

Right now I am checking all packages depend on `Rcpp`, since we don't want to break any existing packages.

**Comment by eddelbuettel** [comment]
Three cheers to @thirdwing to actually starting to work on this (which he and I had discussed in the past as a possibility, but _all_ the work on this is his) and for @etduwx et al at HP/Vertica for raising the issue.

I think this is well on its path. With some luck, @thirdwing can get some if not most or even all  tests passed.  

But please do reach out for help if you think you could use as there seem to be others (at HP and elsewhere) willing to help.

**Comment by etduwx** [comment]
Thanks, @thirdwing and @eddelbuettel . These changes will be very useful. Let us know if we can assist in the efforts.

**Comment by thirdwing** [comment]
The check of 388 packages is done this morning, and four packages have some problems.

* `brms` depends on `rstan`, which is not available on CRAN

* `rlme` can pass `R CMD check`, but not because `Rcpp`. http://cran.r-project.org/web/checks/check_results_rlme.html

* `surveillance` depends on `INLA`, which is not available on CRAN

* `RProtoBuf` failed on [one test](https://github.com/eddelbuettel/rprotobuf/blob/master/inst/unitTests/runit.addressbook.R#L52), but it failed on my machine using the original `Rcpp`.

**Comment by eddelbuettel** [comment]
That is almost better than what I usually get when I run before releases (and log in [this repo](https://github.com/RcppCore/rcpp-logs)).

As for these four:  the first three don't ring a bell; but RProtoBuf tickles a known bug in R 3.2.0 on i386 only.  It should pass fine on a 64-bit OS.

So I'd say you are ready for a pull request!

**Comment by thirdwing** [comment]
Let me set up a clean machine and check again.

**Comment by eddelbuettel** [comment]
Also, in case you only have i386, R-patched should avoid the RProtoBuf issue.

**Comment by thirdwing** [comment]
`RProtoBuf` passed `R CMD check` on Travis, so there might be something wrong on my machine.

**Comment by eddelbuettel** [comment]
As I said, there is a known issue tickled on 32 bit Linux which does not appear on 64 bit.

The most obvious explanation would be that your machine is 32 bit ...

**Comment by thirdwing** [comment]
So we can say it doesn't break any existing packages now.

And @etduwx , can you try my [fork](https://github.com/thirdwing/Rcpp) on the real world problem you are working on? It will provide really good testing cases. If it works, I will send the PR.

**Comment by etduwx** [comment]
Hi @thirdwing ,

Sure, we'll give it a try and let you know how it goes; thanks.

**Comment by kevinushey** [comment]
Would you be willing to submit a PR now? We might not merge right away but
it would be good to get it ready + begin a code review.

**Comment by eddelbuettel** [comment]
:+1:  -- I also see that you are both a few commits ahead (obviously, all the work) and behind.  So maybe we should work on getting your fork and subsequent work a little closer to mainline.  A PR may be a good first step.

**Comment by eddelbuettel** [comment]
I let it run overnight, this just finished -- I got '365 good, 25 bad' and I just [committed the log](https://github.com/RcppCore/rcpp-logs/commit/76c88fe0fe6ba0b63bfd28fc4f0862442d25b474) to the rcpp-logs repo.  

I'll look at the bad cases in more detail; these may not all be due the PR.  This may be the first test I ran since upgrading to Ubuntu 15.04; when I glanced at one or two errors last night they seems more compiler-related.

**Comment by eddelbuettel** [comment]
I started to look into the 25 failures, and we explain _a lot_ of these away:

- I seem to have had RcppEigen installed via R-devel with a bad/wrong LAPACK, my bad
- My test script does not install Suggests: so a lot fail
- Some have upstream setup bugs [eg dplyr (hi @hadley) requires Suggests: packages for tests]

Also, my test setup directory was empty following a reboot so a few packages I had added by hand are missing. I'll report back later but the work day gets in the way now...

**Comment by etduwx** [comment]
@thirdwing ,

I didn't test every case, but it seems to work just fine on our end. Good job!

**Comment by eddelbuettel** [comment]
Same here. I was mostly dealing with issues related to how the tests are set up, and occasional oddities such as some (known) packages failing for no good reason once in a while with low probability.

**Comment by etduwx** [comment]
Hi again,

How does the schedule of the integration of this feature look? Will it be included in 0.11.7?

Thanks.

**Comment by eddelbuettel** [comment]
Yes, as it has been merged.  Just checkout from the master branch and you should be good to go.  We have run several reverse-dependency checks, including one just today against a rev.deps of RcppArmadillo.

**Comment by etduwx** [comment]
Thanks! Any comment on when 0.11.7 will be official?

**Comment by eddelbuettel** [comment]
"When it's ready" :)   Sorry, but we don't have public timelines. A few weeks ago I would have said early/mid-July but we're still keeping busy.

And if it is urgent, the current master branch should be fine though.

**Comment by eddelbuettel** [comment]
Rcpp 0.12.0 is now on CRAN.  We decide on a new 0.12.* series rather than 0.11.7.

**Comment by etduwx** [comment]
Thanks for the update, Dirk! Let us give it a shot, will let you know if everything's peachy. (Don't see why it won't :) ).

**Comment by eddelbuettel** [comment]
As with many things in life, we may not be completely done. When I tried some trivial and obvious constructors, this still failed   So more polish needed.  But this basic example I added in the announcement blog post is real:

```r
R> library(Rcpp)
R> big <- 2^31-1
R> bigM <- rep(NA, big)
R> bigM2 <- c(bigM, bigM)
R> cppFunction("double getSz(LogicalVector x) { return x.length(); }")
R> getSz(bigM)
[1] 2147483647
R> getSz(bigM2)
[1] 4294967294
R>
```
