### ISSUE TITLE
github install fails on Windows 64

### ISSUE THREAD

**Issue by mplourde** [RcppCore/Rcpp#307]
When installing with `devtools::install_github("RcppCore/Rcpp")`, I receive the following error:

    * checking for file 'C:\temp\Rtmp08yoMJ\devtools28ec78163e4\Rcpp-master/DESCRIPTION' ... OK
    * preparing 'Rcpp':
    * checking DESCRIPTION meta-information ... OK
    * cleaning src
    * installing the package to process help pages
    Warning: running command '"C:/PROGRA~1/R/R-32~1.0/bin/i386/Rcmd.exe" INSTALL -l "C:\temp\Rtmpgt2ozY\Rinst2f5826283701" --no-multiarch "C:/temp/Rtmpgt2ozY/Rbuild2f5857ba3005/Rcpp"' had status 1
          -----------------------------------
    * installing *source* package 'Rcpp' ...
    ** libs
    g++ -m32 -I"C:/PROGRA~1/R/R-32~1.0/include" -DNDEBUG -I../inst/include/    -I"d:/RCompile/r-compiling/local/local320/include"     -O2 -Wall  -mtune=core2 -c Date.cpp -o Date.o
    In file included from /usr/lib/gcc/x86_64-pc-cygwin/4.9.2/include/c++/bits/stl_algo.h:59:0,
                     from /usr/lib/gcc/x86_64-pc-cygwin/4.9.2/include/c++/algorithm:62,
                     from ../inst/include/RcppCommon.h:62,
                     from ../inst/include/Rcpp.h:27,
                     from Date.cpp:31:
    /usr/lib/gcc/x86_64-pc-cygwin/4.9.2/include/c++/cstdlib:178:10: error: expected unqualified-id before '__int128'
       inline __int128
              ^
    In file included from ../inst/include/RcppCommon.h:64:0,
                     from ../inst/include/Rcpp.h:27,
                     from Date.cpp:31:
    /usr/lib/gcc/x86_64-pc-cygwin/4.9.2/include/c++/limits:1405:35: error: template argument 1 is invalid
         struct numeric_limits<__int128>
                                       ^
    /usr/lib/gcc/x86_64-pc-cygwin/4.9.2/include/c++/limits:1479:44: error: template argument 1 is invalid
         struct numeric_limits<unsigned __int128>
                                                ^
    Date.cpp: In function 'int Rcpp::differ_by_repeat(time_t, time_t)':
    Date.cpp:114:54: warning: integer overflow in expression [-Woverflow]
     #define SECSPERREPEAT ((int_fast64_t) YEARSPERREPEAT * (int_fast64_t) AVGSECSPERYEAR)
                                                          ^
    Date.cpp:423:48: note: in expansion of macro 'SECSPERREPEAT'
      return (int_fast64_t)t1 - (int_fast64_t)t0 == SECSPERREPEAT;
                                                    ^
    C:/PROGRA~1/R/R-32~1.0/etc/i386/Makeconf:189: recipe for target 'Date.o' failed
    make: *** [Date.o] Error 1
    Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-32~1.0/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-32~1.0/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="Rcpp.dll" OBJECTS="Date.o Module.o Rcpp_init.o api.o attributes.o barrier.o"' had status 2
    ERROR: compilation failed for package 'Rcpp'
    * removing 'C:/temp/Rtmpgt2ozY/Rinst2f5826283701/Rcpp'
          -----------------------------------
    ERROR: package installation failed
    Error: Command failed (1)

With the following traceback:

     1: devtools::install_github("RcppCore/Rcpp")
     2: vapply(repo, install_github_single, FUN.VALUE = logical(1), username, ref, pull, subdir, branch, auth_user, password, auth_token, ..., dependencies = TRUE)
     3: FUN(X[[i]], ...)
     4: install_url(conn$url, subdir = conn$subdir, config = conn$auth, before_install = github_before_install, ...)
     5: mapply(install_url_single, url, name, MoreArgs = list(subdir = subdir, config = config, before_install = before_install, ...))
     6: (function (url, name = NULL, subdir = NULL, config = list(), before_install = NULL, ...) 
    {
        if (is.null(name)) {
            name <- basename(url)
        }
        message("Downloading ", name, " from ", url)
        bundle <- file.path(tempdir(), name)
        request <- GET(url, config)
        stop_for_status(request)
        writeBin(content(request), bundle)
        on.exit(unlink(bundle), add = TRUE)
        install_local_single(bundle, subd
     7: install_local_single(bundle, subdir = subdir, before_install = before_install, ...)
     8: install(pkg_path, quiet = quiet, ...)
     9: build(pkg, tempdir(), vignettes = build_vignettes, quiet = quiet)
    10: with_libpaths(c(tempdir(), .libPaths()), R(cmd, path, quiet = quiet))
    11: force(code)
    12: R(cmd, path, quiet = quiet)
    13: in_dir(path, system_check(r_path, options, c(r_env_vars(), env_vars), ...))
    14: force(code)
    15: system_check(r_path, options, c(r_env_vars(), env_vars), ...)

My session info is as follows:

   R version 3.2.0 (2015-04-16)
   Platform: i386-w64-mingw32/i386 (32-bit)
   Running under: Windows 7 x64 (build 7601) Service Pack 1

**Comment by kevinushey** [comment]
You need to build with [Rtools](http://cran.r-project.org/bin/windows/Rtools/) on Windows.

**Comment by mplourde** [comment]
Hey, Kevin. Thanks for the quick response.

**Comment by eddelbuettel** [comment]
We have some hints about what is needed in the (appropriately titled) [Rcpp FAQ](http://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-FAQ.pdf).  Let us know if pertinent information is unclear or missing.
