### ISSUE TITLE
Error messaging suggestion

### ISSUE THREAD

**Issue by jrowen** [RcppCore/Rcpp#308]
This is a nice-to-have suggestion for those of us having less C++ experience and currently using older environments (like RHEL6).  When there is a problem compiling a package, could the error messaging be enhanced to check the compiler version and let the user know when he/she may be using an older, unsupported version of the compiler?  This info could save a lot of debugging/Google time.

This suggestion was inspired by [this issue](https://github.com/Rblp/Rblpapi/issues/39).

**Comment by eddelbuettel** [comment]
Two answers:

- Yes, and pull requests welcome.  We already [test different compilers](https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/platform/compiler.h#L28-L40) and you could hook into [the next block there](https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/platform/compiler.h#L46-L59) and at least warn if versions older than 4.6.2 (== oldest known CRAN compiler) are used.

- No, as Rcpp is eclectic. We don't always use all features, and different projects have different requirements.  With that I think an error would be wrong, but maybe a warning for truly old compilers?  

To be discussed, cc'ing @jjallaire and @kevinushey

**Comment by kevinushey** [comment]
I'd be happy with warning on gcc <= 4.6.2.

**Comment by coatless** [comment]
On this, it seems like a quick fix would be:

```cpp
#pragma message "WARNING: GCC Compiler Version <= 4.6.2"
```

As:
```cpp
#warning "GCC Compiler Version <= 4.6.2"
```
might not be supporte.

In addition, the `#error` directive would kill the compilation.

**Comment by eddelbuettel** [comment]
In the meantime, "systematically most important" dependent package RcppArmadillo added its own checks to fail those with g++ 4.4 and alike.

That said, I _really_ do like what @mattdowle and @arunsrinivasan are doing with data.table and their arch-conservative dependencies ... supporting everything down to R 2.15 which I think was used during Napoleon's reign.  Of course they have it easier with C than we do but still -- avoiding semi-arbitrary boundaries is a good thing. 

In essence, old RHEL systems are at the same time really stupid and still fairly common.  The longer we can accommodate with minimal pain, the better.  (RcppArmadillo has no choice as Armadillo drew a line).

**Comment by coatless** [comment]
@eddelbuettel : 

Per [/inst/include/armadillo_bits/compiler_setup.hpp](https://github.com/RcppCore/RcppArmadillo/blob/cf5dfdf87be33a02632f5fce1aeca871d6daf147/inst/include/armadillo_bits/compiler_setup.hpp#L155-L170).

The proposed `#pragma message` will be aokay?

**Comment by eddelbuettel** [comment]
Yes :cake:

**Comment by coatless** [comment]
Per discussion in PR #515, due to the way RHEL is structured coupled with the fact that Rcpp's code base working with GCC 4.6.2, this will not be fixed. In the event that this changes, the code in PR #515 can be used in the future.

Please close. (Tagging #506)
