### ISSUE TITLE
Thread safety of the random number distributions

### ISSUE THREAD

**Issue by ivan-krukov** [RcppCore/Rcpp#315]
I wanted to know if the `Rcpp`-sugar random number distributions are thread safe. I have observed this behaviour with `Rcpp::rmultinom` and `R::rbinom`.

Here is a contrived example:

```C++
// [[Rcpp::export]]
List variates(int max, double p1, double p2, int n)
{
  vector<int> first;
  vector<int> second;
  #pragma omp parallel for ordered
  for (int i = 0; i < n; i++) {
    int a, b;
    a = R::rbinom(max, p1);
    b = R::rbinom(max, p2);

    #pragma omp ordered
    {
      first.push_back(a);
      second.push_back(b);
    }
  }

  return List::create(
    _["first"] = first,
    _["second"] = second
  );
}
```

Now, if we compile this with `openmp` support, we get the following:
```R
zz <- variates(1000, 0.01, 0.99, 100)
max(zz$first) #981
min(zz$second) #19
```

Alternatively, compiling this without `openmp`, or wrapping `rbinom` calls into `#pragma omp critical`, produces the expected result:

```R
zz <- variates(1000, 0.01, 0.99, 100)
max(zz$first) #21
min(zz$second) #980
```

This may be coming from my misunderstanding of `openmp` at large (sync error?), but this behavior is rather unexpected.

**Comment by jjallaire** [comment]
You basically can't call any of the R API from a background thread
unless you are absolutely certain there are no interactions with the
main thread. Check the docs on OpenMP in Writing R Extensions
(http://cran.rstudio.com/doc/manuals/r-release/R-exts.html#OpenMP-support)
which says:

Calling any of the R API from threaded code is ‘for experts only’:
they will need to read the source code to determine if it is
thread-safe. In particular, code which makes use of the stack-checking
mechanism must not be called from threaded code.

Others can confirm for sure but my guess is that anything which
interacts with the random number generator is strictly off limits in
background threads.

**Comment by eddelbuettel** [comment]
RNGs in particular are a well-studied topic, and CRAN has a few packages for OpenMP and random numbers --  I think I point to them in the [HPC Task View](http://cran.r-project.org/web/views/HighPerformanceComputing.html).

So in short: while everybody loves the RNGs in base R, there is basically no way you can do what you set out here.   We really can only close this as 'known and documented behaviour' -- R really is not re-entrant.

**Comment by ivan-krukov** [comment]
Okay, makes sense. I think it might be useful to add up these caveats to the documentation of Rcpp (I understand this is a core R question, but it could save time).
Thanks for the pointers, too!
