### ISSUE TITLE
Coding Standards note ?

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#317]
Sitting in the [mlr](https://github.com/berndbischl/mlr) tutorial I notice this at the end of the `README.md`

> We also welcome pull requests or new developers. To get started have a look at the guidelines for contributors. Please also consider the mlr coding guidelines.

(with links in the actual `README.md`).   Should we do something similar?

**Comment by jjallaire** [comment]
Github also allows you to create a file called CONTRIBUTING.md which users
will then be shown a link to whenever they open a PR or submit a new issue:

https://github.com/blog/1184-contributing-guidelines



On Tue, Jun 30, 2015 at 1:48 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by eddelbuettel** [comment]
Nice.  

So should we add this?   Do we need it blessed by a legal eagle, or do we still get by with good old common sense?

**Comment by jjallaire** [comment]
No I think common sense is fine. We don't ask for contributor agreements
however we could make the statement that the package is all licensed under
the GPL-2 so all contributions made are under that license.

On Tue, Jun 30, 2015 at 1:55 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by MattPD** [comment]
Hi!

Just in case anyone would happen to be interested in the references (without taking sides), I've personally found these useful:
- http://www.codingstandard.com/section/references/
- http://www.boost.org/development/requirements.html
- https://svn.boost.org/trac/boost/wiki/BestPracticeHandbook
Perhaps a pass-by-reference link (or links) would be an idea?

Come to think of it, the last one just reminded me of something I've missed before:
https://svn.boost.org/trac/boost/wiki/BestPracticeHandbook#a11.PORTABILITY:Considernotdoingcompilerfeaturedetectionyourself

In particular, the _standalone_ aspect -- if I understood it correctly ("You can therefore if you really want use the Boost feature detection macros instead, even without Boost being present.") sounds rather appealing in this context:
https://github.com/ned14/Boost.APIBind/blob/master/include/cpp_feature.h
https://github.com/ned14/Boost.APIBind/blob/master/include/boost/config.hpp

In any case, it may be hard to adapt an existing style guide, each and every project has its own specifics.
That being said, POCO C++ Libraries happen to have a pretty neat Coding Style Guide which -- possibly important in this context -- is licensed under the Creative Commons Attribution 3.0 Unported License:
http://www.appinf.com/download/CppCodingStyleGuide.pdf
https://github.com/pocoproject/poco/blob/develop/doc/CppCodingStyleGuide.doc

Some of the sections are pretty general good advice:
1 Introduction
3 General Recommendations

If anything, Rule 1 sounds like a potentially nice way to capture the desire for "existing/established common sense" (which can be sometimes not as common as we'd hope for in a perfect world...):
"If this style guide leaves anything unclear, see how it has been done in the existing code base and do it accordingly."
// Perhaps this one is good enough of a statement for "CONTRIBUTING.md"? ;-)

Similarly, Rule 58 and Rule 59 are another examples.
Another nice guide (IMHO) is that of CERT C++ with advice applicable not-just-for-security -- e.g., (note the overlap w/ Rule 60 in the POCO Style Guide):
https://www.securecoding.cert.org/confluence/display/cplusplus/DCL07-CPP.+Minimize+the+scope+of+variables+and+methods

Just thinking out loud, no strong feelings either way.
// Probably worth remembering in either case: http://www.gotw.ca/publications/c++cs.htm -- "0. Don’t sweat the small stuff. (Or: Know what not to standardize.)" ;-)
// Well, OK, looking at this again, I have to admit I _really_ like Item 15, "Use `const` proactively." This one can really, really help when reading someone else's code.

**Comment by eddelbuettel** [comment]
I always liked the short-and-sweet [QuantLib Style page](http://quantlib.org/style.shtml) and agree with most (but not all) of the recommendations.

But I don't want to turn this into bikeshedding, and let's keep post below dissertation length.  Nobody but Matt reads all these links :)

**Comment by MattPD** [comment]
@eddelbuettel: Sure, good point on brevity! ;-)

**Comment by thirdwing** [comment]
Just for contributors like me, coding style is not that important.

It will be great if the team can keep issue list and TODO updated, so we know where to begin.

**Comment by eddelbuettel** [comment]
Not everybody is a diligent as you :)  

I plan to add something.

**Comment by coatless** [comment]
To Do: Add QuantLib Style page to [`Contributing.md`](https://github.com/RcppCore/Rcpp/blob/master/Contributing.md)

Needs documentation flag as well.

**Comment by coatless** [comment]
Preliminary listing of suggested coding style guide is on the wiki:

https://github.com/RcppCore/Rcpp/wiki/Rcpp-Coding-Guidelines

**Comment by eddelbuettel** [comment]
It has a bit of a weird mix between two and four space indentation around `public` and `private`. I think we should either nail one down (and we have, I supposed, via the clang-format contributed by @kevinushey even though I mostly ignore that and just let Emacs deal with it).

Stepping back a little I don't even think we have full consensus on two versus four :)

Also, I do not know how well the wiki here works. I tend to think it is completely ignored so I was planning to just add a paragraph to [Contributing.md](https://github.com/RcppCore/Rcpp/blob/master/Contributing.md).

**Comment by coatless** [comment]
@eddelbuettel  On the later note, I think the wiki would be slightly more ideal vs. contributing especially if you link out to the coding standards. Otherwise, I have an odd feeling that the simplicity of the `Contributing.md` will get a bit messy. Also, the proposed use of the wiki mimics that of the above `mlr` example. See [mlr coding guidelines](https://github.com/mlr-org/mlr/wiki/mlr-Coding-Guidelines) on their wiki.

**Comment by eddelbuettel** [comment]
Agreed.  The `data.table` package also makes good use of the wiki.  So thumbs up.

**Comment by coatless** [comment]
Misc note: 

PR #318 contained the suggested official Rcpp code style.
