### ISSUE TITLE
Element initialization of armadillo does not work with a rcpp attributes

### ISSUE THREAD

**Issue by innir** [RcppCore/Rcpp#325]
Hi,
when I use [element initialization](http://arma.sourceforge.net/docs.html#element_initialisation) of a matrix with armadillo I get the following error

R> library(Rcpp)
R> sourceCpp("/tmp/test.cpp")
1: In sourceCpp("/tm/test.cpp") : No function found for Rcpp::export attribute at test.cpp:6
2: In sourceCpp("/tmp/test.cpp") : No Rcpp::export attributes or RCPP_MODULE declarations found in source

Where /tmp/test.cpp is

```c++
// [[Rcpp::depends(RcppArmadillo)]]
#include <RcppArmadillo.h>
using namespace Rcpp;

// [[Rcpp::plugins("cpp11")]]
// [[Rcpp::export]]
double arma_init(arma::mat dummy={{0,-1,0}, {0,0,0}, {0,0,0}}) {
    return arma::accu(dummy);
}
```

Do you plan to support this? or do I just have to use some R code to be able to set the default values?

Best,
Philip

**Comment by eddelbuettel** [comment]
Yes, you will have to set the default values
- either in R
- or in the function body

That is one of the small costs we have to pay for _Rcpp Attributes_: The function signature gets parsed by us, and we are not a C++(11) interpreter.   Maybe one day, but not for now.

**Comment by innir** [comment]
OK, thanks for the quick feedback
