### ISSUE TITLE
Environment::(get,find)( Symbol )

### ISSUE THREAD

**Issue by romainfrancois** [RcppCore/Rcpp#326]
Currently the `get` and `find` members only take `std::string` : 

```
SEXP find( const std::string& name) const ;
SEXP get(const std::string& name) const ;
```

What they do with the `string` is that they first make a symbol, with `install` and then they call the relevant `C/R API` function, i.e. `Rf_findVarInFrame` or `Rf_findVar`. 

But sometimes, we already have a symbol and perhaps don't want to pay for the double cost of:
 - converting that symbol to a `std::string` 
 - let `get` or `find` reconvert it to a symbol

The alternative being calling `C/R API` directly. 

So can we have: 

```
SEXP find( Symbol name) const ;
SEXP get( Symbol name) const ;
```

This is straightforward, and I'll probably submit a PR anyway, but since I don't have time right now, I'm just logging the need and intent here.

**Comment by coatless** [comment]
Addition of the Symbol option has been addressed in PR #513 

And via GitHub magic, this issue has been closed.

Though... I still need to do (Tagging #506)
