### ISSUE TITLE
Fails to compile on Yosemite with Homebrew’s clang++

### ISSUE THREAD

**Issue by klmr** [RcppCore/Rcpp#328]
I’m trying to install Rcpp on Yosemite and R 3.1.2 from source (via `install_github`). This fails with the following error message.

```
* installing *source* package ‘Rcpp’ ...
** libs
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I../inst/include/ -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c Date.cpp -o Date.o
In file included from Date.cpp:31:
In file included from ../inst/include/Rcpp.h:80:
In file included from ../inst/include/Rcpp/api/meat/meat.h:25:
../inst/include/Rcpp/api/meat/Rcpp_eval.h:54:13: error: use of undeclared identifier 'CDDDR'
    SET_TAG(CDDDR(call), ::Rf_install("interrupt"));
            ^
1 error generated.
make: *** [Date.o] Error 1
ERROR: compilation failed for package ‘Rcpp’
```

I don’t know what this error is due to (and searching didn’t turn up much) but it occurs to me that the clang++ command line looks wrong:

My system uses [Homebrew’s clang++](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/llvm.rb) (LLVM 3.6.1). In order to use clang++ with this installation, it needs to get passed the following command line arguments, according to the Homebrew installation.

```bash
clang++-3.4 -stdlib=libc++ -nostdinc++ -isystem /usr/local/lib/llvm-3.4/include/c++/v1
```

My environment variables `$CXX` and `$CXXFLAGS` are set accordingly, so a Makefile using these variables will work. However, the output from the Rcpp installation above indicates that this isn’t happening here.

```r
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] devtools_1.7.0.9000 httr_0.5            magrittr_1.5
[4] RCurl_1.95-4.3      stringi_0.5-1       stringr_1.0.0
[7] tools_3.1.2
```

**Comment by eddelbuettel** [comment]
I do not own an OS X machine but from what I recall about the _general_ recommendation for R on OS X involves avoiding homebrew and sticking with [what Simon provides](http://r.research.att.com/).

I try to keep the relevant information for this current in eg [the Rcpp FAQ](https://cran.rstudio.com/web/packages/Rcpp/vignettes/Rcpp-FAQ.pdf). If any of the information therein needs updated, please get in touch.

Otherwise, I fear you may be left out in the cold by using an unsupported toolchain.   I'll CC my fellow OS X users @jjallaire and @kevinushey in case I wandered too far off the reservation here...

**Comment by eddelbuettel** [comment]
> My environment variables $CXX and $CXXFLAGS are set accordingly

Do you know about `~/.R/Makeconf`  ?

**Comment by klmr** [comment]
> Do you know about `~/.R/Makeconf` ?

I didn’t. However, I just realised that I do have an (outdated) `~/.R/Makevars`. I’ve not updated this to match, and R is now using the correct clang++ invocation. However, this does not change the error, unfortunately.

I’ve tried searching for the identifier that the error message complains about, `CDDDR`. It is in fact defined nowhere in the Rcpp source, and in my version of `Rinternals.h` (i.e. the one shipping with R 3.1.2) it’s also not yet defined (though it is in the r-source trunk). Does this mean that the current Rcpp master (from 8 days ago, 454de74f579582c7e53d93fde3708b46d596d0cc) cannot be compiled with R 3.1.2 yet? I’ll try upgrading and see what happens …

> by your own choice of relying an unsupported toolchain

True, but it’s a widely recommended / the de facto default toolchain for professional software development on Mac — so it’s hardly arcane.

**Comment by eddelbuettel** [comment]
No, I have current Rcpp with current R -- as well as with previous R versions as we occasionally a little conservative with the servers at work.

**Comment by klmr** [comment]
Well, after an upgrade to R 3.2.1 it worked.

**Comment by kevinushey** [comment]
Yes, the issue here is simple: R 3.2.1 has `CDDDR`; R 3.1.2 doesn't.

We should probably avoid using `CDDDR` to ensure `Rcpp` can compile with older versions of R.

**Comment by eddelbuettel** [comment]
Or we add the proper Depends:.  Making do without `CDDDR` is probably better ....  Volunteers?  ;-)

**Comment by kevinushey** [comment]
Just committed to master: https://github.com/RcppCore/Rcpp/commit/ac11e78feac1194000829f01e1f45152aa235777

**Comment by eddelbuettel** [comment]
:+1:
