### ISSUE TITLE
64 bit integers

### ISSUE THREAD

**Issue by romainfrancois** [RcppCore/Rcpp#33]
From Murray: 

A vector of 64-bit integers in C++ code should be either returned as

1) An integer vector (if all values are < INT_MAX in the C code) corresponding to R's integer type.

2) A numeric vector (if all values are < 1L << 53 such that they can be stored precisely in a double without losing any digits of precision) corresponding to R's numeric type.

3) A vector of strings (if at least 1 value > 1L << 53 such that returning a numeric would lose precision in the result. e.g. 64-bit fingerprints, userids, network addresses or other things can not be stored in a numeric accurately.

Sorry no patch, I work around this in my application code currently before calling Rcpp::wrap().

**Comment by dselivanov** [comment]
Just want to put here [related rcpp-devel discussion](http://lists.r-forge.r-project.org/pipermail/rcpp-devel/2017-July/009650.html) (I think could be someone looking how to use `bit64` with `Rcpp`). Mb worth to put method described by @kevinushey to Rcpp FAQ.
```c++
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
NumericVector timesTwo(NumericVector input) {

  R_xlen_t n = input.size();
  NumericVector output = no_init(n);

  long long* pInput  = (long long*) dataptr(input);
  long long* pOutput = (long long*) dataptr(output);
  for (R_xlen_t i = 0; i < n; i++)
    *pOutput++ = *pInput++ * 2;

  output.attr("class") = "integer64";
  return output;
}

/*** R
library(bit64)
object <- as.integer64(1:16)
timesTwo(object)
*/
```
