### ISSUE TITLE
Rcpp fails to compile on Windows 10

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/Rcpp#336]
The error, from `R CMD INSTALL` (called within an RStudio session):

```
g++ -m32 -I"C:/R/R-32~1.0PA/include" -DNDEBUG -I../inst/include/    -I"d:/RCompile/r-compiling/local/local320/include"     -g -O3 -Wall -pedantic -std=c++0x -c api.cpp -o api.o
api.cpp:40:30: fatal error: execinfo.h: No such file or directory
compilation terminated.
```

It looks like [this line](https://github.com/RcppCore/Rcpp/blob/d6803468fa50da1a9f3c770054afc8941968ae0c/src/api.cpp#L37) is not properly filtering out Windows 10; likely because `WIN32` is not sufficient (we should try `_WIN32` instead).

**Comment by eddelbuettel** [comment]
[Interesting read] that makes you think it should never have worked with `WIN32` ...
