### ISSUE TITLE
2GB limit on vectors, error in sparsematrix

### ISSUE THREAD

**Issue by subsriram** [RcppCore/Rcpp#337]
I am creating a sparse matrix using vectors longer than 2^31 elements. See code below:

library(Matrix)
sz=2^31+10000
a=sample.int(15000000,size=sz,replace=TRUE)
b=sample.int(25000,size=sz,replace=TRUE)
c=sparseMatrix(a,b)

This gives me the error:

Error in validityMethod(as(object, superClass)) : 
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:137

I have used the latest Rcpp version. Not sure what other dependencies maybe causing this issue.

**Comment by eddelbuettel** [comment]
Well, `sparseMatrix()`, which you call here, is a function of the Matrix package.  Maybe it needs an update, maybe some converter needsan update.  There is nothing _immediate_ for us to do here in Rcpp.

**Comment by subsriram** [comment]
Thanks Dirk. I will post a similar question on the matrix package.

Would you have any tips on how I can get around this issue?

On Thu, Aug 6, 2015 at 12:47 PM, Dirk Eddelbuettel <notifications@github.com
> wrote:

> Well, sparseMatrix(), which you call here, is a function of the Matrix
> package. Maybe it needs an update, maybe some converter needsan update.
> There is nothing *immediate* for us to do here in Rcpp.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RcppCore/Rcpp/issues/337#issuecomment-128437599>.
>



-- 
Sriram Subramanian, Ph.D.
Principal
Lighthouse Datalab LLC

**Comment by eddelbuettel** [comment]
No, I do not.  This may need some diligent chasing down several packages.  At least we now the basics in Rcpp via `R_xlen_t` thanks to @thirdwing .   Expanded to actual use cases could require more testing.  Maybe you can contribute some patches / pull requests...

**Comment by eddelbuettel** [comment]
Also, your vectors `a` and `b` are each of size `sz` of around 2 billion.  So the matrix would still have `a * b` elements, which at four bytes for integer comes out as about 1.8e19 elements.  Did you really mean that?

**Comment by subsriram** [comment]
Dirk

The matrix would be 15million x 25k elements - about 375 billion elements

3.75e12

Sriram


On Aug 6, 2015, at 1:29 PM, Dirk Eddelbuettel <notifications@github.com>
wrote:

Also, your vectors a and b are each of size sz of around 2 billion. So the
matrix would still have a * b elements, which at four bytes for integer
comes out as about 1.8e19 elements. Did you really mean that?

—
Reply to this email directly or view it on GitHub
<https://github.com/RcppCore/Rcpp/issues/337#issuecomment-128451539>.

**Comment by eddelbuettel** [comment]
Right. I was (once again) fooled by `sample(x, size)` and `sample.int(n, size)`. My bad.

**Comment by subsriram** [comment]
Thanks for your prompt response, Dirk. I am looking at options (editing the
code or setting up the matrix in a different way). I have a large matrix
with more than 2^31 non zero elements that I need to run SVD on. If you
come across anything relevant, please let me know.

An aside, I just looked through your website, and it is very interesting -
thanks for posting all the material!

Sriram

On Thu, Aug 6, 2015 at 2:59 PM, Dirk Eddelbuettel <notifications@github.com>
wrote:

> Right. I was (once again) fooled by sample(x, size) and sample.int(n,
> size). My bad.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RcppCore/Rcpp/issues/337#issuecomment-128474256>.
>



-- 
Sriram Subramanian, Ph.D.
Principal
Lighthouse Datalab LLC

**Comment by coatless** [comment]
I'm pretty sure the `Matrix` library update occurred as I was able to construct both matrices and attempt to solve. Though, my computer screamed as 32gigs were consumed like chump change. 

Please close. (Tagging #506)

**Comment by subsriram** [comment]
Coatless, I am still getting the same error. Were you able to form the matrix 'c'? IF so, which versions of R and Matrix package are you using?

**Comment by coatless** [comment]
```bash
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.5 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Matrix_1.2-6

loaded via a namespace (and not attached):
[1] rsconnect_0.4.3           tools_3.3.1               RcppArmadillo_0.7.100.3.1 Rcpp_0.12.6.1             grid_3.3.1                lattice_0.20-33
```

Two matrices created:

![screen shot 2016-07-23 at 2 15 52 pm](https://cloud.githubusercontent.com/assets/833642/17079787/017b19e2-50e0-11e6-8b17-3789ad0bb1c7.png)

Solving both matrices:

![screen shot 2016-07-23 at 2 21 55 pm](https://cloud.githubusercontent.com/assets/833642/17079814/da27fd28-50e0-11e6-9e76-73668b12d03f.png)

**Comment by subsriram** [comment]
Thank you James. The matrix you formed is the 'c' matrix with sparsematrix
command, correct? That is where I get the error and I have the same
versions of software as you have output

On Jul 23, 2016, at 3:22 PM, James J Balamuta <notifications@github.com>
wrote:

> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.5 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] Matrix_1.2-6

loaded via a namespace (and not attached):
[1] rsconnect_0.4.3           tools_3.3.1
RcppArmadillo_0.7.100.3.1 Rcpp_0.12.6.1             grid_3.3.1
       lattice_0.20-33

Two matrices created:

[image: screen shot 2016-07-23 at 2 15 52 pm]
<https://cloud.githubusercontent.com/assets/833642/17079787/017b19e2-50e0-11e6-8b17-3789ad0bb1c7.png>

Solving both matrices:

[image: screen shot 2016-07-23 at 2 21 55 pm]
<https://cloud.githubusercontent.com/assets/833642/17079814/da27fd28-50e0-11e6-9e76-73668b12d03f.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/RcppCore/Rcpp/issues/337#issuecomment-234735409>, or mute
the thread

**Comment by thirdwing** [comment]
@subsriram Are you seeing the same error? Or something like

```
Error: cannot allocate vector of size XX Gb
```

If you see the later, you may try to increase the resource limit for R (see https://stat.ethz.ch/R-manual/R-devel/library/base/html/Memory-limits.html).

**Comment by coatless** [comment]
Double check:

1. Matrix version
2. Operating System

Since as of 1.2-4, the `Matrix` package definitely looks like it does have `long` support:

https://github.com/cran/Matrix/blob/fe3ef207d0c66ca434a1328128df3f6ff401e8ad/src/Mutils.h#L37-L43

https://github.com/cran/Matrix/blob/master/inst/include/cholmod.h#L12-L28

**Comment by subsriram** [comment]
It is still the same error - I have tried on two different large instances
(256gb ram) just to check and same result. All packages are updated to the
latest version

On Jul 23, 2016, at 7:43 PM, Qiang Kou (KK) <notifications@github.com>
wrote:

@subsriram <https://github.com/subsriram> Are you seeing the same error? Or
something like

Error: cannot allocate vector of size XX Gb

If you see the later, you may try to increase the resource limit for R (see
https://stat.ethz.ch/R-manual/R-devel/library/base/html/Memory-limits.html).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/RcppCore/Rcpp/issues/337#issuecomment-234747434>, or mute
the thread

**Comment by eddelbuettel** [comment]
It fails fpr me too.  We haven't posted code in a while so I am not sure we are still comparing the same snippets, but I just had this fail (on a 64gb ram box):

```r
> system("free -h")
             total       used       free     shared    buffers     cached
Mem:           61G        43G        17G       447M       391M       9.0G
-/+ buffers/cache:        34G        27G
Swap:          62G       196M        62G
> library(Matrix)
> sz=2^31+10000
> a=sample.int(15000000,size=sz,replace=TRUE)
> b=sample.int(25000,size=sz,replace=TRUE)
> c=sparseMatrix(a,b)
Error in validityMethod(as(object, superClass)) : 
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:138
> 
```

Now -- that is package Matrix failing, not Rcpp or RcppArmadillo.  So with that I'd keep this closed here.  Maybe OP wants to take this (with the code examples) to Matrix ...
