### ISSUE TITLE
Matrix access operator() should check bounds

### ISSUE THREAD

**Issue by fplaza** [RcppCore/Rcpp#341]
Currently, the Vector Matrix access operator() checks bounds but the Matrix access operator() does not 

Here is a small example
```c++
#include <Rcpp.h>
using namespace Rcpp;


// [[Rcpp::export]]
void test_vec()
{
  
  const int length = 2;
  NumericVector v1(length);
  //This fails
  Rcout << v1(length) << std::endl;
}

// [[Rcpp::export]]
void test_mat()
{
  const int num_rows = 2;
  const int num_cols = 2;
  NumericMatrix m1(num_rows, num_cols);
  //This should fail tooo
  Rcout << m1(2,2) << std::endl;
}




/*** R
test_vec()
test_mat()
*/
```
Result
```
> test_vec()
Error in eval(expr, envir, enclos) : index out of bounds
> test_mat()
1.58802e-315
````
Resuls expected
```
test_mat()
Error: index out of bounds
```

Here is a patch that solves this issue:
e4f36eb82326898df4077466383e9e4e637b2567

**Comment by kevinushey** [comment]
Based on the Vector interface, `[]` is used for 'unsafe' access while `()` is used for 'safe' access. Unfortunately, `foo[1, 2]` isnt' valid C++ code so we don't get the same analogues for the Matrix class.

We might want to follow the lead of [`std::vector`](http://www.cplusplus.com/reference/vector/vector/at/) and provide `at` access methods that perform 'safe' (bounds-checked) access into Vector / Matrix objects.

**Comment by fplaza** [comment]
It seems to be a good solution.
Otherwise, the user will have to compute an offset for each access without bounds check.

**Comment by eddelbuettel** [comment]
Yup. Other matrix classes do that too, sometimes with the opposite semantics.  

For Armadillo,  [at is the non-checked version](http://arma.sourceforge.net/docs.html#element_access).

**Comment by jjallaire** [comment]
I'd second keeping () unchecked and adding an explicit at() for checked
access (otherwise we'd end up slowing down a bunch of existing code)

**Comment by eddelbuettel** [comment]
Right -- we clearly can't just redefine behaviour. So our `()` remains unchecked as it has been.

**Comment by fplaza** [comment]
What about the operator[]?
Should it be removed?

**Comment by jjallaire** [comment]
We can't remove existing interfaces either. It should remain as-is

**Comment by fplaza** [comment]
To sum up:
operator[]: no bounds check, unchanged
operator(): no bounds check, unchanged for Matrix, change for Vector from bounds check to no bounds check
operator at : bounds check , new

**Comment by kevinushey** [comment]
Let's keep the existing interfaces as-is, but I think it's okay to add `at()` as a checked accessor.

**Comment by fplaza** [comment]
Fine, I will propose another patch.

**Comment by eddelbuettel** [comment]
Thanks, will close this.  #342 looks good from a first glance.
