### ISSUE TITLE
Address sanitizer check fails with Rcpp::stop but succeeds with Rf_error

### ISSUE THREAD

**Issue by jackwasey** [RcppCore/Rcpp#354]
I was asked by a CRAN maintainer to resolve some new address sanitizer errors unearthed using their build environment, details of which are here: http://www.stats.ox.ac.uk/pub/bdr/memtests/clang-ASAN/README.txt

This environment differs from the rocker SAN and UBSAN images (which did not produce this error), so after some considerable time I replicated that environment in docker, with this Dockerfile: https://github.com/jackwasey/r-devel-san-clang/blob/master/Dockerfile

In summary, this environment is similar to the rocker/r-devel-ubsan-clang, but with clang 3.6, and `-fsanitize=address,undefined`.

I see in the Rcpp docs that Rf_error is discouraged, however, with Rcpp::stop, the sanitizer finds a problem using the environment described above.

```
> Rcpp::cppFunction("void doError() { Rcpp::stop(\"stopping\"); }")
> 
> doError()
==9854==AddressSanitizer CHECK failed: /tmp/buildd/llvm-toolchain-3.6-3.6.2/projects/compiler-rt/lib/asan/asan_interceptors.cc:350 "((__interception::real___cxa_throw)) != (0)" (0x0, 0x0)
    #0 0x4c4874  (/usr/local/lib/R/bin/exec/R+0x4c4874)
    #1 0x4cb1f1  (/usr/local/lib/R/bin/exec/R+0x4cb1f1)
    #2 0x4a542a  (/usr/local/lib/R/bin/exec/R+0x4a542a)
    #3 0x7fdf6de9fe7a  (/tmp/RtmpICK7bl/sourcecpp_267e530ba276/sourceCpp_3.so+0xae7a)
    #4 0x7fdf6de9c310  (/tmp/RtmpICK7bl/sourcecpp_267e530ba276/sourceCpp_3.so+0x7310)
    #5 0x7fdf6de9ca87  (/tmp/RtmpICK7bl/sourcecpp_267e530ba276/sourceCpp_3.so+0x7a87)
    #6 0x7fdf778b6298  (/usr/local/lib/R/lib/libR.so+0xc8e298)
    #7 0x7fdf77930381  (/usr/local/lib/R/lib/libR.so+0xd08381)
    #8 0x7fdf77c108e1  (/usr/local/lib/R/lib/libR.so+0xfe88e1)
    #9 0x7fdf77d06c4e  (/usr/local/lib/R/lib/libR.so+0x10dec4e)
    #10 0x7fdf77c0fdab  (/usr/local/lib/R/lib/libR.so+0xfe7dab)
    #11 0x7fdf77d0fa7b  (/usr/local/lib/R/lib/libR.so+0x10e7a7b)
    #12 0x7fdf77c1157a  (/usr/local/lib/R/lib/libR.so+0xfe957a)
    #13 0x7fdf77f5924e  (/usr/local/lib/R/lib/libR.so+0x133124e)
    #14 0x7fdf77f629a9  (/usr/local/lib/R/lib/libR.so+0x133a9a9)
    #15 0x7fdf77f622c7  (/usr/local/lib/R/lib/libR.so+0x133a2c7)
    #16 0x7fdf77f62bed  (/usr/local/lib/R/lib/libR.so+0x133abed)
    #17 0x4e1046  (/usr/local/lib/R/bin/exec/R+0x4e1046)
    #18 0x7fdf75b20b44  (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)
    #19 0x435d26  (/usr/local/lib/R/bin/exec/R+0x435d26)
```

whereas:

```
> Rcpp::cppFunction("void doError() { Rf_error(\"stopping\"); }")
> doError()
Error in doError() : stopping
```

**Comment by eddelbuettel** [comment]
Which Rcpp version did you use?  As I recall we did some putzing around with this.

Also, we heard from @pschmied about issues with tinyformat on OpenBSD. This may be related.  So could you possibly (given the working ASAN setup) try just some format string for tinyformat?

**Comment by jackwasey** [comment]
Rcpp Is 0.12.0 i.e. current CRAN. Thanks for suggestion. Will be happy to try it, but may be a day or two.

**Comment by eddelbuettel** [comment]
:+1:  I'll try to get to it too from my end, but I am not one of the guys who have worked on the (included) tinyformat library.    

We should also talk about ASAN and maybe get your mods into my image if you're up for it.   As I recall ASAN is older / in need of a refresher; I think I last worked on UBSAN.

**Comment by kevinushey** [comment]
The way we call `tfm` actually looks bogus (https://github.com/RcppCore/Rcpp/blob/7c6ac5bbb7da6af80ec5d64c0b37e791b35f4653/inst/include/Rcpp/exceptions.h#L254-L257):

```
    template <typename T1>
    inline void stop(const char* fmt, const T1& arg1) {
        throw Rcpp::exception( tfm::format(fmt, arg1 ).c_str() );
    }
```

We're creating an exception with a `const char*` pointing to a temporary string -- smells like undefined behaviour.

That said, ASAN is touching a case where we don't even use `tfm`:

```
    inline void stop(const std::string& message) {
        throw Rcpp::exception(message.c_str());
    }
```

so this is going to take some more work to figure out what's going on...

**Comment by kevinushey** [comment]
I can't reproduce with a locally built `clang` (using current trunk):

```
kevin:~/Desktop
$ R --vanilla --slave -f ouch.R 2>&1 | pbcopy
```

gives me

```
Generated code for function definition: 
--------------------------------------------------------

#include <Rcpp.h>

using namespace Rcpp;

// [[Rcpp::export]]
void doError() { Rcpp::stop("stopping"); }

Generated extern "C" functions 
--------------------------------------------------------


#include <Rcpp.h>
// doError
void doError();
RcppExport SEXP sourceCpp_0_doError() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    doError();
    return R_NilValue;
END_RCPP
}

Generated R functions 
-------------------------------------------------------

`.sourceCpp_0_DLLInfo` <- dyn.load('/var/folders/tm/5dt8p5s50x58br1k6wpqnwx00000gn/T//Rtmp5FSCM3/sourcecpp_1197f3c3b2bae/sourceCpp_1.so')

doError <- Rcpp:::sourceCppFunction(function() {}, TRUE, `.sourceCpp_0_DLLInfo`, 'sourceCpp_0_doError')

rm(`.sourceCpp_0_DLLInfo`)

Building shared library
--------------------------------------------------------

DIR: /var/folders/tm/5dt8p5s50x58br1k6wpqnwx00000gn/T//Rtmp5FSCM3/sourcecpp_1197f3c3b2bae

/Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB -o 'sourceCpp_1.so' --preclean  'file1197f45950bd2.cpp'  
/Users/kevin/.llvm/build/Release/bin/clang++ -fsanitize=address,undefined -fno-omit-frame-pointer -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include  -I"/Users/kevin/Library/R/3.3/library/Rcpp/include" -I"/private/var/folders/tm/5dt8p5s50x58br1k6wpqnwx00000gn/T/Rtmp5FSCM3"    -fPIC  -I"/Users/kevin/.llvm/libcxx/include" -g -O3 -Wall -mtune=native -c file1197f45950bd2.cpp -o file1197f45950bd2.o
/Users/kevin/.llvm/build/Release/bin/clang++ -fsanitize=address,undefined -fno-omit-frame-pointer -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o sourceCpp_1.so file1197f45950bd2.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
Error: stopping
Execution halted
```

I do get appropriate ASAN warnings on obvious buffer overruns, so I think I've compiled `clang` + R with ASAN okay...

```
kevin:~/Desktop
$ clang++ -v
clang version 3.8.0 (trunk 246366)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
InstalledDir: /usr/local/bin
```

**Comment by kevinushey** [comment]
And looking at some posts e.g.

https://code.google.com/p/address-sanitizer/issues/detail?id=321
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60038
http://comments.gmane.org/gmane.comp.documentfoundation.libreoffice.scm/55189

I think the `check FAILED` is actually indicative of a bug in ASAN (which may now be fixed), not Rcpp. Please let the CRAN maintainers know.

**Comment by jackwasey** [comment]
Thanks so much for digging into it.

Now I'm wishing I could have got clang-3.7 installed in the docker image I made: I tried, but got lost in debian dependency details. I'll work again on clang-3.7 in my image, check again, and share Dockerfile.

**Comment by eddelbuettel** [comment]
Very nice work Kevin -- thanks a bunch!

**Comment by jackwasey** [comment]
Using the images below, I can no longer reproduce this bug, so can I suggest closing it?
https://github.com/jackwasey/rocker-ubsan

**Comment by eddelbuettel** [comment]
Thanks for the follow-up.  Will close as suggested.
