### ISSUE TITLE
Move semantics for R in Rcpp function

### ISSUE THREAD

**Issue by tqchen** [RcppCore/Rcpp#355]
Inspired by discussion with @thirdwing and @hetong007.  I am not expert in R and Rcpp. However, we are making machine learning packages for R using c++. So this comes from our use case, and I believe it could be useful in general.

The motivation is to create an online update API for some machine learning models. Or in simplified case, recording word counts. We want to create a function that reads document one by one, and update the word count in a matrix.

A common way to implement word count in C++, is create a vector, and update the vector by adding to the cells as the data get updated.  However, R is a language that normally immutable states. This comes with the cost on having to copy the object each time you write it. So a R function for update will usually looks like
```r
word_count_vector <- update(word_count_vector, data)
```

Internally, this means copy the word_count_vector, update it with data, and return a new one. This introduces a cost in memory copy, and is not suitable when data is not a lot, and there is only small amount of updates.

One way to deal with this problem is to make word_count_vector ***mutable***, which is possible if there is a C++ API and ```word_count_vector``` is implemented with external ptr. 

```r
# update will update word_count_vector
update(word_count_vector, data)
```
 
However, this kind of semantics is not natural to R users. As users usually assume  ```word_count_vector``` is immutable.  More importantly, it is impossible to warn the user when they did something wrong, like treat the word_count_vector as the one that has not been changed.
 
After some discussion, we think it is interesting to introduce a ***move sematics***, so user can still write

```r
word_count_vector <- update(word_count_vector, data)
```

Which is in the same way as R. However, when word_count_vector is passed into the function, it get ```moved```, and the original ```word_count_vector``` is no longer valid. It is possible to hit an error to the user when they attempt to use the old ```word_count_vector```, if an invalid field, or nullptr is encountered in internal implementation. This allows run-time check for violation of the move semantics, tell the user if they did something wrong.

In this way, the move semantics kind of allows mutations in R in a way that R user is familiar with. But still get the benefit of reusing the data structure in C++, so no re-allocation and copy is needed.

We believe this could be helpful to introducing online updating functions that continuously updates a state and the old states are dumped.

**Comment by eddelbuettel** [comment]
Hi there, and thanks for starting a discussion.  Are you part of the mxnet effort?

As for growing vectors:  can't you just use `std::vector<...>` ?

**Comment by tqchen** [comment]
Yes, I am of initiators of mxnet. The question here is not on the c++ side, I can see that R cpp might offer ways for R user to directly operate and mutate a ```std::vector<..>```. It is more on how such function is exposed to the user in R language.

Say there is a function that updates a vector by calling update
```
update(word_count_vector, data)
 ```

It update the internal vector representation of word_count_vector. A normal R user will assume ```word_count_vector ``` is immutable, and may not noticed the fact that word_count_vector is changed. 

Another way is to create a function that returns a new vector each time, which will involves a copy

**Comment by eddelbuettel** [comment]
Don't forget that R 
- only knows SEXP
- only talks to us via `.Call()` 

so there are some limits to the cleverness.  Most approaches that change vectors will involve a copy.

**Comment by tqchen** [comment]
Yes, so here is what I guess which might could be done for a generic class.

Assume vector is allocated and stored in ExternalPtr. What we can do is when R calls .Call, a new ExternalPtr is created, move the old vector pointer to the new position, change the vector inplace.

Then return the new ExternalPtr, and invalidate the old one(e.g. set it to nullptr). Since the old one is invalidated, there is no need top copy in order to change the content

so 
```r
new_vector <-update(old_vector, data)
```
will get new_vector that holds the resulting vector. The only requirement is that user need to know ```old_vector ``` is moved, and they are no longer allowed to use the old vector.

If the user happens to use the ```old_vector```, Rcpp detects the ptr is invalid, and hit an error saying the user is using a moved object

**Comment by tqchen** [comment]
The advantage of such approach is that it seems to be able to tell user this is move semantics, and warn them when they did it incorrectly, as compared to an approach that directly inplace update a vector.

**Comment by eddelbuettel** [comment]
Yes -- but that has nothing to do with Rcpp per see apart from possibly using our Rcpp::XPtr interface rather than 'raw' C level external pointers via `SEXP` as [bigmemory](http://cran.rstudio.com/package=bigmemory)  does.

So by all means do experiment with such a novel interface.  It strikes me you need neither help nor permission from us.   I may be missing something though ....

**Comment by tqchen** [comment]
Interesting. I know see that it is possible by using current interface directly. 

It might be nice to have a extension of ```Rcpp:XPtr``` that support such semantics, and hit a error automatically when a fetch to the XPtr is made in a state of moved pointer. 

This kind of semantics might be worth advocating for Rcpp users who want to reuse memory and also be friendly to R interface.

**Comment by eddelbuettel** [comment]
There is no change in interface.  The XPtr is pass through.  I _think_ you can just define everything you want here on  your (C++) side as you then also control the (R side) accessors.

**Comment by tqchen** [comment]
I agree. It is only needed on C++ side. I think what we can do is have a ```RMovablePtr``` that makes uses of XPtr

```c++
template<T>
class RMovablePtr {
public:
   // overload some functions for ptr
private:
    T *data_;
    bool moved_;
};
```

So we can do in c++ function
```c++
dosomething(SEXP vector) {
    RMovablePtr<std::vector<int> >  ptr = RMovablePtr<std::vector<int> >(vector).move();
    ptr->push_back(int);
    return ptr->XPtr();
}
```

And customize RMovablePtr to hit R's error when it is referenced with ```moved_``` flag set to true. This does not have to be part of Rcpp though, but seems to be a nice extension

**Comment by eddelbuettel** [comment]
Rcpp is large enough as it stands such such extensions are best kept in add-on packages.
