### ISSUE TITLE
Date errors on windows

### ISSUE THREAD

**Issue by jeroenooms** [RcppCore/Rcpp#359]
Not sure if this is an Rcpp or mingw issue but any pointers would be helpful.

Using the new windows tool chain on windows 64 (not 32) gives the following problem:

```cpp
// [[Rcpp::export]]
SEXP ctor_mdy() {
  Date dt = Date(12,31,2005);
  return wrap(dt);
}

// [[Rcpp::export]]
SEXP ctor_ymd() {
  Date dt = Date(2005,12,31);
  return wrap(dt);
}
```

Gives:

```r
> library(RToolsTest)
> RToolsTest::ctor_mdy()
[1] "1969-12-31"
> RToolsTest::ctor_ymd()
[1] "-5877641-06-23"
```

Which leads to:

```
RUNIT TEST PROTOCOL -- Mon Aug 31 14:22:10 2015 
*********************************************** 
Number of test functions: 465 
Number of errors: 0 
Number of failures: 5 


1 Test Suite : 
Rcpp Unit Tests - 465 test functions, 0 errors, 5 failures
FAILURE in test.Date.ctor.mdy: Error in checkEquals(ctor_mdy(), as.Date("2005-12-31"), msg = "Date.ctor.mdy") : 
  Mean absolute difference: 13148Date.ctor.mdy
FAILURE in test.Date.ctor.ymd: Error in checkEquals(ctor_ymd(), as.Date("2005-12-31"), msg = "Date.ctor.ymd") : 
  Mean absolute difference: 13148Date.ctor.ymd
FAILURE in test.DateVector.operator.SEXP: Error in checkEquals(Datevector_sexp(), rep(as.Date("2005-12-31"), 2),  : 
  Mean absolute difference: 13148DateVector.SEXP
FAILURE in test.DateVector.wrap: Error in checkEquals(Datevector_wrap(), rep(as.Date("2005-12-31"), 2),  : 
  Mean absolute difference: 13148DateVector.wrap
FAILURE in test.vector.Date: Error in checkEquals(vector_Date(), rep(as.Date("2005-12-31"), 2), msg = "Date.vector.wrap") : 
  Mean absolute difference: 13148Date.vector.wrap
```

**Comment by eddelbuettel** [comment]
That appears to be simply your usage error as there is [only one ctor with an `(int, int, int)` signature](https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/Date.h#L48-L64).  It was added as QuantLib needed it -- and in the pre-Cambrian days, Rcpp was a single pair of .h and .cpp used by and shipped with QuantLib ...

**Comment by aadler** [comment]
Hello.

As discussed on R-sig-windows, I am not getting this error on Win64. I was using R-patched_2015-08-26, Jeroen's 4.9.2 toolchain as of last Thrusday, and I pass std=gnu++11 as well as architecural flags (ivybridge). Specifically, I get:

I get

    > ctor_mdy()
    [1] "2005-12-31"
    > ctor_ymd()
   [1] "2005-12-31"

I am about to build R (R-patched_2015-08-27) on Win764 using the 4.9.3 toolchain, and I will build it vanilla, but will pass gnu++11 in CXXFLAGS for building packages, and I'll test this error again.

Avi

**Comment by jeroenooms** [comment]
@eddelbuettel This example is just a snippet from [your own unit tests](https://github.com/cran/Rcpp/blob/master/inst/unitTests/cpp/dates.cpp#L31-L41).

**Comment by eddelbuettel** [comment]
Guilty as charged :)

**Comment by jeroenooms** [comment]
@aadler mmm you are right. This problem might actually be a side effect of `-mno-sse`.

**Comment by aadler** [comment]
Continuing at https://github.com/jeroenooms/Rbuild/issues/1
