### ISSUE TITLE
Rcpp compiles using -std=gnu++11 but not -std=c++11. Is this a toolchain issue or an Rcpp issue?

### ISSUE THREAD

**Issue by aadler** [RcppCore/Rcpp#360]
Whilst trying to test the new Windows toolchains based on GCC 4.9.x, I have come across an interesting issue. When I compile Rcpp with either nothing or `std=gnu++11`, Rcpp compiles without any issues. However, when I pass `std=c++11` I get:
```
* installing *source* package 'Rcpp' ...
** package 'Rcpp' successfully unpacked and MD5 sums checked
** libs
g++ -m64 -I"C:/R/R-PATC~2/include" -DNDEBUG -I../inst/include/    -I"C:/R/RLocalSoft/extsoft/include"     -std=c++11 -O2 -mtune=ivybridge -pipe -c Date.cpp -o Date.o
g++ -m64 -I"C:/R/R-PATC~2/include" -DNDEBUG -I../inst/include/    -I"C:/R/RLocalSoft/extsoft/include"     -std=c++11 -O2 -mtune=ivybridge -pipe -c Module.cpp -o Module.o
g++ -m64 -I"C:/R/R-PATC~2/include" -DNDEBUG -I../inst/include/    -I"C:/R/RLocalSoft/extsoft/include"     -std=c++11 -O2 -mtune=ivybridge -pipe -c Rcpp_init.cpp -o Rcpp_init.o
g++ -m64 -I"C:/R/R-PATC~2/include" -DNDEBUG -I../inst/include/    -I"C:/R/RLocalSoft/extsoft/include"     -std=c++11 -O2 -mtune=ivybridge -pipe -c api.cpp -o api.o
api.cpp:40:30: fatal error: execinfo.h: No such file or directory
         #include <execinfo.h>
                              ^
compilation terminated.
make: *** [api.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/R/R-PATC~2/etc/x64/Makeconf" -f "C:/R/R-PATC~2/share/make/winshlib.mk" -f "\\[REDACTED]/.R/Makevars" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="Rcpp.dll" WIN=64 TCLBIN=64 OBJECTS="Date.o Module.o Rcpp_init.o api.o attributes.o barrier.o"' had status 2
ERROR: compilation failed for package 'Rcpp'
* removing 'C:/R/R-patched/library/Rcpp'

The downloaded source packages are in
        ‘C:\R\temp\Rtmp4mtdWr\downloaded_packages’
Warning messages:
1: running command '"C:/R/R-patched/bin/x64/R" CMD INSTALL --byte-compile -l "C:\R\R-patched\library" C:\R\temp\Rtmp4mtdWr/downloaded_packages/Rcpp_0.12.0.tar.gz' had status 1 
2: In install.packages("Rcpp", type = "source", INSTALL_opts = "--byte-compile") :
  installation of package ‘Rcpp’ had non-zero exit status
```

Is this a toolchain issue, or an issue with Rcpp being built under Windows?

Thank you.

**Comment by thirdwing** [comment]
This is really weired, `execinfo.h` shouldn't be included, see  https://github.com/RcppCore/Rcpp/blob/master/src/api.cpp#L37-L40

**Comment by eddelbuettel** [comment]
Given that is an issue which arises only with the new toolchain, I think you know the answer to this.  That said, several `#ifdef` assumptions may need to be validated.   PRs welcome to make Rcpp build on the new and untested toolchain...

**Comment by eddelbuettel** [comment]
Looking at 
```
#if defined(_WIN32)
```
the [recent commit](https://github.com/RcppCore/Rcpp/commit/686e04af7a15b1a025c80d56874def5964948349) by @kevinushey comes to mind.  

Maybe we need `_WIN32` and `WIN32` ? Oh the joy of 'doze...

**Comment by aadler** [comment]
@thirdwing I'm on Win64, but if Win32 is the threading, then yes, it's using Win32 and not posix.

@eddelbuettel Thank you; I was afraid of that :)

@jeroenooms, you may be interested in this.

**Comment by kevinushey** [comment]
Normally, `_WIN32` implies both Windows 32bit and Windows 64bit. I have no idea what the toolchain is doing here.

We should put something in `platform.h` like:

```
#if defined(_WIN32) || defined(WIN32) || defined(_WIN64) || defined(WIN64)
# define RCPP_IS_WINDOWS_SYSTEM
#endif
```

and then protect `<execinfo.h>` with that as well.

**Comment by kevinushey** [comment]
This issue is already fixed on master. The switch from `WIN32` to `_WIN32` fixes this. I assume @aadler was building an older version of Rcpp that did not have that fix.

**Comment by eddelbuettel** [comment]
Cool.  I still like the idea about `platform.h` though.

**Comment by aadler** [comment]
I was building from CRAN (Per https://github.com/hadley/devtools/issues/908) so that makes sense. Looking forward to the next release (or seeing if @kevinushey 's suggestion there is correct). Thank you.
