### ISSUE TITLE
Nullable object

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#363]
In quite some user-space code the R side has something like

```{.r}
weightedLeastSquares(X, y, w)      # ie y ~ X given weights w
```

where the third argument is options, ie 

```{.r}
weightedLeastSquares(X, y, NULL)
```

In that case we generally cannot have the third strongly typed as `NumericMatrix` or alike and have to keep it a `SEXP` in the interface.  Nothing wrong with that but a bit of an eyesore. 
  
Following some discussion with @dcdillon I have written a really simple wrapper class `Nullable` that contains a `SEXP` as well as a `bool` for state.  With that we can do (stylized)

```{.cpp}
...., NumericVector & w) {
//...
if (!w.isNull()) {
    // do stuff with w
}
```

If there is no protest -- or someone reminds of something much better we already have ;-) -- then I'll fold that in.

**Comment by jjallaire** [comment]
In boost::error_code they implement nullability via some operator overloads:

   typedef void (*unspecified_bool_type)();
   static void unspecified_bool_true() {}

   operator unspecified_bool_type() const BOOST_SYSTEM_NOEXCEPT  //
true if error
   {
      return m_val == 0 ? 0 : unspecified_bool_true;
   }

   bool operator!() const BOOST_SYSTEM_NOEXCEPT  // true if no error
   {
      return m_val == 0;
   }

This allows you to write code like this:

if (ec) {

}

if (!ec) {


}

Maybe that's too fancy/obscure though?

**Comment by eddelbuettel** [comment]
Interesting.   Looks fancy.  That may fit.  So far I only had `operator SEXP()` and `get()` to extract, and `isNull()` to test.  I may play with the above.  Thanks!

**Comment by dcdillon** [comment]
It's not as fancy as it looks.  It's just a cast operator to bool.

```c++
operator bool()
{
    return !isNull();
}

bool operator!()
{
    return isNull();
}
```

**Comment by eddelbuettel** [comment]
I think we won't inherit from `Nullable` as it can't be a CRTP idiom -- we can't instantiate our standard types (ie `NumericalMatrix`) with `NULL` as that gets us the very run-tome woes which `Nullable` tries to avoid.

**Comment by romainfrancois** [comment]
I'd say make it a template, e.g. Nullable<NumericMatrix>

**Comment by eddelbuettel** [comment]
I looked into that, but eg in `Nullable<NumericMatrix> foo`  I get the same initial problem of `NumericalMatrix` not taking `NULL` --- which lead us to `Nullable` in the first place.   If you can see a way to overcame that (easily) I'd be all ears.  I'd prefer it templated too...

**Comment by kevinushey** [comment]
FWIW the use of 'unspecified_bool_type' is there to help prevent undesired type coercions (ie the [safe bool idiom](http://www.artima.com/cppsource/safebool.html)). You almost definitely don't want just a raw `operator bool(){}` as that is too prone to misuse.

**Comment by eddelbuettel** [comment]
Good timing.  Just tried this `operator bool(){}` approach and was just complaining to @dcdillon over IM :)

**Comment by eddelbuettel** [comment]
I'm going to be pedestrian here and just rely on isNull() as a member.  I don't have luck with either approach while I also have `operator SEXP()`.
