### ISSUE TITLE
hashbang interpreter directive

### ISSUE THREAD

**Issue by aeschreiner** [RcppCore/Rcpp#364]
In the various unit test and example files listed below, the interpreter string is /usr/bin/r. Could that be changed to /usr/bin/R  which is standard on case-sensitive Unix/Linux systems?

File list:
./inst/unitTests/runit.InternalFunction.R
./inst/unitTests/runit.RObject.R
./inst/unitTests/runit.Module.R
./inst/unitTests/runit.binary.package.R
./inst/unitTests/runit.String.R
./inst/unitTests/runit.InternalFunctionCPP11.R
./inst/unitTests/runit.client.package.R
./inst/unitTests/runit.attributes.R
./inst/unitTests/runit.stats.R
./inst/unitTests/runit.rmath.R
./inst/unitTests/runit.Language.R
./inst/unitTests/runit.Matrix.R
./inst/unitTests/runit.sugar.var.R
./inst/unitTests/runit.sugar.R
./inst/unitTests/runit.Function.R
./inst/unitTests/runit.environments.R
./inst/unitTests/runit.Date.R
./inst/unitTests/runit.table.R
./inst/unitTests/runit.Module.client.package.R
./inst/unitTests/runit.Vector.R
./inst/unitTests/runit.S4.R
./inst/unitTests/runit.subset.R
./inst/unitTests/runit.DataFrame.R
./inst/unitTests/runit.XPTr.R
./inst/unitTests/runit.support.R
./inst/unitTests/runit.modref.R
./inst/unitTests/runit.na.R
./inst/unitTests/runit.as.R
./inst/unitTests/runit.wstring.R
./inst/unitTests/runit.wrap.R
./inst/unitTests/runit.Reference.R
./inst/unitTests/runit.misc.R
./inst/examples/functionCallback/newApiExample.r
./inst/examples/RcppInline/UncaughtExceptions.r
./inst/examples/RcppInline/RcppSimpleExample.r
./inst/examples/RcppInline/RObject.r
./inst/examples/RcppInline/external_pointer.r
./inst/examples/RcppInline/RcppInlineExample.r
./inst/examples/RcppInline/RcppInlineWithLibsExamples.r
./inst/examples/Misc/fibonacci.r
./inst/examples/Misc/newFib.r
./inst/examples/Misc/ifelseLooped.r
./inst/examples/Misc/piBySimulation.r
./inst/examples/ConvolveBenchmarks/exampleRCode.r
./inst/examples/ConvolveBenchmarks/overhead.r
./inst/examples/SugarPerformance/sugarBenchmarks.R
./inst/examples/FastLM/benchmark.r
./inst/examples/FastLM/fastLMviaGSL.r
./inst/examples/FastLM/fastLMviaArmadillo.r
./inst/examples/FastLM/benchmarkLongley.r
./inst/examples/OpenMP/OpenMPandInline.r

**Comment by eddelbuettel** [comment]
Gosh no.  

It doesn't matter.  R runs them as R code.   And sensible people like you should install littler.  It's just an apt-get away...

**Comment by eddelbuettel** [comment]
For reference, and based on `r` I use this to run single unit scripts.   You can trivially implement it with `Rscript`:

```{.bash}
#!/bin/sh

set -u 
set -e

progname=`basename $0`
options='p:ah?'
 
usage_and_exit()
{
    echo ""
    echo "Usage: $progname [-p package[,package2,..]] [-?|-h]"
    echo "  Run unit test script for R package"
    echo ""
    echo "Options:"
    echo "  -p package[,package2,..]]  load additional package(s)"
    echo "  -h                         show this help"
    echo "  -a                         run with 'export RunAllRcppTests=yes'"
    echo ""
    echo "The RUnit and inline packages are automatically loaded."
    echo ""
    exit 0
}

while getopts "$options" i 
do 
    case "$i" in
        p)
            pkg=",$OPTARG"
            shift 
            shift
            ;;
        a)
            export RunAllRcppTests="yes"
            shift
            ;;
        h|?)
            usage_and_exit
            ;;
    esac
done

if [ ! -f $1 ]; then
    echo "Error: No file '$1' found"
    exit 1
fi

file=`pwd`/$1

#r -i -t -linline,RUnit${pkg} -e"cppfunction <- function(...) cxxfunction(..., plugin=\"Rcpp\"); runTestFile(\"$file\")"
r -i -t -lRUnit${pkg} -e"runTestFile(\"$file\")"
```

**Comment by aeschreiner** [comment]
It actually does matter to me. I'm on Red Hat based systems and I encounter
problems when I try to create an RPM package. The RPM build system sees
these /usr/bin/r directives and creates a dependency on /usr/bin/r which
cannot be satisfied. There is no littler package in the standard repos.

**Comment by eddelbuettel** [comment]
So package littler, or patch.

**Comment by aeschreiner** [comment]
I patched.
Sorry to take up your time.

On Fri, Sep 4, 2015 at 11:51 AM, Dirk Eddelbuettel <notifications@github.com

**Comment by eddelbuettel** [comment]
Sounds good for the short term.  I'll think about this some more.
