### ISSUE TITLE
Matrix + scalar addition doesn't work

### ISSUE THREAD

**Issue by dcdillon** [RcppCore/Rcpp#365]
The following doesn't compile.

``` c++
#include <Rcpp.h>

using namespace Rcpp;

// [[Rcpp::export]]
NumericMatrix test(NumericMatrix m)
{
    NumericMatrix m2 = m + 1;
    return m2;
}
```

It probably should.

**Comment by eddelbuettel** [comment]
And this is something I just ran into again for [mvabund](cran.rstudio.com/package=mvabund) so Dan and I have been IM'ing over this ...

**Comment by dcdillon** [comment]
Adding the following to Matrix.hpp solves the addition problem.  Other operators could be solved likewise.

```c++
template <int RTYPE, template <class> class StoragePolicy >
inline Matrix<RTYPE, StoragePolicy> operator+(const Matrix<RTYPE, StoragePolicy> &lhs,
    const typename Matrix<RTYPE, StoragePolicy>::stored_type &rhs)
{
    Vector<RTYPE, StoragePolicy> v = static_cast<const Vector<RTYPE, StoragePolicy> &>(lhs) + rhs;
    v.attr("dim") = Vector<INTSXP>::create(lhs.nrow(), lhs.ncol());
    return as< Matrix<RTYPE, StoragePolicy> >(v);
}

template <int RTYPE, template <class> class StoragePolicy >
inline Matrix<RTYPE, StoragePolicy> operator+(const typename Matrix<RTYPE, StoragePolicy>::stored_type &lhs,
    const Matrix<RTYPE, StoragePolicy> &rhs)
{
    return rhs + lhs;
}
```

It obviously won't work for `CharacterMatrix`.  That probably doesn't matter.

**Comment by eddelbuettel** [comment]
Oooold issue -- just got rewarmed on StackOverflow in https://stackoverflow.com/questions/59515517/bizarre-behavior-of-rcpp-numericmatrix

Long story short (see my answer too) when we do  

```c++
// [[Rcpp::export]]
NumericMatrix testfun(NumericMatrix x) {
  NumericMatrix y(x.rows(), x.cols());
  y = x * 2;
  std::cout << x; // x is unmodified
  y = 2 * x;      // contrast with x * 2
  std::cout << x; // x is now modified
  return x;
}
```

the second form where the Rcpp::NumericMatrix is a rhs, the original gets modified too.  I have been glancing at the two cases for `lhs OP scalar` and `scalar OP rhs` in `inst/include/Rcpp/vector/Matrix.h` (and from the PR that fixed this) but I am not yet seeing why the rhs gets modified.

Any idea @thirdwing @dcdillon ?

**Comment by rstub** [comment]
There is an asymmetry between `RCPP_GENERATE_MATRIX_SCALAR_OPERATOR` and `RCPP_GENERATE_SCALAR_MATRIX_OPERATOR`, c.f.

https://github.com/RcppCore/Rcpp/blob/85cf95f2a5c8e1faee05685126381203125aa36b/inst/include/Rcpp/vector/Matrix.h#L255

vs

https://github.com/RcppCore/Rcpp/blob/85cf95f2a5c8e1faee05685126381203125aa36b/inst/include/Rcpp/vector/Matrix.h#L272-L273

If I change the latter to the symmetric form

```cpp
Vector<RTYPE, StoragePolicy> v = lhs __OPERATOR__ static_cast<const Vector<RTYPE, StoragePolicy> &>(rhs);
```
the error seems to go away. I have not tested this in any sensible way yet, though.

**Comment by eddelbuettel** [comment]
I looked at that too and wondered whyit was that way, but "assumed" it would not compile otherwise.  But I can confirm now that I should have tried that too :)  This works. 

Will run the unit tests and maybe even a set of rev.deps.

**Comment by thirdwing** [comment]
I can not remember why it is in this form.

I send a PR for this: https://github.com/RcppCore/Rcpp/pull/1040

**Comment by eddelbuettel** [comment]
Sorry, I may not have been all that clear but I already _made_ the change.  I just haven't pushed my branch.   Reverse-depends check is a few hours in (maybe 20% done) and no issues yet.

But now that you made the PR I guess I may as well fold it in...

**Comment by thirdwing** [comment]
Either way is fine. You can just close that PR and this issue when pushing.

**Comment by eddelbuettel** [comment]
No, the PR is good -- you added tests! I had not gotten to it.  

Will likely merge it once the rev deps are done.

**Comment by thirdwing** [comment]
Fixed in https://github.com/RcppCore/Rcpp/pull/1040
