### ISSUE TITLE
Allowing conversion of list() into std::set<std::vector<T> > 

### ISSUE THREAD

**Issue by coatless** [RcppCore/Rcpp#367]
I'm interested in moving a list() with different vectors into Rcpp to operate on.

Currently:

```cpp
std::vector<std::string> func(std::set<std::vector<std::string> > x ){}
```

Will error with:

```
/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include/Rcpp/internal/Exporter.h:
31:28: error: no matching constructor for initialization of
 'std::__1::set<std::__1::vector<std::__1::basic_string<char>,
 std::__1::allocator<std::__1::basic_string<char> > >, 
std::__1::less<std::__1::vector<std::__1::basic_string<char>,
 std::__1::allocator<std::__1::basic_string<char> > > >,
 std::__1::allocator<std::__1::vector<std::__1::basic_string<char>,
 std::__1::allocator<std::__1::basic_string<char> > > > >'
                    Exporter( SEXP x ) : t(x){}
```

However, writing it with a vector definition instead of set definition succeeds. e.g. 
```cpp
std::vector<std::string> func(std::vector<std::vector<std::string> > x ){}
```

I think the following exporter would be resolve the issue:
```cpp
template <typename T> 
class Exporter< std::set<T> > {
public: 
    Exporter(SEXP x) : data(x){}

    inline std::set<T> get() {
        size_t n = data.size() ;
        std::set<T> out( n ) ;

        std::set<T>::const_iterator it;
        for(it=out.begin(); it!=out.end(); ++it){
            out.insert( as<T>(data[i]) );   
        }
        return out ;
    }

private:
    List data ;
}; 
```

**Comment by eddelbuettel** [comment]
I can see how it would in this issue, I just don't quite see yet why we'd need it :)   

Can you motivate the use case a little?  Any detail why `vector` is inferior to `set`  for this?

**Comment by coatless** [comment]
**Use case example:**

I'm currently generating a huge list containing character vectors of varying dimensions in R (1000+ with inner dimensions ranging from 1-149).

The modeling paradigm I'm working to implement within RcppArmadillo has various conditions that make it necessary to iterate each element individually. This is very computationally intensive within R. 

**Details:**

Underneath the `vector` data structure I receive a list of models in the exact order that is specific on the pass. However, after some manipulations, e.g. adding / modifying, the `vector` lacks the self-property of ordering so finding the right elements becomes problematic (i.e. O(N)) since the vector becomes unsorted.

On the other hand, `set` has some very nice properties that cut down on a few manipulations required. The first benefit is that I end up with guaranteed uniqueness on all elements within the `set`. Now, this is something that could easily be solved with unique/duplicate in R, however, the main goal is to have all operations self-contained so that the modeling framework can auto-construct different lines of inquiry. The second property is that order is preserved according to a preset descriptor for the set (e.g. length of each vector). The third is finding elements reduces from O(N) to O(log(N)). 

**Workaround:**
I end up importing the list as a `vector<T>` and recast it with an internal function to the desired `set<T>`. This is a bit undesirable since any subsequent functions that I pass the `vector<T>` to are unable to be easily surfaced into R.

**Comment by eddelbuettel** [comment]
Sold. 

Can you prepare a pull request so that we get testing via Travis (and ideally more) ?

**Comment by dcdillon** [comment]
I played with this a bit and it's a bit tougher than it initially seems (at least with the code provided by @coatless).

Specifically, the fact that `List` is not yet defined in `inst/include/Rcpp/internal/Exporter.h` which is where this code belongs.

This leads us to some other discussion about handling of `#includes` in `Rcpp` in general, but without a wholesale change to that, it becomes difficult.

The other option I can see is replicating the functionality of `List::size()` and `List::operator[]` within the context of this exporter.  Unfortunately, this seems heavy handed and prone to future error, so I don't really want to go down that path.

Anyone got any better thoughts?

**Comment by eddelbuettel** [comment]
The third option is probably best. Not sure why I didn't think about it when we chatted about this the other day.  I'd much prefer to leave the `#include` order alone and bite the bullet of replicating some `List` functionality we don't yet have at that point via plain R C API structures.  A little more painful, but doable.

And yes, it would still be nice to have this.  @coatless what did you end up using?  More workarounds?

**Comment by dcdillon** [comment]
OK.  Given that I have the following code snipped (with a comment where I am not quite sure what to do).  Any advice would be beneficial.

```c++
template <typename T> 
class Exporter< std::set<T> > {
public: 
    Exporter(SEXP x) : data(x){}

    inline std::set<T> get() {
        size_t n = Rf_xlength(data) ;
        std::set<T> out( n ) ;

        std::set<T>::const_iterator it;
        for(it=out.begin(); it!=out.end(); ++it){
            out.insert( static_cast<T>(data[i]) );   ## here I don't know what to do
        }
        return out ;
    }

private:
    SEXP data ;
}; 
```

**Comment by eddelbuettel** [comment]
I'm still a bit lost about what gets converted from where to where.    We started from
> a huge list containing character vectors of varying dimensions
and is the goal to make this a list of sets instead?   And `std::set` is nice, but R has no real set type...
Anyway, I may just sit this one out.

**Comment by dcdillon** [comment]
OK.  I've done some more investigation and I guess I am going to need a more specific example to make this work.  If you can provide one @coatless, I will take a look.

**Comment by dcdillon** [comment]
And actually (after smoking a cigarette and thinking about it) it would seem that passing in anything as a `std::set` is inherently dangerous.  Given that R doesn't have a set type.  This means that you could pass something in, and get only the unique elements in it.  This seems less than desirable.

My recommendation is that we abandon this line of thinking and close the issue.

**Comment by kevinushey** [comment]
I agree with @dcdillon here -- since R doesn't actually have a `std::set` analog there isn't really a well-defined exporter.

**Comment by eddelbuettel** [comment]
Yep, that's now three of us who said the same thing so time to close this.
