### ISSUE TITLE
More flexible attributes

### ISSUE THREAD

**Issue by romainfrancois** [RcppCore/Rcpp#37]
It would be useful for packages to be able to extend attributes. Package `foo` could register a `foo::bar` attribute to do something about a function, a class, whatever ...

I have one use case in mind for this in `dplyr` where it would be nice to be able to register hybrid handlers as: 

```
// [[dplyr::handler(hitchhiker)]]
Result* hitchhiker_handler( SEXP, const LazySubsets&, int ){
    return new Hitchhiker ;        
}
```

See the [hybrid evaluation](https://github.com/hadley/dplyr/blob/master/vignettes/hybrid-evaluation.Rmd) vignette for context.

**Comment by coatless** [comment]
I think this issue can be closed out of the Rcpp tracker as the project has taken root over at Rcpp11/attributes.

Please close. (Tagging #506)
