### ISSUE TITLE
How to Get Pointer of Underlying Object of Rcpp Class

### ISSUE THREAD

**Issue by tqchen** [RcppCore/Rcpp#379]
The Rcpp class offers a great way to wrap a S4 class from existing class. However, we find the following use-case, where we need to get the underlying pointer from Rcpp Class object. As well as constructing a new Rcpp class from C++ side

```c++
class MyClass {
public:
   static void SaveList(SEXP list, const std::string& filename) {
          Rcpp::List data_lst(list);
          std::vector<MyClass *> internals(data_lst[i]);
          for (size_t i = 0; i < data_lst.size(); ++i) {
               SEXP obj = data_lst[i];
               // Need to Get internal pointers from S4 MyClass object
               internals[i] = GetPtr<MyClass>(obj);
          }
          SomeRealSave(internals, filename);
   }
   static void LoadList(const std::string& filename) {
          std::vector<MyClass > internals;
          SomeReadLoad(&internals);
          Rcpp::List out(internals.size());
          for (size_t i = 0; i < internals.size(); ++i) {
              // need to construct a MyClass object from C++ side
              out[i] = MyClassConstructor(internals[i]);
          }
         return out;
   }
};

RCPP_MODULE(MyClass) {
     class_<MyClass>("MyClass");

     function("save.myclass.list", &Array::SaveList);
     function("load.myclass.list", &Array::LoadList);
}
```

I realized that this is possible to wrap our own struct by external pointer, but seems that duplicates what Rcpp class offers. I could not find "official solution" to this problem, so I am posting an issue here.

**Comment by eddelbuettel** [comment]
I do not know what your question is.  For eg `Rcpp::NumericVector x` you can use `&(x[0])`; I think the iterator `x.begin()` should also work.  That works the same for other vector types but obviously not for all `SEXP` mapped.

This also seems somewhat misplaced here.  Could you maybe ask on rcpp-devel?  You get more eyeballs too.   So if you do not mind I'll close this here in due course.

**Comment by tqchen** [comment]
Thanks for the response. My Array I do not mean specifically NumericVector. But some customized class(in our case, Array that can sit on GPU). And the problem is to save a list of such Objects. I have updated the original question to reflect this

**Comment by eddelbuettel** [comment]
Let's not discuss here.  Rcpp-devel, code is welcome.   Do explain why you expect Rcpp to cover random objects you may get rfom elsewhere (eg GPU).  That may simply be outside of our scope.

**Comment by tqchen** [comment]
Thanks, I have posted the question to the rcpp-devel

**Comment by eddelbuettel** [comment]
I am not seeing it.  Posting is restricted to those registered, and requires posting from the same address.

**Comment by tqchen** [comment]
I see, seems I was still waiting for the pending membership of the maillist. I will post later once it get approved, or ask @thirdwing to post it if he get a chance

**Comment by eddelbuettel** [comment]
There is no approving or denying.  You register with an email address, mailman sends you a post with a link (as I recall, or some similar handshake) to which you reply, and afterwards you have posting privileges from that account.   But if you don't do that you cannot post.

**Comment by tqchen** [comment]
I see, seems my previous email address somehow did not received the confirmation. I sent it with another email. Thanks!
