### ISSUE TITLE
is__module_object leads to error when checking non-module object

### ISSUE THREAD

**Issue by tqchen** [RcppCore/Rcpp#380]
```c++
#include <Rcpp.h>

using namespace Rcpp;

class MyClass{
};

RCPP_EXPORT_CALSS(MyClass)

// [[Rcpp::export]]
bool check(RObject m)
{
    return is<MyClass>(m);
}

RCPP_MODULE(test) {
     class_<MyClass>("MyClass");
}
```
If we call check from R's side by passing in a non-module object. It will report error "External pointer is expected", instead of returning false. 

The problem is here https://github.com/RcppCore/Rcpp/blob/0a43747be6c7b88fec6717a45034e2749012dddf/inst/include/Rcpp/api/meat/is.h#L153

Maybe need a explicit check of ext ptr type first before converting to XPtr

**Comment by thirdwing** [comment]
`if (TYPEOF(m) == EXTPTRSXP)`

**Comment by tqchen** [comment]
Directly check won't work, since that object is a S4, and I guess we need to check type of env.get(".cppclass")

**Comment by thirdwing** [comment]
See the code below, I think it is what you want.

```
#include <Rcpp.h>                                                               
                                                                                 
// [[Rcpp::export]]                                                                                                 
void check(Rcpp::RObject m) {                                                   
    SEXP attrs = ATTRIB(m);                                                     
    Rcpp::List lst(attrs);                                                      
    std::vector<std::string> names = lst.names();                               
    for (size_t i = 0; i < names.size(); i++) {                                 
        Rcpp::Rcout << names[i] << std::endl;                                   
    }                                                                           
                                                                                
    Rcpp::List lst2 = Rcpp::List(lst[1]);                                       
                                                                                
    for (size_t i = 0; i < lst2.size(); i++) {  
        Rcpp::Rcout << Rcpp::as<std::string>(lst2[i]) << std::endl;   
    }                                                                           
}       
```

```
> x = as.array(c(1,2,3))
> mat = mx.nd.array(x, mx.cpu(0))
> check(mat)
.xData
class
Rcpp_MXNDArray
```

**Comment by tqchen** [comment]
Yap :) However, I think this may be something that should be solved by ```Rcpp::is<NDArray>(mat)```
in the future

**Comment by eddelbuettel** [comment]
But 

```{sh}
edd@don:~/git/rcpp(master)$ ag NDArray
edd@don:~/git/rcpp(master)$ 
```

ie `NDArray` is not a type we know, define or support.  How could we have a proper `is<>` for it then?

**Comment by tqchen** [comment]
Sorry for confusion, ```NDArray``` is a class declared by RCPP_EXPORT_CLASS.

Discussed with @thirdwing , seems it is indeed a logical error in current is. Can be fixed by either

 check if object is S4 here https://github.com/RcppCore/Rcpp/blob/0a43747be6c7b88fec6717a45034e2749012dddf/inst/include/Rcpp/is.h#L38-L43

check if  return value of env.get is R_NilValue here
https://github.com/RcppCore/Rcpp/blob/0a43747be6c7b88fec6717a45034e2749012dddf/inst/include/Rcpp/api/meat/is.h#L153

**Comment by tqchen** [comment]
In current code,  say if MyClass is exported by RCPP_EXPORT_CLASS. And we check

```c++
is<MyClass>(some INTEXP )
```

It dispatches to https://github.com/RcppCore/Rcpp/blob/0a43747be6c7b88fec6717a45034e2749012dddf/inst/include/Rcpp/api/meat/is.h#L151 And env.get(".cppclass") cannot successfully return a valid external pointer  because it does not exist.

So instead of return a false, it throws an Error saying things cannot be converted to XPtr

**Comment by tqchen** [comment]
To fix this, we can  check if the return type of env.get(".cppclass") is External Ptr here, and simply return false if it is not.

**Comment by eddelbuettel** [comment]
If you want/need special behaviour for _your_ class, can you not write a function in _your_ library to deal with it?

**Comment by tqchen** [comment]
To be clear, this is not special behavior? As the ```MyClass``` is exposed by RCPP_MODULE already, and declared by RCPP_EXPORT_CLASS. 

I suppose that the check ```is<MyClass>(sexp)``` should return false for the normal integer SEXP? I am totally fine not promoting such change in Rcpp, but I do see this is can benefit users of  RCPP_MODULE

**Comment by eddelbuettel** [comment]
I may still misunderstand the issue but I think you expect Rcpp Modules to do more than it does, and apart from you nobody has brought such expectations forward in the five years we used Rcpp Modules.

So my intuitive feeling is that maybe you need to adjust your expectations. Rcpp Modules is not a parser of your class or library code.  It does some things well enough, and things that are missing ... will be missing until someone (you ?) contributes them.  But posting issue after issue "it should do this or that" will not get us there.  Sorry.  Again, I may be missing something obvious too.

But maybe you can start by _package-local_ code in your package, and then try to convince us that some generic code is general enough to be moved over into Rcpp itself?

**Comment by tqchen** [comment]
Thanks Dirk, Yes. I think we will do it in this way. I am opening the issue to suggest solutions(as in my previous post) and see if it makes sense. I guess writing it out will make it more clear.

**Comment by tqchen** [comment]
created a PR https://github.com/RcppCore/Rcpp/pull/381 on this

**Comment by thirdwing** [comment]
Fixed in #381

**Comment by eddelbuettel** [comment]
Strictly speaking we don't know yet as the tests are not yet done :)    But appreciate the close nonetheless.   And we _will_ get back to your gist and work down the issue tickets.  Promised.

**Comment by thirdwing** [comment]
Sorry for this.

**Comment by eddelbuettel** [comment]
It is more work to get a neutral branch to build from so I just merged and am testing now ...

**Comment by eddelbuettel** [comment]
Looks good -- it just finished and we have what appears to be no new issue.  Just the usual problem of tests failing when `Suggests:` packages are needed for tests and examples as I install only `Depends:`...
