### ISSUE TITLE
Rcpp::is_na() is ambiguous for doubles.

### ISSUE THREAD

**Issue by dcdillon** [RcppCore/Rcpp#386]
``` c++
// [[Rcpp::export]]
bool IsReallyNA(double _val)
{
  return Rcpp::is_na(_val)
}
```

```
MSPDumper.cpp:384:26: error: call of overloaded ‘is_na(double&)’ is ambiguous
   return Rcpp::is_na(_val);
```

This should probably work.  Easily overcome however by using `Rcpp::NumericVector::is_na()`.

**Comment by eddelbuettel** [comment]
Time to once again my overdue-for-a-refactoring `Date` and `Datetime` classes:

```r
R> cppFunction('bool isna(double x) { return Rcpp::is_na(x); }')
file2c5862b580ce.cpp: In function ‘bool isna(double)’:
file2c5862b580ce.cpp:6:43: error: call of overloaded ‘is_na(double&)’ is ambiguous
 bool isna(double x) { return Rcpp::is_na(x); }
                                           ^
file2c5862b580ce.cpp:6:43: note: candidates are:
In file included from /usr/local/lib/R/site-library/Rcpp/include/Rcpp/sugar/functions/functions.h:36:0,
                 from /usr/local/lib/R/site-library/Rcpp/include/Rcpp/sugar/sugar.h:31,
                 from /usr/local/lib/R/site-library/Rcpp/include/Rcpp.h:70,
                 from file2c5862b580ce.cpp:1:
/usr/local/lib/R/site-library/Rcpp/include/Rcpp/sugar/functions/is_na.h:91:49: note: Rcpp::sugar::IsNa_Vector_is_na<Rcpp::DatetimeVector> Rcpp::is_na(const Rcpp::DatetimeVector&)
 inline sugar::IsNa_Vector_is_na<DatetimeVector> is_na( const DatetimeVector& x){
                                                 ^
/usr/local/lib/R/site-library/Rcpp/include/Rcpp/sugar/functions/is_na.h:94:45: note: Rcpp::sugar::IsNa_Vector_is_na<Rcpp::DateVector> Rcpp::is_na(const Rcpp::DateVector&)
 inline sugar::IsNa_Vector_is_na<DateVector> is_na( const DateVector& x){
                                             ^
file2c5862b580ce.cpp:6:46: warning: control reaches end of non-void function [-Wreturn-type]
 bool isna(double x) { return Rcpp::is_na(x); }
                                              ^
make: *** [file2c5862b580ce.o] Error 1
ccache g++ -I/usr/share/R/include -DNDEBUG    -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/tmp/Rtmp8uZIBL"    -fpic  -g -O3 -Wall -pipe -Wno-unused -pedantic -c file2c5862b580ce.cpp -o file2c5862b580ce.o
/usr/lib/R/etc/Makeconf:143: recipe for target 'file2c5862b580ce.o' failed
Error in sourceCpp(code = code, env = env, rebuild = rebuild, showOutput = showOutput,  : 
  Error 1 occurred building shared library.
R> 
```

**Comment by dcdillon** [comment]
Did some more digging on this.  It would seem that there really aren't any `Rcpp::is_na()` functions defined *except* for the `Datetime` stuff that shows up in this error.  The `is_na()` functions that get used are in `Rcpp::traits` and all require an `RTYPE`.

I think we should add functions `is_na()` in the `Rcpp` namespace for the c++ primitives.  These could easily be added to `inst/include/Rcpp/sugar/functions/is_na.h`.  I've tested this for double and it seems to work.  Any objections to doing the same for `int, long, etc.`?

**Comment by eddelbuettel** [comment]
R generally defines NA only for the types it cares about -- do a quick `ag NA_ /usr/share/R/include/` to see 
- `NA_INTEGER` (also `NA_LOGICAL`) and 
- `NA_STRING`.  

So the real one is from IEEE, the others are R-only.  So `long` seems out of scope unless you want to map (bitwise?)

Also, I keep going back to the [nice SO answer](http://stackoverflow.com/questions/26241085/rcpp-function-check-if-missing-value/26262984#26262984) by @kevinushey which I have been meaning to turn into 
-  a post on the Rcpp Gallery and 
-  s starting point for more cleanly adding R function in the `namespace R` we use only for d/p/q/r functions now

**Comment by dcdillon** [comment]
Gotcha.  In that case, I would think adding `Rcpp::is_na(int rhs)`, `Rcpp::is_na(double rhs)`, and perhaps `Rcpp::is_na(const char *)` would just make the interface a bit nicer.

**Comment by dcdillon** [comment]
So I've done some more investigating on this and there are some "inconsistencies" that probably need to be resolved at some point:

in `Rcpp/internal/na.h`:

```c++
inline bool Rcpp_IsNA(double x) {
    return R_IsNA(x);
}
```

in `Rcpp/traits/is_na.h`:

```c++
template <>
inline bool is_na<REALSXP>(double x) {
    return internal::Rcpp_IsNA(x) || internal::Rcpp_IsNaN(x);
}
```

At any rate, you can see that there are two versions of `is_na(double)` that have different returns.  This begs the question, "Which one is correct?" for some definition of correct.

I would think that once that is determined, that version should be promoted to the `Rcpp` namespace for convenience.

**Comment by coatless** [comment]
I know this is a bit old, but I'd like to 86 this issue.

The only reason to keep it open is I can't find any addition of `Rcpp::is_na(int rhs)`, `Rcpp::is_na(double rhs)`, or `Rcpp::is_na(const char *)` in [inst/include/Rcpp/internal/na.h](https://github.com/RcppCore/Rcpp/blob/876d635b45e2c334de4b0533deb1ce2126c87dc4/inst/include/Rcpp/internal/na.h)

The reason in favor of closing the issue are the definitions are consistent due to the following:

From [Kevin's Truth table on SO](http://stackoverflow.com/questions/26241085/rcpp-function-check-if-missing-value/26262984#26262984):

| Function | NaN | NA |
|-----------|------|------|
| ISNAN     |  T    | T       |
| R_IsNaN  |  T     | F       |
| ISNA        |  F     | T       |
| R_IsNA     |  F     | T      |

Thus, the `Rcpp::internal::Rcpp_IsNA` is mapping correctly to the `R_IsNA` function. The downside to this implementation is extra overhead in terms of function calls (e.g. why is it not directly calling `R_IsNA`?)

Meanwhile, the public facing interface matches appropriately to the public facing interactive R functions: 

| Function     | NaN | NA |
|-----------|------|------|
| Rcpp::is_na  | T  | T  |
| Rcpp::is_nan |  T  | F  |

| Function     | NaN | NA |
|-----------|------|------|
| is.na  | T  | T  |
| is.nan |  T  | F  |

**Comment by eddelbuettel** [comment]
Just replace the `double` with `Rcpp::NumericVector`:

```cpp
#include <Rcpp.h>

// [[Rcpp::export]]
bool isReallyNA(Rcpp::NumericVector val) {
  return Rcpp::all(Rcpp::is_na(val));
}

/*** R
isReallyNA(1)
isReallyNA(1L)
isReallyNA(NA)
isReallyNA(NaN)
*/
```

**Comment by kevinushey** [comment]
I added the introduction around `R_IsNA()` -> `Rcpp_IsNA()` because I wanted to see if I could do something more performant than what R does. Honestly though, we should likely just rip that code out and just always call `R_IsNA()` / `R_IsNaN()`.

**Comment by eddelbuettel** [comment]
It vexed because some work well for scalars (ie R's) and some work well for `SEXP` objects (ours).   Would be nice to have a catch-all but ... oh well.
