### ISSUE TITLE
investigate compiler warnings with `-Wconversion`

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/Rcpp#391]
`sourceCpp()` this with `-Wconversion`:

```
#include <Rcpp.h>
using namespace Rcpp;

//[[Rcpp::export]]
int fibonacci(const int x) {
  if(x < 2){
    return(x);
  }else{
    return fibonacci(x-1)+fibonacci(x-2);
  }
}
```

I see a number of (potentially legitimate) warnings, like:

```
In file included from Untitled.cpp:1:
In file included from /Users/kevinushey/Library/R/3.2/library/Rcpp/include/Rcpp.h:27:
In file included from /Users/kevinushey/Library/R/3.2/library/Rcpp/include/RcppCommon.h:158:
/Users/kevinushey/Library/R/3.2/library/Rcpp/include/Rcpp/internal/export.h:32:44: warning: implicit conversion loses integer precision: 'R_xlen_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
                        const char* y = char_get_string_elt( x, i ) ;
                                        ~~~~~~~~~~~~~~~~~~~     ^
```

We should double-check that these aren't regressions from attempting to support long vectors, and see if we can handle / suppress these warnings.

**Comment by thirdwing** [comment]
In `export.h`, we pass `i` with type of `R_xlen_t`:

```
std::wstring as_string_elt__impl( SEXP x, R_xlen_t i, Rcpp::traits::true_type ){
    const char* y = char_get_string_elt( x, i ) ;
    return std::wstring(y, y+strlen(y) ) ;
}
```

And `char_get_string_elt` is defined to accept `int`:

```
const char* char_get_string_elt(SEXP, int) ;
```

**Comment by coatless** [comment]
@thirdwing: FYI the commit referenced above never made it from your local Rcpp fork into the main Rcpp repo.

**Comment by thirdwing** [comment]
I know what you mean. However, there are more conversion warnings. It will take some time to clean all of them.

**Comment by eddelbuettel** [comment]
AFAIK we never stated that `-Wconversion` was a coding standard.  I get by using 

```make
CXXFLAGS +=           -O3 -Wall -pipe -Wno-unused -pedantic
```

@kevinushey Any thoughts?

**Comment by kevinushey** [comment]
It's not really that we want `-Wconversion` per se; it's more that some of the warnings look like legitimate issues that might cause problems when using long vectors with Rcpp. For example, the posted warning:

```
/Users/kevinushey/Library/R/3.2/library/Rcpp/include/Rcpp/internal/export.h:32:44: warning: implicit conversion loses integer precision: 'R_xlen_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
                        const char* y = char_get_string_elt( x, i ) ;
                                        ~~~~~~~~~~~~~~~~~~~     ^
```

would imply that attempting to index into a long string vector might fail with this API, due to the unintended conversion from `R_xlen_t` to `int`.

I don't think we need to be `-Wconversion`-clean, but I think it's worth investigating some of these shortening conversions and see if they're indicative of a deeper issue.
