### ISSUE TITLE
RCPP_CTOR_ASSIGN compiler warning in Rcpp/Module.h

### ISSUE THREAD

**Issue by jpritikin** [RcppCore/Rcpp#410]
I might be able to figure out the cause of this warning, but you could probably figure it out much faster.

````
/opt/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/Module.h: In copy constructor ‘Rcpp::CppClass::CppClass(const Rcpp::CppClass&)’:
/opt/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/Module.h:404:23: warning: base class ‘class Rcpp::S4_Impl<Rcpp::PreserveStorage>’ should be explicitly initialized in the copy constructor [-Wextra]
      RCPP_CTOR_ASSIGN(CppClass)
                       ^
/opt/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/macros/interface.h:27:1: note: in definition of macro ‘RCPP_CTOR_ASSIGN’
 __CLASS__( const __CLASS__& other ){                                           \
 ^
/opt/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/Module.h: In copy constructor ‘Rcpp::CppObject::CppObject(const Rcpp::CppObject&)’:
/opt/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/Module.h:416:26: warning: base class ‘class Rcpp::S4_Impl<Rcpp::PreserveStorage>’ should be explicitly initialized in the copy constructor [-Wextra]
         RCPP_CTOR_ASSIGN(CppObject)
                          ^
/opt/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/macros/interface.h:27:1: note: in definition of macro ‘RCPP_CTOR_ASSIGN’
 __CLASS__( const __CLASS__& other ){                                           \
 ^
````

**Comment by eddelbuettel** [comment]
1. Complete reproducible example, please, or it is no bug report or issue.
2. What compiler? What OS? What version of things?
3. Just add `-Wno-extra` to your compiler options to suppress this. It is a _warning_.

**Comment by jpritikin** [comment]
Rcpp 0.12.2, R 3.2.2, gcc (Tanglu 5.2.1-16) 5.2.1 20150903

**Comment by eddelbuettel** [comment]
g++-5 is known to be pickier.  Pull requests welcome.

**Comment by jpritikin** [comment]
I'm willing to spend some time to investigate. Can you give me a hint about what to fix?

**Comment by eddelbuettel** [comment]
Really appreciate this -- the 90k lines of code for Rcpp can be very convoluted and tough to decipher. It's start by seeing what `RCPP_CTOR_ASSIGN` is made of and the try to find the copy constructor this warns about.

**Comment by jpritikin** [comment]
The warning is solved by changing this,

````
#define RCPP_CTOR_ASSIGN1(__CLASS__)                                           \
__CLASS__( const __CLASS__& other ){                                           \
    Storage::copy__(other) ;                                                   \
}                                                                              \
````

to this

````
#define RCPP_CTOR_ASSIGN(__CLASS__)                                            \
  __CLASS__( const __CLASS__& other ) : Base(other) {			\
    Storage::copy__(other) ;                                                   \
}                                                                              \
````

However, this requires (for the macro) that there is only 1 base class. For users of `RCPP_GENERATE_CTOR_ASSIGN`, the change is not needed. So maybe the way forward is to create 2 versions of `RCPP_CTOR_ASSIGN`, one with the `Base(other)` thing and one without.

Comments?

**Comment by eddelbuettel** [comment]
In that case we would need two distinct versions of `RCPP_CTOR_ASSIGN` as you can't have two with the same name; maybe keep the existing one as `RCPP_CTOR_ASSIGN_ORIG` or something.   We could even flag it to be deprecated in 12+ months.  All this assuming that reverse depends check don't reveal anything nasty.

**Comment by jpritikin** [comment]
Hm, it's it redundant to initialize the base class and also do `Storage::copy__` ?

**Comment by eddelbuettel** [comment]
This can be closed as @thirdwing reminds us.
