### ISSUE TITLE
Nullable additions

### ISSUE THREAD

**Issue by dcdillon** [RcppCore/Rcpp#421]
I would like to add two convenience member functions to `Rcpp::Nullable<T>` specifically:

```c++
T Nullable::as()
{
    return T(m_sexp);
}

T Nullable::clone() const
{
    return T(Rcpp:::clone(m_sexp));
}
```

These are analogous to the `Rcpp::as` and `Rcpp::clone` functions and just add convenience to the `Nullable` class.

Any objections?

**Comment by eddelbuettel** [comment]
That sounds pretty good, is un-objectionable as it also only 'grows' the interface not altering anything existing and completes the interface.  PR away, if your fingers aren't frozen yet :)
