### ISSUE TITLE
Document required TeXlive packages for full build

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#422]
On Debian/Ubuntu:
```
# inconsolata.sty is used in pdf manual; our vignettes use extra fonts too
sudo apt-get install texlive-fonts-extra      
```

What is it from brew / on OS X?

**Comment by thirdwing** [comment]
I don't install latex using `brew`.

I installed the MacTex from https://tug.org/mactex/mactex-download.html

It is around 2.5 GB and I have everything I need to build vignettes.

**Comment by eddelbuettel** [comment]
Dang. 2.5gb is a lot. 

When I started with Linux 'we all' used a dvi/ps manual by Linus's office mate in Helsinki, Lars Wirzenius. It had this glorious line of how you could fit an entire Linux system into 200mb.

We may "soon" have a single CRAN package bigger than that as BH is about half-way there....

**Comment by thirdwing** [comment]
Yes, it is quite big.

It is more like `sudo apt-get install texlive-full`.

**Comment by eddelbuettel** [comment]
Yes. I think I saw that with some Docker containers.  

Just adding texlive* adds, as I recall, just under 1gb. It is huge.  Which I why I usually tell Travis not to bother with vignettes -- just installing all the texlive stuff adds a minute or more to each run.  One day when we're fully containerized I'll revisit.

**Comment by dcdillon** [comment]
Yeah...i fought with this one today a bit (and complained to dirk which resulted in this issue).  Just a minor annoyance when getting things set up in a new environment for development.

**Comment by eddelbuettel** [comment]
Come to think about it, I could have sent you to one @cboettig 's "fatter" Rocker containers (and their build recipes) because those too contain everything we need to put tests, vignettes, packages, ... together.

**Comment by dcdillon** [comment]
Yes, but then I'd have to admit (probably on a resume or something) that I'm involved with R in some way :P.
