### ISSUE TITLE
Matrix ctor that takes std::vector< std::vector< T > >

### ISSUE THREAD

**Issue by dcdillon** [RcppCore/Rcpp#429]
Would be nice to have a `Matrix< T >` constructor that takes `std::vector< std::vector< T > >` where each inner `vector< T >` represents a column.  Just a convenience.

**Comment by eddelbuettel** [comment]
Not convinced.   `vector<vector<double> >` is a C++ programmers idiom, yet there are a bazillion better matrix libraries and we already support two rather well.

**Comment by eddelbuettel** [comment]
Maybe a free floating help function would do?

**Comment by dcdillon** [comment]
Yeah.  That would be perfect.  Specifically a function that takes N vectors of length M and turns them into the columns of a matrix.  I can write it...what should it be called?

**Comment by eddelbuettel** [comment]
Maybe `Rcpp::NumericMatrix::create()`, copying the very useful function for Lists?

**Comment by dcdillon** [comment]
That works.  I'll take a poke at it this weekend and see if I can get something together.

**Comment by coatless** [comment]
As we are on the topic of matrices.... Any thoughts as to whether this feature should go ahead as is?

**Comment by eddelbuettel** [comment]
How would we avoid n times `memcpy()` if the incoming matrix is `vector<vector<T>>` (which is a brain-dead but common idiom).

**Comment by dcdillon** [comment]
Let's scrap this.  I can address it in honey.

**Comment by eddelbuettel** [comment]
And done.

**Comment by dcdillon** [comment]
Either that or create a variable number of arguments cbind that can take a variety of inputs.

**Comment by coatless** [comment]
Awh shucks... Everytime I have to step out things just move too fast =(

I do not see an easy way outside of doing a `memcpy()`. Right now, I do an `n` loop over the outer `vector`, use iterators and `std::copy()` to convert. 

Regarding honey, is that slated to be included in `Rcpp` akin to `algorithms` or? 

(Tagging #506)

**Comment by dcdillon** [comment]
Honey is an add on package that isn't quite ready to go yet.
https://github.com/dcdillon/RcppHoney.

I am not sure if there is a better way than memcpy, but I think I came up
with a way to defer the actual work until a return to R space where we
likely have to do a copy anyhow.
