### ISSUE TITLE
add a utility for generating pre-compiled headers?

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/Rcpp#430]
One of the issues when compiling TUs using Rcpp is the the long compile times.

A potential mediator to this would be to have some mechanism for generating, and using, precompiled headers (e.g. pre-compiling all of `<Rcpp.h>`). I have a utility in `RcppNT2` that does this (very helpful in a `sourceCpp()` context, as compiles are ~3x faster): https://github.com/RcppCore/RcppNT2/blob/master/R/precompiled-headers.R

Would it make sense to add this to `Rcpp`, e.g.

``` R
precompile <- function(header) {
    # precompile header
}
```

and ensure that `sourceCpp()` uses that precompiled header if available?

One big issue with this is that changing of e.g. optimization levels requires the precompiled header to be re-generated, and this could produce errors that users find difficult to work with. However, it could be very useful when iterating in a `sourceCpp()` context.

**Comment by jjallaire** [comment]
Another problem you run into is that upgrading versions of R (for Rcpp) or
the OS kernel (for all other libraries) also invalidate the precompiled
headers. For this reason I'd recommend that this be done per-session rather
than persistently.

**Comment by kevinushey** [comment]
Good idea -- perhaps the compiled headers could be placed in the `tempdir()` of a session, and Rcpp plugins could search for a pre-compiled header within that temporary directory?

**Comment by jjallaire** [comment]
Yeah, that makes sense.

**Comment by eddelbuettel** [comment]
I remain a big fan of [ccache](https://ccache.samba.org/).  Could that be an alternative?

**Comment by kevinushey** [comment]
I tried out ccache as well; it works fine when re-compiling the _same_ translation unit multiple times, but as soon as I changed anything within I was stuck waiting ~20s to compile. No idea if this is an artefact of me using ccache incorrectly, or that it's outside the realm of ccache's work.

**Comment by eddelbuettel** [comment]
No, that's it.  It saves your bacon when you, say, alter the R code or the documentation as the compilation of _unchanged_ code becomes 'free' for repeated use.  No more, no less, and no setup.

**Comment by kevinushey** [comment]
Got it -- precompiled headers help specifically in the case where you are e.g. iterating on a file using `Rcpp::sourceCpp()`; e.g. in `RcppNT2` it helps to bring compile times from ~20s to just ~3s (ie, makes it feasible to do).
