### ISSUE TITLE
SubsetProxy should validate input vector sizes

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/Rcpp#431]
Currently, the `get_indices()` functions (which are called in the constructor) do not validate the input sizes We should validate early that the right-hand side vector is either length 1, or same length as the left-hand side vector.

https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/vector/Subsetter.h#L40

Note that we do perform this check when actually performing the subset (e.g. https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/vector/Subsetter.h#L56-L66) but I think this is happening too late (we should validate before we do any work)

**Comment by eddelbuettel** [comment]
@thirdwing has something [here](https://github.com/thirdwing/Rcpp/commit/216c5220bcb84778a656b3496d0f1803b973ef61).

**Comment by thirdwing** [comment]
I don't think `lhs` and `rhs` need to be the same length.

```cpp

#include <Rcpp.h>

using namespace Rcpp;

//[[Rcpp::export]]
IntegerVector test(IntegerVector x, IntegerVector y) {
  return x[y];
}

/*
> Rcpp::sourceCpp("test.cpp")
> a <- c(1:20L)
> b <- c(2L, 13L)
> test(a, b)
[1]  3 14
*/
```

**Comment by kevinushey** [comment]
Whoops. Sorry, that's only true for logical vectors -- of course, we should be able to subset with vectors of various lengths for integers, numerics, etc...

**Comment by kevinushey** [comment]
Given the segfaulting line of code

    IntegerVector charColNumbers = colNumbers[charCols-1];

and the offending line from the `gdb` stack trace in Rcpp (https://github.com/RcppCore/Rcpp/blob/b112a67b8a1246e8b7040725db9b81db282ede1d/inst/include/Rcpp/vector/Subsetter.h#L199)

    199                 output[i] = lhs[ indices[i] ];

We can see that we're subsetting an IntegerVector with a 
The question is, where does the out-of-bounds access lie?

1) `output[i]`?
2) `indices[i]`?
3) `lhs[indices[i]]`?
