### ISSUE TITLE
20-length limit

### ISSUE THREAD

**Issue by kn1g** [RcppCore/Rcpp#435]
Hi, does the 20-length limit for lists and dataframe has a deeper meaning?
Is it somehow possible to make an elegant workaround or can I somehow edit the code easily? 
I need a dataframe with way more columns...

Thanks and best regards
Nico

**Comment by eddelbuettel** [comment]
Nico,

That's FAQ, but I no longer remember where we gave the best answer: rcpp-devel, stackoverflow or here.  So you may have to look.

In short, these are macro-generated and **yes** there is a cost to having them. The usual answer is that you can always nest: have an outer list of 20, and each of those can have 20 ...

**Comment by thirdwing** [comment]
@eddelbuettel I think you mean this one: http://stackoverflow.com/questions/27371543/how-many-vectors-can-be-added-in-dataframecreate-vec1-vec2

**Comment by kn1g** [comment]
Thanks Dirk and thanks thirdwing. The link was great!
In this context I read about Rcpp11 the first time. I will try to use Rcpp11 in the future.
But for now I will just nest it in lists as a shortcut.
I really appreciate all the support, especially when Dirk is answering nearly in real-time questionss on all the different platforms. 
Thanks an best regards
Nico

**Comment by eddelbuettel** [comment]
It is a good question, and I will try to add it to the Rcpp FAQ.  As for Rcpp11 vs Rcpp:  you may want to compare the rate of more recent releases and commits between them; Rcpp11 has not seen that many updates of late.  Which may of course change at some point...    In any event, you *can* use C++11 and C++14 with Rcpp just as well (but not [yet] always for CRAN uploads also aiming at Windows etc pp).

**Comment by dcdillon** [comment]
Would it be possible to do something with variadic templates for this IF it's in C++11 or greater when compiled?
