### ISSUE TITLE
Issue while building on R on Ubuntu 15.04

### ISSUE THREAD

**Issue by zaid-golwala** [RcppCore/Rcpp#436]
Hi,

I get following error while building Rcpp on R on Ubuntu 15.04 :

+ R CMD check --no-vignettes --timings Rcpp
* using log directory ‘/home/jenkins/workspace/Rlang_Rcpp_Ubuntu15.04/Rcpp.Rcheck’
* using R version 3.2.3 (2015-12-10)
* using platform: powerpc64le-unknown-linux-gnu (64-bit)
* using session charset: UTF-8
* using option ‘--no-vignettes’
* checking for file ‘Rcpp/DESCRIPTION’ ... OK
* this is package ‘Rcpp’ version ‘0.12.3’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... NOTE
Found the following hidden files and directories:
  .git
These were most likely included in error. See section ‘Package
structure’ in the ‘Writing R Extensions’ manual.
* checking for portable file names ... ERROR
Found the following files with duplicate lower-cased file names:
  src/attributes.cpp
File names must not differ just by case to be usable on all R
platforms.
Please rename the files and try again.
See section ‘Package structure’ in the ‘Writing R Extensions’ manual.
 OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘Rcpp’ can be installed ... ERROR
Installation failed.

**Comment by eddelbuettel** [comment]
Misunderstanding your part: do *not* run `R CMD check` on a _directory_.   Do

```bash
git clone https://github.com/RcppCore/Rcpp.git rcpp
R CMD  build rcpp
R CMD check Rcpp_0.12.3.2.tar.gz    # adjust version as needed
```

That will work. It is what Travis does every time, and what we do.

**Comment by zaid-golwala** [comment]
I tried the way you have suggested but I get a different kind of error but it is related to duplication of attributes.cpp . Please find attached the error.
[Rccp_error.txt](https://github.com/RcppCore/Rcpp/files/136027/Rccp_error.txt)

**Comment by zaid-golwala** [comment]
I get following error when i try the build command : 
+ R CMD build --keep-empty-dirs --no-resave-data --no-build-vignettes Rcpp
* checking for file ‘Rcpp/DESCRIPTION’ ... OK
* preparing ‘Rcpp’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* running ‘cleanup’
* installing the package to process help pages
* building the PDF package manual
Hmm ... looks like a package
Converting Rd files to LaTeX ...
Creating pdf output from LaTeX ...
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  Running 'texi2dvi' on 'Rd2.tex' failed.
LaTeX errors:
! LaTeX Error: File `inconsolata.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

! Emergency stop.
<read *> 
         
l.276 ^^M
         
!  ==> Fatal error occurred, no output PDF file produced!
Output:
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
LaTeX2e <2015/10/01> patch level 2
Babel <3.9m> and hyphenation patterns for 2 languages loaded.
(./Rd2.tex (/usr/share/texlive/texmf-dist/tex/latex/base/book.cls
Document Class: book 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/bk10.clo))
(/usr/share/R/share/texmf/tex/latex/Rd.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty)
(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)
(/usr/share/texlive/texmf-dist/tex/latex/tools/bm.sty)
(/usr/share/texlive/texmf-dist/tex/latex/base/alltt.sty)
(/usr/share/texlive/texmf-dist/tex/latex/tools/verbatim.sty)
(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty)
(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def))
(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.def))
(/usr/share/texlive/texmf-dist/tex/latex/psnfss/times.sty)

! LaTeX Error: File `inconsolata.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.276 ^^M
         
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on Rd2.log.
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  Running 'texi2dvi' on 'Rd2.tex' failed.
LaTeX errors:
! LaTeX Error: File `inconsolata.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

! Emergency stop.
<read *> 
         
l.276 ^^M
         
!  ==> Fatal error occurred, no output PDF file produced!

**Comment by JanMarvin** [comment]
You need to inconsolata.sty as pointed out by the error message. In Ubuntu it should be in texlive-fonts-extra.

**Comment by eddelbuettel** [comment]
Correct.  Or force exclusion of the manual:

```sh
R CMD build --no-build-vignettes --no-manual Rcpp 
```

which is what each and every Travis build does so that we do not have to install all of texlive...
