### ISSUE TITLE
Rcpp C++11 .Call issues under Windows

### ISSUE THREAD

**Issue by fabnicol** [RcppCore/Rcpp#441]
I'm experiencing .Call issues when running functions built with Rcpp on Windows, if my c++ code uses C++11 `std::regex` and I have found no way out so far.   

Issues only arise after packaging, not using `Rcpp::source("test.cpp")`    
.Call issues arise as soon as a regex is declared in the C++ code. Using it or no (as in std::regex_match) makes no change.    

Unlike prior questions on similar issues, I have had neither building nor linking issues.  Rcpp packages build and link fine using the C++11 plugin, making usable packages on my platform. C++11-specific  `constexpr` declarations and functions like `std::stoi` cause no issue when `std::regex` is not used.

The same packages build, install and run fine under linux, using vanilla std::regex. 

Windows platform is :    
  
    R version 3.2.3 (2015-12-10)   
    x86_64-w64-mingw32/x64 (64-bit)   
   
Running under:    

    Windows >= 8 x64 (build 9200)  
    Rcpp_0.12.3   
    Rtools 3.3.0.1959 running g++ 4.9.3 (x86_64-posix-seh, 
    built by MinGW-W64 project), normally C++11-compatible.  
    PKG_CXXFLAGS="-std=c++11"

Attached is a code chunk for testing.     

[test.cpp.txt](https://github.com/RcppCore/Rcpp/files/141171/test.cpp.txt)   

This code runs OK when built using -DNO_REG. Otherwise invoking `test::my_test(1, "1000")` returns:   

      `Error in .Call("test_my_test", PACKAGE = "test", prop, index) : 
          "test_my_test" not available for .Call() for package "test"`   

Packaging code:    
R console:  

         Rcpp::Rcpp.package.skeleton("test", attributes=TRUE, example_code=FALSE, cpp_files="test.cpp")     
         Rcpp::compileAttributes("test")   

CMD console:    

         REM paths to R/bin/x64 and Rtools/bin, Rtools/mingw_64/bin added to PATH         
         set PKG_CXXFLAGS=-std=c++11      
         R CMD build test    
         R CMD INSTALL test_1.0.tar.gz

**Comment by thirdwing** [comment]
Can you try to add `CXX_STD = CXX11` into `Makevars`?

Just like https://github.com/eddelbuettel/rcppbdt/blob/master/src/Makevars#L2

**Comment by eddelbuettel** [comment]
:+1:  

My thoughts exactly. I have a few C++11-only packages that do it too, eg

- [RcppTOML](https://github.com/eddelbuettel/rcpptoml/blob/master/src/Makevars#L3)
- [RcppCCTZ](https://github.com/eddelbuettel/rcppcctz/blob/master/src/Makevars#L3)

**Comment by fabnicol** [comment]
Done.
Only change is that I no longer need to set PKG_CXXFLAGS=-std=c++11 on a CMD console prior to building. Makevars does that OK. But the issue remains as is otherwise.
I tentatively suspect a namespace issue. I've already observed that not specifying std:: and resorting to the `using namespace std` directive in c++ code gives similar .Call package-specific issues. And libstdc++ <regex> is replete with namespaces. Just a wild conjecture.

**Comment by eddelbuettel** [comment]
You are not making sense to me.

For what it is worth, I followed your (scattered) instruction, built a basic package via `Rcpp.package.skeleton()`, copied `test.cpp` in and everything was just fine -- Ubuntu 15.10, g++ 5.2.1.

If you think that you have an issue, you need to provide (and that is unchanged) a [minimally reproducible example](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example).  And even then we may not reproduce as we don't have g++ 4.9.3 on Windows.

I'll close this for now as there is no issue.  Feel free to ask to have it reopened, but please provide something more mighty.

**Comment by kevinushey** [comment]
As @eddelbuettel said, we'll need an MRE. But it seems like symbol registration is failing, somehow (did you remember to run `Rcpp::compileAttributes()`?)

What does `RcppExports.cpp` look like in the failure case?

**Comment by fabnicol** [comment]
@eddelbuettel: Fair enough, no offense meant.

The issue is strictly Windows-specific so it comes as no surprise that you found none in your linux tests. 

Attached is an MRE. 

**Prerequisites**    latest Rtools 3.3.exe freshly installed. R 3.2.3 64 bit for Windows. Latest Rcpp CRAN package (or github built code. I tried this too).
**Instructions**   Unzip to a clean directory. Run batch file in a CMD console .   
**Testing protocol**    
   
  rcpp.bat   Path/to/R.exe   Path/to/Rtools_folder     
    
This should cause a .Call issue. Now erase your test directory and relaunch using:    
    
  rcpp.bat   Path/to/R.exe   Path/to/Rtools_folder  NOREG   
    
This should give you :
[1] 1011
as the package was now compiled without regex.

Further details @kevinushey:
Rcpp::compileAttributes() was correctly invoked.
RcppExports.cpp is invariant in either case.

**Comment by eddelbuettel** [comment]
There was no attchment.  This is GitHub.  Most people seem to prefer pointing to repositories instead.

**Comment by eddelbuettel** [comment]
Also, just stop the REG/NOREG dance.  Include what you want from std::regex in the code. Demonstrate that g++ 4.9.3 (on Windows or whereever fails).   

SIMPLE and MINIMAL reproducible examples.   We all wasted ten messages on this and still have nothing to show.  Let's try to do better.

**Comment by fabnicol** [comment]
You're right. I use Dropbox in such cases.   
[test.zip](https://www.dropbox.com/s/s8onw7jcd1nxjlh/test.zip?dl=0)

**Comment by eddelbuettel** [comment]
No, please use a GH repo.
