### ISSUE TITLE
Rcpp compilation issue on Alpine distribution

### ISSUE THREAD

**Issue by lostie** [RcppCore/Rcpp#448]
```
"Command failed (1)

Failed to run system command:

'/usr/lib/R/bin/R' --vanilla CMD INSTALL '/tmp/RtmpDPDGNf/Rcpp' --library='/app/packrat/lib/x86_64-alpine-linux-musl/3.2.3' --install-tests --no-docs --no-multiarch --no-demo
The command failed with output:
* installing *source* package 'Rcpp' ...
** package 'Rcpp' successfully unpacked and MD5 sums checked
** libs
x86_64-alpine-linux-musl-g++ -I/usr/lib/R/include -DNDEBUG -I../inst/include/ -Os -fomit-frame-pointer    -fpic  -Os -fomit-frame-pointer  -c Date.cpp -o Date.o
x86_64-alpine-linux-musl-g++ -I/usr/lib/R/include -DNDEBUG -I../inst/include/ -Os -fomit-frame-pointer    -fpic  -Os -fomit-frame-pointer  -c Module.cpp -o Module.o
x86_64-alpine-linux-musl-g++ -I/usr/lib/R/include -DNDEBUG -I../inst/include/ -Os -fomit-frame-pointer    -fpic  -Os -fomit-frame-pointer  -c Rcpp_init.cpp -o Rcpp_init.o
x86_64-alpine-linux-musl-g++ -I/usr/lib/R/include -DNDEBUG -I../inst/include/ -Os -fomit-frame-pointer    -fpic  -Os -fomit-frame-pointer  -c api.cpp -o api.o
api.cpp:40:30: fatal error: execinfo.h: No such file or directory
compilation terminated.
/usr/lib/R/etc/Makeconf:141: recipe for target 'api.o' failed
make: *** [api.o] Error 1
ERROR: compilation failed for package 'Rcpp'
* removing '/app/packrat/lib/x87_64-alpine-linux-musl/3.2.3/Rcpp'"
```

It seems related to https://github.com/RcppCore/Rcpp/issues/360 (although on a diferrent platform).

The code it is hitting seems to be https://github.com/RcppCore/Rcpp/blob/0.12.3/src/api.cpp#L40 

According to the [gnulib page](https://www.gnu.org/software/gnulib/manual/html_node/execinfo_002eh.html) it seems that for platforms that the file is missing it should only have a stub (do nothing).

> Alpine Linux is a security-oriented, lightweight Linux distribution based on musl libc
http://wiki.alpinelinux.org/wiki/Main_Page

Alpine seems to use a [different](http://www.etalabs.net/compare_libcs.html) `libc` as mentioned above

Is that the Alpine distribution be covered by the `Rcpp api.cpp` to just use a stub?

**Comment by eddelbuettel** [comment]
I would encourage you to work up a (minimal) pull request demonstrating (via Travis CI) that nothing breaks on other systems yet that it recognizes your (somewhat exotic) libc variant.   

We generally rely on that set of defines list over [here at sourceforge](https://sourceforge.net/p/predef/wiki/OperatingSystems/).  Methinks the required change may just be on one line (but possibly one line in several files).

**Comment by thirdwing** [comment]
From musl source code (http://git.musl-libc.org/cgit/musl/tree/include), there seems no `execinfo.h`.

I know GLIBC defines several macros (https://github.com/lattera/glibc/blob/master/include/features.h#L358), so we know we are using GLIBC.

I am not sure there are such macros in musl.

**Comment by eddelbuettel** [comment]
@thirdwing take a step back -- @lostie correctly pointed to [line 40](https://github.com/RcppCore/Rcpp/blob/0.12.3/src/api.cpp#L40) for `execinfo.h` but on [line 37](https://github.com/RcppCore/Rcpp/blob/0.12.3/src/api.cpp#L37) we have the very test he needs to expand.  Should not be hard, may however also be needed somewhere else.

**Comment by lostie** [comment]
I don't seem to be able to push my changes to the remote :cry: 

Here's a suggested patch: https://gist.github.com/lostie/425d11dff9c06cc9ff89

**Comment by thirdwing** [comment]
Hi @lostie 

I think there is another place need to be changed [line260](https://github.com/RcppCore/Rcpp/blob/0.12.3/src/api.cpp#L260) . Maybe more.

This change means we will only have the full backtrace info using GLIBC.

**Comment by eddelbuettel** [comment]
> I don't seem to be able to push my changes to the remote :cry:

Welcome to git(hub). You are supposed to *fork* a repo after which you can push to *your copy* after which you can (once happy) propose a pull request.   There are lots of tutorials.

**Comment by eddelbuettel** [comment]
This was taken care of in #449.

**Comment by albap** [comment]
I still have this issue with Rcpp 0.12.5

```
trying URL 'http://cloud.r-project.org/src/contrib/Rcpp_0.12.5.tar.gz'
Content type 'application/x-gzip' length 2397088 bytes (2.3 MB)
==================================================
downloaded 2.3 MB

* installing *source* package ‘Rcpp’ ...
** package ‘Rcpp’ successfully unpacked and MD5 sums checked
** libs
g++ -I/usr/include/R -DNDEBUG -I../inst/include/ -Os -fomit-frame-pointer    -fpic  -Os -fomit-frame-pointer  -c Date.cpp -o Date.o
g++ -I/usr/include/R -DNDEBUG -I../inst/include/ -Os -fomit-frame-pointer    -fpic  -Os -fomit-frame-pointer  -c Module.cpp -o Module.o
g++ -I/usr/include/R -DNDEBUG -I../inst/include/ -Os -fomit-frame-pointer    -fpic  -Os -fomit-frame-pointer  -c Rcpp_init.cpp -o Rcpp_init.o
g++ -I/usr/include/R -DNDEBUG -I../inst/include/ -Os -fomit-frame-pointer    -fpic  -Os -fomit-frame-pointer  -c api.cpp -o api.o
api.cpp:40:30: fatal error: execinfo.h: No such file or directory
compilation terminated.
/usr/lib/R/etc/Makeconf:139: recipe for target 'api.o' failed
make: *** [api.o] Error 1
ERROR: compilation failed for package ‘Rcpp’
* removing ‘/home/j/R/x86_64-pc-linux-gnu-library/3.3/Rcpp’
```

**Comment by thirdwing** [comment]
@albap Hi, you need to modify the Makevars first.

**Comment by albap** [comment]
@thirdwing 
How can I do that?
Is it something that could be automated on Alpine Linux?

**Comment by thirdwing** [comment]
You need `-D__MUSL__` in the `PKG_CXXFLAGS` to install Rcpp on Alpine.

You can add the following line

```
PKG_CXXFLAGS = -D__MUSL__
```

into Makevars (https://github.com/RcppCore/Rcpp/blob/master/src/Makevars) in the package.

**Comment by albap** [comment]
So I can't just install.package("ggplot2") (and maybe other packages) on Alpine?
I'll have to do manually, download the source code, edit Makevars.....
This is a bit inconvenient, could there be a way to set -D__MUSL__ for my entire R and have packages recognize it?

**Comment by thirdwing** [comment]
You can try with a `~/.R/Makevars` with content

```
CXXFLAGS = -D__MUSL__
```

**Comment by kevinushey** [comment]
You could also try amending the file at `file.path(R.home("etc"), "Renviron")` to set it (as an environment variable) whenever the R process is launched. You could likely just add a line

    __MUSL__=1

or something to that effect. (You could confirm this works by checking the value of `Sys.getenv("__MUSL__")` when launching R)

**Comment by eddelbuettel** [comment]
@thirdwing 's suggestion is what I would do but possibly with `+=` rather than `=`:

```
CXXFLAGS  += -D__MUSL__
CXX1XFLAGS += -D__MUSL__
```

to ensure C++ and C++11 have it set.   That will affect _all_ R builds across all packages; and at least Rcpp should take advantage of it.

**Comment by jirutka** [comment]
Can we set it in system-wide `Makeconf` instead of `Makevars`? What’s difference between them?

**Comment by thirdwing** [comment]
Not everyone has the permission to change system-wide configurations.

**Comment by kevinushey** [comment]
Basically, when `R` compiles code in a package, it calls `make` and reads in the system `Makeconf`, and then applies (potentially amending or overriding) any variables set in the appropriate `Makevars` files. If you're able to just edit the `Makeconf` file, that should be sufficient.

Reading the file at `R.home("bin")/config` is somewhat helpful (it shows how R looks up and uses the various Makefiles)

**Comment by jirutka** [comment]
> Not everyone has the permission to change system-wide configurations.

That’s not what I’ve asked. I’m maintainer of the R package in Alpine Linux, so I’m about to add `CXXFLAGS` and `CXX1XFLAGS` as the default for the package.

**Comment by sgerrand** [comment]
> Is it something that could be automated on Alpine Linux?

@albap @jirutka: 📝  This change now exists in each of the Alpine packages for R which I maintain - https://github.com/sgerrand/alpine-pkg-R/releases. I've updated the value of `R_XTRA_CPPFLAGS`, so packages like `Rcpp` now compile out of the box.

Try it out:
```
wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://raw.githubusercontent.com/sgerrand/alpine-pkg-R/master/sgerrand.rsa.pub
apk --no-cache -X http://apkproxy.heroku.com/sgerrand/alpine-pkg-R add R R-dev R-doc
```

**Comment by eddelbuettel** [comment]
Thanks for the update.  As it happens, we'll probably release a new Rcpp version within a few days so if you have some cycles to spare, could you try the current master branch here (with version 0.12.5.7 likely to become 0.12.6 'real soon now') ?

**Comment by jirutka** [comment]
@sgerrand I wonder, why do you maintain [sgerrand/alpine-pkg-R](https://github.com/sgerrand/alpine-pkg-R/) when we already have [R package](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/R) in official Alpine repository?

**Comment by sgerrand** [comment]
> @sgerrand I wonder, why do you maintain sgerrand/alpine-pkg-R when we
already have R package in official Alpine repository?

Mainly because that package predated my packaging efforts, it is still only
in the edge branch and not publicly released.

**Comment by eddelbuettel** [comment]
This is all getting a little too inside-baseball for Rcpp so I am going to lock this discussion here.

As it stands, Rcpp appears to be twice compiled right for Alpine we're all a happy family now.
