### ISSUE TITLE
Rcpp.package.skeleton with module = TRUE can't install

### ISSUE THREAD

**Issue by cruiseling** [RcppCore/Rcpp#450]
I want to first try the example code, so I do this
>Rcpp.package.skeleton(name = pkg.name, example_code = T, module = TRUE)
>cmd <- file.path(R.home(component = "bin"), paste0("R CMD INSTALL ", pkg.name))
>system(cmd) 

And here comes the error

>* installing to library 'C:/Users/Yun/Documents/R/win-library/3.1'
>* installing *source* package 'mypackage' ...

>** libs

>g++ -m64 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG    -I"C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include" -I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O2 -Wall  -mtune=core2 -c Num.cpp -o Num.o

>g++ -m64 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG    -I"C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include" -I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o

>g++ -m64 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG    -I"C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include" -I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O2 -Wall  -mtune=core2 -c rcpp_hello_world.cpp -o rcpp_hello_world.o

>g++ -m64 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG    -I"C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include" -I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O2 -Wall  -mtune=core2 -c rcpp_module.cpp -o rcpp_module.o

>g++ -m64 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG    -I"C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include" -I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O2 -Wall  -mtune=core2 -c stdVector.cpp -o stdVector.o

>In file included from C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include/Rcpp/as.h:25:0,
                 from C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include/RcppCommon.h:163,
                 from C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include/Rcpp.h:27,
                 from stdVector.cpp:22:

>C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include/Rcpp/internal/Exporter.h: In constructor 'Rcpp::traits::Exporter<T>::Exporter(SEXP) [with T = long long unsigned int, SEXP = SEXPREC*]':

>C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include/Rcpp/as.h:79:51:   instantiated from 'T Rcpp::internal::as(SEXP, Rcpp::traits::r_type_generic_tag) [with T = long long unsigned int, SEXP = SEXPREC*]'

>C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include/Rcpp/as.h:144:84:   instantiated from 'T Rcpp::as(SEXP) [with T = long long unsigned int, SEXP = SEXPREC*]'

>C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include/Rcpp/InputParameter.h:34:45:   instantiated from 'Rcpp::InputParameter<T>::operator T() [with T = long long unsigned int]'

>C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include/Rcpp/module/Module_generated_CppMethod.h:130:9:   instantiated from 'SEXPREC* Rcpp::CppMethod1<Class, void, U0>::operator()(Class*, SEXPREC**) [with Class = std::vector<double>, U0 = long long unsigned int, SEXP = SEXPREC*]'
stdVector.cpp:90:1:   instantiated from here

>C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include/Rcpp/internal/Exporter.h:31:31: error: invalid conversion from 'SEXP' to 'long long unsigned int' [-fpermissive]
In file included from C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include/RcppCommon.h:181:0,
                 from C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include/Rcpp.h:27,
                 from stdVector.cpp:22:

>C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include/Rcpp/internal/wrap.h: In function 'SEXPREC* Rcpp::internal::wrap_dispatch_unknown_iterable(const T&, Rcpp::traits::false_type) [with T = long long unsigned int, SEXP = SEXPREC*, Rcpp::traits::false_type = Rcpp::traits::integral_constant<bool, false>]':

>C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include/Rcpp/internal/wrap.h:732:98:   instantiated from 'SEXPREC* Rcpp::internal::wrap_dispatch_unknown(const T&, Rcpp::traits::false_type) [with T = long long unsigned int, SEXP = SEXPREC*, Rcpp::traits::false_type = Rcpp::traits::integral_constant<bool, false>]'

>C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include/Rcpp/internal/wrap.h:770:96:   instantiated from 'SEXPREC* Rcpp::internal::wrap_dispatch_eigen(const T&, Rcpp::traits::false_type) [with T = long long unsigned int, SEXP = SEXPREC*, Rcpp::traits::false_type = Rcpp::traits::integral_constant<bool, false>]'

>C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include/Rcpp/internal/wrap.h:787:80:   instantiated from 'SEXPREC* Rcpp::internal::wrap_dispatch_unknown_importable(const T&, Rcpp::traits::false_type) [with T = long long unsigned int, SEXP = SEXPREC*, Rcpp::traits::false_type = Rcpp::traits::integral_constant<bool, false>]'

>C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include/Rcpp/internal/wrap.h:807:99:   instantiated from 'SEXPREC* Rcpp::internal::wrap_dispatch(const T&, Rcpp::traits::wrap_type_unknown_tag) [with T = long long unsigned int, SEXP = SEXPREC*]'

>C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include/Rcpp/internal/wrap_end.h:30:110:   instantiated from 'SEXPREC* Rcpp::wrap(const T&) [with T = long long unsigned int, SEXP = SEXPREC*]'

>C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include/Rcpp/internal/wrap_end.h:35:26:   instantiated from 'SEXPREC* Rcpp::module_wrap_dispatch(const T&, Rcpp::traits::normal_wrap_tag) [with T = long long unsigned int, SEXP = SEXPREC*]'

>C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include/Rcpp/internal/wrap.h:922:96:   instantiated from 'SEXPREC* Rcpp::module_wrap(const T&) [with T = long long unsigned int, SEXP = SEXPREC*]'

>C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include/Rcpp/module/Module_generated_CppMethod.h:71:71:   instantiated from 'SEXPREC* Rcpp::const_CppMethod0<Class, RESULT_TYPE>::operator()(Class*, SEXPREC**) [with 

>Class = std::vector<double>, RESULT_TYPE = long long unsigned int, SEXP = SEXPREC*]'
stdVector.cpp:90:1:   instantiated from here

>C:/Users/Yun/Documents/R/win-library/3.1/Rcpp/include/Rcpp/internal/wrap.h:525:11: error: invalid conversion from 'long long unsigned int' to 'SEXP' [-fpermissive]

>make: *** [stdVector.o] Error 1

>Warning: running command 'make -f "C:/PROGRA~1/R/R-31~1.2/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-31~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="mypackage.dll" WIN=64 TCLBIN=64 OBJECTS="Num.o RcppExports.o rcpp_hello_world.o rcpp_module.o stdVector.o"' had status 2

>ERROR: compilation failed for package 'mypackage'

>* removing 'C:/Users/Yun/Documents/R/win-library/3.1/mypackage'

It seems that there is something wrong with stdVector.cpp, but I can not find the "long long unsigned int" data in stdVector.cpp.

After I delete the stdVector.cpp  and 
>#loadModule("stdVector", TRUE)

Then everything left works fine.
Really not sure what's wrong with stdVector.cpp

**Comment by thirdwing** [comment]
I think it is from https://github.com/RcppCore/Rcpp/blob/master/inst/skeleton/stdVector.cpp#L64-L65

It seems the classical problem of `size_t` type on Windows.

**Comment by eddelbuettel** [comment]
A few quick comments:

- This is really old code. I even think we may tickle this from unit tests. Maybe not wito `module=TRUE`.
- On my Linux box it works. So some blame for the old Windows compiler.
- Issues with `long long` reflect the (well known) issue that R forces us to live by the C++98 standard,
pretending that newer standards did not happen. You can overcome that by setting C++11, either in the DESCRIPTION file or in `src/Makevars{,.win}`.

**Comment by cruiseling** [comment]
@eddelbuettel  Thanks. It is fine with C11

**Comment by eddelbuettel** [comment]
@cruiseling I check and thought we had added this to the Rcpp FAQ. We have not, and it needs to be there.

I personally have a number of packages that need `long long` and they all declare C++11 -- that even works with the old Windows compiler.

**Comment by eddelbuettel** [comment]
So ok if we close this?

**Comment by cruiseling** [comment]
@eddelbuettel Sure.
