### ISSUE TITLE
Rcpp::Nullable<Rcpp::String> problems

### ISSUE THREAD

**Issue by asieira** [RcppCore/Rcpp#452]
When I run this with a string, I get an error message saying `Error: 'getCharCE' must be called on a CHARSXP`:
```
// [[Rcpp::export]]
String test_nullable(Rcpp::Nullable<Rcpp::String> param = R_NilValue) {
  if (param.isNotNull())
    return String(param);
  else
    return String("");
}
```

This, however, works perfectly:
```
// [[Rcpp::export]]
CharacterVector test_nullable2(Rcpp::Nullable<Rcpp::CharacterVector> param = R_NilValue) {
  if (param.isNotNull())
    return CharacterVector(param);
  else
    return CharacterVector();
}
```

Is there a principled reason why `Rcpp::Nullable` should not work with the `String` class so it enforces a scalar value?

**Comment by dcdillon** [comment]
How are you calling `test_nullable()`.  Can you add the R code?

**Comment by asieira** [comment]
There you go:
```
> cppFunction('String test_nullable(Rcpp::Nullable<Rcpp::String> param = R_NilValue) {
+   if (param.isNotNull())
+     return String(param);
+   else
+     return String("");
+ }')
> test_nullable()
[1] ""
> test_nullable("blah")
Error in test_nullable("blah") : 
  'getCharCE' deve ser chamado em uma CHARSXP

Enter a frame number, or 0 to exit   

1: test_nullable("blah")

Selection: 
```

**Comment by dcdillon** [comment]
Will have to look into this some more.  I'm sure it's an easy fix, but on the surface looks like a bug to me.

**Comment by asieira** [comment]
:bow:

**Comment by eddelbuettel** [comment]
Strings are really complicated.  We set up `Nullable` to work with `SEXP` types, so I suggest you do something like this instead:
```C++
#include <Rcpp.h>

using namespace Rcpp;

// [[Rcpp::export]]
std::string test_nullable(Nullable<CharacterVector> param = R_NilValue) {
  if (param.isNotNull()) {
    CharacterVector s(param);
    return std::string(s[0]);
  } else
    return std::string("");
}
```

This seems to work:

```r
R> sourceCpp("/tmp/nullstr.cpp")
R> test_nullable("abc")               
[1] "abc"
R> test_nullable(NULL)                       
[1] ""
R> 
```

**Comment by kevinushey** [comment]
This is more a problem with the `String` class and the fact that it wraps `CHARSXP`s and not `STRSXP`s, even though it 'wrap's to a `STRSXP`. For example:

```cpp
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
String test(String string) {
  return String(data);
}

/*** R
test("ouch")
*/
```

This gives

```R
> test("ouch")
Error in test("ouch") : 'getCharCE' must be called on a CHARSXP
```

In other words, `String(SEXP)` does not work with non-`CHARSXP` `SEXP`s, and the `Nullable<String>` implicitly converts to a `STRSXP` `SEXP`.

**Comment by asieira** [comment]
Thank you for the workaround suggestion using `Nullable<CharacterVector>`, that is exactly what I have in my code right now. 

As for your explanation of what's going on... Well, those C to R types are not something I'm familiar with, which is actually one of the reasons why I find Rcpp so interesting. :) If there's a way to make `String` work as a function return value and also with `Nullable` I think will make Rcpp much more usable.

**Comment by thirdwing** [comment]
Just as @kevinushey said, this can be fixed by modifying our String ctor.

```cpp
        /** construct a string from a single CHARSXP SEXP */
        String(SEXP charsxp) {
            if (TYPEOF(charsxp) == STRSXP) {
              data = STRING_ELT(charsxp, 0);
            } else if (TYPEOF(charsxp) == CHARSXP) {
              data = charsxp;
            }
            
            if (::Rf_isString(data) && ::Rf_length(data) != 1)
                throw ::Rcpp::not_compatible("expecting a single value");

            valid = true;
            buffer_ready = false;
            enc = Rf_getCharCE(data);
            Rcpp_PreserveObject(data);
            RCPP_STRING_DEBUG("String(SEXP)");
        }
```

```r
> Rcpp::sourceCpp("test.cpp")
>  test_nullable()
[1] ""
>  test_nullable("blah")
[1] "blah"
>
```

**Comment by dcdillon** [comment]
@thirdwing - are you going to PR this or want me to play with it a bit?

**Comment by thirdwing** [comment]
You can do that. Another ctor also needs to be changed.

https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/String.h#L81-L87

**Comment by dcdillon** [comment]
Ok...will take a look.  Probably not til later this week, but I'll get it in there.

**Comment by eddelbuettel** [comment]
This has indeed been taken care of in #453 and be closed.
