### ISSUE TITLE
Please add/push the 0.12.4 tag

### ISSUE THREAD

**Issue by krlmlr** [RcppCore/Rcpp#455]
Now it's on CRAN.

**Comment by eddelbuettel** [comment]
Ah, yes. Rcpp is the one project I've done that for in the past.

Care to detail why you need it (just so that I know what you are missing in essentially my other projects which generally are not tagged)  ?

**Comment by krlmlr** [comment]
Wanted to do a bisect between 0.12.3 and 0.12.4, noticed it. (Turned out it's not an Rcpp issue after all, don't worry.) Generally I think a bijection between CRAN releases and Git tags helps. A GitHub release is helpful too, but optional.

FWIW, I usually add annotated tags with the NEWS, creating a GitHub release from such a tag is easy  (copy-paste without leaving the browser, perhaps could be automated, too).

**Comment by eddelbuettel** [comment]
It's done.  I still do `NEWS.Rd` rather than Markdown so am I missing something semi-automatic?

**Comment by krlmlr** [comment]
I don't do NEWS.Rd. To me the CRAN rendering of the Rcpp NEWS looks like you could pandoc it to markdown. Didn't try, though.

**Comment by eddelbuettel** [comment]
Yes.  NEWS.Rd -> NEWS.html -> NEWS.md is on my list of things to try.  The first step is `tools::Rd2HTML()`, the second step should just be `pandoc`.
