### ISSUE TITLE
Random number generation mixing R and c++

### ISSUE THREAD

**Issue by konkam** [RcppCore/Rcpp#465]
Dear Rcpp developpers,

I have come across an undesirable behaviour, which I am not entirely certain is a bug.

I am using the multinomial distribution provided in Rcpp on a vector of size 11, so that each value has a probability 1/11 or  0.091

In test_multinom, I include a call to an R function which returns a random number. This seems to mess up the Rcpp multinomial distribution, as it does not return a multinomial distribution anymore.

In test_multinom2, I check that without the call to the R function, Rcpp::rmultinom returns a multinomial distributions, this seems ok.

I also observe that:

- calling a random number from a function in c++ does not alter Rcpp::rmultinom
- calling a R function with a deterministic result does not alter Rcpp::rmultinom

The zip file contains the code that can be run using sourceCpp()

Best regards, 

[bug_report.zip](https://github.com/RcppCore/Rcpp/files/223456/bug_report.zip)

```
#include <Rcpp.h>
using namespace Rcpp;


// [[Rcpp::export]]
int test_multinom(NumericVector content_of_urn, Function p0){

  int n_urn = content_of_urn.length();
  NumericVector probs(n_urn + 1, 1./(1. + n_urn));
  probs[n_urn] = 1./(1. + n_urn);

  IntegerVector item_sampled(n_urn + 1);
  rmultinom(1, probs.begin(), n_urn + 1, item_sampled.begin());

  int pos = std::find(item_sampled.begin(), item_sampled.end(),1) - item_sampled.begin();

  if (pos == n_urn) {
    NumericVector new_particle = p0(1);

    return(1);
  }
  else {
    return(0);
  }


  return pos;
}

// [[Rcpp::export]]
int test_multinom2(NumericVector content_of_urn, Function p0){

  int n_urn = content_of_urn.length();
  NumericVector probs(n_urn + 1, 1./(1. + n_urn));
  probs[n_urn] = 1./(1. + n_urn);

  IntegerVector item_sampled(n_urn + 1);
  rmultinom(1, probs.begin(), n_urn + 1, item_sampled.begin());

  int pos = std::find(item_sampled.begin(), item_sampled.end(),1) - item_sampled.begin();

  if (pos == n_urn) {
    // NumericVector new_particle = p0(1);
    return(1);
  }
  else {
    return(0);
  }

  return pos;
}


// [[Rcpp::export]]
NumericVector runif_(int N){
  return runif(N);
}
```

```
library(dplyr)
# sample_one_from_urn_cpp(content_of_urn = matrix(1:10), p0 = function(n) runif(n), theta = 1)
lapply(1:1000000, function(x) test_multinom(content_of_urn = 1:10, p0 = function(n) runif(n))) %>%
  unlist %>%
  (function(x) length(which(x==1))/length(x))
```

> [1] 0.154046

```
lapply(1:1000000, function(x) test_multinom2(content_of_urn = 1:10, p0 = function(n) runif(n))) %>%
  unlist %>%
  (function(x) length(which(x==1))/length(x))
```

> [1] 0.090216

```
lapply(1:1000000, function(x) test_multinom(content_of_urn = 1:10, p0 = runif_)) %>%
  unlist %>%
  (function(x) length(which(x==1))/length(x))
```

> [1] 0.090861

```
lapply(1:1000000, function(x) test_multinom(content_of_urn = 1:10, p0 = function(x) 0.5)) %>%
  unlist %>%
  (function(x) length(which(x==1))/length(x))
```

> 0.090474

**Comment by eddelbuettel** [comment]
I am not really sure what this is about.  

Can demonstrate a 'failure' (if there is one) with something shorter and simpler?

**Comment by eddelbuettel** [comment]
But there may be something not quite right with `rmultinom()`.  I am not sure anybody has ever used that so far.

Now, however, that we only have one definition in [Rmath.h](https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/Rmath.h#L102) which you have to access via the `R::` namespace.  I don't think we ever added a sugar function,

**Comment by konkam** [comment]
Ok I've narrowed things a bit.

Take this function:

```
#This function samples from a multinomial distribution with uniform probability over 11 outcomes
#Thus the probability of any given outcome is close to 0.091
#
#Input = a function of one argument which returns a NumericalVector
#Oupt: 1 if the last of the 11 outcomes is sampled, 0 otherwise

int test_multinom(Function p0){

  NumericVector probs(11, 1./11.);

  IntegerVector item_sampled(11);
  rmultinom(1, probs.begin(), 11, item_sampled.begin());

  int pos = std::find(item_sampled.begin(), item_sampled.end(),1) - item_sampled.begin();

  if (pos == 10) {
    NumericVector new_particle = p0(1);
    return(1);
  }
  else {
    return(0);
  }

  return pos;
}
```

We run this function 10**5 times and compute the observed probability of the result 1, which should be close to 0.091

```
library(dplyr)
lapply(1:100000, function(x) test_multinom(p0 = function(n) runif(n))) %>%
  unlist %>%
  (function(x) length(which(x==1))/length(x))
```

> [1] 0.15304


So there is an excess of 1's, meaning that the multinomial gives too often the last outcome.


We can test the other outcomes by changing the if condition, other outcomes are sampled too rarely except the first outcome (pos==0) which seems sampled with a correct frequency

Tests in my first post show that avoiding to call a random R function, ie. taking for argument p0 a constant function or a random C++ function seem to eliminate the problem

**Comment by konkam** [comment]
With gcc version 5.3.0 20151204 (Ubuntu 5.3.0-3ubuntu1~14.04), Rcpp_0.12.4 and R version 3.2.4 Revised (2016-03-16 r70336)

**Comment by eddelbuettel** [comment]
I am not sure I agree with the validity of your test:  checking sampled frequency of one outcome.

**Comment by konkam** [comment]
I agree, testing the Rcpp function rmultinom, one would rather look at all the outcomes but testing a special case should only be a less powerful test to detect an error, no ? 

I am just checking that the marginals of the multinomial, which are binomial distributions, have the right expected frequency. The same function in pure R should give the right result (and indeed it does):

```
test_multinomR = function(p0){

  probs = rep(1./11., 11)

  item_sampled = rmultinom(n = 1, size = 1, prob = probs)

  pos = which(item_sampled == 1, arr.ind = T)[1]

  if (pos == 11) {
    new_particle = p0(1);
    return(1);
  }
  else {
    return(0);
  }
}

lapply(1:1000000, function(x) test_multinomR(p0 = function(n) runif(n))) %>%
  unlist %>%
  (function(x) length(which(x==1))/length(x)) 
```

> [1] 0.090912

I suspect the call to a random R function plays a role, and I would probably not observe anything wrong if I just tested the function rmultinom independently.

Tell me if you have any other idea

Best,

**Comment by eddelbuettel** [comment]
Here is something really simply I just did on the commuter train:

```C++
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
IntegerVector callRMultinom(NumericVector x) {
    int n = x.size();
    IntegerVector d(n);
    R::rmultinom(1, x.begin(), n, d.begin());
    return d;
}

/*** R
N <- 1e5
M <- matrix(NA, N, 4)
for (i in 1:N) M[i,] <- callRMultinom(rep(0.25,4))
colSums(M)
*/
```

which tests more broadly and simpler -- and seems to work out just fine:

```r
R> Rcpp::sourceCpp('/tmp/multi.cpp')

R> N <- 1e5

R> M <- matrix(NA, N, 4)

R> for (i in 1:N) M[i,] <- callRMultinom(rep(0.25,4))

R> colSums(M)
[1] 25099 24869 25036 24996
R> 
```

I see no issue with R's underlying function.  I'll probe a little around the Rcpp interface which may need a brushup.

**Comment by eddelbuettel** [comment]
And upon further reflection:  that is all that there is.   Rcpp does not offer its own `rmultinom()` function, we only have a [years old TODO item](https://github.com/RcppCore/Rcpp/blob/master/TODO#L61-L62) so I inted to close this.

If still think you have unrepresentative sampling you may want to submit a bug report for R itself, but I would recommend you make it as short, concise and compelling as you can to get your point across.

**Comment by eddelbuettel** [comment]
Closing this lack of an actual issue, and follow-up.

**Comment by konkam** [comment]
Dear Dirk, 

sorry I did not find the time to reply earlier. I understand that there is no problem with the multinomial function per se, I suspect that there is an interaction between the random number generators in R and in C++ which messes some things up.


I slightly modified your example:

```
cppFunction({'IntegerVector callRMultinom4(NumericVector x, Function p0) {
  int n = x.size();
  IntegerVector d(n);
  R::rmultinom(1, x.begin(), n, d.begin());

  if (d[n-1] == 1) {
      NumericVector new_particle = p0(1);
      return(d);
  }
  else {
    return(d);
  }

}'}
)
```

So basically, it returns the same result as your function but perform a call to another function in between.

```
M <- rep(NA, N)
for (i in 1:N) M[i] <- callRMultinom2(rep(0.25,4), function(n) runif(1))
length(which(M==1))/N
```

> [1] 0.16683 0.16713 0.33155 0.33449

M <- matrix(NA, N, 4)
for (i in 1:N) M[i,] <- callRMultinom3(rep(0.25,4), function(n) runif(1))
colSums(M)/sum(M)

> [1] 0.24857 0.25147 0.24935 0.25061


So when the call is to a random R function (runif), the result are not what is expected, whereas when the call is to a deterministic function, the results seem good.


Thanks for taking the time too look into this

**Comment by konkam** [comment]
Dear Dirk, 

sorry I did not find the time to reply earlier. I understand that there is no problem with the multinomial function per se, I suspect that there is an interaction between the random number generators in R and in C++ which messes some things up.


I slightly modified your example:

```
cppFunction({'IntegerVector callRMultinom4(NumericVector x, Function p0) {
  int n = x.size();
  IntegerVector d(n);
  R::rmultinom(1, x.begin(), n, d.begin());

  if (d[n-1] == 1) {
      NumericVector new_particle = p0(1);
      return(d);
  }
  else {
    return(d);
  }

}'}
)
```

So basically, it returns the same result as your function but perform a call to another function in between.

```
N <- 1e5

M <- matrix(NA, N, 4)
for (i in 1:N) M[i,] <- callRMultinom4(rep(0.25,4), function(n) runif(1))
colSums(M)/sum(M)
```

> [1] 0.16683 0.16713 0.33155 0.33449

```
M <- matrix(NA, N, 4)
for (i in 1:N) M[i,] <- callRMultinom4(rep(0.25,4), function(n) 1)
colSums(M)/sum(M)
```

> [1] 0.24857 0.25147 0.24935 0.25061


So when the call is to a random R function (runif), the result are not what is expected, whereas when the call is to a deterministic function, the results seem good.


Thanks for having taken the time to look into this

**Comment by eddelbuettel** [comment]
Please read Writing R Extensions about the RNG state getters/setters, and then read the Rcpp documentation (plus maybe some Google searches) about RNGScope.  

You are purposely messing with the RNG by calling `runif()`.  Things break.  

Easy fix:  Don't mess with the RNG.  Calling _back to R via `Rcpp::Function`_ breaks the implicit contract you have here with the RNG interaction via Rcpp Attributes.

**Comment by konkam** [comment]
Ah, perfect, sorry for bothering you with this, then, and thanks for the references.

Best,
