### ISSUE TITLE
Rcpp fails to install, R 3.2.5, Debian Jessie 8.4

### ISSUE THREAD

**Issue by phillc73** [RcppCore/Rcpp#467]
Rcpp fails to build and install:
```
install.packages("Rcpp")
--
* installing *source* package ‘Rcpp’ ...
** package ‘Rcpp’ successfully unpacked and MD5 sums checked
** libs
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c Date.cpp -o Date.o
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c Module.cpp -o Module.o
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c Rcpp_init.cpp -o Rcpp_init.o
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c api.cpp -o api.o
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c attributes.cpp -o attributes.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
/usr/lib/R/etc/Makeconf:143: recipe for target 'attributes.o' failed
make: *** [attributes.o] Error 4
ERROR: compilation failed for package ‘Rcpp’
* removing ‘/home/phillc73/R/x86_64-pc-linux-gnu-library/3.2/Rcpp’

The downloaded source packages are in
        ‘/tmp/RtmpOdFh6g/downloaded_packages’
Warning message:
In install.packages("Rcpp") :
  installation of package ‘Rcpp’ had non-zero exit status

> sessionInfo()
R version 3.2.5 (2016-04-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base 
```
g++ (Debian 4.9.2-10) 4.9.2

**Comment by eddelbuettel** [comment]
Lemme guess:  virtual machine, less than 4gb of RAM?

**Comment by phillc73** [comment]
Yes, Digital Ocean Droplet with 512MB ram.

Just needed it to run some scripts under cron, and really it was dplyr I was after. Rcpp included with love.

**Comment by eddelbuettel** [comment]
Get yourself a RAM allocation suitable for a real computer.  That is pilot error, ie yours.

**Comment by eddelbuettel** [comment]
Also: you _completely avoid_ the issue via `sudo apt-get install r-cran-rcpp`.  Ditto for dplyr; but they may not be a recent versions (ie Debian stable is stable, after all).

**Comment by phillc73** [comment]
Well, not completely. As far as I can see there is no r-cran-dplyr package for Debian Jessie. Installing r-cran-rcpp installs 0.11.3 and 0.12.0 is required for the latest dplyr. Of course it's fixable in other ways, and I might just have to live with an older version of dplyr.

Appreciate your point about RAM, but at the same time if one just wants to schedule a handful of scripts, there's no need for such a large amount of RAM.

Thanks for the time and response.

**Comment by kevinushey** [comment]
You should also double check that you aren't using a parallel make (ie, what's the output of `MAKEFLAGS`?)

Either way, I echo @eddelbuettel's comment that 512MB is not nearly enough (C++ compilers require a lot of memory to do what they do)

**Comment by phillc73** [comment]
For future reference, I just ended up upgrading to Debian Stretch, where both r-cran-rcpp and r-cran-dplyr are packaged and available. This is not a production server, but a small personal hack to make my life easier. Thanks again for the pointers.

**Comment by catbrower** [comment]
FYI if you have a RAM problem, just allocate swap so you don't have to pay more dollars :0
https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04

I also recommend installing htop

**Comment by eddelbuettel** [comment]
No, install the binary so that don't need to compile.
