### ISSUE TITLE
"loadRcppModules/.onLoad" error under devtools toolchain in RStudio

### ISSUE THREAD

**Issue by dmenne** [RcppCore/Rcpp#468]
In https://github.com/dmenne/teststan I have prepared a skeleton rstan project with test cases. It is a minimal version of the featured provided by rstanarm. Details are given in the README. Tested with Rcpp CRAN 0.12.4

* Build and check works under Windows and Linux with the command line tools (rcmd / R CMD), and in TravisCI
* 'Clean and Rebuild' and 'Build and Reload' in RStudio use `R CMD` and therefore work. 
* Menu item "Check" in RStudio calls `devtools::check()` and stops with : `Error in Rcpp::loadRcppModules() : loadRcppModules can only be used within a .onLoad function`
* Same issue with `devtools::test()` and `devtools::document(roclets=c('rd', 'namespace'))`, both from menu items
* Manually calling `devtools::check(document=FALSE)` works ok.
* Manually calling `roxygen2::roxygenize(clean = TRUE)` also works.

Thus currently (May 2016) the RStudio/devtools chain cannot be used in the default versions provided by RStudio. 

It might be that the above is related to the issue reported in May 2015 on https://github.com/hadley/devtools/issues/828 and confirmed in September 2015 as an rcpp issue.

See also [Ben Goodrich's comments](https://groups.google.com/forum/?fromgroups#!category-topic/stan-users/general/UmjMFMahdYM)

**Comment by eddelbuettel** [comment]
Please checkout the current master branch (ie Rcpp 0.12.4.5; somewhat imminent for release) which had _multiple_ fixes for this.   I will ignore this issue til I know whether it raises its head in master.

Also, I don't particularly care about RStudio this or devtools that.  Those are local picks of your choosing which may or may not complicate things.  _They are neither documented by us nor recommended._ 

The only really relevant output is from `R CMD ...`.

**Comment by eddelbuettel** [comment]
Also from your long laundry list I see repeated 'works' and one 'fails'.  Why did you choose to report the latter here rather than with RStudio?

**Comment by eddelbuettel** [comment]
Lastly, I think `Rcpp::loadRcppModules()` is mostly deprecated and has been for years -- it was a change by John Chambers who seems to prefer that we do `loadModule("NameOfModule", TRUE)` in an R file in the package (not necessarily `.onLoad()` or `.onAttach()` called from `zzz.R` or `init.R`).

**Comment by eddelbuettel** [comment]
Took me a moment to locate it but [this comment a few weeks agp](https://github.com/RcppCore/Rcpp/issues/462#issuecomment-210139319) is pertinent.

I'll create an issue to deprecate / warn / set hair on fire when `loadRcppModules()` is used.

**Comment by dmenne** [comment]
No change with current github version 0.12.4.5/2016-04-15.
I have not been able to get a working version with loadModule instead of shotgun. I see that an issue caused by the use of a deprecated function is not a bug and will close it.

**Comment by eddelbuettel** [comment]
Well, our fault really.  I never thought the transition to `loadModule()` was all that well handled / motivated.  But that does not excuse that I sat on my hands no documenting this better.  I think this is in the Rcpp Modules vignette, but still -- deprecating is the right step.

If you use `loadModule()` no matter which additional build obfuscation^Hhelper tool you use, Rcpp should still load your test package faithfully.  This has worked pretty well for most people.

And I will try to get a deprecation warning into the next release to safe the next person from the troubles you had here.

**Comment by eddelbuettel** [comment]
Even worse. The Rcpp modules vignette still refers to it.  Oh well, I'll change that too in #469.
