### ISSUE TITLE
type conversion from LogicalVector to NumericVector

### ISSUE THREAD

**Issue by liyi-1989** [RcppCore/Rcpp#473]
Can we do type conversion from True to 1, and False to 0? Met this problem when doing multiplication of a indicator function of a vector. Thanks!

**Comment by eddelbuettel** [comment]
Do you when like this:

```r
R> library(Rcpp)
R> cppFunction('double mysum(LogicalVector x) { return(sum(x)); }')
R> mysum(c(rep(TRUE,3), rep(FALSE, 2), rep(TRUE, 3)))
[1] 6
R> 
```

Please use the rcpp-devel list for beginner question instead of this issue tracking system.  Thanks.

**Comment by liyi-1989** [comment]
Thanks! In your example, I want to do element-wise operation of that LogicalVector: like (True,False,True)*1.5=(1.5,0,1.5) which is a NumericalVector. 

I actually want to calculate a simple box kernel of a NumericalVector x, which is (abs(x)<1) /2.0, but the LogicalVector cannot multiplied by a double, and thus cannot get a NumericalVector. 

I will switch to the rcpp-devel list. Thanks you so much for your help!

**Comment by liyi-1989** [comment]
Thanks! It works when using `wrap()`, though a little bit not direct. 
`NumericVector r=wrap(abs(x)<=1); return r/2.0;`
 
Thank you very much!

**Comment by eddelbuettel** [comment]
It's tricky as there are so many permutation of type and ops -- I guess you did find we do not have LogicalVector ops double.   I have use (Rcpp)Armadillo for related things -- here you would have started without a boolean vector (but rather `unsigned int`) because Armadillo is more focused on all things numbers.  But then it has the matching ops...

**Comment by eddelbuettel** [comment]
FYI here is [one way of doing logical ops on Armadillo vectors](http://gallery.rcpp.org/articles/armadillo-subsetting/).  You may find more luck over there.

**Comment by liyi-1989** [comment]
Thanks @eddelbuettel for your help! I will check the post.
