### ISSUE TITLE
Move unit tests to `./tests`

### ISSUE THREAD

**Issue by jeroenooms** [RcppCore/Rcpp#480]
Currently Rcpp always installs all unit tests with the package, which increases the installation size for no good reason. It would be nice if Rcpp would only install unit tests for `--install-tests`, simply by putting tests into the appropriate `./tests` directory.

**Comment by eddelbuettel** [comment]
It is on purpose because it allows to run the tests for an _installed package_.

**Comment by eddelbuettel** [comment]
Besides the tests also provides documentation in that they show usage -- we refer to them for that reason.  

Moreover, the total size, to pick my current installation directory, is 0.7mb out of 13.3mb or about  5.4%.  Not worth making the change.

One thing that would be worth changing at the R side is to differentiate more between Build-Depends and Depends---right now many Rcpp through their compile-time_use_ pull in the BH package for run-time.  That is crazy, but worth 124mb.
