### ISSUE TITLE
Rcpp-quickrefs issue

### ISSUE THREAD

**Issue by exixx** [RcppCore/Rcpp#484]
In the Inline section of the quickrefs sheet, the single quotes in the body aren't single quotes. a copy/paste of the code into R (3.3.0) from the 0.12.5 vignette doesn't work without replacing the quotes.
Additionally, since this is a minor point, I'll add another. In the Important Notes section, it states that many of the examples imply
`using namespace Rcpp;`

If this is mentioned, shouldn't it also mention that they also imply
`#include <Rcpp.h>`
?

**Comment by eddelbuettel** [comment]
Thanks.  Could you try to take a stab at fixing the existing LaTeX markup and try to correct this?

**Comment by exixx** [comment]
Hmm. I haven't looked at LaTeX in like 30 years, but sure.

**Comment by coatless** [comment]
Needs documentation flag

**Comment by coatless** [comment]
@eddelbuettel : 

Is it okay if I also:

1. add a short code example using Rcpp Attributes? 
2. replace the `cxxfunction` with `cppFunction`?

**Comment by eddelbuettel** [comment]
Yes, sure. This one may be the most half-baked one of all.
