### ISSUE TITLE
How to teach the compiler that stop() doesn't return?

### ISSUE THREAD

**Issue by krlmlr** [RcppCore/Rcpp#486]
So that we can write

```
bool foo(int x) {
  switch (x) {
    case 1: return true;
    case 2: return false;
    default: stop("Don't know this x");
  }
}
```

without issuing a warning.

There is a "noreturn" attribute for [GCC](https://gcc.gnu.org/onlinedocs/gcc-3.4.3/gcc/Function-Attributes.html) and [clang](http://clang.llvm.org/docs/LanguageExtensions.html), but there might be other solutions. **EDIT**: http://stackoverflow.com/a/25408952/946850 is a nice SO answer that features `__builtin_unreachable()`.

Re https://github.com/hadley/dplyr/pull/1878#issuecomment-223140346, CC @hadley.

**Comment by kevinushey** [comment]
For what it's worth, R defines the `NORET` macro for handling this as well so we could potentially just use that: https://github.com/wch/r-source/blob/trunk/src/include/R_ext/Error.h#L29-L37

**Comment by eddelbuettel** [comment]
We appear to have issues with this per #512.  

@krlmlr @kevinushey Can one of you familiar with NORET please check how / why it is defined?  I tried adding a simple

```
#undef NORET
```

in the file, but no mas.  If and when I do replace `NORET` with `/*NORET*/` then I can build on the old platform.
