### ISSUE TITLE
RVector not constructible from NumericVector

### ISSUE THREAD

**Issue by thk686** [RcppCore/Rcpp#494]
```c++
NumericMatrix a(3, 3);
RMatrix<double> b(a); // seems to work
NumericVector c(3);
RVector<double> d(c); // fails
```

This seems inconsistent. There's a copy constructor for RVector and one based on a begin and end std::size_t, but not one that ingests a NumericVector. That seems like an obvious use case.

**Comment by eddelbuettel** [comment]
Pull requests welcome.  Note though that `RVector` is part of RcppParallel.

**Comment by thk686** [comment]
Right. I assumed because its in the same source tree that it was the same github project. What do you currently do to fill an RVector<double>? Std::copy?

**Comment by eddelbuettel** [comment]
"in the same source tree" ? What do you mean by that?   Different repos are, well, different repos.

I use whatever the few standard examples for RcppParallel do :)

**Comment by thk686** [comment]
I was confused by the RcppCore umbrella and thought it was one tree. Apparently not.

I found a solution: you have to use the explicit constructor, so:

NumericVector a;
auto b = RVector<double>(a);

works. Same for RMatrix<>.

Was it intended that the constructor be marked explicit?

Anyway, I'll close this now.
