### ISSUE TITLE
Package 'testRcppClass' not available in repository or locally

### ISSUE THREAD

**Issue by jankovicd** [RcppCore/Rcpp#510]
I am trying to deploy a Shiny application to shinyapps.io but I am getting error messages

In FUN(X[[i]], ...) :Package 'testRcppClass' not available in repository or locally
In FUN(X[[i]], ...) :Package 'testRcppModule' not available in repository or locally

I have Rcpp installed (from CRAN), any idea why these messages coming up?

**Comment by eddelbuettel** [comment]
That makes no sense.  We have a number of shiny apps at works which use Rcpp in some form (eg via RcppRedis).   You may be doing something wrong but as this not reproducible I can't say more.

**Comment by eddelbuettel** [comment]
Moreover, it is unclear why those would be called.  They are only used for unit tests.

**Comment by coatless** [comment]
@jankovicd Is there anyway you can make this somewhat reproducible? Perhaps via a code gist containing the shiny app or an R package?

**Comment by kevinushey** [comment]
This is a packrat issue (and @jankovicd has posted here: https://github.com/rstudio/packrat/issues/313).

My guess is that the project folder contains Rcpp sources, and packrat crawls those, discovering calls to e.g `library(testRcppClass)`, and infers those packages as dependencies of the project.

**Comment by eddelbuettel** [comment]
Yes, embedded test package. Looks, smells and tastes like an external package but isn't one.  

You may be able to build a heuristic around being below `inst/tests/` or `inst/unitTests/`. Still tricky.
