### ISSUE TITLE
install.packages("Rcpp") fails

### ISSUE THREAD

**Issue by ajdamico** [RcppCore/Rcpp#519]
login as: damico
	Authenticating with public key "rsa-key-20141110"
	Last login: Tue Jul 26 08:02:16 2016 from zandbak.cwi.nl
	[damico@scilens-ssh ~]$ ssh stones15
	Last login: Tue Jul 26 08:02:21 2016 from scilens-ssh.scilens.private
	[damico@stones15 ~]$ R

	R version 3.1.1 (2014-07-10) -- "Sock it to Me"
	Copyright (C) 2014 The R Foundation for Statistical Computing
	Platform: x86_64-redhat-linux-gnu (64-bit)

	R is free software and comes with ABSOLUTELY NO WARRANTY.
	You are welcome to redistribute it under certain conditions.
	Type 'license()' or 'licence()' for distribution details.

	  Natural language support but running in an English locale

	R is a collaborative project with many contributors.
	Type 'contributors()' for more information and
	'citation()' on how to cite R or R packages in publications.

	Type 'demo()' for some demos, 'help()' for on-line help, or
	'help.start()' for an HTML browser interface to help.
	Type 'q()' to quit R.

	>
	> install.packages("Rcpp")
	Installing package into ‘/local/damico/R/x86_64-redhat-linux-gnu-library/3.1’
	(as ‘lib’ is unspecified)
	--- Please select a CRAN mirror for use in this session ---
	CRAN mirror

	  1: 0-Cloud [https]                 2: 0-Cloud
	  3: Algeria [https]                 4: Algeria
	  5: Argentina (La Plata)            6: Australia (Canberra)
	  7: Australia (Melbourne)           8: Austria [https]
	  9: Austria                        10: Belgium (Antwerp)
	 11: Belgium (Ghent) [https]        12: Belgium (Ghent)
	 13: Brazil (BA)                    14: Brazil (PR)
	 15: Brazil (RJ)                    16: Brazil (SP 1) [https]
	 17: Brazil (SP 1)                  18: Brazil (SP 2)
	 19: Bulgaria                       20: Canada (BC)
	 21: Canada (MB) [https]            22: Canada (MB)
	 23: Canada (NS)                    24: Canada (ON)
	 25: Chile [https]                  26: Chile
	 27: China (Beijing 4) [https]      28: China (Beijing 4)
	 29: China (Xiamen)                 30: Colombia (Cali) [https]
	 31: Colombia (Cali)                32: Czech Republic
	 33: Ecuador                        34: El Salvador
	 35: Estonia                        36: France (Lyon 1) [https]
	 37: France (Lyon 2) [https]        38: France (Lyon 2)
	 39: France (Marseille)             40: France (Montpellier)
	 41: France (Paris 1)               42: France (Paris 2) [https]
	 43: France (Paris 2)               44: Germany (Göttingen)
	 45: Germany (Münster) [https]      46: Germany (Münster)
	 47: Greece                         48: Hungary
	 49: Iceland [https]                50: Iceland
	 51: India                          52: Indonesia (Jakarta)
	 53: Iran                           54: Ireland
	 55: Italy (Milano)                 56: Italy (Padua) [https]
	 57: Italy (Padua)                  58: Italy (Palermo)
	 59: Japan (Tokyo) [https]          60: Japan (Tokyo)
	 61: Korea (Seoul 1)                62: Korea (Seoul 2)
	 63: Korea (Ulsan)                  64: Lebanon
	 65: Malaysia [https]               66: Malaysia
	 67: Mexico (Mexico City) [https]   68: Mexico (Mexico City)
	 69: Mexico (Texcoco)               70: Netherlands (Amsterdam)
	 71: Netherlands (Utrecht)          72: New Zealand [https]
	 73: New Zealand                    74: Norway
	 75: Philippines                    76: Poland
	 77: Portugal (Lisbon)              78: Russia (Moscow) [https]
	 79: Russia (Moscow)                80: Serbia [https]
	 81: Singapore                      82: South Africa (Cape Town)
	 83: South Africa (Johannesburg)    84: Spain (A Coruña) [https]
	 85: Spain (A Coruña)               86: Spain (Madrid) [https]
	 87: Spain (Madrid)                 88: Sweden
	 89: Switzerland [https]            90: Switzerland
	 91: Taiwan (Chungli)               92: Taiwan (Taipei)
	 93: Thailand                       94: Turkey (Denizli)
	 95: Turkey (Mersin)                96: UK (Bristol) [https]
	 97: UK (Bristol)                   98: UK (Cambridge) [https]
	 99: UK (Cambridge)                100: UK (London 1)
	101: UK (London 2)                 102: UK (St Andrews)
	103: USA (CA 1) [https]            104: USA (CA 1)
	105: USA (CA 2)                    106: USA (IA)
	107: USA (IN)                      108: USA (KS) [https]
	109: USA (KS)                      110: USA (MI 1) [https]
	111: USA (MI 1)                    112: USA (MO)
	113: USA (NC)                      114: USA (OH 1)
	115: USA (OH 2)                    116: USA (OR)
	117: USA (PA 1)                    118: USA (PA 2)
	119: USA (TN) [https]              120: USA (TN)
	121: USA (TX) [https]              122: USA (TX)
	123: USA (WA) [https]              124: USA (WA)
	125: Venezuela

	Selection: 120
	trying URL 'http://mirrors.nics.utk.edu/cran/src/contrib/Rcpp_0.12.6.tar.gz'
	Content type 'application/x-gzip' length 2415707 bytes (2.3 Mb)
	opened URL
	==================================================
	downloaded 2.3 Mb

	* installing *source* package ‘Rcpp’ ...
	** package ‘Rcpp’ successfully unpacked and MD5 sums checked
	** libs
	g++ -m64 -I/usr/include/R -DNDEBUG -I../inst/include/ -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic  -c Date.cpp -o Date.o
	In file included from ../inst/include/RcppCommon.h:122:0,
					 from ../inst/include/Rcpp.h:27,
					 from Date.cpp:31:
	../inst/include/Rcpp/exceptions.h:267:23: error: expected initializer before ‘stop’
		 inline void NORET stop(const std::string& message) {
						   ^
	../inst/include/Rcpp/exceptions.h:272:23: error: expected initializer before ‘stop’
		 inline void NORET stop(const char* fmt, const T1& arg1) {
						   ^
	../inst/include/Rcpp/exceptions.h:277:23: error: expected initializer before ‘stop’
		 inline void NORET stop(const char* fmt, const T1& arg1, const T2& arg2) {
						   ^
	../inst/include/Rcpp/exceptions.h:282:23: error: expected initializer before ‘stop’
		 inline void NORET stop(const char* fmt, const T1& arg1, const T2& arg2, con
						   ^
	../inst/include/Rcpp/exceptions.h:287:23: error: expected initializer before ‘stop’
		 inline void NORET stop(const char* fmt, const T1& arg1, const T2& arg2, con
						   ^
	../inst/include/Rcpp/exceptions.h:292:23: error: expected initializer before ‘stop’
		 inline void NORET stop(const char* fmt, const T1& arg1, const T2& arg2, con
						   ^
	../inst/include/Rcpp/exceptions.h:297:23: error: expected initializer before ‘stop’
		 inline void NORET stop(const char* fmt, const T1& arg1, const T2& arg2, con
						   ^
	../inst/include/Rcpp/exceptions.h:302:23: error: expected initializer before ‘stop’
		 inline void NORET stop(const char* fmt, const T1& arg1, const T2& arg2, con
						   ^
	../inst/include/Rcpp/exceptions.h:307:23: error: expected initializer before ‘stop’
		 inline void NORET stop(const char* fmt, const T1& arg1, const T2& arg2, con
						   ^
	../inst/include/Rcpp/exceptions.h:312:23: error: expected initializer before ‘stop’
		 inline void NORET stop(const char* fmt, const T1& arg1, const T2& arg2, con
						   ^
	../inst/include/Rcpp/exceptions.h:317:23: error: expected initializer before ‘stop’
		 inline void NORET stop(const char* fmt, const T1& arg1, const T2& arg2, con
						   ^
	In file included from ../inst/include/Rcpp/Vector.h:56:0,
					 from ../inst/include/Rcpp.h:38,
					 from Date.cpp:31:
	../inst/include/Rcpp/vector/DimNameProxy.h: In member function ‘Rcpp::internal::DimNameProxy& Rcpp::internal::DimNameProxy::assign(SEXP)’:
	../inst/include/Rcpp/vector/DimNameProxy.h:43:121: error: too many arguments to function ‘void Rcpp::stop(const string&)’
	 is '%d' while length of names is '%d'", INTEGER(dims)[dim_], Rf_length(other));
																				  ^
	In file included from ../inst/include/RcppCommon.h:70:0,
					 from ../inst/include/Rcpp.h:27,
					 from Date.cpp:31:
	../inst/include/Rcpp/utils/tinyformat.h:127:10: note: declared here
		 void stop(const std::string& message);
			  ^
	In file included from ../inst/include/Rcpp.h:47:0,
					 from Date.cpp:31:
	../inst/include/Rcpp/Function.h: In constructor ‘Rcpp::Function_Impl<StoragePolicy>::Function_Impl(const string&, const string&)’:
	../inst/include/Rcpp/Function.h:72:63: error: too many arguments to function ‘void Rcpp::stop(const string&)’
					 stop("there is no namespace called \"%s\"", ns);
																   ^
	In file included from ../inst/include/RcppCommon.h:70:0,
					 from ../inst/include/Rcpp.h:27,
					 from Date.cpp:31:
	../inst/include/Rcpp/utils/tinyformat.h:127:10: note: declared here
		 void stop(const std::string& message);
			  ^
	make: *** [Date.o] Error 1
	ERROR: compilation failed for package ‘Rcpp’
	* removing ‘/local/damico/R/x86_64-redhat-linux-gnu-library/3.1/Rcpp’

	The downloaded source packages are in
			‘/tmp/RtmpuMmkYx/downloaded_packages’
	Warning message:
	In install.packages("Rcpp") :
	  installation of package ‘Rcpp’ had non-zero exit status
	> sessionInfo()
	R version 3.1.1 (2014-07-10)
	Platform: x86_64-redhat-linux-gnu (64-bit)

	locale:
	 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
	 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
	 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
	 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
	 [9] LC_ADDRESS=C               LC_TELEPHONE=C
	[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

	attached base packages:
	[1] stats     graphics  grDevices utils     datasets  methods   base

	loaded via a namespace (and not attached):
	[1] tools_3.1.1
	>

	

machine version info
	
	uname -a
	Linux stones15.scilens.private 3.12.10-300.fc20.x86_64 #1 SMP Thu Feb 6 22:11:48 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

	gcc -v
	Using built-in specs.
	COLLECT_GCC=gcc
	COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/lto-wrapper
	Target: x86_64-redhat-linux
	Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-isl=/builddir/build/BUILD/gcc-4.8.2-20131212/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.2-20131212/obj-x86_64-redhat-linux/cloog-install --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
	Thread model: posix
	gcc version 4.8.2 20131212 (Red Hat 4.8.2-7) (GCC)

**Comment by eddelbuettel** [comment]
See #512 and #516 as well as [this SO question from yesterday](http://stackoverflow.com/questions/38566225/not-able-to-compile-rcpp-0-12-6-under-r).

Combination of your R too old and us missing that in 0.12.6 -- so use 0.12.6.1 or upgrade R.

**Comment by ajdamico** [comment]
thanks!

**Comment by eddelbuettel** [comment]
No problem. Sorry about the bug. I also emailed to rcpp-devel but R-Forge seems to once again not deliver emails right now.
