### ISSUE TITLE
R 3.1.2 Rcpp - "expected initializer before ‘stop’"  NORET?

### ISSUE THREAD

**Issue by david-w-webb** [RcppCore/Rcpp#520]
I get errors when trying to upgrade Rcpp from 0.11.3 to 0.12.6 on CentOS 6.5.

I note that the R changelog for 2016-06-02 contains:
`*inst/include/Rcpp/exceptions.h: Annotate stop() with NORET`

The installation log is below:
`* installing *source* package ‘Rcpp’ ...
** package ‘Rcpp’ successfully unpacked and MD5 sums checked
** libs
g++ -I/opt/R-3.1.2/lib64/R/include -DNDEBUG -I../inst/include/ -I/usr/local/include    -fpic  -g -O2  -c Date.cpp -o Date.o
In file included from ../inst/include/RcppCommon.h:122,
                 from ../inst/include/Rcpp.h:27,
                 from Date.cpp:31:
../inst/include/Rcpp/exceptions.h:267: error: expected initializer before ‘stop’
../inst/include/Rcpp/exceptions.h:272: error: expected initializer before ‘stop’
../inst/include/Rcpp/exceptions.h:277: error: expected initializer before ‘stop’
../inst/include/Rcpp/exceptions.h:282: error: expected initializer before ‘stop’
../inst/include/Rcpp/exceptions.h:287: error: expected initializer before ‘stop’
../inst/include/Rcpp/exceptions.h:292: error: expected initializer before ‘stop’
../inst/include/Rcpp/exceptions.h:297: error: expected initializer before ‘stop’
../inst/include/Rcpp/exceptions.h:302: error: expected initializer before ‘stop’
../inst/include/Rcpp/exceptions.h:307: error: expected initializer before ‘stop’
../inst/include/Rcpp/exceptions.h:312: error: expected initializer before ‘stop’
../inst/include/Rcpp/exceptions.h:317: error: expected initializer before ‘stop’
In file included from ../inst/include/Rcpp/Vector.h:56,
                 from ../inst/include/Rcpp.h:38,
                 from Date.cpp:31:
../inst/include/Rcpp/utils/tinyformat.h: In member function ‘Rcpp::internal::DimNameProxy& Rcpp::internal::DimNameProxy::assign(SEXPREC*)’:
../inst/include/Rcpp/utils/tinyformat.h:127: error: too many arguments to function ‘void Rcpp::stop(const std::string&)’
../inst/include/Rcpp/vector/DimNameProxy.h:43: error: at this point in file
In file included from ../inst/include/Rcpp.h:47,
                 from Date.cpp:31:
../inst/include/Rcpp/utils/tinyformat.h: In constructor ‘Rcpp::Function_Impl<StoragePolicy>::Function_Impl(const std::string&, const std::string&)’:
../inst/include/Rcpp/utils/tinyformat.h:127: error: too many arguments to function ‘void Rcpp::stop(const std::string&)’
../inst/include/Rcpp/Function.h:72: error: at this point in file
make: *** [Date.o] Error 1
ERROR: compilation failed for package ‘Rcpp’
* removing ‘/opt/R-3.1.2/lib64/R/library/Rcpp’
* restoring previous ‘/opt/R-3.1.2/lib64/R/library/Rcpp’
Warning message:
In install.packages(pkgs = "/tmp/zip/Rcpp_0.12.6.tar.gz", repos = NULL,  :
  installation of package ‘/tmp/zip/Rcpp_0.12.6.tar.gz’ had non-zero exit status
`

**Comment by david-w-webb** [comment]
gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC)

**Comment by eddelbuettel** [comment]
Please see #512, #516, #519, StackOverflow and the rcpp-devel list (now that it is back).

**Comment by david-w-webb** [comment]
As referenced in other threads:

http://stackoverflow.com/questions/38566225/not-able-to-compile-rcpp-0-12-6-under-r

My source directory was /tmp/zip

I unzipped the /tmp/zip/Rcpp_0.12.6.tar.gz file, edited /tmp/zip/Rcpp/inst/include/Rcpp/exceptions.h to add 

`#define NORET`

Afterwards, I was able to execute in R:

`> install.packages(pkgs="/tmp/zip/Rcpp",repos = NULL, type = "source", verbose = TRUE)`

I received a warning:
`file ‘inst/include/Rcpp/exceptions.h’ has the wrong MD5 checksum`
but the install.packages completed.

My end goal was to update the 'dplyr' package and I was able to complete this.

Thanks for the help!

**Comment by eddelbuettel** [comment]
Yes, and `install.packages("Rcpp", repos="http://RcppCore.github.io/drat")` would do it too, but better with our fix.
