### ISSUE TITLE
Stripping Debug Symbols plugin

### ISSUE THREAD

**Issue by dcdillon** [RcppCore/Rcpp#522]
By adding the `PKG_LIBS=-Wl,-S` to my package, I tell the linker to strip the debug symbols when creating the `.so` file.  This is necessary because I generate some truly unholy class and function names via templates (e.g. .so size goes from 13MB to 54KB with this flag added).

Would it be reasonable to add an `// [[Rcpp::plugins(strip)]]` that does this?  I think it's probably useful.

**Comment by coatless** [comment]
To set some sort of build flags within the source has actually be brought up before: #266, #163, and #37. 

I think perhaps a better way forward is to support a generalized version via:

```cpp
// [[Rcpp::ldflags(-Wl,-S)]]
```

This is one of the features that I'd like to attack when I have a bit more time as I do not want to ruin the work of art that is the Rcpp Attributes system.

**Comment by thirdwing** [comment]
I think it should not be hard to add. However, it seems we need to think more about the design of attribute system.

Can you give some advice? @eddelbuettel

**Comment by kevinushey** [comment]
Well, the problem with using a plain old `ldflags` attribute is that it's not portable. I imagine @dcdillon wants a 'portable' solution, where 'portable' means 'works on Solaris'.

I would suggest that packages just do their own thing, e.g. you can always have in your DESCRIPTION file:

    SystemRequirements: clang or gcc

and tell the CRAN maintainers that you're not interested in supporting non-free operating systems which you have no access to.

**Comment by dcdillon** [comment]
Is there any way we can say PKG_LIBS=xxx unless Solaris?

**Comment by eddelbuettel** [comment]
@dcdillon Yes, (with a fair amount of work) using `configure`. That is _exactly_ what `configure` is good at.

But I am with @kevinushey.  Just alter `SystemRequirements:` to say, for example, "Windows or OS X or Linux". Maybe use a comma instead.  I could swear that CRANberries showed me a new package once that had exactly that.

Now, of course, if you do we may mock you til the end of time for chickening out in front of Solaris.  

In all seriousness though this is a tricky topic. Maybe not the time to rush this.   I *do* like the discussion about the plugin of extra linker flags.  That *is* good.

One loose idea:  do what we did earlier for Rcpp and have R code return the proper string.  Then we know _at run-time_ that it is Slowlaris and we return an empty (and hence very, ahem, "portable") string,  The others get your desired stripping behaviour.

**Comment by dcdillon** [comment]
Can you detect Solaris effectively within R?  If so that's a nice and easy idea.  And `// [[Rcpp::plugins(strip)]]` would definitely be a good thing...good for `RcppArmadillon`...good for `BH`, etc.

**Comment by coatless** [comment]
@dcdillon Yes, you can reliably detect the different OSes.

https://github.com/coatless/balamuta/blob/282771477ecf21a99282e0da2bc053a7a97a1d4e/R/is_os.R#L16-L50

**Comment by dcdillon** [comment]
Well hell...let's do that.  And condition a plugin (I vote for calling it `strip`) on that.

**Comment by dcdillon** [comment]
And for the record, @eddelbuettel, Brian Ripley scares me.  I'm currently trying to create a Solaris VM.

**Comment by eddelbuettel** [comment]
He scares R Core members.  Earlier this afternoon: https://twitter.com/kwbroman/status/759837614262321152

**Comment by dcdillon** [comment]
If we can do something like https://github.com/Dcdillon/RcppHoney/blob/feature/strip-libraries/R/onLoad.R, I will write it up.  Any objections?

**Comment by dcdillon** [comment]
Basically it says, "If we are using a GNU linker (ld or gold), then we can pass `-Wl,-S` to it and get the stripping we desire."
