### ISSUE TITLE
Shall we create branches with ChangeLog.new and inst/NEWS.Rd ?

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#530]
I really, really, really appreciate how everybody updates ChangeLog and NEWS.   This workflow sort-of predates git, and it doesn't merge cleanly.   I am wondering if we should make the 'snippets' that are added called `ChangeLog.new` and `inst/NEWS.Rd.new`?   Or maybe our initials instead of `new`?

Mostly just thinking out loud here to find a better flow that conflicts less.  Feel free to close, or yell at me for being old-fashioned with these files.  It happened before...  :-/

**Comment by jjallaire** [comment]
I think we should just deal with the merge conflicts as they occur (they
aren't that bad). Alternatively we could keep changes to NEWS and ChangeLog
out of our PRs and then update later but that feels like it would risk the
update never happening.

**Comment by nathan-russell** [comment]
I haven't used either of these features, but according to [here](https://about.gitlab.com/2015/02/10/gitlab-reduced-merge-conflicts-by-90-percent-with-changelog-placeholders/#update) and [here](http://roadfiresoftware.com/2015/09/automatically-resolving-git-merge-conflicts-in-xcodes-project-pbxproj/), it looks like adding a [`.gitattributes`](https://git-scm.com/docs/gitattributes) file and specifying something along the lines of `ChangeLog merge=union` and `NEWS.Rd merge=union` could potentially resolve the problem. Any thoughts on this?

**Comment by eddelbuettel** [comment]
@jjallaire Agreed. Thought about this more on the train, and my suggestion was stupid. Creates a new for `.Rbuildignore` and whatnot.

@nathan-russell Most interesting -- that may be _exactly_ what the doctor needed. Ace.  To be tested.
