### ISSUE TITLE
Building with clang++ -stdlib=libcxx on CentOS

### ISSUE THREAD

**Issue by jeroenooms** [RcppCore/Rcpp#536]
Currently Fedora/CentOS has `libcxx` but not `libcxxabi`. Compiling Rcpp fails as below. Is it possible to build Rcpp without `cxxabi.h`? Note that libcxxabi [might make it into Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1332306) at some point, but it would be great if we wouldn't have to wait for that.

```
* installing *source* package ‘Rcpp’ ...
** package ‘Rcpp’ successfully unpacked and MD5 sums checked
** libs
clang++ -stdlib=libc++ -I/usr/include/R -DNDEBUG -I../inst/include/ -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c Date.cpp -o Date.o
clang++ -stdlib=libc++ -I/usr/include/R -DNDEBUG -I../inst/include/ -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c Module.cpp -o Module.o
clang++ -stdlib=libc++ -I/usr/include/R -DNDEBUG -I../inst/include/ -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c Rcpp_init.cpp -o Rcpp_init.o
clang++ -stdlib=libc++ -I/usr/include/R -DNDEBUG -I../inst/include/ -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c api.cpp -o api.o
api.cpp:33:10: fatal error: 'cxxabi.h' file not found
#include <cxxabi.h>
         ^
1 error generated.
```

**Comment by jjallaire** [comment]
It looks like this is already considered an optional feature:
https://github.com/RcppCore/Rcpp/blob/master/src/api.cpp#L32-L34

Seems like we just need a better test here:
https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/platform/compiler.h#L191-L194

**Comment by eddelbuettel** [comment]
What are the defining and identifiable feature of Fedora/CentOS/RHEL, besides being [....retracted by my editor for being unprintable...] ?

How would we test for it?  We do not currently `configure` where `autoconf` does things like identifying presence/absence of headers for breakfast. I see no point in re-inventing this (though other in this thread are known to disagree here).  So maybe for me to sit down and write a short one...

**Comment by jeroenooms** [comment]
For now it would be sufficient if there was configure or make variable that I can pass to `CMD INSTALL` to manually set this. In all likelihood, the problem will solve itself once `libcxxabi` gets accepted into the repositories.

**Comment by eddelbuettel** [comment]
Ok -- we could try to protect the three lines identified by JJ with an outer `#ifndef` -- and you can then tickle this / avoid the demangling definition by defining this.

This demangling test is six years old.  We were fighting some braindead compilers then.  Interesting to see that the RH/FC/CentOS line tends to think it is a good idea to pick this up.    

/me shakes head ...

**Comment by jeroenooms** [comment]
I can just comment hat out manually then and see what happens...

**Comment by jeroenooms** [comment]
Well seems to work. Should I worry about side effects of disabling mangling?

**Comment by eddelbuettel** [comment]
No. It is just used for some (entirely optional) diagnostics and error messages as I recall.

**Comment by jjallaire** [comment]
Yeah, it's just used to propagate C++ stack traces into R (as Dirk said,
diagnostic only).
