### ISSUE TITLE
install.packages problem

### ISSUE THREAD

**Issue by DimitrYo** [RcppCore/Rcpp#538]
Hi!

On Debian 8 when installing Rcpp get an error:

```
In file included from ../inst/include/RcppCommon.h:70:0,
                 from ../inst/include/Rcpp.h:27,
                 from Date.cpp:31:
../inst/include/Rcpp/utils/tinyformat.h:127:10: note: declared here
     void stop(const std::string& message);
          ^
/usr/lib/R/etc/Makeconf:137: recipe for target 'Date.o' failed
make: *** [Date.o] Error 1
ERROR: compilation failed for package ‘Rcpp’
* removing ‘/home/dymytr/R/x86_64-pc-linux-gnu-library/3.1/Rcpp’
Warning in install.packages :
  installation of package ‘Rcpp’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmp48uETh/downloaded_packages’
```

[diagnostics-report.txt](https://github.com/RcppCore/Rcpp/files/413840/diagnostics-report.txt)

**Comment by eddelbuettel** [comment]
Yes, known issue, reported at least three times here (see closed issues) and once on StackOverflow.

Solution: either use a _current version of R_ (at least R 3.2.0 release 15 months ago) which defines the symbol we inserted before the `stop()` that failed, or use Rcpp 0.12.6.1 from the drat which adds the definition.

If I were you I'd look at https://cloud.r-project.org/bin/linux/debian/ to learn about .deb packages with the current R version rebuilt for your older Debian distro.

**Comment by eddelbuettel** [comment]
For reference, this is discussed in #512 (with reference to the drat repo), #516, #519 and #520.
