### ISSUE TITLE
Better handling of std::exception

### ISSUE THREAD

**Issue by dcdillon** [RcppCore/Rcpp#542]
Instead of printing "`std::exception`" as the R error, `ex.what()` would be better.

If one throws a `std::exception` in an Rcpp function, R simply prints "`std::exception`" whereas it could print the value of `std::exception::what()` which is a string representation of what the exception actually is.

```
#include <Rcpp.h>
#include <exception>

class my_exception : public std::exception {
    std::string what() /* override */ {
        return "This is my fun exception";
    }
};

// [[Rcpp::export]]
void throwMeAnException() {
    throw my_exception();
}
```

Results:

```
> throwMeAnException()
Error: std::exception
> 
```

Whereas the error could be "This is my fun exception".

**Comment by eddelbuettel** [comment]
Could it be that you may be fully familiar with Rcpp does?  Copied and pasted from a unit test (where it was as far away as a `grep` call):

```r
R> cppFunction('void foo() { throw std::range_error("boom"); }')
R> foo()
Error: boom
R> 
```

You get the `std::exception` you dread if you fail to supply something better.  If and when you supply something better, you get it.

Our docs are neither great not complete, but one can search.  One doesn't always find stuff -- happens to me too...

**Comment by dcdillon** [comment]
fixed.
