### ISSUE TITLE
Copy construction does not work with vectors returned in Rcpp code

### ISSUE THREAD

**Issue by renkun-ken** [RcppCore/Rcpp#544]
Consider the following Rcpp code:

```cpp
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
NumericVector test(NumericVector x) {
  NumericVector y = x;
  for (int i = 0; i < y.size(); ++i) {
    y[i] *= 2;
  }
  return y;
}
```

The above code assumes that `NumericVector y = x` uses the copy construction so that `y` is the copy of `x` and it is safe to modify and return `y` without affecting `x`. 

Test R code 

```r
x <- 1:10
y <- test(x)
x
y
test(y)
y
```

Surprisingly, the output of the test R code indicates otherwise when input `x` is returned from Rcpp code:

```rconsole
> x <- 1:10
> y <- test(x)
> x
 [1]  1  2  3  4  5  6  7  8  9 10
> y
 [1]  2  4  6  8 10 12 14 16 18 20
> test(y)
 [1]  4  8 12 16 20 24 28 32 36 40
> y
 [1]  4  8 12 16 20 24 28 32 36 40
```

`test(y)` does not return a modified copy of `y` but modifies `y` in place. I wonder if this is the desirable behavior: Vector created in R is somehow different from vector created returned from Rcpp code?

**Comment by kevinushey** [comment]
In general, Rcpp vectors don't have value semantics (they act as proxy objects to an underlying SEXP of some type). This is the documented behavior, e.g. in the introduction vignette.

The perhaps more surprising bit here is the silent coercion of integer vectors to numeric vectors -- when you call `test(x)`, you are passing in an integer vector, and Rcpp automatically converts that to a numeric vector for you behind the scenes -- thereby transiently generating a whole new R SEXP, and acting a proxy to that SEXP.

**Comment by renkun-ken** [comment]
Thanks! If a numeric vector is supplied, the results look consistent with no-copy.

```rconsole
> x <- c(1, 2, 3)
> y <- test(x)
> x
[1] 2 4 6
> y
[1] 2 4 6
> test(y)
[1]  4  8 12
> y
[1]  4  8 12
```
