### ISSUE TITLE
Potential issue with Rcpp Attributes and src/RcppExports.cpp

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#550]
So I have been looking into getting @thirdwing 's nice RcppMLPACK building with an external MLPACK one can eg get via Debian/Ubuntu (to avoid having to link with Boost when we continue to existing path of embedding).  So far, so good.

The package has a `DESCRIPTION` file entry `LinkingTo: Rcpp, RcppArmadillo` which is, I suspect, pretty common given the 250+ dependents RcppArmadillo has on CRAN.

But MLPACK is a little different in that it ties about as closely to Armadillo as we do.  So when RcppExports.cpp gets created with

```c++
// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RcppMLPACK.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>
```

or rather I have a problem when I tried to rewrite `RcppMLPACK.h` such that _it_ already includes RcppArmadillo.h and Rcpp.h.   (As a recap, we walk a fine line of including Rcpp.h _inside_ RcppArmadillo.h so that we get forward declarations right.)  

As a net result, we now **fail** because we get multiple includes.   :cry: 

The best I could come up with so far (besides the obvious manual one of commenting the last two lines in the snippet above) is something like

```c++
// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RcppMLPACK.h"
#if !defined(RcppArmadillo__RcppArmadillo__h)
  #include <RcppArmadillo.h>
#endif
#if !defined(Rcpp_hpp)
  #include <Rcpp.h>
#endif
```

So going forward we would need to recommend a particular 'per-package guard' line, maybe `$pkg__$pkg__h` as RcppArmadillo has (ie changing the one for Rcpp.h, or at least also defining it), and then modify the writing of these in `src/Attributes.cpp` to make it conditional.

Am I making sense, or am I under-caffeinated?

**Comment by kevinushey** [comment]
I'm a little confused -- shouldn't the header guards for `RcppArmadillo.h` and `Rcpp.h` take care of this either way? Ie, as long as you're including `RcppArmadillo.h` before `Rcpp.h` we should be fine?

I'm guessing the error is emitted by inclusion of `RcppArmadillo.h`, and somehow `Rcpp.h` has snuck in 'too early'? Or is it something else?

**Comment by eddelbuettel** [comment]
They should. I realized that too when sitting down for dinner.  I am currently trying to find out why this doesn't protect them. I also realized that 'worst case' I could just `#define` those guards again at the end of `RcppMLPACK.h` (which is the one that has to walk the fine line of ordering MLPACK, Rcpp and Armadillo header includes).

**Comment by eddelbuettel** [comment]
And this commit f649032c031c248bc7b583d0d700d683a870b38b achieves it.  The issue, as it were, was that I had to 'unorder' inclusion from within `RcppArmadillo.h` inside of `RcppMLPACK.h`.  So the former was included "in its parts" but eg withhout its header guard, and hence include guard.  

No change to Rcpp headerd :cake: :100: :grinning:
