### ISSUE TITLE
Factory classes

### ISSUE THREAD

**Issue by krlmlr** [RcppCore/Rcpp#554]
My IDE doesn't recognize `List::create(...)` with more than one argument. I suspect this is because `Rcpp/generated/Vector__create.h` is included from inside a class. **IDE issues aside**, this doesn't exactly look like the cleanest solution to that problem.

Would you consider moving the `create(...)` method to a mixin that uses the CRTP? The definition of that mixin could be autogenerated entirely. (Where do I find the code that generates the `__generated.h` files?)

```cpp
template <...>
class Vector : public VectorFactory<...>, ... {
}

template <...>
class VectorFactory {
public:
  static Vector<...> create(...) { return ...; }
}
```

**Comment by eddelbuettel** [comment]
Well, strictly personally speaking, I am not very motivated to risk the stability of Rcpp over one person's IDE enjoyment.   Maybe you get other people on the team to speak up for you.

The scripts are in the [scripts/ directory of the rcpp-scripts repo](https://github.com/RcppCore/rcpp-scripts/tree/master/scripts) but be careful as sometimes changes were made is a rush by some committers which did not result in updated scripts.

**Comment by krlmlr** [comment]
I see your point. The proposed change involves CRTP with a template template parameter, do you think the compiler might choke?

I'll work around the issue for my IDE. There's good old `...` ;-)
