### ISSUE TITLE
Compiling error on OSX using clang++

### ISSUE THREAD

**Issue by thirdwing** [RcppCore/Rcpp#558]
I met an error when compiling the latest Rcpp on OSX using clang++.

@kevinushey Can you help to confirm this?

A simple file to reproduce the error
```cpp
#include <Rcpp.h>

using namespace Rcpp;

//[[Rcpp::export]]
void test() {
  Datetime d1 = Datetime(946774923.123456);                                                       
  Datetime d2 = d1 + 60*60;
}
```

In R

```
> Rcpp::sourceCpp("test.cpp")
test.cpp:8:20: error: use of overloaded operator '+' is ambiguous (with operand
      types 'Rcpp::Datetime' and 'int')
  Datetime d2 = d1 + 60*60;
                ~~ ^ ~~~~~
/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include/Rcpp/date_datetime/Datetime.h:108:21: note: 
      candidate function
    inline Datetime operator+(const Datetime &datetime, double offset) {
                    ^
test.cpp:8:20: note: built-in candidate operator+(double, int)
  Datetime d2 = d1 + 60*60;
                   ^
test.cpp:8:20: note: built-in candidate operator+(unsigned __int128, int)
test.cpp:8:20: note: built-in candidate operator+(unsigned long long, int)
test.cpp:8:20: note: built-in candidate operator+(unsigned long, int)
test.cpp:8:20: note: built-in candidate operator+(float, int)
test.cpp:8:20: note: built-in candidate operator+(unsigned int, int)
test.cpp:8:20: note: built-in candidate operator+(__int128, int)
test.cpp:8:20: note: built-in candidate operator+(long long, int)
test.cpp:8:20: note: built-in candidate operator+(long, int)
test.cpp:8:20: note: built-in candidate operator+(int, int)
```

**Comment by eddelbuettel** [comment]
Not clang++ specific.  Also bombs for me:

```r
R> library(Rcpp)
R> sourceCpp("/tmp/kk.cpp")
kk.cpp: In function ‘void datetest()’:
kk.cpp:10:20: error: ambiguous overload for ‘operator+’ (operand types are ‘Rcpp::Datetime’ and ‘int’)
   Datetime d2 = d1 + 60*60;
                    ^
kk.cpp:10:20: note: candidate: operator+(double, int) <built-in>
In file included from /usr/local/lib/R/site-library/Rcpp/include/Rcpp/date_datetime/date_datetime.h:29:0,
                 from /usr/local/lib/R/site-library/Rcpp/include/Rcpp.h:60,
                 from kk.cpp:3:
/usr/local/lib/R/site-library/Rcpp/include/Rcpp/date_datetime/Datetime.h:108:21: note: candidate: Rcpp::Datetime Rcpp::operator+(const Rcpp::Datetime&, double)
     inline Datetime operator+(const Datetime &datetime, double offset) {
                     ^
make: *** [kk.o] Error 1
ccache g++ -I/usr/share/R/include -DNDEBUG    -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/tmp"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -O3 -Wall -pipe -Wno-unused -pedantic  -c kk.cpp -o kk.o
/usr/lib/R/etc/Makeconf:141: recipe for target 'kk.o' failed
Error in sourceCpp("/tmp/kk.cpp") : 
  Error 1 occurred building shared library.
R> 
```

Code ensures that the `#define` we need is ON:

```C++

#define RCPP_NEW_DATE_DATETIME_VECTORS 1
#include <Rcpp.h>

using namespace Rcpp;

//[[Rcpp::export]]
void datetest() {
  Datetime d1 = Datetime(946774923.123456);                                                       
  Datetime d2 = d1 + 60*60;
}

/*** R
datetest()
*/
```

**Comment by eddelbuettel** [comment]
When you make it ` Datetime d2 = d1 + 60*60*1.0;` is passes. I presume we need another line [here](https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/date_datetime/Datetime.h#L56+L64).

**Comment by thirdwing** [comment]
I got these two lines of code from our [unit test](https://github.com/RcppCore/Rcpp/blob/master/inst/unitTests/cpp/dates.cpp#L127-L128). I thought it could compile on Linux.

**Comment by eddelbuettel** [comment]
Color me confused then.

Also:  The `Datetime` class has not changed in years.  If that failed, it failed for a long time.  Or maybe clang++ just got stricter.

Anyway, baby PR forthcoming.  Just typed it on the train an hour ago.

**Comment by eddelbuettel** [comment]
Worse, now I can't replicate the failure, and I don't recall which machine I ran that one...

**Comment by thirdwing** [comment]
It seems `clang++` is stricter. Personally I think the error is due to the new `operator double()  const { return m_dt; }`.

In `Datetime d2 = d1 + 60*60;`, `clang++` thought there are more than one candidate functions it can use:

It thinks it can call the `operator double()` of `Datetime`, then performs a plus between a double and int.

It thinks it can also convert the `int` into `double` then call `inline Datetime operator+(const Datetime &datetime, double offset)`

**Comment by eddelbuettel** [comment]
Yes, likely that `operator double()` is involved.  That is the change event.  Not turned on by default yet though...

**Comment by thirdwing** [comment]
I saw your commit.

BTW, do you think it is necessary to add OSX into travis testing?

**Comment by eddelbuettel** [comment]
I always hesitated doing that because ... it slows things down more, and gives extra admin headaches.

So far we have not _really_ needed it as enough of us do run on OS X.  I'd prefer to wait for R Hub.

**Comment by thirdwing** [comment]
Yes, R hub. I almost forget it. Let’s look forward to it.

**Comment by eddelbuettel** [comment]
Rhub is _awesome_. Install it now.   I.e. tested a Windows build the other day, you launch from a local R prompt and it _looks_ as if it is local -- but it remote via JSON streaming.  Super impressive.  Reported a few baby bugs which Gabor all fixes in now time.

**Comment by eddelbuettel** [comment]
Package is [here](https://github.com/r-hub/rhub) and needs a bunch other micro-packages by Gabor.

No OS X yet, but plenty of different Linux + Windows builds.  Twelve in total as I recall.
