### ISSUE TITLE
New matrix ctor to allow for fill on dimension creation

### ISSUE THREAD

**Issue by coatless** [RcppCore/Rcpp#562]
Going through the matrix options right now, there seems to be only two options to fill a matrix:

``` cpp
// by vector
NumericVector x = NumericVector(100, 2.0); 
y = NumericMatrix(10, 10, v.begin());


// using stl
NumericMatrix z(10,10);
std::fill(z.begin, z.end(), 2.0);
```

However, as indicated by option using a vector, it would be nice to be able to immediately specify the fill value within the constructor:

``` cpp
// proposed addition
NumericMatrix z2(10, 10, 2.0);
```

**Comment by eddelbuettel** [comment]
Yep, could do.

**Comment by coatless** [comment]
The ctor would need to be:

```cpp
template <typename U>
Matrix( const int& nrows_, const int& ncols, const U& u) : 
        VECTOR( Dimension( nrows_, ncols ), u ), nrows(nrows_) { } // Vector ctor already exists.
```
    
The only issue with this approach is a ctor of `Matrix(int, int, typename)` already exists for handling iterators

```cpp
template <typename Iterator>
Matrix( const int& nrows_, const int& ncols, Iterator start ) :
        VECTOR( start, start + (static_cast<R_xlen_t>(nrows_)*ncols) ),
        nrows(nrows_)
{
        VECTOR::attr( "dim" ) = Dimension( nrows, ncols ) ;
}
```

**Comment by thirdwing** [comment]
If we really need this, it can be done like below:

```cpp
template <typename U>
Matrix(const int& nrows_, const int& ncols, const U& u,
       typename Rcpp::traits::enable_if<traits::is_arithmetic<U>::value, void>::type* = 0)
```

**Comment by coatless** [comment]
Sadly, when I tried this, it was picked up as ambiguous since the first three parameters are the same. 

However, I think a modification to the `Iterator` based ctor to verify if the object is an iterator should suffix to fix the problem. Browsing quickly through the source, it looks like [`Rcpp::traits`]() will need to be modified to support a SFINAE `is_iterator()`.

 Though, a simpler solution would be to create a matrix ctor with

```cpp
template <typename U>
Matrix( Dimension &dims, const U& u ) : VECTOR( Dimension( dims ), u )
```

Or as @eddelbuettel has proposed in the PR, just simply rely on the `.fill()`.
