### ISSUE TITLE
Environment.get() version throwing an exception instead of returning NULL

### ISSUE THREAD

**Issue by progtw** [RcppCore/Rcpp#571]
In R one can search an environment without inheritance and find names that have NULL assigned:
`get( "varName", envir=enEnv, inherits=FALSE)`

`Rcpp::Environement::get` method returns NULL if the name is not assigned. Hence it cannot distinguish between a name bound to NULL or a nonexisting name.

`Rcpp::Environement::find` methods throws an error if the name is not bound. Hence, it is suitable to distinguish unbound versus NULL-bound names. However it corresponds to inherits=TRUE.

Hence, a method in the Environment class would be welcomed that throws an exception instead of returning NULL but only searches the environment without its parents. Name suggestion: `SEXP getThrows( const std::string& name) const`

**Comment by eddelbuettel** [comment]
Good report.  Would you mind just putting together a five or ten liner we can `sourceCpp()` to have concrete behaviour?   A working example of what exactly you don R and what to do from C++ would also help.

The `NULL` as 'not here' as well explicit `assigned NULL` is a little unfortunate.   We can probably extend the API to add a `bool isSet(const std::string& varname)` or something like  that.

**Comment by kevinushey** [comment]
The other alternate is to return the sentinel R value `R_UnboundValue`, and instruct users to check against that value.

**Comment by progtw** [comment]
Here the code with concrete behaviour.

```
get_cpp <- cxxfunction(signature(name_x="character", envir_x="environment"),	
		plugin="Rcpp"
		,body='
				std::string name = as<std::string>(name_x);
				Environment envir(envir_x);
				return envir.get(name);
				')

find_cpp <- cxxfunction(signature(name_x="character", envir_x="environment"),	
		plugin="Rcpp"
		,body='
				std::string name = as<std::string>(name_x);
				Environment envir(envir_x);
				return envir.find(name);
				')

c <- "cParent"		# value in parent environment
a <- "aParent"
env <- new.env()
env$a <- NULL

stopifnot(  get("a", envir=env, inherits=FALSE) == NULL )
try(  get("c", envir=env, inherits=FALSE)  )	# expect error
#stopifnot(  get("a", envir=env, inherits=TRUE) == "aParent" )

get_cpp("a", env)	# NULL wanted behaviour
get_cpp("nonExisting", env)	# NULL instead of notification that it is not existing
get_cpp("c", env)	# NULL instead of notification that it is not existing

find_cpp("a", env)	# NULL wanted behaviour
try(find_cpp("nonExisting", env))  # error: wanted behaviour 
find_cpp("c", env)  # "cParent": instead of notification 
```

**Comment by eddelbuettel** [comment]
Same thing using Rcpp Attributes which makes it a lot more concide. 

Use `sourceCpp("nameOfTheFile.cpp")` to _build and run the R illustration_ in one step.

```c++
#include <Rcpp.h>

using namespace Rcpp;

// [[Rcpp::export]]
Environment get_cpp(std::string name, Environment envir) {
  return envir.get(name);
}

Environment find_cpp(std::string name, Environment envir) {   
  return envir.find(name);
}

/*** R
c <- "cParent"      # value in parent environment
a <- "aParent"
env <- new.env()
env$a <- NULL

stopifnot(  get("a", envir=env, inherits=FALSE) == NULL )
try(  get("c", envir=env, inherits=FALSE)  )    # expect error
stopifnot(  get("a", envir=env, inherits=TRUE) == NULL )

get_cpp("a", env)   # NULL wanted behaviour
get_cpp("nonExisting", env) # NULL instead of notification that it is not existing
get_cpp("c", env)   # NULL instead of notification that it is not existing

find_cpp("a", env)  # NULL wanted behaviour
try(find_cpp("nonExisting", env))  # error: wanted behaviour 
find_cpp("c", env)  # "cParent": instead of notification 
*/
```

**Comment by progtw** [comment]
I am not familiar with R Internals. But being able to check the return value with an if-statement (as I understood @kevinushey) in order to distinguish unbound versus NULL values would probably be better and faster than using try-catch statements. An example of how to do this check should then be provided in the function documentation.

**Comment by coatless** [comment]
So, harvesting from [`Environment` `get`](https://github.com/RcppCore/Rcpp/blob/327d0574b21634f08c9013a5c82a6676fa2f3a1b/inst/include/Rcpp/Environment.h#L106-L110) the `isSet` is straightforward with the exception of what to do in regard to promises.  Should the promise be evaluated and if there is a result then the value is set? Or is just the presence of the promise sufficient enough to trigger a set condition? 

I've opted to go along the lines of the later here:
```cpp
bool isSet(const std::string& name) const {
    SEXP env = Storage::get__() ;
    SEXP nameSym = Rf_install(name.c_str());
    SEXP res = Rf_findVarInFrame( env, nameSym ) ;
    
    if( res == R_UnboundValue ) return false; // not found in environment
    
    return true; // object _might_ be a promise in this case.
}
```

```r
> is_cpp("a", env)   # exists
[1] TRUE

> is_cpp("nonExisting", env) #  not existing
[1] FALSE

> is_cpp("c", env)   #  not existing
[1] FALSE
```

**Comment by coatless** [comment]
@progtw, sorry for not seeing this earlier, but the above function is not necessary as Rcpp already has one that provides the same functionality via [`exists`](https://github.com/RcppCore/Rcpp/blob/327d0574b21634f08c9013a5c82a6676fa2f3a1b/inst/include/Rcpp/Environment.h#L184-L196).  

Example:

```cpp
// [[Rcpp::export]]
bool exists_cpp(std::string name, Environment envir) {   
  return envir.exists(name);
}
```

**Comment by coatless** [comment]
@eddelbuettel: This issue can be closed out as the functionality already exists in the member function `exists`.
