### ISSUE TITLE
Signed / unsigned comparisons in IndexHash

### ISSUE THREAD

**Issue by nathan-russell** [RcppCore/Rcpp#574]
When compiled with `-Wall` (GCC 4.9.2), the following generates warnings for me: 

```c++
#include <Rcpp.h>

// [[Rcpp::export]]
int usize(Rcpp::IntegerVector x) {
    return Rcpp::unique(x).size();
}
```

> /home/nathan/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include/Rcpp/hash/IndexHash.h:173:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>                if (addr == m) {

--------

`IndexHash` has some `int` [members](https://github.com/RcppCore/Rcpp/blob/adae3fe4eb094eb45419b35c49c3f6fd5071267d/inst/include/Rcpp/hash/IndexHash.h#L119) and for the most part seems to stick to signed-signed comparison; [this block](https://github.com/RcppCore/Rcpp/blob/adae3fe4eb094eb45419b35c49c3f6fd5071267d/inst/include/Rcpp/hash/IndexHash.h#L170-L176) being an exception which results in the above warning. There is another such comparison [done here](https://github.com/RcppCore/Rcpp/blob/adae3fe4eb094eb45419b35c49c3f6fd5071267d/inst/include/Rcpp/hash/IndexHash.h#L189-L195) as well. 

Is anyone else able to reproduce this?

**Comment by eddelbuettel** [comment]
Confirmed on Ubuntu 16.04 with g++ 5.4.0:

```
/usr/lib/R/bin/R CMD SHLIB -o 'sourceCpp_7.so'  'nr.cpp'  
ccache g++ -I/usr/share/R/include -DNDEBUG    -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/tmp"    -fpic  -g -O3 -Wall -pipe -Wno-unused -pedantic -c nr.cpp -o nr.o
In file included from /usr/local/lib/R/site-library/Rcpp/include/Rcpp/hash/hash.h:27:0,
                 from /usr/local/lib/R/site-library/Rcpp/include/Rcpp/sugar/sugar.h:28,
                 from /usr/local/lib/R/site-library/Rcpp/include/Rcpp.h:70,
                 from nr.cpp:1:
/usr/local/lib/R/site-library/Rcpp/include/Rcpp/hash/IndexHash.h: In instantiation of ‘bool Rcpp::sugar::IndexHash<RTYPE>::add_value(int) [with int RTYPE = 13]’:
/usr/local/lib/R/site-library/Rcpp/include/Rcpp/hash/IndexHash.h:77:46:   required from ‘Rcpp::sugar::IndexHash<RTYPE>& Rcpp::sugar::IndexHash<RTYPE>::fill() [with int RTYPE = 13]’
/usr/local/lib/R/site-library/Rcpp/include/Rcpp/sugar/functions/unique.h:68:2:   required from ‘Rcpp::Vector<RTYPE> Rcpp::unique(const Rcpp::VectorBase<RHS_RTYPE, RHS_NA, RHS_T>&) [with int RTYPE = 13; bool NA = true; T = Rcpp::Vector<13>]’
nr.cpp:5:26:   required from here
/usr/local/lib/R/site-library/Rcpp/include/Rcpp/hash/IndexHash.h:173:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
               if (addr == m) {
                        ^
g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o sourceCpp_7.so nr.o -L/usr/lib/R/lib -lR
R> 
```

**Comment by thirdwing** [comment]
@nathan-russell Thank you for reporting this. PR is always welcome.

We are on the way to investigate compiler warnings with -Wconversion (https://github.com/RcppCore/Rcpp/issues/391). It will be great if you can also spend some time to look into the conversion and comparison warnings.

**Comment by nathan-russell** [comment]
@thirdwing I'd be happy to try to track down more issues like this one, but I was actually hoping to get some input from others on the recommended fix in this particular case. It seems to me that the least-intrusive change would be just adding a C-style cast to one of the variables in the expression `if (addr == m)`, and that `if (addr == (unsigned int)m)` would be preferable to `if ((int)addr == m)`. Do you agree?

**Comment by kevinushey** [comment]
I think casting would be fine here.

**Comment by eddelbuettel** [comment]
I have a moderate preference for `static_cast<type>(var)` over `(type) var`.
