### ISSUE TITLE
Obtain typed value from Shield<>

### ISSUE THREAD

**Issue by krlmlr** [RcppCore/Rcpp#580]
I would have expected to find an `operator T()` in the class definition of `Shield` and friends. Is there a particular reason why these classes don't seem to use their template parameter at all? 

Changing that now will probably affect existing code, but how about implementing `T get() const`?

**EDIT**: After revisiting what `PreserveStorage` does, this would be probably very slow and useless. But there's `NoProtectStorage`, if we could get e.g. from `List` (which is a `List_Impl<PreserveStorage>`) to `List_Impl<NoProtectStorage>` and use that as return type for the new getter?

**Comment by romainfrancois** [comment]
`Shield` is only really expected to work with `T = SEXP`

**Comment by eddelbuettel** [comment]
@krlmlr Is this a more "theoretical" desire (as in: each templated class should have such an operator) or do you need this for actual code?

**Comment by krlmlr** [comment]
Two issues here:

1. I may have a wrong understanding about the aims of `Shield<>`, it just puzzles me to see a template class where the template parameter is not used.
2. I understand that `PreserveStorage` is the safest option, but a `ProtectStorage` (doing essentially the same as `Shield`) seems to be missing. R-exts 5.9.1 (at the bottom) claims that preserving storage is

    > less efficient that the normal protection mechanism, and should be used sparingly.

    Could you please comment?

**Comment by eddelbuettel** [comment]
Well, it always depends.  I would time on the type of data you deem representative for your use case.

**Comment by eddelbuettel** [comment]
But I don't see an "issue" here.  That was more of an open-ended question for which rcpp-devel may be more suited.
