### ISSUE TITLE
Matrix/Matrix Arithmetic Operators

### ISSUE THREAD

**Issue by dcdillon** [RcppCore/Rcpp#583]
This one's a bit tricky and the answer may be "don't bother, it's not a big deal", but currently one cannot do elementwise `Matrix op Matrix`.  This is a result of the way the `sugar` operators are implemented (i.e. they operate on `VectorBase` and drop attributes).

Specifically, if one tries to

```
// [[Rcpp::export]]
SEXP test_matrix(Rcpp::NumericMatrix a, Rcpp::NumericMatrix b)
{
        return Rcpp::wrap(a + b);
}
```
the result is a `Vector` (as evidenced below).
 ```
> m <- matrix(c(1, 2, 3,4), 2, 2)
> m
     [,1] [,2]
[1,]    1    3
[2,]    2    4
> test_matrix(m, m)
[1] 2 4 6 8
```

I'm wondering if we couldn't create `sugar` expression templates like `sugar::Matrix_Matrix_Plus` which would be analogous to `sugar::Vector_Vector_Plus` but would preserve the attributes (and probably throw on dimension mismatch).

Now this raises the question what does `Matrix * Matrix` mean.  Obviously `+, -, and /` are elementwise operations, but `*` may want to be matrix multiplication.

Anyhow, this obviously isn't high priority, but it would be nice.

**Comment by coatless** [comment]
Definitely nice.

I think mimicking armadillo's approach with regard to matrix multiplication would be preferred. That is:

- `*` to define traditional matrix multiplication e.g. `n x p` v `p x q` = `n x q` .
- `%` defines element-wise matrix multiplication.
