### ISSUE TITLE
Rcpp no longer builds with RCPP_NO_SUGAR defined

### ISSUE THREAD

**Issue by dcdillon** [RcppCore/Rcpp#584]
This is mostly due to the fact that `RNGScope` is defined inside `inst/include/Rcpp/stats/random/random.h` and is used outside the stats directory.  There is also a small issue with the `Matrix op scalar` functions in `inst/include/Rcpp/vector/Matrix.h`.

Moving the definition of `RNGScope` outside of stats (to its own file) and including it unconditionally will fix the former.  Protecting the `Matrix op scalar` functions with `#ifndef RCPP_NO_SUGAR` will fix the latter.

**Comment by dcdillon** [comment]
Here's an example:

test.cpp:
```c++
#define RCPP_NO_SUGAR

#include <Rcpp.h>

using namespace Rcpp;

// [[Rcpp::export]]
NumericVector test_no_sugar(NumericVector v) {
        return v;
}
```

```
> library(Rcpp)
> sourceCpp("test.cpp")
test.cpp: In function ‘SEXPREC* sourceCpp_1_test_no_sugar(SEXP)’:
test.cpp:19:5: error: ‘RNGScope’ is not a member of ‘Rcpp’
     Rcpp::RNGScope rcpp_rngScope_gen;
     ^
make: *** [test.o] Error 1
g++ -I/usr/share/R/include -DNDEBUG    -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/home/dcdillon/src/git"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c test.cpp -o test.o
/usr/lib/R/etc/Makeconf:141: recipe for target 'test.o' failed
Error in sourceCpp("test.cpp") : 
  Error 1 occurred building shared library.
> 
```

**Comment by eddelbuettel** [comment]
Could you prepare a PR?

**Comment by dcdillon** [comment]
Wrote it before I posted the issue.  30 more seconds.
