### ISSUE TITLE
Checking for interrupt

### ISSUE THREAD

**Issue by jeroenooms** [RcppCore/Rcpp#586]
Would be nice to have an API for dealing with user interruptions. R allows for checking for SIGINT via the C API:

    R_CheckUserInterrupt();

However this function will immediately jump back to the console if an interruption is pending which can leave your C/C++ code in an undefined state.

A trick [suggested](https://stat.ethz.ch/pipermail/r-devel/2011-April/060702.html) by @s-u is to use the following wrapper code:

	/* Check for interrupt without long jumping */
	void check_interrupt_fn(void *dummy) {
	  R_CheckUserInterrupt();
	}

	int pending_interrupt() {
	  return !(R_ToplevelExec(check_interrupt_fn, NULL));
	}

This is in use in several CRAN packages. Perhaps something like that can be exposed in Rcpp.

An alternative way to deal with interrupts is to attach a handler. For example it could automatically raise an exception like below. I guess that only works when R code is evaluated. Not sure if there is a sensible way to expose something like that in Rcpp.

```r
tryCatch({
  Sys.sleep(99)
}, interrupt = function(e){ stop("USER INTERRUPT") })
```

**Comment by jjallaire** [comment]
We have this already (see section 2.4 of the Rcpp Attributes vignette).

**Comment by jeroenooms** [comment]
Awesome. Dirk didn't seem to be aware of this :)

**Comment by eddelbuettel** [comment]
Haha, good one.  Didn't I add in the very SO comment (which you chose not to reference, and which I can't find -- did you delete that question) I think I referenced that we had something.  

In any event, you and I had a number of exchanges now where I mostly shake my head because you not-so-infrequently seem to ask for a contraption or device ... we have had in Rcpp for years :)

**Comment by jeroenooms** [comment]
http://stackoverflow.com/questions/40563522/r-how-to-write-interruptible-c-function-and-recover-partial-results/40565675

**Comment by eddelbuettel** [comment]
Right. Didn't find it, somehow, when I looked.  So my immediate hint was "we got this". Still true today :)

**Comment by kevinushey** [comment]
Note that you only want to use `Rcpp::checkUserInterrupt()` if you're also using Rcpp Attributes to generate your interfaces (since that function will throw an exception that's normally only caught by the boilerplate generated by e.g. `Rcpp::compileAttributes()`).

**Comment by jjallaire** [comment]
You can technically also use the RCPP_BEGIN and RCPP_END macros (w/o using
attributes) and the interrupts will be handled correctly (their handling is
essentially analogous to / related to our standard handling of exceptions)
