### ISSUE TITLE
Rcpp sp_mat doesn't work for Sparse Symmetric Matrices

### ISSUE THREAD

**Issue by jeffwong-nflx** [RcppCore/Rcpp#590]
This code produces a sparse symmetric matrix, a special case when crossprod(x) is known to be symmetric.
```
require(Matrix)
x = rsparsematrix(10000, 50, .05)
x2 = crossprod(x)
```
Note that the nonzero values stored in x2 only reflect the upper triangle
```
x2@x #only upper triangle part!
```
When this is sent to Rcpp as a sp_mat, only the upper triangle is sent, and Rcpp thinks that the lower triangle is all 0

```
#include <RcppArmadillo.h>
// [[Rcpp::depends(RcppArmadillo)]]

using namespace Rcpp;
using namespace arma;

// [[Rcpp::export]]
sp_mat foo(sp_mat X) {
  return X;
}
```

```
foo(crossprod(rsparsematrix(10000, 5, .01)))
```

**Comment by eddelbuettel** [comment]
Wrong repo.  RcppArmadillo != Rcpp.  Can you close here, and reopen there?

**Comment by jeffwong-nflx** [comment]
Moved to here

https://github.com/RcppCore/RcppArmadillo/issues/114

Thanks
