### ISSUE TITLE
Sugar ops unit tests

### ISSUE THREAD

**Issue by romainfrancois** [RcppCore/Rcpp#6]
Sugar ops unit tests on +, -, ... need double, fail with int

**Comment by coatless** [comment]
This issue has been addressed in [/inst/unitTests/runit.sugar.R](https://github.com/RcppCore/Rcpp/blob/e09f1b333893d3df606625e49628ee109d72bba2/inst/unitTests/runit.sugar.R#L667-L692) for vectors (See commit 48ec3a6e7cfcb4a765741ec717df44816b62f2cf) and [/inst/unitTests/cpp/Matrix.cpp](https://github.com/RcppCore/Rcpp/blob/e09f1b333893d3df606625e49628ee109d72bba2/inst/unitTests/cpp/Matrix.cpp#L315-L333) for matrices (See PR #406)

Notes: The vector operations allow for vector on vector and vector on constant. The matrix operations only allow for matrix on constant (element-wise) manipulation.

Possible feature: Matrix Multiplication (perhaps use the `%` operator for element-wise manipulation similar to `armadillo`?) and Matrix to Matrix Addition. 

Please close. (Tagging #506)
