### ISSUE TITLE
Possible g++-6.2.0 issue

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#600]
On my laptop with Ubuntu 16.10:

```r
> library(Rcpp)
> cppFunction("IntegerVector runit_intersect( IntegerVector x, IntegerVector y){return intersect( x, y ) ;} ")
> runit_intersect(1:10, 1:5)
[1] 1 5 4 3 2
> runit_intersect(1:5, 1:10)
[1] 4 5 1 2 3
> 
```

That is a really old unit test which suddenly blows up.  _Could_ be the branch I am on (for the open PR) but I doubt that.

**Comment by eddelbuettel** [comment]
Where with 16.04 and g++-5.4.*:

```
R> library(Rcpp)
R> cppFunction("IntegerVector runit_intersect( IntegerVector x, IntegerVector y){return intersect( x, y ) ;} ")
R> runit_intersect(1:10, 1:5)
[1] 1 2 3 4 5
R> runit_intersect(1:5, 1:10)
[1] 1 2 3 4 5
R> 
```

and the implicit sorting is what the unit test needs.   

Now, the bigger question:  shoud `intersect()` sort?

**Comment by kevinushey** [comment]
It looks like Rcpp tries to detect whether `std::unordered_set` is available, and use that if so. Are you able to reproduce with older compilers + `// [[Rcpp::plugins(cpp11)`?

The `Insersect` class has this: (https://github.com/RcppCore/Rcpp/blob/7a22d2144ccc67cdcb399ce0f70d5ed6ef9da29e/inst/include/Rcpp/sugar/functions/setdiff.h#L99-L130):

```
    template <int RTYPE, bool LHS_NA, typename LHS_T, bool RHS_NA, typename RHS_T>
    class Intersect {
    public:
        typedef typename Rcpp::traits::storage_type<RTYPE>::type STORAGE ;

        Intersect( const LHS_T& lhs, const RHS_T& rhs) :
            intersect()
        {

            SET lhs_set( get_const_begin(lhs), get_const_end(lhs) ) ;
            SET rhs_set( get_const_begin(rhs), get_const_end(rhs) ) ;

            ITERATOR end = lhs_set.end() ;
            ITERATOR rhs_end = rhs_set.end() ;
            for( ITERATOR it=lhs_set.begin(); it != end; it++){
                if( rhs_set.find(*it) != rhs_end ) intersect.insert(*it) ;
            }
        }

        Vector<RTYPE> get() const {
            R_xlen_t n = intersect.size() ;
            Vector<RTYPE> out = no_init(n) ;
            std::copy( intersect.begin(), intersect.end(), out.begin() ) ;
            return out ;
        }

    private:
        typedef RCPP_UNORDERED_SET<STORAGE> SET ;
        typedef typename SET::const_iterator ITERATOR ;
        SET intersect ;

    } ;
```

so it seems like it never really wanted to preserve order.  I think that `RCPP_UNORDERED_MAP` and `RCPP_UNORDERED_SET` are actually just plain old `std::map` and `std::set` with C++98 compilers (most of the time).

**Comment by eddelbuettel** [comment]
Yes, we had those old fallback since the glory old days of `tr1` and what not.

Question really is what behaviour we want to assume.  This super-simple test blew up on me:

```c++
// [[Rcpp::export]]
IntegerVector runit_intersect( IntegerVector x, IntegerVector y){
    return intersect( x, y ) ;
}
```

and

```r
#    test.intersect <- function(){
#        checkEquals( runit_intersect( 1:10, 1:5 ), intersect( 1:10, 1:5 ) )
#    }
```

But the bigger question really how we want this to behave ?  I guess we could just be generous and assume little and `sort()` on both parts inside `checkEquals()` ?

**Comment by eddelbuettel** [comment]
I added a `sort()` and restated the test, that helps for now.   The issue of whether we want to assume sorted or unsorted output remains.
