### ISSUE TITLE
Rewriting Rcpp Modules Vignette

### ISSUE THREAD

**Issue by coatless** [RcppCore/Rcpp#603]
Per conversation with Christian Gunning, there is a lot of work related to improving the clarity of the Rcpp Modules vignette...

He made several good suggestions... In particular: 

> * 1 Motivation - edit to explain that modules is intended for exposing C++
 classes in R, and explain relation to attributes
> * 1.1 - remove
> * 1.2 - move to beginning of section 2, "the hard way"
> * 2.1 - remove
> * 2.1.1-2.1.2 - move to end of section 2, "other issues"
> * 3.1.2 - remove example of deprecated loadRcppModules (move note r.e.
 deprecation to after loadModule example)
> * 4 - remove

Typically, I've avoided removing sections before... However, given the state of Modules, I'm in favor of simplifying the documentation as much as possible even if this means documentation number breakage (e.g. Citation of 1.1 no longer correctly refers to the right section).

**Comment by helmingstay** [comment]
FYI, Christian = me :)

**Comment by coatless** [comment]
Oh hey @helmingstay ! Pleasure to meet you on GH =)

**Comment by carlganz** [comment]
Sorry if this is the wrong forum to comment, but it would be helpful if the updated modules vignette mentioned `RCPP_EXPOSED_CLASS`. Apropos of this SO question: http://stackoverflow.com/questions/33549712/using-a-class-as-a-parameter-in-a-constructor-of-another-class

Forgetting `RCPP_EXPOSED_CLASS` has bitten me a few times, and it doesn't appear to be documented anywhere as far as I know. 

Thanks

**Comment by eddelbuettel** [comment]
Did you see #416 and then [this commit](https://github.com/RcppCore/Rcpp/commit/8bc879052fd2a5fcef76828d79bee68871183eb7) ?

**Comment by carlganz** [comment]
I did not. Thanks. I still think it makes sense to mention it in the Modules vignette.

**Comment by coatless** [comment]
@eddelbuettel: Please flag as documentation. 

After thinking about it, I'm highly in favor of re-writing the sections and deleting a few paragraphs (oh the hu-manatee of it). I'm also thinking about focusing more on shifting the focus from an `inline` perspective to emphasizing that Modules should be used predominately within packages due to limited support with attributes. Thoughts?
