### ISSUE TITLE
EnvironmentImpl::new_child() is missing const qualifier

### ISSUE THREAD

**Issue by krlmlr** [RcppCore/Rcpp#609]
without apparent reason. (Unless this is intended as a warning to the fact that it performs a callback to R. It's a shame there seems to be no C API for this.)

**Comment by eddelbuettel** [comment]
Could you at least reference a file, preferably a line too, and ideally even show compiler output?

**Comment by krlmlr** [comment]
Thanks.

```
> grep -rn 'new_child' inst/include
inst/include/Rcpp/Environment.h:392:        Environment_Impl new_child(bool hashed) {
```

Most other methods have a `const` between `)` and `{`, I don't see why `new_child()` shouldn't. I'm trying to use `const` references where possible.

**Comment by coatless** [comment]
Only one `Environment_Impl` has a `const` tag and that is `Environment_Impl parent()`

https://github.com/RcppCore/Rcpp/blob/8e3076d818961874cb49151ddec75bdc0444c250/inst/include/Rcpp/Environment.h#L328-L395

**Comment by eddelbuettel** [comment]
Closing this.
