### ISSUE TITLE
Development version broken for STRICT_R_HEADERS

### ISSUE THREAD

**Issue by jeroenooms** [RcppCore/Rcpp#612]
For some packages we need to `#define STRICT_R_HEADERS` because macros like `Calloc`, `Free` and `ERROR` conflict with identically named macros in other libraries. 

This is working fine in Rcpp from CRAN, however in the development version of Rcpp I now get errors on Windows. It looks like a recent change in [sugar/functions/sample.h](https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/sugar/functions/sample.h) has started using S-style `Calloc` and `Free` instead of stdlib `calloc` and `free`. 

Is this intentional? It will break many packages that use `<Rcpp.h>` in conjunction with `STRICT_R_HEADERS`.

```r
devtools::install_github("RcppCore/Rcpp")
devtools::install_github("ropensci/tesseract")
```

**Comment by eddelbuettel** [comment]
It is an oversight by our newest team member.  We'll fix.  Thanks for the heads up.

**Comment by nathan-russell** [comment]
@jeroenooms Apologies, I was trying to be consistent with the implementation in R's [`random.c`](https://github.com/wch/r-source/blob/trunk/src/main/random.c#L364-L365) file, but was unaware of this. Wrapping those sections with the appropriate macro guards in `sample.h`, e.g. 

```c++
#ifdef STRICT_R_HEADERS
        HL = static_cast<int*>(R_Calloc(n, int));
        q = static_cast<double*>(R_Calloc(n, double));
#else
        HL = static_cast<int*>(Calloc(n, int));
        q = static_cast<double*>(Calloc(n, double));
#endif
```

seemed to work, as I was able to compile `tesseract` successfully. Will this be sufficient to address the problem?

**Comment by jeroenooms** [comment]
Why can't you use stdlib malloc?

**Comment by eddelbuettel** [comment]
Because it is data that may go back to R.

But do a recursive grep (or my _fav_, `ag` from the silversearcher) for alloc.  We do use `Rf_allocVector` a lot.  Why not use that?   The `#ifdef` above is ... weird.  We're not force to translate the code from R base line by line.

**Comment by eddelbuettel** [comment]
My code reviews skills clearly need honing too.

**Comment by jeroenooms** [comment]
I have no idea what you're trying to do in `sample.h` but it looks like this code could benefit from some rcpp-ification. Much code in base-r is old messy C code that nobody wants to touch because it will break stuff. The nice thing about Rcpp code is that it is more elegant and maintainable.

**Comment by nathan-russell** [comment]
@jeroenooms Again, trying to follow the conventions used in the R source, but I also got the impression from [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#User_002dcontrolled-memory) that these function were preferred to their stdlib counterparts: 

> [...] providing analogues of calloc, realloc and free. If there is an error during allocation it is handled by R, so if these routines return the memory has been successfully allocated or freed. 

However, if my interpretation of that passage is incorrect and you are confident that `calloc`, `free` are sufficient then I will use those instead.

**Comment by eddelbuettel** [comment]
Hm, I could swear I had uses of `Rf_Calloc` in code of mine but I don't find it now.  

To me either _explicit_ prefix with `Rf_` offered by R works, or what we did in the sugar random functions and do it ourselves via `R::....`

**Comment by eddelbuettel** [comment]
Of course if it is really just temp storage then either `malloc()` / `free()` or some C++ containers are preferable.

**Comment by nathan-russell** [comment]
@eddelbuettel Understood; I'll make these changes.

**Comment by eddelbuettel** [comment]
@jeroenooms Just FYI this all goes back to the [earlier and useful variant in RcppArmadillo](https://github.com/RcppCore/RcppArmadillo/blob/master/inst/include/RcppArmadilloExtensions/sample.h) which also stayed "close" to how R does things to offer a replacement.
