### ISSUE TITLE
Conditional compilation

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#614]
We already build differently depending on whether the version scheme is a.b.c (ie a CRAN release) or "merely" an interim development release a.b.c.d --- the tests get turned off from R code in [tests/doRUnit.R](https://github.com/RcppCore/Rcpp/blob/master/tests/doRUnit.R#L45-L52).

Since #612 alerted us to the `R_STRICT_HEADERS` issue I have been thinking about how to do this.  We have [version information in a header](https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/config.h#L25-L33) already but I don't see how to condition on 'dev or not dev' here.

One possible solution:  use run-time code from `configure` to define a flag. That way we could _conditionally_ set what #613 (IMHO incorrectly) does _unconditionally_. 

Thoughts?

**Comment by eddelbuettel** [comment]
I misunderstood what #613 was doing at first.  That is not a bad approach either.  We can combine the two as well.

**Comment by jeroenooms** [comment]
Another approach is simply hardcode it in your `Makevars`:

    PKG_CPPFLAGS =	-I../inst/include/ -DSTRICT_R_HEADERS

That way it will only apply to Rcpp and not dependent packages.

**Comment by jeroenooms** [comment]
By the way your `makevars.win` file is redundant; windows will default to `makevars` if no `makevars.win is present and they are identical.

**Comment by jeroenooms** [comment]
I'm going to submit another PR just to see what travis says.

**Comment by eddelbuettel** [comment]
> By the way your makevars.win file is redundant

I don't care. I think it is good practice to have one present.

**Comment by eddelbuettel** [comment]
> I'm going to submit another PR just to see what travis says.

The point of having a _discussion_ is to get _consensus_ before jumping tirelessly into action.   I don't think we are there yet.  

But then you haven't listened to me for a decade so why change now ;-)

**Comment by jeroenooms** [comment]
The PR *is* the venue for discussion. It allows you to precisely see what changes are being proposed, and you can comment on them, inline or in the topic. Then we can dicuss things, and perhaps update the PR based on the discussion. Eventually you can decide to accept/reject the proposal. 

It's much more effective than an *issue* which is for reporting a problem. But you're the boss here, whatever works for you :)

**Comment by eddelbuettel** [comment]
I cannot spend an entire working day debating trivia with you, and asking you not to DOS with PRs that you know will bomb.

May I suggest a ceasefire and we all come back here in a day or two?   There is also a mailing list.

**Comment by eddelbuettel** [comment]
So it is now a week later, and on balance, I think we are fine with the STRICT_HEADERS directive.  We are mostly pretty grown up coders, and that was a one-off mistake.  They happen, but the lesson was learned.

Other views?

**Comment by jeroenooms** [comment]
You mean to leave it as is, or compile Rcpp *with* `-DSTRICT_R_HEADERS`?

**Comment by eddelbuettel** [comment]
"Leave as is" is what I meant.  I edited the comment. My bad for unclear language.

Your suggestion is/was valid in the abstract sense. Yes we could toggle that switch at the top of our headers only to flip it at the bottom.  But on the margin I feel it adds more complexities than gain.  So I would be in favour of not making a change.
