### ISSUE TITLE
Rcpp.package.skeleton() does not work when called within function

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/Rcpp#624]
E.g.

```R
skeleton <- function(name = "anRpackage") {
    Rcpp.package.skeleton(name)
}
skeleton()
```

gives

```
> skeleton <- function(name = "anRpackage") {
+     Rcpp.package.skeleton(name)
+ }
> skeleton()
Warning in package.skeleton(name = name, list = "Rcpp.fake.fun") :
  object ''Rcpp.fake.fun'' not found
Error in value[[3L]](cond) :
  error while calling `package.skeleton` : no R objects specified or available
```

I believe the issue arises because [Rcpp.package.skeleton()](https://github.com/RcppCore/Rcpp/blob/master/R/Rcpp.package.skeleton.R) tries to create a dummy environment `env` with this `Rcpp.fake.fun` object, but we never actually ensure that `package.skeleton()` is called using that dummy environment.

**Comment by eddelbuettel** [comment]
Yes, all highly obscure code.  Not sure how much effort it is to fix it. 

But I guess `RcppParallel.package.skeleton()` would like to call it?    AFAICR the other ones we have (for RcppArmadillo, RcppEigen, ... all more or have their own simplified copy.

**Comment by coatless** [comment]
If `environment` is in the call, why not create a merged environment between the `environment` and the `env`? 

Otherwise, just supply `env` as the environment to `package.skeleton`?
