### ISSUE TITLE
When the destructor is called in modules?

### ISSUE THREAD

**Issue by cruiseling** [RcppCore/Rcpp#633]
For a class **Toep** defined below
``` c++
class Toep {
    double* x;
public:
    Toep(int);
    ~Toep();
}

Toep::Toep(int n_){
    x = new double[n_];
}

Toep::~Toep(){
    cout << "destructor called" << endl;
    delete[] x;
}

RCPP_MODULE(Toep)
{
    class_<Toep>("Toep")
    .constructor<int>()
    ;
}
```

We call the constructor using
```R 
T1 <- new(Toep, 3)
```
but how can we call the destructor? I just know that by overwriting
```R 
T1 <- new(Toep, 4)
```
or remove
```
rm(T1)
```
I cannot see sentence "destructor called".
Thank you.

**Comment by eddelbuettel** [comment]
Try calling `gc()` a few times.  R, as an interpreter, reserves the right to do cleanup when it sees fit.

**Comment by cruiseling** [comment]
Thank you.

**Comment by eddelbuettel** [comment]
Did that fix it?  Did you see the message from  your destructor?  If so, please feel free to close this issue.

**Comment by cruiseling** [comment]
Yea I saw the message when I called ```gc()```. Thanks
