### ISSUE TITLE
Should Rcpp care about copy on write?

### ISSUE THREAD

**Issue by grimjoey** [RcppCore/Rcpp#639]
I'm using Rcpp to convert data, writing (from c++) to multiple matrices previously initialized in R.

data <- read_csv('data.csv')
a <- b <- c <- matrix(0, 10, 10)
sourceCpp('convert_data.cpp')
convert_data(data, a, b, c)

Rcpp will treat a, b and c as the same matrix, requiring the following change:

...
a <- matrix(0, 10, 10)
b <- matrix(0, 10, 10)
c <- matrix(0, 10, 10)
...

to make things work as intended.

[test.zip](https://github.com/RcppCore/Rcpp/files/737073/test.zip)

**Comment by eddelbuettel** [comment]
That's how R works. I see no issue here, apart from maybe pointing you to appropriate documentation.

**Comment by grimjoey** [comment]
Ok. Thanks for the instant reply.

**Comment by eddelbuettel** [comment]
On your side, look for the `clone()` helper for deep copies. All this is not obvious 'unless you know'; if you have suggestions for better documentation or examples let us know.  We tried in a few places.

**Comment by grimjoey** [comment]
It's not obvious that a, b and c refers to the same object/memory. I happened to have read about this in R-internals. Still, it took me a while to realize what was going on. I'm sure many R users are unaware of the copy on write that happens behind the scenes. I thought it might be a good idea to make Rcpp emulate this behaviour. But it's not my call.

**Comment by eddelbuettel** [comment]
Rcpp does. We get one underlying `SEXP`.  As I said, try to find some of the discussion surrounding `clone()`. [Here](http://stackoverflow.com/questions/21281911/how-can-i-protect-a-matrix-in-r-from-being-altered-by-rcpp) is one from SO.  It's been discussed numerous times.
