### ISSUE TITLE
`lower_tri` / `upper_tri` non-functional

### ISSUE THREAD

**Issue by coatless** [RcppCore/Rcpp#641]
Both the `lower_tri` and `upper_tri` sugar functions are non-functional for two reasons:

1. Neither function returns a `Matrix` as CTRP's base is `VectorBase` instead of `MatrixBase`.
2. Attempting to store the result in a `LogicalVector` leads the R process to hang.

After glancing at the source, it appears as if both of functions were DOA and should _not_ have been pushed back with Rcpp 0.8.3. Though, this remark is made in light of the fact that there are no unit tests governing these functions.

---

**The following will _hang_ your R session**

```r
Rcpp::cppFunction('
LogicalVector test(NumericMatrix x){
return upper_tri(x);
}')
x <- matrix(1:4, 4, 5)
test(x)
``` 

---

Example of desired output:

``` r
(x <- matrix(1:4, 4, 5))
#>      [,1] [,2] [,3] [,4] [,5]
#> [1,]    1    1    1    1    1
#> [2,]    2    2    2    2    2
#> [3,]    3    3    3    3    3
#> [4,]    4    4    4    4    4
lower.tri(x)
#>       [,1]  [,2]  [,3]  [,4]  [,5]
#> [1,] FALSE FALSE FALSE FALSE FALSE
#> [2,]  TRUE FALSE FALSE FALSE FALSE
#> [3,]  TRUE  TRUE FALSE FALSE FALSE
#> [4,]  TRUE  TRUE  TRUE FALSE FALSE
```

**Comment by eddelbuettel** [comment]
Ewww.  Vote for disabling these until fixed.  Doesn't even work for symmetric matrices.

**Comment by nathan-russell** [comment]
I think I have a fix; just putting together unit tests now.
