### ISSUE TITLE
Static functions in Modules

### ISSUE THREAD

**Issue by rubak** [RcppCore/Rcpp#644]
Hi,

I've recently started using Rcpp Modules to wrap a C++ library in R. I've encountered the problem that some of the member functions are static, and cannot be wrapped by the module code. This is a (well) known problem mentioned in [this post on Rcpp-devel in 2013](http://lists.r-forge.r-project.org/pipermail/rcpp-devel/2013-May/005780.html) and @romainfrancois replied

> This is not supported currently. It might be in the future when someone finds time or funding.

which is very reasonable. I wonder if it is something to mention in the Modules vignette? I got bit by it and didn't understand what was going on for a while.

With Romain's wrapper function [in his reply on Rcpp-devel](http://lists.r-forge.r-project.org/pipermail/rcpp-devel/2013-May/005782.html) you don't get association with the class. To solve this I made a workaround by letting the wrapper take a pointer to the object and then the arguments of the static member function. This way I can associate it with the class as below. Can this approach be generalised (automated) and should it be mentioned somewhere as a workaround for people looking to import a full C++ class in R with all member functions?

```c++
#include <Rcpp.h>

using namespace Rcpp;

class Foo {
  public:
    Foo() {};

    void static fun(double y){
      Rcout <<"y*x is: " << y*x << std::endl;
    }
  private:
    static const double x = 2.0;
};

void Foo_fun(Foo* bar, double y){
  Foo::fun(y);
}

RCPP_EXPOSED_CLASS(Foo);
RCPP_MODULE(mod_Foo){
class_<Foo>("Foo")
.constructor()
.method("fun", &Foo_fun)
;
}

/***R
obj = Foo$new()
obj$fun(3)
***/
```

**Comment by eddelbuettel** [comment]
Rcpp modules is dormant and not being extended.   We like what it does, and maintain in its current state, but nobody is looking at extending it as the code is somewhat complicated.

But if you want to contribute a pull request to the either the documentation (maybe as simple as adding sentence or paragraph in an appropriate place, maybe with links to the mailing list) or the code base we will certainly consider it.  But most of us work with Rcpp Attributes now on new projects.

**Comment by rubak** [comment]
OK. Thanks for the quick reply and all the good work on Rcpp. I will see if I can contribute some useful documentation once I'm a little deeper into this and understand things better.
