### ISSUE TITLE
No newlines in SPARC

### ISSUE THREAD

**Issue by Enchufa2** [RcppCore/Rcpp#647]
I got my hands on a SPARC machine and I've detected that a `std::endl` issued with `Rcpp::Rcout` is not printed. I've done the following:

1. Create a test package with `Rcpp::Rcpp.package.skeleton("test")`.
2. Modify `src/rcpp_hello_world.cpp` as follows:

```c++
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
void rcpp_hello_world() {
  Rcpp::Rcout << "hello world!" << std::endl;
  Rcpp::Rcout << "another hello world!" << std::endl;
}
```

3. Build the package with `R CMD build test`.
4. And in the SPARC station...

```bash
-bash-3.2$ R CMD INSTALL test_1.0.tar.gz 
* installing to library '/export/home/***/R/sparc-sun-solaris2.10-library/3.3'
* installing *source* package 'test' ...
** libs
/opt/csw/bin/g++-5.2 -I/opt/csw/lib/R/include -DNDEBUG  -I/opt/csw/include -I"/export/home/***/R/sparc-sun-solaris2.10-library/3.3/Rcpp/include"   -fPIC  -O2 -pipe -fno-omit-frame-pointer -mcpu=v9 -Wa,-xarch=v8plus  -c RcppExports.cpp -o RcppExports.o
/opt/csw/bin/g++-5.2 -I/opt/csw/lib/R/include -DNDEBUG  -I/opt/csw/include -I"/export/home/***/R/sparc-sun-solaris2.10-library/3.3/Rcpp/include"   -fPIC  -O2 -pipe -fno-omit-frame-pointer -mcpu=v9 -Wa,-xarch=v8plus  -c rcpp_hello_world.cpp -o rcpp_hello_world.o
/opt/csw/bin/g++-5.2 -shared -mcpu=v9 -Wa,-xarch=v8plus -L/opt/csw/lib -o test.so RcppExports.o rcpp_hello_world.o
installing to /export/home/***/R/sparc-sun-solaris2.10-library/3.3/test/libs
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (test)
-bash-3.2$ Rscript -e "test::rcpp_hello_world()"
hello world!another hello world!-bash-3.2$
```

No newlines! (I've verified that a simple C++ program using `std::cout` prints the newlines).

**Comment by kevinushey** [comment]
Here's the bits of Rcpp's stream buffer implementation that are probably relevant here: https://github.com/RcppCore/Rcpp/blob/d38a304dbc4a6c5d7e7cf4012c63ffe3a364090b/inst/include/Rcpp/iostream/Rstreambuf.h#L60-L67

Perhaps something funky is going on with how that stream buffer is receiving input? Do you see the same issue with `Rcpp::Rcerr`?

**Comment by Enchufa2** [comment]
Same issue with `Rcpp::Rcerr`, yes. However, I've just tried the following and it's working well:

```c++
void rcpp_hello_world() {
  std::ostringstream end;
  end << "\n";
  Rcpp::Rcout << "hello world!" << end.str();
  Rcpp::Rcout << "another hello world!" << end.str();
}
```

And so does this:

```c++
void rcpp_hello_world() {
  Rcpp::Rcout << "hello world!\n";
  Rcpp::Rcout << "another hello world!\n";
}
```

So maybe the bug is upstream in `std::endl`?

**Comment by Enchufa2** [comment]
Another test I made:

```c++
void rcpp_hello_world() {
  Rcpp::Rcout << "hello world!" << std::endl << "X";
  Rcpp::Rcout << "another hello world!" << std::endl << "X";
}
```

prints

```bash
-bash-3.2$ Rscript -e "test::rcpp_hello_world()"
hello world!Xanother hello world!X-bash-3.2$
```

Which means that `std::endl` is not being inserted at all. Any idea?

**Comment by kevinushey** [comment]
Unfortunately no -- since none of us have access to a SPARC machine, it's unlikely that we'll be able to help debug further.

My only suggestion would be for you to copy the `streambuf` implementation we have in:

https://github.com/RcppCore/Rcpp/blob/d38a304dbc4a6c5d7e7cf4012c63ffe3a364090b/inst/include/Rcpp/iostream/Rstreambuf.h

and try playing around with that until you get the expected output.
