### ISSUE TITLE
`saveAs` command in function `setRcppClass` does not work

### ISSUE THREAD

**Issue by cruiseling** [RcppCore/Rcpp#653]
We are trying to write a Ref class, which works as a "generator" of a C++ class exposed using modules. So we add following code in zzz.R
``` R
setRcppClass("World", 
             module = "Class_World",
             saveAs = "World_"
             )

setMethod("show", "World", function(object){
  print(object$AcfCheck())
})
```
We successfully create a Ref class called `World`, but it seems that 
``` R
saveAs = "World_"
```
is not working, since we can only create the class using 
``` R
a <- World(n)
```
while 
``` R
a <- World_(n)
```
would say
> Error: could not find function "World_"

However when we try on the demonstration module `yada`
``` R
setRcppClass("World",
             module = "yada",
             saveAs = "World_"
)
```
It works perfectly fine: class can only be generated using function `World_`. Did we miss anything or make any mistake?

**Comment by eddelbuettel** [comment]
Can you post a complete and reproducible example?

**Comment by cruiseling** [comment]
I find that my colleague just changed the NAMESPACE when he uses vignette. The problem can be solved by add  `expose` in NAMESPACE.
But I am still confused at the outcome of `setRcppClass`. Modules and class metioned below is the demonstration code included in the Rcpp package.
``` R
setRcppClass("World",
             module = "yada",
             saveAs = "World_"
)

genWorld <- function(str){
  World_$new()
  World_$set(str)
}

setMethod("show", "World", function(object) cat("World Object\n"))

setGeneric("set", def = function(a, b){})
setMethod("set", "World", function(a, b){
  a$set(b)
})
```
when running this command
``` R
a <- genWorld()
```
we will have message
> set?is not a valid field or method name for reference class refGeneratorSlot?

I understand that `World_` in function `genWorld` is not a ref class. But I have not idea what it is, and how should I properly set up this function.

**Comment by eddelbuettel** [comment]
I plan to close this as there still is not self-contained reproducible issue here, despite the request for one.

It is not entirely clear to me a) what you want or expect, b) what you get and c) exactly what you tried.  There are tutorials / guides on [asking better questions](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) which may help you.
