### ISSUE TITLE
Running XPtr finalizer on exit

### ISSUE THREAD

**Issue by jeroen** [RcppCore/Rcpp#655]
[I tried posting on the mailing list but having issues with my UCLA email...]

I am experiencing odd behavior in packages that use XPtr (V8, tesseract, xml2) which is caused by the fact that Rcpp does not run the finalizer when R quits. This can lead to corrupted connections, memory leaks, etc.

The problem is that Rcpp hardcodes the call to `R_RegisterCFinalizerEx` with [onexit = FALSE](https://github.com/RcppCore/Rcpp/blob/6f81b4684481dbd9bb554dd95e66725fc3b63a8c/inst/include/Rcpp/XPtr.h#L151) which makes that R skips over the finalizer when exiting.

Currently there is no way to fix this on the package side. Would there be a way to expose `onexit` as an option in Rcpp? Or better: make the default `TRUE` (imo you should always cleanup after yourself). But I can live with opt-in if there is a good reason for not finalizing.

**Comment by eddelbuettel** [comment]
> I tried posting on the mailing list but having issues with my UCLA email..

You may need to resubscribe from the Berkeley address (or gmail or ...). Mailman uses strict string equality.

**Comment by eddelbuettel** [comment]
The lifetime management is a delicate issue.  In some (smaller, simpler) projects I just brought a general instance of what I needed up, and then down explicitly at the end.  You may well deal with way more complicated setups here.

But the `onexit=FALSE` you identify may indeed help.  We could put the boolean into the function signature of `setDeleteFinalizer()` with a default of `FALSE`, thus allowing the override.   Can you try that at your end and see if it helps?

**Comment by jeroen** [comment]
I think ideally we would add a fourth argument to the `XPtr` template to be consistent with R's C API. 

So the [example from xml2](https://github.com/hadley/xml2/blob/7d83d9f7175af980f423ff4c637b962d21608362/inst/include/xml2_types.h#L15-L17) is now: 


```cpp
typedef Rcpp::XPtr<xmlDoc,Rcpp::PreserveStorage,xmlFreeDoc> XPtrDoc;
```

And then to enable finalizing on exit one would do:

```cpp
typedef Rcpp::XPtr<xmlDoc,Rcpp::PreserveStorage,xmlFreeDoc, true> XPtrDoc;
```
