### ISSUE TITLE
Improving doxygen documentation

### ISSUE THREAD

**Issue by coatless** [RcppCore/Rcpp#657]
# Proposal

For a large part of the Rcpp API, it is relatively undocumented with the exception of the [Environments class](https://github.com/RcppCore/Rcpp/blob/5a71cf64399cd8a1a11c27cfbe92edb3255cb5f6/inst/include/Rcpp/Environment.h#L79-L86). The objective of this issue is to fill in missing details within the code header files so that when doxygen is ran upon release a more clear picture of the different functionality offered is available on <http://dirk.eddelbuettel.com/code/rcpp/html/index.html>.  Part of the details that are missing can potentially be obtained from the documentation in the API vignette being constructed in #602. As this is a relatively large change, it will likely be done via a WIP PR.

# Scope

Each header should have:

- Meta file data
- Description of the class
- How a function uses parameters and the return value
- Potential error handling

## Sample ctor documentation

Consider the [matrix ctor with parameters](https://github.com/RcppCore/Rcpp/blob/5a71cf64399cd8a1a11c27cfbe92edb3255cb5f6/inst/include/Rcpp/vector/Matrix.h#L59-L61). The function would be marked up with the following...

```cpp
/*!
  Constructs a matrix with the specified number of rows and columns (m x n).

  @param nrows_ Number of rows in the matrix
  @param ncols Number of columns in the matrix
  @return Matrix with the specified \p nrows_ and \p ncols
  @par Example:
  @code
   Rcpp::cppFunction("Rcpp::NumericMatrix matrix_ctor(nrows, ncols){
     return Rcpp::NumericMatrix(nrows, ncols);
   }")
  @endcode
*/
Matrix( const int& nrows_, const int& ncols) : VECTOR( Dimension( nrows_, ncols ) ),
      nrows(nrows_) {}
```

Though, embedding examples may not necessarily be ideal. In the end, there may be more benefit to include code snippets using `\snippet` and referencing their location.

## Sample File Meta 

Also, while this is occurring, I would suggest moving the main description heading of the file to doxygen syntax. In the class of the matrix file, that would result in the following:

```cpp
// -*- mode: C++; c-indent-level: 4; c-basic-offset: 4; indent-tabs-mode: nil; -*-
/*!
 @file Matrix.h
 @author Dirk Eddelbuettel and Romain Francois
 @date 2010 - 2016
 @copyright  >= GNU Public License 2.0

 The implementation of the matrices in the Rcpp R/C++ interface class library.

 This file is part of Rcpp.

 Rcpp is free software: you can redistribute it and/or modify it
 under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 2 of the License, or
 (at your option) any later version.

 Rcpp is distributed in the hope that it will be useful, but
 WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Rcpp.  If not, see <http://www.gnu.org/licenses/>.
*/
```

Though, a majority of the file meta information is already tracked via git. So the benefit may not necessarily be relatively large.

### Edits:

- Switched from javadoc style to block of at least two C++ comment lines
- Switched from `//!` to `/*! */` style.

**Comment by eddelbuettel** [comment]
This may not be very efficient.  Maybe just close this, and we noodle in a Wiki over a proposed page change.  The header change under 'Sample File Meta' is not motivated and I am likely to block that.

I would also prefer a more C++-ish syntax.  I am aware of the Doxygen legacy use, I just don't like it much.

**Comment by coatless** [comment]
Closing and moving over to the Rcpp wiki is fine. Just wanted to sketch out what I briefly mentioned to see if it was of interest. 

The file meta update really doesn't need to happen as the information is tracked via `git`. The main motivation to converting the file information was to make it more "searchable" via doxygen while the headers were being updated.

I've done more with Javadocs hence the use of the `/** */` and `@tags` in the initial spec (now switched slightly.

**Comment by eddelbuettel** [comment]
I have never seen anything like this:

```
//! \file Matrix.h
//! \author Dirk Eddelbuettel and Romain Francois
//! \date 2010 - 2016
//! \copyright  >= GNU Public License 2.0
```

and I really don't like it.

**Comment by coatless** [comment]
Built off of: https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdauthor

Also used in mlpack:

https://github.com/mlpack/mlpack/blob/master/src/mlpack/core/optimizers/lbfgs/lbfgs_impl.hpp#L1-L12

**Comment by eddelbuettel** [comment]
Touche.  Can't argue with MLPACK.  

But consider headers as sacrosanct and "contracts".  You just don't *ever* change copyright info, besides updating the year and adding new contributors.   

If you really feel we need the metainfo, put it below as a new block.

**Comment by eddelbuettel** [comment]
More things we can tack on top of this are
- possibly removing my beloved Emacs line and moving to a global [editorconfig](http://editorconfig.org) file
- adding // #nocov tags
- maybe running [clang-format](https://clang.llvm.org/docs/ClangFormat.html) over the code to get the somewhat idiosyncratic formatting cleaned up
- .... your suggestion here ...

So there is lots to discuss.   But yes, doxygen would be nice.  I also see no way for it to be added to the give or take 100k lines.   Life, generally speaking, tends to be too short for that....

**Comment by coatless** [comment]
Well, let's tackle some easy things? 
----

For the `editorconfig` I'm thinking:

```
# Rcpp EditorConfig settings 

# 4-space tabs, new line at end of file, unix file endings
[*.{cpp,hpp,h,r,R}]
indent_style = space
indent_size = 4
insert_final_newline = true
end_of_file = lf

# Limit code to 80 characters
[*.{R,r}]
max_line_length = 80
```

---

For `clang-format` I'm thinking use the Linux kernel style with a modification to 4 spaces:

```
UseTab: Never
IndentWidth: 4
BreakBeforeBraces: Linux
AllowShortIfStatementsOnASingleLine: false
IndentCaseLabels: false
```

[Lots of style options...](https://clang.llvm.org/docs/ClangFormatStyleOptions.html)

**Comment by eddelbuettel** [comment]
We actually already [have an clang-format spec file](https://github.com/RcppCore/Rcpp/blob/master/.clang_format) thanks to @kevinushey -- but it may need tweaking.  Don't think we quite want to run it over all files quite yet.

The editorconfig snippet looks good.  Most is pretty standard.   Not sure I want to impose 80 chars, open to discussions.  We can start with something, I was thinking to start in some smaller repos to see.

@kevinushey The RStudio editor reads those too, correct?

**Comment by kevinushey** [comment]
RStudio doesn't yet read `.editorconfig` files but it's something we want to do in the future. (I don't think we've hooked up `clang-format` support to the IDE yet either; I've mostly just been doing that from the command line)

**Comment by eddelbuettel** [comment]
That's actually pretty much what I told @coatless over in Slack :)

**Comment by jimhester** [comment]
I was just working on a simple setup for `clang-format` on travis for one of my projects, e.g.

- [travis.yml](https://github.com/rstats-db/odbc/blob/a6bc8359e90e9300222dfbf7339a88f5e39fbe70/.travis.yml#L23-L26)
- [check_format.sh](https://github.com/rstats-db/odbc/blob/c7fc5cc982a8aabf50e64c6ba96d73cffae043d4/travis/check_format.sh#L6)
- [example failing build](https://travis-ci.org/rstats-db/odbc/jobs/223262604#L800)

You could use something similar for Rcpp, although the logic for including / excluding files would likely have to be more complicated than the above if you are not going to be running `clang-format` on everything.

**Comment by eddelbuettel** [comment]
Interesting but a little draconian at least for my current tastes.

**Comment by coatless** [comment]
Draconian? How so? The failure on bad formatting?

Color me impressed by the implementation (~ 4 lines?)

**Comment by eddelbuettel** [comment]
As you asked, I neither plan to *enforce* a coding style, not would I want to have tests fail because of white space differences.  If you need an enforced indentation style you can always switch to go :)

But yes clang-format is a nice tool.
