### ISSUE TITLE
set_encoding(CE_UTF8) won't work for ASCII characters?

### ISSUE THREAD

**Issue by yutannihilation** [RcppCore/Rcpp#659]
This may due to lack of my experience of Rcpp and/or C++, but I cannot find out the way to set encodings to Strings properly. `set_encoding(CE_UTF8)` seems to work for non-ASCII characters, but others are not.

I wonder if this is by design. Am I missing some point?

```r
Rcpp::cppFunction("
String echo(String x) {
  x.set_encoding(CE_UTF8);
  return x;
}
")
Encoding(echo("a"))
#> [1] "unknown"
Encoding(echo("あ"))
#> [1] "UTF-8"
```

```r
sessionInfo()
#> R version 3.3.3 (2017-03-06)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows >= 8 x64 (build 9200)
#> 
#> locale:
#> [1] LC_COLLATE=Japanese_Japan.932  LC_CTYPE=Japanese_Japan.932    LC_MONETARY=Japanese_Japan.932
#> [4] LC_NUMERIC=C                   LC_TIME=Japanese_Japan.932    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#> [1] tools_3.3.3  Rcpp_0.12.10
```

**Comment by eddelbuettel** [comment]
Unsure.  We have relatively little wide-char support in Rcpp.   I know little about the topic and usually just 
recoil in horror when eg Duncan Murdoch explains all the intricacies.   To top it off there is an extra layer of trouble on Windows.

**Comment by yutannihilation** [comment]
Ah, sorry, this is what R does. I didn't know this...

```r
Encoding(enc2utf8("a"))
#> [1] "unknown"
Encoding(enc2utf8("あ"))
#> [1] "UTF-8"
```

**Comment by yutannihilation** [comment]
@eddelbuettel Anyway, thanks for this quick response! I understand that wide-char on Windows always be headaches for R people...
