### ISSUE TITLE
Rcpp Package installation error

### ISSUE THREAD

**Issue by IDaisyWu** [RcppCore/Rcpp#660]
Hi All,

I faced one error when I tried to install Rcpp package on Linux Suse 11.4, my gcc version is 4.5, it seems c++ cannot compile Rcpp.so file, please give me a hand if you have any suggestion.

Error:

> install.packages("Rcpp_0.12.9.tar.gz", repos =NULL, type="source")
* installing *source* package ‘Rcpp’ ...
** package ‘Rcpp’ successfully unpacked and MD5 sums checked
** libs
g++-4.5 -I/usr/local/lib64/R/include -DNDEBUG -I../inst/include/ -I/usr/local/include    -fPIC   -c Date.cpp -o Date.o
g++-4.5 -I/usr/local/lib64/R/include -DNDEBUG -I../inst/include/ -I/usr/local/include    -fPIC   -c Module.cpp -o Module.o
g++-4.5 -I/usr/local/lib64/R/include -DNDEBUG -I../inst/include/ -I/usr/local/include    -fPIC   -c Rcpp_init.cpp -o Rcpp_init.o
g++-4.5 -I/usr/local/lib64/R/include -DNDEBUG -I../inst/include/ -I/usr/local/include    -fPIC   -c api.cpp -o api.o
g++-4.5 -I/usr/local/lib64/R/include -DNDEBUG -I../inst/include/ -I/usr/local/include    -fPIC   -c attributes.cpp -o attributes.o
g++-4.5 -I/usr/local/lib64/R/include -DNDEBUG -I../inst/include/ -I/usr/local/include    -fPIC   -c barrier.cpp -o barrier.o
g++-4.5 -L/usr/local/lib64/R/lib -o Rcpp.so Date.o Module.o Rcpp_init.o api.o attributes.o barrier.o -L/usr/local/lib64/R/lib -lR
/usr/lib64/gcc/x86_64-suse-linux/4.5/../../../../lib64/crt1.o: In function `_start':
/usr/src/packages/BUILD/glibc-2.11.3/csu/../sysdeps/x86_64/elf/start.S:109: undefined reference to `main'
collect2: ld returned 1 exit status
make: *** [Rcpp.so] Error 1
ERROR: compilation failed for package ‘Rcpp’
* removing ‘/usr/local/lib64/R/library/Rcpp’
Warning message:
In install.packages("Rcpp_0.12.9.tar.gz", repos = NULL, type = "source") :
  installation of package ‘Rcpp_0.12.9.tar.gz’ had non-zero exit status

Makefile:
CC=gcc -std=gnu99
CXX =g++-4.5

Thanks a lot.

Best Regards
Daisy

**Comment by eddelbuettel** [comment]
I don't follow SUSE version but g++-4.5 is pretty old. I do think folks on RHEL still try with g++-4.4.  So this should work -- but the `undefined reference to main'` is weird as there is no `main()` function here in the (library) package that is Rcpp.

If everthing else fails, just take an older Rcpp release from a year or two ago.   But Rcpp is rigorously tested and built on different platforms.  But with more current toolchains.

**Comment by Enchufa2** [comment]
@IDaisyWu The `-shared` flag is missing when linking.

**Comment by eddelbuettel** [comment]
Which means that R itself could have been built without shared library support -- in which case it is a local issue for SUSE / your setup.

Try and see if you have `libR.so`:

```bash
edd@max:~$ ls -l $(R RHOME)/lib/
total 2848
-rw-r--r-- 1 root root 2915920 Mar  6 13:46 libR.so
edd@max:~$ 
```

**Comment by IDaisyWu** [comment]
Thanks for your comments.
I can find this file you wanted, please let me know what else need to check, thanks.

ls -l $(R RHOME)/lib/
total 15784
-rwxr-xr-x 1 root root 11614940 Mar 22 18:41 libR.so
-rwxr-xr-x 1 root root   422944 Mar 22 18:41 libRblas.so
-rwxr-xr-x 1 root root  4095784 Mar 22 18:41 libRlapack.so

Best Regards
Daisy

**Comment by eddelbuettel** [comment]
Now do this:

```
edd@max:~$ grep shared $(R RHOME)/etc/Makeconf 
DYLIB_LDFLAGS = -shared -fopenmp# $(CFLAGS) $(CPICFLAGS)
SHLIB_CXXLDFLAGS = -shared
SHLIB_CXX1XLDFLAGS = -shared
SHLIB_FCLDFLAGS = -shared
SHLIB_LDFLAGS = -shared# $(CFLAGS) $(CPICFLAGS)
edd@max:~$
```

As was noted by Inaki, your build had no `-shared` indicating that some may be amiss at your end.

**Comment by IDaisyWu** [comment]
Big thanks!!

After added "-shared" to the missing parameters, this issue has been fixed and Rcpp can be installed successfully. Really appreciate your help.

Best Regards
Daisy

**Comment by eddelbuettel** [comment]
Nice!  Good think Inaki caught that.

You may want to check how you built R, or check with those who built it for you (SUSE?) to make sure `-shared` is set there.  Rcpp has no control over this.

**Comment by IDaisyWu** [comment]
My server is internal server with default env SUSE 11.4, and I followed one blog to install Rserver 3.2.5, its installation processed well. So I cannot define which step is to set this, if I can get more info, I will post here. Thanks again.
