### ISSUE TITLE
Rcpp link to Ceres

### ISSUE THREAD

**Issue by yonicd** [RcppCore/Rcpp#666]
Is Rcpp linked to the Ceres nonlinear equation solver? I am looking to implement Powell's dog-leg optim through R. I saw this [post](http://lists.r-forge.r-project.org/pipermail/rcpp-devel/2012-May/003755.html) in Rcpp-devel mailing list that notes both Dirk and D. Bates.

I was wondering if the issue was raised again since 2012? and if there is a solution?

Thanks

**Comment by eddelbuettel** [comment]
Linking to any C or C++ library should be straightforward.

Ceres itself is pretty old as it was around when I was a grad student. You could search for other packages which may already use it -- eg [BOOM](https://cran.r-project.org/package=Boom) (but that one is huge and not a good example).

**Comment by yonicd** [comment]
thanks for the direction. i found [minqa](https://cran.r-project.org/web/packages/minqa/minqa.pdf) to solve [bobyqa](https://www.rdocumentation.org/packages/minqa/versions/1.2.4/topics/bobyqa) optim problems.

thanks
