### ISSUE TITLE
Convert remaining `Rf_length()` instances to `Rf_xlength()` and `R_len_t` to `R_xlen_t`

### ISSUE THREAD

**Issue by coatless** [RcppCore/Rcpp#678]
While working on the exception message update, I noticed that there were a few uses of `Rf_length()` still kicking around. In total, it seems like there are about 12 files using `Rf_length()` instead of `Rf_xlength()`.  

Per a remark by @thirdwing, we should also make sure to change `R_len_t` or `int` instances to `R_xlen_t` where applicable. Searching for this term revealed only 1 file still using `R_len_t`

Search: [`Rf_length()`](https://github.com/RcppCore/Rcpp/search?p=1&q=rf_length&type=&utf8=%E2%9C%93)

Search: [`R_len_t`](https://github.com/RcppCore/Rcpp/search?p=1&q=R_len_t&type=&utf8=%E2%9C%93)

Affected Files for `Rf_length()`:

- [`inst/include/Rcpp/vector/DimNameProxy.h`](https://github.com/RcppCore/Rcpp/blob/6f81b4684481dbd9bb554dd95e66725fc3b63a8c/inst/include/Rcpp/vector/DimNameProxy.h#L37)
- [`inst/include/Rcpp/internal/Exporter.h`](https://github.com/RcppCore/Rcpp/blob/6f81b4684481dbd9bb554dd95e66725fc3b63a8c/inst/include/Rcpp/internal/Exporter.h#L46)
- [`inst/include/Rcpp/Formula.h`](https://github.com/RcppCore/Rcpp/blob/6f81b4684481dbd9bb554dd95e66725fc3b63a8c/inst/include/Rcpp/Formula.h#L52)
- [`inst/include/Rcpp/internal/GreedyVector.h`](https://github.com/RcppCore/Rcpp/blob/6f81b4684481dbd9bb554dd95e66725fc3b63a8c/inst/include/Rcpp/internal/GreedyVector.h#L32)
- [`inst/include/Rcpp/proxy/NamesProxy.h`](https://github.com/RcppCore/Rcpp/blob/6f81b4684481dbd9bb554dd95e66725fc3b63a8c/inst/include/Rcpp/proxy/NamesProxy.h#L51)
- [`inst/include/Rcpp/as.h`](https://github.com/RcppCore/Rcpp/blob/6f81b4684481dbd9bb554dd95e66725fc3b63a8c/inst/include/Rcpp/as.h#L32)
- [`inst/include/Rcpp/api/meat/is.h`](https://github.com/RcppCore/Rcpp/blob/6f81b4684481dbd9bb554dd95e66725fc3b63a8c/inst/include/Rcpp/api/meat/is.h#L28-L32)
- [`inst/include/Rcpp/hash/SelfHash.h`](https://github.com/RcppCore/Rcpp/blob/88ebc36c89789c035135ca9b35dcfb316d2bce94/inst/include/Rcpp/hash/SelfHash.h#L37)
- [`inst/include/Rcpp/exceptions.h`](https://github.com/RcppCore/Rcpp/blob/25c23699c06a5dfd8cf746ba4746e71f31106808/inst/include/Rcpp/exceptions.h#L179)
- [`inst/include/Rcpp/hash/IndexHash.h`](https://github.com/RcppCore/Rcpp/blob/88ebc36c89789c035135ca9b35dcfb316d2bce94/inst/include/Rcpp/hash/IndexHash.h#L55)
- [`inst/include/Rcpp/String.h`](https://github.com/RcppCore/Rcpp/blob/6f81b4684481dbd9bb554dd95e66725fc3b63a8c/inst/include/Rcpp/String.h#L74)
- [`src/barrier.cpp`](https://github.com/RcppCore/Rcpp/blob/8fc0eab52d9d09e990e9531810969e9393e3763d/src/barrier.cpp#L201)

Affected Files for `R_len_t`:

- [`inst/include/Rcpp/sugar/functions/strings/trimws.h`](https://github.com/RcppCore/Rcpp/blob/e81493bd988a5ee93e5a35458662dd2582de1c5d/inst/include/Rcpp/sugar/functions/strings/trimws.h#L52)

**Comment by eddelbuettel** [comment]
It's been a while but I thought in at least one instance we had a reason not to.  

If it were a "blind" search and replace, it would happen at the macro level.  I seem to recall that some data structures do not have extended indices.  Am I remembering that correctly?

@thirdwing @kevinushey Do you guys recall?

**Comment by kevinushey** [comment]
As per https://cran.r-project.org/doc/manuals/r-devel/R-ints.html#Long-vectors:

> There is now some support for long vectors. This applies to raw, logical, integer, numeric and character vectors, and lists and expression vectors. (Elements of character vectors (CHARSXPs) remain limited to 2^31 - 1 bytes.) Some considerations:

So the main caveat is character vectors, if I understand correctly. However, `Rf_xlength()` should still appropriately check whether a vector is 'long' or 'short' and do the right thing in such a case (if I understand correctly), so I think using `Rf_xlength()` with character vectors is still okay (ie, it won't blow up in your face with 'short' vectors)

**Comment by thirdwing** [comment]
`CHARSXP` should be the concern.

Besides just replacing `Rf_length` with `Rf_xlength`, we might also need to pay attention to the conversion between `R_xlen_t` and `int`. For example, 
https://github.com/RcppCore/Rcpp/blob/master/src/barrier.cpp#L201
