### ISSUE TITLE
Rewrite of Rcpp Package vignette

### ISSUE THREAD

**Issue by coatless** [RcppCore/Rcpp#681]
Within the Rcpp Package vignette, there probably should be a section specifying how to document code using the `roxygenize()` function from `roxygen2`.

Flow:

- `Rcpp::compileAttributes()`
- `tools::package_native_routine_registration_skeleton()`
- `roxygen2::roxgenize()`

**Comment by eddelbuettel** [comment]
In the sense that the workflow requires `compileAttributes()`, followed by `roxygenize()` and possibly also by something updating the newly required registration.

**Comment by coatless** [comment]
I'm thinking it also might be pertinent to include a section on adding plugins for a package. Perhaps touch on header packages?

**Comment by eddelbuettel** [comment]
Come to think about it, `roxygen2::roxygenize()` is of course _entirely optional_.  Which is qualitatively different from `compileAttributes()`.   But it is also common, so we may as well.  But no need to go overboard.

It is too bad that R still doesn't have a hook for calling such functions automatically on each build.  

We should also mention that these are calls are mandatory _if_ interfaces, or documentation, have changed.

**Comment by coatless** [comment]
Alrighty.

I'm also tempted to add to this vignette a note about code development planning... Any thoughts on this?
