### ISSUE TITLE
fix potential protect errors

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/Rcpp#685]
From https://github.com/kalibera/rprotect:

> maacheck
> 
> This tool is quite simple and only reports instances of multiple allocating arguments pattern, such as (from Rcpp code):
> 
> Rf_lang2(::Rf_install("simpleError"), Rf_mkString(str.c_str()))
> 
> This is a real error: Rf_mkString returns an unprotected newly allocated object. Rf_install may allocate and may be called after Rf_mkString, and hence may trigger garbage collection that will corrupt the object allocated by Rf_mkString.

The associated fix needs to occur here: https://github.com/RcppCore/Rcpp/blob/e81493bd988a5ee93e5a35458662dd2582de1c5d/inst/include/Rcpp/exceptions.h#L294

**Comment by eddelbuettel** [comment]
Also see #665
