### ISSUE TITLE
checking for interupts

### ISSUE THREAD

**Issue by romainfrancois** [RcppCore/Rcpp#69]
Client packages need a clean way to check for interupts, i.e. the documented way (as of Writing R extensions) would potentially violate C++ destructors, meaning leaks, and potentially objects that are forever protected from the GC ...

In a [R-devel thread](http://permalink.gmane.org/gmane.comp.lang.r.devel/27627), Simon posted this code: 

```
static void chkIntFn(void *dummy) {
  R_CheckUserInterrupt();
}

// this will call the above in a top-level context so it won't longjmp-out of your context
bool checkInterrupt() {
  return (R_ToplevelExec(chkIntFn, NULL) == FALSE);
}

// your code somewhere ...
if (checkInterrupt()) { // user interrupted ... }
```

**Comment by coatless** [comment]
This issue was addressed in PR #91 .

Please close. (Tagged #506)
