### ISSUE TITLE
Garbage collection issues

### ISSUE THREAD

**Issue by Enchufa2** [RcppCore/Rcpp#693]
Initially, I reported this in tidyverse/magrittr#146 (see the reprex there, please). But after many attempts, I'm definitely unable to take Rcpp out of the equation, and I'm starting to think that the issue has something to do with it. I cross-post here so that the Rcpp gurus can take a look.

**Comment by eddelbuettel** [comment]
I will close this as there is absolutely nothing reproducible here.

**Comment by Enchufa2** [comment]
I know, I know... but this is the best I managed to do so far. Do you know if it is possible that a reference to an environment is still visible to the `gc` but not to `ls`, and where?

**Comment by eddelbuettel** [comment]
You need to talk to the folks who deal in pipes, and standard vs non-standard evaluation.  We "just" have C++ code here that very guarantees you that an destructor is executed (but in our context maybe only once `gc()` happens).  What we do is more straightforward.  The other one is ... harder.

I would imagine you might be able to construct something without Rcpp exhibiting the same behaviour.
