### ISSUE TITLE
mysterious sourceCpp error when the parent of `env` is the empty environment

### ISSUE THREAD

**Issue by jgabry** [RcppCore/Rcpp#695]
I'm not sure if this is intended to work and doesn't or if it should indeed error out and just needs a more informative error message, but I noticed that when the `env` argument to `sourceCpp` has its _parent_ as the empty environment then I get an error and a confusing message. 

This code reproduces the error (at least on my system, sessionInfo below): 

```r
my_env <- new.env(parent = emptyenv())

Rcpp::sourceCpp(code='
  #include <Rcpp.h>

  // [[Rcpp::export]]
  int fibonacci(const int x) {
    if (x == 0) return(0);
    if (x == 1) return(1);
    return (fibonacci(x - 1)) + fibonacci(x - 2);
  }', 
  env = my_env
)
```

and the error message I get is the following:

```
Error in .sourceCpp_1_DLLInfo <- dyn.load("/private/var/folders/h6/14xy_35x4wd2tz542dn0qhtc0000gn/T/RtmpTSOHag/sourceCpp-x86_64-apple-darwin15.6.0-0.12.10/sourcecpp_a19057b7ed5e/sourceCpp_2.so") : 
  could not find function "<-"
```

Here's the result of `sessionInfo()`:

```
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.0 tools_3.4.0    Rcpp_0.12.10  
```

**Comment by eddelbuettel** [comment]
Is this mocked-up version of an actual issue?  Is there a need to stick this into particular environments?

I do not doubt that the error comes up. I am just not sure yet whether I should care.

**Comment by jgabry** [comment]
I only noticed this because in the **rstan** package we have a function `expose_stan_functions` that uses `sourceCpp` internally and allows the user to pass an`env` argument to `sourceCpp`. It works great but one of our users showed me that it fails when using an environment like the `my_env` I used above. I don't actually think getting it working with an environment like `my_env` is particularly important, so if it's nontrivial to fix I wouldn't bother. I wasn't sure if this would require much effort to change or if anyone was aware of it so I opened the issue, but I don't mind if you close and ignore it.

**Comment by kevinushey** [comment]
My guess is that the error occurs here:

https://github.com/RcppCore/Rcpp/blob/4e0f79c8651e17438ae88ef52b37139ff1135fc9/R/Attributes.R#L186-L188

In particular, because we're calling `source(..., local = env)`, and so we end up evaluating R code in an environment when not even the base R functions are available.

In short: I think it's a real bug, but not a serious one. You should ensure that the environments passed in have `globalenv()` as the parent.

**Comment by jjallaire** [comment]
So you could create the new environment like this:

new.env(parent = globalenv())

Or more conservatively:

new.env(parent = baseenv())

**Comment by jgabry** [comment]
On Thu, May 18, 2017 at 12:11 AM Kevin Ushey <notifications@github.com>
wrote:

> In particular, because we're calling source(..., local = env), and so we
> end up evaluating R code in an environment when not even the base R
> functions are available.
>

Ah, I see. That would explain the bit in the error message about not
finding the function "<-".

In short: I think it's a real bug, but not a serious one. You should ensure
> that the environments passed in have globalenv() as the parent
>

Makes sense, thanks. And yeah I've never had any trouble when the parent is
globalenv().

**Comment by eddelbuettel** [comment]
So shall we / can we close here?
