### ISSUE TITLE
Piping code into cppFunction()?

### ISSUE THREAD

**Issue by richgoldberg** [RcppCore/Rcpp#696]
It seems that piping text containing a C++ function into cppFunction() doesn't lead to the function becoming part of the environment.   (`code` is the first argument fo cppFunction() so I thought that it should work.)  

Here's an example that didn't work for me:

```
'int fibonacci(const int x) {
    if (x == 0) return(0); 
    if (x == 1) return(1);
    return (fibonacci(x - 1)) + fibonacci(x - 2);
    }' %>% cppFunction()
```
In contrast, this worked perfectly for me:
```
cppFunction(
    'int fibonacci(const int x) {
        if (x == 0) return(0); 
        if (x == 1) return(1);
        return (fibonacci(x - 1)) + fibonacci(x - 2);
    }')
```
(I am using R version 3.4.0 on 64 bit Windows 7 with version 0.12.10 of Rcpp.)

**Comment by eddelbuettel** [comment]
Funny how using something the way it is actually documented works.   News at 11::00pm.

**Comment by richgoldberg** [comment]
Dr. Eddelbuettel,

I love the Rcpp package so don’t want to be offensive but is there a reason you wouldn’t want the Rcpp functions to be compatible with magrittr/dplyr?  Your reply to my Issue seems like you dismiss the issue that some people may want to create their C++ code programmatically and would like to pipe the result into cppFunction().

I would understand if you said that the difficulty in making it compatible with the magritter pipe wasn’t worth the effort or if I was doing something wrong in how I was passing the arguments but your sarcastic response really seemed uncalled for.  Yes, I can get the function to work which is all I personally need.  However, your function doesn’t’ behave as expected in the case I identified so it seemed like a legitimate  Issue to flag.

Rich

**Comment by eddelbuettel** [comment]
You seem to imply that *we* owe you a function for piping into `cppFunction()`.  We don't.

But this is Open Source. You can go crazy and write such a function, or even a package.

Or heck, go crazy and fork Rcpp itself into tidyRcpp or whatnot.   

But your imagination went overboard when you convinced yourself that we ever suggested to use `cppFunction()` this way.  We have not.  We (and I say this as acting maintainer) are not all that likely to ever do that either.   Allow me to repeat that _a package working as documented_ is not in fact a bug.

**Comment by kevinushey** [comment]
More to the point -- if something works without `magrittr`'s pipe, but does not work with `magrittr`'s pipe, then that is surely a bug in `magrittr`, and the bug should be filed on their side.

**Comment by eddelbuettel** [comment]
And for closure, quoting @spacedman from a conversation in the StackOverflow chatroom:

>  its only because Rcpp has side effects that it fails :) You can still do `fib = code %>% cppFunction()`
>  or `code %>% cppFunction(env=.GlobalEnv)` will work for that user

Still all user error and runaway imagination...
