### ISSUE TITLE
Using CMake in Rcpp

### ISSUE THREAD

**Issue by Weiming-Hu** [RcppCore/Rcpp#699]
I have a c++ project that is using CMake to generate Makefile and compile. I would like to transfer this project to an R package using Rcpp. What would be the most straightforward solution to this?

My main concern is how to use CMake when installing this package in `R CMD`.

Thank you.

**Comment by eddelbuettel** [comment]
Wrong repository / project:  You need to ask _the core R developers_ to extend `R CMD INSTALL ...` etc.  

Rcpp simply calls the standard functions R provides to compile, load, link, ... and all of those are currently based on `make`.

**Comment by thirdwing** [comment]
@Weiming-Hu I am afraid we don't get enough information to help you.

As far as I know, you can try to put the cmake stuff in the `configure` script.

**Comment by eddelbuettel** [comment]
Right.  And you're essentially on your own.  With that, I'd recommend against. Over 10600 CRAN use a system that works.

So maybe you can try to wrap `make` around the `cmake` calls you need.  But again, not an Rcpp question but maybe one for the r-package-devel list.

**Comment by jjallaire** [comment]
We've had success in the past just using CMake external commands to invoke
R CMD build.

**Comment by Weiming-Hu** [comment]
Thank you, and sorry for posting at the wrong place. Will check the `configure` solution and the r-package-devel list.

**Comment by Weiming-Hu** [comment]
@jjallaire That sounds like a good idea. Do you have any existing codes as examples? Thank you

**Comment by jjallaire** [comment]
Here's the code we used to use. I can't warrant that it's fully correct or
fits with your use case so your milage may vary!

https://github.com/rstudio/rstudio/blob/c13ddfd7af4ac8acee2e77ab7489c2d8fdb29f36/src/cpp/r/R/packages/CMakeLists.txt

**Comment by Weiming-Hu** [comment]
I'm really sorry to bother you again, but I think I need some help.

First, I don't know to ask questions about `CMake` in `r-package-devel list` as mentioned by @eddelbuettel. How can I find it?

Second, I attach my question [here](https://stackoverflow.com/questions/44835770/use-another-compiler-when-install-r-packages-with-rcpp-and-cmake?noredirect=1#comment76652157_44835770). Really appreciate it if anyone could help.

Again, thank you guys.
