### ISSUE TITLE
Automatic registration of attributes when non RCpp C/Cpp code is present

### ISSUE THREAD

**Issue by vspinu** [RcppCore/Rcpp#700]
Within the same package I have plain C and Rcpp code. With the new changes (probably #694) `compileAttributes` generates registration code that takes into account only entries in Rcpp code. 

My question is what is correct/recommended way to go about it? Can `compileAttributes` run `tools::package_native_routine_registration_skeleton` (or whatever else it does) on all c/cpp files within a package?

**Comment by vspinu** [comment]
Actually the problem is specific to  R < 3.4.0. On 3.4.0 it seems to be doing the right thing.

**Comment by jjallaire** [comment]
Yes, compileAttributes does run
tools::package_native_routine_registration_skeleton when running under R
3.4, so you should indeed try to develop under R 3.4 (or if that's not
practical just write your own init function and then compileAttributes
won't try to generate any registration code).

**Comment by vspinu** [comment]
Yeh. I switched to 3.4.0. Thanks.

**Comment by eddelbuettel** [comment]
And for completeness, before R 3.4.0 it worked just fine to call `compiledAttributes()` by hand (or a script, my case) followed by a call for package registration (easy to script, I blogged about that three times).
