### ISSUE TITLE
clang complains about "no newline at end of file" in Rcpp/utils/tinyformat.h

### ISSUE THREAD

**Issue by Enchufa2** [RcppCore/Rcpp#701]
I see this when I compile my package with clang. Also [here](https://www.stats.ox.ac.uk/pub/bdr/memtests/clang-UBSAN/Rcpp/build_vignettes.log), among other things:

```
/data/gannet/ripley/R/packages/tests-clang-SAN/Rcpp.Rcheck/Rcpp/include/Rcpp/utils/tinyformat.h:1046:32: warning: no newline at end of file [-Wnewline-eof]
#endif // TINYFORMAT_H_INCLUDED
```

If the comment is required, a newline should appease clang.

**Comment by eddelbuettel** [comment]
Clang version?  Exact invocation command?

**Comment by Enchufa2** [comment]
Sorry, in my system, clang 3.9.1, default version shipped with Fedora 25:

```
ccache clang++ -Qunused-arguments -I/usr/include/R -DNDEBUG -DBOOST_NO_LONG_LONG -I/usr/local/include -I"/home/xxx/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include" -I"/home/xxx/R/x86_64-redhat-linux-gnu-library/3.3/BH/include"   -fpic  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic  -pedantic -Wno-long-long -c policy.cpp -o policy.o
In file included from RcppExports.cpp:4:
In file included from /home/xxx/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include/Rcpp.h:27:
In file included from /home/xxx/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include/RcppCommon.h:70:
/home/xxx/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include/Rcpp/utils/tinyformat.h:1046:32: warning: no newline at end of file [-Wnewline-eof]
#endif // TINYFORMAT_H_INCLUDED
```

The link points to CRAN's clang-UBSAN checks.

**Comment by eddelbuettel** [comment]
I cannot reproduce it, though I can generate pages of other warnings :-/

clang++-3.8 and clang++-3.9 on Ubuntu.

**Comment by eddelbuettel** [comment]
NOW I get it, using `-Wno-conversion -pedantic'.

**Comment by Enchufa2** [comment]
It seems that this is a warning in some versions of C++ only: see comments [here](https://github.com/llvm-mirror/clang/blob/master/test/Lexer/newline-eof.c) and [here](https://github.com/llvm-mirror/clang/blob/master/test/Lexer/newline-eof-c%2B%2B98-compat.cpp).

**Comment by coatless** [comment]
What is an appropriate battery of compile flags to run against?

**Comment by eddelbuettel** [comment]
Well @krlmlr helped to get rid of a few of the (easier) conversion warnings so now `-Wall -Wextra -pedantic` works, now we have some harder ones (in the: need to make sure we don't accidentally pick a wrong variable conversions) left.

My (current) default (for `g++`) is  

```
CXXFLAGS += -O3 -Wall -pipe -Wno-unused -pedantic -Wextra -Wno-deprecated-declarations
```

but I few more commented-out lines in there.  For `clang++` I used

```
CC=ccache clang-3.9 -Qunused-arguments 
CXX=ccache clang++-3.9 -Qunused-arguments  
CXXFLAGS=-Wall -O3 -Wno-conversion -pedantic
```
