### ISSUE TITLE
Name attribute in RcppExports no longer works

### ISSUE THREAD

**Issue by mbertolacci** [RcppCore/Rcpp#702]
I updated Rcpp to version 0.12.11 from 0.12.10 and suddenly exported functions with name="" attributes no longer work.

This appears to be due to the CallEntries in RcppExport.cpp using the incorrect name to derive a function pointer.

Example exported code:
```
// [[Rcpp::export(name=".stick_breaking_mixture")]]
Rcpp::List stickBreakingMixture(
    unsigned int nLoop,
    unsigned int nWarmUp,
    //...
```

RcppExport wrapper:
```
// stickBreakingMixture
Rcpp::List stickBreakingMixture(unsigned int nLoop, unsigned int nWarmUp, ...);
RcppExport SEXP BayesSpec_stickBreakingMixture(SEXP nLoopSEXP, SEXP nWarmUpSEXP, ...) {
```

Corresponding CallEntries entry:
```
    {"BayesSpec_.stick_breaking_mixture", (DL_FUNC) &BayesSpec_.stick_breaking_mixture, 9},
```
I think this function pointer should be `&BayesSpec_stickBreakingMixture`

Note that I have checked and this is not due simply to the use of '.' in the exported name.

**Comment by eddelbuettel** [comment]
Possible. @jjallaire Any quick idea which regexps to tune?

In the meantime consider the fallback of calling `tools::package_native_routine_registration_skeleton(".")` to create your own `src/init.c`.

**Comment by jjallaire** [comment]
Bummed that this one snuck through. At least anyone who runs into this will get a local compilation error (rather than "silently" incorrect code) so has a chance to fix before submitting to CRAN. Just submitted a PR with the fix.

**Comment by eddelbuettel** [comment]
I could as a convenience roll up 0.12.11.1 for the [rcpp drat repo](https://rcppcore.github.io/drat/).
