### ISSUE TITLE
make Rcpp_0.12.11 compile and installed on haiku-os

### ISSUE THREAD

**Issue by armgong** [RcppCore/Rcpp#707]
Today try install Rcpp on haiku-os , compile failed. then I modify two line in src/api.cpp line make Rcpp compile and install. 
line 36    and line 275
~~~c
     defined(__HAIKU__)
~~~
and RcppEigen also need modify install/include/unsupported/Eigen/src/SparseExtra/MatrixMaketIterator.h
line 196 
 ~~~c
     defined(__HAIKU__)
~~~
can we add this mod to the source ? 

thanks

**Comment by eddelbuettel** [comment]
Please prepare a proper pull request.
