### ISSUE TITLE
Vignette on including C++ libraries with Rcpp

### ISSUE THREAD

**Issue by coatless** [RcppCore/Rcpp#711]
**Proposal:**

Presently, the vignettes target the "Seamless R to C++" transference. However, using Rcpp to embed a C++ library within _R_ is not covered outside of establishing `as<>()` and `wrap()`. The objective of this vignette would be to introduce more advance concepts of embedding R libraries:

- header-only packages (c.f. [`sitmo`](https://github.com/coatless/sitmo) and [`rgen`](https://github.com/coatless/rgen)) 
- including source (c.f. [`RcppMLPACK1`](https://github.com/rcppmlpack/rcppmlpack1))
- `autoconf` demo (c.f. [`RcppArmadillo`](https://github.com/rcppcore/RcppArmadillo))

Potentially, I think this could be submitted as an R Journal paper...

**Comment by eddelbuettel** [comment]
![From Slack](https://user-images.githubusercontent.com/673121/27086308-755079b6-5017-11e7-8cf8-d5a7b6647ec1.png)

**Comment by coatless** [comment]
![](http://i1.kym-cdn.com/photos/images/newsfeed/000/242/631/382.gif)

**Comment by eddelbuettel** [comment]
Sorry, but I *had* to delete that.

That is not what I was saying.  If I establishing chronological order.  Our private conversation, including my statement quoted above, predates your issue ticket here.  Frankly, I still don't understand why you filed that ticket but then again there are many things in this world I don't understand.

**Comment by coatless** [comment]
Generally, whenever we talk about I normally end up creating tickets immediately afterward and you provide additional feedback within the ticket (c.f 657 , 681 , 604). The end part of the quoted screenshot also is a big reason for this ticket:

> "Not sure when I get to that."

In particular, the ticket acts as reminder of the conservation since the slack conversations have started to disappear a bit more quickly due to the 10k history limit. 

I apologize if this was released when it shouldn't be. Regarding the response, I thought the post of the screenshot was a reaffirmation of the initial proposal and, hence, the "It's happening!" meme. 

Speaking to the topic at hand, I already have a few resources regarding Rcpp & C++ libraries written:

- [Understanding Makevars](https://stackoverflow.com/a/43599233/1345455)
- [Requiring OpenMP availability for use in an Rcpp package](https://stackoverflow.com/questions/42280628/requiring-openmp-availability-for-use-in-an-rcpp-package/42281495#42281495)
- Header only packages that have a post sitting in queue at TCP: [`sitmo`](https://github.com/coatless/sitmo) and [`rgen`](https://github.com/coatless/rgen)
- Windows binary builds following rwinlibs process

**Comment by eddelbuettel** [comment]
It's a big topic.  It's need a discussion of `autoconf` versus the shell-script hacks by Jeroen. Possibly `cmake` too though I don't use it.  We have dozens of usage cases, from embedding small libraries (cf RcppCNPy, RcppFadeeva) to header-only (many) to header-only in C++11 (RcppTOML), C++14 (RcppGeiger), ... to a whole slew of library detection and various headaches of working with them.

I am not sure this will get done in any reasonably time frame though.
