### ISSUE TITLE
Protection problems with C++ interfaces

### ISSUE THREAD

**Issue by krlmlr** [RcppCore/Rcpp#712]
My package "bindrcpp" provides a C++ interface via `// [[Rcpp::interfaces(cpp)]]`. I was able to track down spurious segmentation faults (in dplyr, https://github.com/tidyverse/dplyr/issues/2811) to (what I think is) a protection error in the auto-generated C++ wrappers for these interfaces.

The commit https://github.com/krlmlr/bindrcpp/commit/6d1e2bde24fd8a26a3911923cd2e6cd0a1a29180 shows both the problem and the solution: In general, `wrap()` will perform allocation of R objects, and without extra shielding these can be garbage collected even before the wrapped function is called, because the latter has all `SEXP` in its signature.

After applying this particular commit, I'm not seeing test failures anymore, which before occurred after a few iterations. Happy to submit a PR.

CC @lionel-.

**Comment by eddelbuettel** [comment]
It's been a while but we did revise that aspect once or twice already.

Could you provide a reproducible example we could call before and after ?  With and without `gctorture()` ?

**Comment by krlmlr** [comment]
Thanks. That commit is the reprex, `gctorture2()` is called inside the tests:

```bash
hub clone krlmlr/bindrcpp
cd bindrcpp
git checkout 6d1e2bd^ # omit ^ to see fixed behavior
R -q -e 'devtools::test(reporter = c("summary", "stop"))'
```

**Comment by eddelbuettel** [comment]
I am sorry but I don't use `hub`, or `devtools`.

**Comment by krlmlr** [comment]
Give me a minute to translate that for you. I seriously recommend checking out `hub`, though: https://github.com/github/hub

**Comment by eddelbuettel** [comment]
Yes, I read about it. So far exiting command-line and magit are good enough for me.

**Comment by lionel-** [comment]
who needs hub when there's magit ;)

**Comment by krlmlr** [comment]
Thanks for the pointers, will check out magit.

Now, for the reprex:

1. Install bindrcpp from https://github.com/krlmlr/bindrcpp/tree/a7759861e780fa84cf022f31809af3744599abea
2. Run the script below, it should stop very soon
3. Now install the fixed version from https://github.com/krlmlr/bindrcpp/tree/6d1e2bde24fd8a26a3911923cd2e6cd0a1a29180
4. Run the script below, it should run until the end

If you install from a clone with `R CMD INSTALL .`, you need to remove `src/*.o` before switching to a different version.

```r
library(bindrcpp)
gctorture2(29)

for (i in 1:1000) {

print(i)

env_cb <- bindrcpp:::cpp_create_environment(letters, "toupper")
env <- env_cb$env
env2_cb <- bindrcpp:::cpp_create_environment(LETTERS, "tolower", parent = env)
env2 <- env2_cb$env
stopifnot(identical(get("a", env2), "A"))
stopifnot(identical(get("x", env2), "X"))
stopifnot(identical(env2$a, NULL))
stopifnot(identical(env2$x, NULL))
stopifnot(identical(env2$B, "b"))
stopifnot(identical(env2$Y, "y"))
stopifnot(identical(length(ls(env2)), length(letters)))
#expect_error(env2$B <- "B", "read-only")
env2$a <- "a"
stopifnot(identical(get("a", env2), "a"))

}
```

**Comment by jjallaire** [comment]
PR is here: https://github.com/RcppCore/Rcpp/pull/713
