### ISSUE TITLE
Regarding stingsAsFactors and generating dataframe

### ISSUE THREAD

**Issue by elderRex** [RcppCore/Rcpp#714]
So I've been trying to read in arbitrary data and store them in a dataframe.
```c++
DataFrame df = DataFrame::create(_["stringsAsFactors"] = false);
...
    for (int __c = 0; __c < num_columns; __c++)
    {
      if (!selected_cols.empty() && selected_cols.find(__c) == selected_cols.end())
      {
        continue;
      }
      my_push_back(df,rvec[__c].ivec,descr->name());
      rvec[__c].clear();
    }
```
where my_push_back is just a push back pushing different vectors based on type.

The problem I'm encountering is:
1. the _["stringsAsFactors"] = false does not turnoff the stringsAsFactors option in the resulting dataframe.
based on this [chain](http://lists.r-forge.r-project.org/pipermail/rcpp-devel/2014-July/007844.html)
Tho it was in 2014 so not sure if new solution has popped up over the years...

by far, the solution I found is in R instead of Rcpp
```R
x = sapply(df,is.factor)
df[x] = lapply(df[x],as.character)
```

2. the push_back seems to be doing [full copies](https://stackoverflow.com/questions/8631197/constructing-a-data-frame-in-rcpp)
which is causing double mem usage... The problem I have is that I cannot use the create api since the number of columns is arbitrary. been meaning to use the assign api tho cannot find an example for that.

However, I do know the number of columns, columns' types and #rows before hand. Been looking for a way to construct a arbitrary length of arguments but couldn't quite figure out how to convert to input compatible with DataFrame::create()

Probably looking at the wrong place, would be great if some pointers can be provided...

would really appreciate the help!

**Comment by eddelbuettel** [comment]
What is your question?  It works if you set `stringsAsFactors` as a parameter:

```r
R> Rcpp::cppFunction("DataFrame foo(CharacterVector x, bool flag) { return DataFrame::create(Named(\"x\")=x, Named(\"stringsAsFactors\")=flag); }")
R> a1 <- foo(LETTERS[1:4], FALSE)
R> a1
  x
1 A
2 B
3 C
4 D
R> class(a1[,1])
[1] "character"
R> a2 <- foo(LETTERS[1:4], TRUE)
R> a2
  x
1 A
2 B
3 C
4 D
R> class(a2[,1])
[1] "factor"
R> 
```

**Comment by elderRex** [comment]
Thank you so much for the update!

so is not working when:
1. the dataframe is declared as DataFrame df = DataFrame::create(_["stringsAsFactors"] = false);
and other columns are being push_back afterwards

for now I'm using R to switch the factor to chr..

tho I managed to create wrapper for DF based on my needs so second problem is solved...

**Comment by eddelbuettel** [comment]
That `push_back` use is the wrong idiom.  

You can also deploy the _global_ `options()` value for `stringsAsFactor` before calling your Rcpp function.

**Comment by elderRex** [comment]
@eddelbuettel Thank you so much for the help! : D
So, I guess the only way to deal with that without using R is to use the DataFrame::create() api provided then : D
'cause push_back and insert seems not affecting columns being added after declaration...
