### ISSUE TITLE
Rcpp::compileAttributes() started hallucinating a symbol

### ISSUE THREAD

**Issue by flying-sheep** [RcppCore/Rcpp#718]
I don’t know which change to my system caused this, but with the newest gcc (7.1.1) and Rcpp (0.12.11), a new block appeared in my `RcppExports.cpp`.

note that apart from the new `CallEntries` and `R_init_destiny`, which i assume are new Rcpp features, there’s also a new function `cp` that i didn’t add to my C++ code.

```cpp
RcppExport SEXP cp(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"destiny_censoring_impl", (DL_FUNC) &destiny_censoring_impl, 7},
    {"destiny_predict_censoring_impl", (DL_FUNC) &destiny_predict_censoring_impl, 6},
    {"destiny_icor2_no_censor", (DL_FUNC) &destiny_icor2_no_censor, 6},
    {"cp",                             (DL_FUNC) &cp,                             1},
    {NULL, NULL, 0}
};

RcppExport void R_init_destiny(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
```

What i did add is this, because using `palette` in `.onLoad` caused a bug for a user (since `palette` needlessly uses `.Call.graphics`, and therefore opens a plot device on package load)

```r
set_palette <- function(v) {
	cp <- getFromNamespace('C_palette', 'grDevices')
	.Call(cp, v)
}
```

As proof that no source file defines “cp”:

```console
$ rg -A1 Rcpp::export
src/censoring.cpp
81 // [[Rcpp::export]]
82 Eigen::SparseMatrix<double> censoring_impl(
--
149 // [[Rcpp::export]]
150 NumericMatrix predict_censoring_impl(

src/no_censoring.cpp
36 // [[Rcpp::export]]
37 Eigen::SparseMatrix<double> icor2_no_censor(
```

I’m using `// [[Rcpp::plugins(cpp11)]]` and `// [[Rcpp::depends(RcppEigen)]]`

You can find the project [here](https://github.com/Bioconductor-mirror/destiny/tree/master). I’m sorry: I’m far too busy to create a minimal working example, but the issue appeared without my interference anyway 😉

---

as a workaround, i tried this, but it says the function is not available in the package.

```cpp
// [[Rcpp::export]]
SEXP set_palette(SEXP pal) {
	typedef SEXP palette(SEXP);

	static palette *fun = NULL;
	if (fun == NULL)
		fun = (palette*)R_GetCCallable("grDevices", "palette");
	return fun(pal);
}
```

/edit: and this alternative workaround segfaults (“permission denied”):

```cpp
// [[Rcpp::export]]
SEXP set_palette(SEXP pal) {
	typedef SEXP palette(SEXP);
	
	static palette *fun = NULL;
	if (fun == NULL) {
		Rcpp::Environment grDevices("package:grDevices");
		Rcpp::List record = grDevices["C_palette"];
		SEXP addr = record[1]; //"address"
		Rcout << "dereferencing addr " << addr << '\n';
		fun = (palette*)R_ExternalPtrAddr(addr);
	}
	Rcout << "calling fun " << fun << '\n';
	return fun(pal);
}
```

**Comment by eddelbuettel** [comment]
See NEWS for R 3.4.0: 

>     * Package tools has a new function
>      package_native_routine_registration_skeleton() to assist adding
>      native-symbol registration to a package.  See its help and SS5.4.1
>      of 'Writing R Extensions' for how to use it.  (At the time it was
>      added it successfully automated adding registration to over 90%
>      of CRAN packages which lacked it.  Many of the failures were
>      newly-detected bugs in the packages, e.g. 50 packages called
>      entry points with varying numbers of arguments and 65 packages
>      called entry points not in the package.)

Dynamically loaded functions now need to be registered.  Your package calls `.Call(cp, v)`, this requires a registration for `cp`.   Rcpp creates you one.  No more, no less.

Now, what if anything is the actual problem?

**Comment by flying-sheep** [comment]
“cp” is defined here:

```r
set_palette <- function(v) {
	cp <- getFromNamespace('C_palette', 'grDevices')
	.Call(cp, v)
}
```

the problems are that

1. “cp” isn’t the name of the c function i call. cp is the variable that stores the `CallRoutine` object that references the `.Call` function `C_palette`
2. Rcpp creates the declaration `RcppExport SEXP cp(SEXP);`. there is no definition for that function anywhere

**Comment by flying-sheep** [comment]
but if you just use the builtin skeleton, the problem is in upstream R, not C.

thank you! i could work around it now using `do.call`:

```r
set_palette <- function(v) {
	cp <- getFromNamespace('C_palette', 'grDevices')
	do.call(.Call, list(cp, v))  # needed to get around static analysis
}
```

**Comment by jjallaire** [comment]
This code is being generated by `tools::package_native_routine_registration_skeleton()` which we call from within compileAttributes. We can't fix this but you can definitely report a bug to R core and it may be fixable there. I'd do 2 things:

1) Call `tools::package_native_routine_registration_skeleton()` and include the generated code in your project (with an edit to fix this issue).

2) Report a bug against `tools::package_native_routine_registration_skeleton()`

**Comment by flying-sheep** [comment]
thanks! see above, i found a way to circumvent the issue.

**Comment by eddelbuettel** [comment]
Yes, should have mentioned this right away.  If and when you already have registered symbols, Rcpp will leave them alone.  That allows you to deal with this one-off via edits, as @jjallaire suggested.

Going forward, this may well addressed as an R issue if you report it.  One could imagine a tag to not consider a particular `.Call()` instance, or some other means of avoiding the false positive.

**Comment by flying-sheep** [comment]
Jup, here’s the bug: https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17294
