### ISSUE TITLE
Datetime not behaving as expected with new DatetimeVector

### ISSUE THREAD

**Issue by quantitative-technologies** [RcppCore/Rcpp#724]
I am using the new `DatetimeVector`, and I am having the following issue since `Datetime` does not (AFAIK) have a "tzone" attribute. Basically, for a single `Datetime` extracted from a `DatetimeVector`, the accessors like `getHours()` are calculated for UTC, rather than the timezone of the `DatetimeVector` as I was expecting. 

This is demonstrated in the following example.

    // use new Datetime vector API
    #define RCPP_NEW_DATE_DATETIME_VECTORS 1

    #include <Rcpp.h>
    using namespace Rcpp;

    // [[Rcpp::export]]
    int DatetimeIssue(DatetimeVector v, std::string tz) {
      DatetimeVector y(v);
      y.attr("tzone") = tz;
  
      Datetime first(y[0]);
      return first.getHours();
    }

    /*** R
    NowTime <- as.POSIXct("2017-03-21 13:35:23","%Y-%m-%d %H:%M:%S", tz="America/Chicago")
    format(NowTime, tz="UTC")
    DatetimeIssue(NowTime, "America/New_York")
    */

Sourcing it gives:

    > Rcpp::sourceCpp('src/issue.cpp')

    > NowTime <- as.POSIXct("2017-03-21 13:35:23","%Y-%m-%d %H:%M:%S", tz="America/Chicago")

    > format(NowTime, tz="UTC")
    [1] "2017-03-21 18:35:23"

    > DatetimeIssue(NowTime, "America/New_York")
    [1] 18

So the `DatetimeVector` `attr` has been ignored. 

A side-issue is that the C++ code changes the timezone of the input, which was intuitively unexpected looking at the code:

    > NowTime
    [1] "2017-03-21 14:35:23 EDT"

**Comment by eddelbuettel** [comment]
Well, `getHours()` does return the `struct tm` component.  That will always be UTC.  

Adding TZ functionality to Rcpp seems ... wrong when we have libraries for it.  Can you for example look at [RcppCCTZ](https://github.com/eddelbuettel/rcppcctz) ?

**Comment by quantitative-technologies** [comment]
UTC was actually fine for what I was working on, since the series used the GMT timezone. But I will look into RcppCCTZ if this becomes an issue again.

**Comment by eddelbuettel** [comment]
Ok, thanks for reporting back.  I think we can close this as keeping it at UTC is the right thing for Rcpp.
