### ISSUE TITLE
MSVC toolchain support - mingw and MSVC compatibility

### ISSUE THREAD

**Issue by SylvainCorlay** [RcppCore/Rcpp#728]
The documentation specifies

*Less experienced R users on the Windows platform frequently ask about using Rcpp with the Visual Studio toolchain.  That is simply not possible as R is built with the gcc compiler. Different compilers have different linking conventions.*

Mingw-style `.a` import libraries are in a standard format that MSVC understands. For C++ functions (mangled names) it is not the case.

Are there any mangled symbols in core R that Rcpp would be using that prevent it to be built with visual studio?

**Comment by eddelbuettel** [comment]
"It's complicated."

Basically everything from R on down is built and tested with just onecompiler on Windows:  `g++-4.9.3` (from the  Rtools meta-package from R / CRAN).  

You can try getting things to work with MSVC, but you are on your own.  Others have tried, more so in the past than recently.   You guys have good chops, so maybe you will make it work.   But to be frank I think the odds are kinda up against you.  The one saving grace is that the interface from/to R is plain C.

**Comment by SylvainCorlay** [comment]
This is something we do without any issue with `Julia`, which also built with gcc, as well as with e.g. openblas (which can only be built with gcc on windows). I was basically wondering if there was a deep reason for this to not be possible with R.

**Comment by eddelbuettel** [comment]
Compiler interop can get in the way fast.  You may get Rcpp loaded into R. But then 1070+ packages on CRAN alone rely on Rcpp to get into R.  Again, those all interface the same C-language `SEXP .Call(....zero to more SEXP args here)` interface so _in theory_ it could all work.

In practice nobody has made it work.  I would assume that Microsoft itself, now vested in R, has tried. I am simply not aware of anyone who got this work.   What you quoted above is a warning to newbs.   If you guys try hard, maybe you can make it work.   But I don't think too many people would give you good odds. 

Too bad you're not over in Brussels today.  You would have enjoyed [this](https://riotworkshop.github.io) and the people there.

**Comment by eddelbuettel** [comment]
Closing for general scope creep.  The MSFT toolchain issues are addressed in the Rcpp FAQ.
