### ISSUE TITLE
Compile error on Linux RHEL, Microsoft Open R 3.4.0

### ISSUE THREAD

**Issue by ppau1** [RcppCore/Rcpp#734]
## Short description
I installed Microsoft Open R in my system and now I can't install `Rcpp`. Before I had the Anaconda installation and `Rcpp` worked fine, but had to remove it due to other issues.

## Error message
This is what I ran and the error message I got:
```r
> install.packages('Rcpp')
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2388k  100 2388k    0     0  9888k      0 --:--:-- --:--:-- --:--:-- 9911k
X11 connection rejected because of wrong authentication.
* installing *source* package ‘Rcpp’ ...
** package ‘Rcpp’ successfully unpacked and MD5 sums checked
** libs
g++ -I/usr/lib64/microsoft-r/3.4/lib64/R/include -DNDEBUG -I../inst/include/ -DU_STATIC_IMPLEMENTATION    -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c Date.cpp -o Date.o
cc1plus: error: unrecognized command line option "-mbmi-mavx"
make: *** [Date.o] Error 1
ERROR: compilation failed for package ‘Rcpp’
* removing ‘/usr/lib64/microsoft-r/3.4/lib64/R/library/Rcpp’

The downloaded source packages are in
	‘/tmp/RtmpGUnf0C/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("Rcpp") :
  installation of package ‘Rcpp’ had non-zero exit status
```

## System Info

```r
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Amazon Linux Bare Metal release 2012.03

Matrix products: default
BLAS: /usr/lib64/microsoft-r/3.4/lib64/R/lib/libRblas.so
LAPACK: /usr/lib64/microsoft-r/3.4/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] RevoUtilsMath_10.0.0

loaded via a namespace (and not attached):
[1] compiler_3.4.0   RevoUtils_10.0.4 tools_3.4.0
```

### Linux version:
```bash
% cat /etc/redhat-release
Red Hat Enterprise Linux Server release 5.3 (Tikanga)
```

**Comment by eddelbuettel** [comment]
> `cc1plus: error: unrecognized command line option "-mbmi-mavx"`

That looks like your R setup on RedHat needs help.  This does _not_ come from us.  

Do you know where to get help for RedHat?

**Comment by ppau1** [comment]
I see. I'm new to RedHat so I don't really know where to get help. 
It seems that there is a problem with the compiler, doesn't it?

Thanks for your quick answer!

**Comment by eddelbuettel** [comment]
Kinda.  More like the R package itself which "remembers" how it was built.

There is a mailing list r-sig-fedora.  Maybe ask there?

Debian/Ubuntu tend to just work.  You could always dive into a container or vm for one of those.  Or build R yourself.

**Comment by varun992** [comment]
Hi,

Were you able to find a resolution? I'm facing the same issue with R-3.4.1

**Comment by mzhao577** [comment]
Hi varun992 ,  Did you finally fix your issue?   I has the similar issue, which has been bothering me for while.  When I was trying to install the package data.table, it gives me error messages like this:  
* installing *source* package â€˜highlightâ€™ ...
** libs
g++ -I/usr/lib64/RRO-3.2.0/R-3.2.0/lib64/R/include -DNDEBUG  -I/usr/local/include   -I. -fpic  -g -O2  -c ASBeautifier.cpp -o ASBeautifier.o
make: g++: Command not found
make: *** [ASBeautifier.o] Error 127
ERROR: compilation failed for package â€˜highlightâ€™
* removing â€˜/home/gzhao/R/x86_64-unknown-linux-gnu-library/3.2/highlightâ€™
* installing *source* package â€˜Rcppâ€™ ...
** libs

I am using the RedHat Linux from mapr.   I found there is no g++ at my Linux at all.   Can anybody help with this?

My R version is:  
Revolution R Open 3.2.0
Using CRAN snapshot taken on 2015-05-01
The enhanced R distribution from Revolution Analytics
Visit mran.revolutionanalytics.com/open for information
about additional features and technical support options.

$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 7.4 (Maipo)
Release:        7.4
Codename:       Maipo

Thanks in advance.
Max

**Comment by eddelbuettel** [comment]
`make: g++: Command not found` 

I would start by making sure you have compiler.

**Comment by mzhao577** [comment]
The above error message is for the current time when I install the package geosphere.   It was disrupted when it comes to install Rcpp.

**Comment by mzhao577** [comment]
The above error message is for the current time when I install the package geosphere.   It was disrupted when it comes to install Rcpp.

**Comment by mzhao577** [comment]
@eddelbuettel ,   Is there any other way of install Pcpp without going to redhat for help?   There is no g++ at my Redhat, but there is gcc.

**Comment by eddelbuettel** [comment]
I am not sure how familiar you are with _basic_ adminstration of a Linux computer but these tend to have _packages_ (just like CRAN has Rcpp) which you _install_.  

Here is a Google query:  https://www.google.com/search?q=how+do+I+install+g%2B%2B+on+redhat&rlz=1C1CHBF_enUS797US798&oq=how+do+I+install+g%2B%2B+on+redhat&aqs=chrome..69i57j69i60j0j69i64.7142j0j1&sourceid=chrome&ie=UTF-8

This question are _inappropriate_ here as you fail to demonstrate a failure _in Rcpp_ as opposed to your use of it.

FWIW I use this stuff daily on Debian/Ubuntu as well as CentOS.   As does CRAN.  And a fair number of users.
