### ISSUE TITLE
double precision version for the numericmatrix

### ISSUE THREAD

**Issue by yonghuajiang** [RcppCore/Rcpp#739]
The current numericmatrix stores data in Real. It will be great if we can also have a double precision version.

**Comment by eddelbuettel** [comment]
Please look more closely at the R headers to figure out what `REAL`.  Or trust me and this code:

```r
> object.size(rep(1.23, 100)) 
840 bytes 
> object.size(rep(1.23, 1)) 
48 bytes
>
```

There is a 40 bytes overhead, and then 8 bytes for 1 double, and 800 for hundred of them.

See the R Internals and/or R Language manuals.
