### ISSUE TITLE
RcppAttributes problem with multiline comments

### ISSUE THREAD

**Issue by jeroen** [RcppCore/Rcpp#740]
Using `Rcpp 0.12.12`: if a `cpp` file contains a multiline comment line where the closing `*/` is at the end of the line, then the `compileAttributes()` parser seems to miss the `*/` and hence ignores all code subsequent code.

For example for this cpp file and entry is generated in `RcppExports.cpp`:

```cpp
#define R_NO_REMAP
#include <Rcpp.h>

/* This works fine
 */

// [[Rcpp::export]]
int foo(){
  return 0;
}
```

However when the comment is like this, Rcpp does not generate the proper export for `int foo()`.

```cpp
#define R_NO_REMAP
#include <Rcpp.h>

/* does not work */

// [[Rcpp::export]]
int foo(){
  return 0;
}
```

**Comment by eddelbuettel** [comment]
The parser is home-grown.  Feel like taking a stab?

Also, I presume a more C++-ish

```c++
#define R_NO_REMAP
#include <Rcpp.h>

// bet this does

// [[Rcpp::export]]
int foo(){
  return 0;
}
```

is not an issue either?   So maybe we just document that _Friends don't let friends use C comments_  ;-)

**Comment by jimhester** [comment]
This is a dup of https://github.com/RcppCore/Rcpp/issues/161 btw
