### ISSUE TITLE
Warn about some things on crazy OSs?

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#743]
More of a 'thinking out aloud' ticket prompted by two recent issues:

### Windoze and UNC paths

This very recent [SO question for reticulate](https://stackoverflow.com/questions/45876471/installing-keras-for-r-reticulate-package-fails-with-rcpp-h-no-such-file-or) really fails because the UNC path prevents Rcpp from finding its header.  Once set correctly, everything works.

So on Windoze should we warn if we see a UNC path?

### macOS and OpenMP

@coatless and I are going nuts over trying to have RcppArmadillo (!!) even build (!!) on macOS.  I know 
next to nothing about the platform but there seems to an organized cluster-fsck going on with `-fopenmp` being set in `SHLIB_OPENMP_CFLAGS` (just like on Linux, where everything _just works_) but of course no OpenMP library being present _unless user does something_.   So even `rhub` builds fail...

Is there something we can / should do in terms of offering preemptive help or warnings?

**Comment by kevinushey** [comment]
As far as R on macOS goes, because I don't want to bother using R's own custom toolchain here (the default toolchain on macOS is fine and if I cared about OpenMP I'd just run on a Linux box) I have this in my `~/.R/Makevars`:

```
# Disable OpenMP
SHLIB_OPENMP_CFLAGS   =
SHLIB_OPENMP_CXXFLAGS =
SHLIB_OPENMP_FCFLAGS  =
SHLIB_OPENMP_FFLAGS   =
MAIN_LDFLAGS          =
```

Note that the real solution here is for the _user_ to install R's LLVM toolchain and activate it during compilation as discussed here: https://cran.r-project.org/bin/macosx/tools/

I'm not sure what Rcpp / RcppArmadillo can do here, other than amend the configure script to detect and enable / disable OpenMP as needed (which sounds like a frustrating waste of time that will just piss us off and inevitably the CRAN maintainers off when we get it wrong somehow)

**Comment by eddelbuettel** [comment]
> frustrating waste of time that will just piss us off 

So you guys in Seattle now have a mind reading machine?

**Comment by eddelbuettel** [comment]
In all seriousness, I tried to be clever and [parsed the compiler flags for `-fopenmp`](https://github.com/RcppCore/RcppArmadillo/blob/master/configure.ac#L84-L88).  

Hilarity ensued as macOS has it set, but of cause can't back it up.   

Trying to be conditional in `src/Makevars` and you get yelled at 'non-portable Makefile'.  My solution: give every kid a nickel and tell them to get a real computer:

![image](https://user-images.githubusercontent.com/673121/29726857-0eb2ed1a-8997-11e7-8b8f-8f8f307b6304.png)

**Comment by eddelbuettel** [comment]
So we're still fighting this. AFAIK @coatless already has some `autoconf` code to automate (to `src/Makevars`) what you did locally.  Question is if we really want to release that in the wild.

But what about Rcpp and failure to find `Rcpp.h` ... when used on stooopid paths (and you know where)?

**Comment by kevinushey** [comment]
I don't think there's much Rcpp can do to help here, either. Effectively, the _package being installed_ would need some kind of configure script, or some other install hook, that checked the library paths for a UNC path, and I don't think there's a clean way of accomplishing that.

Unless there's some way for Rcpp to register an install hook to be run during some dependent package's compilation? (AFAIK there isn't such a thing)

On the RStudio side, we generally recommend remapping UNC / network paths to a local drive as well, just to help minimize these kinds of issues.

**Comment by eddelbuettel** [comment]
Ack.  Some of code testing for abnormal situations (ie on Windows yet no Rtools) is only internal to the IDE, right?   Would be nice to be callable in case of trouble ...

**Comment by eddelbuettel** [comment]
RcppArmadillo got fixed.  UNC paths are, well, a "known issue".
