### ISSUE TITLE
After compileAttributes() C++ functions are not visible from R

### ISSUE THREAD

**Issue by twolodzko** [RcppCore/Rcpp#744]
I wanted to build from the scratch mu package on new machine, so I downloaded the source code and run the `devtools::document()` that internally calls `Rcpp::compileAttributes()`, them builded it and reloaded R. This worked with no errors or warnings and it should give me a working package as it worked properly before, however it doesn't and it returns the errors:

```
Error in foo(params) : object '_myPkg_cpp_foo' not found
```

What has changed, is that now `Rcpp::compileAttributes()` is registering `_myPkg_cpp_foo`, while previously it was registering `myPkg_cpp_foo`.  I *guess* that useDynLib (in my case defined in roxygen2 documentation) doesn't recognize the `_myPkg`. I tried changing the
```
#' @useDynLib myPkg, .registration = TRUE
```
to
```
#' @useDynLib _myPkg, .registration = TRUE
```
but I get error saying that `_` is invalid to in the name.

If this is by design, then it does not seem to be documented in `?compileAttributes`.

**Comment by eddelbuettel** [comment]
Briefly:
- Leave devtools out of this til you understand what is going on.
- During transitions you _may_ need to run `compileAttributes()` twice.
- If in doubt, download a package from CRAN.  There are 1131 of them using Rcpp. Look what they do.

**Comment by eddelbuettel** [comment]
Just in case it was this repo you had been working on, it is fine:

```
/tmp> git clone https://github.com/twolodzko/misster.git
Cloning into 'misster'...
remote: Counting objects: 197, done.
Checking connectivity... done.
/tmp> cd misster/
/tmp/misster> compAttr.r 
/tmp/misster> compAttr.r 
/tmp/misster> cd ..
/tmp> build.r misster/
* checking for file ‘misster/DESCRIPTION’ ... OK
* preparing ‘misster’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building ‘misster_0.1.0.tar.gz’

/tmp> R_LIBS_USER=/tmp/RcppDepends/lib R CMD check misster_0.1.0.tar.gz 
* using log directory ‘/tmp/misster.Rcheck’
* using R version 3.4.1 (2017-06-30)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘misster/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘misster’ version ‘0.1.0’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘misster’ can be installed ... [17s/15s] OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking compiled code ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 OK
* checking PDF version of manual ... OK
* DONE

Status: OK

/tmp> 
```

If it is a different one, let us know which so that we can help.

**Comment by twolodzko** [comment]
@eddelbuettel I am talking about a package that already worked and is on CRAN (https://github.com/twolodzko/extraDistr). I just re-installed it on Linux machine and it works (it didn't on Windows). I already tested different approaches (e.g. deleting the RcppExports.R/.cpp files, deleting the NAMESPACE files, so that they will be automatically re-created etc.), I deleted everything (including devtools, Rcpp) and re-builded from the scratch etc. I'll check few more things and call back.

**Comment by eddelbuettel** [comment]
Give me a moment and I can hopefully take a look now that I know what the package is.

**Comment by eddelbuettel** [comment]
I cloned your repo, built a tarball and checked the tarball.  It all works.  

Ubuntu 16.10. Current packages of just about everything.

**Comment by eddelbuettel** [comment]
And it also works if I run `compileAttributes()` but you need to run it twice.

**Comment by coatless** [comment]
Yup. Everything compiles nicely...

**Comment by eddelbuettel** [comment]
So with that it appears to be a 'problem between keyboard and chair' as you rely on devtools which runs `compileAttributes()` only once.  Run it another time by hand and you should be good.

**Comment by twolodzko** [comment]
@eddelbuettel may I ask why do I need to run it twice? I'd be happy to learn more and possibly suggest some changes in devtools if this is the issue.

**Comment by eddelbuettel** [comment]
It is related to how the parser works.  See the Rcpp repo and issue tickets between release 0.12.10 and 0.12.11, and then again 0.12.11 and 0.12.12.

And please note that I didn't suggest to file an issue with devtools, I simply asked you to run `compileAttributes()` twice.

**Comment by twolodzko** [comment]
@eddelbuettel running it twice on the Windows machine worked. Still, I'd argue that this *is* a problem and will probably be coming back if you need to run it twice in some cases. When I previously build my package everything worked fine (soon after the feature was implemented in Rcpp, earlier I registered the routines by hand), now it doesn't. Either the `compileAttributes()` should be altered (e.g. it should run twice if there is no other option), or at least there should be warning in the docs saying "run it twice" (IMHO, this does not sound like a good solution). Anyway, the devtools team should be informed on that since they will probably be getting issues on it.
