### ISSUE TITLE
(Draft) New FAQ entry on running compileAttributes() twice

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#745]
R 3.4.0 and later strongly encourage registering dynamically loadable symbols.  In the stronger form (where `.registration=TRUE` is added to the `useDynLib()` statement in `NAMESPACE`), only registered symbols can be loaded.   This is fully support by Rcpp 0.12.12, and the required code is added to `src/RcppExports.cpp`.  

However, the transition from the previously generated file `src/RcppExports.cpp` to the new one _may_ require running  `compileAttributes()` twice.  When `Rcpp::compileAttributes()` is called, it also calls `tools::package_native_routine_registration_skeleton()`, which crawls through usages of `.Call()` in the `R/` source files of the package to figure out what routines need to be registered. If an older `RcppExports.R` file is discovered, its out-of-date symbol names get picked up, and registration rules for those symbols get written as well. This will register more symbols for the package than are actually defined, leading to an error. This point has been discussed at some length both in the [GitHub issue tickes](https://github.com/RcppCore/Rcpp/issues), on StackOverflow and elsewhere.   

So if you autogenerated file fails, and a `symbols not found` error is reported by the linker, consider running `compileAttributes()` twice.  Deleting `R/RcppExports.R` and `src/RcppExports.cpp` may also work.   We are not aware of any other persistent errors.

**Comment by eddelbuettel** [comment]
Above is a first draft.  Please feel free to copy/paste/edit.

**Comment by coatless** [comment]
Why not instead just tell them to delete `src/RcppExports.cpp`? Also, I think it might be important to mention that the previously required file `src/init.c` is automatically generated in `src/RcppExports.cpp`

**Comment by eddelbuettel** [comment]
a) Done
b) There never was a required file `src/init.c`.  You could have called `src/thomasTheTankEngine.c`.  It needed to contain the registration.

**Comment by coatless** [comment]
a.) Conceptually, deleting and then compiling is easier than running it twice as you can easily see the generation. This makes sense at least in my head. 

b.) True, but the general advice that went out when R 3.4.0 was being released was to call the registration file `src/init.c`. The more folks that can be ported over... The better. One way to ensure this is a node to the prior _de facto_ means for establishing native registration.

**Comment by eddelbuettel** [comment]
a) Please demonstrate that it works.
b) I don't think so. I happened to use `src/init.c` in my examples, other people used other filenames.

**Comment by coatless** [comment]
a.) Oddly enough, on the `extraDist` repo, it does indeed need to be run twice. So, I retract this suggestion.
b.) `src/init.c` is in the official _R_ documentation [Section 5.4.2: Example: converting a package to use registration](https://cran.r-project.org/doc/manuals/R-exts.html#Converting-a-package-to-use-registration) (conventionally).

**Comment by kevinushey** [comment]
I decided to dive in here, and I think the underlying issue is the presence of out-of-date RcppExports.R and RcppExports.cpp files when `Rcpp::compileAttributes()` is called.

When `Rcpp::compileAttributes()` is called, we also call `tools::package_native_routine_registration_skeleton()`, which crawls through usages of `.Call()` in the R source files of the package, to figure out what routines need to be registered. The problem is, if an older `RcppExports.R` is discovered, the _out-of-date_ symbol names get picked up, and registration rules for those symbols get written as well.

In my testing, explicitly deleting the old `R/RcppExports.R` and `src/RcppExports.cpp` files before calling `Rcpp::compileAttributes()` avoided the issue entirely. We might want to just do that explicitly ourselves.

**Comment by eddelbuettel** [comment]
Why didn't you tell us two releases ago :)

**Comment by kevinushey** [comment]
😄 

I was more optimistic that more users wouldn't bump into this, or that the issue would transiently resolve itself as users called `Rcpp::compileAttributes()` multiple times while building their package. It looks like there are still a number of users who don't regularly re-compile their attributes, though!

**Comment by eddelbuettel** [comment]
It's because folks like you give them tooling.  So RStudio automates this, they don't know how devtools gets involved and they never ever call `compileAttributes()` by hand.  Sad.

Which makes it tricky for us.  I kinda hate the forced delete.  Hmpf.

**Comment by eddelbuettel** [comment]
I edited the draft once above once more.

**Comment by coatless** [comment]
> Which will create more symbols than are actually defined.  

This will create more symbols in the package than are actually defined.
