### ISSUE TITLE
New vignette Rcpp-introduction

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#746]
There is a new introduction to Rcpp by @eddelbuettel and @coatless in a [PeerJ preprint](https://peerj.com/manuscripts/20068/); it is also on its to a TAS paper in the same collection.

I suggest to add it to Rcpp.  To make room, I will rename the existing vignette [Rcpp-introduction.Rnw](https://github.com/RcppCore/Rcpp/blob/master/vignettes/Rcpp-introduction.Rnw) to `Rcpp-introdcution-2011.Rnw`, and add the new one as `Rcpp-introduction.Rnw`.  

That way links to the old one persist, and get the new one.  I will add cross-references (just how the old one already mentions it is a JSS paper preprint, it will then also point to the new intro).  

As a minor technicality, I have also derived a somewhat spiffier look by working of the PNAS style in the [rticles package](https://github.com/rstudio/rticles).  The LaTeX style is a single file now.  We may work on making this a Rmarkdown template in due course as well.

**Comment by eddelbuettel** [comment]
Looks like there is an R bug and I cannot rename the old one as a 'new-name plus extension' -- we get a (spurious) warning about R file in `inst/doc/ `

So maybe the old one will become `Rcpp-2011-intro.Rnw` instead.

**Comment by eddelbuettel** [comment]
Confirmed by glancing at R's tools package and file `R/build.R`; has to do with how `PkgVignettes()` chops the ending off.  So a common filename root is not good -- maybe I just renamed it to `rcpp-jss-paper.Rnw` or `rcpp-jss-v40i08.Rnw` or `rcpp-jss-2011.Rnw`.

**Comment by coatless** [comment]
c.f. #506 

The ideal title would be: "Rcpp JSS Paper"

**Comment by eddelbuettel** [comment]
The referenced SO question has long been deleted, and the OP who asked it is a certified, err, "trouble maker" short of clues.  So if there ever was something to disregard, it was this.  Did you really make inferences from N=1 ?

As for actual intent, "Rcpp JSS Paper" does not convey that said paper is six years old, and was in need of the replacement you and I now provided.   So I think rcpp-jss-2011 dominates.

Also note that the discussion of the four comments is tangential and peripheral to the actual issue, a reflection of an actual R behaviour, and addresses only the _filename_ and not the vignette title.

**Comment by coatless** [comment]
@eddelbuettel Sadly, no. A few students that first time through looked at the "introduction" vignette and asked me a few questions. Plus, I think a few other _Rcpp_ beginners had questions at the time that used `cxxfunction()`, which is emphasized in the vignette. That was a motivating factor for writing -- albeit later -- [_To Rcpp Attributes and Beyond From inline_](http://thecoatlessprofessor.com/programming/rcpp/to-rcpp-attributes-and-beyond-from-inline/) as I wanted a post that I could link to that exposed the flaws of _inline_.

👍 for `rcpp-jss-2011.Rnw`.
