### ISSUE TITLE
Rcpp prohibits simultaneous R and C++ unit testing using RStudio and testthat

### ISSUE THREAD

**Issue by zer0hedge** [RcppCore/Rcpp#749]
As described [here ](https://stackoverflow.com/q/46022275/5674719) Rcpp prohibits simultaneous R and C++ unit testing using RStudio and testthat. 

Below are the steps to reproduce the issue. You don't actually need RStudio - plain R is enough. 

I believe the issue is due to the line `R_useDynamicSymbols(dll, FALSE);` generated by `Rcpp::compileAttributes()` in the file `RcppExports.cpp`.  

Steps to reproduce:

1. Start R

1. Create new package:

       devtools::create("~/mypackage")

2. Add support for testthat:

       devtools::use_testthat("~/mypackage")

4. Add C++ unit testing infrastructure:

       testthat::use_catch("~/mypackage")

5. Add 'LinkingTo: testthat' in DESCRIPTION. 
6. Add  'useDynLib(mypackage)' in  NAMESPACE.
7. Build package

       devtools::build("~/mypackage")

8. Test package:

       devtools::test("~/mypackage")

The following output is produced:

        C++: .
        DONE ===========================================================

I.e. everything works perfectly  -  sample C++ test passed.

9. Add 'LinkingTo: Rcpp' , 'Imports: Rcpp (>= 0.11.0)'  in DESCRIPTION 

10. Add line `// [[Rcpp::export]]` above `int twoPlusTwo() {` in the file `src/test-example.cpp` (it forces compileAttribute() do something) 

11.  Run `Rcpp::compileAttributes()`:

         Rcpp::compileAttributes("~/mypackage", verbose=TRUE)

12. Test package again:  

        devtools::test("~/mypackage")

The following output is produced:

         Failed -------------------------------------------------------------------------
         1. Error: Catch unit tests pass (@test-cpp.R#3) --------------------------------
         failed to locate routine 'run_testthat_tests' in package 'mypackage'
         1: expect_cpp_tests_pass("mypackage") at /home/zer0hedge/mypackage/tests/testthat/test-cpp.R:3
         2: get_routine(package, "run_testthat_tests")
         3: stop("failed to locate routine '", routine, "' in package '", package, "'", call. = FALSE)

**Comment by eddelbuettel** [comment]
"Prohibits" ? Please.

I already told you several times in the SO question you raised that you 
- have unmet and unrealistic expectations and 
- that this is if any anything a testthat issue

Files with proper `// [[Rcpp::export]]` tags are processed by Rcpp as expected.

**Comment by eddelbuettel** [comment]
This may also be related to #745 in which case it is a devtools issue.

**Comment by eddelbuettel** [comment]
I replicated this.  You are trying to use a feature from a package that is not ours, and it fails.

Not our fault.  It is probably fixable, but you really need to look into how testthat does this, and preferably work out a solution.

**Comment by eddelbuettel** [comment]
A fairly simple if hackish fix was to
- include the entire `testthat.h` file in `src/test-runner.cpp`
- add the export tag there
- adjust one include path for `vendor/` by prepending `testthat/`

There is still something wrong with `R CMD check mypackage*tar.gz` but you can run it by hand:

```r
> library(mypackage)
> mypackage::run_testthat_tests()
===============================================================================
All tests passed (1 assertion in 1 test case)

[1] TRUE
>
```

As I personally use neither devtools nor testthat I'll leave it at that.   As I said before, it is _their_ integration with Rcpp which probably needs an update.

**Comment by zer0hedge** [comment]
Thanks for the link and workaround.  I agree that it is the testthat team  who should (not must yet!)  register their C function. But while you are going in the right direction, you are ahead of the pack it seems.  It is NOT yet prohibited to call unregistered functions.

**Comment by eddelbuettel** [comment]
You are free to adjust your packages to your needs as you see fit.  If our functions don't suit you, don't use them.  And if everything else fails, use the money-back guarantee ;-)

**Comment by eddelbuettel** [comment]
And don't me wrong:  I like Catch too.  But someone (you?) needs to sit down and write better integration.

**Comment by zer0hedge** [comment]
`run_testthat_tests` comes into existense in `mypackage` as a "C"  function and then is called within testthat by `getNativeSymbolInfo`.  Rcpp "monopilizes" registration of native routines for 'mypackage', so I can't register `run_testthat_test` myself.  Is there a way to "ask" Rcpp to register C function?

**Comment by kevinushey** [comment]
See https://github.com/hadley/testthat/pull/569. The issue is known and we
plan to fix it in testthat.

**Comment by kevinushey** [comment]
(and the issue is specifically with testthat not understanding the new
native routine registration system, not with Rcpp)

**Comment by zer0hedge** [comment]
Great - I'll be waiting then!

**Comment by eddelbuettel** [comment]
> as a "C" function

You misunderstand, again.  R only has a C interface.  Every function is a C function.  We too use `extern "C"` but it is a bit more hidden.

**Comment by zer0hedge** [comment]
I'm an old guy and is not afraid of making mistakes :-) I didn't actually want to disturb you with the basic things, sorry for that.  The issue is being resolved by testthat team as you originally suggested, so I deleted my question from stackexchange - the issue is really closed.
