### ISSUE TITLE
Rcpp::depends with R CMD check --as-cran

### ISSUE THREAD

**Issue by mlysy** [RcppCore/Rcpp#759]
I have a package which compiles source code on-the-fly with `sourceCpp`.  The source code also has additional build dependencies specified with `Rcpp::depends`.  I have no issues using the package, nor passing `R CMD check`.  However, `R CMD check --as-cran` generates an error.  I've tried this on two platforms (OSX and linux, `sessionInfo` below).  Please find attached a minimal example: [RcppDependsAsCran_1.0.tar.gz](https://github.com/RcppCore/Rcpp/files/1346825/RcppDependsAsCran_1.0.tar.gz).  The relevant part of the error output is:

```
* checking examples ... ERROR
Running examples in ‘RcppDependsAsCran-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: test_depends_cran
> ### Title: Test on-the-fly compiling of external dependencies within R CMD
> ###   check.
> ### Aliases: test_depends_cran
> 
> ### ** Examples
> 
> n <- 3
> p <- 2
> X <- matrix(rnorm(n*p), n,p)
> 
> # pre-compiled code
> tX <- test_depends_cran(X)
> identical(tX, t(X))
[1] TRUE
> 
> # now compile same code on-the-fly
> test_code <- "
+ #include <Rcpp.h>
+ #include <RcppEigen.h>
+ using namespace Rcpp;
+ using namespace Eigen;
+ //[[Rcpp::depends(RcppEigen)]]
+ 
+ //[[Rcpp::export]]
+ Eigen::MatrixXd test_depends_cran2(Eigen::MatrixXd X) {
+   MatrixXd Y(X.cols(), X.rows());
+   Y = X.transpose();
+   return Y;
+ }
+ "
> Rcpp::sourceCpp(code = test_code, verbose = TRUE)

Generated extern "C" functions 
--------------------------------------------------------


#include <Rcpp.h>
// test_depends_cran2
Eigen::MatrixXd test_depends_cran2(Eigen::MatrixXd X);
RcppExport SEXP sourceCpp_1_test_depends_cran2(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(test_depends_cran2(X));
    return rcpp_result_gen;
END_RCPP
}

Generated R functions 
-------------------------------------------------------

`.sourceCpp_1_DLLInfo` <- dyn.load('/private/var/folders/8r/t8wdg7cj2mq1fx4h1546v1y40000gn/T/RtmpcDmLK2/sourceCpp-x86_64-apple-darwin15.6.0-0.12.13/sourcecpp_29e62a168620/sourceCpp_2.so')

test_depends_cran2 <- Rcpp:::sourceCppFunction(function(X) {}, FALSE, `.sourceCpp_1_DLLInfo`, 'sourceCpp_1_test_depends_cran2')

rm(`.sourceCpp_1_DLLInfo`)

Building shared library
--------------------------------------------------------

DIR: /private/var/folders/8r/t8wdg7cj2mq1fx4h1546v1y40000gn/T/RtmpcDmLK2/sourceCpp-x86_64-apple-darwin15.6.0-0.12.13/sourcecpp_29e62a168620

Error: Package 'RcppEigen' referenced from Rcpp::depends in source file file29e66086ae32.cpp is not available.
Execution halted
```

Here is the `sessionInfo` for OSX:

```
R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.1 tools_3.4.1   
```

Here is the `sessionInfo` for linux:

```
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8    
 [5] LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8   
 [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.1
```

**Comment by coatless** [comment]
I can't replicate this on macOS High Sierra. The `DESCRIPTION` file contains the necessary `RcppEigen` statement in import as well.

<details>
 <summary>R CMD check --as-cran macOS log</summary>

```bash
Updating RcppDependsAsCran documentation
Loading RcppDependsAsCran
Setting env vars --------------------------------------------------------------
CFLAGS  : -Wall -pedantic
CXXFLAGS: -Wall -pedantic
Building RcppDependsAsCran ----------------------------------------------------
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD build  \
  '/tmp/RcppDependsAsCran' --no-resave-data --no-manual 

* checking for file ‘/tmp/RcppDependsAsCran/DESCRIPTION’ ... OK
* preparing ‘RcppDependsAsCran’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building ‘RcppDependsAsCran_1.0.tar.gz’

Setting env vars --------------------------------------------------------------
_R_CHECK_CRAN_INCOMING_ : FALSE
_R_CHECK_FORCE_SUGGESTS_: FALSE
Checking RcppDependsAsCran ----------------------------------------------------
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD check  \
  '/var/folders/c8/fd3_gkc90657vwn34_bm76fc0000gn/T//RtmpGv7EOF/RcppDependsAsCran_1.0.tar.gz'  \
  --as-cran --timings --no-manual 

* using log directory ‘/tmp/RcppDependsAsCran.Rcheck’
* using R version 3.4.1 (2017-06-30)
* using platform: x86_64-apple-darwin15.6.0 (64-bit)
* using session charset: UTF-8
* using options ‘--no-manual --as-cran’
* checking for file ‘RcppDependsAsCran/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘RcppDependsAsCran’ version ‘1.0’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘RcppDependsAsCran’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking compiled code ... OK
* checking examples ... OK
* DONE
Status: OK

R CMD check results
0 errors | 0 warnings | 0 notes

R CMD check succeeded
```
</details>

**Comment by eddelbuettel** [comment]
Works for me too, mostly, with `R-devel CMD check --as-cran`.  It does die in the example though.  Which is (and pardon my bluntness) silly.  We all love `\examples{}`.  We all used them for tests.  Until circa ten years ago real unit test support arrived with RUnit, and later testthat.  

You will see numerous examples of testing even _complete embedded packages_ in our various Rcpp* packages.  So what you want to do can be done, and is being done.  You are insisting on one particular way which is never claimed to be supported.  So if it breaks, _you_ get to keep the pieces.

I am closing this.  Feel to discuss on rcpp-devel how/why you want this.  Maybe someone did or does something similar.  Else I recommend RUnit, others may prefer testthat.

**Comment by mlysy** [comment]
Thanks for your help.  After some further digging around I'd like to document this properly in case anyone else encounters the same issue.

**Problem:** Packages in the `LinkingTo` field referenced by `Rcpp::depends` in code compiled on-the-fly by `sourceCpp` throws an error with `R CMD check --as-cran`.  This happens both in `\examples{}` *and* in unit tests.  I have tried this on various platforms, including [rocker/r-devel/](https://hub.docker.com/r/rocker/r-devel/).  The problem only affects code compiled on-the-fly (i.e., not in `src`), and disappears without the `--as-cran` flag.

**Solution:** The problem seems to be in the first line of `.validatePackages` in `Rcpp/R/attributes.R`:
```
unavailable <- depends[!depends %in% .packages(all.available=TRUE)]
```
For some reason, the `.packages` call with `--as-cran` does not find the packages in `LinkingTo` if they're not specified anywhere else in the `DESCRIPTION`.  Seems that `.libPaths` with `--as-cran` doesn't list user-specified locations, but has its own temporary location, in addition to **R**'s defaults.

So listing the `LinkingTo` packages there and under `Imports` or `Suggests` solves the issue, with the former issuing an `R CMD check --as-cran` note if no **R** functions from the package are actually imported.

@eddelbuettel, could you please confirm that this is not an `Rcpp` issue, before I take the question to `R-devel`?

**Comment by kevinushey** [comment]
I think `LinkingTo` only implies the package must be available at build time, not necessarily at run time (and so the `--as-cran` check attempts to reflect this decision).

If you plan on using `sourceCpp()`, then all the dependent packages should also be included in e.g. `Imports` or similar.

**Comment by mlysy** [comment]
I see...wonderful, thanks!

**Comment by eddelbuettel** [comment]
No, LinkingTo sadly is a _run-time_ dependency too.  Every dplyr uses gets dozens of megabytes of BH installed.

I still think this here is user error / bad assumption of thinking `sourceCpp()` would be a good idea in examples.  Exactly _how_ and _where_ R finds packages during the `R CMD variant` differs AFAIK with the flags.

**Comment by kevinushey** [comment]
`LinkingTo` packages only get downloaded and installed if you're installing a package from sources (at least, as per the default behavior of `install.packages()`).  In other words, on Windows and macOS, installing a `dplyr` binary will install `dplyr` sans `BH`.

Since @mlysy is testing on macOS I suspect that's relevant here.

**Comment by eddelbuettel** [comment]
Ohhh, good point.  Being on Linux, and generally source-focused, I keep forgetting about how binaries work off CRAN.  That is partially good news then ("less of a 'tax' imposed by BH and alike") and helpful here too.   

So in essence, the bug is still his because his use of `sourceCpp()` now creates a _run-time_ dependency which he didn't encode.

**Comment by mlysy** [comment]
Thanks for all this very helpful feedback.

I don't think this is a binary/source issue, as the error persists on linux as well (tested on my own system and [rocker/r-devel/](https://hub.docker.com/r/rocker/r-devel/)).

In fact I've just checked (on linux) that `LinkingTo: BH` (which has no `Rcpp` dependencies) followed by
```
"BH" %in% .packages(all.available = TRUE)
```
in the package examples returns `FALSE` with `--as-cran` and `TRUE` without.  So I can't see how this could be an `Rcpp` issue...

**Comment by eddelbuettel** [comment]
> I can't see how this could be an Rcpp issue...

I agree. R does some _really_ quirky things for testing with the set of "seen" and "known" packages. If I were you I'd just file the idea of arbitrery `sourceCpp()` during examples as "won't work".  The overall use cases are still weird.
