### ISSUE TITLE
Resource leak, and other warnings from Coverity

### ISSUE THREAD

**Issue by krlmlr** [RcppCore/Rcpp#760]
When analyzing RMariaDB, a warning most likely related to Rcpp came up.

Source code location: https://github.com/RcppCore/Rcpp/blob/f9b700abcf97c408786150de0fd65adf6823699e/inst/include/Rcpp/iostream/Rstreambuf.h#L49

Problem: The `new Buffer` seems to be never freed. This might be a false positive, but maybe not.

Screenshot (because Coverity reports are private):

![screenshot from 2017-10-02 09-20-11](https://user-images.githubusercontent.com/1741643/31067486-654f4824-a753-11e7-85d9-8ce2f28b217f.png)

The other warning is about a constructor that doesn't initialize class members in tinyformat.h:

https://github.com/RcppCore/Rcpp/blob/f9b700abcf97c408786150de0fd65adf6823699e/inst/include/Rcpp/utils/tinyformat.h#L497

Screenshot:

![screenshot from 2017-10-02 09-25-09](https://user-images.githubusercontent.com/1741643/31067580-e0f6c542-a753-11e7-9810-777379c90672.png)

I've ignored the exception warnings so far, but we may take a look at them later.

**Comment by eddelbuettel** [comment]
I'm not sure.  Just look at the handful of lines at https://github.com/RcppCore/Rcpp/blob/f9b700abcf97c408786150de0fd65adf6823699e/inst/include/Rcpp/iostream/Rstreambuf.h#L43-L58

Sure, the `delete` is conditional, but it is still there.  One layer of `typedef` should not confuse.

Suggest to close this.

PS Congrats on being your own boss now!

**Comment by kevinushey** [comment]
FWIW we use a similar pattern in `testthat`:

https://github.com/hadley/testthat/blob/master/inst/include/testthat/testthat.h#L92-L96

Do you see the same warning there? I think the code as-is in Rcpp should be fine as well though. (Presumedly, if it weren't, `valgrind` and other tools would report a memory leak when exiting R after loading `Rcpp`)

**Comment by krlmlr** [comment]
@eddelbuettel: Thanks, also for the congrats. The code is fine, but marginally confusing, both to humans and to static code analyzers. Maybe declare `Buffer buf` instead of `Buffer* buf`? This doesn't seem to introduce extra cohesion, because the buffer class is defined just above the stream class.

@kevinushey: Haven't tested testthat yet.

What about the empty `FormatArg()` constructor?

**Comment by eddelbuettel** [comment]
> What about the empty FormatArg() constructor?

That's third party code (from tinyformat).  First order of biz would be to see if it changed.

**Comment by krlmlr** [comment]
Submitted upstream. Happy to provide a PR that makes buf a class member instead of a pointer member.

**Comment by eddelbuettel** [comment]
Sure, if you can re-test with coverity and rephrase the code so that we don't get yelled at ...
