### ISSUE TITLE
std::bad_alloc when calling Rcpp::stop from definition of function declared with Rcpp::export

### ISSUE THREAD

**Issue by jtatria** [RcppCore/Rcpp#765]
Hello Dirk et al.

I don't know if this is a bug or if it's documented somewhere, but if [[Rcpp::export]] is used in a function declaration and Rcpp::stop is used in the function definition, R crashes with a std::bad_alloc exception.

MWE:

````
    #include <Rcpp.h>
    
    // [[Rcpp::export]]
    void bomb();
    
    void bomb() {
        Rcpp::stop( "kaboom" );
    }
````
I assume this is becasue [[Rcpp::export]] normally generates the proper exception handling code in RcppExports.cpp if it sees uses of Rcpp::stop in a function and having that call in the definition hides it from the attribute expansion, but I spent hours debugging this yesterday and thought I'd come and let you know about it or, alternatively, ask if it's possible to safely use [[Rcpp::export]] in function headers somehow.

Thanks!
jta

ps: I'm also welcome to alternative suggestions... I'm playing with conditional compilation of function implementations to use an optional CUDA backend and figured that the correct way of handling that use case was to annotate the header in order to keep RcppExports.cpp unaware of the implementation details. It works great.... as long as you don't need to Rcpp::stop :(

**Comment by eddelbuettel** [comment]
You are exporting an empty function there.  How about:

```cpp
#include <Rcpp.h>
    
// [[Rcpp::export]]
void bomb() {
      Rcpp::stop( "kaboom" );
}

/*** R
bomb()
cat("Hello, world\n")
*/
```

When I source that, all is well.  The script ends, but I remain alive:

```r
R> Rcpp::sourceCpp('/tmp/gh.cpp')  

R> bomb() 
Error in bomb() : kaboom 
R> cat("Hello still alive\n") 
Hello still alive
R>
```

**Comment by jtatria** [comment]
Right, that's what I thought... but the wrapper still works, and this way I can change the actual definition of the function without having to export it. i.e. RcppExports.cpp ends up with:

````
void bomb();
RcppExport SEXP _mypkg_bomb() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    bomb();
    return R_NilValue;
END_RCPP
}
````

which works great as long as bomb() doesn't blow up.

My rationale was that it was better to keep the exports tied to the interface defined in a header and keep implementation details under the hood... It would be nice not having to sprinkle [[Rcpp::export]] everywhere. Maybe there is some workaround that I'm not aware of (e.g. an alternative for Rcpp::stop with no exception)?

Thanks!

**Comment by eddelbuettel** [comment]
I am sorry.  You opening a ticket claiming that `stop()` blows up your program.  I guess we can conclude that I disproved that.

Now you are going on about something with headers, but I honestly do not understand what you are trying to say.  If you want public and private functions in our file, you already can but you cannot use the same signature `void bomb()` twice for both.

But you haven't really made a compelling case as to why our package should change.  So I'd be inclined to just close this.   And no, there can't be an alternate `stop()` because we need to unwind things properly for which we need a `try` / `catch`. 

Maybe I misunderstand what you're after.   But right now I am inclined to close this.

**Comment by jtatria** [comment]
You are free to do as you please with the tickets opened as issues in your package. Thanks for your time.

However, there is nothing in the documentation that says that this use of the [[Rcpp::export]] attribute is not allowed, and this is backed somewhat strongly by the fact that the code posted above compiles and runs without any problems until a specific combination, not dissallowed by your API, of your own attributes and functions is used, at which point a rather uninformative std::bad_alloc exception is thrown.

I find it rather quaint that this is the case, and in my own very personal opinion, it seems rather unfortunate, as c++ attributes are allowed in function declarations, and speculation about the inner mental states of package developers should not generally be required in order to use a package in accordance with its public API.

I'm "going on about something with headers" because I was trying to do something very reasonable for lesser minds: i.e. keeping a function's declaration separate from its definition. The language in which you have chosen to write this package allows this without the need to create spurious additional signatures, but we see now that (apparently?) you disprove of this. Oh well. However honestly you don't understand what someone is trying to say does not necessarily imply that there is no argument there, but a minimum of communicative intetion is required for proper discussion.

Finally: I was not asking about an "alternative stop()", I was asking about an alternative _to_ stop(). i.e. if your convenience function does not work in this case, maybe there is some other mechanism that does work that could be used in its place?

Again, thanks.

**Comment by eddelbuettel** [comment]
I am at work and don't really have time for extended 500 word essays.   We have a rather detailed vignette about Rcpp Attributes and I have the feeling you would benefit from reading it carefully and studying the examples.  If you have remaining questions, feel free to discuss on the rcpp-devel mailing list.

**Comment by jtatria** [comment]
I assume you mean http://dirk.eddelbuettel.com/code/rcpp/Rcpp-attributes.pdf.

I did read it as carefully as I could. Section 2.3 says nothing to suggest this usage is not allowed.
Section 2.10 suggests this use-case is encouraged by the package.

I can think of two solutions to support this (though I'm sure there are good reasons against them):
1) force Rcpp::export to always include exception handling.
2) introduce an additional attribute to indicate that an exported function may throw an exception in order to force Rcpp::export to include the exception handling code.

I'll compose a more thorough presentation of the issue and continue this in rcpp-devel.

Thanks.

**Comment by eddelbuettel** [comment]
Yes, the [version off CRAN](https://cloud.r-project.org/web/packages/Rcpp/vignettes/Rcpp-attributes.pdf) -- which also what is on your computer if you have the current package -- is technically newer, but same content. 

Maybe stop for a moment too and try to search the old (closed) issue tickets here.  We had _many_ discussions on this, and believe our design to be sound.
