### ISSUE TITLE
Vectorised rgamma

### ISSUE THREAD

**Issue by amawl** [RcppCore/Rcpp#766]
The following command in R:
```r
rgamma(n = 10, shape = c(3,5), scale = c(2,8))
```
will produce one vector of 10 numbers; 5 generated with `  shape = 3` and ` scale = 2` and 5 others with the remaining parameters.
I know rgamma is vectorised in Rcpp, but it takes only scalar shape and scale parameters (if I well understood the code at http://dirk.eddelbuettel.com/code/rcpp/html/rgamma_8h_source.html, it is only scalars). Would it be possible to do the same as R (i.e., ` double a, scale;` could be vectors of same length---the number of generated numbers---if we want to avoid the recycling coding )?
Many thanks!

**Comment by eddelbuettel** [comment]
"Everything is possible" as it just code someone needs to write.  You need to be careful to not trample on existing behaviour.   Do you want to give it a shot?

**Comment by amawl** [comment]
I will try, I am not familiar with such a big program and I have basic C++ knowledge. For now, I am just going to do a for loop

**Comment by eddelbuettel** [comment]
That's is probably best.  Just write a local, non-general function.  Gather some experience, once you are comfortable with it and the design come back and maybe reopen the issue I'm about to close -- ok?

For us it is more important to be consistent than to change all possible features.  Vectorising one r* function but not the others is not a great plan.  And I don't have the bandwidth to do all of them,

**Comment by amawl** [comment]
I agree, thanks!
