### ISSUE TITLE
-pedantic compile changes Rcpp Behavior. 

### ISSUE THREAD

**Issue by mattfidler** [RcppCore/Rcpp#772]
A small example 
```c++
void fn(List lst){
  DataFrame df = lst["df"];
}
```

This compiles OK without the `-pendantic`.  However, adding the `-pendantic` gives:

```
rxData.cpp:513:26: error: conversion from ‘Rcpp::Vector<19>::NameProxy {aka Rcpp::internal::generic_name_proxy<19>}’ to ‘Rcpp::DataFrame {aka Rcpp::DataFrame
_Impl<Rcpp::PreserveStorage>}’ is ambiguous
```

Of course, you could get around this by:
```
void fn(List lst){
 DataFrame df = as<DataFrame>(lst["df")];
}
```

In theory, since I know that  the "df" member is in fact a dataframe, I shouldn't have to convert it with `as`.

This is a bit strange to me, but of course I can overcome it.  I just thought I should bring it to your attention.

(My fixed code:)

https://github.com/nlmixrdevelopment/RxODE/pull/13

**Comment by eddelbuettel** [comment]
It's not ideal, but it is common.  There is a _metric ton_ of template magic happening with `as<>()` and `wrap()` and not all cases are perfectly handled.   If you already have a workaround I suggest to use it.

**Comment by mattfidler** [comment]
Thats fine with me;  I just thought I would bring it to your attention.  You can close it if you wish.

**Comment by eddelbuettel** [comment]
I think we should.  I also think ALL documented use cases of extracting by name from a list use a template argument.

Come to think about it you must.  At _compile time_ we do not know will be in the `SEXP` at run-time.  So if you don't object, I'll close.

**Comment by mattfidler** [comment]
In this case, I do since it is created by me; However, overall I agree; Thanks for your time.

**Comment by eddelbuettel** [comment]
I can reopen in for you if feel better if you close it yourself ;-)

**Comment by mattfidler** [comment]
No.  Thanks again.
