### ISSUE TITLE
Quite Slowly to Transfer List of Lists From R to Cpp

### ISSUE THREAD

**Issue by hack1nt0** [RcppCore/Rcpp#773]
I have some codes to transfer List of Lists from R side to Cpp:

```cpp
RcppExport SEXP new_dtm(SEXP wordListsSEXP) {
    Rcpp::List textList = as<Rcpp::List>(wordListsSEXP);
    std::vector<Rcpp::List> wordLists(textList.size());
    for (int i = 0; i < textList.size(); ++i) wordLists[i] = as<Rcpp::List>(textList[i]);
    //dosomething
    return R_NilValue;
}
```
The ‘wordListsSEXP’  is a list of different-sized lists, actually it’s a list of tokenized texts. I need that to construct some Natural Language Process data structure, i.e., Document Term Matrix.

All the cost time is **60+** seconds, but the transferring and converting to std::vector part costs **58+** seconds. Can you believe it! The data is only 60 Mb, and direct copying in memory is much faster than that….Then I found a sound good solution, which cost **less than 1** second:

```cpp
RcppExport SEXP new_dtm(SEXP wordListsSEXP) {
    Rcpp::List textList = as<Rcpp::List>(wordListsSEXP);
    std::vector<Rcpp::List> wordLists(textList.begin(), textList.end());
    //dosomething
    return R_NilValue;
}
```
But this initialize of std::vector **in normal usage** is slower than first version, due to resizing of underly buffer. Obviously it's not the case when using Rcpp.

Some ideas to the reason? Thank you

**Comment by Enchufa2** [comment]
Could you provide a small example input for `wordListsSEXP`?

**Comment by eddelbuettel** [comment]
Closing for lack of follow-up.
