### ISSUE TITLE
Uninitialized `bool` members in `Type` class in `attributes.cpp` causing misleading sanitizer messages.

### ISSUE THREAD

**Issue by dcdillon** [RcppCore/Rcpp#774]
Basically this boils down to the default constructor of `Type` in `Rcpp/src/attributes.cpp` not initializing `isConst_` and `isReference_` members.  I have tested it against the appropriate rocker image, and initializing those members removes the runtime error.  Also see here: https://github.com/RcppCore/RcppArmadillo/issues/189.

For what it's worth I simply added
```
Type() : isConst_(false), isReference_(false) {}
```

to replace
```
Type() {}
```
and the runtime error goes away.

This from where I ran into the problem which mirrors the `RcppArmadillo` issue. 
```
Executing test function test.binary.function.hooked.and.hooked  ... attributes.cpp:167:11: runtime error: load of value 120, which is not a valid value for type 'bool'
```

**Comment by eddelbuettel** [comment]
(The https://github.com/RcppCore/RcppArmadillo/issues/189 is unrelated. @dcdillon were slack'ing and I mentioned that.  While also an ABSAN/USAN error, it got nuttin' on Rcpp.)

**Comment by dcdillon** [comment]
Upon further investigation, this would appear to not be the reason for the failure (jury still out), but it is flagging something that could be easily corrected.  Uninitialized variables are probably not for the best.

Unless I find something else important file this under "Should be cleaned up sometime".

**Comment by eddelbuettel** [comment]
Ok if we close this then?

**Comment by dcdillon** [comment]
Line noise is still a problem.  The fact that this line is often flagged is just going to lead to more false positives.  So the non-initialization should be cleaned up to avoid confusion, but I don't think it's a showstopper of any sort.

**Comment by dcdillon** [comment]
Perhaps close this and just make a ticket to have the default constructor initialize things to avoid line noise?  So we don't overstate the problem?

**Comment by eddelbuettel** [comment]
You can rename this one...
