### ISSUE TITLE
Different ordering of functions in RcppExports.cpp/.R on Windows and Linux

### ISSUE THREAD

**Issue by twolodzko** [RcppCore/Rcpp#775]
I maintain a package using Rcpp extensively, I edit it on two machines running on Windows and linux. I use devtools package for maintaining the package. I noticed that often when I change my package on different machine the ordering of functions in the src/RcppExports.cpp and R/RcppExports.R files changes (one of the functions changes its place) so on each commit I update the files nonetheless that _nothing_ has changed in the files besides toe ordering (I checked it multiple times). You can see an example [in this commit](https://github.com/twolodzko/extraDistr/commit/a8b038ee18bf2449ed039fc5c649c0022d85c008), where the location of the `cpp_rcatlp` function is swapped. This seems to happen after using `devtools::document()` and `devtools:check()` but as far as I understand, this is not an issue since the RcppExports files are updated by Rcpp itself since the functions call `Rcpp::compileAttributes()` and do not seem to do anything with the RcppExports files themselves. This is a minor issue, but still, it is irritating.

**Comment by eddelbuettel** [comment]
This is not a reproducible example.

**Comment by twolodzko** [comment]
@eddelbuettel I have the same versions of all the packages since on both machines I regularly update all the packages. Sorry but I have no idea how I could make a small reproducible example out of this.

**Comment by eddelbuettel** [comment]
I _really_ don't think you are the only one working cross-platform on one codebase. That is common. 

Yet you appear to be the only one bitten, and we have nothing reproducible.

**Comment by twolodzko** [comment]
Windows machine:

```
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Polish_Poland.1250  LC_CTYPE=Polish_Poland.1250    LC_MONETARY=Polish_Poland.1250 LC_NUMERIC=C                  
[5] LC_TIME=Polish_Poland.1250    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rcpp_0.12.13    devtools_1.13.4

loaded via a namespace (and not attached):
[1] compiler_3.4.2 tools_3.4.2    withr_2.1.0    yaml_2.1.14    memoise_1.1.0  digest_0.6.12  rlang_0.1.4 
```

Linux machine:

```
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=pl_PL.UTF-8      
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=pl_PL.UTF-8    LC_MESSAGES=en_US.UTF-8  
 [7] LC_PAPER=pl_PL.UTF-8       LC_NAME=C                  LC_ADDRESS=C             
[10] LC_TELEPHONE=C             LC_MEASUREMENT=pl_PL.UTF-8 LC_IDENTIFICATION=C      

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base    

other attached packages:
[1] Rcpp_0.12.13    devtools_1.13.4

loaded via a namespace (and not attached):
[1] compiler_3.4.2 tools_3.4.2    withr_2.1.0    yaml_2.1.14    memoise_1.1.0  digest_0.6.12 
```

The package was edited on Windows machine, then I ran git pull on linux machine and simply used `devtools::document()`, the effect is this commit: https://github.com/twolodzko/extraDistr/commit/b70b4debc421be169b6d1bcb3b2f9333a931e001 No updates of R or the packages were made between the commits.

**Comment by eddelbuettel** [comment]
I had an idea about what it could be:  impact of different locales on sorting.

Which is not something we can control.  But your printout (thanks for that!) leans the same way.  On Linux you have nothing set so you get `C` (ie US) defaults.  On Windows it knows you are in Poland.

Can you try harmonizing these two?

**Comment by twolodzko** [comment]
@eddelbuettel I ran `Sys.setlocale(locale = "pl_PL.UTF-8")` and `devtools::document()` on linux and nothing has changed, so I guess it had no effect unless it is that it is Windows that has it's own strange settings for locales.

**Comment by eddelbuettel** [comment]
I am pretty sure that this is the issue.  We don't explicitly sort of rearrange.

I can only suggest you experiment with a smaller, simpler package and see if you can reconstruct the behaviour, and maybe in doing so learn a way to avoid it.

**Comment by eddelbuettel** [comment]
Shall we close this then?

**Comment by twolodzko** [comment]
@eddelbuettel if this is something you can't fix, then it seems that yes.

**Comment by eddelbuettel** [comment]
I don't control how the operating system implements sorting according to a locale.
