### ISSUE TITLE
Rcpp::warning does not follow the correct interface for Rf_warning

### ISSUE THREAD

**Issue by jimhester** [RcppCore/Rcpp#776]
[`Rf_warning`](https://github.com/wch/r-source/blob/eb468006b82d96917db88e2310286b54a27b47b7/src/main/errors.c#L296-L308) is defined with a function prototype like that of printf

> void warning(const char *format, ...)

However `Rcpp::warning()` calls it instead with only a null terminated string (I linked here to the C11 code, but the C89 code has the same problem).

https://github.com/RcppCore/Rcpp/blob/fc3c0ed269458b69fbd60ee42005b83990cdca3f/inst/include/Rcpp/exceptions/cpp11/exceptions.h#L45-L48

This means that any values passed to `Rcpp::warning()` which happen to have format specifiers in them will access random memory, outputting garbage or potentially crashing R.

For a simple example illustrating the issue.

``` r
Rcpp::cppFunction('void test() { Rcpp::warning("%s", "a str with %o in it"); }')
test()
#> Warning in test(): a str with 1543134670 in it
```

**Comment by eddelbuettel** [comment]
Ugggh.

What should we do? Refuse to process strings with `%[a-z]` in them?  Pass them to tinyformat?

**Comment by jimhester** [comment]
I would either

1. Remove tinyformat from the equation entirely for warnings and pass the arguments directly to `Rf_warning()`.
2. Always specify a first argument of `%s` and leave the tiny format the way it is as the second argument.

With either approach you shouldn't need to sanitize the inputs.

**Comment by eddelbuettel** [comment]
Approach 2 is good.  PR forthcoming.
