### ISSUE TITLE
Update tinyformat

### ISSUE THREAD

**Issue by krlmlr** [RcppCore/Rcpp#786]
to satisfy `-Wimplicit-fallthrough` on GCC 7, https://github.com/c42f/tinyformat/pull/39.

Happy to submit a PR that just includes this change or all recent upstream changes.

**Comment by eddelbuettel** [comment]
Sounds good.  Can you do me a favour and double check that we don't have any local change in the currently-included version of tinyformat?

**Comment by coatless** [comment]
There _are_ local changes in the tinyformat header that ships with Rcpp. Primarily some `#ifdef`

**Comment by eddelbuettel** [comment]
We need a clean patch against the original version then so that we can carry the patch forward.

**Comment by eddelbuettel** [comment]
Quite a few touches on this file:

```sh
edd@brad:~/git/rcpp/inst/include/Rcpp/utils(master)$ git ls tinyformat.h
* 8640275e - additional #nocov tags, reformating wrap.h (6 months ago) <Dirk Eddelbuettel>
* ef4e9c53 - extra newline (closes #701) (6 months ago) <Dirk Eddelbuettel>
* 72f0652b - Improved exception infrastructure (8 months ago) <James Joseph Balamuta>
* 0c238764 - Refresh tinyformat with May 2016 header, retain local modifications (8 months ago) <James Balamuta>
* f23cc203 - refreshed tinyformat.h against upstream, keeping local mods (2 years, 3 months ago) <Dirk Eddelbuettel>
* 74204012 - don't enable C++11 features in tinyformat (2 years, 8 months ago) <Kevin Ushey>
* e47cd95a - stripping out more 'assert' bits (2 years, 10 months ago) <Kevin Ushey>
* 40fffd23 - further ensure no 'assert' leakage (2 years, 10 months ago) <Kevin Ushey>
* e0f5fecd - disable TFM assert (#237) (2 years, 10 months ago) <Kevin Ushey>
* 11b9f125 - Better Rcpp::stop. See hadley/dplyr#794 for the full story (3 years, 1 month ago) <Romain François>
edd@brad:~/git/rcpp/inst/include/Rcpp/utils(master)$
```

**Comment by coatless** [comment]
Diff between current tinyformat and new version: 

https://github.com/c42f/tinyformat/compare/6f47210fd32fb2b5e257cd4af50c36a85e08011c...689695cf58700e6defe3741829564cd682d5ae57#diff-377db66ac3fb15cf2670e774fab87d13

**Comment by coatless** [comment]
Difference between what is currently implemented in _Rcpp_ vs. upstream tinyformat library:

https://www.diffchecker.com/vQLIKRnV

**Comment by kevinushey** [comment]
If possible, I would be in favor of the following:

1. Bring in the latest version of Catch (on the v1 branch, since we need to support C++98)
2. Define our own wrapper header file, wherein we define our own patches before inclusion of Catch (so that we can maintain Catch + our patches separately)
3. Only if necessary would we then patch the Catch header itself.

**Comment by eddelbuettel** [comment]
_scratches head_

We are talking about tinyformat here, not catch.  That said, I luuv catch as much as the next guy and would be in favour.  Now, do we actually want it here (bloat?) or should we consider another outside package (in the same way @krlmlr has plog in another package).  Included may be easier.

**Comment by eddelbuettel** [comment]
Did you maybe mean s/Catch/tinyformat/ ?

**Comment by kevinushey** [comment]
Whooooops. By Catch, I meant tinyformat -- I think what I suggested still applies, though...

*brews another cup of coffee*

**Comment by eddelbuettel** [comment]
Yup. And in favour of 1., 2., and 3.  Does anybody feel like volunteering with the PR?

**Comment by krlmlr** [comment]
I think we need to cherry-pick only the last three changes to tinyformat, because 0c238764 (the fourth commit) was just an update from upstream.

For 72f0652b I think we can use an external header (only defining a macro). Can we do 8640275e without changing the tinyformat header?

**Comment by eddelbuettel** [comment]
We can ignore `#nocov`, that is cosmetic.  I don't think we can ignore `assert()`, and not sure we want to play games with that.  Would that be the one (set of) minimal edit(s) ?

**Comment by krlmlr** [comment]
If we ignore `#nocov`, I think we can do with a wrapping header and a minimal set of edits. Happy to submit a PR.

**Comment by eddelbuettel** [comment]
Go for it.  Maybe even add a global `// #nocov start` at the top with a matching `// #nocov end` and the bottom.

**Comment by krlmlr** [comment]
I have submitted a change upstream, if merged this will simplify our maintenance here.

**Comment by c42f** [comment]
Thanks for the patch. It's always neat to see people using this little library in places I didn't expect :-)
