### ISSUE TITLE
compound operators (+=, ...) with scalar argument

### ISSUE THREAD

**Issue by sgsokol** [RcppCore/Rcpp#787]
Recently I had to increment an integer vector by 1 and discovered that I could not write `v+=1`. Compiler didn't agree. Instead, I had to write `v=v+1` which was accepted. When I tried to patch vector/Vector.h to add smth like:
```
template <typename T>
   Vector& operator+=( const T& rhs ) { ... }
```
template pattern conflicted with already defined
```
template <typename EXPR_VEC>
    Vector& operator+=( const VectorBase<RTYPE,true,EXPR_VEC>& rhs ) {...}
```
If I rewrite the latter as
```
    Vector& operator+=( const Vector& rhs ) {...}
```
It preserves the old functionality and leaves enough space to add templated scalar += operator.
Can I propose a PR with this rewriting/addition?
The new code will be similar to
```
    template <typename T>
    Vector& operator+=( const T& rhs ) {
        iterator start = begin() ;
        if (is_na( rhs )) {
            for( R_xlen_t i=0; i<size(); i++){
                start[i] = traits::get_na<RTYPE>();
            }
        } else {
            for( R_xlen_t i=0; i<size(); i++){
                if( ! traits::is_na<RTYPE>(start[i]) ){
                    start[i] += rhs ;
                }
            }
        }
        return *this ;
    }
    Vector& operator+=( const Vector& rhs ) {
        const_iterator ref = rhs.begin() ;
        iterator start = begin() ;
        R_xlen_t n = size() ;
        // TODO: maybe unroll this
        stored_type tmp ;
        if (Vector::can_have_na::value) {
            for( R_xlen_t i=0; i<n; i++){
                Proxy left = start[i] ;
                if( ! traits::is_na<RTYPE>( left ) ){
                    tmp = ref[i] ;
                    left = traits::is_na<RTYPE>( tmp ) ? tmp : ( left + tmp ) ;
                }
            }
        } else {
            for( R_xlen_t i=0; i<n; i++){
                if( ! traits::is_na<RTYPE>(start[i]) ){
                    start[i] += ref[i] ;
                }
            }
        }
        return *this ;
    }

```
By the way, this could be a good occasion to add the other similar operators (-=, *= and /=). As the code for all these operators is very similar, I plan to use a macro definition. Is it OK with your coding policy?

**Comment by eddelbuettel** [comment]
Rounding this out / adding support sounds like a good idea.  

We had some other changes to Sugar etc top --- but we probably want to review this carefully by a number of folks.  So let's not rush yet.

**Comment by coatless** [comment]
c.f. #25

**Comment by sgsokol** [comment]
What I see in #25 is only an intention to add these operators and some commits to Rcpp11 not to Rcpp. Right?

**Comment by eddelbuettel** [comment]
That was a particularly charming way of telling the world how Rcpp11 was better and going to dominate all. 

The need for this was long recognised; these (low-numbered) issue tickets were carried over from R-Forge. Usually, I just recommended to use Arma matrices and vectors but we are closer.  So no need to rush now, we may as well get it right.

**Comment by sgsokol** [comment]
I have found a couple of additional points that could help in your reflexion:
 - both actual operations `v1+=v2` and `v1+v2` does not check for different sizes of arguments so some nasty surprises can occur, e.g. `v1+v2 != v2+v1` if they are of different sizes. Another (even worse) example is reading from memory far beyond of allowed limits when `length(v2) << length(v1)`;
 - `v1+=v2` respects the attributes of `v1` (namely `Dim`) while `v1+v2` does not, it will always results in a vector even if `v1` or `v2` or both  are matrices.
