### ISSUE TITLE
Sugar sample with seed to improve reproducibility

### ISSUE THREAD

**Issue by instantkaffee** [RcppCore/Rcpp#794]
To reproduce `c++ ` functions using the Rcpp sugar `sample()` function it would be helpful to somehow ensure same results depending on a seed. One way would be to give sample an `int seed` parameter, not sure whether this is the best way.

**Comment by eddelbuettel** [comment]
This already works the usual way:

```r
R> cppFunction("NumericVector mysample(NumericVector v, int n) { return sample(v, n, true); }")
R> set.seed(123)               # set a seed
R> mysample(1:10, 5)
[1]  3  8  5  9 10
R> set.seed(123)               # set the same seed
R> mysample(1:10, 5)
[1]  3  8  5  9 10             # got the same sample
R> mysample(1:10, 5)   
[1] 1 6 9 6 5                  # different one because RNG state not reset
R> 
```

**Comment by eddelbuettel** [comment]
In general, seeding is "difficult" because the R RNGs are feature-rich.  So all of Rcpp works by assuming you set the seed ... via the R interface.

**Comment by instantkaffee** [comment]
Perfect, thx for fast answer.
