### ISSUE TITLE
Support NVCC better?

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#797]
Cf email discussion on rcpp-devel in thread titled "NVCC compatibility" started by @cdeterman.

One issue, apparently found first by @jtilly and noted [here in his RcppThrust README](https://github.com/jtilly/RcppThrust) is that [this line](https://github.com/RcppCore/Rcpp/blob/4af2b9acd40e198f657f67e028cbcceef3b68c1d/inst/include/Rcpp/vector/proxy.h#L98) need to drop `const`.   Can we just add a non-const version too?

(Typo fixed. Added New Year's Resolution to only copy addresses and never ever type free hand, cf `fortunes::fortune("dirk can type")`)

**Comment by Enchufa2** [comment]
Quick comment to ping @jtilly (typo above) and to note that [this getter](https://github.com/RcppCore/Rcpp/blob/4af2b9acd40e198f657f67e028cbcceef3b68c1d/inst/include/Rcpp/vector/proxy.h#L128) is the only one in that file not qualified as `const`, which could solve the problem without discarding the other one.

**Comment by Enchufa2** [comment]
Oh, and consequently, [this operator](https://github.com/RcppCore/Rcpp/blob/4af2b9acd40e198f657f67e028cbcceef3b68c1d/inst/include/Rcpp/vector/proxy.h#L103) should be qualified as `const` too.

**Comment by cdeterman** [comment]
@Enchufa2  I have tried modifying that getter and operator both as `const` with my own [gpuRcuda](https://github.com/gpuRcore/gpuRcuda) but the following error is still returned

>/usr/local/lib/R/site-library/Rcpp/include/Rcpp/vector/proxy.h(99): error: the object has type qualifiers that are not compatible with the member function "Rcpp::internal::string_name_proxy<RTYPE>::get"
            object type is: const Rcpp::internal::string_name_proxy<RTYPE>

**Comment by Enchufa2** [comment]
@cdeterman Have you clean up before rebuilding and reinstalled correctly? Because I've tried with docker and your package compiles just fine (with warnings, but without error). [This is the diff](https://github.com/RcppCore/Rcpp/compare/master...Enchufa2:nvcc-compatibility). I can create a pull request if @eddelbuettel agrees.

**Comment by eddelbuettel** [comment]
Narrow-ish change to one setter / adding one getter as discussed sounds fine to me.

Diff looks good.  If you are familiar enough with the format an entry in ChangeLog is always appreciated too.

**Comment by Enchufa2** [comment]
Fine. I'll prepare a Dockerfile too and append it to the PR, so that you can test it with one command.

**Comment by eddelbuettel** [comment]
Why would I need it?  I tend to just rebuild Rcpp and then use [my fancy new parallel rev dep runner](http://dirk.eddelbuettel.com/code/prrd.html) to test'em.

**Comment by Enchufa2** [comment]
I mean, to test that nvcc does not complain anymore.

**Comment by eddelbuettel** [comment]
Ah, yes.  I had created an nvidia-enabled container the other day (see [here](https://github.com/rocker-org/ml/blob/master/gpu/Dockerfile)) but I have my docker binary and nvidia-docker out of sync.

But `nvcc` is @cdeterman 's problem, I just want to ensure we don't break Rcpp for all :)

**Comment by cdeterman** [comment]
@Enchufa2 you are correct, I overlooked cleaning up my previous build.  Sorry for confusion.  The changes in the provided commit indeed do address the error.  Thanks for all your help everyone.
