### ISSUE TITLE
Negative `NA` in `na_omit`

### ISSUE THREAD

**Issue by HervePerdry** [RcppCore/Rcpp#803]
I met a problem with `na_omit()`. A minimal example speaks a thousand words. Consider this test function:

```c++
#include <Rcpp.h>
using namespace Rcpp;
NumericVector test(NumericVector x) {
  return na_omit(x);
}
```
And this R session.

```
> test( NA_real_ )
numeric(0)
> test( -NA_real_ )
[1] NA
```

Such negative `NA`'s can be produced by numeric functions. This was an inexplicable source of failure in some code of mine...

**Comment by eddelbuettel** [comment]
Upgrade to what is in the master branch and currently waiting in incoming at CRAN:

```r
R> packageVersion("Rcpp")
[1] ‘0.12.15’                                        ## upcoming release, now at GitHub
R> Rcpp::cppFunction("NumericVector myna(NumericVector x) { return na_omit(x); } ")
R> myna(NA_real_)
numeric(0)
R> myna(-NA_real_)
numeric(0)
R> 
```

**Comment by HervePerdry** [comment]
Thanks.

**Comment by eddelbuettel** [comment]
What version were you runnnig? 0.12.14 or older?

**Comment by HervePerdry** [comment]
I was running 0.12.14 at least on one of the places where I met the issues, yes — not sure about the others right now.

**Comment by eddelbuettel** [comment]
Dang. It is something that you'd think we would have caught.  But it so happens that one of those comparisons just flipped back to R itself, and these little consistencies matter.  Sorry you had to chase that.

**Comment by HervePerdry** [comment]
No problem — I admit it was a bit lengthy, but at least I learned that `NA_real_` and `-NA_real_` have different internal representations. I’ll try to drop that into casual conversations ;)

**Comment by eddelbuettel** [comment]
LOL :)
