### ISSUE TITLE
Compile Openacc in Rcpp using RStudio on Windows

### ISSUE THREAD

**Issue by ManuHamel** [RcppCore/Rcpp#805]
Hi, 

I have a question. I would like to use OpenAcc combined with Rcpp on Windows. However, I find it difficult to build a package with RStudio. I think there are some "links" that are missing.  Also, I am using the PGI compiler for OpenAcc. Do you have tips or do you have an example that you could send to me? 

Emmanuel

**Comment by eddelbuettel** [comment]
As I tried to explain when you contacted me directly, the best place for support and help is the mailing list.

You find the [mailing list page over here](http://lists.r-forge.r-project.org/mailman/listinfo/rcpp-devel) as any query to Google of the form `rcpp-devel list` should show.

Direct email to one person is suboptimal.  More eyes is better, and you get the most on the list.  As the [Rcpp FAQ vignette](https://cloud.r-project.org/web/packages/Rcpp/vignettes/Rcpp-FAQ.pdf) (on the CRAN site and installed withyour copy of Rcpp) says:  

> ## Where can I ask further questions
>
> The [Rcpp-devel](https://lists.r-forge.r-project.org/cgi-bin/mailman/listinfo/rcpp-devel) mailing list hosted at R-forge is by far the best place.  You may also want
to look at the list archives to see if your question has been asked before.
>
> You can also use [StackOverflow via its 'rcpp' tag](http://stackoverflow.com/questions/tagged/rcpp).

I'll add something to the GitHub README.md too.

**Comment by ManuHamel** [comment]
Thank you! I will write to this email list!
