### ISSUE TITLE
Issue with auto and NumericMatrix constructor

### ISSUE THREAD

**Issue by drjdn** [RcppCore/Rcpp#806]
The following code works as expected:

```cpp
#include <Rcpp.h>
using namespace Rcpp;


// [[Rcpp::export]]
NumericMatrix MatAdd1(const NumericMatrix X) {
  auto vX = as<NumericVector>(X);
  // Changing NumericVector to auto results in error
  NumericVector vZ = vX + 1;
  auto Z = NumericMatrix(X.nrow(), X.ncol(), vZ.begin());
  return Z;
}
```
however when you change NumericVector to auto:

```cpp
#include <Rcpp.h>
using namespace Rcpp;


// [[Rcpp::export]]
NumericMatrix MatAdd1(const NumericMatrix X) {
  auto vX = as<NumericVector>(X);
  // Changing NumericVector to auto results in error
  auto  vZ = vX + 1;
  auto Z = NumericMatrix(X.nrow(), X.ncol(), vZ.begin());
  return Z;
}
```
it fails to compile.  The error message seems to indicate that the issue is in the iterator in the constructor.  Clearly, this code doesn't do anything useful but it was the smallest example I could come up with that illustrates the issue.

**Comment by eddelbuettel** [comment]
As always, patches welcome.  

Preferably those that do not do harm to other code so it better pass the unit tests, preferably also tests against reverse dependencies...

**Comment by drjdn** [comment]
Running the following code:

```cpp
#include <typeinfo>
#include <Rcpp.h>
using namespace Rcpp;


// [[Rcpp::export]]
List tester(const NumericMatrix X) {
  auto vX = as<NumericVector>(X);
  NumericVector vZ = vX + 1;
  std::cout << typeid(vZ).name() << "\n";
  auto avZ = vX + 1;
  std::cout << typeid(avZ).name() << "\n";
  List out;
  out["vZ"] = vZ;
  out["avZ"] = avZ;
  return out;
}
```
outputs:

N4Rcpp6VectorILi14ENS_15PreserveStorageEEE
N4Rcpp5sugar21Plus_Vector_PrimitiveILi14ELb1ENS_6VectorILi14ENS_15PreserveStorageEEEEE

which c++filt -t tells me are:

Rcpp::Vector<14, Rcpp::PreserveStorage>
Rcpp::sugar::Plus_Vector_Primitive<14, true, Rcpp::Vector<14, Rcpp::PreserveStorage> >

which solves the issue as defined operators in sugar don't have begin() and end() methods.  I'll fix this and make a pull request on the weekend when I have time for fun ;-).  I'd be surprised if this causes any breakage but I'll run the unit tests as requested.

**Comment by eddelbuettel** [comment]
If you have Travis CI setup up they should run when you commit to your fork too.

**Comment by drjdn** [comment]
Thanks for the heads up.  I don't have Travis CI setup but I'll look into it.
