### ISSUE TITLE
Trouble updating package to work with Rcpp >= 0.12.12

### ISSUE THREAD

**Issue by tpq** [RcppCore/Rcpp#809]
First of all, thanks everyone for their hard work in putting together a great package! Your great software has made my R package possible! I fear I've hit a wall though, and hope someone here can point me in the right direction? --

I use RStudio and Roxygen; the package works smoothly with Rcpp 0.12.11. However, the new(er) versions of Rcpp change the `R/RcppExports.R` and `src/RcppExports.cpp` files and now my functions do not work. The changes look like this, e.g. (i.e., they drop `PACKAGE = 'propr'`):

![rcpp](https://user-images.githubusercontent.com/13802096/35758651-36ca3b26-08c9-11e8-84f8-827ee0a414e6.png)

I can build the package fine, but when using a function, I get the error e.g.,:

`Error in lr2rho(prop@logratio) : object '_propr_lr2rho' not found`

I think everything is set up where this shouldn't happen? i.e.,:

`#' @useDynLib propr, .registration = TRUE`

Any advice is appreciated.

Thank you in advance!

**Comment by eddelbuettel** [comment]
We all had the same transition, and it works for all of us.  There may be a point where you just need to run `compileAttributes()` twice, and thereafter you are good.

**Comment by eddelbuettel** [comment]
And that was all there was to it -- running `compileAttributes()` twice.

```
  cd /tmp/
  git clone git@github.com:tpq/propr.git
  cd propr/
  compAttr.r     ## littler wrapper for compileAttributes()
  compAttr.r 
  git diff
  build.r        ## littler wrapper for R CMD build
  build.r -f     ## skipping vignettes as I do not have all your Suggests:
  install.r propr_3.1.4.tar.gz    ## littler wrapper for R CMD INSTALL 
```

and it compiles and installs and all that.

**Comment by eddelbuettel** [comment]
@tpq :  Would an entry in the Rcpp FAQ have helped you? Would you have looked there.

**Comment by tpq** [comment]
Thank you for a quick and helpful reply. I have tried `compileAttributes()` twice. This did not work within RStudio, but also did not work from command-line: 

```
  mkdir tmp
  cd /tmp/
  git clone git@github.com:tpq/propr.git
  cd propr/
  Rscript -e "Rcpp::compileAttributes()"
  Rscript -e "Rcpp::compileAttributes()"
  git diff
```

![screenshot_2018-02-03_12-37-16](https://user-images.githubusercontent.com/13802096/35761641-01789dbc-08df-11e8-8f2d-3ba6ad5a7983.png)

Build and install works:

```
cd ..
R CMD build --no-build-vignettes propr
R CMD INSTALL propr_3.1.4.tar.gz
```

Execution of function does not work:

```
Rscript -e "library(propr);propr::perb(matrix(1:25, 5, 5))"
# error
Loading required package: methods
Error in lr2rho(prop@logratio) : object '_propr_lr2rho' not found
Calls: <Anonymous> -> lr2rho
Execution halted
```

Reading #745 is helpful, though deleting RcppExports* files did not resolve issue.

Perhaps I am struck with a computer-specific problem?

**Comment by tpq** [comment]
ADDENDUM: OK, I think I got it. Manually deleting the file `src/init.c` seems to have fixed the issue.

Thanks for your help!

**Comment by eddelbuettel** [comment]
Glad to hear you are set. I am not sure why I didn't have to do that, but yes the old definitions in there would be a problem. We now write new ones too.

**Comment by eddelbuettel** [comment]
I was too fast / superficial. I had that error too, but then skipped vignettes. Good work for hanging in there.
