### ISSUE TITLE
Cannot include <regex> from C++ 11 on Windows

### ISSUE THREAD

**Issue by hongyuanjia** [RcppCore/Rcpp#810]
Hi, I am pretty new to Rcpp. I tried to write a simple function to test regex functions in C++ 11, please see below. The function can be compiled successfully, but whenever I ran it, R just stuck there with no response. I found that the issue occurred whenever there is a `std::regex` call. Below is minimally reproducible example:

```r
Rcpp::cppFunction(code =
    '
    int test() {
        std::regex simple("\\\\d");
        return 0;
    }
    ',
    plugins = "cpp11",
    includes = "#include <regex>"
)

test()
```

I saw some kind of relevant  issue here: #441  . Sorry I do not have a Mac or Linux machine, and I cannot confirm whether this issue can be reproduced on those platforms.

Here are the session info:
```r
> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936 
[2] LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rcpp_0.12.15    devtools_1.13.4

loaded via a namespace (and not attached):
[1] compiler_3.3.3 tools_3.3.3    withr_2.1.1    memoise_1.1.0  digest_0.6.13 
```

Any insights? Thanks!

**Comment by eddelbuettel** [comment]
I think that is to be expected because
- `regex` is from C++11
- on windows, _all_ builds use the same compiler, `g++` version 4.9.3
- which has incomplete C++11 support

None of this has anything to do with Rcpp, or is in any way under our control, sadly.  So I think I will close this.

**Comment by hongyuanjia** [comment]
Thanks for quick response. 

As this has nothing to do with Rcpp. I will close it.

So the only way to do is to wait an update from `g++` with full compatibility with C++11?

**Comment by eddelbuettel** [comment]
Yes, which may take years. :-/

**Comment by hongyuanjia** [comment]
No way... :-(

Thanks anyway. I will try to find a workaround using Boost.Regex.

**Comment by eddelbuettel** [comment]
Which works ... until it doesn't (easily) as you need linking :-/

I think your best bet may be the regex engines R uses itself you get that "for free".

**Comment by hongyuanjia** [comment]
Another sad news... 

I think I'd better take your advice.

**Comment by jjallaire** [comment]
Yes, that's what we do in Rcpp:
https://github.com/RcppCore/Rcpp/blob/master/src/attributes.cpp#L801-L810

**Comment by hongyuanjia** [comment]
@jjallaire Thanks a lot for your resources. It is a quite useful showcase of how to use R's regex engines in Rcpp.

**Comment by eddelbuettel** [comment]
I actually even meant at the C level. We should be able to link for free with eg the Perl regex engine as R is built with libprce everwhere.  I think.

It is not in `capabilities()` so it should be everywhere.  Here:

```sh
edd@rob:~$ ldd /usr/lib/R/lib/libR.so | grep pcre
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f738fa63000)
edd@rob:~$ 
```
