### ISSUE TITLE
Possible typo in source file? c+11 instead of c++11

### ISSUE THREAD

**Issue by hanchoppie** [RcppCore/Rcpp#822]
I am trying to install rcpp remotely to a computer cluster, running on linux. 

The installation is failing, with "g++: error: unrecognized command line option ‘-std=c+11’; did you mean ‘-std=c++11’?"

As far as I can tell there is no such thing as c+11, and I can find no reference to this anywhere online. Could this be a mistake? I have tried to investigate and fix this manually, however when downloading the tar ball to my home computer (MacBookPro, v10.12.6), I can't find "c+11" anywhere.

The modules loaded on the cluster are rstudio/1.1.383 and gcc-4.8.5, and the command I'm running is
>install.packages("Rcpp", Sys.getenv("R_LIBS_USER"), repos = c(CRAN = "http://cran.rstudio.com"))

**Comment by eddelbuettel** [comment]
I don't think `std=c+11` is set in our files.  Other tests would have flagged it.

Are you sure that is not a local setting creeping in?

**Comment by hanchoppie** [comment]
Ok that's good to know. Guessing it must be then, I'll have to investigate further. Thanks!

**Comment by eddelbuettel** [comment]
You can try any one of
- `~/.R/Makevars`
- `$RHOME/etc/Makeconf`
- the `src/Makevars` of the package you were building
- other environment variables
