### ISSUE TITLE
Rcpp.rdb is corrupt when downloading and opening package

### ISSUE THREAD

**Issue by mlfearon** [RcppCore/Rcpp#824]
I am trying to use a different package (lubridate) that relies on the Rcpp package, but it will not work because each time that I try to load 'lubridate' I receive an error message that says that the Rcpp.rdb file in the Rcpp package is corrupt.  I went to the file indicated within the Rcpp package documents and it indeed appears to be corrupted. I have tried re-downloading it multiple times, and the same file remains corrupted. I am unsure of how to move forward or if others are experiencing a similar problem.
Thanks!

**Comment by eddelbuettel** [comment]
No, nobody else has this problem.

I suspect you are starting R in such a way that your previous session will get loaded -- and which pulls Rcpp in.  "Don't do that" -- start R as an empty fresh session, which will enable you to install or update Rcpp.

**Comment by mlfearon** [comment]
Thank you, I had tried that, but I guess the 3rd time is the charm and it worked this time.
