### ISSUE TITLE
Rcpp hex sticker

### ISSUE THREAD

**Issue by coatless** [RcppCore/Rcpp#827]
Thoughts on modifying the _C++_ sticker to reflect _Rcpp_? 

<img src="https://user-images.githubusercontent.com/833642/36984493-9f340464-205a-11e8-9d93-bddc0a5793ec.png" alt="C++ Logo" width="306" height="344" />

In particular, I think let's add the _R_ logo and change _++_ to _pp_.

**Comment by eddelbuettel** [comment]
_The_ C++ sticker?  So source is https://isocpp.org/?  Any re-use issues?   Morhing the R logo over it would be a natural fit.

Personally, I can live without hex sticker but you kids seem pretty gang-ho so ...

**Comment by eddelbuettel** [comment]
> In general, we want the logo to be used as widely as possible to indicate material related to the portable C++ and its applications, without implicitly endorsing something or someone. Please ask first before using a derived version of the logo or when in doubt.

From https://isocpp.org/home/terms-of-use

**Comment by coatless** [comment]
No dice in terms of modify the logo. If the logo is kept in-tact, then yes.
I'll look into this more in about 2 weeks.

**Comment by coatless** [comment]
How about this:

![rcpp-hex-sticker](https://user-images.githubusercontent.com/833642/41198117-2e70b208-6c37-11e8-8939-9f544163cd47.png)

We can use the R logo under GPL-2 licensing:

https://www.r-project.org/logo/

**Comment by eddelbuettel** [comment]
1. Why would we _want_ a hex sticker?
2. What does the blue border signify?
3. Why is the cpp in handwritten font?

**Comment by coatless** [comment]
1. Logo? Branding?
2. The border exists to focus attention within the sticker. 
     - c.f. examples: https://github.com/rstudio/hex-stickers/tree/master/PNG
     - With this being said, the blue border is a bit bigger here as I had the "bleed" over layer active.
3. "Roughness" of _C++_ compared to _R_.

How about something along the lines of:

![screen shot 2018-06-10 at 10 17 58 am](https://user-images.githubusercontent.com/833642/41203034-997ffa3a-6c97-11e8-8ec1-a96d07079bd5.png)

Maybe modify the ring around the R logo to resemble a speedometer with _cpp_ portion written in a more technical font.

**Comment by coatless** [comment]
Based the meter off of: https://en.wikipedia.org/wiki/Up_to_eleven

Basically, start at 0, have a notch for odd values, and show even ones.

Example:

![rcpp-hex-sticker-meter](https://user-images.githubusercontent.com/833642/41204412-c8bea1b8-6ca9-11e8-948e-9b1826e75ddf.png)

Moved the cpp portion to small caps: 
![rcpp-hex-sticker-meter-v3](https://user-images.githubusercontent.com/833642/41204425-f415af64-6ca9-11e8-9b61-8d2c3819e13b.png)

**Comment by coatless** [comment]
Better yet... How about:

![rcpp-hex-sticker-meter-v4](https://user-images.githubusercontent.com/833642/41204580-efc45260-6cab-11e8-8f61-f28f0923d34b.png)

**Comment by eddelbuettel** [comment]
Maybe center the speedometer?  We can shadow the 0|2|4...   The asymmetry is bit odd.

The two contrasting fonts for R and cpp are just right.

**Comment by coatless** [comment]
When you mean _center_ do you mean lower the Rcpp text? Similar to the positioning of the first iteration? Or center it in terms of where the needle is pointing? 

Shadow-wise, is this like a silhouette for each number or do you mean knock out the number and leave an imprint? 

![rcpp-hex-sticker-meter-v5](https://user-images.githubusercontent.com/833642/41205000-df0a15a8-6cb1-11e8-8c00-f911b79382db.png)

^ centered needle + drop shadow on each number

**Comment by eddelbuettel** [comment]
Sorry, I meant center the speedometer _relative to the rest of the design_.  Ie move it left so that the base of the needle is in the middle of a horizontal axis across the design.  Right the base of the needle is at 3/4 to the right.

**Comment by coatless** [comment]
Okay. Centered the spindle. Here are two versions of the centered spindle:

![rcpp-hex-sticker-meter-v8](https://user-images.githubusercontent.com/833642/41205206-8e9f108e-6cb4-11e8-8308-6ef0bbfd4bdf.png)

![rcpp-hex-sticker-meter-v9](https://user-images.githubusercontent.com/833642/41205207-8ea992fc-6cb4-11e8-8765-5d1f95a65470.png)

**Comment by eddelbuettel** [comment]
Dude.

Please.

Just.

Stop.

**Comment by coatless** [comment]
For safe keeping, here are the sticker files including the PSD file used. 

[rcpp-sticker-files.zip](https://github.com/RcppCore/Rcpp/files/3587153/rcpp-sticker-files.zip)
