### ISSUE TITLE
Source Cpp code from online source

### ISSUE THREAD

**Issue by coatless** [RcppCore/Rcpp#830]
Recently, there was an interesting StackOverflow question that came up regarding how to source code from GitHub. Sourcing code from an online repository has precedents in other _R_ packages. Most notably, `shiny` implements several ways to [run an app](https://shiny.rstudio.com/articles/deployment-local.html) from `shiny::runGist()` to `shiny:: runUrl()`. 

Dirk wrote a nice little five liner to solve this issue:

```r
library(Rcpp)
remurl <- "https://github.com/slwu89/MCMC/blob/master/adaptMCMC_source.cpp"
locfile <- "/tmp/mcmc.cpp"
download.file(url=remurl, destfile=locfile)
sourceCpp(locfile)   # dozens of error for _this_ file
```

I think it may be helpful to wrap this up into three functions:

- `compileGist()`
- `compileGitHub()`
- `compileURL()`

The pros of this approach: 

- Easier way to run code found online
- Allows for examples to just "work" without copy paste errors. 

The cons of this approach:

- `sourceCpp()` has already diluted the need to learn how to _package_ compiled code. By adding this, there is a risk of further neglecting package builds.
- This adds a new feature to the package.

**Comment by eddelbuettel** [comment]
Intend to close as *very clearly* stated over Slack.

**Comment by kevinushey** [comment]
I'd be open to extending `sourceCpp()` to understand `http://` URLs (where we just attempt to download the file and source it for you) but would rather not add extra helper functions.

I'm also open to doing nothing at all and saying the onus is on the user to download the file explicitly before sourcing it.

**Comment by coatless** [comment]
@kevinushey I'm more of a fan of modifying `sourceCpp()` as well. I proposed the helpers to match with prior work done in the _R_ ecosystem. 

I think having the URL component would amplify the usefulness of the Gallery as code could be spun into its own cpp file and then sourced. 

Quite a few mistakes arise on SO because of bad gallery copy + pastes.

**Comment by eddelbuettel** [comment]
The burden is on us for testing, consistence, easy of use.

It really looks like you badly want a mostly personaly helper function.  I still suggest you write one for yourself.  We don't really have to enlarge the package for this.    (And yes, @kevinushey is current that we _could_ alter `sourceCpp()`  to recognise a URL but again, needs testing, it already is a big and mighty function etc pp.).

**Comment by eddelbuettel** [comment]
Nobody really spoke up, so in the interest of keeping the open issue count smaller, I'm closing this.

BTW, I did add this helper function at the SO question:

```r
u2f <- function(url) { 
   tf <- tempfile() 
   download.file(url, tf, quiet=TRUE) 
   tf 
}
library(Rcpp)
url <- "https://raw.githubusercontent.com/slwu89/MCMC/master/adaptMCMC_source.cpp"
sourceCpp( u2f( url ) )
```

Make perfect sense in a personal helper function, or heck, maybe even on the help page for `sourceCpp`.

**Comment by coatless** [comment]
@eddelbuettel if you don't mind, I'd like to ping others as this issue on incorporating web compilation may have been lost in the fray.

Any thoughts on enabling `sourceCpp()` to accept a web URL? @jjallaire @nathan-russell @thirdwing 

**Current tally:**

@eddelbuettel is on record w/ no.
@kevinushey is on record w/ a neutral stance.

**Comment by eddelbuettel** [comment]
Sorry but you had seven days for this.  And I read Kevin as a nope here.  No new entry points.

**Comment by thirdwing** [comment]
> I think life is easier with just one entry point.

I agree with Kevin.

**Comment by eddelbuettel** [comment]
Also, bears repeating that 
- even the gallery half 1/2 Rmd files where it would not help
- on the 1/2 of cpp files you still need to adjust the URL

It's an ok idea in theory, but in practice it isn't compelling enough.
