### ISSUE TITLE
Better sugar support for NumericMatrix objects

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#833]
See eg [this somewhat recent SO question](https://stackoverflow.com/questions/49026407/how-can-i-do-logical-operations-on-rcppnumericmatrix-using-a-sugar-manner).  I gave an answer which carries the `dim` attribute from input to result, but treats it otherwise like a vector.  Would be nice to have that via TMP.

**Comment by coatless** [comment]
Related: #583, #23, #20
