### ISSUE TITLE
compileAttributes() from anywhere in package directory?

### ISSUE THREAD

**Issue by mlysy** [RcppCore/Rcpp#834]
Currently one can only do this from the top-level package folder, but I wonder if there's a reason not to be able to do this from the subfolders as well (as does e.g., `devtools::install`).

If you don't see any harm in this feature I'm happy to get started on a pull request.

**Comment by eddelbuettel** [comment]
But we also say `R CMD build` or `R CMD check` or any other command from the package root.  I see no need for a change.  Moreover, most people probably just have RStudio run it for them, and it too knows where to call it from.

Can't you keep that a local change, ie a local helper script of yours?

**Comment by mlysy** [comment]
I guess if everyone's using RStudio then indeed the feature isn't that useful.  I appreciate the feedback.

**Comment by kevinushey** [comment]
What do other development environments (e.g. ESS) do here?

**Comment by eddelbuettel** [comment]
@lionel- Can you chime in?

I don't call `compileAttributes()` from ESS; I tend to have 'editor plus shell' view of the world and long created [the `compAttr.r` helper (using littler)](https://github.com/eddelbuettel/littler/blob/master/inst/examples/compAttr.r).  A script such as that could easily be amended to 'climb up' the tree, or use the `here` package, or ...   I never had a need for anything more than this.

**Comment by lionel-** [comment]
We could add a compileAttributes() package command. I think more generally we need an easy way for users to set up commands that should only run with wd temporarily set to the current package directory.

**Comment by mlysy** [comment]
Dear all, thanks the for the feedback.  Since I don't use RStudio I never quite know whether my issue are of general interest or not.  I myself use ESS + devtools.  Digging a bit further, it seems that 
```{r}
Rcpp::compileAttributes(devtools::package_file())
```
solves my issue...about 5% faster than changing directories :)

I'm always up for learning better workflows though.  @coatless, may I ask you to expand on your feature of interest?  So you'd want to "compileAttributes" one file at a time?
