### ISSUE TITLE
SEXP function return 0 triggers runtime crash while return 1 compile time error

### ISSUE THREAD

**Issue by renkun-ken** [RcppCore/Rcpp#835]
The follow code does not trigger any compile time error:

```cpp
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
SEXP test1(int arg) {
  if (arg == 0) {
    return 0;
  }
  
  return List::create(_["arg"] = arg);
}
```

and if I run `test1(0)` the session will crash. An obvious fix is `return wrap(0)` but it would be much better to be handled at compile time, which behaves inconsistently with other integers. If I change `0` to `1` or any other integer, the code simply does not compile, which makes it easier to spot the issue.

```cpp
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
SEXP test1(int arg) {
  if (arg == 0) {
    return 1;
  }
  
  return List::create(_["arg"] = arg);
}
```

which produces the following compile error:

```
test1.cpp: In function ‘SEXPREC* test1(int)’:
test1.cpp:7:12: error: invalid conversion from ‘int’ to ‘SEXP {aka SEXPREC*}’ [-fpermissive]
     return 1;
            ^
make: *** [test1.o] Error 1
g++  -I/usr/share/R/include -DNDEBUG   -I"/home/ken/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/ken/R/test"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c test1.cpp -o test1.o
/usr/lib/R/etc/Makeconf:168: recipe for target 'test1.o' failed
Error in Rcpp::sourceCpp("~/R/test/test1.cpp") : 
  Error 1 occurred building shared library.
```

**Comment by kevinushey** [comment]
That compiles for the same reason this compiles:

```
struct Object {};
Object* whoops() { return 0; }
```

In C++, the `0` integer literal is 'special', and can be used to initialize null pointers of any type.

**Comment by eddelbuettel** [comment]
Your interface may need / want the `SEXP` here but in general you can protect yourself by being typed with a more explicit type.

**Comment by renkun-ken** [comment]
Thanks for the information. A more explicit type like `NumericVector` or `List` is certainly preferred in general but when the function has to handle multiple types and return multiple possible types, it becomes unsafe in some cases. I thought `compileAttributes()` had tried doing such checking as much as possible to avoid runtime error like this. Feel free to close this issue if you prefer.

**Comment by eddelbuettel** [comment]
Hm, I can't think of a `compileAttributes()` feature that would do this.

**Comment by eddelbuettel** [comment]
Closing as there is nothing actionable for us.
