### ISSUE TITLE
compileAttributes doesn't respect .Rbuildignore

### ISSUE THREAD

**Issue by jackwasey** [RcppCore/Rcpp#838]
> Rcpp      * 0.12.16 2018-03-13 CRAN (R 3.4.4)

Actual: I have C++ source files which I exclude using `.Rbuildignore` but it seems that `Rcpp::compileAttributes()` looks at them anyway in order to generate the various exports. This results in missing symbols when compiling, those missing symbols being from the ignored code.

Expected: files that are going to be ignored when building the package are also ignored (optionally?) by `Rcpp::compileAttributes()`

I am absolutely prepared to accept I could or should be doing things differently, and would appreciate guidance if this is the case. A workaround seems to be writing header files for each C++ source file and not excluding them.

**Comment by eddelbuettel** [comment]
Shooting from the hip:
- phase 1: take advantage of `.Rbuildignore` and create a tarball excluding files you do not want
- phase 2: unpackage that tarball; run `compileAttributes()` on its source

Or else I'd just renamed the files I do not want to, say, `src/ignoreMe.cpp.txt`.

**Comment by jackwasey** [comment]
Yes, that sounds like what I'll have to do.

Similarly Rcpp doesn't account for `#ifdef` and again brings in unwanted symbols in the export files.
I'm not expecting Rcpp to  recreate the entire R package build process, and as I seem to be the first to report this, I doubt it is worth the investment in time to make Rcpp do what Dirk describes above. However, I know some package do package builds as part of their operation, e.g. 'covr', so it does at least seem possible to me.

**Comment by eddelbuettel** [comment]
If you land at a describable / scripted usage pattern let us know.  I'd rather not think about embedding a filename regexer in compileAttributes but maybe we could add a fixed exclusion list.  So far this strikes me as too specialised an issue to warrant broad attention.  (We just got burned on a well-meaning change showing side-effects somewhere else.)

**Comment by eddelbuettel** [comment]
I'll close this at it is out of scope.
