### ISSUE TITLE
Rcpp modules do not support named arguments

### ISSUE THREAD

**Issue by JorisGoosen** [RcppCore/Rcpp#839]
Rcpp modules work nicely when you have a cpp class that you want to expose to R.
It is, however, not possible to use named arguments in the same way as one could do in R.

It would be practical to allow this and I have made an implementation of that in my fork. It adds a `method_named_args` to the module-definition functions. It assumes that the user has a class method that receives a single `std::map<std::string, Rcpp::RObject>` and will contain all named arguments with the specified name. Any unnamed arguments will be given a name such as `"__unnamed_arg_1"`.

This means the user will have to manually process the arguments in the same logical manner as R would do, aka use the unnamed arguments in the order they come in on the locations that would be expected but this is a small price to pay I would think.

**Comment by eddelbuettel** [comment]
That sounds like something we could look into.  Could you post here a mock (or real) extension of one of the sample modules that ship with Rcpp?

**Comment by JorisGoosen** [comment]
snippets from RcppModuleWorld that is extended in my fork:

```
class RcppModuleWorld {                   // a simple class with a setter and getter
public:
    RcppModuleWorld() : msg("hello"){}
  
    std::string named_args(Rcpp::map_named_args args) 
    { 
        std::string out = (args.count("hello") > 0 ? Rcpp::as<std::string>(args["hello"]) : "") + " ";
        out += args.count("world") > 0 ?  Rcpp::as<std::string>(args["world"]) : (args.count("1") > 0 ?  Rcpp::as<std::string>(args["1"]) : ""); //first check named argument world and otherwise use first unnamed arg ("1") if it exists
        return out;
    }

private:
    std::string msg;
};

std::string free_named_args(RcppModuleWorld * modworld, Rcpp::map_named_args args) { return modworld->named_args(args); }


RCPP_MODULE(RcppModuleWorld) {
    using namespace Rcpp;

    class_<RcppModuleWorld>( "RcppModuleWorld")
        .default_constructor()
        .method_named_args("named_args",    &RcppModuleWorld::named_args)
        .method_named_args("free_named_args",    &free_named_args)
	;
}
```

This works and i've added this to the unittest as well. I can set up a PR for this.

**Comment by eddelbuettel** [comment]
I maybe dense but could you also add the new usage pattern from the R side, and explain why it is useful?

**Comment by eddelbuettel** [comment]
I see it in the unit test you added.

```r
worldtest <- new(RcppModuleWorld)
stopifnot(all.equal(worldtest$named_args(hello="hallo", world="wereld"), 
                    worldtest$free_named_args(world="wereld", hello="hallo")))
stopifnot(all.equal(worldtest$named_args(hello="hallo", "wereld"), 
                    worldtest$free_named_args("wereld", hello="hallo")))
```

I know understand better what you were describing -- you get more R-like  behaviour of 'unordered' arguments on the C++ side.  I can maybe see the marginal benefit of this, I am not sure I buy yet that I want to modify thirteen files for it.

**Comment by JorisGoosen** [comment]
I thought this would be useful because all the code to make use of unordered arguments with modules would be on the cpp-side and not in R itself. To me it seems that this makes the class much more selfcontained and I think that is a good thing. 

The same behaviour could possibly be achieved by subclassing it in R, but for me as a more cpp-oriented programmer it wasn't quite clear how I could do this and what the repercussions would be for objects that refer to each other through pointers. And it also seems to go against the spirit of Rcpp-modules as far as it appeared to me because for the rest it offers a (relatively) painfree wrapping of an entire cpp-class in R.

**Comment by eddelbuettel** [comment]
I am closing this as it is really a C++ language constraint.

**Comment by JorisGoosen** [comment]
Fair enough, thanks for your consideration anyhow.
