### ISSUE TITLE
RS.h - Rcpp or R 3.5.0?

### ISSUE THREAD

**Issue by brainprint** [RcppCore/Rcpp#848]
I am new to Rcpp. Trying to compile the program attached, I got an error from RS.h.

macOS Sierra, R 3.5.0.

I am not sure if it is related to Rcpp or R 3.5.0. Could you be kind to advise me on how to proceed?

`> Rcpp::sourceCpp('Rcpp/IrrGood.cpp')
In file included from /Library/Frameworks/R.framework/Resources/include/R.h:91:0,
                 from /Users/Normand/Library/R/3.5/library/Rcpp/include/Rcpp/r/headers.h:52,
                 from /Users/Normand/Library/R/3.5/library/Rcpp/include/RcppCommon.h:38,
                 from /Users/Normand/Library/R/3.5/library/Rcpp/include/Rcpp.h:27,
                 from IrrGood.cpp:2:
/Library/Frameworks/R.framework/Resources/include/R_ext/RS.h:55:17: error: expected unqualified-id before ')' token
 #define ERROR   ),error(R_problem_buf);}
                 ^
IrrGood.cpp:22:14: note: in expansion of macro 'ERROR'
 const double ERROR= 1e30;
              ^
/Library/Frameworks/R.framework/Resources/include/R_ext/RS.h:55:40: error: expected declaration before '}' token
 #define ERROR   ),error(R_problem_buf);}
                                        ^
IrrGood.cpp:22:14: note: in expansion of macro 'ERROR'
 const double ERROR= 1e30;
              ^
make: *** [IrrGood.o] Error 1
/usr/local/Cellar/gcc/7.3.0_1/bin/g++-7 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I"/Users/Normand/Library/R/3.5/library/Rcpp/include" -I"/Users/Normand/GB Brainprint/Brainprint/Codes/R/Rcpp" -I/usr/local/include   -fPIC  -Wall -g -O2  -c IrrGood.cpp -o IrrGood.o
Error in Rcpp::sourceCpp("Rcpp/IrrGood.cpp") : 
  Error 1 occurred building shared library.
In addition: Warning message:
No function found for Rcpp::export attribute at IrrGood.cpp:20 `
[Archive.zip](https://github.com/RcppCore/Rcpp/files/1956642/Archive.zip)

**Comment by eddelbuettel** [comment]
There are nine vignettes that ship with Rcpp; including two devoted to an introduction.  Please read at least on of those and and maybe replicate some of the examples.

**Comment by brainprint** [comment]
Thank you. I have already realized many of my mistakes.
