### ISSUE TITLE
Runtime type mismatch: throw error if NDBEUG is unset?

### ISSUE THREAD

**Issue by jackwasey** [RcppCore/Rcpp#857]
While debugging, I get runtime errors like:

> Not compatible with requested type: [type=character; target=integer]

Would it be possible for Rcpp to hard-stop, like C++ assert does, in the case that compilation uses `-UNDEBUG`? This would be useful for debugging with gdb or lldb, and give a line number in the source code where the problem was encountered.

**Comment by eddelbuettel** [comment]
Not sure. `assert()` and alike are frowned upon by CRAN Policy.

**Comment by jackwasey** [comment]
Yes, I think so, but they compile (and I believe default R installs, also) use -DNDEBUG, so what I imagined was just Rcpp-based package developers enabling it while debugging.

**Comment by eddelbuettel** [comment]
You could try with one or two and see -- some things "they" check are text based, some look at the shared library resulting from it.  I think you are correct in that this test is based on the shared library.

**Comment by jackwasey** [comment]
Ah, I see. Will take a look.

**Comment by eddelbuettel** [comment]
Fixed via #860
