### ISSUE TITLE
RcppExports.R not playing well with lintr style check

### ISSUE THREAD

**Issue by renkun-ken** [RcppCore/Rcpp#864]
`Rcpp::compileAttributes` automatically generates `R/RcppExports.R` in the following style:

```r
# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Test C++ function
#' @param x a numeric vector
#' @export
test_cpp <- function(x) {
    .Call('_pkgdemo_test_cpp', PACKAGE = 'pkgdemo', x)
}
```

Unfortunately, the single-quote does not play well with `lintr::lint_package()` which recommends "Only use double-quotes".

I'm wondering if it makes sense that double-quotes are used in `RcppExports.R` instead?

**Comment by kevinushey** [comment]
Can you instruct lintr to ignore this file?

**Comment by coatless** [comment]
@renkun-ken See [`lintr::exclude()`](https://rdrr.io/cran/lintr/man/exclude.html)

**Comment by renkun-ken** [comment]
Thanks! Excluding the file is of course a straightforward option.
