### ISSUE TITLE
Fail if missing update to ChangeLog / NEWS.Rd

### ISSUE THREAD

**Issue by coatless** [RcppCore/Rcpp#865]
Lots of PRs nowadays are lacking an update to  `inst/NEWS.Rd` +  `ChangeLog`. To address this, I recommend inserting a check in `.travis.yml` to see if there is a difference between these file on the PR branch and master, c.f. 

```bash
script:
  - |
    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
       ! (git diff --exit-code master -- inst/NEWS.Rd || git diff --exit-code master -- ChangeLog) 
    fi
  - ./run.sh run_tests
```

In short, we have:

```bash
git diff --exit-code master -- inst/NEWS.Rd
```

This returns 1 (FALSE), if a difference is present, and 0 (TRUE), if the same. Hence, we negate.  By placing the check before the unit tests, we can have a quicker "fail".

It may be advisable to add a [pull request template](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) that mentions this.

**Comment by eddelbuettel** [comment]
Not interested in added formalism.   I have been at this for a while, and some contributor do, some don't and forcing all to it will turn some away.
