### ISSUE TITLE
Package CHECK gives warning: ‘-Wno-unused-function’

### ISSUE THREAD

**Issue by SachaEpskamp** [RcppCore/Rcpp#870]
Dear Rcpp maintainers,

After years of working fine my package graphicalVAR (https://github.com/SachaEpskamp/graphicalVAR) suddenly gave these CRAN warnings:

```
checking compilation flags used ... WARNING
Compilation used the following non-portable flag(s):
  ‘-Wno-unused-function’ ‘-Wno-unused-variable’

```

Unfortunately, this led to the package being removed from CRAN, as I couldn't figure out how to remediate this problem. Do you have any idea what I could do?

Best, Sacha

**Comment by eddelbuettel** [comment]
That has been discussed many times on the lists, SO, and elsewhere.  Do two things:
- remove these flags from `src/Makevars{,win}` just as the check and warnings tell you to 
- add these flags to `~/.R/Makevars` which means _your builds_ will still use them

This would have been a good question for the `r-package-devel` list. It has zero to do with Rcpp.

**Comment by eddelbuettel** [comment]
(And the change is typically from new compiler versions which add more warnings. That is a _good thing_.)

**Comment by SachaEpskamp** [comment]
Thanks for your quick reply! I don't get it though, I don't have a file `src/Makevars{,win}` in my package?

**Comment by eddelbuettel** [comment]
The warnings are for your package, and come from analysing your package in isolation.  Where else would this be set?

**Comment by eddelbuettel** [comment]
Also, you are making a classic 'wrong context' mistake:
- the CRAN warnings come from the _last uploaded package_ and it clearly shows that you have them in 0.2.1
- you are looking at your GH repo which does not have them

Both states are happy to coexist :)   The error is in the former.

**Comment by SachaEpskamp** [comment]
Hm weird I don't get the warning if I use the terminal to R CMD CHECK but do get it inside RStudio. I'll try to look into it. Thanks for the quick replies!!
