### ISSUE TITLE
"No Rcpp::export attributes or RCPP_MODULE declarations found in source" with a extern

### ISSUE THREAD

**Issue by HaotianLin** [RcppCore/Rcpp#885]
-  #include <Rcpp.h>
-  using namespace Rcpp;
-  extern "C" double digamma(double);
-  //[[Rcpp::export]]
-  
-  RcppExport SEXP updatealpha_u(SEXP alphaut,

This is the head of my code, and when I want to use sourceCpp("updatealpha_u.cpp") to make this function into global environment, it comes out with this error.

-  > sourceCpp("/Users/lehostal/Desktop/summer research/COMPASS_Extent/updatealpha_u.cpp")
-  Warning message:
-  In sourceCpp("/Users/lehostal/Desktop/summer research/COMPASS_Extent/updatealpha_u.cpp") :
-    No Rcpp::export attributes or RCPP_MODULE declarations found in source

**Comment by jjallaire** [comment]
If I source the following file (on OS X) then I get no warnings or messages as you did:

```cpp
#include <Rcpp.h>
using namespace Rcpp;
extern "C" double digamma(double);
//[[Rcpp::export]]
RcppExport SEXP updatealpha_u(SEXP alphaut) {
  return R_NilValue;
}
```

You might need to give us a more complete minimal reproducible example?

**Comment by eddelbuettel** [comment]
As @jjallaire showed, you simply had your ordering wrong.

It is also prefereanle to use the mailing list, or StackOverflow, for simple usage questions.  And to include a [minimally reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example).
