### ISSUE TITLE
Outputs not wrapped automatically: double to NumericVector compiles but should not.

### ISSUE THREAD

**Issue by Jean-Romain** [RcppCore/Rcpp#889]
I encountered a weird issues in a C++ code partially written with C++ and regular STL. The simplest reproducible example is the following:

```cpp
#include <Rcpp.h>
using namespace Rcpp;
    
 // [[Rcpp::export]]
NumericVector f(double x) { return(x); }
```

It returns `c(0,0)`. I believed that `x` will be wrapped automatically but it is not. Trying the same with an `std::vector<double>`

```cpp
// [[Rcpp::export]]
NumericVector h(std::vector<double> x) { return(x); }
```

I got the following compilation error:

>  error: could not convert ‘x’ from ‘std::vector<double>’ to ‘Rcpp::NumericVector {aka Rcpp::Vector<14, Rcpp::PreserveStorage>}’

I suggest to add a compilation error for the first case as well.

**Comment by eddelbuettel** [comment]
I think you are mostly just misunderstand exactly what the header files do, and what is defined.  

The central key is the `SEXP` type that is key to all things R.  

Corected version below.

### Code

```c++
#include <Rcpp.h>
using namespace Rcpp;
    
 // [[Rcpp::export]]
NumericVector f(double x) { return(x); }

 // [[Rcpp::export]]
NumericVector fcorrect(double x) { return(wrap(x)); }

// [[Rcpp::export]]
NumericVector hcorrect(std::vector<double> x) { return(wrap(x)); }

/*** R
f(2)
fcorrect(2)
hcorrect(2)
*/
```

### Output

```
> Rcpp::sourceCpp("/tmp/gh.cpp")

> f(2)
[1] 0 0

> fcorrect(2)
[1] 2

> hcorrect(2)
[1] 2
> 
```
