### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [RcppCore/Rcpp#891]
I would like to point out that an identifier like “[`__P__`](https://github.com/RcppCore/Rcpp/blob/e1766bbe3912a7293580328a0d6a3196be2d5d7d/src/internal.h#L39 "Update candidate")” [does not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to [adjust your selection for unique names](https://github.com/RcppCore/Rcpp/issues/387 "Fix invalid C++ identifiers")?

**Comment by eddelbuettel** [comment]
It's only used in a preprocessor macro -- so it is not really an identifier.

**Comment by elfring** [comment]
[Parameter names are also identifiers](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?").
Would you like to rename them (any any remaining update candidates)?

**Comment by eddelbuettel** [comment]
I think nobody on the Rcpp Core feels as strongly about this as you, so I'd say no.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by eddelbuettel** [comment]
See https://www.stats.ox.ac.uk/pub/bdr/memtests/clang-UBSAN/Rcpp/00check.log

**Comment by eddelbuettel** [comment]
I'll leave it open for a few more days if other want to pitch in but I still see this as a non-issue.

**Comment by elfring** [comment]
Do you [care for questionable identifiers](https://en.cppreference.com/w/c/language/identifier#Reserved_identifiers "Description for reserved identifiers") any more [at other source code places](https://github.com/RcppCore/Rcpp/blob/b75bb7b5d0e99840b6dfe6113b965dd124e95ebf/src/Module.cpp#L166 "Update candidate: CppMethod__invoke()")?

**Comment by eddelbuettel** [comment]
I am locking this now.  I am not quite sure what your agenda is but would you consider moving on and playing in somebody else's backyard?  You made your point.

**Comment by eddelbuettel** [comment]
Nobody else from the Rcpp Core team had anything else to add so I am closing this.
