### ISSUE TITLE
Vignette about stats function

### ISSUE THREAD

**Issue by romainfrancois** [RcppCore/Rcpp#9]
This has been on the TODO for ages. I don't think it is likely to happen. Maybe we should just close this.

**Comment by coatless** [comment]
I think the `stats` functions being referred to are those inherited from `Rmath.h` that are accessible from `R::`? 

Per: 

http://dirk.eddelbuettel.com/code/rcpp/html/namespaceRcpp_1_1stats.html


If so, perhaps include part of the following gallery post?

http://gallery.rcpp.org/articles/random-number-generation/

**Comment by eddelbuettel** [comment]
I think this was a call for Sugar documentation or some such, and is carried over here from R-Forge. 

Can probably be closed.
