### ISSUE TITLE
License requirements for packages depending on Rcpp

### ISSUE THREAD

**Issue by swagatam11** [RcppCore/Rcpp#901]
Hello,
I am confused about a licensing issue, regarding packages which depend on Rcpp. Can you please help me understand this?
Specifically, I understand that Rcpp uses GPL 2. But I do not understand when must I use GPL 2 for a package which depends on Rcpp, and when can I use any other GPL compatible licenses. 

I have read the Rcpp FAQ, specially point 1.5, and I am not sure when is a package (which depends on Rcpp) considered a mere aggregation, and when is it considered "linking".
Perhaps some dependency types, (e.g., runtime dependencies) constitute derivative work, while others (e.g., "suggested" dependencies) are aggregation only? Or maybe there is a completely different way to resolve this?

I am new to this, so any suggestion or advice you can share will help me a lot.

Thank you very much for your time.

**Comment by eddelbuettel** [comment]
> when is a package (...) considered a mere aggregation, and when is it considered "linking".

That is the open question, and you may need a lawyer or court ruling on this.

Our interpretation, as written in the [Rcpp FAQ](https://cloud.r-project.org/web/packages/Rcpp/vignettes/Rcpp-FAQ.pdf), is that depending on Rcpp creates an aggregate work so that any _GPL-compatible_ license should do. 

But we are not lawyers, and don't claim to be.  If in doubt, consult a lawyer.  But also look at other examples:  as of today 1440 packages are on CRAN depending on Rcpp under a variety of licenses (that are all compatible as checked by CRAN).  (And of course if you do not distribute your code then you can do "whetever" as I (and others) have done for a decade....)

**Comment by swagatam11** [comment]
Thanks a lot for clarifying this. It helps a lot.

**Comment by eddelbuettel** [comment]
Glad to know it helped.  Suggested additions or clarifications to the Rcpp FAQ paragraph would be welcome.

**Comment by swagatam11** [comment]
Thanks again for your time.
I believe the FAQ may be clearer if one augments the following lines in section 1.5
"So you are free to license your work under whichever terms you find suitable (provided they are GPL-compatible, see the FSF site for details). However, the combined work will remain under the terms and conditions of the GNU General Public License"

by using this:

"So you are free to license your work under whichever terms you find suitable(provided they are GPL-compatible, see the FSF site for details). This is because in our view, simply depending on the Rcpp package does not constitute a derivative work, only an aggregation. However, the combined work, will remain under the terms and conditions of the GNU General Public License."

This will clarify your stand/ opinion to whoever reads it, more directly.

**Comment by eddelbuettel** [comment]
Well that's not what I said or meant.  I only said that what constiutes a derivative work is critically important, and unclear until courts rule. _Personally speaking I think linking does._ Other friends whose view I respect as more reserved.  In short, we do not know.

But what is neither unclear not disputed is that combining with GPL keeps the aggregate under GPL.  Your contribution can be any license (that is compatible) but the "whole" (ie your code, the Rcpp part and so) are an aggregation and hence under GPL.

**Comment by swagatam11** [comment]
Ah, I understand. Thank you for sharing your thoughts on this.
In this case, the FAQ is perfect. Of course, others who may have questions like me, will perhaps find our conversation here useful.
