### ISSUE TITLE
Matrix(no_init())

### ISSUE THREAD

**Issue by romainfrancois** [RcppCore/Rcpp#907]
The constructor does not set `nrows`. https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/vector/Matrix.h#L92

```cpp
    explicit Matrix( const no_init_matrix& obj) {
        VECTOR::set__( Rf_allocMatrix( RTYPE, obj.nrow(), obj.ncol() ) );
    }
```

I have a patch that I'll submit as a pull request.

**Comment by romainfrancois** [comment]
Is a thumbs up reaction enough green light to send the pull request ?

**Comment by kevinushey** [comment]
Do you recall why we maintain `nrows` as a variable separate to what's already defined as part of the `dims` attribute? Just for efficiency in lookup?

**Comment by romainfrancois** [comment]
IIRC this was about performance, i.e. implementing the `(` operator so that we can cheaply go from `i, j` to the underlying vector index.

**Comment by eddelbuettel** [comment]
I always liked how Armadillo exports this as read-only variables rather than calls: http://arma.sourceforge.net/docs.html#attributes

**Comment by kevinushey** [comment]
Sounds good. Either way this definitely warrants a patch; thanks for taking the time to prepare one.

**Comment by eddelbuettel** [comment]
And making sure it passes tests :)
