### ISSUE TITLE
Unable to give different names to R class and Cpp Class

### ISSUE THREAD

**Issue by nico-schmid** [RcppCore/Rcpp#909]
Since the latest changes of the package it is no more possible to name the R Class differently from the Cpp Class.

I'm wirting a package and use the  Rcpp package.
In particular I used the had 
```
#include <Rcpp.h>
#include "PkgFile.h"
using namespace PkgNamespace;

RCPP_MODULE(PkgModuleName) {
     using namespace Rcpp;
	class_<PkgNamespace::ClassA>("ClassA")
		.constructor()
		.constructor< std::vector<double>, std::vector<double>, int >()
		.property("prop1",  &PkgNamespace::ClassA::prop1, "Returns prop1 vector")
		.property("prop2", &PkgNamespace::ClassA::prop2, "la le lu info")
		.method("getValue", &PkgNamespace::ClassA::value, "la le lu info")
	;
	}
```
on the Cpp side and 
```
Rcpp::loadModule("PkgModuleName", what = "ClassA")
.ClassA <- setRcppClass(
  Class = ".ClassA",
  CppClass = "ClassA",
  module = "PkgModuleName",
  fields = c(
     remark = "character"
  )
)
ClassA <- function(prop1,prop2){
  tmpObj <- .ClassA()
  tmpObj$doSomething()
  return(tmpObj)
}

evalqOnLoad({
.ClassA$methods(
  doSomething = function(){
  # do something
  })
})

```
on the R side.
That worked fine, at least until Rcpp version 0.12.17. 
But since version 0.12.19 I get a error when trying to build my package, saying the ".ClassA" can't be found in modul "PkgModuleName" 
The only fix I found is to change the setRcppClass property  "class" form ".ClassA" to "ClassA" and hence to the same name as the cpp class.
Did I miss something or why was this changed? 

Best regards
Nico Schmid

**Comment by nico-schmid** [comment]
Thanks for the quick response.
...and yes of course you may... :)
I currently working on publishing the package on CRAN, which forced me to check the package with the latest version of dependencies. That was where the problem started... ;)

I tried to figure out what changes caused the problem and my best guess is, that it was the 
bugfixes for Rcpp::exposeClass #886 which was done in Juli this year. 
Since than the environment is now searched for CppClass instead of Class...
does nobody else reported problems with this change in behavior?
 
On the other hand I'm quite certain that it does not relate to the registration but I will try to double check that. In addition thanks for the hint with the leading underscore, but does this also makes the R object invisible to the user?

Again thanks for the answer!

**Comment by eddelbuettel** [comment]
> does nobody else reported problems with this change in behavior?

Correct. And I believe we have a unit test for RcppClasses too.

> does this also makes the R object invisible to the user

Of course not.  But Rcpp Attributes switches to a leading underscore and 1000+ CRAN packages use that (when they updated their RcppExports.{cpp,R}.
