### ISSUE TITLE
enum code generation

### ISSUE THREAD

**Issue by romainfrancois** [RcppCore/Rcpp#913]
Currently working with enums from some c++ code base is cumbersome and requires writing error prone boiler plate code in the R side, something like https://github.com/apache/arrow/blob/master/r/R/enums.R

```r
enum <- function(class, ..., .list = list(...)){
  structure(
    .list,
    class = c(class, "arrow-enum")
  )
}
FileMode <- enum("arrow::io::FileMode",
  READ = 0L, WRITE = 1L, READWRITE = 2L
)
```

Would be useful to have some code, perhaps as part of attributes that would scan the c++ code, e.g. https://github.com/apache/arrow/blob/c9ac8696a335f4e818c7356d9af77317150e94ce/cpp/src/arrow/io/interfaces.h#L36

```cpp
struct FileMode {
  enum type { READ, WRITE, READWRITE };
};
```

background: https://github.com/apache/arrow/pull/2714#discussion_r224546601

**Comment by wesm** [comment]
I think it would even be fine for Rcpp to generate constants like `FileMode_READ`. That's what we do in Cython: 

https://github.com/apache/arrow/blob/master/python/pyarrow/includes/libarrow.pxd#L35

**Comment by eddelbuettel** [comment]
Early morning here so maybe I am even slower than usual -- but what is it that are proposing?.  Namespace-scoped variables on the R side that map enums?  Presumably as immutable constants?  Any suggestion about how to go about it?  R doesn't really have the notion of a constant...

**Comment by romainfrancois** [comment]
Ideally the enum would be able to travel to the C++ functions so that we they can be used as Rcpp::export functions, in and out. 

There is limited support for this on the c++ side with a macro, but not on the R side where you essentially have to manually re create them.

**Comment by eddelbuettel** [comment]
So you are thinking of R side facilities to create enums on the C++ side?    Ie extending Attributes to generate something?

I was most often driven by the other side (and held back by the lack of support): I wanted what already exists in C++ (as enums) to be identifiers in R. Ie QuantLib has a ton of them, starting with simple ones like enumeration of the months etc.  We have nothing for that either.

**Comment by romainfrancois** [comment]
That’s the same use case. 

We have c++ enums in some headers that we interface, and want to get a handle on them at the r side. 

Having them in a list with an S3 class and the $ method on that list emitting something that has a class allowing it to be recognized on the c++ side, via inout parameter etc ...

**Comment by eddelbuettel** [comment]
Right on.  I have a feeling you and even talked about such use cases many moons ago.

**Comment by alexkyllo** [comment]
I stumbled upon this thread as I'm assessing effort needed to write R bindings for the [Z3 Theorem Prover](https://github.com/Z3Prover/z3)

Their approach with python bindings was to write a python script to read through the C++ headers, find all the enum members, and generate another python file declaring them as constants. This outputs a python file with hundreds of lines like this:
```python
# Automatically generated file

# enum Z3_lbool
Z3_L_FALSE = -1
Z3_L_UNDEF = 0
Z3_L_TRUE = 1

# enum Z3_symbol_kind
Z3_INT_SYMBOL = 0
Z3_STRING_SYMBOL = 1

# enum Z3_parameter_kind
Z3_PARAMETER_INT = 0
Z3_PARAMETER_DOUBLE = 1
Z3_PARAMETER_RATIONAL = 2
Z3_PARAMETER_SYMBOL = 3
Z3_PARAMETER_SORT = 4
Z3_PARAMETER_AST = 5
Z3_PARAMETER_FUNC_DECL = 6

```

I'll probably need to generate R code using the same approach for now--but in the future if Rcpp could provide a better way to do this, that would be awesome!
