### ISSUE TITLE
Using of move semantics in `as<T>` and `ReferenceInputParameter`

### ISSUE THREAD

**Issue by SylvainCorlay** [RcppCore/Rcpp#923]
Currently, the constructor of e.g. `ReferenceInputParameter<T>` initializes the internal `T obj` with the following member initialization `: obj( as<T>(x_) ){}`. Since `as<T>` returns a `T` by value, this causes the copy constructor to be called.

 ```cpp
template <typename T>
class ReferenceInputParameter {
public:
    typedef T& reference ;
    ReferenceInputParameter(SEXP x_) : obj( as<T>(x_) ){}
    inline operator reference() { return obj ; }
private:
    T obj ;
} ;
```

In simple cases, this copy construction may be optimized out by the compiler through copy elision, but not always. This would probably be more efficient if `as<T>` returned an rvalue reference on T.

At the moment, we can circumvent this by specializing `ReferenceInputParameter` for our types, but we thought it was worth reporting upstream.

**Comment by eddelbuettel** [comment]
Salut @SylvainCorlay -- we do specialise for C++11 in some spot so we could. Or can you think of a way to get this done in C++98?  

Clean PRs always appreciated :)
