### ISSUE TITLE
Use ISO C90 comments

### ISSUE THREAD

**Issue by ms609** [RcppCore/Rcpp#924]
`devtools` v1.2 now defaults to using `-pedantic`.  My compiler now throws an error

`warning: C++ style comments are not allowed in ISO C90`

when it encounters a comment prefixed with `//`.  The syntax `/* comment */` does not throw this error.

Affected files in the Rcpp library include

- RcppCommon.h
- Rcpp.h

Is it possible to replace //comments  with /* comments */ in these files, to avoid these pedantic errors?  I'd be happy to to put together a pull request if helpful, but thought I'd check whether there would be reasons not to do this first.

**Comment by ms609** [comment]
Many thanks for the suggestion; I'll take this advice.
Cheers.

**Comment by eddelbuettel** [comment]
My pleasure. I think the real issue, if any, is the C90 to C++ crossover.  You can also try to avoid C90 by imposing a C standard, and I believe the manual may even suggest that.   Compilers keep getting newer -- my laptop now has `gcc/g++` 8.2.* as default where C++ is automagically C++14.  CRAN itself moved forward to C++11 but AFAIK C is still at the older one.  I could be wrong -- I don;t have that many C-only project so I did not cross that bridge.

And longer term we can of course normalise the comments but so far they are totally legit in C++ -- and this is after all a C++ package.
