### ISSUE TITLE
Extra copy in `Rcpp::traits::Exporter::get`.

### ISSUE THREAD

**Issue by SylvainCorlay** [RcppCore/Rcpp#925]
Currently, the constructor of `Exporter<T>` trait initializes an internal `T` obj which is returned by value in `get()` which causes a copy of the object.

In simple cases, this copy may be cheap but not always. This would probably be more efficient if a SEXP was stored internally like some other specialization of `Exporter` and the T instance was built upon call of `get()`.

At the moment, we can circumvent this by specializing Exporter for our types, but we thought it was worth reporting upstream.

**Comment by SylvainCorlay** [comment]
I think this should remain open!

**Comment by SylvainCorlay** [comment]
I see that @romainfrancois mentioned this issue. (Sorry I missed the ping.)

**Comment by eddelbuettel** [comment]
Good PRs are always welcome.  Maybe you can contribute one, sounds like you already have related code?

**Comment by kevinushey** [comment]
The relevant code lives here:

https://github.com/RcppCore/Rcpp/blob/a78885679cbcd4ebca63c24b1d04fa928c373b72/inst/include/Rcpp/internal/Exporter.h#L28-L36

It seems like it would be relatively straight-forward to defer construction of the `T` to when `get()` is first invoked. Or, we could have something like `defer = true` as a constructor argument to control that behavior if desired.

Agree that PRs are welcome.
