### ISSUE TITLE
update quick ref vignette

### ISSUE THREAD

**Issue by dongzhuoer** [RcppCore/Rcpp#932]
1. `Named[]` should be `Named()`  in last statement of "Create simple vectors" card, see #929
2. `glob.ls()` need a bool argument in "Retrieve information from environment" section of "Environment" card, see #930
3. add definition for `glob` in Environment" card, see #931

**Comment by eddelbuettel** [comment]
STOP now.

**Comment by dongzhuoer** [comment]
I'm writing

**Comment by eddelbuettel** [comment]
Nice catch re `glob`.  I think this would make sense:

```r
R> cppFunction("CharacterVector foo() { Environment glob=Environment::global_env(); return glob.ls(true); }" )
R> foo()
[1] ".Random.seed" "foo"
R> 
```

So how about you prepare a new (single) PR with the three suggested changes as well as a ChangeLog entry with your name and email?

**Comment by eddelbuettel** [comment]
@dongzhuoer Are you going to prepare a new PR now that we settled on these three changes in one submission?  Else I can make the change directly too.  Let us know.

**Comment by dongzhuoer** [comment]
Sorry, I'm a graduate student. I was busy doing homework a few days ago.

I issue #933, we can discuss there.
