### ISSUE TITLE
Rccp and C++ Atomics - question

### ISSUE THREAD

**Issue by heff001** [RcppCore/Rcpp#936]
Hi All, Can someone please let me know what C++ atomic types and objects are available / accepted / transformed in Rcpp? I thank you. I want to use Rcpp from now on; MS Visual C++ is dreadful.

**Comment by eddelbuettel** [comment]
You can use whatever your C++ compiler supports. But see _Writing R Extensions_ about doing it portably.

The interface to R that Rcpp and other use is constrained to being a C interface over the basic R types we cover --but once you are in C++ you can do whatever language elements you like.
