### ISSUE TITLE
Codecov uploads not working

### ISSUE THREAD

**Issue by rstub** [RcppCore/Rcpp#941]
On https://codecov.io/github/RcppCore/Rcpp?branch=master one sees no test coverage reports uploaded in the last 6 months. I guess this happened when Travis CI was changed to use docker containers. I recently had the same problem and solved it like this:

* Go to the codecov.io settings page (should be https://codecov.io/github/RcppCore/Rcpp/settings) and take note of the "Repository Upload Token".
* Go to the travis-ci.org settings page (should be https://travis-ci.org/RcppCore/Rcpp/settings) and create a new environment variable `CODECOV_TOKEN` with that value.
* Pass the token value from the environment into the docker container by adding `-e  CODECOV_TOKEN` to the docker arguments when calling `covr::codecov()`.

**Comment by eddelbuettel** [comment]
Indeed, I had left that open.  Will look into this -- thanks for the detailed suggestion.

**Comment by eddelbuettel** [comment]
@rstub Looks like it broke again. I'm at a loss as to why. Any idea?

**Comment by rstub** [comment]
At first glance it looks like coverage dropped when you changed the version to 1.0.1. I remember that some tests don’t run on CRAN, ie not for releases. Is there a way to force execution of the tests even for three digit release numbers?

**Comment by eddelbuettel** [comment]
Hm, but that test for 'is it a three digit release' has been there forever and has not changed

https://github.com/RcppCore/Rcpp/blob/0837b3557ea3a50c8a9e350622da0f871dda5240/tests/doRUnit.R#L46-L53

Plus we have the environment variable to override

https://github.com/RcppCore/Rcpp/blob/0837b3557ea3a50c8a9e350622da0f871dda5240/docker/ci/Dockerfile#L25

**Comment by eddelbuettel** [comment]
But on reflection, I think you are spot on.  "1.0.1" is a release version that turns tests off at CRAN, it does so here (by accident) so the setting in the Dockerfile simply does not work.  I may need another check for a Travis environment variable in `tests/doRUnit.R`.

**Comment by rstub** [comment]
Maybe `covr` does not make use of `~/.R/check.Renviron`? If that is the case, you could use `ENV  RunAllRcppTests=yes` within the `Dcokerfile` instead.

**Comment by eddelbuettel** [comment]
Yes I now suspect that `covr` / Travis runs as a different user to `~` aka `$HOME` is somewhere else.

But again, well spotted. I was so focussed on 'why does coverage not run' that I did not realize that the related 'hm jobs only take 8 mins instead of around 15 mins' was the driver.  Should be better now as I altered the test driver in `~/tests/`.

**Comment by eddelbuettel** [comment]
Now committed.  

When I wrote the comment above I had it written here but not yet pushed so you couldn't have seen that :)
