### ISSUE TITLE
Rcpp::sample memory issue

### ISSUE THREAD

**Issue by pcubre** [RcppCore/Rcpp#944]
When calling Rcpp::sample multiple times, it uses more memory than expected.  In EmpiricalSample there is an R_alloc causing the issue.

`void foo(int x) {
  for(int i = 0; i < 1e7; i++){
    Rcpp::sample(x, 2, false, R_NilValue, false);
  }
}
foo(250);
`

**Comment by kevinushey** [comment]
What do you mean by "it uses more memory than expected" -- do you mean something like a memory leak?

My understanding is that R reclaims any `R_alloc()` memory is freed by R automatically after exiting the current `.Call()` function so there shouldn't be any issue there.

**Comment by pcubre** [comment]
In my use case, a Monte Carlo simulation, I do not return to R before all memory is consumed.

**Comment by eddelbuettel** [comment]
That is still a little on the vague side.  In _Writing R Extension_ it is shown how to do memory profiling.  It would this discussion if you could show us some actual bad behaviour in a reproducible example as we currently have very little to go by.   

Now, there are occassional instability between R and external functions.  In essence, calling a dynamically loadable function 1e7 times makes it somewhat likely something may go wrong as a subtle data race may be manifested somewhere.  But this is a 10 year old project, and that very aspect was refined several times.  We are not aware of a fixable issue -- that does not mean it is bug free.  But your report simply does not yet help anyone making things better.

Also, recall that we _are_ using R memory, and that gets recycled only by R's garbage collection which may require multiple sweeps.  It could be that your expectations are misplaced.

**Comment by kevinushey** [comment]
@pcubre then I think you need to manually call `vmaxget()` and `vmaxset()` as needed when you need to force R to reclaim this memory.

**Comment by pcubre** [comment]
'#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
void foo(int x) {
  for(int i = 0; i < 1e7; i++){
    IntegerVector temp = Rcpp::sample(x,2,false, R_NilValue, true);
  }
}

/*** R
memory.size()
Rprofmem("Rprofmem.out", threshold = 100)
foo(250)
Rprofmem(NULL)
noquote(readLines("Rprofmem.out", n = 5))
memory.size()
gc()
*/'

My Console output
> memory.size()
[1] 75.3

> Rprofmem("Rprofmem.out", threshold = 100)

> foo(250)

> Rprofmem(NULL)

> noquote(readLines("Rprofmem.out", n = 5))
[1] 1056 :".Call" "foo" "eval" "eval" "withVisible" "source" "<Anonymous>" 
[2] 1056 :".Call" "foo" "eval" "eval" "withVisible" "source" "<Anonymous>" 
[3] 1056 :".Call" "foo" "eval" "eval" "withVisible" "source" "<Anonymous>" 
[4] 1056 :".Call" "foo" "eval" "eval" "withVisible" "source" "<Anonymous>" 
[5] 1056 :".Call" "foo" "eval" "eval" "withVisible" "source" "<Anonymous>" 

> memory.size()
[1] 10373.33

> gc()
          used (Mb) gc trigger   (Mb)   max used   (Mb)
Ncells  727356 38.9   11162294  596.2   15258601  814.9
Vcells 1428253 10.9 1023221826 7806.6 1263048167 9636.3`

**Comment by eddelbuettel** [comment]
I fear you may have the wrong mental model of R works.  There is no reason the (non-portable and only-on-Windows) `memory.size()` would have to show the same number before and after.

In short, I still see no issue here.
