### ISSUE TITLE
R 3.6.x Update for Sample Sugar Functions

### ISSUE THREAD

**Issue by coatless** [RcppCore/Rcpp#945]
Similar to RcppCore/RcppArmadillo#250, the implementation of the `sample()` functions in _Rcpp_ need to be updated for R 3.6.x.

So, likely this will need a patch that mirrors what is available in _Base R_. c.f. Implementation changes.

- [Rejection sampling routine](https://github.com/wch/r-source/commit/e4f28798df4c9412ce4cb40333a30ef5b0ad1dec)
- [Implementation of `R_unif_rand()` in existing _R_ code](https://github.com/wch/r-source/commit/e4acfd1f240a42b3fc1474a4d97017114e4eb053)
- [Walker sampling changes](https://github.com/wch/r-source/commit/9a65c8381f86db2215fb2e76af402aef25ed135b)

**Comment by eddelbuettel** [comment]
As discussed over slack, in favour, and especially if we can combine the work between Rcpp and RcppArmadillo (which has similar code that came earlier).
