### ISSUE TITLE
Can `sort_unique()` pass along the `decreasing` argument to `sort()`?

### ISSUE THREAD

**Issue by DavisVaughan** [RcppCore/Rcpp#950]
It looks like `sort_unique()` is simply `unique(x).sort()`, as shown [here](http://dirk.eddelbuettel.com/code/rcpp/html/namespaceRcpp.html#a47ab8d30a152cd824a5e63a6d9046af1). Would it be possible to expose the `decreasing` argument of [`sort()`](http://dirk.eddelbuettel.com/code/rcpp/html/classRcpp_1_1Vector.html#a88c8e717a758626ad5150a2e0324d247) to `sort_unique()`? I can call both separately to do this, but it seems useful to wrap the pattern completely.

**Comment by eddelbuettel** [comment]
Yes, looks like an oversight we can fix.  

Maybe wait a day or three before PRing as I am trying to get 1.0.1 out of the door but I am seriously short of resources for the rev.dep.   So patience is a virtue.

**Comment by DavisVaughan** [comment]
Sure, I put it on my calendar to work on a week from now. I'll be out a bit next week. Thanks

**Comment by eddelbuettel** [comment]
Clised in #958
