### ISSUE TITLE
.clang-format filename is incorrect

### ISSUE THREAD

**Issue by jimhester** [RcppCore/Rcpp#957]
The file (added in https://github.com/RcppCore/Rcpp/pull/318) should be called `.clang-format` not `.clang_format`. The `clang-format` program only reads [`.clang-format` or `_clang-format`](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#configuring-style-with-clang-format), so the settings in the file are currently being ignored.

See the difference in the old and new configs when I dump them after renaming the file.

```shell
> clang-format -dump-config > old
> mv .clang_format .clang-format
> clang-format -dump-config > new
> diff old new
3,4c3
< # BasedOnStyle:  LLVM
< AccessModifierOffset: -2
---
> AccessModifierOffset: -4
74c73
< IndentWidth:     2
---
> IndentWidth:     4
95c94
< PointerAlignment: Right
---
> PointerAlignment: Left
99c98
< SpaceAfterCStyleCast: false
---
> SpaceAfterCStyleCast: true
108c107
< SpacesBeforeTrailingComments: 1
---
> SpacesBeforeTrailingComments: 2
114,115c113,114
< Standard:        Cpp11
< TabWidth:        8
---
> Standard:        Cpp03
> TabWidth:        4
```

**Comment by jimhester** [comment]
Oh wait, I may have been using an older version of Rcpp locally, I think this has already been fixed.

**Comment by eddelbuettel** [comment]
And fwiw the file is unused.  We have no enforced rule of formating.  I like [editorconfig](https://editorconfig.org/) as an opt-in.
