### ISSUE TITLE
Use of C++ in Packages

### ISSUE THREAD

**Issue by waynelapierre** [RcppCore/Rcpp#962]
I saw this article and would like to know how Rcpp developers think of it
https://developer.r-project.org/Blog/public/2019/03/28/use-of-c---in-packages/index.html

**Comment by eddelbuettel** [comment]
There were several threads with follow-up on
- the r-devel list starting at https://stat.ethz.ch/pipermail/r-devel/2019-March/077560.html
- the rcpp-devel list starting at http://lists.r-forge.r-project.org/pipermail/rcpp-devel/2019-April/010310.html

Please read those threads. Rcpp Core member @kevinushey participated in both and shared some of our views.
