### ISSUE TITLE
Turning off `Rcpp::RNGScope` in RcppExports.cpp

### ISSUE THREAD

**Issue by DavisVaughan** [RcppCore/Rcpp#964]
Question) Can we turn off the automatically inlined `Rcpp::RNGScope rcpp_rngScope_gen;` in `RcppExports.cpp` if we know we don't need it?

Consider the simple example:

```cpp
#include <Rcpp.h>

// [[Rcpp::export]]
void example() {
}
```

Every time `example()` is called, you get `2.49kb` of allocation and it takes around 1-2us.

``` r
bench::mark(example(), iterations = 100000)
#> # A tibble: 1 x 10
#>   expression   min   mean median    max `itr/sec` mem_alloc  n_gc n_itr
#>   <chr>      <bch> <bch:> <bch:> <bch:>     <dbl> <bch:byt> <dbl> <int>
#> 1 example()  679ns 2.08µs 1.08µs 32.5ms   481597.    2.49KB     9 99990
#> # … with 1 more variable: total_time <bch:tm>
```

Looking at medians, this seems to scale a bit linearly at around 500ns per call, and you can clearly see the memory allocation there.

```cpp
#include <Rcpp.h>

// [[Rcpp::export]]
void example2() {
  Rcpp::RNGScope rcpp_rngScope_gen;
}

// [[Rcpp::export]]
void example3() {
  Rcpp::RNGScope rcpp_rngScope_gen;
  Rcpp::RNGScope rcpp_rngScope_gen2;
}
```

``` r
Rcpp::sourceCpp("~/Desktop/test.cpp")
bench::mark(example2(), iterations = 1000000)
#> # A tibble: 1 x 10
#>   expression    min   mean median    max `itr/sec` mem_alloc  n_gc  n_itr
#>   <chr>      <bch:> <bch:> <bch:> <bch:>     <dbl> <bch:byt> <dbl>  <int>
#> 1 example2() 1.19µs 2.16µs 1.59µs 13.6ms   462173.    4.98KB   101 999898
#> # … with 1 more variable: total_time <bch:tm>
bench::mark(example3(), iterations = 1000000)
#> # A tibble: 1 x 10
#>   expression    min   mean median   max `itr/sec` mem_alloc  n_gc  n_itr
#>   <chr>      <bch:> <bch:> <bch:> <bch>     <dbl> <bch:byt> <dbl>  <int>
#> 1 example3() 1.67µs 2.34µs 2.22µs 102µs   426602.    7.48KB   161 999839
#> # … with 1 more variable: total_time <bch:tm>
```

I know it's a very minor allocation / time, but I think it would be useful to opt out of it if possible.

**Comment by eddelbuettel** [comment]
See the corresponding vignette (sources) at 
https://github.com/RcppCore/Rcpp/blob/6062d561939e72a9a6bbf0d0b3a2311374be3552/vignettes/Rcpp-attributes.Rmd#L335-L364

so `rng=false` is your new best friend.  Send me a copy of the novel you'll be writing in all those 500ns increments you save.

**Comment by DavisVaughan** [comment]
Just found that myself after some more searching. Thanks!

**Comment by eddelbuettel** [comment]
```r
R> microbenchmark::microbenchmark(yes(), no())
Unit: nanoseconds
  expr  min   lq    mean median   uq     max neval
 yes() 1084 1329  9716.8 1502.5 1729  792520   100
  no()  194  206 11116.5  223.5  297 1081985   100
R> 
```

based on 

```c++
#include <Rcpp.h>

// [[Rcpp::export]]
void yes() {
}

// [[Rcpp::export(rng=false)]]
void no() {
}
```

and I verified via `sourceCpp("....file here...", verbose=TRUE)` that the code behaves as expected and omits that instantiation in the `no()` case.

**Comment by DavisVaughan** [comment]
Yes I have checked it myself as well and it works for me. I had looked at `?Rcpp::exportAttribute` but it wasn't mentioned there so I didn't know it existed.

**Comment by eddelbuettel** [comment]
I started from the code generator, saw that it was in fact conditional and also had to remind myself about how that gets turned on ...    It's a big package with a lot of nooks and crannies.
