### ISSUE TITLE
Could `Rcpp::stop()` get `include_call = true` as an argument?

### ISSUE THREAD

**Issue by DavisVaughan** [RcppCore/Rcpp#965]
I see how `Rcpp::stop()` works here
https://github.com/RcppCore/Rcpp/blob/f3c5a34e06e774532227470b01c63a8f08ce4313/inst/include/Rcpp/exceptions/cpp98/exceptions.h#L126

Would it be possible to add `bool include_call = true` to the end of each template implementation and pass that on to `Rcpp::exception()`? Would that be a non-invasive change?

I see I could set `RCPP_DEFAULT_INCLUDE_CALL` but I don't think I love that idea.
https://github.com/RcppCore/Rcpp/blob/2f72ff884b4d9d078250cd52b9c121df28915142/inst/include/Rcpp/exceptions.h#L37 

I could also make my own `stop()` on top of `Rcpp::exception()` but I'd hate to have to copy/paste all that boilerplate from `Rcpp::stop()`, and appreciate that it already formats string input for me.

**Comment by coatless** [comment]
@DavisVaughan I don't think that's possible due to how we are obtaining the parameters. The best option would be setting the `RCPP_DEFAULT_INCLUDE_CALL` define.

**Comment by eddelbuettel** [comment]
It's also "fairly recent" code from #868, maybe start by reviewing that discussion?

**Comment by DavisVaughan** [comment]
Gotcha, I see now how that won't work especially with the cpp11 variadic template argument
https://github.com/RcppCore/Rcpp/blob/f3c5a34e06e774532227470b01c63a8f08ce4313/inst/include/Rcpp/exceptions/cpp11/exceptions.h#L51
