### ISSUE TITLE
[Feature request] use eigs_gen in rcpp scripts

### ISSUE THREAD

**Issue by pachamaltese** [RcppCore/Rcpp#969]
how can I contribute to be able to use eigs_gen (http://arma.sourceforge.net/docs.html#eigs_gen) in rcpp scripts?

**Comment by eddelbuettel** [comment]
What do you mean by 'rcpp sripts' ?  It already works -- see the example quicky wrapped around the example in the docs by @conradsnicta ...

#### Code

```c++
#include <RcppArmadillo.h>
using namespace arma;

// [[Rcpp::depends(RcppArmadillo)]]

// [[Rcpp::export]]
void foo() {

  // generate sparse matrix
  sp_mat A = sprandu<sp_mat>(1000, 1000, 0.1);

  cx_vec eigval;
  cx_mat eigvec;

  eigs_gen(eigval, eigvec, A, 5);  // find 5 eigenvalues/eigenvectors
  Rcpp::Rcout << eigval;
}

/*** R
foo()
*/

```

#### Output

```r
R> Rcpp::sourceCpp("/tmp/eigs_gen.cpp")

R> foo()
    (+5.009e+01,+0.000e+00)
    (-5.696e+00,+0.000e+00)
    (-3.591e+00,+4.362e+00)
    (-3.591e+00,-4.362e+00)
    (-1.139e+00,+5.434e+00)
R> 
```

**Comment by pachamaltese** [comment]
it's not you, it's me... I tried your example and I assume I have a problem with my setup, as your example doesn't work here either :(

**Comment by coatless** [comment]
@pachamaltese fyi, this should be filed against the [`RcppArmadillo`](https://github.com/rcppcore/rcpparmadillo) package. 

Are you on a mac? If so, read over the [toolchain requirements](http://thecoatlessprofessor.com/programming/r-compiler-tools-for-rcpp-on-macos/).

**Comment by pachamaltese** [comment]
I have the package. And yes, I'm using a mac without much success.

**Comment by eddelbuettel** [comment]
I am going to close this.  The Rcpp-on-macOS requirements, including the RcppArmadillo ones for `gfortran` and OMP, are well documented.  The package is not at fault, macOS may well be.
