### ISSUE TITLE
functions work on Linux, fails on Windows

### ISSUE THREAD

**Issue by FBartos** [RcppCore/Rcpp#971]
Hi,

I've written a function that works perfectly on a Linux server while crashes on Windows. There is no problem during sourcing, but it crashes (closes the r-session or causes fatal-error in Rstudio) when being called. I tried reinstalling R, Rtools, Rcpp, even the whole system, and it's not working on a different windows computer either, It completely crashes the console with no traceback or information and I've no idea what to do.

I managed to find Windows error reporting files, but I have no idea what the content means.
[error_logs.zip](https://github.com/RcppCore/Rcpp/files/3294331/error_logs.zip)

And there is the code:
[ZcurveEM.txt](https://github.com/RcppCore/Rcpp/files/3294337/ZcurveEM.txt)

It can be run by:
ZcurveEM_Cpp(rnorm(300,3))

**Comment by eddelbuettel** [comment]
I am truly sorry but are not a debugging service for your code.  Maybe try StackOverflow or the code review side at Stack Exchange.

Unless you substantiate this with a [minimally complete verifiable example](https://stackoverflow.com/help/minimal-reproducible-example) about Rcpp, I will have to close this.

**Comment by FBartos** [comment]
> I am truly sorry but are not a debugging service for your code. Maybe try StackOverflow or the code review side at Stack Exchange.
> 
> Unless you substantiate this with a [minimally complete verifiable example](https://stackoverflow.com/help/minimal-reproducible-example) about Rcpp, I will have to close this.

I see, I'm sorry, I will break it down and re-submit in a clearer form.

**Comment by eddelbuettel** [comment]
It is very likely still a vanilla bug, and yes, you will have to chase by getting to a more minimal example.  Sadly even after decades of software engineering there is no better automated way.
