### ISSUE TITLE
github language classification for Rcpp is C, not R

### ISSUE THREAD

**Issue by apsteinmetz** [RcppCore/Rcpp#973]
Minor annoyance, but if you use the Github API to find repos named  Rcpp in the R language this package does not come up because Github knows the language to be C++.  Can it, should it, be fixed?

**Comment by eddelbuettel** [comment]
I think it can (I recall reading about a hinter, and I may have used on in another one or two of my repos) but it really is two-sided.  That 'lines of code in repo' classification should probably be C or C++ for Rcpp as that is how the package is built: it contains a boatload of C++ code, and less R code.

Also not that the 'tag'  (under 'manage topics') does have 'r' as well as 'c-plus-plus'.  So I'd be inclined to leave it as is.

Then again your search argument has merit...

**Comment by eddelbuettel** [comment]
Yes I used what is described [here](https://github.com/github/linguist) to exclude parts of repos from the count.  That doesn't apply here.  Not sure if there is an overall override.
