### ISSUE TITLE
Rcpp Errror

### ISSUE THREAD

**Issue by Kamel20** [RcppCore/Rcpp#974]
Hello everyone,
I am trying to speed up my code by using Rcpp, the last function in this code (myModel) makes a problem for me, when I compile the code, I get this error,
1. cannot convert 'SEXP {aka SEXPREC*}' to 'Rcpp:traits::input_parameter::{aka Rcpp::InputParameter}' in initialization
2. cannot convert 'Rcpp::traits::input_parameter::type{aka Rcpp::InputParameter}' to 'double*' for argument '3' to double myModel(double, int, double*, int)
could anyone helps me for that,
```
#include <Rcpp.h>
#include <math.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include
using namespace Rcpp;
// Place the export tag right above function declaration.
// [[Rcpp::export]]
double FactorialC(int n)
{
int ii;
double prod;
if(n==0) return 1;
if(n==1) return 1;
prod=1.0;
for(ii=n; ii>0; ii--) prod *= ii;
return prod;
}
// [[Rcpp::export]]
double PoissonKC(double mu, int n)
{
double prob;
if(n==0) return (exp(-1.0*mu));
prob = (exp(-1.0*mu)*pow(mu,n))/FactorialC(n);
return prob;
}
// [[Rcpp::export]]
double myModel(double d, int m, double Vin, int flag){
double Vout, mu, probk;
int kk, jj, H,R;
Vout = (double) calloc(m+1, sizeof(double));
mu = 2(m+1)*d;
for(kk =0; kk<= 50; kk++){
probk = PoissonKC(mu, kk);
for(jj =0; jj<=m; jj++){
  if(kk>0){
    H = (jj + kk)/(m+1);
    R = (jj + kk)%(m+1);
    if(H >0){
      Vout[R] += 0.5*Vin[jj]*probk;
    }
    else{
      if(flag == 2) Vout[R] += Vin[jj]*probk;
    }
  }
  else{
    if(flag == 2) Vout[jj] += Vin[jj]*probk;
  } 
}
}
Vout;
}
```

**Comment by eddelbuettel** [comment]
Please follow the link in the edit box to learn about formatting.  It is not hard.  See other questions or issue tickets where you drop into edit mode.  Thank you.

**Comment by kevinushey** [comment]
> cannot convert 'Rcpp::traits::input_parameter::type{aka Rcpp::InputParameter}' to 'double*' for argument '3' to double myModel(double, int, double*, int)

This does not match the code you copied here. The error suggests that your function accepts a `double*` parameter (pointer to `double`), but the code you copied just uses a plain `double`.

I'm guessing that Rcpp Attributes does not understand how to marshal to `double*`. But the solution here is pretty simple: just use `NumericVector` instead, or pass a `SEXP` and get the data pointer with e.g. `REAL(data)`.

**Comment by eddelbuettel** [comment]
There is no real issue with Rcpp here -- you just need to learn a little about how to use it.  Please see the [Rcpp Gallery](http://gallery.rcpp.org)  (and if needed reset some links to http, as https it does not always render right) and maybe also the mailing list archives as well as StackOverflow.
