### ISSUE TITLE
Modules suddenly not loading anymore

### ISSUE THREAD

**Issue by david-cortes** [RcppCore/Rcpp#976]
I don’t know how to reproduce the error. But roughly speaking, I was compiling some test packages with RCPP_MODULE exposes classes, which at some point failed to compile and left the `.lock` file in my R folder. After deleting that, I cannot get any package with Rcpp modules to work.

E.g. if I create an example module
```r
Rcpp::Rcpp.package.skeleton("mod4", path="/home/me/mypath", module = TRUE)
```

then compile it, generating necessary files along the way, e.g. RcppExports.cpp
```cpp

RcppExport SEXP _rcpp_module_boot_NumEx();
RcppExport SEXP _rcpp_module_boot_yada();
RcppExport SEXP _rcpp_module_boot_stdVector();

static const R_CallMethodDef CallEntries[] = {
    {"_mod4_rcpp_hello_world", (DL_FUNC) &_mod4_rcpp_hello_world, 0},
    {"_rcpp_module_boot_NumEx", (DL_FUNC) &_rcpp_module_boot_NumEx, 0},
    {"_rcpp_module_boot_yada", (DL_FUNC) &_rcpp_module_boot_yada, 0},
    {"_rcpp_module_boot_stdVector", (DL_FUNC) &_rcpp_module_boot_stdVector, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_mod4(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
```
zzz.R
```r
loadModule("NumEx", TRUE)
loadModule("yada", TRUE)
loadModule("stdVector", TRUE)
```

then
```r
library(Rcpp)
library(mod4)
loadModule("yada", TRUE)
a = new("yada")
```

I get
```
Error in getClass(Class, where = topenv(parent.frame())) : 
  “yada” is not a defined class
```

If I try
```r
a = Module("yada")
a$<autocomplete>
```

Then I get
```
Error in Module(module, mustStart = TRUE) : 
  Failed to initialize module pointer: Error in FUN(X[[i]], ...): no such symbol _rcpp_module_boot_yada in package .GlobalEnv
```

(This is despite that the necessary export is right there in `RcppExports.cpp`)

Issue affects all packages. Already tried reinstalling Rcpp.

**Comment by eddelbuettel** [comment]
Sorry for delated reply, currently at useR.  It might be worthwhile splitting off the package creation with the `package.skeleton` which (if I recall correctly) had been seen to have problem with modules -- something may have changed when registration was added in NAMESPACE.  

In general, Rcpp Modules still works. I just re-checked one of the CRAN packages using it.  So please try poking around and maybe consider setting up your package differently.

**Comment by riccardoporreca** [comment]
@david-cortes, `Rcpp.package.skeleton()` uses the preferred way of loading modules via `loadModule()`

https://github.com/RcppCore/Rcpp/blob/d04eae80562c8933a484d095309af3b47bc041f8/inst/skeleton/zzz.R#L12-L14

The C++ functions and classes defined inside the modules are exported and readily available in hte package namespace, w/o the need for any extra `Module(yada)` or `new("yada")` (which I guess are relevant for different usages).

https://github.com/RcppCore/Rcpp/blob/d04eae80562c8933a484d095309af3b47bc041f8/inst/skeleton/rcpp_module.cpp#L60-L83

Therefore you can simply go for
```r
library(mod4)
hello()
bla()
bla1(42)
bla2(42, 0.42)
bar()
bar(10)
foo()
foo(5)
foo(3, 9)

w <- World$new()
w$greet()
w$set("hohoho")
w$greet()
```

**Comment by riccardoporreca** [comment]
@eddelbuettel, I was actually quickly cross-checking the [Rcpp-modules](https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-modules.pdf) vignette, and it could be causing some confusion w.r. to e.g. calling `Module()`

https://github.com/RcppCore/Rcpp/blob/d04eae80562c8933a484d095309af3b47bc041f8/vignettes/Rcpp-modules.Rmd#L356-L364

I admit though that I have only used Rcpp modules inside packages in a pretty standard way, and never bothered with `Module()`.

It might be worth having a similar comment to 

https://github.com/RcppCore/Rcpp/blob/d04eae80562c8933a484d095309af3b47bc041f8/vignettes/Rcpp-modules.Rmd#L1136-L1137

from section _Deprecated older method using loadRcppModules_ also in the section _Preferred current method using loadModule_.

**Comment by david-cortes** [comment]
@riccardoporreca  : Thanks! that worked. Although, I still find it problematic that for some reason the methods specified in the vignette suddenly stopped working in my setup, without having reinstalled/updated Rcpp itself.

**Comment by eddelbuettel** [comment]
@riccardoporreca Yes, that could probably do with stronger wording to discourage the old use.  And/or maybe even a new section with a tutorial along the lines you wrote here.  Feel like drafting a PR?

**Comment by riccardoporreca** [comment]
@eddelbuettel, I will try drafting something in the next couple of days for a PR.
