### ISSUE TITLE
compileAttributes not exporting functions unless they have a comment above

### ISSUE THREAD

**Issue by david-cortes** [RcppCore/Rcpp#978]
I have not been able to create a minimal reproducible example, and no longer have a copy of the file in which the problem was caused, but roughly speaking, I ran into the following problem:
* I define some functions that take a mixture of `SEXP` and `Rcpp::.*Vector` with `// [[Rcpp::export]]` in `/src` cpp files.
* Generate Rcpp files through `Rcpp::compileAttributes`.
* I set some of the (Rcpp objects') arguments in exported functions to be passed by reference (`&` - I know this is not needed with Rcpp vectors).
* After that, re-generate Rcpp files through `Rcpp::compileAttributes`.
* Existing Rcpp files are deleted and no new files are generated (not upon re-run of the command, nor on restart of the R session and further re-run). This is despite the fact that there are many Rcpp-exported functions which have no issues. All the files (`.o`) are compiled properly if I try to build the package, and if I inspect them, have the function symbols.
* After eliminating the offending ampersands from the exported functions that had them, `Rcpp::compileAttributes` generates files again, with exports for all the exported functions.

Would be nice if it could at least give me a warning or hint about why it's not generating the files.

**Comment by david-cortes** [comment]
Update: it seems the problem was not entirely related to the ampersands. It's actually something related to what's above the files. E.g. this will not export:
```cpp
// [[Rcpp::export]]
SEXP regurgitate_obj(SEXP obj)
{
    return obj;
}
```

But this will:
```cpp
/* Now I put a comment above */
SEXP regurgitate_obj(SEXP obj)
{
    return obj;
}
```

**Comment by eddelbuettel** [comment]
I take the other side of that bet:

### Code

```c++
#include <Rcpp.h>

// [[Rcpp::export]]
SEXP regurgitate_obj(SEXP obj)
{
    return obj;
}
```

### Output

```r
R> Rcpp::sourceCpp("/tmp/issue978.cpp")
R> regurgitate_obj(c(foo="bar", biz="bam"))
  foo   biz 
"bar" "bam" 
R>
```

**Comment by david-cortes** [comment]
@eddelbuettel : could you please run `compileAttributes` on this project that I'm attaching.

Particularly, in file `Rwrapper.cpp`, function `reconstruct_OutlierTree_if_needed` refuses to export, but if I add this above it, it will export:
```
/*	This is meant to be called from R every time the object needs to be used.
	Will first check if the pointer is still valid, and if not (e.g. after
	`readRDS`), will re-create it from the serialized raw vector. */
```

However if I add this, it will not:
```
/*	This is meant to be called from R every time the object needs to be used.
	Will first check if the pointer is still valid, and if not (e.g. after
	`readRDS`), will re-create it from the serialized raw vector.
	Do NOT remove this comment or otherwise Rcpp doesn't export it:
	https://github.com/RcppCore/Rcpp/issues/978 */
[example_unexported.tar.gz](https://github.com/RcppCore/Rcpp/files/3412724/example_unexported.tar.gz)

```

**Comment by eddelbuettel** [comment]
You seem to have a dot in the package name.  That works for R, but _not_ for Rcpp and `compileAttributes` as the package name ends in some identifiers and the dot is _not_ a valid indentifier.

This is documented, and came up before.  Sorry if confounded you.  Best bet is always to start from small working examples -- ie without a dot.

**Comment by david-cortes** [comment]
@eddelbuettel : But the name doesn't end in a dot. Also I think I've narrowed it down to comments having slashes inside.

So what causes the problem is having some comment with `/*  */` containing double slashes, such as this:
```cpp

#include <Rcpp.h>
using namespace Rcpp;

/*	This will introduce a problem
	https://github.com/RcppCore/Rcpp/issues/978 */
// [[Rcpp::export]]
List rcpp_hello_world() {

    CharacterVector x = CharacterVector::create( "foo", "bar" )  ;
    NumericVector y   = NumericVector::create( 0.0, 1.0 ) ;
    List z            = List::create( x, y ) ;

    return z ;
}
```

Code above doesn't export, but this does:
```cpp

#include <Rcpp.h>
using namespace Rcpp;

/*	This will introduce a problem
	https://github.com/RcppCore/Rcpp/issues/978 */
/* this fixes it */
// [[Rcpp::export]]
List rcpp_hello_world() {

    CharacterVector x = CharacterVector::create( "foo", "bar" )  ;
    NumericVector y   = NumericVector::create( 0.0, 1.0 ) ;
    List z            = List::create( x, y ) ;

    return z ;
}
```

The effect BTW extends further than the next function, so if I put a comment with `/* // */ three functions above, then all next functions in line will not be exported until there is a new comment without `//`.

**Comment by eddelbuettel** [comment]
Please read what I wrote.  "No dot in package names."

**Comment by david-cortes** [comment]
@eddelbuettel : ok, but that second `rcpp_hello_world` still doesn't export in a package named `hworld`.

**Comment by eddelbuettel** [comment]
In any event I don't time to teach you here one on one.  You example was *far* from being minimally reproducible (as it contained more than it needed, plus depends on other packages I may or may not have installed).  I do this for free on spare time so consider helping me help you.  Else you may have to wait for somebody else's free time.  Good luck.

**Comment by david-cortes** [comment]
@eddelbuettel : ok, sorry, will close this and create a new one with minimal reproducible example.
