### ISSUE TITLE
Using Rcpp::List method push_back on a ListOf<List> element will not actually push

### ISSUE THREAD

**Issue by david-cortes** [RcppCore/Rcpp#979]
Using `Rcpp::List` method `push_back` on an element of a `ListOf<List>` will not actually push to that element.

C++ code:
```cpp
ListOf<List> accessor_push(){
	ListOf<List> outp(3);
	outp[2].push_back(List(wrap(10.0)));
	return outp;
}
```
in R:
```r
library(Rcpp)
accessor_push = cppFunction("
ListOf<List> accessor_push(){
	ListOf<List> outp(3);
	outp[2].push_back(List(wrap(10.0)));
	return outp;
}
")
accessor_push()
```
````
[[1]]
list()

[[2]]
list()

[[3]]
list()
````

-----
Calling it on single elements:
C++ code:
```cpp
ListOf<List> push_with_assign(){
    ListOf<List> outp(3);
    List temp = outp[2];
    temp.push_back(List(wrap(10.0)));
    outp[2] = temp;
    return outp;
}
```
in R:
```r
library(Rcpp)
push_with_assign = cppFunction("
ListOf<List> push_with_assign(){
    ListOf<List> outp(3);
    List temp = outp[2];
    temp.push_back(List(wrap(10.0)));
    outp[2] = temp;
    return outp;
}
")
push_with_assign()
```
```
[[1]]
list()

[[2]]
list()

[[3]]
[[3]][[1]]
[[3]][[1]][[1]]
[1] 10
```

**Comment by eddelbuettel** [comment]
Consider reading the note entitled [Contributing](https://github.com/RcppCore/Rcpp/blob/master/Contributing.md) more carefully, and particular the hint on *reproducible examples*.  

We are all busy and do not have time to chase anecdata.  Thanks for your understanding -- but the above is neither minimal nor reproducible..

**Comment by david-cortes** [comment]
Sorry, updated.

**Comment by eddelbuettel** [comment]
I don't recally the reasons but it may just be that the semantics of `List` are incomplete.  Most code examples you see out there use the `Rcpp::List::create(...)` pattern to create once -- rather than grow.  

As you can just use `std::list` too (and convert before return) there was never too much urgency.  But clean PRs are always welcome.
