### ISSUE TITLE
Empty pairlist entries (argument lists)

### ISSUE THREAD

**Issue by flying-sheep** [RcppCore/Rcpp#986]
Getting the `formals` of a function results in pairlists with only named entries, but sometimes empty values:

```r
> formals(bquote)
$expr

$where
parent.frame()
> formals(bquote)[[1L]]

> str(formals(bquote)[[1L]])
symbol 
> as.character(formals(bquote)[[1L]])
""
```

Looks like this is the empty symbol, but I don’t seem to be able to construct it:

```r
> as.symbol('')
Error in as.symbol(""): attempt to use zero-length variable name
> Rcpp::evalCpp('Rcpp::Symbol("")')
Error in fun(): attempt to use zero-length variable name
```

How can I programmatically construct a pairlist with empty values like this?

**Comment by flying-sheep** [comment]
Found it:

The error comes from [`Rf_install`](https://github.com/wch/r-source/blob/e27687aa7fe42687907e318a7c8285275d361051/src/main/names.c#L1222). There’s an internal function `mkSYMSXP`, redefined to `Rf_mkSYMSXP` in the internal header [Defn.h](https://github.com/wch/r-source/blob/b6280636ca7425aef97938cf553da574cb82f9d8/src/include/Defn.h).

There seem to be a bunch of marker symbols, among them … `R_MissingArg`.

**Comment by eddelbuettel** [comment]
Right.  When I saw this (before I went out to run) I wondered what this could conceivably have to do with Rcpp.   Guess my hunch was correct...

**Comment by flying-sheep** [comment]
I don’t know the C API for pairlists and couldn’t find any example on how to construct an `Rcpp::Pairlist` with `Named("foo", R_MissingArg)`. Maybe we should add this as an example for #987.

**Comment by eddelbuettel** [comment]
Please stop debating base R APIs here.  We don't have the staff and bandwidth, and you know where to find the `r-devel` mailing list.

**Comment by eddelbuettel** [comment]
Also FWIW and IIRC the few times pair lists came up on the `r-devel` or alike lists, I do recall R Core members stating just about each and every time that they are either deprecated or not meant to be seen at the API.  Maybe try want you want to do with a simple list instead?
