### ISSUE TITLE
Rcpp::Function: add getter for formals and constructor from body and formals

### ISSUE THREAD

**Issue by flying-sheep** [RcppCore/Rcpp#987]
The setter `formals<-` creates a new function by passing the concatenation of the new `formals` and the old function’s body to `as.function`. Rcpp should offer an equivalent constructor.

```r
> `formals<-`
function (fun, envir = environment(fun), value) {
    if (!is.function(fun)) warning("'fun' is not a function")
    bd <- body(fun)
    as.function(c(value, if (is.null(bd) || is.list(bd)) list(bd) else bd), envir)
}
```

To easily retrieve the `formals` of an `Rcpp::Function`, we should also add a `formals()` method.

**Comment by eddelbuettel** [comment]
Why "should" Rcpp do that?

**Comment by flying-sheep** [comment]
I think those are two simple building blocks to reflect what R functions are: A `Pairlist` representing the signature and a `Language` object representing the body.

Functions are pretty fundamental to R, so properly reflecting them isn’t super exotic.

Finally, correct me if I’m wrong, but an extension wouldn’t be possible as there’s no public API to get the internal R function object, so once someone has an `Rcpp::Function` there’s no way to get the SEXP, right?

**Comment by eddelbuettel** [comment]
I cannot parse your last paragraph.  Which you now deleted. Gaaa.

See my other comment about pair lists.  The absense of public API _appears to be intentional_ on the part of R Core.  So no API, hence no Rcpp accessor to API.

**Comment by flying-sheep** [comment]
Pairlists are and will always be what `formals` returns and accepts. They aren’t what people should use in any “normal” data science code, but when dealing with function signatures they have to be dealt with. Rcpp already supports pairlists very well (there’s even a generated ctor construction API, that’s some effort right there). What Rcpp doesn’t support well yet is the programmatic construction and introspection of R functions.

**Comment by flying-sheep** [comment]
Yo, this is still and issue, and as I said part of the official way R works:

> ### [**formals**](https://stat.ethz.ch/R-manual/R-devel/library/base/html/formals.html) {base}
>
> #### Description
> 
> Get or set the formal arguments of a function. 
> 
> […]
> 
> #### Value
> 
> formals returns the formal argument list of the function specified, as a pairlist, or NULL for a non-function or primitive. 
> 
> […]

**Comment by eddelbuettel** [comment]
Are you offering to do work on this?  It would appear nobody else is.  Only saying "yo" is actually not changing anything.

I am going closing this now as nothing has happened here in some time, which the bot correctly identified.  You are free to reopen it if you have a concrete proposal.

**Comment by flying-sheep** [comment]
I was commenting on the facts that

1. you claimed an “absense of public API” but [R disagrees](https://cran.r-project.org/doc/manuals/r-release/R-lang.html#Function-objects):

   > In this document we generally use the term ‘function’, but use ‘closure’ to emphasize the importance of the attached environment.
   > 
   > It is possible to extract and manipulate the three parts of a closure object using **`formals`**, `body`, and `environment` constructs (all three can also be used on the left hand side of assignments). The last of these can be used to remove unwanted environment capture. 

   (emphasis mine)

   With the documentation of [`formals`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/formals.html) being as above. Therefore `pairlist`s are the official interface to retrieve a function’s arguments.

2. the feature request is still valid. If you have an official policy in which you close feature requests unless there’s someone interested in working on them, I apologize, but can’t see that anywhere.

**Comment by eddelbuettel** [comment]
You appear to be under assumption that everything that is possible in R ought to be double in Rcpp.   What gave you that idea?

**Comment by flying-sheep** [comment]
> What gave you that idea?

The second and third sentences of the synopsis:

> All underlying R types and objects, i.e., everything a SEXP represents internally in R, are matched to corresponding C++ objects. This covers anything from vectors, matrices or lists to environments, **functions** and more.

Without all of `formals`, `body`, and `environment`, your class doesn’t fully represent R functions.

> This is a volunteer project and we get to choose what we work on

Sure, I maintain enough projects to know exactly what you’re talking about.

I responded here because you still seemed to be under the impression that `formals` is not part of the official R API, and wanted to clarify that, and because I didn’t know what your feature request policy is.

I wanted to be helpful that way. I don’t feel like that’s the way you received it, but as said: As a fellow maintainer, I get it.

**Comment by eddelbuettel** [comment]
If you want to count beans, there are (IIRC) 27 different values in the bitmap for a `SEXP`.  Not even R itself considers all public.  A good handful one are key, and we mapped those from day one.  A few others are helpful and present here (say, the environment class) buy already used by way fewer projects (two orders of magnitude).  If you think you need to noodle on function formals and bodies, you are free to write yourself help functions, and we even offer to review them here if they seem relevant for Rcpp.  No more, no less, and no harm done.  Thanks for your understanding.
