### ISSUE TITLE
warning compiled code

### ISSUE THREAD

**Issue by larssk** [RcppCore/Rcpp#989]
We're using Rcpp for our bio3d package. On newer Fedora distribs running R-3.6.0 I noticed a new warning when checking (e.g. with `devtools::check(cran=TRUE)`): 

```
W  checking compiled code ...
   File 'rcpptest/libs/rcpptest.so':
     Found 'abort', possibly from 'abort' (C)
       Object: 'RcppExports.o', 
     Found 'printf', possibly from 'printf' (C)
       Object: 'RcppExports.o'
```

This was originally noticed after receiving an email from B. Ripley on Stan Headers warnings. When trying to reproduce what he reported I ran into these warnings. After failing to identify the origin I set up a new empty R package (using Rstudio) linking to Rcpp and a simple function, this warning is still present, pointing to Rcpp as the origin ? 

```
 setting  value                       
 version  R version 3.6.0 (2019-04-26)
 os       Fedora 30 (Container Image) 
 system   x86_64, linux-gnu           
 ui       X11                         
 language (EN)                        
 collate  C                           
 ctype    C                           
 tz       Etc/UTC                     
 date     2019-08-30         
```

```
 package     * version date       lib source                        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)                
 backports     1.1.4   2019-04-10 [1] CRAN (R 3.6.0)                
 callr         3.3.1   2019-07-18 [1] CRAN (R 3.6.0)                
 cli           1.1.0   2019-03-19 [1] CRAN (R 3.6.0)                
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)                
 desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.0)                
 devtools      2.1.0   2019-07-06 [1] CRAN (R 3.6.0)                
 digest        0.6.20  2019-07-04 [1] CRAN (R 3.6.0)                
 fs            1.3.1   2019-05-06 [1] CRAN (R 3.6.0)                
 glue          1.3.1   2019-03-12 [1] CRAN (R 3.6.0)                
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.0)                
 memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.0)                
 pkgbuild      1.0.5   2019-08-26 [1] CRAN (R 3.6.0)                
 pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.0)                
 prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.6.0)                
 processx      3.4.1   2019-07-18 [1] CRAN (R 3.6.0)                
 ps            1.3.0   2018-12-21 [1] CRAN (R 3.6.0)                
 R6            2.4.0   2019-02-14 [1] CRAN (R 3.6.0)                
 Rcpp          1.0.2.1 2019-08-30 [1] Github (RcppCore/Rcpp@1789f09)
 remotes       2.1.0   2019-06-24 [1] CRAN (R 3.6.0)                
 rlang         0.4.0   2019-06-25 [1] CRAN (R 3.6.0)                
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.0)                
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.0)                
 testthat      2.2.1   2019-07-25 [1] CRAN (R 3.6.0)                
 usethis       1.5.1   2019-07-04 [1] CRAN (R 3.6.0)                
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.0)       
```

**Comment by coatless** [comment]
It isn't. I would double check your code w.r.t `printf()` and `abort()` usage. The `RcppExports.{cpp,o}` is a red herring here. 

Are you wrapping an external library?

**Comment by eddelbuettel** [comment]
Sure, please see the [_Writing R Extensions_ Manual, Section 6.5](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Printing) about using R facilities for printing.  IIRC the language used to be stronger.

But in essence this comes from _your_ code and yes, I too as a package author have had to edit out / alter such uses _e.g._ by replace `printf` with `Rprintf` and `std::cout` with `Rcpp::Rcout`.

**Comment by kevinushey** [comment]
See also: https://stat.ethz.ch/pipermail/r-package-devel/2018q2/002752.html

You likely need to modify the default compilation options used by `gcc` on Fedora.

**Comment by eddelbuettel** [comment]
Oh, wow, forgot/missed that one.  Ugly,  Kevin is likely right -- appears to be local to Fedora (and R).  Rcpp is not adding further gas onto the fire.

**Comment by larssk** [comment]
Thanks for the tip Kevin. Seems that the system is overriding that CXXFLAG in Makevars:

```
Variables overriding user/site settings:
    CXXFLAGS: -U_GLIBCXX_ASSERTIONS
```

> But in essence this comes from your code and yes, 

Sorry for not making it clear enough- but it's not from my code. I used the following sample code from Rstudio to reproduce the warning:

```
#include <Rcpp.h>
using namespace Rcpp;
// [[Rcpp::export]]
NumericVector timesTwo(NumericVector x) {
  return x * 2;
}
```

**Comment by eddelbuettel** [comment]
We shot from the hip and got it wrong.  The issue is still local to your Fedora box (and all similar Fedora boxen that do not undefine `_GLIBCXX_ASSERTIONS` as suggested in Inaki's email referenced by Kevin.  You can convince yourself of that by submitting  the package to, say, builder.r-hub.io and pick a different OS -- or run one of its Fedora build images which will likely not show the issue either.
