### ISSUE TITLE
use exported R API when removing variables from environment

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/Rcpp#990]
From a recent R-devel post:

> Thanks for spotting this pattern. Using Rf_defineVar() this way to 
> delete a variable from package code is wrong because WRE does not 
> describe such behavior. That behavior has not been intended by the 
> implementation and as you observe, the variable will not be properly 
> deleted.
> 
> I found another pattern in another package (Rcpp, Rcpp11) which calls 
> directly the .Internal() function that deletes a variable, that is also 
> wrong, one should only use exported wrappers. The only legitimate way to 
> delete a variable in already released versions of R from C is to use 
> eval() to call R's rm()/remove(), but we will consider adding a C 
> function to the API to do this directly.

And the code:

https://github.com/RcppCore/Rcpp/blob/d04eae80562c8933a484d095309af3b47bc041f8/inst/include/Rcpp/Environment.h#L245-L252

We're already calling back to R; might as well use the official function `base::rm`.

**Comment by eddelbuettel** [comment]
Thanks.  I follow r-devel pretty closely but missed this. [ Turns out I was behind on that folder.  Busy day. ]  Well and we know how the OP "really" feels about Rcpp, don't we ;-)
