### ISSUE TITLE
Performance of list of vectors

### ISSUE THREAD

**Issue by notEvil** [RcppCore/Rcpp#991]
Hi,

I have a function which returns a list of many integer vectors, like

    // [[Rcpp::export]]
    List test(Function const& cat) {
        cat("a");
        std::vector<IntegerVector> v;
        for (int i = 0; i < 100000; i++) {
            v.push_back(IntegerVector());
        }
        cat("b");
        List result = List::import(v.begin(), v.end());
        cat("c");
        return result;
    }

This one takes >30s which is weird because I expect it to be trivial. The profile says that 99% of time is spent in Rf_pmatch, therefore it might not be Rcpp's fault. Still, how can this be done efficiently?

I can rewrite it to return two integer vectors instead and reassemble the list in R, but it feels unnecessary.

**Comment by eddelbuettel** [comment]
Try

```
    List result = List::create(Named("v") = v);
```

instead.

**Comment by eddelbuettel** [comment]
See any decent text on performance -- for example @csgillespie on _Efficient R Programming_ -- and this is *always* one of the key tips.  Neither the R interpreter, nor the C++ compiler can read your mind.  So be explicit.

Also, if you use `Rcpp::IntegerVector v` then you save one copy at the end.
