### ISSUE TITLE
Empty Range

### ISSUE THREAD

**Issue by const-ae** [RcppCore/Rcpp#992]
Hi, first of all thank you very much for developing `Rcpp`, it makes dealing with native code so much easier.

I recently ran into problem that the the `Range` object must all always contain [at least one](http://dirk.eddelbuettel.com/code/rcpp/html/Range_8h_source.html#l00031) element. This is similar to the way that R's `seq(from, to)` function works. Unfortunately, this makes it impossible to create an empty Range.

Here, is some example code that behaves gives me the expected result:

``` r
library(Rcpp)

Rcpp::cppFunction('
    double subset_sum(NumericVector x, int start, int end){
      if(start < 0 || end > x.size() || end < start) {
        throw std::range_error("Start or end value invalid");
      }
      if(start == end){
        return sum(NumericVector(0));
      }else{
        return sum(x[Range(start, end-1)]);
      }
    }
')


vec <- 1:10
subset_sum(vec, 4, 8)
#> [1] 26
subset_sum(vec, 4, 5)
#> [1] 5
subset_sum(vec, 4, 4)
#> [1] 0
subset_sum(vec, 4, 3)
#> Error in subset_sum(vec, 4, 3): Start or end value invalid
```

<sup>Created on 2019-09-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

And this is the code that I would like to write. As you can see it breaks on the edge case that the range would be empty:

``` r
library(Rcpp)

Rcpp::cppFunction('
    double subset_sum2(NumericVector x, int start, int end){
      if(start < 0 || end > x.size() || end < start) {
        throw std::range_error("Start or end value invalid");
      }
      return sum(x[Range(start, end-1)]);
    }
')


vec <- 1:10
subset_sum2(vec, 4, 8)
#> [1] 26
subset_sum2(vec, 4, 5)
#> [1] 5
subset_sum2(vec, 4, 4)
#> Error in subset_sum2(vec, 4, 4): upper value must be greater than lower value
subset_sum2(vec, 4, 3)
#> Error in subset_sum2(vec, 4, 3): Start or end value invalid
```

<sup>Created on 2019-09-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I realize that for this simple example, the first `subset_sum()` works just fine, but when I would want to generalize this pattern for different aggregation functions (`sum()`, `prod()`, `cumsum()` etc.), I would need to specify the super class of `NumericVector::Indexer`and `NumericVector`, which I couldn't figure out.

**Comment by nathanieljblack** [comment]
Rather than adjusting Range, can't you use the STL (i.e. `std::accumulate`)?

```
// [[Rcpp::export]]
double subset_sum2(NumericVector x, int start, int end){
    if(start < 0 || end > x.size() || end < start) {
         throw std::range_error("Start or end value invalid");
    }
    return std::accumulate(x.begin() + start, x.begin() + end, 0.0);
 }
```

Changing this to `prod` could easily be done like this...

```
// [[Rcpp::export]]
double subset_prod(NumericVector x, int start, int end){
  if(start < 0 || end > x.size() || end < start) {
    throw std::range_error("Start or end value invalid");
  }
  return std::accumulate(x.begin() + start, x.begin() + end, 1, std::multiplies<int>());
}
```

**Comment by const-ae** [comment]
Hi nathanieljblack,
thank you for your suggestion. Indeed, I did end up using STL (eg. https://github.com/const-ae/sparseMatrixStats/blob/master/src/methods.cpp#L179), however I would have found it convenient if `Rcpp` would have offered a way to get an empty `Range` so I didn't need to re-invent the wheel.
Best, Constantin
