### ISSUE TITLE
Attribute for generating R_unload_<pkgname>()

### ISSUE THREAD

**Issue by nbenn** [RcppCore/Rcpp#996]
I was looking for an attribute to generate the unload-analog of `void R_init_<pkgname>(DllInfo *info)`, but I couldn't find anything. Was I not thorough enough?

Since fairly recently (404e1ef612e5db74b5ebb8ba7585fa0eb1248087), the `[[Rcpp::init]]` attribute was added, I was wondering whether it might also be convenient to have something like `[[Rcpp::unload]]`?

At the same time, I guess it's no big deal to do this manually, so if you see no need for this, feel free to close again. However if there is some interest, I'm happy to implement something like @jjallaire's `[[Rcpp::init]]`.

**Comment by eddelbuettel** [comment]
The consensus is that you cannot cleanly and fully unload.  

So I just run tests in fresh sessions spawned at the command-line.  I would recommend you do the same.  If you insinst on trying to unload, then `devtools` aka `usethis` have some tools.  Rcpp is unlikely to add to this.

**Comment by nbenn** [comment]
I'm sorry, I might be a bit slow here, but I don't fully understand what you're saying.

If I add a function `void R_unload_<pkgname>(DllInfo*)` to a package, what do you mean by

> The consensus is that you cannot cleanly and fully unload.

Do you mean that there is no guarantee that `R_unload_<pkgname>()` is actually run under all possible circumstances?

**Comment by nbenn** [comment]
Thanks. I guess this means the current implementation of package unloading is a bit buggy and therefore Rcpp discourages the use of `R_unload_<pkgname>()` altogether.

I'm sorry for being a bit pedantic. I'm just trying to understand your reasoning.

**Comment by eddelbuettel** [comment]
It would be nice if dynamic libraries behaved more consistently in general and across OSs but it is what it is.

A related problem is that Rcpp is also used as an intermediating layer so we may have dependencies above us we do not know about.  Unloading seems nice in theory, in practice at least some of us prefer to just stick with launching well-defined processes and maybe just terminate those when done.

**Comment by nbenn** [comment]
Works for me. Thanks!
