### ISSUE TITLE
Warnings when specialise as<>

### ISSUE THREAD

**Issue by stephematician** [RcppCore/Rcpp#999]
I'm trying to extend Rcpp using a specialisation of as<> in a package. No matter what I try it seems like I always get this warning when I try to compile the dll (via, say, pkgbuild)

    ...R/R-3.6.1/library/Rcpp/include/Rcpp/protection/Armor.h:38:23: warning: inline function 'Rcpp::Armor<T>& Rcpp::Armor<T>::operator=(const U&) [with U = SEXPREC*; T = SEXPREC*]' used but never defined.

Attached zip:
[apackage.zip](https://github.com/RcppCore/Rcpp/files/3722782/apackage.zip)

 To help reproduce the error if needed - here's what I've got inside a stripped down example package called `apackage`, with a class `shallow_vector` that holds the pointer to numeric data.
- the declaration of `shallow_vector` is in (header filer) `inst/include/apackage/vector.h`,
- the definitions of its members are in (source file) `src/vector.cpp`,
- forward declaration for Rcpp is assisted by (header file) `src/apackage_types.h` which gets included by RcppExports.cpp automatically
- a to-be-exported function that takes in `shallow_vector` as an argument is in `src/do_nothing.cpp`

Now the contents of the files; `inst/include/apackage/vector.h`:

```cxx
#ifndef APACKAGE_VECTOR_H
#define APACKAGE_VECTOR_H

#include <RcppCommon.h>

struct shallow_vector {

    public:

        shallow_vector(double *, const size_t);

    private:
        double * shallow_data;
        const size_t size;

};

namespace Rcpp {

/* Define specialisation to allow conversion */
template <> shallow_vector as(SEXP x);

}

#endif
```

Source file; `src/vector.cpp`:

```cxx
#include "apackage/vector.h"

shallow_vector::shallow_vector(double * data_, const size_t size_) :
    shallow_data(data_), size(size_) { }

/* is it bad to put this in its own translation unit? _shrugs_ */
namespace Rcpp {

template <>
shallow_vector as(SEXP x) {

    if (!Rf_isReal(x)) Rcpp::stop("shallow_vector only supports double (real)");

    R_xlen_t n = XLENGTH(x);
    return shallow_vector(REAL(x), n);

}

}
```

The forward declarations; `src/apackage_types.h`:

```cxx
#ifndef APACKAGE_TYPES_H
#define APACKAGE_TYPES_H

#include "apackage/vector.h"

#endif
```

And then the exported function which just returns a dummy; `src/do_nothing.cpp`:

```cxx
// [[Rcpp::plugins("cpp11")]]

#include "apackage/vector.h"

#include <Rcpp.h>

//' @export
// [[Rcpp::export]]
Rcpp::NumericVector return_one(shallow_vector x) {

    Rcpp::NumericVector A(1);

    return A;

}
```

FWIW my sessionInfo (when using `pkgbuild::compile_dll()`)

    R version 3.6.1 (2019-07-05)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 10 x64 (build 17134)

    Matrix products: default

    locale:
    [1] LC_COLLATE=English_United States.1252 
    [2] LC_CTYPE=English_United States.1252   
    [3] LC_MONETARY=English_United States.1252
    [4] LC_NUMERIC=C                          
    [5] LC_TIME=English_United States.1252    

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    loaded via a namespace (and not attached):
     [1] processx_3.4.1    compiler_3.6.1    backports_1.1.4   magrittr_1.5     
     [5] assertthat_0.2.1  R6_2.4.0          rprojroot_1.3-2   cli_1.1.0        
     [9] prettyunits_1.0.2 tools_3.6.1       withr_2.1.2       crayon_1.3.4     
    [13] Rcpp_1.0.2        desc_1.2.0        callr_3.3.2       ps_1.3.0         
    [17] pkgbuild_1.0.5

**Comment by eddelbuettel** [comment]
Something went haywire with your code quote there:

```
[...]
    public:
[apackage.zip](https://github.com/RcppCore/Rcpp/files/3722778/apackage.zip)
[apackage.zip](https://github.com/RcppCore/Rcpp/files/3722779/apackage.zip)
[apackage.zip](https://github.com/RcppCore/Rcpp/files/3722780/apackage.zip)

        shallow_vector(double *, const size_t);
[...]
```

Assuming that was not what you meant, can you edit?

Also, I never ever saw that warning.  Given that your Sys.info() reveals windoze with the ancient g++-4.9.3, can you by chance try somewhere else (Docker? rhub?) with a newer g++ ?

**Comment by stephematician** [comment]
> Something went haywire with your code quote there:
> 
> ```
> [...]
>     public:
> [apackage.zip](https://github.com/RcppCore/Rcpp/files/3722778/apackage.zip)
> [apackage.zip](https://github.com/RcppCore/Rcpp/files/3722779/apackage.zip)
> [apackage.zip](https://github.com/RcppCore/Rcpp/files/3722780/apackage.zip)
> 
>         shallow_vector(double *, const size_t);
> [...]
> ```
> 
> Assuming that was not what you meant, can you edit?
> 
> Also, I never ever saw that warning. Given that your Sys.info() reveals windoze with the ancient g++-4.9.3, can you by chance try somewhere else (Docker? rhub?) with a newer g++ ?

Already fixed - i was trying to upload a zipped example and didn't notice where it went

**Comment by eddelbuettel** [comment]
_Ah, Windoze, how I hate thee:_

```
RcppExports.cpp:4:10: fatal error: Apackage_types.h: No such file or directory
 #include "Apackage_types.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [/usr/lib/R/etc/Makeconf:176: RcppExports.o] Error 1
```

Friends don't let friends works on OSs that do not reflect case.

**Comment by stephematician** [comment]
> can you by chance try somewhere else (Docker? rhub?) with a newer g++ ?

I'll give rhub a go - didn't realise it existed, thanks for the tip.

**Comment by eddelbuettel** [comment]
There are _lots_ of errors

- `apackage` != `Apackage` -- figure out what you want
- `src/Makevars.in` but no `configure` --  so make it `src/Makevars`
- `NAMESPACE` wants to load `forecastRcpp` but that is not what we are here

Maybe use a package creation helper next time?

**Comment by eddelbuettel** [comment]
After all that it installs for me.  Ubuntu 19.04.  I email you the zipfile, charge you the hourly rate of zero and we close this.  Deal?

**Comment by stephematician** [comment]
> There are _lots_ of errors
> 
> * `apackage` != `Apackage` -- figure out what you want
> * `src/Makevars.in` but no `configure` --  so make it `src/Makevars`
> * `NAMESPACE` wants to load `forecastRcpp` but that is not what we are here
> 
> Maybe use a package creation helper next time?

This is what happens when you try and cut down another package instead of starting from scratch, I found the same problems (Rcpp::compileAttributes on Windoze capitalised the first letter without my consent)

**Comment by stephematician** [comment]
gcc 5.4 also gave me a warning (courtesy of rhub's ubuntu 16.04 - the first one i tried). Is it because the translation unit that contains the definition of the specialisation has to include "Rcpp.h" after?

**Comment by eddelbuettel** [comment]
I have no idea. I live in the year 2019, so why would I handcuff myself to Ubuntu 16.04 from three years ago?  Why bother with g++-5.* when I can have 9.*?

Then again Rcpp has not changed all that much so ...   <shrug>.  And we keep compatibility with older tools (within reason) as a goal so Windows should work.   But then again your draft package had a few, ahem, issues, so I would want to make sure you have all ironed out.  

Anyway, coming up to night time here so I'll leave to explore all the other options.  And if in doubt, presue CRAN.  We have 1813 reverse dependencies of Rcpp on CRAN, and they generally work without nasty warnings.  GitHub allows you to search too (hint: `user:cran`).

**Comment by stephematician** [comment]
I leave this here for future reference if anyone else tries to specialise as<> in a similar way: __The answer is exactly that "Rcpp.h" has to be included in the translation unit (read: source file) that contains the template _definition_ (not declaration). Compiler/OS is irrelevant__

**Comment by eddelbuettel** [comment]
If that is missing from the appropriate documentation (vignette, say) let me know, and we'll add it.  Otherwise it sounds like something ... probably not new and somewhat given.
